### ISSUE TITLE
After upgrading logstash continously restarting logstash

### ISSUE THREAD

**Issue by sharathmankala** [elastic/logstash#10807] opened 2019-05-21 09:53 UTC
After installing latest version logstash 7.0.1 i am getting below error.
I don't have any idea.
Kindly help us.

**[2019-05-21T09:50:48,872][DEBUG][logstash.outputs.elasticsearch] Running health check to see if an Elasticsearch connection is working {:healthcheck_url=>http://logstash:xxxxxx@x.x.x.x:9200/, :path=>"/"}
[2019-05-21T09:50:48,887][WARN ][logstash.outputs.elasticsearch] Restored connection to ES instance {:url=>"http://logstash:xxxxxx@x.x.x.x:9200/"}
[2019-05-21T09:50:48,895][INFO ][logstash.outputs.elasticsearch] ES Output version determined {:es_version=>7}
[2019-05-21T09:50:48,895][WARN ][logstash.outputs.elasticsearch] Detected a 6.x and above cluster: the `type` event field won't be used to determine the document _type {:es_version=>7}
[2019-05-21T09:50:48,899][INFO ][logstash.outputs.elasticsearch] New Elasticsearch output {:class=>"LogStash::Outputs::ElasticSearch", :hosts=>["//x.x.x.x:9200"]}
[2019-05-21T09:50:48,899][DEBUG][logstash.outputs.elasticsearch] Normalizing http path {:path=>nil, :normalized=>nil}
[2019-05-21T09:50:48,902][INFO ][logstash.outputs.elasticsearch] Elasticsearch pool URLs updated {:changes=>{:removed=>[], :added=>[http://logstash:xxxxxx@x.x.x.x:9200/]}}
[2019-05-21T09:50:48,903][DEBUG][logstash.outputs.elasticsearch] Running health check to see if an Elasticsearch connection is working {:healthcheck_url=>http://logstash:xxxxxx@x.x.x.x:9200/, :path=>"/"}
[2019-05-21T09:50:48,903][ERROR][org.logstash.Logstash    ] java.lang.IllegalStateException: Logstash stopped processing because of an error: (SystemExit) exit
[2019-05-21T09:50:48,910][WARN ][logstash.outputs.elasticsearch] Restored connection to ES instance {:url=>"http://logstash:xxxxxx@x.x.x.x:9200/"}
**

[root@NY1LENVELK01 logstash]# cat /etc/*release
CentOS Linux release 7.5.1804 (Core) 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

CentOS Linux release 7.5.1804 (Core) 
CentOS Linux release 7.5.1804 (Core) 
[root@NY1LENVELK01 logstash]# 

[root@NY1LENVELK01 logstash]# rpm -qa|grep logs
logstash-7.0.1-1.noarch
[root@NY1LENVELK01 logstash]#

[root@NY1LENVELK01 logstash]# cat /etc/logstash/logstash.yml|grep -v "#"
path.data: /var/lib/logstash
path.config: /etc/logstash/conf.d/*.conf

log.level: trace
path.logs: /var/log/logstash
[root@NY1LENVELK01 logstash]#

**Comment by danhermann** [comment] 2019-05-31 18:05
Since this is a general usage question and not a reproducible bug report or a feature request, I am closing this issue.

>Please post all product and debugging questions on our forum.
>Your questions will reach our wider community members there, and if we confirm that there is a bug, then we can open a new issue here.
>
>-- Logstash Issue Template

In nearly all cases, the cause of the exception logged on this line `[2019-05-21T09:50:48,903][ERROR][org.logstash.Logstash ] java.lang.IllegalStateException: Logstash stopped processing because of an error: (SystemExit) exit` will be logged in more detail a couple seconds earlier in the `logstash-plain.log` file. Please open a thread on the [forum](https://discuss.elastic.co/c/logstash) if you need additional assistance.

**Closed by danhermann** 2019-05-31 18:05 UTC
