### ISSUE TITLE
Error Encoding Event: LocalJumpError: unexpected next

### ISSUE THREAD

**Issue by AlexClineBB** [elastic/logstash#5029] opened 2016-04-06 01:46 UTC
I'm running into an issue during an upgrade from logstash 1.4.2 to 2.2.3. Using the following simple logstash configuration, every event triggers the following error:

```
input {
  file {
    path => [ "/mnt/log/syslogs/*/*/*/*/nginx/*.access.log" ]
    type => "nginx_access_log"
  }
}

output {
  if [type] == "nginx_access_log" or [type] == "nginx_error_log" {
    redis {
      host => "redisserver.example.com"
      key => "logstash"
    }
  }
}
```

```
{:timestamp=>"2016-04-06T01:19:16.469000+0000", :message=>"Error encoding event", :exception=>#<LocalJumpError: unexpected next>, :event=>#<LogStash::Event:0x2e01f568 @metadata={"path"=>"/mnt/log/syslogs/2016/04/06/mesos-hybrid-use1b-prod-ex-90/nginx/example.m.access.log"}, @accessors=#<LogStash::Util::Accessors:0x6c6ed60a @store={"message"=>"Apr  6 01:19:09 mesos-hybrid-use1b-prod-ex-90 example_m_access 80.12.96.117 - - [06/Apr/2016:01:19:09 +0000] \"GET /akamai/sureroute-test-object.html HTTP/1.1\" 303 200 \"-\" \"-\" 0.210 0.210 - - m.example.com - - BYPASS \"example.m.dbbf8cd3-f81a-11e5-af74-0a6988c82749\" 303", "@version"=>"1", "@timestamp"=>"2016-04-06T01:19:15.377Z", "path"=>"/mnt/log/syslogs/2016/04/06/mesos-hybrid-use1b-prod-ex-90/nginx/example.m.access.log", "host"=>"logs.example.com", "type"=>"nginx_access_log", "tags"=>["inf2"]}, @lut={"path"=>[{"message"=>"Apr  6 01:19:09 mesos-hybrid-use1b-prod-ex-90 example_m_access 80.12.96.117 - - [06/Apr/2016:01:19:09 +0000] \"GET /akamai/sureroute-test-object.html HTTP/1.1\" 303 200 \"-\" \"-\" 0.210 0.210 - - m.example.com - - BYPASS \"example.m.dbbf8cd3-f81a-11e5-af74-0a6988c82749\" 303", "@version"=>"1", "@timestamp"=>"2016-04-06T01:19:15.377Z", "path"=>"/mnt/log/syslogs/2016/04/06/mesos-hybrid-use1b-prod-ex-90/nginx/example.m.access.log", "host"=>"logs.example.com", "type"=>"nginx_access_log", "tags"=>["inf2"]}, "path"], "host"=>[{"message"=>"Apr  6 01:19:09 mesos-hybrid-use1b-prod-ex-90 example_m_access 80.12.96.117 - - [06/Apr/2016:01:19:09 +0000] \"GET /akamai/sureroute-test-object.html HTTP/1.1\" 303 200 \"-\" \"-\" 0.210 0.210 - - m.example.com - - BYPASS \"example.m.dbbf8cd3-f81a-11e5-af74-0a6988c82749\" 303", "@version"=>"1", "@timestamp"=>"2016-04-06T01:19:15.377Z", "path"=>"/mnt/log/syslogs/2016/04/06/mesos-hybrid-use1b-prod-ex-90/nginx/example.m.access.log", "host"=>"logs.example.com", "type"=>"nginx_access_log", "tags"=>["inf2"]}, "host"], "type"=>[{"message"=>"Apr  6 01:19:09 mesos-hybrid-use1b-prod-ex-90 example_m_access 80.12.96.117 - - [06/Apr/2016:01:19:09 +0000] \"GET /akamai/sureroute-test-object.html HTTP/1.1\" 303 200 \"-\" \"-\" 0.210 0.210 - - m.example.com - - BYPASS \"example.m.dbbf8cd3-f81a-11e5-af74-0a6988c82749\" 303", "@version"=>"1", "@timestamp"=>"2016-04-06T01:19:15.377Z", "path"=>"/mnt/log/syslogs/2016/04/06/mesos-hybrid-use1b-prod-ex-90/nginx/example.m.access.log", "host"=>"logs.example.com", "type"=>"nginx_access_log", "tags"=>["inf2"]}, "type"], "tags"=>[{"message"=>"Apr  6 01:19:09 mesos-hybrid-use1b-prod-ex-90 example_m_access 80.12.96.117 - - [06/Apr/2016:01:19:09 +0000] \"GET /akamai/sureroute-test-object.html HTTP/1.1\" 303 200 \"-\" \"-\" 0.210 0.210 - - m.example.com - - BYPASS \"example.m.dbbf8cd3-f81a-11e5-af74-0a6988c82749\" 303", "@version"=>"1", "@timestamp"=>"2016-04-06T01:19:15.377Z", "path"=>"/mnt/log/syslogs/2016/04/06/mesos-hybrid-use1b-prod-ex-90/nginx/example.m.access.log", "host"=>"logs.example.com", "type"=>"nginx_access_log", "tags"=>["inf2"]}, "tags"], "[type]"=>[{"message"=>"Apr  6 01:19:09 mesos-hybrid-use1b-prod-ex-90 example_m_access 80.12.96.117 - - [06/Apr/2016:01:19:09 +0000] \"GET /akamai/sureroute-test-object.html HTTP/1.1\" 303 200 \"-\" \"-\" 0.210 0.210 - - m.example.com - - BYPASS \"example.m.dbbf8cd3-f81a-11e5-af74-0a6988c82749\" 303", "@version"=>"1", "@timestamp"=>"2016-04-06T01:19:15.377Z", "path"=>"/mnt/log/syslogs/2016/04/06/mesos-hybrid-use1b-prod-ex-90/nginx/example.m.access.log", "host"=>"logs.example.com", "type"=>"nginx_access_log", "tags"=>["inf2"]}, "type"], "[tags]"=>[{"message"=>"Apr  6 01:19:09 mesos-hybrid-use1b-prod-ex-90 example_m_access 80.12.96.117 - - [06/Apr/2016:01:19:09 +0000] \"GET /akamai/sureroute-test-object.html HTTP/1.1\" 303 200 \"-\" \"-\" 0.210 0.210 - - m.example.com - - BYPASS \"example.m.dbbf8cd3-f81a-11e5-af74-0a6988c82749\" 303", "@version"=>"1", "@timestamp"=>"2016-04-06T01:19:15.377Z", "path"=>"/mnt/log/syslogs/2016/04/06/mesos-hybrid-use1b-prod-ex-90/nginx/example.m.access.log", "host"=>"logs.example.com", "type"=>"nginx_access_log", "tags"=>["inf2"]}, "tags"]}>, @data={"message"=>"Apr  6 01:19:09 mesos-hybrid-use1b-prod-ex-90 example_m_access 80.12.96.117 - - [06/Apr/2016:01:19:09 +0000] \"GET /akamai/sureroute-test-object.html HTTP/1.1\" 303 200 \"-\" \"-\" 0.210 0.210 - - m.example.com - - BYPASS \"example.m.dbbf8cd3-f81a-11e5-af74-0a6988c82749\" 303", "@version"=>"1", "@timestamp"=>"2016-04-06T01:19:15.377Z", "path"=>"/mnt/log/syslogs/2016/04/06/mesos-hybrid-use1b-prod-ex-90/nginx/example.m.access.log", "host"=>"logs.example.com", "type"=>"nginx_access_log", "tags"=>["inf2"]}, @metadata_accessors=#<LogStash::Util::Accessors:0x27085a7 @store={"path"=>"/mnt/log/syslogs/2016/04/06/mesos-hybrid-use1b-prod-ex-90/nginx/example.m.access.log"}, @lut={"[path]"=>[{"path"=>"/mnt/log/syslogs/2016/04/06/mesos-hybrid-use1b-prod-ex-90/nginx/example.m.access.log"}, "path"]}>, @cancelled=false>, :level=>:warn}
```

The event that triggered the above error is this one:

```
Apr  6 01:19:09 mesos-hybrid-use1b-prod-dsg-90 example_m_access 80.12.96.117 - - [06/Apr/2016:01:19:09 +0000] "GET /akamai/sureroute-test-object.html HTTP/1.1" 303 200 "-" "-" 0.210 0.210 - - m.example.com - - BYPASS "example.m.dbbf8cd3-f81a-11e5-af74-0a6988c82749" 303
```

The same configuration works correctly in version 1.4.2. I used the .deb download of 2.2.3 from the elastic.co website.

```
/opt/logstash/bin/logstash --version
logstash 2.2.3
```

Searching on Google for the above error message doesn't reveal any information.

**Comment by purbon** [comment] 2016-04-06 09:26
There is the same error at https://github.com/logstash-plugins/logstash-output-redis/issues/26, could you please move your message there so we have all in one place? that would be awesome!

we try to keep all issues in their plugins and this belongs to the redis output :+1:

**Comment by andrewvc** [comment] 2016-04-06 14:49
Closing this issue as a dupe of https://github.com/logstash-plugins/logstash-output-redis/issues/26

**Closed by andrewvc** 2016-04-06 14:49 UTC

**Comment by AlexClineBB** [comment] 2016-04-06 15:22
Thanks for the quick response. I guess Google hasn't caught up with the recent github issues for these projects.
