### ISSUE TITLE
Logstash Bug With Geoip

### ISSUE THREAD

**Issue by SkytheK** [elastic/logstash#13049] opened 2021-07-05 11:08 UTC
I have logstash working but when I want to create different geoip to be able to visualize it in the "Point to Point" map it only shows me 1 correct one and in the feedback that logstash gives me back it does not show me that the geolocation of the second geoip is done correctly, it only performs twice the geolocation to the same ip when they are different one of origin and the other one of destination. 

Code: 
```
input {
    file {
        path => "/var/log/snort/alert_fast.txt"
        start_position => "beginning"
    }
}

filter {
  dissect { mapping => { "message" =>  '%{ts} [%{fd1}] [%{fd2}] "%{alert}" [%{ip_dest}] [%{ip_orig}:'} } 
  geoip { source => "ip_orig" target => "orig" }
  geoip { source => "ip_dest" target => "dest" }
}

output {
    elasticsearch {
        hosts => "http://10.200.0.29:9200"
        index => "logstash-snort3a"
    }
    stdout { codec => rubydebug }
}
```

Feedback:
```
logstash         | {
logstash         |        "ip_orig" => "142.250.184.5",
logstash         |       "priority" => "0",
logstash         |           "dest" => {
logstash         |               "latitude" => 37.751,
logstash         |               "location" => {
logstash         |             "lon" => -97.822,
logstash         |             "lat" => 37.751
logstash         |         },
logstash         |           "country_name" => "United States",
logstash         |         "continent_code" => "NA",
logstash         |          "country_code2" => "US",
logstash         |              "longitude" => -97.822,
logstash         |          "country_code3" => "US",
logstash         |                     "ip" => "185.199.111.153",
logstash         |               "timezone" => "America/Chicago"
logstash         |     },
logstash         |       "@version" => "1",
logstash         |        "ip_dest" => "185.199.111.153",
logstash         |           "path" => "/var/log/snort/alert_fast.txt",
logstash         |           "host" => "e751afb4966b",
logstash         |          "alert" => "NMAP ping sweep Scan",
logstash         |       "protocol" => "TCP",
logstash         |             "ts" => "07/05-11:11:58.488925",
logstash         |      "port_dest" => "55398",
logstash         |        "service" => "HTTPS",
logstash         |        "message" => "07/05-11:11:58.488925 [**] [1:10000004:1] \"NMAP ping sweep Scan\" [**] [Priority: 0] [AppID: HTTPS] {TCP} 142.250.184.5:443 -> 185.199.111.153:55398",
logstash         |      "port_orig" => "443",
logstash         |           "orig" => {
logstash         |               "latitude" => 37.751,
logstash         |               "location" => {
logstash         |             "lon" => -97.822,
logstash         |             "lat" => 37.751
logstash         |         },
logstash         |           "country_name" => "United States",
logstash         |         "continent_code" => "NA",
logstash         |          "country_code2" => "US",
logstash         |              "longitude" => -97.822,
logstash         |          "country_code3" => "US",
logstash         |                     "ip" => "142.250.184.5",
logstash         |               "timezone" => "America/Chicago"
logstash         |     },
logstash         |     "@timestamp" => 2021-07-05T10:20:10.431Z
logstash         | }
```

**Comment by yaauie** [comment] 2021-07-06 15:34
It appears to be working as designed. The result contains an `orig` that maps to the IP from `ip_orig` _(NOTE: enriched `[orig][ip]` matches top-level `ip_orig` field — both are `142.250.184.5`)_:

> ~~~
> "ip_orig" => "142.250.184.5"
> ~~~
> 
> ~~~
> "orig" => {
>           "latitude" => 37.751,
>           "location" => {
>                 "lon" => -97.822,
>                 "lat" => 37.751
>             },
>       "country_name" => "United States",
>     "continent_code" => "NA",
>      "country_code2" => "US",
>          "longitude" => -97.822,
>      "country_code3" => "US",
>                 "ip" => "142.250.184.5",
>           "timezone" => "America/Chicago"
> },
> ~~~

And also contains a `dest` that maps to the IP from `ip_dest` (NOTE: enriched `[dest][ip]` matches top-level `ip_dest` field — both are `185.199.111.153`):

> ~~~
>         "ip_dest" => "185.199.111.153",
> ~~~
> ~~~
> "dest" => {
>           "latitude" => 37.751,
>           "location" => {
>                  "lon" => -97.822,
>                  "lat" => 37.751
>            },
>       "country_name" => "United States",
>     "continent_code" => "NA",
>      "country_code2" => "US",
>          "longitude" => -97.822,
>      "country_code3" => "US",
>                 "ip" => "185.199.111.153",
>           "timezone" => "America/Chicago"
> },
> ~~~

It is likely that the GeoIP database you are using resolves both IPs to the same point. The free-tier GeoIP databases that are bundled with the Logstash GeoIP Filter are less precise than the paid databases available from Maxmind, so it's possible that a higher-precision database would resolve these as merely being close to each other instead of identical. Either way though, it looks like we are correctly doing two lookups and storing the results.

***

I am closing this issue because Logstash core isn't the right place to open bugs on individual plugins.

> Logstash Plugins are located in a different organization: [logstash-plugins](https://github.com/logstash-plugins). For bugs on specific Logstash plugins, for example, if Redis Output has a defect, please open it in the respective Redis Output repository.

If you have further issues, I would advise opening up [an issue with the GeoIP Filter plugin](https://github.com/logstash-plugins/logstash-filter-geoip/issues/new/choose)

**Closed by yaauie** 2021-07-06 15:34 UTC
Labels: bug, status:needs-triage
