### ISSUE TITLE
Doc: Kafka input default values are not coherent 

### ISSUE THREAD

**Issue by psanz-estc** [elastic/logstash#13069] opened 2021-07-13 10:10 UTC
This statement from kafka input documentation is not aligned with our default values:

```
The value of the configuration request_timeout_ms must always be larger than max_poll_interval_ms
```

Default values:

[max_poll_interval_ms](https://www.elastic.co/guide/en/logstash/current/plugins-inputs-kafka.html#plugins-inputs-kafka-max_poll_interval_ms) -> Default value is 300000 milliseconds (5 minutes) 

[request_timeout_ms](https://www.elastic.co/guide/en/logstash/current/plugins-inputs-kafka.html#plugins-inputs-kafka-request_timeout_ms) -> Default value is 40000 milliseconds (40 seconds).

Following our default values, _request_timeout_ms_ is smaller than _max_poll_interval_ms_

Documentation should be fixed.

**Comment by robbavey** [comment] 2021-07-13 14:09
Closing as a dupe of [this issue](https://github.com/logstash-plugins/logstash-integration-kafka/issues/20) in the kafka plugin repo.

**Closed by robbavey** 2021-07-13 14:09 UTC
Labels: bug, docs, status:needs-triage
