### ISSUE TITLE
logstash api node/stats does not show valid values for process when running under windows

### ISSUE THREAD

**Issue by DWrightQA** [elastic/logstash#9272] opened 2018-03-21 16:37 UTC
When starting logstash on windows, the node stats api does not return a valid value for process. CPU usage for instance is set to -3%

- Version: 6.2.2
- Operating System: Windows 2012 R2
- Config File (if you have sensitive info, please remove it):

node.name: xxxxx
xpack.monitoring.enabled: true
xpack.monitoring.elasticsearch.url: xxxxx:9200

- Sample Data:

- Steps to Reproduce:

Start logstash on windows using ./bin/logstash.bat -f ./config/pipeline.conf
Run a GET request on localhost:9600/_node/stats/process?pretty

Expected Response:
~~~ json
{
  "host" : "xxxxx",
  "version" : "6.2.2",
  "http_address" : "xxxxxx:9600",
  "id" : "xxxxx",
  "name" : "xxxx",
  "process" : {
    "open_file_descriptors" : some_value,
    "peak_open_file_descriptors" : some_value,
    "max_file_descriptors" : some_value,
    "mem" : {
      "total_virtual_in_bytes" : some_value
    },
    "cpu" : {
      "total_in_millis" : some_value,
      "percent" : some_value,
      "load_average" : some_value
    }
  }
}
~~~

Actual Response:
~~~ json
{
  "host" : "xxxx",
  "version" : "6.2.2",
  "http_address" : "xxxxx:9600",
  "id" : "xxxxx",
  "name" : "xxxxx",
  "process" : {
    "open_file_descriptors" : -1,
    "peak_open_file_descriptors" : -1,
    "max_file_descriptors" : -1,
    "mem" : {
      "total_virtual_in_bytes" : -1
    },
    "cpu" : {
      "total_in_millis" : -1,
      "percent" : -3,
      "load_average" : 
    }
  }
}
~~~

**Comment by yaauie** [comment] 2018-03-22 19:45
Duplicate of https://github.com/elastic/logstash/issues/6653

**Closed by yaauie** 2018-03-22 19:45 UTC
