### ISSUE TITLE
Elasticsearch output plugin is using deprecated _retry_on_conflict

### ISSUE THREAD

**Issue by jguay** [elastic/logstash#9092] opened 2018-02-05 11:55 UTC
Elasticsearch deprecated logs contain the following entry for every bulk sent by logstash to ES 6.x 
```
[2018-02-05T11:04:55,636][WARN ][o.e.d.c.ParseField ] Deprecated field [_retry_on_conflict] used, expected [retry_on_conflict] instead
```
- Environment : Stack 6.1.3 - logstash-output-elasticsearch (9.0.2)
- Steps to Reproduce:

Add this conf and wait 10 seconds to start getting deprecated log entries
```
input {
  heartbeat {
    interval => 5
    message  => 'Hello from Logstash 💓'
  }
}

output {
  elasticsearch {
    action => 'update'
    document_id => '1'
    doc_as_upsert => true
  }
}
```

Background : If output is to ES 5.X then there will be no issue since "_retry_on_conflict" is the right setting. However when writing to ES 6.x this causes a lot of deprecated logs entries so better would be to use the new v6 setting

Workaround in case disk space issue is sparse would be to add a regex rule in log4j2.properties, this example is for standard docker ES
```
appender.console.filter.regex.type = RegexFilter
appender.console.filter.regex.onMatch = DENY
appender.console.filter.regex.regex = .*Deprecated field \[_retry_on_conflict\]  
used, expected \[retry_on_conflict\] instead$
appender.console.filter.regex.onMisMatch = ACCEPT
```

**Comment by rnaccache** [comment] 2018-03-09 14:27
I've noticed the exact same behavior, is there any updates regarding this besides Jguay's workaround?

**Comment by jsvd** [comment] 2018-04-04 14:10
closing as duplicate of https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/710

**Closed by jsvd** 2018-04-04 14:10 UTC
