### ISSUE TITLE
ES DLQ Rats Test is very Unstable

### ISSUE THREAD

**Issue by original-brownbear** [elastic/logstash#8142] opened 2017-09-05 18:13 UTC
This is happening in more than 50% of IT runs now ... https://travis-ci.org/elastic/logstash/jobs/272065977#L4133

will try to fix ...

**Comment by robbavey** [comment] 2017-09-05 18:13
@original-brownbear Feel free to assign this to me - I made it, so I can fix it

**Comment by original-brownbear** [comment] 2017-09-05 18:14
@robbavey enjoy :)

**Comment by original-brownbear** [comment] 2017-09-06 05:45
Seems better now with #8143 merged, closing :)

**Comment by original-brownbear** [comment] 2017-09-06 08:39
Still seeing this locally and just now on Travis (sorry no link I re-triggerd) (though at a lower rate now it seems)

**Comment by robbavey** [comment] 2017-09-06 13:31
Interesting error in one of the failed runs - 

```
Exception in thread "Ruby-0-Thread-10@[main]>worker0: :1" java.lang.IllegalArgumentException: Counters can not be incremented by negative values
	at org.logstash.instrument.metrics.counter.LongCounter.<clinit>(org/logstash/instrument/metrics/counter/LongCounter.java:15)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(java/lang/Class.java:348)
	at org.jruby.javasupport.JavaSupportImpl.loadJavaClass(org/jruby/javasupport/JavaSupportImpl.java:154)
	at org.jruby.javasupport.Java.getProxyClassOrNull(org/jruby/javasupport/Java.java:940)
	at org.jruby.javasupport.Java.getProxyClassOrNull(org/jruby/javasupport/Java.java:927)
	at org.jruby.javasupport.Java.getProxyOrPackageUnderPackage(org/jruby/javasupport/Java.java:885)
	at org.jruby.javasupport.JavaPackage.method_missing(org/jruby/javasupport/JavaPackage.java:259)
	at org.jruby.javasupport.JavaPackage$INVOKER$i$method_missing.call(org/jruby/javasupport/JavaPackage$INVOKER$i$method_missing.gen)
	at RUBY.<main>(:1)
	at org.jruby.Ruby.runInterpreter(org/jruby/Ruby.java:839)
	at org.jruby.Ruby.loadFile(org/jruby/Ruby.java:2876)
	at org.jruby.RubyKernel.requireCommon(org/jruby/RubyKernel.java:968)
	at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:961)
	at org.jruby.RubyKernel$INVOKER$s$1$0$require19.call(org/jruby/RubyKernel$INVOKER$s$1$0$require19.gen)
	at RUBY.<main>(:1)
	at org.jruby.Ruby.runInterpreter(org/jruby/Ruby.java:839)
	at org.jruby.Ruby.loadFile(org/jruby/Ruby.java:2876)
	at org.jruby.RubyKernel.requireCommon(org/jruby/RubyKernel.java:968)
	at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:961)
	at org.jruby.RubyKernel$INVOKER$s$1$0$require19.call(org/jruby/RubyKernel$INVOKER$s$1$0$require19.gen)
	at org.jruby.Ruby.runInterpreter(org/jruby/Ruby.java:839)
	at org.jruby.Ruby.loadFile(org/jruby/Ruby.java:2876)
	at org.jruby.RubyKernel.requireCommon(org/jruby/RubyKernel.java:968)
	at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:961)
	at org.jruby.RubyKernel$INVOKER$s$1$0$require19.call(org/jruby/RubyKernel$INVOKER$s$1$0$require19.gen)
	at org.jruby.Ruby.runInterpreter(org/jruby/Ruby.java:839)
	at org.jruby.Ruby.loadFile(org/jruby/Ruby.java:2876)
	at org.jruby.RubyKernel.requireCommon(org/jruby/RubyKernel.java:968)
	at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:961)
	at org.jruby.RubyKernel$INVOKER$s$1$0$require19.call(org/jruby/RubyKernel$INVOKER$s$1$0$require19.gen)
	at org.jruby.Ruby.runInterpreter(org/jruby/Ruby.java:839)
	at org.jruby.Ruby.loadFile(org/jruby/Ruby.java:2876)
	at org.jruby.RubyKernel.requireCommon(org/jruby/RubyKernel.java:968)
	at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:961)
	at org.jruby.RubyKernel$INVOKER$s$1$0$require19.call(org/jruby/RubyKernel$INVOKER$s$1$0$require19.gen)
	at org.jruby.Ruby.runInterpreter(org/jruby/Ruby.java:839)
	at org.jruby.Ruby.loadFile(org/jruby/Ruby.java:2876)
	at org.jruby.RubyKernel.requireCommon(org/jruby/RubyKernel.java:968)
	at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:961)
	at org.jruby.RubyKernel$INVOKER$s$1$0$require19.call(org/jruby/RubyKernel$INVOKER$s$1$0$require19.gen)
	at home.travis.build.elastic.logstash.build.logstash_minus_7_dot_0_dot_0_minus_alpha1_minus_SNAPSHOT.lib.bootstrap.environment.<main>(/home/travis/build/elastic/logstash/build/logstash-7.0.0-alpha1-SNAPSHOT/lib/bootstrap/environment.rb:70)
	at java.lang.invoke.MethodHandle.invokeWithArguments(java/lang/invoke/MethodHandle.java:627)
	at org.jruby.Ruby.runScript(org/jruby/Ruby.java:827)
	at org.jruby.Ruby.runNormally(org/jruby/Ruby.java:746)
	at org.jruby.Ruby.runNormally(org/jruby/Ruby.java:764)
	at org.jruby.Ruby.runFromMain(org/jruby/Ruby.java:577)
	at org.jruby.Main.doRunFromMain(org/jruby/Main.java:417)
	at org.jruby.Main.internalRun(org/jruby/Main.java:305)
	at org.jruby.Main.run(org/jruby/Main.java:232)
	at org.jruby.Main.main(org/jruby/Main.java:204)
```

**Comment by original-brownbear** [comment] 2017-09-06 13:51
@robbavey nah this is a an exception that our metrics throw internaly. Seems we're simply calling a metric increment with a negative argument somewhere :)

**Comment by robbavey** [comment] 2017-09-06 14:00
You sure about that? The stack trace seems to stem from the initialization of the static variable - 

```
at home.travis.build.elastic.logstash.build.logstash_minus_7_dot_0_dot_0_minus_alpha1_minus_SNAPSHOT.lib.bootstrap.environment.<main>(/home/travis/build/elastic/logstash/build/logstash-7.0.0-alpha1-SNAPSHOT/lib/bootstrap/environment.rb:70)
	```

(That line is `require ARGV.shift`)

**Comment by robbavey** [comment] 2017-09-06 14:06
@original-brownbear ^

**Comment by original-brownbear** [comment] 2017-09-06 14:38
@robbavey yes

```sh
Exception in thread "Ruby-0-Thread-10@[main]>worker0: :1" java.lang.IllegalArgumentException: Counters can not be incremented by negative values
	at org.logstash.instrument.metrics.counter.LongCounter.<clinit>(org/logstash/instrument/metrics/counter/LongCounter.java:15)
```

this is our code. The reason you're seeing such a weird stack-trace is that we invoke this thing via `send`.
That said, seems like the initialization of this class is broken since it's coming from a `require` call, should be easy to track down I think :)

**Comment by original-brownbear** [comment] 2017-09-06 14:56
@robbavey yea on second thought, this might be really hard to track down. Misread the stack trace :D This is just coming from some interpreter execution ... it seems close to impossible to read the exact origin of the call from the stack trace :(

**Comment by robbavey** [comment] 2017-09-06 15:00
@original-brownbear jruby stack traces != fun... I hope that this is a jruby 9k bug, but just in case, I'd be inclined to add more detail to the exception message - cc @jakelandis

**Comment by original-brownbear** [comment] 2017-09-06 15:01
@robbavey how could this be a JRuby bug, that would mean JRuby is altering the method argument somehow?

**Comment by robbavey** [comment] 2017-09-06 15:04
@original-brownbear More hope than expectation ;) - from the stack trace alone, IllegalArgumentException should not be thrown from there.

**Comment by original-brownbear** [comment] 2017-09-06 15:05
@robbavey well it's just this code in the "only-increment" counter:

```
    private static final IllegalArgumentException NEGATIVE_COUNT_EXCEPTION = new IllegalArgumentException("Counters can not be incremented by negative values");
```

```java
    /**
     * Optimized version of {@link #increment(Long)} to avoid auto-boxing.
     * @param by The value which to increment by. Can not be negative.
     */
    public void increment(long by) {
        if (by < 0) {
            throw NEGATIVE_COUNT_EXCEPTION;
        }
        longAdder.add(by);
    }
```

what's wrong with `IllegalArgumentException` here, a negative input is def. invalid :)

**Comment by robbavey** [comment] 2017-09-06 15:10
@original-brownbear Agreed on that... but there is nowhere in that stack trace where a metric is being incremented. So, there is a bug somewhere...

**Comment by robbavey** [comment] 2017-09-06 15:15
@original-brownbear ok, now I understand more - I suspect the issue is the static definition of the Exception -

https://stackoverflow. com/questions/15090664/is-it-safe-to-store-an-instance-of-an-exception-and-reuse-it

Going to log a separate bug to track the misleading error reporting

**Comment by original-brownbear** [comment] 2017-09-06 15:23
@robbavey nah this is intentional :) This path is so hot and already crazy nested, making this a `static` was the only thing small enough to not break inlining :)

**Comment by robbavey** [comment] 2017-09-06 15:38
@original-brownbear I've created #8153 to track this. It may be intentional, but this doesn't seem right as it stands

**Comment by original-brownbear** [comment] 2017-09-06 18:23
@robbavey Maybe it's coming from this:


```java
    public long writeEvent(byte[] eventArray) throws IOException {
        ByteBuffer eventBuffer = ByteBuffer.wrap(eventArray);
        RecordType nextType = null;
        ByteBuffer slice = eventBuffer.slice();
        long startPosition = channel.position();
        while (slice.hasRemaining()) {
            if (posInBlock + RECORD_HEADER_SIZE + 1 > BLOCK_SIZE) {
                channel.position((++currentBlockIdx) * BLOCK_SIZE + VERSION_SIZE);
                posInBlock = 0;
            }
            nextType = getNextType(slice, nextType);
            int originalLimit = slice.limit();
            int nextRecordSize = Math.min(remainingInBlock() - RECORD_HEADER_SIZE, slice.remaining());
            OptionalInt optTotalSize = (nextType == RecordType.START) ? OptionalInt.of(eventArray.length) : OptionalInt.empty();
            slice.limit(nextRecordSize);

            Checksum checksum = new CRC32();
            checksum.update(slice.array(), slice.arrayOffset() + slice.position(), nextRecordSize);
            posInBlock += writeRecordHeader(
                    new RecordHeader(nextType, nextRecordSize, optTotalSize, (int) checksum.getValue()));
            posInBlock += channel.write(slice);

            slice.limit(originalLimit);
            slice = slice.slice();
        }
        return channel.position() - startPosition;
    }
```

the number returned here will be used as an argument for `increment`. This looks kind of wrong no matter what (constantly seeking during append writes). Maybe there's a path through this thing (combined with other stuff going on in `RecordIOWriter` that could return negative here)?

**Comment by robbavey** [comment] 2017-09-06 18:31
@original-brownbear Unlikely - this class doesn't use the LongCounter, it is incrementing a LongAdder used internally...

**Comment by original-brownbear** [comment] 2017-09-06 18:33
@robbavey which then, in turn, has its value passed down to the `increment` call doesn't it? (maybe there is a weird condition here at startup?)

**Comment by robbavey** [comment] 2017-09-06 18:36
@original-brownbear the increment() call is on an instance of LongAdder. I don't think the LongCounter gets involved here.

I don't think this is happening at startup  - the confusion with the stack trace is that stack frames for an Exception get filled in at the first construction of a LongCounter, hence during the `require` method

**Comment by robbavey** [comment] 2017-09-06 18:36
@original-brownbear But there could be a path where increment gets called downstream on a bad call. Haven't found it yet, though

A good stack trace would be useful here ;)

**Comment by original-brownbear** [comment] 2017-09-07 16:57
@robbavey btw also started seeing this every now and then locally and on Travis:

```sh
  2) Test Dead Letter Queue using pipelines.yml with multiple pipelines behaves like it can send 1000 documents to and index from the dlq should index all documents
     Failure/Error: expect(result["hits"]["total"]).to eq(1000)
     
       expected: 1000
            got: 1002
     
       (compared using ==)
     Shared Example Group: "it can send 1000 documents to and index from the dlq" called from ./specs/dlq_spec.rb:89
     # ./specs/dlq_spec.rb:53:in `block in /home/travis/build/elastic/logstash/qa/integration/specs/dlq_spec.rb'
     # /home/travis/.rvm/gems/jruby-9.1.10.0/gems/stud-0.0.23/lib/stud/try.rb:79:in `block in try'
     # /home/travis/.rvm/gems/jruby-9.1.10.0/gems/stud-0.0.23/lib/stud/try.rb:95:in `block in try'
     # /home/travis/.rvm/gems/jruby-9.1.10.0/gems/stud-0.0.23/lib/stud/try.rb:91:in `try'
     # /home/travis/.rvm/gems/jruby-9.1.10.0/gems/stud-0.0.23/lib/stud/try.rb:123:in `try'
     # /home/travis/.rvm/gems/jruby-9.1.10.0/gems/logstash-devutils-1.3.3-java/lib/logstash/devutils/rspec/logstash_helpers.rb:18:in `try'
     # ./specs/dlq_spec.rb:51:in `block in (root)'
     # /home/travis/.rvm/gems/jruby-9.1.10.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block in (root)'
Finished in 32 minutes 39 seconds (files took 9.51 seconds to load)
35 examples, 2 failures
```

maybe we should turn that test off unless a fix is only hours away?

**Comment by robbavey** [comment] 2017-09-07 17:27
@original-brownbear Yeah, lets kill it for now. I'm working on it, and have a couple of leads, but I'll do a quick PR turning this off

**Comment by jakelandis** [comment] 2017-09-21 14:12
Caught another instance of this on PR based from master:

```
08:10:03 Failures:
08:10:03 
08:10:03   1) Test Dead Letter Queue using logstash.yml and separate config file behaves like it can send 1000 documents to and index from the dlq should index all documents
08:10:03      Failure/Error: expect(hits).to eq(1000)
08:10:03      
08:10:03        expected: 1000
08:10:03             got: 967
08:10:03      
08:10:03        (compared using ==)
08:10:03      Shared Example Group: "it can send 1000 documents to and index from the dlq" called from ./specs/dlq_spec.rb:125
08:10:03      # ./specs/dlq_spec.rb:57:in `block in /opt/logstash/qa/integration/specs/dlq_spec.rb'
08:10:03      # ./specs/dlq_spec.rb:49:in `block in (root)'
08:10:03 
08:10:03 Finished in 11 minutes 20 seconds (files took 3.67 seconds to load)
08:10:03 21 examples, 1 failure
08:10:03 
08:10:03 Failed examples:
08:10:03 
08:10:03 rspec './specs/dlq_spec.rb[1:2:1:1]' # Test Dead Letter Queue using logstash.yml and separate config file behaves like it can send 1000 documents to and index from the dlq should index all documents
08:10:03 
08:10:03 Randomized with seed 4672
```

**Comment by jakelandis** [comment] 2017-09-21 21:14
@robbavey - This seems to be the only problematic DLQ tests left. How did you want to proceed ?

**Comment by robbavey** [comment] 2017-09-22 13:27
@jakelandis I'll take a closer look at this, to check whether it is a test failure or an actual bug - the other test failures in here were actual Logstash bugs rather than test bugs, so I'd like to take a closer look to double check

**Comment by jsvd** [comment] 2017-10-04 09:50
@robbavey [another instance of this spec failure](https://logstash-ci.elastic.co/job/elastic+logstash+master+multijob-integration-1/61/console):


```
18:36:30 Failures:
18:36:30 
18:36:30   1) Test Dead Letter Queue using logstash.yml and separate config file behaves like it can send 1000 documents to and index from the dlq should index all documents
18:36:30      Failure/Error: expect(hits).to eq(1000)
18:36:30      
18:36:30        expected: 1000
18:36:30             got: 960
18:36:30      
18:36:30        (compared using ==)
18:36:30      Shared Example Group: "it can send 1000 documents to and index from the dlq" called from ./specs/dlq_spec.rb:125
18:36:30      # ./specs/dlq_spec.rb:57:in `block in /opt/logstash/qa/integration/specs/dlq_spec.rb'
18:36:30      # ./specs/dlq_spec.rb:49:in `block in (root)'
18:36:30 
18:36:30 Finished in 16 minutes 36 seconds (files took 7.33 seconds to load)
18:36:30 21 examples, 1 failure
18:36:30 
18:36:30 Failed examples:
18:36:30 
18:36:30 rspec './specs/dlq_spec.rb[1:2:1:1]' # Test Dead Letter Queue using logstash.yml and separate config file behaves like it can send 1000 documents to and index from the dlq should index all documents
18:36:30 
18:36:30 Randomized with seed 6198
```

**Comment by original-brownbear** [comment] 2017-10-04 10:04
@robbavey I'm also still seeing a few of these lately. Though as far as I can see, this became **a lot** less frequent on Jenkins than it was on Travis.
Maybe some freak timing/performance issue after all?

**Comment by original-brownbear** [comment] 2017-10-04 12:18
also, this stopped reproducing locally for me ... making a performance(ish) problem more likely I guess ...

**Comment by original-brownbear** [comment] 2017-10-04 12:23
nevermind, this is what Jenkins prints in the example @jsvd posted:

```sh
18:28:49 [ERROR] 2017-10-03 18:28:49.163 [[main]<dead_letter_queue] pipeline - A plugin had an unrecoverable error. Will restart this plugin.
18:28:49   Pipeline_id:main
18:28:49   Plugin: <LogStash::Inputs::DeadLetterQueue path=>"/tmp/studtmp-9f3f4c63eff2aa91d8194c36e007c822273e72eba29c2661079cf9b85a21", commit_offsets=>true, id=>"1a95d6fe517cc4236cd0c55a38d0f00bdc5dcf3ee011609001a1f7611c4e5c21", enable_metric=>true, codec=><LogStash::Codecs::Plain id=>"plain_5f4061fe-7ad1-4a5f-ab7c-0eed7d1bb7e6", enable_metric=>true, charset=>"UTF-8">, pipeline_id=>"main">
18:28:49   Error: invalid checksum of record
18:28:49   Exception: Java::JavaLang::RuntimeException
18:28:49   Stack: org.logstash.common.io.RecordIOReader.getRecord(org/logstash/common/io/RecordIOReader.java:217)
18:28:49 org.logstash.common.io.RecordIOReader.readEvent(org/logstash/common/io/RecordIOReader.java:233)
18:28:49 org.logstash.common.io.DeadLetterQueueReader.pollEntryBytes(org/logstash/common/io/DeadLetterQueueReader.java:120)
18:28:49 org.logstash.common.io.DeadLetterQueueReader.pollEntry(org/logstash/common/io/DeadLetterQueueReader.java:97)
18:28:49 org.logstash.input.DeadLetterQueueInputPlugin.run(org/logstash/input/DeadLetterQueueInputPlugin.java:82)
18:28:49 java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:498)
18:28:49 org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(org/jruby/javasupport/JavaMethod.java:423)
18:28:49 org.jruby.javasupport.JavaMethod.invokeDirect(org/jruby/javasupport/JavaMethod.java:290)
18:28:49 opt.logstash.build.logstash_minus_7_dot_0_dot_0_minus_alpha1_minus_SNAPSHOT.vendor.bundle.jruby.$2_dot_3_dot_0.gems.logstash_minus_input_minus_dead_letter_queue_minus_1_dot_1_dot_1.lib.logstash.inputs.dead_letter_queue.run(/opt/logstash/build/logstash-7.0.0-alpha1-SNAPSHOT/vendor/bundle/jruby/2.3.0/gems/logstash-input-dead_letter_queue-1.1.1/lib/logstash/inputs/dead_letter_queue.rb:60)
18:28:49 opt.logstash.build.logstash_minus_7_dot_0_dot_0_minus_alpha1_minus_SNAPSHOT.vendor.bundle.jruby.$2_dot_3_dot_0.gems.logstash_minus_input_minus_dead_letter_queue_minus_1_dot_1_dot_1.lib.logstash.inputs.dead_letter_queue.RUBY$method$run$0$__VARARGS__(opt/logstash/build/logstash_minus_7_dot_0_dot_0_minus_alpha1_minus_SNAPSHOT/vendor/bundle/jruby/$2_dot_3_dot_0/gems/logstash_minus_input_minus_dead_letter_queue_minus_1_dot_1_dot_1/lib/logstash/inputs//opt/logstash/build/logstash-7.0.0-alpha1-SNAPSHOT/vendor/bundle/jruby/2.3.0/gems/logstash-input-dead_letter_queue-1.1.1/lib/logstash/inputs/dead_letter_queue.rb)
18:28:49 opt.logstash.build.logstash_minus_7_dot_0_dot_0_minus_alpha1_minus_SNAPSHOT.logstash_minus_core.lib.logstash.pipeline.inputworker(/opt/logstash/build/logstash-7.0.0-alpha1-SNAPSHOT/logstash-core/lib/logstash/pipeline.rb:572)
18:28:49 
```

invalid checksum ...

**Comment by original-brownbear** [comment] 2017-10-04 13:13
https://logstash-ci.elastic.co/job/elastic+logstash+pull-request+multijob-integration-1/236/console another one also died with the invalid checksum error

**Comment by robbavey** [comment] 2017-10-04 13:16
@original-brownbear Thanks - this is my next focus after the support stint is up

**Comment by original-brownbear** [comment] 2017-10-04 16:44
@robbavey nice, I had some downtime today and looked into this a little. 
Check out https://github.com/elastic/logstash/pull/8432 it's not a fix (def. not, though unfortunately, it may make the system more stable making it harder to reproduce this issue) but:
I made the writing of crc32 and the data that belongs to it. So we should learn more about where this is happening by getting the broken Hash error out of the way on the writer side.
(if it still appears it's pretty likely the reader is at fault).
Will ping you there once I retriggered the build often enough to see the failure :D

**Comment by original-brownbear** [comment] 2017-10-05 12:56
Alright finally tracked down all the issue here:

### Missing Events (sometimes accompanied by checksum failures)

This one is easy to understand in hindsight. The DLQ reader starts reading a file as soon as the watch service notices it being created. Neither files nor events are atomically written.
Making events be written atomically, makes the failure a lot less likely and fixes checksum failures, it doesn't fix all cases though since we still wouldn't write a file containing multiple events atomically, making us miss events. This is more likely to happen on systems with fast `WatchService` implementations, less likely and close to impossible on Systems like OSX with very slow `WatchService` implementations

### Fix??

Not entirely trivial (imo) without changing the current approach. One quick-fix that comes to mind and should be safe on all systems is:

* DLQ writers write to `*.log.tmp` files
* DLQ writers move `*.log.tmp` files to `*.log` files on `close()`
=> a *.log file appearing to the `WatchService` will always be "complete" since `mv` is an atomic FS operation => issue fixed

Long term we should try to not have this kind of communication intra-JVM, there is no need to `poll` a set of files for writes from the same JVM. Note that in theory, it just doesn't make sense to `poll` here ever since the DLQ file lock prevents 2 different JVMs from concurrently accessing the same path anyways.

**Comment by robbavey** [comment] 2017-10-05 13:42
@original-brownbear Great work on this. 

One thing to note - 2 JVMs can concurrently access the same dead letter queue. The lock is only for the writer, so a Logstash instance with a dead_letter_queue reader, but with dead_letter queue functionality disabled or pointing to a different data directory, another JVM instance can read from the dlq.

The lock.tmp approach is interesting, we'd need to figure out what to do with infrequent writes, which I suspect may have been more expected during the design  - live with it, or flush after an inactivity period.

**Comment by original-brownbear** [comment] 2017-10-05 14:20
@robbavey ah damn ok :) yea then we need to decide between "live with it
 and flushing.

I think (even though it's a little more effort) we should have flushing:

*  If we don't flush we'll constantly have some number of events in limbo in a `*.tmp` file and will only be able to drain the whole queue when all files are "full". In practice this could lead to some annoying things if you want to use the DLQ for debugging problems and then are forced to restart LS to get those last 3 events from the Queue => doesn't feel right + seems like it will introduce a bunch of complicated/flaky test scenarios :D

I think we could simply implement flushing a file that has some data after `5s` (a low number is fine here imo, provided we only flush non-empty pages and only after a period of inactivity I can't see how this will lead to a million files created) of inactivity or so and be happy.

**Comment by robbavey** [comment] 2017-10-05 14:25
@original-brownbear +1 on that. Flushing makes sense here, and yeah,  5 seconds seems like a reasonable default here.

**Comment by original-brownbear** [comment] 2017-10-05 14:28
@robbavey alright :) you got time to code it up or should I look into this? (I think we should fix in a timely manner, flaky tests are annoying and it seems like a pretty major bug in production code)

**Comment by robbavey** [comment] 2017-10-05 14:30
@original-brownbear I was going to look into this anyway, and you've given me a massive head start ;), so I'll take this

**Comment by colinsurprenant** [comment] 2017-10-11 15:27
Another integration failure on for this
https://logstash-ci.elastic.co/job/elastic+logstash+master+multijob-integration-1/78/console

```
14:55:47   1) Test Dead Letter Queue using logstash.yml and separate config file behaves like it can send 1000 documents to and index from the dlq should index all documents
14:55:47      Failure/Error: expect(hits).to eq(1000)
14:55:47      
14:55:47        expected: 1000
14:55:47             got: 987
14:55:47      
14:55:47        (compared using ==)
14:55:47      Shared Example Group: "it can send 1000 documents to and index from the dlq" called from ./specs/dlq_spec.rb:125
14:55:47      # ./specs/dlq_spec.rb:57:in `block in /opt/logstash/qa/integration/specs/dlq_spec.rb'
14:55:47      # ./specs/dlq_spec.rb:49:in `block in (root)'
14:55:47 
14:55:47 Finished in 14 minutes 36 seconds (files took 5.71 seconds to load)
14:55:47 21 examples, 1 failure
14:55:47 
14:55:47 Failed examples:
14:55:47 
14:55:47 rspec './specs/dlq_spec.rb[1:2:1:1]' # Test Dead Letter Queue using logstash.yml and separate config file behaves like it can send 1000 documents to and index from the dlq should index all documents
14:55:47 
14:55:47 Randomized with seed 34243
```

**Comment by jsvd** [comment] 2017-11-07 13:50
Another instance of the same failure on https://logstash-ci.elastic.co/job/elastic+logstash+pull-request+multijob-integration-1/454/console

**Comment by danhermann** [comment] 2017-12-01 22:12
Another failure -- https://logstash-ci.elastic.co/job/elastic+logstash+pull-request/1973/console

**Comment by jordansissel** [comment] 2018-01-08 23:01
Possibly similar failure, but maybe not -- this one is connection refused, not a different count:

https://logstash-ci.elastic.co/job/elastic+logstash+6.1+multijob-integration-1/42/console

```
21:54:27   1) Test Dead Letter Queue using pipelines.yml with multiple pipelines behaves like it can send 1000 documents to and index from the dlq should index all documents
21:54:27      Got 0 failures and 2 other errors:
21:54:27      Shared Example Group: "it can send 1000 documents to and index from the dlq" called from ./specs/dlq_spec.rb:93
21:54:27 
21:54:27      1.1) Failure/Error: result = es_client.search(index: 'logstash-*', size: 0, q: '*')
21:54:27 
21:54:27           Faraday::ConnectionFailed:
21:54:27             Connection refused - Failed to open TCP connection to localhost:9200 (Connection refused - connect(2) for "localhost" port 9200)
```

**Comment by original-brownbear** [comment] 2018-01-16 10:59
@robbavey any news here, it's been a few months? :D

**Comment by robbavey** [comment] 2018-01-17 01:55
@original-brownbear Thanks for the reminder - this completely slipped my mind. I'll try and get to it shortly

**Comment by colinsurprenant** [comment] 2018-01-18 14:47
Another failure on 6.1 integration https://logstash-ci.elastic.co/job/elastic+logstash+6.1+multijob-integration-1/52/console

```
19:32:40   1) Test Dead Letter Queue using logstash.yml and separate config file behaves like it can send 1000 documents to and index from the dlq should index all documents
19:32:40      Failure/Error: expect(hits).to eq(1000)
19:32:40 
19:32:40        expected: 1000
19:32:40             got: 989
19:32:40 
19:32:40        (compared using ==)
19:32:40      Shared Example Group: "it can send 1000 documents to and index from the dlq" called from ./specs/dlq_spec.rb:125
19:32:40      # ./specs/dlq_spec.rb:57:in `block in /opt/logstash/qa/integration/specs/dlq_spec.rb'
19:32:40      # /opt/logstash/build/qa/integration/gems/gems/stud-0.0.23/lib/stud/try.rb:79:in `block in try'
19:32:40      # /opt/logstash/build/qa/integration/gems/gems/stud-0.0.23/lib/stud/try.rb:95:in `block in try'
19:32:40      # /opt/logstash/build/qa/integration/gems/gems/stud-0.0.23/lib/stud/try.rb:91:in `try'
19:32:40      # /opt/logstash/build/qa/integration/gems/gems/stud-0.0.23/lib/stud/try.rb:123:in `try'
19:32:40      # /opt/logstash/build/qa/integration/gems/gems/logstash-devutils-1.3.5-java/lib/logstash/devutils/rspec/logstash_helpers.rb:18:in `try'
19:32:40      # ./specs/dlq_spec.rb:49:in `block in (root)'
19:32:40      # /opt/logstash/build/qa/integration/gems/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block in (root)'
19:32:40 
19:32:40 Finished in 15 minutes 40 seconds (files took 3.91 seconds to load)
19:32:40 21 examples, 1 failure
19:32:40 
19:32:40 Failed examples:
19:32:40 
19:32:40 rspec './specs/dlq_spec.rb[1:2:1:1]' # Test Dead Letter Queue using logstash.yml and separate config file behaves like it can send 1000 documents to and index from the dlq should index all documents
19:32:40 
19:32:40 Randomized with seed 3814
```

**Comment by guyboertje** [comment] 2018-01-26 17:39
Another failure on master integration https://logstash-ci.elastic.co/job/elastic+logstash+master+multijob-integration-1/288/console
```
21:06:40   1) Test Dead Letter Queue using logstash.yml and separate config file behaves like it can send 1000 documents to and index from the dlq should index all documents
21:06:40      Failure/Error: expect(hits).to eq(1000)
21:06:40 
21:06:40        expected: 1000
21:06:40             got: 964
21:06:40 
21:06:40        (compared using ==)
21:06:40      Shared Example Group: "it can send 1000 documents to and index from the dlq" called from ./specs/dlq_spec.rb:125
21:06:40      # ./specs/dlq_spec.rb:57:in `block in /opt/logstash/qa/integration/specs/dlq_spec.rb'
```

**Comment by original-brownbear** [comment] 2018-01-26 18:18
@robbavey seriously, I can address this if you're busy :)

**Comment by robbavey** [comment] 2018-01-26 18:20
@original-brownbear Its next on my plate :)

**Comment by colinsurprenant** [comment] 2018-03-26 20:39
Got another one, https://logstash-ci.elastic.co/job/elastic+logstash+6.x+multijob-integration-1/40/console
```
20:21:42   1) Test Dead Letter Queue using logstash.yml and separate config file behaves like it can send 1000 documents to and index from the dlq should index all documents
20:21:42      Failure/Error: expect(hits).to eq(1000)
20:21:42 
20:21:42        expected: 1000
20:21:42             got: 0
20:21:42 
20:21:42        (compared using ==)
20:21:42      Shared Example Group: "it can send 1000 documents to and index from the dlq" called from ./specs/dlq_spec.rb:125
20:21:42      # ./specs/dlq_spec.rb:57:in `block in /opt/logstash/qa/integration/specs/dlq_spec.rb'
20:21:42      # /opt/logstash/build/qa/integration/vendor/jruby/2.3.0/gems/stud-0.0.23/lib/stud/try.rb:79:in `block in try'
20:21:42      # /opt/logstash/build/qa/integration/vendor/jruby/2.3.0/gems/stud-0.0.23/lib/stud/try.rb:95:in `block in try'
20:21:42      # /opt/logstash/build/qa/integration/vendor/jruby/2.3.0/gems/stud-0.0.23/lib/stud/try.rb:91:in `try'
20:21:42      # /opt/logstash/build/qa/integration/vendor/jruby/2.3.0/gems/stud-0.0.23/lib/stud/try.rb:123:in `try'
20:21:42      # /opt/logstash/build/qa/integration/vendor/jruby/2.3.0/gems/logstash-devutils-1.3.5-java/lib/logstash/devutils/rspec/logstash_helpers.rb:18:in `try'
20:21:42      # ./specs/dlq_spec.rb:49:in `block in /opt/logstash/qa/integration/specs/dlq_spec.rb'
20:21:42      # /opt/logstash/build/qa/integration/vendor/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block in /opt/logstash/build/qa/integration/vendor/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb'
20:21:42 
20:21:42   2) Test Dead Letter Queue using pipelines.yml with a single pipeline behaves like it can send 1000 documents to and index from the dlq should index all documents
20:21:42      Failure/Error: expect(hits).to eq(1000)
20:21:42 
20:21:42        expected: 1000
20:21:42             got: 0
20:21:42 
20:21:42        (compared using ==)
20:21:42      Shared Example Group: "it can send 1000 documents to and index from the dlq" called from ./specs/dlq_spec.rb:115
20:21:42      # ./specs/dlq_spec.rb:57:in `block in /opt/logstash/qa/integration/specs/dlq_spec.rb'
20:21:42      # /opt/logstash/build/qa/integration/vendor/jruby/2.3.0/gems/stud-0.0.23/lib/stud/try.rb:79:in `block in try'
20:21:42      # /opt/logstash/build/qa/integration/vendor/jruby/2.3.0/gems/stud-0.0.23/lib/stud/try.rb:95:in `block in try'
20:21:42      # /opt/logstash/build/qa/integration/vendor/jruby/2.3.0/gems/stud-0.0.23/lib/stud/try.rb:91:in `try'
20:21:42      # /opt/logstash/build/qa/integration/vendor/jruby/2.3.0/gems/stud-0.0.23/lib/stud/try.rb:123:in `try'
20:21:42      # /opt/logstash/build/qa/integration/vendor/jruby/2.3.0/gems/logstash-devutils-1.3.5-java/lib/logstash/devutils/rspec/logstash_helpers.rb:18:in `try'
20:21:42      # ./specs/dlq_spec.rb:49:in `block in /opt/logstash/qa/integration/specs/dlq_spec.rb'
20:21:42      # /opt/logstash/build/qa/integration/vendor/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block in /opt/logstash/build/qa/integration/vendor/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb'
20:21:42 
20:21:42 Finished in 22 minutes 1 second (files took 5.08 seconds to load)
20:21:42 22 examples, 2 failures
20:21:42 
20:21:42 Failed examples:
20:21:42 
20:21:42 rspec './specs/dlq_spec.rb[1:2:1:1]' # Test Dead Letter Queue using logstash.yml and separate config file behaves like it can send 1000 documents to and index from the dlq should index all documents
20:21:42 rspec './specs/dlq_spec.rb[1:1:2:1:1]' # Test Dead Letter Queue using pipelines.yml with a single pipeline behaves like it can send 1000 documents to and index from the dlq should index all documents
20:21:42 
20:21:42 Randomized with seed 58329
```

**Comment by original-brownbear** [comment] 2018-04-11 13:57
@robbavey any update here? If not, would you mind me handling this one?

**Comment by robbavey** [comment] 2018-04-11 14:00
@original-brownbear I have a commit to fix this that I need to dig up, rebase and finish testing. I can get to it this week

**Closed** 2021-04-01 17:27 UTC
Labels: DLQ, test failure
