### ISSUE TITLE
Conditional on boolean not working.

### ISSUE THREAD

**Issue by BarcoMasile** [elastic/logstash#9983] opened 2018-09-12 07:49 UTC
Hello there, I'm running logstash 6.4, on a PC with Windows 10 pro installed, but I have the same problem on a CentOS server.
I have a config file in which I copy in a new filed the content of an environment variable in a field (and assign a default value if it doesn't exist). The env var is either "true" or "false" . The new field is in the `@metadata` object, so it will be
~~~
[@metadata][drop_grokparsefailure]
[@metadata][drop_other_writers]
~~~

So this fields are now of type "string", and I use the mutate filter to convert them to a boolean type field.

Then I use those same fields in a conditional statement like this 
~~~
if [@metadata][drop_grokparsefailure] {  ...  }
~~~

and of course like this
~~~
if [@metadata][drop_other_writers] { .... }
~~~

My problem is that this doesn't work. Changing the value of the var (or the default value) doesn't change logstash behavior.

Keep in mind, the env variable is taken correctly and that part works, I don't get any error of sort.

extracts of the config file:

~~~
mutate {
   add_field => { "[@metadata][drop_grokparsefailure]" => "${DROP_GROKPARSEFAILURE:true}" }
   convert => { "[@metadata][drop_grokparsefailure]" => "boolean" }
}

if "_grokparsefailure" in [tags] {
            if [@metadata][drop_grokparsefailure] {
                drop {}
            }
}
~~~

I use the other field in the same way.

I'm starting to believe this is a bug, and I'd like to know what the community thinks, or if it's just me making a mistake somewhere. Thank you

PS: I don't think I can show you the entire config file, that's why I'm only posting the small extract. There's not even that much more to it, and this is the only way I use those fields in the config file. Thank you again

**Comment by yaauie** [comment] 2018-09-12 08:41
While you are giving the mutate filter both an `add_field` directive and a `convert` directive, they aren't being executed in the order you are expecting. This is by design, although I'm the first to admit that it is less than intuitive.

The `add_field` directive, available on most plugins, is part of event decoration that occurs on the successful completion of the plugin's other tasks. 

Effectively this means that we are converting an unset field and _then_ setting it to be a string.

When we get to the if statement, it is then determining the truthiness of the value, which is always a string, which is truthy since the only values that evaluate to false are the Boolean false or a missing value.

We could solve your use-case by testing directly against the environment variable, for equality with the string `"true"`:

~~~
if "_grokparsefailure" in [tags]{
  if "${DROP_GROKPARSEFAILURE:true}" == "true" {
    drop {}
  }
}
~~~

**Comment by yaauie** [comment] 2018-09-20 20:40
I am closing this issue because I believe my prior explanation provides enough help to get the user unstuck, and there has not been a response in more than a week.

Please feel free to re-open with further reproduction steps, or to tag me in a thread in our [forum](https://discuss.elastic.co/c/logstash) for further assistance.

**Closed by yaauie** 2018-09-20 20:40 UTC
