### ISSUE TITLE
6.0 branch still using namespaces in metrics

### ISSUE THREAD

**Issue by untergeek** [elastic/logstash#7994] opened 2017-08-14 19:04 UTC
When starting a pipeline I get a `wrong number of arguments for constructor` argument error:
```
$ bin/logstash --modules netflow --setup
Sending Logstash's logs to /Users/buh/WORK/logstash/logs which is now configured via log4j2.properties
[2017-08-14T12:41:41,508][INFO ][logstash.modules.scaffold] Initializing module {:module_name=>"fb_apache", :directory=>"/Users/buh/WORK/logstash/modules/fb_apache/configuration"}
[2017-08-14T12:41:41,511][INFO ][logstash.modules.scaffold] Initializing module {:module_name=>"netflow", :directory=>"/Users/buh/WORK/logstash/modules/netflow/configuration"}
[2017-08-14T12:41:41,558][WARN ][logstash.config.source.multilocal] Ignoring the 'pipelines.yml' file because modules or command line options are specified
[2017-08-14T12:41:41,651][FATAL][logstash.runner          ] An unexpected error occurred! {:error=>#<ArgumentError: wrong number of arguments for constructor>,
```

I do not see this error in the master or 6.x branches.  @jordansissel did the legwork and found that the 6.0 branch is still calling `super(namespaces, key.to_s)` while master and 6.x are calling `super(key.to_s)`:

## 6.x
```
% git blame 6.x -- logstash-core/lib/logstash/instrument/metric_type/counter.rb | sed -ne 8p
977dc84f (Jake Landis          2017-08-01 16:09:58 -0500  :sunglasses:       super(key.to_s)
```
## 6.0
```
% git blame 6.0 -- logstash-core/lib/logstash/instrument/metric_type/counter.rb | sed -ne 8p
17be8b09 (Jake Landis          2017-07-12 16:05:50 -0500  :sunglasses:       super(namespaces, key.to_s)
```
## master
```
% git blame master -- logstash-core/lib/logstash/instrument/metric_type/counter.rb | sed -ne 8p
fe7cd1fe (Jake Landis          2017-08-01 16:09:58 -0500  :sunglasses:       super(key.to_s)
```

Before arbitrarily changing this, I wanted to know _why_ this is not changed in 6.0

**Comment by robbavey** [comment] 2017-08-14 19:09
@untergeek Isn't this because the LongCounter ctr in 6.0 expects a namespace - https://github.com/elastic/logstash/blob/6.0/logstash-core/src/main/java/org/logstash/instrument/metrics/counter/LongCounter.java#L24, whereas in 6.x and master, that field has been removed? https://github.com/elastic/logstash/blob/6.x/logstash-core/src/main/java/org/logstash/instrument/metrics/counter/LongCounter.java#L25

**Comment by robbavey** [comment] 2017-08-14 19:10
Why there is a ```wrong number of arguments for constructor``` is more mysterious, however...

**Comment by andrewvc** [comment] 2017-08-14 19:16
@untergeek did you make sure to run a `rake compile:all` after switching branches?

**Comment by andrewvc** [comment] 2017-08-15 13:58
I confirmed that the `rake compile:all` was the issue. Closing.

**Closed by andrewvc** 2017-08-15 13:58 UTC
Labels: blocker
