### ISSUE TITLE
Configuration directive with preceeding whitespace in logstash.yml causes crash

### ISSUE THREAD

**Issue by rbw0** [elastic/logstash#6543] opened 2017-01-16 23:00 UTC
Hello,

- Version: 5.1.2
- Operating System: Ubuntu 15.10
- Steps to Reproduce:

Add a whitespace preceeding a directive, like:
" config.reload.automatic: true"

This causes Logstash to crash with the following obscure error in the syslog (/var/log/syslog in my case):
ERROR: Failed to load settings file from "path.settings". Aborting... path.setting=/etc/logstash, exception=Psych::SyntaxError, message=>(<unknown>): expected <block end>, but found BlockMappingStart while parsing a block mapping at line 77 column 2

Additionally, no logging is performed by logstash when this happens.

Regards,
Robert

**Comment by jsvd** [comment] 2017-01-17 09:30
+1 the error message needs to say upfront that we couldn't parse the yaml file

by the way, did you add a space character (ascii 20) or a tab (ascii 9)?
I tried reproducing this with a normal space and the yaml file was loaded correctly

**Comment by jsvd** [comment] 2017-01-17 10:16
closing as duplicate of https://github.com/elastic/logstash/issues/6509

**Closed by jsvd** 2017-01-17 10:16 UTC
