### ISSUE TITLE
Test failure: agent: killed thread

### ISSUE THREAD

**Issue by jordansissel** [elastic/logstash#7392] opened 2017-06-08 23:37 UTC
https://logstash-ci.elastic.co/job/elastic+logstash+feature-9000+dockerubuntu-periodic/58/console

```
  1) LogStash::Agent Agent execute options when `config.reload.automatic` is set to`FALSE` and successfully load the config converge only once
     Failure/Error: agent_task.stop!

     ThreadError:
       killed thread
     # ./vendor/bundle/jruby/2.3.0/gems/stud-0.0.22/lib/stud/interval.rb:44:in `stop!'
     # ./vendor/bundle/jruby/2.3.0/gems/stud-0.0.22/lib/stud/task.rb:52:in `stop!'
     # ./logstash-core/spec/logstash/agent/converge_spec.rb:113:in `block in (root)'
     # ./vendor/bundle/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block in /tmp/logstash/vendor/bundle/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb'
     # ./lib/bootstrap/rspec.rb:13:in `<main>'
```

**Comment by jakelandis** [comment] 2017-07-20 14:33
This should be fixed by : https://github.com/elastic/logstash/pull/7736/files#diff-f1f1ca81cad27ed4f3313abb14381739R458 

or possibly:
The fix for https://github.com/elastic/logstash/issues/7737 is applicable. 

Basically it appears that we have alot of race conditions in our tests that require retry logic and in the case of Agent shutdown can raise an exception in the stop.  I was not able to reproduce locally, but pretty sure the rescue in the stop will keep the test from failing. 

@jordansissel Mind if I close this ?  _Not sure how to get closer to resolution in the absence of reproducing it._

**Comment by jakelandis** [comment] 2017-09-21 21:35
Closing since we no longer have a periodic docker test, and this can not be reproduced.

**Closed by jakelandis** 2017-09-21 21:35 UTC
Labels: test failure
