### ISSUE TITLE
logstash stops infinity time

### ISSUE THREAD

**Issue by BjoernBe** [elastic/logstash#12344] opened 2020-10-14 15:16 UTC
We run Elasticsearch+Logstach+Kibana in Version 7.9 on the same machine running a Debian Buster.
We installed all components with apt using the official repository as in https://www.elastic.co/guide/en/logstash/7.9/installing-logstash.html

When we want to reboot it stops Elasticsearch BEFORE Logstach. This means logstash can't write the messages still in memory to elasticsearch.

We fixed that by adding to the Unit-File (/etc/systemd/system/logstash.service):
[Unit]
Requires=elasticsearch.service
After=elasticsearch.service

**Comment by kares** [comment] 2020-10-16 11:40
Thanks for the report, not really sure what the bug is about, could you please clarify?
If you need guidance for your specific scenario please try the [forums](https://discuss.elastic.co/) instead.

**Comment by BjoernBe** [comment] 2020-10-16 11:46
The bug is, that in the systemd-service in official packages distributed by the official repository a dependency on the systemd-service of elasticsearch is missing.

**Comment by chadek** [comment] 2021-02-19 09:27
Nice! I also had the issue and the workaround I used was changing `TimeoutStopSec=infinity` to `TimeoutStopSec=180`. Clearly not nice as I did not spot the root cause @BjoernBe describes here. I'll try your solution, thanks mate!
Be careful while using this workaround until it is definitely fix: `/etc/systemd/system/logstash.service` is replaced when you upgrade logstash. I recommend to write an override to avoid this issue: `/etc/systemd/system/logstash.service.d/override.conf`

**Comment by chadek** [comment] 2021-02-19 09:44
That being said, if we do as you are suggesting, logstash will never start if you intend to run it standalone in case you want to separate all this components. Maybe the best solution here is to define an override with your suggestion asking the user on first installation if he will intend to run all components on the same host.

**Comment by kares** [comment] 2021-07-14 14:48
Hey, thanks for the feedback - looking through the comments the issue is likely a "won't fix".

Logstash can operate without Elasticsearch and even when it does depend on Elasticsearch it's usually from a different host.
Logstash supports several outputs including Kafka, RabbitMQ, Redis - listing these as local system deps is not the way to go.

**Closed by kares** 2021-07-14 14:48 UTC

**Comment by chadek** [comment] 2021-07-15 09:39
@kares you want to document that somewhere as a warning then?

**Comment by chadek** [comment] 2021-07-15 09:42
@fdutheil that's what I ended to setup and I hadn't any trouble since
