### ISSUE TITLE
Logstash 6, java 8 not listening on ipv6

### ISSUE THREAD

**Issue by yakyNIIF** [elastic/logstash#8545] opened 2017-10-29 12:36 UTC
Dear all,

I have installed the logstash 6.0.0-rc1 version, but I have seen that the input port only listening on ipv4.
I have tried to extend the java_opts with the followings:
-Djava.net.preferIPv4Stack=false
-Djava.net.preferIPv6Addresses=true

but these aren't changing it.

The 'ps aux | grep logstash' output is:
root@logstash-teszt:/home/debian# ps aux | grep logstash
logstash 11888 91.0  5.8 3035156 120376 ?      SNsl 13:27   0:01 /usr/bin/java -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+DisableExplicitGC -Djava.net.preferIPv4Stack=false -Djava.net.preferIPv6Addresses=true -Djava.awt.headless=true -Dfile.encoding=UTF-8 -XX:+HeapDumpOnOutOfMemoryError -Xmx1g -Xms256m -Xss2048k -Djffi.boot.library.path=/usr/share/logstash/vendor/jruby/lib/jni -Xbootclasspath/a:/usr/share/logstash/vendor/jruby/lib/jruby.jar -classpath : -Djruby.home=/usr/share/logstash/vendor/jruby -Djruby.lib=/usr/share/logstash/vendor/jruby/lib -Djruby.script=jruby -Djruby.shell=/bin/sh org.jruby.Main /usr/share/logstash/lib/bootstrap/environment.rb logstash/runner.rb --path.settings /etc/logstash

netstat output:
root@logstash-teszt:/home/debian# netstat -alnp | grep 6666
udp        0      0 0.0.0.0:6666            0.0.0.0:*                           11888/java

Installed logstash version:
root@logstash-teszt:/home/debian# dpkg -l | grep logstash
ii  logstash                        1:6.0.0~rc1-1                  all          An extensible logging pipeline

Do you have any idea or have a chance to be repaired?

Thank you.

Best regards,
Janos BODOR

**Comment by jordansissel** [comment] 2017-10-30 16:29
I don't think we have enough information. Can you provide your Logstash configuration files?

**Comment by yakyNIIF** [comment] 2017-10-31 09:19
Hy,

Sorry, you are right.
Here is the configuration file of logstash with relevant lines:
----
node.name: logstash1
path.data: /var/lib/logstash
#path.config: /etc/logstash/conf.d
config.reload.automatic: true
path.logs: /var/log/logstash

Here is the jvm.options file:
-----
-Xms2g
-Xmx2g
-XX:+UseParNewGC
-XX:+UseConcMarkSweepGC
-XX:CMSInitiatingOccupancyFraction=75
-XX:+UseCMSInitiatingOccupancyOnly
-XX:+DisableExplicitGC
-Djava.net.preferIPv4Stack=false
-Djava.net.preferIPv6Addresses=true
-Djava.awt.headless=true
-Dfile.encoding=UTF-8
-XX:+HeapDumpOnOutOfMemoryError

Thank you.

**Comment by jsvd** [comment] 2022-03-10 11:15
Closing here as the issue is rather old and discussion stalled. Please open a new issue if you find yourself here.

**Closed by jsvd** 2022-03-10 11:15 UTC
