### ISSUE TITLE
Install plugin fails

### ISSUE THREAD

**Issue by CoryBond** [elastic/logstash#3367] opened 2015-06-02 21:30 UTC
Not sure if this issue is simular to issue: #3336 but.... when I attempt to install an example I created (its the same to example codec but names are different) plugin It says: 
"./plugin install /tmp/logstash-codec-logcat-0.1.1.gem
Validating /tmp/logstash-codec-logcat-0.1.1.gem
Installing logstash-codec-logcat
Installation successful"

but after looking for the plugin in my list of plugins I don't see it there and when I try to uninstall the plugin I get:
"./plugin uninstall /tmp/logstash-codec-logcat-0.1.1.gem
ERROR: Uninstall Aborted, message: This plugin has not been previously installed, aborting"

Is this because installing gave me false positive?

**Comment by purbon** [comment] 2015-06-03 17:26
This looks to me totally like #3336, but here I'm more concerned about you saying you don't the plugin in the output, this is strange. Can you provide more details so I can reproduce your behaviour myself?

**Comment by CoryBond** [comment] 2015-06-03 18:10
Hey purbon,

So my components are:
logstash vesion - 1.5.0
ruby - 2.2.2p95

I git pulled in codec example from the logstash plugin repository which contained DEVELOPER.md, LICENSE and README.md. My file structure follows that of the example tutorial here: https://www.elastic.co/guide/en/logstash/master/_how_to_write_a_logstash_codec_plugin.html.

The files I currently have are \logstash-codec-plugin-logcat\lib\logstash\codecs\logcat.rb:
"# encoding: utf-8
require "logstash/codecs/base"
require "logstash/codecs/line"

# Add any asciidoc formatted documentation here
class LogStash::Codecs::Logcat < LogStash::Codecs::Base

  # This example codec will append a string to the message field
  # of an event, either in the decoding or encoding methods
  #
  # This is only intended to be used as an example.
  #
  # input {
  #   stdin { codec => example }
  # }
  #
  # or
  #
  # output {
  #   stdout { codec => example }
  # }
  config_name "example"

  # Append a string to the message
  config :append, :validate => :string, :default => ', Hello World!'

  public
  def register
    @lines = LogStash::Codecs::Line.new
    @lines.charset = "UTF-8"
  end

  public
  def decode(data)
    @lines.decode(data) do |line|
      replace = { "message" => line["message"].to_s + @append }
      yield LogStash::Event.new(replace)
    end
  end # def decode

  public
  def encode(event)
    @on_event.call(event, event["message"].to_s + @append + NL)
  end # def encode

end # class LogStash::Codecs::Example"

logstash-codec-plugin-logcat\spec\codecs\Logcat_spec.rb which is basically a repeat of logcat.rb because I haven't taken time to change it yet.

and my gemspec at logstash-codec-plugin-logcat\logstash-codec-logcat:
"Gem::Specification.new do |s|
  s.name = 'logstash-codec-logcat'
  	s.version = '0.1.1'
  s.licenses = ['Apache License (2.0)']
  s.summary = "This codec does x, y, z in Logstash"
  s.description = "This gem is a logstash plugin required to be installed on top of the Logstash core pipeline using $LS_HOME/bin/plugin install gemname. This gem is not a stand-alone program"
  s.authors = ["cb86578"]
  s.email = 'cb.cobond@gmail.com'
  s.homepage = "http://www.elastic.co/guide/en/logstash/current/index.html"
  s.require_paths = ["lib"]

  # Files
  s.files = `git ls-files`.split($\)
   # Tests
  s.test_files = s.files.grep(%r{^(test|spec|features)/})

  # Special flag to let us know this is actually a logstash plugin
  s.metadata = { "logstash_plugin" => "true", "logstash_group" => "codec" }

  # Gem dependencies
  s.add_runtime_dependency 'logstash', '>= 1.4.0', '< 2.0.0'
  s.add_development_dependency 'logstash-devutils'
end"

I am unable to post my gem file here but it claims to install when I use the plugin script though it neither shows in the plugin list nor is compiliable in the logcat configurations when I try to do something like:
"
stdin{
codec => example
}
"

**Comment by CoryBond** [comment] 2015-06-25 17:00
Hello Again,

So for that plugin I was making I pretty much shelved it for the time being and moved on to other things..... however recently I have tried to install a new plugin "input-jms" from : https://github.com/logstash-plugins/logstash-input-jms and have been experiencing the same behavior like the ones I described in my previous posts.

The plugin says it validated the gem file and then installed it successfully.... but the plugin is nowhere to be found in the plugins list. I also can't use the plugin in my configuration file.

My components now are:
logstash vesion - 1.5.1 -tar.gz packaging
ruby - 2.2.2p95

The way I went about installing this plugin is simular to what I have done previously. I downloaded the source code from the website. Then I built the gem using this command "gem build logstash-input-jms.gemspec" within the the downloaded and unziped directory. The output I get is this: 

"$ gem build logstash-input-jms.gemspec
fatal: Not a git repository (or any parent up to mount point /cygdrive/c)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
WARNING:  open-ended dependency on logstash-codec-json (>= 0) is not recommended
  if logstash-codec-json is semantically versioned, use:
    add_runtime_dependency 'logstash-codec-json', '~> 0'
WARNING:  open-ended dependency on logstash-codec-plain (>= 0) is not recommended
  if logstash-codec-plain is semantically versioned, use:
    add_runtime_dependency 'logstash-codec-plain', '~> 0'
WARNING:  open-ended dependency on logstash-devutils (>= 0, development) is not recommended
  if logstash-devutils is semantically versioned, use:
    add_development_dependency 'logstash-devutils', '~> 0'
WARNING:  See http://guides.rubygems.org/specification-reference/ for help
  Successfully built RubyGem
  Name: logstash-input-jms
  Version: 0.1.0
  File: logstash-input-jms-0.1.0.gem"

I then move my gem from my local machine to the server where logstash is on and then use the command "./plugin install logstash-input-jms-0.1.0.gem" which ouputs:

"./plugin install ./logstash-input-jms-master/logstash-input-jms-master/logstash-input-jms-0.1.0.gem
Validating ./logstash-input-jms-master/logstash-input-jms-master/logstash-input-jms-0.1.0.gem
Installing logstash-input-jms
Installation successful"

I have not touched anything with the source code. I have also tried building the gem and moving it and all the source to the directory before installing but I see the same behavior.

I am believe gem files are generally cross compatible right? Right now I build the gem on a windows system and then move it to a linux system. Could that be a problem?

**Comment by purbon** [comment] 2015-06-29 10:35
Hi, sorry It took time for me to come back here, I apologies for that. I was reviewing your comments now and here are a couple of idea to check:

* Do you have internet on those servers you're trying to install the gems? If so, you can actually use ```bin/plugin install [plugin name] ``` and everything should work fine. Otherwise you need the plugin + the dependencies to be installed, so it gets tricky.
* How are you starting your LS instance ? are you doing just doing ```bin/logstash``` or you introduce some changes here?  I ask this because it looks like you try to run ```logstash``` with MRI, and this can be a source of issues.
* Building the plugins in windows, if using JRuby, should not be a problem. But in your case it looks to me you try to build with MRI, what for some plugins might trigger the wrong dependencies. I would recommend if you are ___stricktly___ forced to do it like this, you build them with cygwin and jruby.

Looking forward to know more about it.

/cheers

**Comment by CoryBond** [comment] 2015-06-29 15:33
Hello purbon,

So I work for company using this the ELK stack and the server team that regulates the server I try to install these on is picky about what things get through networks firewall. I was hoping to install these plugins easily by building them and then moving/installing them. In theory it should have worked.... in theory.

Yes I have been building these plugins with cygwin and its version of ruby. I did not know the type of interpreter I use Is of importance. How would I know if my ruby interpreter is MRI or not? Using "ruby -v" only outputs "ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-cygwin]."

Also for how I run logstash... I use a start script I created to run it but thats about it. I use java 1.8.0, and ruby is not directly installed on the machine I am using. I assumed Jruby uses its own internal interpreter but I guess this isn't true? Logstash seems to run fine for everything else except installing plugins.

**Comment by CoryBond** [comment] 2015-06-29 15:36
To give you an idea of what my start script for logstash does It uses this command:        

 /usr/bin/nohup $BIN_PATH/$APPMAIN -f $CONFIG_PATH/logstash.config -l $LOG_PATH/logstash.log --quiet >$LOG_PATH/logstash.out 2>&1 &
        sleep 1

and before it does this command I export: 

export JAVA_HOME=/usr/java/1.8.0_31l64
export LS_HEAP_SIZE=4096m
export LS_JAVA_OPTS="$JAVA_OPTS -Xms4096m"
export LS_USE_GC_LOGGING=true

**Comment by talevy** [comment] 2017-02-17 17:20
Closing this issue since it has been open for a long time and we haven't received the details to debug it further. Please reopen a new issue if you still run into issues

**Closed by talevy** 2017-02-17 17:20 UTC
Labels: bug, needs details
