### ISSUE TITLE
Data loss in logstash

### ISSUE THREAD

**Issue by quejinho1988** [elastic/logstash#3461] opened 2015-06-18 12:33 UTC
I used rabbitmq as broker to logstash to elasticsearch via http protocol 
I use access.log for testing ( i filled it by scriopt that sends 5000 requests )
so the amount of data is 5k of indexed files to es. 

At that point while killing logstash i lost about 200 messages. 
After talk on irc i changed protocol to node and lost of messages went to ~40 or nothing so it was fine. 
After change of SizedQueue to 1 for everything , result was still about ~40  that showed it aint fine. 

Second time a bit different way  i got 

nxlog -> via tcp -> logstash - > rabbitmq   with killing logstash i lose about 700 messages. 

Logstash used was in 1.4.2 version

Tested with 1.5.1  version 

nxlog -> connection with ssl -> logstash - > rabbitmq 

i made tests as above and i have lost 700 messages from 5k running in. 
I could not kill logstash or close it , only kill -9 worked.  But as i mentioned before with this sizedqueue ( 1 ) it should not lose such big number of data since with 1.4.2 i lost max 40  on kill -9.

**Comment by suyograo** [comment] 2015-06-23 19:50
@quejinho1988 can you try your setup with 1.5.1? We fixed a lot of bugs in this release and want to validate if your issue reappears

**Comment by quejinho1988** [comment] 2015-06-29 09:15
In upcoming days i will check it.

**Comment by quejinho1988** [comment] 2015-07-07 12:52
Add question if You still need more information.

**Comment by jsvd** [comment] 2015-07-07 15:12
@quejinho1988 here is my first attempt at reproducing data loss:

### Scenario: Kill Logstash while getting data from RabbitMQ to Elasticsearch

#### Versions

* Rabbitmq 3.5.1
* Logstash 1.5.2
* Elasticsearch 1.6.0

#### Logstash config

Read from rabbitmq, send to elasticsearch using http protocol:

```
input {
  rabbitmq {
    host => "localhost"
    queue => "test"
    codec => json
  }
}
output {
  elasticsearch {
    protocol => http
    host => localhost
  }
}
```

#### Elasticsearch

Unpacked and executed with "bin/elasticsearch", nothing changed in elasticsearch.yml

#### RabbitMQ

Installed on MacOSX through brew, started without custom settings.
I created a ruby script to write 10k events to rabbitmq:

```ruby
require 'bunny'
require 'json'

conn = Bunny.new(:hostname => "localhost")
conn.start
ch   = conn.create_channel
10000.times do |i|
  ch.default_exchange.publish({"field1" => "test", "field2" => 2}.to_json, :routing_key => "test")
end
```

### Running the test

Steps:
1. confirmed rabbitmq queue and elasticsearch indices are empty
2. insert 10k documents to rabbitmq
3. check rabbitmq queue has 10k documents
4. start logstash, wait for pipeline to start + a few seconds then do "ctrl+c"
5. check if number of events left in queue + number of events in elasticsearch = 10k
6. start logstash again and wait longer
7. check that rabbitmq is empty and elasticsearch index has 10k events, thus no loss


```
curl -s 'http://guest:guest@127.0.0.1:15672/api/queues/%2F/test' | jq -r ".messages"
0
curl -s 'http://localhost:9200/logstash-*/_count' |jq -r ".count"
0
ruby send_rabbitmq.rb
curl -s 'http://guest:guest@127.0.0.1:15672/api/queues/%2F/test' | jq -r ".messages"
10000
bin/logstash -f config
Logstash startup completed
  ## waited some seconds ##
^CSIGINT received. Shutting down the pipeline. {:level=>:warn}
RabbitMQ connection error: . Will reconnect in 10 seconds... {:level=>:error}
Logstash shutdown completed
curl -s 'http://guest:guest@127.0.0.1:15672/api/queues/%2F/test' | jq -r ".messages"
5301
curl -s 'http://localhost:9200/logstash-*/_count' |jq -r ".count"
4699
```

5301 + 4699 = 10000
At this point no event loss happened. Restarting logstash so all events can be processed:

```
bin/logstash -f config
Logstash startup completed
 ## waited longer ##
^CSIGINT received. Shutting down the pipeline. {:level=>:warn}
RabbitMQ connection error: . Will reconnect in 10 seconds... {:level=>:error}
Logstash shutdown completed
curl -s 'http://guest:guest@127.0.0.1:15672/api/queues/%2F/test' | jq -r ".messages"
0
curl -s 'http://localhost:9200/logstash-*/_count' |jq -r ".count"                   
10000
```

Thus no event loss happened. Any suggestions for changes in my scenario @quejinho1988 ?
Next I'll try reading from nxlog.

**Comment by quejinho1988** [comment] 2015-07-08 07:24
True it wont from this side. It was fixed from 1.5.1   even with  kill -9 works superb. 
But there is still issue with my shipper  try  nxlog  -> logstash -> rabbitmq    and do kill -9 . 
Ctrl -c  i understand that You were in some kind of debbug mode. it is ussual slower so i think its better to have it in the service ,  also i could not kill so that is why i used kill -9 .

**Comment by jsvd** [comment] 2015-07-08 10:03
I was running logstash in the foreground in a terminal. ctrl+c (SIGINT) or a normal kill (SIGTERM) are treated the same by logstash (starts a clean shutdown procedure).

Dealing with -9 is not relevant here. If you want to minimize data loss in a -9 then set all queues and buffers (e.g. logstash-output-elasticsearch flush_size option) to a minimum. You'll always lose data in this scenario.

I'll try to setup a nxlog -> logstash -> rabbitmq pipeline and test it with a normal kill (SIGTERM). I will not waste time for now considering data loss in a SIGKILL

**Comment by talevy** [comment] 2017-02-17 17:21
Closing this issue since it has been open for a long time and we haven't received the details to debug it further. Please reopen a new issue if you still run into issues

**Closed by talevy** 2017-02-17 17:21 UTC
Labels: needs details
