### ISSUE TITLE
Support painless scripting

### ISSUE THREAD

**Issue by fpompermaier** [elastic/logstash#11518] opened 2020-01-20 10:03 UTC
Why isn't painless supported by Logstash? This doesn't make any sense to me..

**Comment by yaauie** [comment] 2020-01-23 22:31
The Painless language and runtime is a part of Elasticsearch, with deep ties to Elasticsearch internals, so it is not ready for consumption by other projects (including Logstash).

***

I am closing this issue because we use the issue tracker here on Github for confirmed issues on Logstash core and there is nothing we can do in the foreseeable future to implement this feature request. I would encourage you to open a thread in the below-linked forums, where developers and community members work together to find solutions to problems:

> Please post all product and debugging questions on our [forum](https://discuss.elastic.co/c/logstash). Your questions will reach our wider community members there, and if we confirm that there is a bug, then we can open a new issue here.

**Closed by yaauie** 2020-01-23 22:31 UTC

**Comment by fpompermaier** [comment] 2020-01-24 09:21
Thanks @yaauie , that makes sense. I created a thread in the ES forum about this problem: https://discuss.elastic.co/t/logstash-and-painless-is-logstash-going-to-be-replaced-by-ingest-nodes/216393
