### ISSUE TITLE
master build failure on java 7

### ISSUE THREAD

**Issue by colinsurprenant** [elastic/logstash#4632] opened 2016-02-04 22:53 UTC
there is a build failure in #4631 which does not seems to be related to the PR. In fact, I just finished checking on bare master and it also reproduces.

The failure happens only in **Java 7** and can be reproduced with 
```sh
rake bootstrap
rake test:install-core
SPEC_OPTS="--seed 61716" rake test:core
```

the error is

```
Failures:

  1) LogStash::Runner argument parsing with no arguments should show help
     Failure/Error: subject.run(args)
       (#<Cabin::Channel:0x57ec8527>).warn("You may be interested in the '--configtest' flag which you can use to validate\nlogstash's configuration before you choose to restart a running system.")
           expected: 1 time with any arguments
           received: 2 times with arguments: ("You may be interested in the '--configtest' flag which you can use to validate\nlogstash's configuration before you choose to restart a running system.")
     # ./logstash-core/lib/logstash/runner.rb:164:in `execute'
     # ./vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
     # ./logstash-core/spec/logstash/runner_spec.rb:40:in `(root)'
     # ./vendor/bundle/jruby/1.9/gems/rspec-wait-0.0.8/lib/rspec/wait.rb:46:in `(root)'
     # ./rakelib/test.rake:42:in `(root)'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:240:in `execute'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:179:in `invoke_with_call_chain'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:106:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:106:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:78:in `run'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'

Finished in 13.06 seconds (files took 3.31 seconds to load)
1005 examples, 1 failure

Failed examples:

rspec ./logstash-core/spec/logstash/runner_spec.rb:36 # LogStash::Runner argument parsing with no arguments should show help

Randomized with seed 61716
```

**Comment by suyograo** [comment] 2016-02-05 00:13
https://github.com/elastic/logstash/commit/9b0361e495f30921b619f72ccde2226b5a121173 did not break this, IMO. See http://build-eu-00.elastic.co/job/Logstash_PR/2157/

Still investigating.

**Comment by colinsurprenant** [comment] 2016-02-05 02:15
then it must be jwoww.

**Comment by suyograo** [comment] 2016-02-05 02:32
Also seems intermittent :( 

Tests passed on this PR commit: http://build-eu-00.elastic.co/job/Logstash_PR/2170/

**Comment by suyograo** [comment] 2016-02-05 03:05
I see why it happens. On Java 7, and specifically on master we now emit a warning log `Please upgrade your java version, the current version '1.7.0_80-b15' is not supported. We recommend a minimum version of Java 8 {:level=>:warn}`

This test is checking if warning is emited once, but now its twice because of the Java 7 warning. https://github.com/elastic/logstash/blob/master/logstash-core/spec/logstash/runner_spec.rb#L39

@colinsurprenant The correct fix is to update the PR Jenkins job to only test on Java 8 for master PRs. 2.x can still test on Java 7 and Java 8. 

It does not make sense to add `if version == java 7` conditional here..

**Comment by colinsurprenant** [comment] 2016-02-05 03:18
well, on java 7 the behaviour of emitting 2 warning is "correct" so the spec should reflect that in one way or the other. maybe simply change the expectation to `.at_least(:once)` ?

**Comment by suyograo** [comment] 2016-02-05 03:55
> maybe simply change the expectation to .at_least(:once) ?

Yep, makes sense

**Comment by purbon** [comment] 2016-02-05 10:34
Hi,
  I've seen this very same error inside the feature/metrics branch, did not
test this also happened in master :-/

I agree this happen due to the warning in the version.

my approach here, and the one I actually fixed in metrics branch is to mock
the agent interface. We're actually testing for the config check warning
inside runner and not the other components, so this was my actually idea to
"fix" the issue.

If we understand this as integration test see how many warning we should
write specific test for it, who can verify the expected behaviour from the
user point of view, at less this is my understanding.

happy hacking!

- purbon

**Comment by suyograo** [comment] 2016-02-05 18:58
@jsvd fixed this indirectly with his commits in https://github.com/elastic/logstash/pull/4520

https://github.com/elastic/logstash/blob/master/logstash-core/spec/logstash/runner_spec.rb#L46

**Closed by suyograo** 2016-02-05 18:58 UTC
Labels: blocker, bug, tests-infra
