### ISSUE TITLE
Logstash 1.4.2 keeps creating temporary files like  "jffi7147932261595358903.tmp

### ISSUE THREAD

**Issue by ESamir** [elastic/logstash#2500] opened 2015-02-03 14:01 UTC
Logstash 1.4.2 keeps creating temporary files like  "jffi7147932261595358903.tmp" in Windows/temp directory and not cleaning them up
This  files created  by logstash at start-up time because of FFI library.

I found bug in jruby https://github.com/jruby/jruby/issues/1237
upgrading to new Jruby version should fix the issue

**Comment by ph** [comment] 2015-02-04 19:32
Actually the bug is `jffi`, the fix was merged in the lastest version of master but a new version of the library isn't included in jruby. https://github.com/jruby/jruby/blob/3cdfc853fba4c3219fce5b6a177a9aa412882cf5/pom.rb#L62

Keeping this open to track it.

**Comment by dialloa** [comment] 2015-04-02 23:56
Hi All,
Did this issue got fixed? Which version of jruby fixed the issue? I am using logstash 1.4.2 and wondering if i can just replace the jruby-complete-1.7.11.jar with the right version of jruby where the issue is fixed.

Thanks for your feedback
Abdoul

**Comment by suyograo** [comment] 2015-09-01 18:47
@ph what version of jruby has this been released?

**Comment by ph** [comment] 2015-09-01 18:54
in .18 (http://jruby.org/2014/12/22/jruby-1-7-18.html) we can close this.

**Closed by ph** 2015-09-01 18:54 UTC
Labels: bug, upstream fix needed, windows
