### ISSUE TITLE
QA: Acceptance Snapshot feature make the VM unresponsive.

### ISSUE THREAD

**Issue by ph** [elastic/logstash#5324] opened 2016-05-19 16:00 UTC
When the QA acceptance framework bring the machine back from a snapshot.
The machine become unresponsive, we cannot run test on it, we cannot ssh to it and we have to bootstrap the machine again.

```
artifacts operation
  behaves like installable
    is installed on 127.0.0.1:2222
    is running on 127.0.0.1:2222
    is removable on 127.0.0.1:2222
  behaves like updated
    can update on 127.0.0.1:2222 (FAILED - 1)
    can run on 127.0.0.1:2222 (FAILED - 2)

An error occurred in an `after(:context)` hook.
  LogStash::CommandExecutor::CommandError: CMD: vagrant snapshot restore centos-6 centos-6-snapshot STDERR: Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that

````

The failling test will return the following: 
```
     Failure/Error: logstash.install(LOGSTASH_VERSION)
     Net::SSH::Disconnect:
       connection closed by remote host
```

Trying to connect to the vm with `vagrant ssh centos-6`
```
~/e/l/qa git:fix/migrate-cli-test ❯❯❯ vagrant ssh centos-6                                                                                              ⏎ ✱
ssh_exchange_identification: Connection closed by remote host
```

**Comment by purbon** [comment] 2016-05-20 15:58
this is actually because of an issue in https://github.com/purbon/runner-tool I'm fixing this now, issue is bacially that after restore, connection broken and the connection need to be reconnected.

**Comment by purbon** [comment] 2016-05-22 10:12
Got this sorted out, the problem is that the SSH connection is not keep open during snapshot/restore, so the ssh runner got confused, thinking there was an open connection when there was not a real socket open. 

https://github.com/purbon/runner-tool/commit/1f924e9e7dd43773329609fbc77c21731804dfe3 Added a decorator with reconnect+retry (only for N times) when an exception like this happen, this will help reconnecting and dealing with this sort of errors.

@ph you should be able to get this only by doing `bundle update` inside the qa directory, please let me know if this works for you, my tests showed the error is gone and I can execute the full set of test after snapshot/restore.

The only thing I was unable to reproduce is your last error, see

```
~/e/l/qa git:fix/migrate-cli-test ❯❯❯ vagrant ssh centos-6                                                                                              ⏎ ✱
ssh_exchange_identification: Connection closed by remote host
```

I always been possible to reconnect with ssh after snapshot restore, please let me know if all works for you now 👍, looking forward to get this sorted out!

- purbon

**Comment by purbon** [comment] 2016-05-24 13:00
I think I've might found why of your issue, the one I was unable to reproduce locally in my machine, https://github.com/mitchellh/vagrant/issues/391 trying to narrow it down and see how we can proceed on this.

**Comment by purbon** [comment] 2016-05-25 09:14
@ph were you able to validate the current fix in runner it's actually making the first part of the snapshot/restore bug away?

**Comment by ph** [comment] 2016-05-25 15:02
But more details, I was able to go further with the execution.
I had a warning but it did not stop the execution of the tests. 

```
An error occurred in an `after(:context)` hook.
  LogStash::CommandExecutor::CommandError: CMD: vagrant snapshot restore ubuntu-1404 ubuntu-1404-snapshot STDERR: Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.
  occurred at /Users/ph/es/logstash/qa/vagrant/command.rb:40:in `run!'

  behaves like installable
    is installed on ubuntu-1504
    is running on ubuntu-1504 (FAILED - 1)
    is removable on ubuntu-1504
  behaves like updated
    can update on ubuntu-1504
    can run on ubuntu-1504 (FAILED - 2)
```

**Comment by purbon** [comment] 2016-05-25 15:12
@ph can you describe your env, as i don't get this error, might this be bound to vagrant,  os version, etc. Thanks

**Comment by ph** [comment] 2016-05-25 15:34
Yes.

```
Vagrant 1.8.1
MacOS X 10.11.3
Target OS was ubuntu: 1504.
jruby 1.7.23 (1.9.3p551) 2015-11-24 f496dd5 on Java HotSpot(TM) 64-Bit Server VM 1.8.0_20-b26 +jit [darwin-x86_64]
```

**Comment by ph** [comment] 2016-05-25 15:35
I am trying with a never jruby version, not sure why .23 was still around.

**Comment by purbon** [comment] 2016-05-25 16:36
@ph are you able to reproduce this by crafting a set of simple commands, so something like

```
at(host1) do
  cmd("command 1")
  cmd("command 2")
end

and then 

at(host1) do
  cmd("command 3")
end
```

my expectation would be second will fail, however is strange because this looks not anymore related to snapshot/restore,  as the failed test are `    is running on ubuntu-1504 (FAILED - 1)` and `    can run on ubuntu-1504 (FAILED - 2)` what do you think?

**Comment by purbon** [comment] 2016-05-26 09:22
@ph I guess we'll have to asses how important is are this failures, or if this is mostly related to the way your environment is setup, also trying to think how common this issue could be, not sure which component is the one causing, testing now with the different moving parts.

@jsvd can you also check this when you  review #5350 ?

**Comment by ph** [comment] 2016-05-26 13:43
@purbon Yeah, lets get another eye or tester on that, Something might be weird with my setup.

Are you running the same version as me (vargant,virtualbox, ruby)?

**Comment by purbon** [comment] 2016-05-26 13:58
```
skywalker% vagrant version
Installed Version: 1.8.1
Latest Version: 1.8.1
```

```jruby 1.7.20 (1.9.3p551) 2015-05-04 3086e6a on Java HotSpot(TM) 64-Bit Server VM 1.8.0_40-ea-b15 +jit [darwin-x86_64]```

`MacOS X 10.10.5`

fairly similar I guess

**Comment by purbon** [comment] 2016-06-07 10:01
we sadly hit the same issue in logstash-ci 👎, see https://logstash-ci.elastic.co/job/elastic+logstash+master+multijob-acceptance/label=metal,suite=debian/10/console for a bit of research.

not is time to investigate this and have a solution, @untergeek your thoughts are welcome also.

**Comment by purbon** [comment] 2016-06-08 14:50
With the merge of #5456 we removed the usage of snapshot/restore so we don't see this issue anymore, will close this issue and open a new one where we can follow up further investigation if necessary.

**Closed by purbon** 2016-06-08 14:50 UTC
Labels: acceptance testing, bug, v5.0.0-alpha4
