### ISSUE TITLE
fails:  LogStash::Instrument::WrappedWriteClient AckedMemoryQueue pushes batch to the 

### ISSUE THREAD

**Issue by ph** [elastic/logstash#7031] opened 2017-05-05 01:34 UTC
branch: logstash+5.x
Link: https://logstash-ci.elastic.co/job/elastic+logstash+5.x+dockerubuntu-periodic/1976/console

Wee seems to have a NPE exception in the write_client/read_client, the test that fails is the following

```
Failures:

  1) LogStash::Instrument::WrappedWriteClient AckedMemoryQueue pushes batch to the `WriteClient`
     Failure/Error: expect(read_client.read_batch.size).to eq(1)
       
       expected: 1
            got: 0
       
       (compared using ==)
     # ./logstash-core/spec/logstash/instrument/wrapped_write_client_spec.rb:41:in `(root)'
     # ./vendor/bundle/jruby/1.9/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `(root)'
     # ./rakelib/test.rake:40:in `(root)'
```

but we also saw this error in other part of the execution:

```
core/spec/logstash/instrument/wrapped_write_client_spec.rb:36" java.lang.NullPointerException
	at org.logstash.ackedqueue.Queue.write(Queue.java:317)
	at org.logstash.ackedqueue.ext.JrubyAckedQueueMemoryExtLibrary$RubyAckedMemoryQueue.ruby_write(JrubyAckedQueueMemoryExtLibrary.java:152)
	at org.logstash.ackedqueue.ext.JrubyAckedQueueMemoryExtLibrary$RubyAckedMemoryQueue$INVOKER$i$1$0$ruby_write.call(JrubyAckedQueueMemoryExtLibrary$RubyAckedMemoryQueue$INVOKER$i$1$0$ruby_write.gen)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:326)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:170)
	at org.jruby.ast.CallOneArgNode.interpret(CallOneArgNode.java:57)
	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
	at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
	at org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:74)
	at org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:182)
	at org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.java:203)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:326)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:170)
	at org.jruby.ast.CallOneArgNode.interpret(CallOneArgNode.java:57)
```

```
Randomized with seed 61547
```

Might be linked to https://github.com/elastic/logstash/pull/6998

**Comment by ph** [comment] 2017-05-05 01:35
It might be linked to the issue you are working on  ? @original-brownbear

**Comment by original-brownbear** [comment] 2017-05-05 07:38
@ph yea this is a nasty case (one of two) that I actually created this issue for https://github.com/elastic/logstash/issues/7026.

We need to have clear exceptions on those and then prevent instantiating the `Queue` without `open`ing (or as I was told) `recover`ing it (imo).

**Comment by ph** [comment] 2017-05-05 18:17
@original-brownbear I will assign it to you since you are working on that issue.

**Comment by colinsurprenant** [comment] 2017-05-05 18:32
I am confused, #6998 is not merged so this is not the cause.
I am not sure why/how these errors could be related to #7010 either. Is that a new failure?

**Comment by original-brownbear** [comment] 2017-05-05 18:56
@colinsurprenant sorry, I explained that a little too "meta" I think.

My reasoning was/is this:

* We fixed the NPE in one case by returning `0` for an un`open`ed queue. This is actually wrong if you think about it, the queue for that configuration(path for the persisted files) could have size `> 0` here.

So: 
1. #7010 is wrong and creates wrong behavior.
2. This doesn't matter all that much if your metric return `0` for a short time and you just use it for monitoring or so ...
3. This is horrible if in #6998 you use it for the actual startup behavior since now you have to juggle the temporal order of `Queue` `open` and `recover` and whatever logic for the check get's implemented => very error-prone IMO.

... that was my reasoning :)

**Comment by colinsurprenant** [comment] 2017-05-05 19:15
I cannot reproduce on 5.x with both
```
rake test:core
```
```
SPEC_OPTS="--seed 61547" rake test:core
```
🤔

**Comment by colinsurprenant** [comment] 2017-05-05 19:27
@original-brownbear **For now**, if we say that "the contract" is that you have to call `open()` or `recover()` and `getPersistedByteSize()` returns zero if `open()` or `recover()` are not yet called is *OK*, certainly not ideal but *ok* for this context. But overall I agree that we should fix this queue state problem. 

Now, I agree we have a problem with the bootstrap check since in order for `getPersistedByteSize()`  to return something meaningful `open()` or `recover()` need to be called which is a catch 22. 

What I don't get is the cause of the reported failure in this issue. it does not seem related to any of the work on `getPersistedByteSize()` in #7010

**Comment by colinsurprenant** [comment] 2017-05-05 19:32
Maybe I am missing something ... I will try to checkout the actual commit jenkins checked out d6612637afdd78827c41d9839023fa270e3094ec but doing a diff from that commit with 5.x now shows only asciidoc changes.

**Comment by colinsurprenant** [comment] 2017-05-05 19:43
I double checked with @ph and this error happened once, did not show up in subsequent builds and I cannot reproduce it. Unless something else comes up I think that we can close this since with @original-brownbear we will be improving the invalid queue state before `open()` or `recover()` is called which I think should prevent such NPE.
 
I think we can close this issue and move on.

**Comment by jsvd** [comment] 2017-05-12 15:41
This happened again in https://logstash-ci.elastic.co/job/elastic+logstash+5.x+multijob-os-compatibility/os=fedora/275/console

**Comment by colinsurprenant** [comment] 2017-05-12 16:44
Upon discussing this with @ph - the wrapped_write_client_spec threading logic will be refactored - we'll see if this helps.

**Comment by ph** [comment] 2017-05-12 17:44
@colinsurprenant I've refactored the test using 2 thread and joining them together, It work perfectly with the Synchronous Queue but it fails with the AckedMemory queue, the pusher thread never unblock after a read.

Ruby code:
```ruby
    it "pushes single event to the `WriteClient`" do
      pusher_thread = Thread.new(subject, event) do |subject, event|
        puts "before pushing"
        subject.push(event)
        puts "done pushing"
      end

      reader_thread = Thread.new(read_client) do |read_client|
        started_at = Time.now

        batch_size = 0
        loop {
          if Time.now - started_at > 60
            raise "Took too much time to read from the queue"
          end
          puts "in loop"
          batch_size = read_client.read_batch.size
          puts "after batch: #{batch_size}"

          break if batch_size > 0
        }
        expect(batch_size).to eq(1)
        puts "After expect"
      end


      [pusher_thread, reader_thread].collect(&:join)
    end
```

Execution Trace:
```
LogStash::Instrument::WrappedWriteClient
  WrappedSynchronousQueue
before pushing
in loop
done pushing
after batch: 1
After expect
    pushes single event to the `WriteClient`
    pushes batch to the `WriteClient` (PENDING: Temporarily skipped with xit)
    recorded metrics
      records instance level events `in` (PENDING: Temporarily skipped with xcontext)
      record input `out` (PENDING: Temporarily skipped with xcontext)
      records pipeline level `in` (PENDING: Temporarily skipped with xcontext)
      recording of the duration of pushing to the queue
        records at the `global events` level (PENDING: Temporarily skipped with xcontext)
        records at the `plugin level (PENDING: Temporarily skipped with xcontext)
        records at the `pipeline` level (PENDING: Temporarily skipped with xcontext)
  AckedMemoryQueue
before pushing
in loop
after batch: 1
After expect
```

**Comment by colinsurprenant** [comment] 2017-05-14 00:41
as discussed, the problem is with the queue initialization where the page size equals the max queue size, this is probably a bug that need to be looked into but in the mean time the queue can be initialized with a bigger max size like this which solves the problem:
```
let(:queue) { LogStash::Util::WrappedAckedQueue.create_memory_based("", 1024, 10, 4096) }
```

**Closed** 2017-05-16 14:20 UTC
Labels: test failure
