### ISSUE TITLE
Variable Expansion with Integer 

### ISSUE THREAD

**Issue by danielkasen** [elastic/logstash#10787] opened 2019-05-13 17:40 UTC
Logstash 6.5.4
Ubuntu 18.04

When trying to use variable expansion on a port number I get failures:

`output {
  tcp {
    host => localhost
    port => %{[@metadata][port]}
    codec => json_lines
  }
}`

Here the @metadata.port number is correctly set in a previous conditional and I can get it to expand as a string but not an int so it fails to work properly when trying to use it as a port number.

`{"level":"ERROR","loggerName":"logstash.outputs.tcp","timeMillis":1557769241305,"thread":"Converge PipelineAction::Create<logstash_input_proxy>","logEvent":{"message":"Invalid setting for tcp output plugin:\n\n  output {\n    tcp {\n      # This setting must be a number\n      # Expected number, got \"%{[@metadata][port]}\" (type %{[@metadata][port]})\n      port => \"%{[@metadata][port]}\"\n      ...\n    }\n  }"}}`

**Comment by danhermann** [comment] 2019-05-31 18:21
Sounds like you need to use the [mutate/convert filter](https://www.elastic.co/guide/en/logstash/current/plugins-filters-mutate.html#plugins-filters-mutate-convert) to convert the string value into an integer value.

I'm closing this since it's a general usage question and not a reproducible bug report or a feature request. Please open a thread on the [forum](https://discuss.elastic.co/c/logstash) if you need additional assistance.

**Closed by danhermann** 2019-05-31 18:21 UTC
