### ISSUE TITLE
wms & wmts plugins missing from logstash 1.5

### ISSUE THREAD

**Issue by mfournier** [elastic/logstash#3842] opened 2015-09-02 10:07 UTC
When migrating the plugins from v.1.4's logstash-contrib repo to 1.5's logstash-plugins github org, these 2 plugins got dropped.

According to @electrical on IRC, this was a mistake. He asked me to open this issue to keep track of the problem.

FTR, these plugins work fine with 1.5 when pointing logstash to them using `--pluginpath`.
These are the 2 commands I had to type to install the geoscript gem which these plugins rely on: 
```
$ GEM_HOME=/opt/logstash/vendor/bundle/jruby/1.9 PATH=/opt/logstash/vendor/jruby/bin/:$PATH gem install --no-rdoc --no-ri -V geoscript
$ echo 'gem "geoscript" >> /opt/logstash/Gemfile
```

Let me know if there's anything I can do to help them get back !

**Comment by purbon** [comment] 2015-09-02 10:10
@mfournier are you willing to create a plugin out of them? you see how to port them to 1.5 in https://www.elastic.co/guide/en/logstash/current/contributing-to-logstash.html, this would be very helpful. If you have question on the process, feel free to ask, we're more than happy to guide you.

**Comment by mfournier** [comment] 2015-09-02 10:18
@purbon ok, I'll give this a go and let you know once I have something working. Thanks !

**Comment by purbon** [comment] 2015-09-02 10:35
awesome! let us know how is it going :P, and don't hesitate to ask questions when there.

**Comment by wiibaa** [comment] 2015-09-02 11:11
@purbon hello this is a duplicate of #3056 and https://github.com/wiibaa/logstash-filter-wms  is waiting for review :smile:

**Comment by purbon** [comment] 2015-09-02 11:14
yay! I apologise @wiibaa I was not aware of this. 

@mfournier closing this as duplicate, will continue conversation in #3056

**Closed by purbon** 2015-09-02 11:14 UTC
