### ISSUE TITLE
one Logstash output rule can't work due to other logstash output rule has problem?

### ISSUE THREAD

**Issue by mizeng** [elastic/logstash#5551] opened 2016-06-24 00:45 UTC
- Version: logstash 2.3.2
- Operating System: Ubuntu 12.04
- Config File (if you have sensitive info, please remove it):

```output_elasticsearch
output {
 elasticsearch {
  hosts => ['es_vip:80']
 }
}
```

```output_kafka
output {
 kafka {
  topic_id => 'logstash_logs'
  bootstrap_servers => 'kafka_host:9092'
 }
}
```

I have above 2 logstash output in one server, and it used to work well.

However yesterday our kafka host get disk full due to too many messages, which means output_kafka may not work since it can not write new messages to the kafka host.
That also impact output to elasticsearch. I found there're thousands of logs lost in elasticsearch compared to local log file.

So it seems once one of logstash output has problem, all other logstash output will get impacted. Maybe due to exception not handling well?

BTW, how can I know from log if logstash rule didn't work (like output to kafka didn't write message successfully due to kafka server disk full)?

**Comment by markwalkom** [comment] 2016-06-26 07:45
When an output is held up for whatever reason, it puts back pressure on the entire pipeline, including other outputs.
This is expected behaviour, not a bug, so I'll close this one off.

If you have further questions, please use our forums - https://discuss.elastic.co :)

**Closed by markwalkom** 2016-06-26 07:45 UTC
