### ISSUE TITLE
Logstash stuck in restart loop due to Ruby dependency 

### ISSUE THREAD

**Issue by klacc** [elastic/logstash#10700] opened 2019-04-21 08:10 UTC
I have installed logstash on Raspberry Pi and am getting the below errors in Syslog - logstash error folder is completely empty. I have tried reinstalling the package but to no avail. Any thoughts? 

Apr 20 14:27:04 raspberrypi logstash[2772]: [ERROR] 2019-04-20 14:27:04.710 [main] Logstash - java.lang.IllegalStateException: Logstash stopped processing because of an error: (GemspecError)
Apr 20 14:27:04 raspberrypi logstash[2772]: [!] There was an error while loading `logstash-core-plugin-api.gemspec`: load error: psych -- java.lang.RuntimeException: BUG: we can not copy embedded jar to temp directory
Apr 20 14:27:04 raspberrypi logstash[2772]: Does it try to require a relative path? That's been removed in Ruby 1.9. Bundler cannot continue.
Apr 20 14:27:04 raspberrypi systemd[1]: logstash.service: main process exited, code=exited, status=1/FAILURE
Apr 20 14:27:04 raspberrypi systemd[1]: Unit logstash.service entered failed state.
Apr 20 14:27:04 raspberrypi systemd[1]: logstash.service holdoff time over, scheduling restart.
Apr 20 14:27:04 raspberrypi systemd[1]: Stopping logstash...
Apr 20 14:27:04 raspberrypi systemd[1]: Starting logstash...
Apr 20 14:27:04 raspberrypi systemd[1]: Started logstash.Apr 20 14:27:53 raspberrypi systemd[1]: logstash.service: main process exited, code=exited, status=1/FAILURE
Apr 20 14:27:53 raspberrypi systemd[1]: Unit logstash.service entered failed state.
Apr 20 14:27:53 raspberrypi systemd[1]: logstash.service holdoff time over, scheduling restart.
Apr 20 14:27:53 raspberrypi systemd[1]: Stopping logstash...
Apr 20 14:27:53 raspberrypi systemd[1]: Starting logstash...
Apr 20 14:27:53 raspberrypi systemd[1]: Started logstash.

**Comment by danhermann** [comment] 2019-04-25 14:58
The Logstash process requires read, write, and execute permissions on the temp directory. If it does not have that, it will produce the error above. Since this is expected behavior and not a reproducible bug report or a feature request, I am closing this issue. Please open a thread on the [forum](https://discuss.elastic.co/c/logstash) if you need additional assistance with this issue.

**Closed by danhermann** 2019-04-25 14:58 UTC

**Comment by isrrapy** [comment] 2020-01-09 19:20
This happened to me as well and I found out that the actual issue was that my /root directory was full due to logs. Truncating my log files fixed the problem.

**Comment by kbpanchal1** [comment] 2022-10-11 17:25
This happened to me too and I found that the issue is /tmp folder was 100% folder. Removed the logs files and issue got resolved.
