### ISSUE TITLE
logstash issue reported in plain log : The shutdown process appears to be stalled due to busy or blocked plugins”

### ISSUE THREAD

**Issue by suddhasilsarkar** [elastic/logstash#12539] opened 2020-12-23 15:54 UTC
Hi Team,
Need help- we have ELK cluster which was down for few months. we have recently brought the cluster up . Now having issues in logstash log as below..
[ERROR][logstash.shutdownwatcher ] The shutdown process appears to be stalled due to busy or blocked plugins. Check the logs for more information.
I have restarted logstash but don't see any log is processing at all and in the plain log i see the same above error.Any help is much appreciated. our logstash version : logstash 5.3.0

Please let me know if any questions

**Comment by yaauie** [comment] 2020-12-23 16:47
The GitHub issues are for confirmed issues with clear reproduction steps, not for general debugging. I'll close this issue and advise you to follow up in [the forums](https://discuss.elastic.co/c/elastic-stack/logstash/14).

But I'll also add some notes to help you get started:

The log message indicates that Logstash is being blocked from shutting down because a filter or output plugin is holding onto work that would be lost if it were to shut down. One of the most common causes is when an output has a batch of events in a retry loop because it is hitting some other failure (such as the elasticsearch output when it cannot establish a connection to elasticsearch). You should be able to force the shutdown by sending the process two interrupt signals (`kill -INT $process_id`), which will cause the in-flight events to get dropped.

Separately, Logstash 5.3 is past its EOL, and we would encourage you to plan to upgrade to Logstash 7. If you are stuck on the 5.x series, we encourage you to at least upgrade to the latest 5.6 ([5.6.16](https://www.elastic.co/downloads/past-releases/logstash-5-6-16) as of this writing), which includes a number of fixes for known issues.

**Closed by yaauie** 2020-12-23 16:47 UTC
