### ISSUE TITLE
user_agent mapping incompatible with beats/ecs

### ISSUE THREAD

**Issue by convertivpool** [elastic/logstash#10834] opened 2019-05-29 12:51 UTC
Hi,
I have a beats + logstash setup with index patterns (and default dashboards) loaded from filebeats. I was trying to match our custom log parsing in logstash to the common schema. New events fail to index with the following error:
```[2019-05-29T11:51:54,428][WARN ][logstash.outputs.elasticsearch] Could not index event to Elasticsearch. {:status=>400, :action=>["index", {:_id=>nil, :_index=>"filebeat-7.1.0-2019.05.29", :_type=>"_doc", :routing=>nil}, #<LogStash::Event:0x72567d48>], :response=>{"index"=>{"_index"=>"filebeat-7.1.0-2019.05.29", "_type"=>"_doc", "_id"=>"p-tuA2sBM9iAJ4-fsBR5", "status"=>400, "error"=>{"type"=>"mapper_parsing_exception", "reason"=>"object mapping for [user_agent.os] tried to parse field [os] as object, but found a concrete value"}}}}```

Example of output of the user_agent filter, note that the `user_agent.os` is a string:
```
"user_agent.build": 
"user_agent.device": "Other"
"user_agent.major": "74"
"user_agent.minor": "0"
"user_agent.name": "Chrome"
"user_agent.os": "Windows"
"user_agent.os_name": "Windows"
"user_agent.patch": 
```

The index pattern seems to be expecting a schema like this:
```
            "user_agent.device.name",
            "user_agent.name",
            "user_agent.original",
            "user_agent.os.family",
            "user_agent.os.full",
            "user_agent.os.kernel",
            "user_agent.os.name",
            "user_agent.os.platform",
            "user_agent.os.version",
            "user_agent.version",
```
I'm assuming the the ingest node matches its output to the common schema. Shouldn't the output of Logstash user_agent filter and the user_agent processor in elasticsearch be compatible?

My current workaround is to process the user_agent.original via the ingest node.
Running Logstash, FIlebeat and Elasticsearch 7.1.0

**Comment by danhermann** [comment] 2019-05-31 18:25
I'm going to close this as a duplicate of https://github.com/logstash-plugins/logstash-filter-useragent/issues/56 (which also has some suggested workarounds). The short answer is that we're actively working to support ECS across the different plugins in Logstash though it is a non-trivial effort.

**Closed by danhermann** 2019-05-31 18:25 UTC
