### ISSUE TITLE
Install logstash with an error (ubuntu 16.04)

### ISSUE THREAD

**Issue by hkhk366** [elastic/logstash#9941] opened 2018-08-26 21:59 UTC
Install logstash with an error (ubuntu 16.04)

root@hkhk-VirtualBox:/# apt-get install logstash=1:6.3.2-1
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages were automatically installed and are no longer required:
linux-headers-4.15.0-29 linux-headers-4.15.0-29-generic
linux-image-4.15.0-29-generic linux-modules-4.15.0-29-generic
linux-modules-extra-4.15.0-29-generic
Use 'sudo apt autoremove' to remove them.
The following NEW packages will be installed:
logstash
0 upgraded, 1 newly installed, 0 to remove and 1 not upgraded.
Need to get 146 MB of archives.
After this operation, 247 MB of additional disk space will be used.
Get:1 https://artifacts.elastic.co/packages/6.x/apt stable/main amd64 logstash all 1:6.3.2-1 [146 MB]
Fetched 146 MB in 1min 4s (2,277 kB/s)
Selecting previously unselected package logstash.
(Reading database ... 295671 files and directories currently installed.)
Preparing to unpack .../logstash_1%3a6.3.2-1_all.deb ...
Unpacking logstash (1:6.3.2-1) ...
Setting up logstash (1:6.3.2-1) ...
Using provided startup.options file: /etc/logstash/startup.options
Errno::ENOMEM: Cannot allocate memory - systemctl
spawn at org/jruby/RubyProcess.java:1566
spawn at org/jruby/RubyKernel.java:1511
popen_run at /usr/share/logstash/vendor/jruby/lib/ruby/stdlib/open3.rb:206
popen3 at /usr/share/logstash/vendor/jruby/lib/ruby/stdlib/open3.rb:102
execute at /usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/pleaserun-0.0.30/lib/pleaserun/detector.rb:74
detect_systemd at /usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/pleaserun-0.0.30/lib/pleaserun/detector.rb:29
detect_platform at /usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/pleaserun-0.0.30/lib/pleaserun/detector.rb:24
detect at /usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/pleaserun-0.0.30/lib/pleaserun/detector.rb:18
setup_defaults at /usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/pleaserun-0.0.30/lib/pleaserun/cli.rb:153
execute at /usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/pleaserun-0.0.30/lib/pleaserun/cli.rb:119
run at /usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/clamp-0.6.5/lib/clamp/command.rb:67
run at /usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/pleaserun-0.0.30/lib/pleaserun/cli.rb:114
run at /usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/clamp-0.6.5/lib/clamp/command.rb:132
at /usr/share/logstash/lib/systeminstall/pleasewrap.rb:12
chmod: cannot access '/etc/default/logstash': No such file or directory
dpkg: error processing package logstash (--configure):
subprocess installed post-installation script returned error exit status 1
E: Sub-process /usr/bin/dpkg returned an error code (1)
Thank you for your help.

**Comment by yaauie** [comment] 2018-09-20 20:44
> `Errno::ENOMEM: Cannot allocate memory - systemctl`

Logstash installed, but could not start because it failed to allocate enough memory. Using the default configuration, Logstash needs at least [1GB of memory](https://github.com/elastic/logstash/blob/v6.3.2/config/jvm.options#L6).

**Comment by newtogitrepo** [comment] 2019-02-21 13:16
yes, I spent long time to sort same issue in my instance, but 2Gb helped me to install Logstash successfully.

**Comment by jsvd** [comment] 2022-03-10 11:51
closing as a duplicate of https://github.com/elastic/logstash/issues/9925

**Closed by jsvd** 2022-03-10 11:51 UTC
