### ISSUE TITLE
Leading spaces on config entries seem to break Logstash

### ISSUE THREAD

**Issue by krisATelastic** [elastic/logstash#8968] opened 2018-01-17 04:13 UTC
- Version: 5.2.2
- Operating System: Redhat

Hey guys, when building a Logstash configuration file (logstash.yml), it would seem that when you have leading spaces in your configuration, it can cause some wierd erroeus issues with Logstash firing up;

**Config Example, note the space:**
```
# ------------  Node identity ------------
#
# Use a descriptive name for the node:
#
 node.name: logstashServer01
#
# If omitted the node name will default to the machine's host name
```

The errors that are currently logged are;
**logstash-plain.log**
```
[2017-10-10T13:53:51,872][INFO ][logstash.setting.writabledirectory] Creating directory {:setting=>"path.queue", :path=>"/var/lib/logstash/data/queue"} 
[2017-10-10T13:53:51,888][INFO ][logstash.agent ] No persistent UUID file found. Generating new UUID {:uuid=>"bbb637f1-e468-4792-8d2d-d16914bd2f55", :path=>"/var/lib/logstash/data/uuid"} 
[2017-10-10T13:53:51,983][INFO ][logstash.agent ] No config files found in path {:path=>"/etc/logstash/conf.d/*"} 
[2017-10-10T13:53:52,050][INFO ][logstash.pipeline ] Starting pipeline {"id"=>"main", "pipeline.workers"=>4, "pipeline.batch.size"=>125, "pipeline.batch.delay"=>5, "pipeline.max_inflight"=>500} 
[2017-10-10T13:53:52,068][INFO ][logstash.pipeline ] Pipeline main started 
[2017-10-10T13:53:52,124][INFO ][logstash.agent ] Successfully started Logstash API endpoint {:port=>9600} 
[2017-10-10T13:54:24,320][WARN ][logstash.runner ] SIGINT received. Shutting down the agent. 
[2017-10-10T13:54:24,327][WARN ][logstash.agent ] stopping pipeline {:id=>"main"} 
```

**logstash-stdout.log**
```
Sending Logstash's logs to /var/log/logstash which is now configured via log4j2.properties 
usage: 
bin/logstash -f CONFIG_PATH [-t] [-r] [] [-w COUNT] [-l LOG] 
bin/logstash -e CONFIG_STR [-t] [--log.level fatal|error|warn|info|debug|trace] [-w COUNT] [-l LOG] 
bin/logstash -i SHELL [--log.level fatal|error|warn|info|debug|trace] 
bin/logstash -V [--log.level fatal|error|warn|info|debug|trace] 
bin/logstash --help
```

**logstash-stderr.log**
```
ERROR: No configuration file was specified. Perhaps you forgot to provide the '-f yourlogstash.conf' flag?
```

This smells "bugish", as removing the leading space in the config fired up Logstash without issues. Maybe some more validation on pre-start for this sort of scenario might help too?

Thanks!

**Comment by jordansissel** [comment] 2018-01-17 07:44
Thank you for filing, and I agree this is a very bad user experience. The technical explanation for what is happening is a bit funny. (Yaml parser is seeing the leading space, then ignoring the rest of the document, silently. This is ... bizarre!)

I tested this and it's a duplicate of this issue: https://github.com/elastic/logstash/issues/8434

**Closed by jordansissel** 2018-01-17 07:44 UTC
Labels: bug, v5.2.2
