### ISSUE TITLE
Different number of tests are run with each core tests

### ISSUE THREAD

**Issue by suyograo** [elastic/logstash#4755] opened 2016-03-03 22:47 UTC
Hopefully the # of tests run is not randomized! I get different number of examples each time I run `rake test:core`

```
Finished in 18.54 seconds (files took 2.01 seconds to load)
1357 examples, 0 failures

Randomized with seed 5668

suyog@machine:~/ws/elastic/logstash (revert_4425)$ rake test:core
Using Accessor#strict_set for specs
/Users/suyog/ws/elastic/logstash/logstash-core/lib/logstash/api/init.ru:1 warning: already initialized constant ROOT
Run options: exclude {:redis=>true, :socket=>true, :performance=>true, :couchdb=>true, :elasticsearch=>true, :elasticsearch_secure=>true, :export_cypher=>true, :integration=>true, :windows=>true}
........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

Finished in 19.01 seconds (files took 2.07 seconds to load)
1256 examples, 0 failures

Randomized with seed 20244

suyog@machine:~/ws/elastic/logstash (revert_4425)$ rake test:core
Using Accessor#strict_set for specs
/Users/suyog/ws/elastic/logstash/logstash-core/lib/logstash/api/init.ru:1 warning: already initialized constant ROOT
Run options: exclude {:redis=>true, :socket=>true, :performance=>true, :couchdb=>true, :elasticsearch=>true, :elasticsearch_secure=>true, :export_cypher=>true, :integration=>true, :windows=>true}
...........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

Finished in 19.68 seconds (files took 2.04 seconds to load)
1611 examples, 0 failures

Randomized with seed 60477
```

**Comment by jordansissel** [comment] 2016-03-03 23:45
If any tests use Flores' `stress_it` those specs run a random number of times, yeah. I'll try to find out.

**Comment by jordansissel** [comment] 2016-03-04 00:51
@suyograo I didn't find any use of `stress_it` in logstash 2.2.2 (or its plugins).

Can you run rspec with `-f d` maybe we can see what tests are missing or not from each run

**Comment by ph** [comment] 2016-03-04 03:15
This is a duplicate of https://github.com/elastic/logstash/issues/3751

@jsvd also created an issue in flores https://github.com/jordansissel/ruby-flores/issues/4

**Closed** 2016-10-29 17:33 UTC
Labels: tests
