### ISSUE TITLE
Can not remove my installed plugin

### ISSUE THREAD

**Issue by alah64** [elastic/logstash#10781] opened 2019-05-10 06:40 UTC
hi 
i installed my plugin . but when i want to remove my plugin or any other plugins , logstash said :
```
#my commands : /usr/share/logstash/bin/logstash-plugin remove logstash-filter-myplugin
#another command: /usr/share/logstash/bin/logstash-plugin remove logstash-filter-kv

ERROR: Operation aborted, cannot remove plugin, message: The path `/root/logstash-core` does not exist.
```
after i copy `/usr/share/logstash/logstash-core` to /root/logstash-core , error changed to :
```
ERROR: Operation aborted, cannot remove plugin, message: The path `/root/logstash-core-plugin-api` does not exist.
```

i think logstash dont know where is installed .

- Version: elk 7
- Operating System: ubuntu 18.4

**Comment by alah64** [comment] 2019-05-10 06:50
Ok , i solve it by ` cd /usr/share/logstash/` command before execute remove command.

**Comment by remd** [comment] 2019-07-01 19:15
I'm not sure why this issue was closed considering that users should not have to workaround this with their own manual `cd`. Can this issue please be reopened? @alah64

**Comment by rkhapre** [comment] 2019-07-17 06:09
Yes, i am also facing this issue.

**Comment by gekkeharry13** [comment] 2019-12-10 19:41
Facing the same issue here

**Comment by JazyK** [comment] 2020-01-13 16:50
Issue does not only impact 7.x, it shows up when moving from `6.6.2 -> 6.7.0/6.8.x`

**Comment by bangejsans** [comment] 2020-03-03 17:56
The workaround alah64 mentioned works, but still impacts 7.6.

**Comment by guanyufen123** [comment] 2020-04-17 07:09
Facing the same issue here。

**Comment by LuckyWindsck** [comment] 2020-05-06 21:39
Facing the same issue here

```
logstash --version
logstash 7.6.2
```

I tried to modify the code to print the backtrace of the exception, and I found that this line.

```
gem "logstash-core", :path => "./logstash-core"

# In line /usr/local/Cellar/logstash/7.6.2/libexec/Gemfile:5
# I installed logstash by homebrew.
```

It seems like that `"./logstash-core"` is the reason of the bug.
I am not familiar with the source code, but I guess that `Gemfile.template` is the file responsible for it.

**Comment by nicholas-cross-fujitsu** [comment] 2020-12-03 17:14
We have this in 7.10

**Comment by farrp** [comment] 2021-03-16 15:20
We are having the same issue in 7.10.2. I see this has been opened almost a year without being assigned to anyone. It seems that @LuckyWindsck has supplied a pointer to the solution. When will this be fixed?

**Closed** 2021-04-08 15:59 UTC
Labels: int-shortlist, papercut, regression, ux

**Comment by rquinnlv** [comment] 2021-04-15 16:51
Just ran into this issue as well, please reopen and fix

**Comment by kaisecheng** [comment] 2021-04-15 17:39
Hi @rquinnlv the fix will deliver in `v7.12.1` next week

**Comment by VexVexVex** [comment] 2021-04-28 14:01
Hi, `v7.12.1` actually introduced this error into our build process when it hadn't been present previously. Specifically when removing the lumberjack plugin to replace with a custom one.

**Comment by kaisecheng** [comment] 2021-04-28 14:52
@VexVexVex  Could you create an issue in Logstash with the version and the steps to reproduce the issue? 
Please tag me there and I will do a follow-up.

**Comment by VexVexVex** [comment] 2021-04-28 14:57
@kaisecheng Sorry for the noise, after posting I figured out it was a false alarm on my part. Looks like y'all set the Gemfile to be 644 root and we were doing our plugin mods as logstash user. I fixed that and our process works fine now.
