### ISSUE TITLE
LS_HEAP_SIZE and LS_JAVA_OPTS are missing from Windows script

### ISSUE THREAD

**Issue by pickypg** [elastic/logstash#4065] opened 2015-10-20 17:32 UTC
Currently, the only way to setup the memory for Logstash on Windows is to manually set the `LS_MIN_MEM` and `LS_MAX_MEM` environment variables.

Worse, to set any `JAVA_OPTS`, Windows users are forced to modify the `setup.bat` script or to add to `JAVA_OPTS` directly, which is a bad idea.

**Comment by colinsurprenant** [comment] 2015-10-20 18:46
+1 

This is a duplicate of #3134. It also relates to #2942 and work done in #3111 which was never totally completed for Windows. The same startup strategy as refactored in #3111 should be used on Windows.

**Comment by suyograo** [comment] 2015-10-20 20:37
Closing this as dup of #3134

**Closed by suyograo** 2015-10-20 20:37 UTC
Labels: bug, windows
