### ISSUE TITLE
logstash-core beta vs release gem version

### ISSUE THREAD

**Issue by johnarnold** [elastic/logstash#4243] opened 2015-11-20 18:58 UTC
I upgraded from 2.0.0.beta2 to GA (Which was in itself a PITA because apt thinks debian package for beta2 > 2.0.0-1)

It looks like with gem version comparison, 2.0.0 isn't greater than 2.0.0.beta2

johnar@flowr1a4:/var/log/logstash$ sudo /opt/logstash/bin/plugin list
 Bundler::VersionConflict: Bundler could not find compatible versions for gem "logstash-core":
 In snapshot (Gemfile.lock):
 logstash-core (= 2.0.0)

In Gemfile:
 logstash-output-kafka (>= 0) java depends on
 logstash-core (< 3.0.0, >= 2.0.0.beta2) java

**Comment by johnarnold** [comment] 2015-11-20 19:03
Also, I manually upgraded my plugins (bin/plugin upgrade), and confirmed all the interactive prompts, but still get an error when starting up:

johnar@flowr1a4:/var/log/logstash$ cat logstash.err
RuntimeError: Logstash expects concurrent-ruby version 0.9.1 and version 0.9.2 is installed, please verify this patch: /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.0.0-java/lib/logstash/patches/silence_concurrent_ruby_warning.rb
   (root) at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.0.0-java/lib/logstash/patches/silence_concurrent_ruby_warning.rb:53
  require at org/jruby/RubyKernel.java:1040
   (root) at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.0.0-java/lib/logstash/patches.rb:1
  require at org/jruby/RubyKernel.java:1040
   (root) at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.0.0-java/lib/logstash/patches.rb:6
  require at org/jruby/RubyKernel.java:1040
   (root) at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.0.0-java/lib/logstash/environment.rb:1
  require at org/jruby/RubyKernel.java:1040
   (root) at /opt/logstash/lib/bootstrap/environment.rb:48

This seems like a build breaking bug?

**Comment by colinsurprenant** [comment] 2015-11-20 19:14
I cannot reproduce locally from a 2.0 fresh install (from the tar.gz). Can you share the steps you did from the 2.0 package install?

**Comment by colinsurprenant** [comment] 2015-11-20 19:18
the `concurrent-ruby` version conflict is another issue. pulling in @ph who worked specifically on this problem.

**Comment by johnarnold** [comment] 2015-11-20 19:40
On Ubuntu 15.04.  First host was installed manually, next 6 hosts installed via ansible tasks (below).  All exhibited same issues. 

    - name: Add Elasticsearch apt key.
      apt_key:
        url: http://packages.elasticsearch.org/GPG-KEY-elasticsearch
        state: present

    - name: Add Logstash repository.
      apt_repository:
        repo: 'deb http://packages.elasticsearch.org/logstash/2.0/debian stable main'
        state: present

    - name: Install Logstash
      become: true
      apt:
        pkg=logstash=1:2.0.0-1
        state=present
        update_cache=yes
        force=yes

    - name: Install translate plugin
      become: true
      command: /opt/logstash/bin/plugin install logstash-filter-translate
      notify: Restart Logstash Daemon

    - name: Ensure Logstash is running
      service:
        name=logstash
        state=started
        enabled=yes
      become: yes

**Comment by ph** [comment] 2015-11-20 19:46
@colinsurprenant @johnarnold 

I only know 2 workaround for this, without a new release (which is coming next week.)

Apply this patch to logstash https://github.com/elastic/logstash/pull/4146


OR

Either lock the version of the `concurrent-ruby` to 0.9.1 in the gemfile
```
echo "gem 'concurrent-ruby', '0.9.1'" >> gemfile
bin/plugin install --no-verify
```

**Comment by colinsurprenant** [comment] 2015-11-20 19:46
@johnarnold so your saying that to reproduce you
- intall logstash 2.0 from deb package as above
- install logstash-filter-translate 

and then 
```
$ bin/plugin list 
```
results in the `Bundler::VersionConflict` exception ?

**Comment by johnarnold** [comment] 2015-11-20 19:47
I built a deb off of the latest master, using rake artifact:deb, and pushed that out.  That appears to resolve the issues (the spice flows).

Ansible steps:

   - name: Copy logstash dev package
     copy:
      src=files/logstash_3.0.0.dev-1_all.deb
      dest=/var/tmp/
     become: yes

   - name: Install logstash dev package
     become: true
     apt:
      deb=/var/tmp/logstash_3.0.0.dev-1_all.deb
      state=present

   - name: Install translate plugin
     become: true
     command: /opt/logstash/bin/plugin install logstash-filter-translate
     notify: Restart Logstash Daemon

I did get a warning when trying to update plugins after installing master package:

johnar@flowr1a1:/var/log/logstash$ sudo /opt/logstash/bin/plugin update --no-verify
Update is not supported for manually defined plugins or local .gem plugin installations, skipping: logstash-core, logstash-core-event
Updating logstash-codec-collectd, logstash-codec-dots, logstash-codec-edn, logstash-codec-edn_lines, logstash-codec-es_bulk, logstash-codec-fluent, logstash-codec-graphite,
...

When building from GitHub master, are all the plugins packaged/installed too, or do I need to build a 'contrib' package or something?

**Comment by ph** [comment] 2015-11-20 19:48
@johnarnold @colinsurprenant He could install a snapshot version of 2.1 ?

**Comment by johnarnold** [comment] 2015-11-20 19:49
@colinsurprenant   Yes, although I would add that I upgraded to 2.0.0-1 "GA" from 2.0.0.beta2. Not sure if it matters.

**Comment by colinsurprenant** [comment] 2015-11-20 19:49
@johnarnold I do not recommend you run off of master in production, it has not been thoroughly tested, neither the package generation. you'd be better off from a release branch like 2.1

**Comment by colinsurprenant** [comment] 2015-11-20 19:50
@johnarnold ah, that's a good point (upgrade path). Would it be possible for you to test a 2.0 install from scratch, no upgrade, to see if you can reproduce?

**Comment by johnarnold** [comment] 2015-11-20 19:57
@colinsurprenant  Yeah I'll try to get a repro, after I get everything working again.

Will try 2.1 branch on your suggestion.  master ran for a bit, then looks like silently died.

**Comment by ph** [comment] 2015-11-20 19:59
@johnarnold https://download.elastic.co/logstash/logstash/logstash-latest-SNAPSHOT.deb This a 2.1 build which should include the concurrent-ruby fix.

This will become GA.

**Comment by colinsurprenant** [comment] 2015-11-20 20:05
^^ this SHOULD become GA :smile: 

Yeah, in general @johnarnold master and N.x (2.x, etc) branches are dev branches, should be stable enough for dev work but are not production quality. Release branches (2.0, 2.1, etc) are meant for the release process and are definitely a safer bet. Obviously the testing cycle is not complete until we reach GA.

**Comment by johnarnold** [comment] 2015-11-20 20:07
<grin> I just build 2.1 snapshot 4, will check back in.

**Comment by colinsurprenant** [comment] 2015-11-20 20:32
also relates to #2461

**Comment by colinsurprenant** [comment] 2015-11-20 20:36
@johnarnold to make we leave no stone unturned, how did you manage to do the 2.0.0.beta2 to GA deb upgrade ?

**Comment by johnarnold** [comment] 2015-11-20 20:57
@colinsurprenant See ansible playbook above, specifically I specified the long-form package version, including the prefix "1:"

pkg=logstash=1:2.0.0-1

**Comment by ph** [comment] 2016-03-11 17:37
I think we can safely close this, the infamous concurrent ruby is solved and we did a few main release since then.

**Closed by ph** 2016-03-11 17:37 UTC
Labels: bug
