### ISSUE TITLE
multiline input plugin inserts superfluous newlines and ignores existing newlines

### ISSUE THREAD

**Issue by UlrichEckhardt** [elastic/logstash#2925] opened 2015-03-31 11:22 UTC
The multiline input plugin inserts a bunch of unexpected newlines and sometimes ignores existing newlines. Consider following configuration:
```
input {
  stdin {
    codec => multiline {
      pattern => "^\s"
      what => "previous"
    }
  }
}

output {
  stdout {
    codec => rubydebug
  }
}
```

# Missed Input
The first problem with this seems to be buffering related, because when I write some test input (see below) to a file and use `cat file.log | logstash -f newline-bug.conf`, logstash terminates without having handled even a single event.

# Ignored Newlines
Further, when I run `logstash -f newline-bug.conf` and then paste two input lines at once, those are *always* treated as single event, with further lines pasted onto them according to the plugin configuration. Note that if the pattern that should trigger a new event is inside such a cluster of lines, the newline input plugin will not detect it. *Therefore, for the two test cases below, you have to paste the lines one-by-one.*

# Trailing Newline
Given the following input:
```
abc
def
```
The first line is turned into one event, with `"message" => "abc\n"` in the output. This should be `"message" => "abc"` instead, i.e. without trailing newline.

# Internal Newlines
Given the following input:
```
abc
  def
ghi
```
The first two lines are turned into one event, with `"message" => "abc\n\n  def\n"` in the output. This should be `"message" => "abc\n  def"` instead, i.e. without trailing newline and without duplicate, internal newlines.

Notes:

 * Using logstash 1.4.2 on Debian.
 * The two initial issues don't occur when not using the multiline plugin, which is why I added them to this issue instead of creating a new issue for buffering.
 * I have not tested this using other inputs than stdin, so I can't tell if that makes a difference.
 * Some of these things should be easy to test automatically. From my own experience, I can tell you that you won't regret the effort required to set up automated tests.

**Comment by UlrichEckhardt** [comment] 2015-04-01 11:38
I think I have found a workaround for this: Instead of using the multiline input codec plugin, use the multiline filter to group events:
```
input {
  stdin {
    # no multiline here!
  }
}

filter {
  # multiline here instead
  # Note: No "codec => " here!
  multiline {
    pattern => "^\s"
    what => "previous"
  }
}

output {
  stdout {
    codec => rubydebug
  }
}
```

**Comment by WCMinor** [comment] 2015-07-22 10:03
Weird, this is also happening to me, multiline input plugin doesn't react as expected on regex, but the filter does.

**Comment by WCMinor** [comment] 2015-07-22 10:11
And then magically a second message appears after the proper message with a blank "message", like it's only the '\s' message:
This is each log entry (with a blank line at the end)
```
one line
another line
and the last one

```
This is are my input and filter:
```
input {
  file
  { 
    path           => ["/tmp/log"]
    start_position => "beginning"
    tags           => [ "log" ]
    type           => "log"
  }
}
filter {
  if [type] == "log" {
    multiline {
      pattern => "^\s*$"
      negate  => true
      what    => previous
    }
  }
}
```
and here's the output:
```
{
       "message" => "one line\nanother line\nand the last one",
      "@version" => "1",
    "@timestamp" => "2015-07-22T10:07:17.478Z",
          "host" => "dario-laptop",
          "path" => "/tmp/log",
          "type" => "log",
          "tags" => [
        [0] "log",
        [1] "multiline"
    ]
}
{
       "message" => "",
      "@version" => "1",
    "@timestamp" => "2015-07-22T10:07:17.482Z",
          "host" => "dario-laptop",
          "path" => "/tmp/log",
          "type" => "log",
          "tags" => [
        [0] "log"
    ]
}
```
I can filter it out with mutate but it's a bit annoying having this to happen

**Comment by TurboPunk** [comment] 2015-10-14 08:50
Using the multiline filter instead of the input codec solves the extra linebreaks. But the filter doesn't seem to handle (a vast amount of) multiline as smooth as the codec does at input level.

Any other idea's or fixes?

**Comment by UlrichEckhardt** [comment] 2015-10-15 12:45
We have given up on extracting the info from the Monolog output. Instead, we just dump all output into a second file using Monolog's LogstashFormatter, which not only made integration much easier but also improved performance of our ELK stack. Having multiple lines per log entry also becomes a non-issue that way.

**Comment by guyboertje** [comment] 2015-11-25 14:21
The bugs related to problems noted above have been fixed except for one auto-flush - I am working on that now.

I will address the points raised in the opening comment.

- Missed Input. This is exactly the auto-flush problem.  The multiline codec will buffer the lines matched until a new 'first' line is seen, only then will it flush a new event from the buffered lines.  If there is no more data to be read the buffered lines are never flushed.  We have done some work recently to fix this.
- Ignored Newlines. The point seems to say that the multiline codec should **split** the line on the newlines then apply the match expression. The current versions of stdin input and multiline codec **do** do this. If one pastes this:
```
gfafgafg
 asdfsdf
 aasfgrr
 ijijpij
egerer
geuyiut

```
into stdin for this config `bin/logstash --debug -e 'input { stdin { codec => multiline { pattern => "^\s" what => "previous" } } }'`, one gets two events, the first one has a message of `"gfafgafg\n asdfsdf\n aasfgrr\n ijijpij"` and the other has `"egerer"`.
- Trailing Newline and Internal Newlines. Maybe the versions of stdin and multiline used at the time did retain extra newline characters. With 1.5.5 and 2.X the stdin input with the multiline codec do not have extra newline characters.  There will be newline characters between the merged lines in the Event message field though.

**Closed by guyboertje** 2015-11-25 14:21 UTC

**Comment by TurboPunk** [comment] 2015-12-09 09:46
Hi Guy,

Is there anywhere I can follow or check the fix for that auto-flush?

Thanks!

**Comment by guyboertje** [comment] 2015-12-09 17:05
@TurboPunk - yes, [here](https://github.com/logstash-plugins/logstash-codec-multiline/issues/15) and [here](https://github.com/logstash-plugins/logstash-codec-multiline/issues/11)

**Comment by ruria** [comment] 2016-09-16 20:20
Hi, I´m little confused here, need some clarification. thanks.

Shoul auto_flush_interval (in multiline codec) with udp input work?

See: https://discuss.elastic.co/t/auto-flush-interval-not-flushing/60387

**Comment by guyboertje** [comment] 2016-09-19 09:25
@ruria - I will answer here and on the discuss question.

No - multiline auto-flush does not work with the UDP input yet. AFAIK the file input and the beats input are the only input plugins that have been modified to support auto-flush.

The reason why the multiline (or any) codec can't support auto-flush without the input being modified is because the codecs are in-band event generators. This means that the call to decode happens in the input thread's execution context. The input thread calls the codec's decode method with a closure to call back on. Auto-flush is something that occurs out-of-band i.e. in another thread at some time later when the input thread is doing some other work - the auto-flush code does not have a reference to the input to call back on when it has an auto-flush generated event give to Logstash for further processing.

It is not possible make auto-flushing work in the codec alone without modifying the input code.

**Comment by ruria** [comment] 2016-09-19 13:19
I´ll use multiline filter codec instead (in a "1-worker" mode), thank you.

Maybe some doc clarification ( https://www.elastic.co/guide/en/logstash/current/plugins-codecs-multiline.html#plugins-codecs-multiline-auto_flush_interval ) can be useful to others ¿?

**Comment by guyboertje** [comment] 2016-09-20 11:55
Good idea.

**Comment by pstankie** [comment] 2017-09-15 10:50
The issue is closed, but it seems that superfluous newlines issue isn't closed. 
I'm trying to debug logstash input tcp with multiline codec (logstash 2.x to 5.x and multiline 2x/3x)

When message is spanning two tcp packets, there's newline inserted in the message in the place of packets boundaries. I'm observing the problem on multiple installations...
Multiline concatenates both messages into one, but newline is there, whereas tcpdump doesn't show newline !
