### ISSUE TITLE
Send csv to ES <ArgumentError: Setting "" hasn't been registered>

### ISSUE THREAD

**Issue by gfelot** [elastic/logstash#6881] opened 2017-04-05 09:52 UTC
I'm trying to send 8Go of csv from my computer to a locate server with ES.

I already post my issue on the forum without any answer so I'm trying here.
https://discuss.elastic.co/t/error-argumenterror-setting-hasnt-been-registered/78666

- Version: 5.3.0 (test with 5.0.1 too)
- Operating System: MacOS
- Config File : 
```
input {
    file {
        path => '/Users/gil/Downloads/sirenApril.csv'
        start_position => 'beginning'
        sincedb_path => "/dev/null"
    }
}
filter {
    csv {
        columns => ['SIREN','NIC','L1_NORMALISEE','L2_NORMALISEE','L3_NORMALISEE','L4_NORMALISEE','L5_NORMALISEE','L6_NORMALISEE','L7_NORMALISEE','L1_DECLAREE','L2_DECLAREE','L3_DECLAREE','L4_DECLAREE','L5_DECLAREE','L6_DECLAREE','L7_DECLAREE','NUMVOIE','INDREP','TYPVOIE','LIBVOIE','CODPOS','CEDEX','RPET','LIBREG','DEPET','ARRONET','CTONET','COMET','LIBCOM','DU','TU','UU','EPCI','TCD','ZEMET','SIEGE','ENSEIGNE','IND_PUBLIPO','DIFFCOM','AMINTRET','NATETAB','LIBNATETAB','APET700','LIBAPET','DAPET','TEFET','LIBTEFET','EFETCENT','DEFET','ORIGINE','DCRET','DDEBACT','ACTIVNAT','LIEUACT','ACTISURF','SAISONAT','MODET','PRODET','PRODPART','AUXILT','NOMEN_LONG','SIGLE','NOM','PRENOM','CIVILITE','RNA','NICSIEGE','RPEN','DEPCOMEN','ADR_MAIL','NJ','LIBNJ','APEN700','LIBAPEN','DAPEN','APRM','ESS','DATEESS','TEFEN','LIBTEFEN','EFENCENT','DEFEN','CATEGORIE','DCREN','AMINTREN','MONOACT','MODEN','PRODEN','ESAANN','TCA','ESAAPEN','ESASEC1N','ESASEC2N','ESASEC3N','ESASEC4N','VMAJ','VMAJ1','VMAJ2','VMAJ3','DATEMAJ']
    }
    separator => ';'
}
output {
    elasticsearch {
        hosts => '192.168.10.19:9200'
        index => 'siren'
    }
    stout {}
}
```
Error : 
```
$ ./bin/logstash -f ./config/logstash.yml
Sending Logstash's logs to /Users/gil/Downloads/logstash-5.3.0/logs which is now configured via log4j2.properties
[2017-04-05T11:42:07,394][FATAL][logstash.runner          ] An unexpected error occurred! {:error=>#<ArgumentError: Setting "" hasn't been registered>, :backtrace=>["/Users/gil/Downloads/logstash-5.3.0/logstash-core/lib/logstash/settings.rb:29:in `get_setting'", "/Users/gil/Downloads/logstash-5.3.0/logstash-core/lib/logstash/settings.rb:61:in `set_value'", "/Users/gil/Downloads/logstash-5.3.0/logstash-core/lib/logstash/settings.rb:80:in `merge'", "org/jruby/RubyHash.java:1342:in `each'", "/Users/gil/Downloads/logstash-5.3.0/logstash-core/lib/logstash/settings.rb:80:in `merge'", "/Users/gil/Downloads/logstash-5.3.0/logstash-core/lib/logstash/settings.rb:115:in `validate_all'", "/Users/gil/Downloads/logstash-5.3.0/logstash-core/lib/logstash/runner.rb:210:in `execute'", "/Users/gil/Downloads/logstash-5.3.0/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'", "/Users/gil/Downloads/logstash-5.3.0/logstash-core/lib/logstash/runner.rb:183:in `run'", "/Users/gil/Downloads/logstash-5.3.0/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'", "/Users/gil/Downloads/logstash-5.3.0/lib/bootstrap/environment.rb:71:in `(root)'"]}
```

**Comment by andrewvc** [comment] 2017-04-07 16:41
Please be patient. @guyboertje is working with you on the thread in discuss, its been only two days since his last response. Additionally, I see that you have not posted your `settings.yml` as he requested using the backticks for formatting.

Closing this issue as it is a dupe of the forum. Having multiple identical threads only confuses things.

**Closed by andrewvc** 2017-04-07 16:41 UTC

**Comment by psasikumarece** [comment] 2017-05-17 07:34
Hi,
I'm getting the following error - Can anyone help me on this?
An unexpected error occurred! :error => Setting "" hasn't been registered, :back
trace => ["C:/Elk-Stack/logstash/logstash-core/lib/logstash/settings.rb:29:in `g
et_setting'", "C:/Elk-Stack/logstash/logstash-core/lib/logstash/settings.rb:61:i
n `set_value'", "C:/Elk-Stack/logstash/logstash-core/lib/logstash/settings.rb:80
:in `merge'", "org/jruby/RubyHash.java:1342:in `each'", "C:/Elk-Stack/logstash/l
ogstash-core/lib/logstash/settings.rb:80:in `merge'", "C:/Elk-Stack/logstash/log
stash-core/lib/logstash/settings.rb:115:in `validate_all'", "C:/Elk-Stack/logsta
sh/logstash-core/lib/logstash/runner.rb:210:in `execute'", "C:/Elk-Stack/logstas
h/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'", "C
:/Elk-Stack/logstash/logstash-core/lib/logstash/runner.rb:183:in `run'", "C:/Elk
-Stack/logstash/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:13
2:in `run'", "C:\\Elk-Stack\\logstash\\lib\\bootstrap\\environment.rb:71:in `(ro
ot)'"]
