### ISSUE TITLE
Logstash stops processing after a period

### ISSUE THREAD

**Issue by ackackack** [elastic/logstash#3914] opened 2015-09-14 10:18 UTC
Hello,
Not sure if there is a bug here or if there is a configuration issue which is causing this problem...

I have recently setup logstash on a newly installed VM running Debian Jessie ( **Debian 8.2** ).
**Logstash 1.5.4-1** was installed via the repository from http://packages.elasticsearch.org/logstash/1.5/debian

Not sure if this is relevant but i'm including it for the sake of completeness: The process for Logstash was started via _systemctl start logstash_ in the first few attempts and then via _/etc/init.d/logstash start_ on the next few. 

When logstash stops:
- I cannot restart it via systemctl or via the init.d script. the processes needs to be stopped with a killall -9 java
- No data is being logged to the log files
- No data is being forwarded on to the other host
- A number of the child processes have higher CPU activity than the others

As its stopping the number of entries passed from logstash to the second host decreases over time.

My configuration is as follows:

```
input {
# Syslog bind port for systems
   udp {
     port => 5140
     type => "syslog"
     tags => [ "syslog-plain" ]
   }
   tcp {
         port => 5140
         type => "syslog"
         tags => [ "syslog-plain" ]
   }
}

filter {
if [program] == "" {
     mutate {
         replace => ["program", "unknown"]
     }
}
if "syslog-plain" in [tags] {
     grok {
       match => [ "host", "%{IP:source_host}(:%{POSINT:source_port})?" ]
     }
     dns {
       reverse => [ "source_host" ]
       action => "replace"
     }
     grok {
         match => [ "message", "(<%{POSINT:syslog_pri}>)?%{SYSLOGTIMESTAMP:syslog_timestamp} %{SYSLOGHOST:syslog_hostname} %{DATA:syslog_program}(?:\[%{POSINT:syslog_pid}\])?: %{GREEDYDATA:syslog_message}" ]
     }
  grok {
    patterns_dir => "/etc/logstash/patterns"
    match => { "message" => "%{FTARGET}" }
        add_tag => ["target_to_host2"]
  }

}

# This is the closing for the filter section.
}

output {
    file {
        message_format => "%{message}"
        path => "/home/logstash/%{+YYYY}/%{+MM}/%{+dd}/%{source_host}.log"
    }
    if "target_to_host2" in [tags] {
        udp {
            host => "<host2>"
            port => 514
            codec => "plain"
        }
    }
}

```

The FTARGET is as follows:

```
FTARGET (devid=(xxff78758|xx989876|839804|))
```

There are 50 items in total listed in the FTARGET pattens above

You may have noticed that I'm listening on 5140. There is a router in front of this performing translation from 514 on the outside to 5140 on the inside for both TCP and UDP. This is because the process is running as the default logstash user and cannot listen on 514 without root.

While logstash is apparently dead the logs do continue to be passed to the server but are not processed.

I attempted to attach strace to one of the logstash processes with higher CPU load and was returned the following over and over:

```
futex(0x7f31cc0b3d28, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x7f31cc03f654, FUTEX_WAIT_PRIVATE, 1, NULL) = 0
futex(0x7f31cc03f628, FUTEX_WAIT_PRIVATE, 2, NULL) = 0
futex(0x7f31cc03f628, FUTEX_WAKE_PRIVATE, 1) = 0
...
```

Out of curiosity I modified the nice level on one of the busier processes from 19 to 0. during this time a couple of extra logs did filter through to host2.

In the error log for logstash i received the following:

```
Exception in thread "|worker" java.lang.UnsupportedOperationException
       at java.lang.Thread.stop(Thread.java:869)
       at org.jruby.RubyThread.exceptionRaised(RubyThread.java:1221)
       at org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:112)
       at java.lang.Thread.run(Thread.java:745)
```

Other then the start message in the .log file no other logstash log files contained any further information. 

Apologies if the above is a little woolly.

Does anyone have an idea of what could be going wrong here ?
certainly willing to provide further diags here, however I have had to restart the process to get it going again. I'd estimate that it will fall over again tomorrow so there may be some delay in finding information.

Something in the back of my mind says that I may have over done it on the FTARGET matching but would/should it really bring it down like this?

**Comment by suyograo** [comment] 2015-09-14 16:33
@ackackack What's the size of events flowing into Logstash? 

`Exception in thread "|worker" java.lang.UnsupportedOperationException` typically means you have run out of heap space. Logstash default heap size is 500MB which maybe too small for your usecase. I would try increasing it using `LS_HEAP_SIZE`.

As a related note, we are trying to:
1) Improve the error message when Logstash runs out of memory https://github.com/elastic/logstash/issues/3817
2) Increase default heap size https://github.com/elastic/logstash/issues/3861

**Comment by ackackack** [comment] 2015-09-14 17:31
Hi!
Thanks for pointing this out.

Yes, it has been left as the default heapsize of 500m I've increased this to 1300m and restarted.
If it were going to fail again i'd be expecting it to be about this time tomorrow (~17:00Z)


We are basically logging the output of a couple of web filters. These filters logs would contain the domain that was hit plus the path and/or the query string. So "http://www.naughtywebsite.com/naught/things/bad.file" would get kicked out as "domain='www.naughtywebsite.com' url='/naughty/things/bad.file'" with a few extra bits on too like src IP etc etc

So they can be variable in length.

in terms of frequency however, we are still finding out feet on this as its quite new. So far its been upwards of 1000 entries per second.
 I shall update you as i get more info...

**Comment by ackackack** [comment] 2015-09-17 09:54
This seems to have stayed up and running for longer this time but has fallen over this morning at about 0759z

This was present in the error log:

Exception in thread "<udp" Exception in thread "|worker" java.lang.UnsupportedOperationException
        at java.lang.Thread.stop(Thread.java:869)
        at org.jruby.RubyThread.exceptionRaised(RubyThread.java:1221)
        at org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:112)
        at java.lang.Thread.run(Thread.java:745)
java.lang.UnsupportedOperationException
        at java.lang.Thread.stop(Thread.java:869)
        at org.jruby.RubyThread.exceptionRaised(RubyThread.java:1221)
        at org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:112)
        at java.lang.Thread.run(Thread.java:745)


I've bumped the heap size up again and restarted with the usual kill -9 java the /etc/init.d/logstash start

**Comment by ackackack** [comment] 2015-09-23 15:05
**Update**:
I've had it running a lot longer this time by removing the TCP listener from the configuration. 
Now it only listens on the UDP port 5140.
it seems to have been stable now since late thursday last week.

The heap size has remained unchanged since.

**Comment by suyograo** [comment] 2015-09-24 00:02
@ackackack thanks for the update. Can you add back the tcp input and see if we can reproduce the behavior. This could be a memory leak in the tcp plugin

**Comment by ackackack** [comment] 2015-09-28 10:40
The configuration without the tcp listener died yesterday (2015.09.27) at about midday
It seems to have died in the same way as before. processes are non responsive and have to be killed with killall -9 java

Its been restarted with the tcp listener back in play as requested. We'll see how this goes...

**Comment by ackackack** [comment] 2015-10-02 14:56
Curiously the process is yet to fall over in its current state.
TCP listeners remain in play and the process is still processing the logs as per the configuration.
I think this issue lies more in the heap size thing than anything else.

**Comment by ackackack** [comment] 2015-11-23 13:21
Sadly this still seems to be an issue...
I'm in a state now where the process will run for a few day's then fall over
in some situations the memory is maxed out and in other situations the java processes just go away. ( dont appear to have been killed by the kernel and no users have been on the box )

I've made a few changes to the config recently and added in the KV module in the filter section simply because it makes it easier to do the filters on the entries.


My configuration now looks like this:

Input Section:
````
input {
   udp {
     port => 5140
     type => "syslog"
     tags => [ "syslog-plain" ]
   }
}
````


Filter Section:
````
filter {
if [program] == "" {
     mutate {
         replace => ["program", "unknown"]
     }
}
if "syslog-plain" in [tags] {
     grok {
       match => [ "host", "%{IP:source_host}(:%{POSINT:source_port})?" ]
     }
     dns {
       reverse => [ "source_host" ]
       action => "replace"
     }
     grok {
         match => [ "message", "(<%{POSINT:syslog_pri}>)?%{SYSLOGTIMESTAMP:syslog_timestamp} %{SYSLOGHOST:syslog_hostname} %{DATA:syslog_program}(?:\[%{POSINT:syslog_pid}\])?: %{GREEDYDATA:syslog_message}" ]
     }

    kv { }

  grok {
    patterns_dir => "/etc/logstash/patterns"
    match => { "devid" => "%{FGTARGET}" }
    add_tag => ["target_to_host2"]
 }

  grok {
    patterns_dir => "/etc/logstash/patterns"
    match => { "device_id" => "%{FGT2}" }
    add_tag => ["target_to_host2"]
 }
}
}
````
If I tweak the filters above and add more patterns i can make logstash crash faster.



and the output section:
````
output {

file {
  message_format => "%{message}"
  path => "/home/logstash/%{+YYYY}/%{+MM}/%{+dd}/%{source_host}.log"
}

if "target_to_host2" in [tags] {
  udp {
    host => "<host2>"
    port => 514
    codec => "plain"
  }

}

udp {
  host => "<host3>"
  port => 514
  codec => "plain"
}

}
````

Is there anything in the config here that looks obviously wrong?

My pattern file has the following:

````
FGTARGET2 (fgxxxxxxxxxxxxxx|fgxxxxxxxxxxxxxx|fgxxxxxxxxxxxxxx|fgxxxxxxxxxxxxxx|fgxxxxxxxxxxxxxx|fgxxxxxxxxxxxxxx|fgxxxxxxxxxxxxxx|fgxxxxxxxxxxxxxx)
FGT2 (fgxxxxxxxxxxxxxx)
````
In the FGTARGET2 entry there are 50 "FGxxxxxxxx" entries. I've truncated them for the purpose of this snippet.
There are two patterns here because one device i want to target spits out "device_id" instead of the others that spit out "dev_id"

The memory in the machine now sits at 3965GB     ( just shy of 4G )


I can see through htop that the memory for the java process increases over a day or so and can chew through about half of the ram 
When it stops passings logs and the processes are still present they are consuming almost all the memory and 100% of CPU. The processes are given the default nice level of 19 set from the init script in the package.
When its in this state the processes will not respond to conventional signals and they have to be killed with sigkill to make them go away.
If I tweak the nice levels of the processes one or two logs may creep through before it locks up again.

I have logstash version 1 5.5 installed on the system ( from the repo ) and its making use of jre1.8.0_60 provided by oracle.

DNS lookups are being performed for every log entry submitted to logstash ( as per the config ) so i've installed "unbound" on the box to cache these queries and the local dns configuration is set to talk to 127.0.0.1

I'm pretty sure this is some kind of memory leak. Question is what do I need to do to give you guys what you need to find and fix the issue ?

**Comment by ackackack** [comment] 2015-11-25 16:02
This is an image of the logstash output tailing off as the process dies:

![Logstash Output Drop](http://i.imgur.com/tRkpsTy.png)

The increase on the right hand side of the graph when I've manually restarted it.

**Comment by ackackack** [comment] 2015-12-14 17:04
Anyone ?

**Comment by talevy** [comment] 2017-02-17 17:24
Closing this issue since it has been open for a long time and we haven't received the details to debug it further. Please reopen a new issue if you still run into issues

**Closed by talevy** 2017-02-17 17:24 UTC
Labels: needs details
