### ISSUE TITLE
rspecTests[core tests] FAILED in logstash 7.17.9 

### ISSUE THREAD

**Issue by ambujkumar3** [elastic/logstash#14901] opened 2023-02-14 10:11 UTC
Logstash information:

Logstash 8.4.1 and 8.6.0 worked fine with build and all test case. But 7.17.9 build success but one test case failed. 

Plugins installed:
[plugin:install-default] Installing default plugins
Installing logstash-codec-avro, logstash-codec-cef, logstash-codec-collectd, logstash-codec-dots, logstash-codec-edn, logstash-codec-edn_lines, logstash-codec-es_bulk, logstash-codec-fluent, logstash-codec-graphite, logstash-codec-json, logstash-codec-json_lines, logstash-codec-line, logstash-codec-msgpack, logstash-codec-multiline, logstash-codec-netflow, logstash-codec-plain, logstash-codec-rubydebug, logstash-filter-aggregate, logstash-filter-anonymize, logstash-filter-cidr, logstash-filter-clone, logstash-filter-csv, logstash-filter-date, logstash-filter-de_dot, logstash-filter-dissect, logstash-filter-dns, logstash-filter-drop, logstash-filter-elasticsearch, logstash-filter-fingerprint, logstash-filter-geoip, logstash-filter-grok, logstash-filter-http, logstash-filter-json, logstash-filter-kv, logstash-filter-memcached, logstash-filter-metrics, logstash-filter-mutate, logstash-filter-prune, logstash-filter-ruby, logstash-filter-sleep, logstash-filter-split, logstash-filter-syslog_pri, logstash-filter-throttle, logstash-filter-translate, logstash-filter-truncate, logstash-filter-urldecode, logstash-filter-useragent, logstash-filter-uuid, logstash-filter-xml, logstash-input-azure_event_hubs, logstash-input-beats, logstash-input-couchdb_changes, logstash-input-dead_letter_queue, logstash-input-elasticsearch, logstash-input-exec, logstash-input-file, logstash-input-ganglia, logstash-input-gelf, logstash-input-generator, logstash-input-graphite, logstash-input-heartbeat, logstash-input-http, logstash-input-http_poller, logstash-input-imap, logstash-input-jms, logstash-input-pipe, logstash-input-redis, logstash-input-s3, logstash-input-snmp, logstash-input-snmptrap, logstash-input-sqs, logstash-input-stdin, logstash-input-syslog, logstash-input-tcp, logstash-input-twitter, logstash-input-udp, logstash-input-unix, logstash-integration-elastic_enterprise_search, logstash-integration-jdbc, logstash-integration-kafka, logstash-integration-rabbitmq, logstash-output-cloudwatch, logstash-output-csv, logstash-output-elasticsearch, logstash-output-email, logstash-output-file, logstash-output-graphite, logstash-output-http, logstash-output-lumberjack, logstash-output-nagios, logstash-output-null, logstash-output-pipe, logstash-output-redis, logstash-output-s3, logstash-output-sns, logstash-output-sqs, logstash-output-stdout, logstash-output-tcp, logstash-output-udp, logstash-output-webhdfs

JVM:
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
openjdk version "11.0.18" 2023-01-17
OpenJDK Runtime Environment Temurin-11.0.18+10 (build 11.0.18+10)
OpenJDK 64-Bit Server VM Temurin-11.0.18+10 (build 11.0.18+10, mixed mode)

https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.18%2B10/OpenJDK11U-jdk_ppc64le_linux_hotspot_11.0.18_10.tar.gz
export JAVA_TOOL_OPTIONS="-Dfile.encoding=UTF8"
export JAVA_HOME=/usr/local/jdk-11.0.18+10/
export PATH=$PATH:/usr/local/jdk-11.0.18+10/bin
ln -sf /usr/local/jdk-11.0.18+10/bin/java /usr/bin/

OS version:
uname -r
4.18.0-240.22.1.el8_3.ppc64le
cat /etc/os-release
NAME="Red Hat Enterprise Linux"
VERSION="8.7 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.7"
PLATFORM_ID="platform:el8

Description of the problem including expected versus actual behavior:
all test case passing in 8.4.1 and 8.6.1 but failed on 7.17.9 current release version.

Steps to reproduce:

# Install latest version of Ruby using rvm
curl -sSL https://rvm.io/mpapis.asc | gpg2 --import -
curl -sSL https://rvm.io/pkuczynski.asc | gpg2 --import -
curl -sSL https://get.rvm.io | bash -s stable --ruby
source /usr/local/rvm/scripts/rvm
rvm install ruby 2.6.0
gem install rake
gem install bundler -v 2.3.26
rvm install "jruby-9.2.20.1"

# install logstash
cd $WORKDIR
git clone https://github.com/elastic/logstash.git
cd logstash
git checkout $PACKAGE_VERSION
git apply new_logstash.patch
sed -i '2d' ./rakelib/artifacts.rake
rake bootstrap
rake plugin:install-default
# Test logstash
./gradlew test

through ./gradlew test all test case and test suite is passing in 8.4.0 and upstream version
but one test case fail on 7.17.9
    Failed examples:
    rspec './logstash-core/spec/logstash/agent_spec.rb[1:2:1:11:1:3]' # LogStash::Agent using persisted queue behaves like all Agent tests metrics after config reloading when reloading a good config increases the successful reload count
    rspec './logstash-core/spec/logstash/agent_spec.rb[1:2:1:11:1:4]' # LogStash::Agent using persisted queue behaves like all Agent tests metrics after config reloading when reloading a good config does not set the failure reload timestamp
    rspec './logstash-core/spec/logstash/agent_spec.rb[1:2:1:11:1:6]' # LogStash::Agent using persisted queue behaves like all Agent tests metrics after config reloading when reloading a good config does not set the last reload error
    rspec './logstash-core/spec/logstash/agent_spec.rb[1:2:1:11:1:1]' # LogStash::Agent using persisted queue behaves like all Agent tests metrics after config reloading when reloading a good config resets the pipeline metric collector
    rspec './logstash-core/spec/logstash/agent_spec.rb[1:2:1:11:1:5]' # LogStash::Agent using persisted queue behaves like all Agent tests metrics after config reloading when reloading a good config sets the success reload timestamp
    rspec './logstash-core/spec/logstash/agent_spec.rb[1:2:1:11:1:2]' # LogStash::Agent using persisted queue behaves like all Agent tests metrics after config reloading when reloading a good config does not reset the global event count
    rspec './logstash-core/spec/logstash/agent_spec.rb[1:1:1:11:1:3]' # LogStash::Agent using memory queue behaves like all Agent tests metrics after config reloading when reloading a good config increases the successful reload count
    rspec './logstash-core/spec/logstash/agent_spec.rb[1:1:1:11:1:2]' # LogStash::Agent using memory queue behaves like all Agent tests metrics after config reloading when reloading a good config does not reset the global event count
    rspec './logstash-core/spec/logstash/agent_spec.rb[1:1:1:11:1:5]' # LogStash::Agent using memory queue behaves like all Agent tests metrics after config reloading when reloading a good config sets the success reload timestamp
    rspec './logstash-core/spec/logstash/agent_spec.rb[1:1:1:11:1:1]' # LogStash::Agent using memory queue behaves like all Agent tests metrics after config reloading when reloading a good config resets the pipeline metric collector
    rspec './logstash-core/spec/logstash/agent_spec.rb[1:1:1:11:1:6]' # LogStash::Agent using memory queue behaves like all Agent tests metrics after config reloading when reloading a good config does not set the last reload error
    rspec './logstash-core/spec/logstash/agent_spec.rb[1:1:1:11:1:4]' # LogStash::Agent using memory queue behaves like all Agent tests metrics after config reloading when reloading a good config does not set the failure reload timestamp
    Randomized with seed 53851
org.logstash.RSpecTests > rspecTests[core tests] FAILED
    java.lang.AssertionError: RSpec test suite `core tests` saw at least one failure.
        at org.junit.Assert.fail(Assert.java:88)
        at org.logstash.RSpecTests.rspecTests(RSpecTests.java:76)
----------------------------------------------------------------------
|  Results: FAILURE (74 tests, 71 successes, 1 failures, 2 skipped)  |
----------------------------------------------------------------------
74 tests completed, 1 failed, 2 skipped
> Task :logstash-core:rubyTests FAILED
FAILURE: Build failed with an exception.

Any pointers to resolve the failures would be of great help.

**Comment by robbavey** [comment] 2024-12-19 14:09
Not able to reproduce. Closing. Please open an issue if you continue to have build issues

**Closed by robbavey** 2024-12-19 14:09 UTC
Labels: bug, status:needs-triage, Team:Logstash
