### ISSUE TITLE
logstash configuration files in json

### ISSUE THREAD

**Issue by jloveric** [elastic/logstash#5854] opened 2016-09-01 18:32 UTC
This is actually a feature request.  As far as I can tell, the logstash configuration file is a non standard file format...  So I've been looking for parsers.  It would be useful if logstash configuration files could be written in json or some other standard format so that they could be easily parsed and generated from existing tools.  I'm generating logstash files from node.js

input : {
         stdin : {}
}

**Comment by wiibaa** [comment] 2016-09-01 19:16
@jloveric can you please upvote existing => https://github.com/elastic/logstash/issues/3600 and close this one

**Comment by jordansissel** [comment] 2016-09-01 19:35
Closing this as a duplicate of #3600.

**Closed by jordansissel** 2016-09-01 19:35 UTC
