### ISSUE TITLE
http_proxy and https_proxy NullPointerException

### ISSUE THREAD

**Issue by primarycircle** [elastic/logstash#9089] opened 2018-02-02 17:17 UTC
When trying to install a plugin for Logstash through a *NIX/Linux proxy, if the proxy address doesn't start with 'http://' or 'https://' a NullPointerException is thrown.

- Version: 6.1.3
- Operating System: CentOS Linux release 7.4.1708 (Core)
- Steps to Reproduce:

```bash
[root@thorin ~]# export http_proxy=this-awesome-proxy.this.net:8181
[root@thorin ~]# export https_proxy=this-awesome-proxy.this.net:8181
[root@thorin ~]# /usr/share/logstash/bin/logstash-plugin install logstash-output-syslog
```
```bash
[root@thorin ~]# export http_proxy=http://this-awesome-proxy.this.net:8181
[root@thorin ~]# export https_proxy=http://this-awesome-proxy.this.net:8181
[root@thorin ~]# /usr/share/logstash/bin/logstash-plugin install logstash-output-syslog
```

![logstashproxybug_20180202](https://user-images.githubusercontent.com/5704950/35745941-07fa3244-0813-11e8-8a7a-0bd84f56581f.PNG)

The final command will work as expected and inherit the proxy correctly.

**Comment by tsg** [comment] 2018-04-09 16:48
This looks like a dupe of #9132, which is fixed and will be released with 6.3.0.

**Closed by tsg** 2018-04-09 16:48 UTC
Labels: bug
