### ISSUE TITLE
Logstash stuck on “Sending bulk of actions to client” - multiline issues in logstash 1.5.0beta

### ISSUE THREAD

**Issue by deezx** [elastic/logstash#2440] opened 2015-01-27 14:46 UTC
In logstash 1.5.0beta, when there are several filters configured ( I have~8 grok filters, multiline and json filters), logstash gets stuck when sending bulk to elasticsearch.

I tried playing with the amount of filters to see if that what causes the issue.
- Only multiline and json filters configured - all works well
- Only grok filters configured - all works well

But when combining them all together, logstash starts to work but just gets stuck at a very early point on "Sending bulk of actions to client". 
When I remove only the multiline filter - all works well.

I'm using logstash 1.5.0beta and ES 1.4.2

Thanks.

**Comment by suyograo** [comment] 2015-01-27 22:12
hi @deezx we fixed some issues in multiline filter post beta1. Can you try with version `0.1.4` of the multiline filter? In your Logstash, do:

```
bin/plugin update logstash-filter-multiline
```

Let us know if this fixes it

**Comment by deezx** [comment] 2015-01-28 14:16
Thanks @suyograo , I've updated the logstash-filter-multiline to version 0.1.4. First logstash didn't like the upgrade and crashed with this exception:
"The error reported is: 
 multiline must set a milestone. For more information about plugin milestones, see http://logstash.net/docs/1.5.0.beta1/plugin-milestones"

I manually fixed it by adding a milestone to multiline.rb
After that logstash managed to start but it got stuck on the same problem - "Sending bulk of actions to client". 

When removing multiline filter from the configuration, it resumed working fine.

**Comment by suyograo** [comment] 2015-01-28 17:32
ok, can you provide us a sample config that fails and sample log line which triggers it? We'll reproduce it.

**Comment by deezx** [comment] 2015-02-01 08:45
ok, this is my indexer configuration -

input {
kafka {
        zk_connect => "<kafka_server1>:2181,<kafka_server2>:2181/kafka_logstash"
        topic_id => "logstash"
        consumer_threads => 10 
 }
}
filter {

multiline {
        pattern => "(^\s)|(^INFO.+)|(^SEVERE.+)"
        what => "previous"
        add_tag => ["multiline_new"]
        stream_identity => '%{host}.%{file}.%{type}'
   }
    
if [type] == "apache-access" {
   grok {
        break_on_match => false
        match => { "message" => "%{IPORHOST:clientip} %{USER:ident} %{USER:auth} \[%{HTTPDATE:timestamp}\] \"(?:%{WORD:method} %{NOTSPACE:request}(?: HTTP/%{NUMBER:httpversion})?|%{DATA:rawrequest})\" %{NUMBER:response} (?:%{NUMBER:bytes}|-)" }
        match => { "message" => "\[%{HTTPDATE:timestamp}\] %{IPORHOST:clientip} %{WORD:protocol} %{NOTSPACE:crypt} \"(?:%{WORD:method} %{NOTSPACE:request}(?: HTTP/%{NUMBER:httpversion})?|%{DATA:rawrequest})\" " }
        match => { "message" => "\[%{DAY} %{MONTH} %{MONTHDAY} %{TIME} %{YEAR}\] \[%{NOTSPACE:apacheseverity}\] %{GREEDYDATA:message_remainder}" }
        match => { "message" => "%{GREEDYDATA:message}" }
        add_tag => [ "apache", "grokked" ]
        }
}
}
		
output {

elasticsearch {
    host => "<ES_VIP>"
    port => "9300"
    index => "logstash-%{+YYYY.MM.dd}"
    cluster => "elasticsearchcluster"
    embedded => false
    node_name => "logstash"
    workers => 4
  }
}   



I have more grok filters but the problem reproduce with this configuration as well.
These are the log lines I managed to identify as related, didn't see any exceptions -

Sending bulk of actions to client[0]: <ES_VIP> {:level=>:debug, :file=>"logstash/outputs/elasticsearch.rb", :line=>"443"}

Thanks

**Comment by jordansissel** [comment] 2016-03-09 00:09
Is this still an issue?

**Comment by untergeek** [comment] 2016-03-11 16:57
Closing this as there's been many fixes to multiline since more than a year ago.  Feel free to re-open at https://github.com/logstash-plugins/logstash-output-elasticsearch with more details if this is still an issue.  We'd love to squash any bugs, but this now belongs in its own dedicated repository.

**Closed by untergeek** 2016-03-11 16:57 UTC
Labels: needs details
