### ISSUE TITLE
Make start scripts work with cygwin

### ISSUE THREAD

**Issue by BoronNitride** [elastic/logstash#1524] opened 2014-07-11 07:07 UTC
Because of the path name mess in MS Windows the following changes are needed to start logstash with cygwin bash:
```
bin/logstash 
22d21
<
24,26d22
< if [[ "$OSTYPE" == "cygwin" ]] ; then
<     basedir=`cygpath -m ${basedir}`
< fi


bin/logstash.lib.sh bin
2,4d1
< if [[ "$OSTYPE" == "cygwin" ]] ; then
<     basedir=`cygpath -m ${basedir}`
< fi
```

**Comment by cleiter** [comment] 2015-04-01 13:27
+1
I can confirm that this is needed with cygwin and that the patch works as expected.

**Comment by suyograo** [comment] 2015-05-29 16:36
This has been fixed in https://github.com/elastic/logstash/commit/6cb438d7fc56e93b99d1e766a5b6573012d979f2

**Closed by suyograo** 2015-05-29 16:36 UTC

**Comment by cleiter** [comment] 2015-06-10 08:27
@suyograo I don't see how that commit would fix that, since it only touches the `.bat` file but under cygwin `logstash` is executed.
