### ISSUE TITLE
The error reported is: \n  uninitialized constant Concurrent::Delay::Executor" in Logstash-1.5.4

### ISSUE THREAD

**Issue by gugansankar** [elastic/logstash#3776] opened 2015-08-22 08:47 UTC
Logstash stopped if I insert lumberjack input configuration. But Strange part is, it doesn't tell me when I do configtest. It says " Everything is OK".

This is the error message logged in the log file,

{:timestamp=>"2015-08-22T08:28:52.633000+0000", :message=>"The error reported is: \n  uninitialized constant Concurrent::Delay::Executor"}

Note: But there is no issue with other input configurations like tcp, collectd [ those input method I have tried so far]. 

only problem with lumberjack input .

Is this a bug in new release or Did I make any mistake in the configuration ?.

Note : I'm using the same configuration in logstash-1.5.3 that doesn't hit with the problem. 

My Configuration : 
input {
 tcp {
    port => 5000
    type => "logs"
}
 udp {
port => 25827
codec => collectd { }
type => "collectd"
}

lumberjack {
  port => 5055
  type => "logs"
  ssl_certificate => "/etc/pki/tls/certs/test.example.com.crt"
  ssl_key => "/etc/pki/tls/private/test.example.com.key"
}

}

output {
stdout { codec => rubydebug } 
}

**Comment by gugansankar** [comment] 2015-08-22 08:51
Forgot to mention, I have re-installed logstash-1.5.4 package. Though, problem is still persist. 

So I'm planning to downgrade it to logstash-1.5.3 but this version too hit with ""'[DEPRECATED] use `require 'concurrent'` instead of `require 'concurrent_ruby'`"" warning bug.  

I saw there was a fix for 1.5.3 Deprecated warning bug issue. I will use it for meanwhile until get a resolution for 1.5.4 packge issue

**Comment by ph** [comment] 2015-08-22 19:43
Update your plugin to the latest version.  We hav4 released a fix after the release.  bin/plugin update logstash-input-lumberjack and it should fix this issue.

**Comment by stevenyu530** [comment] 2015-08-27 16:00
I am using the latest 1.0.5 version of lumberjeack plug in, and the received the same error. 
The logstash i m using is 1.5.4 on Linux.
Anyone have ideas about how to fix?

**Comment by ph** [comment] 2015-08-28 13:02
@gugansankar I've tested your config with the stock 1.5.4 release and I was able to reproduce your issue with your configuration. If you update the lumberhack input the issue goes away, you can update it with the following command:

``bin/plugin update logstash-input-lumberjack``

**Comment by ph** [comment] 2015-08-28 13:04
@stevenyu530 can you gist your configuration and the version of all the installed plugins?

Running this command will give you all the version.
``bin/plugin list --verbose``

**Comment by stevenyu530** [comment] 2015-08-28 13:40
@ph the version of the all plugins are

**Comment by stevenyu530** [comment] 2015-08-28 13:43
@ph my forwarder config is this:

"network": {
		"servers": [ "aaa.bbb.ccc:5043" ],
		"ssl ca": "D:\\logstash-forwarder\\SSL\\logstash-server.crt",
		"timeout": 15
	},
"files": [
		{
			"paths": ["D:\\log\\*-cache-size.txt"],
			"fields": { "type": "cache_size", "service": "coh"}
		}
]

**Comment by stevenyu530** [comment] 2015-08-28 13:45
@ph and my logstash config is:

input{
	lumberjack {
		port => 5043
		ssl_certificate => "/home/logstash-config/logstash-server.crt"
		ssl_key => "/home/logstash-config/logstash-server.key"
	}
}

output{
	stdout { 
		codec => rubydebug 
	}
}

**Comment by stevenyu530** [comment] 2015-08-28 13:46
many thanks in advance!

**Comment by gugansankar** [comment] 2015-08-31 05:37
@stevenyu530 , Are you sure , this version too have same problem logstash-input-lumberjack (1.0.5) ? 

@ph, Could you please let know which version we have to get it try to setup ?.

**Comment by LordWingZero** [comment] 2015-08-31 15:47
Running: ```/opt/logstash/bin/plugin/update logstash-input-lumberjack``` fixed my problem.

Logstash: 1.5.4
Luberjack: 1.0.5

**Comment by ph** [comment] 2015-09-01 13:21
@gugansankar @stevenyu530 updating to lumberjack 1.0.5 should have fixed this issue, @gugansankar are you running a similar configuration than @stevenyu530 ?

**Comment by gugansankar** [comment] 2015-09-01 13:35
I'm going to test it now.

**Comment by gugansankar** [comment] 2015-09-01 14:07
@ph , Its working fine once I update the lumberjack to 1.0.5 . Thanks :)

-----------------------------------------------
@ph, As you mentioned, Steps I followed to get it work 

After installed Logstash-1.5.4,  just start it with default configuration

[root@6bb6bb674138 conf.d]# /opt/logstash/bin/plugin list --verbose | grep lumberjack
logstash-input-lumberjack (1.0.5)
logstash-output-lumberjack (1.0.2)
[root@6bb6bb674138 conf.d]# 
[root@6bb6bb674138 conf.d]# /etc/init.d/logstash start
/etc/init.d/logstash: line 63: ulimit: open files: cannot modify limit: Operation not permitted
logstash started.
[root@6bb6bb674138 conf.d]# /etc/init.d/logstash status 
logstash is running
[root@6bb6bb674138 conf.d]# /etc/init.d/logstash status
logstash is not running
[root@6bb6bb674138 conf.d]# 

Here, Logstash stopped with same error as shown below,

[root@6bb6bb674138 conf.d]# tail /var/log/logstash/logstash.log 
{:timestamp=>"2015-09-01T13:53:53.542000+0000", :message=>"The error reported is: \n  uninitialized constant Concurrent::Delay::Executor"}
[root@6bb6bb674138 conf.d]# 

As said by @ph , I did update the lumberjack input plugin by using below command,

[root@6bb6bb674138 conf.d]# /opt/logstash/bin/plugin update logstash-input-lumberjack
Updating logstash-input-lumberjack
Updated logstash-input-lumberjack 1.0.4 to 1.0.5
[root@6bb6bb674138 conf.d]# 

And start the Logstash again and this time it didn't get stopped. its running smoothly
 
--------------------------------------------------------------

@stevenyu530 , Can you make sure that you have tried the same step as I mentioned ?.

**Comment by stevenyu530** [comment] 2015-09-02 13:42
@gugansankar 
@ph : I update the logstash forwarder and reinstalled the new logstash and lumberjack plugins. problem fixed now. 
So, with the new logstash and plugins, it should solve the problem. I m thining it might be the actual forwarder that caused my early problem.

**Comment by ph** [comment] 2015-09-02 13:43
Thanks for updating this, the next release of logstash will contains the latest version of the plugins.

 I'll close this issue.

**Closed by ph** 2015-09-02 13:43 UTC
Labels: bug, v1.5.5

**Comment by ajsharp** [comment] 2015-09-06 21:36
It's probably worth noting that this problem exists with the 1.5.4 version of logstash packaged with homebrew. The plugin command seems to be out of date there (`plugin update` is not a command), though that may be an issue to take up with homebrew.

**Comment by ph** [comment] 2015-09-08 15:13
@ajsharp Thanks for bringing this up, yes this look like an issue with the homebrew package they don't include the `plugin` binary with the formula. ref: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/logstash.rb#L10

Would you mind creating an issue or a PR on the homebrew repository?

**Comment by ajsharp** [comment] 2015-09-08 17:46
Created an issue here: https://github.com/Homebrew/homebrew/issues/43710//

**Comment by splashx** [comment] 2015-09-10 17:46
/opt/logstash/bin/plugin update logstash-input-lumberjack fixes.

**Comment by alekseymykhailov** [comment] 2015-09-11 15:51
```
 dpkg -S /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-lumberjack-1.0.4
logstash: /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-lumberjack-1.0.4
```

logstash-input-lumberjack-1.0.4 included to the logstash DEB package 

```
 apt-cache show logstash
Package: logstash
Status: install ok installed
Priority: extra
Section: default
Installed-Size: 139746
Maintainer: <jenkins@slave12.build.ci.hetz.es.io>
Architecture: all
Version: 1:1.5.4-1
Depends: logrotate
Conffiles:
 /etc/default/logstash ac72257cd45e5de8f6799eaa5875bc04
 /etc/init.d/logstash 47d90631994ffa23eeef7c6748395a0d
 /etc/logrotate.d/logstash 38425b942183178628577e120c95035d
Description: An extensible logging pipeline
Description-md5: 2cc8837023e818d510770f6e573a838a
License: Apache 2.0
Vendor: Elasticsearch
Homepage: http://www.elasticsearch.org/overview/logstash/
```

I think it should be updated and repackaged ... 
thank you!

**Comment by nk-roddy** [comment] 2015-09-23 15:14
Sorry guys, but the problem still persist.

logstash-forwarder 0.4.0
logstash-input-lumberjack (1.0.5)
logstash-output-lumberjack (1.0.2)
logstash 1.5.4 and 1.5.5

error log:

{:timestamp=>"2015-09-23T16:10:20.047000+0100", :message=>"Lumberjack input: the pipeline is blocked, temporary refusing new connection.", :level=>:warn}


very simple logstash config:

    lumberjack {
        port => 5043
            ssl_certificate => "/etc/certs/star.ninja.public"
            ssl_key => "/etc/certs/star.ninja.private"
    }
}

filter {
  grok {
             match => [ "message", "%{COMBINEDAPACHELOG}" ]
   }
output{

    elasticsearch {
        host => "logstash.my-domain"
        port => 9200
        protocol => "http"
    }
}

**Comment by ph** [comment] 2015-09-23 17:11
@nk-roddy I have a few questions:
-  How many events are you generating? 
- Any errors related to the elasticsearch output in your log?
- Any errors on the elasticsearch side?

**Comment by sebastianhoitz** [comment] 2015-10-21 15:45
When I run the bin/update command it now wants me to update to 2.0.4. How can I select the 1.0.5 version?

**Comment by lmgray** [comment] 2015-10-26 21:25
@sebastianhoitz:

-bash-4.2$ sudo bin/plugin install --version 1.0.5 logstash-input-lumberjack
Validating logstash-input-lumberjack-1.0.5
Installing logstash-input-lumberjack
Installation successful

-bash-4.2$ sudo bin/plugin list --verbose logstash-input-lumberjack
logstash-input-lumberjack (1.0.5)

**Comment by DarshanDNA** [comment] 2015-12-07 11:57
please anyone tell me how to update kafka-output-plugin in logstash 1.5.4.
thanks
