### ISSUE TITLE
Help with installing and configuring Logstash/Kibana on windows 2012

### ISSUE THREAD

**Issue by stephenstroud** [elastic/logstash#2669] opened 2015-02-23 12:41 UTC
I've installed ElasticSearch 1.4.4 on windows successfully, however, having issues following the http://logstash.net/ guides.

I've used these instructions to install Logstash 1.4.2
https://github.com/verbosemode/public-notes/blob/master/logstash-windows.md

and used these instructions to configure ElasticSearch with Logstash
http://logstash.net/docs/1.4.2/tutorials/getting-started-with-logstash
However, the follow commands gives errors as show. Please help.
bin/logstash -e 'input { stdin { } } output { stdout {} }'
bin/logstash -e 'input { stdin { } } output { stdout { codec => rubydebug } }'

![logstashissue](https://cloud.githubusercontent.com/assets/7649287/6327888/314d138c-bb59-11e4-8d18-3198e1fb7fed.JPG)

**Comment by untergeek** [comment] 2015-02-23 18:12
I believe you omitted quotes around localhost:

```
logstash agent -e 'input { stdin {} } output { elasticsearch { host => "localhost" } }'
```

Omitting spaces at the end may be problematic, but the same rule applies to encapsulating localhost in quotes.

`rubydebug` does not need quotes because it is a codec, not a string (like the `host =>` directive requires, hence the quotes).

**Comment by ph** [comment] 2015-02-23 21:56
This is issue is similar to this one https://github.com/elasticsearch/logstash/issues/1426

**Comment by ph** [comment] 2015-02-23 22:02
Thank you for the bug report @stephenstroud 

1) I wasn't able to reproduce the `RubyIO.java` Error from your first command in the master branch, So I assume this is fixed.

2) I was able to reproduce the `= was unexpected at this time` error with the 1.4.2 release, but this is currently fixed in the master branch.

The 1.4.2 release seems to have a few problems parsing inline configuration, I suggest that you create a file for your config and use this command: `bin\logstash agent -f myconfig.conf`

**Comment by suyograo** [comment] 2016-01-14 01:12
1.5 and 2.1 has a bunch of fixes for Windows, please upgrade to that

**Closed by suyograo** 2016-01-14 01:12 UTC
