### ISSUE TITLE
--configtest doesn't detect relative path problems

### ISSUE THREAD

**Issue by chris-martin** [elastic/logstash#1609] opened 2014-08-07 07:36 UTC
My first attempt at a logstash config file:

```
input {
  file {
    path => "~/logs/*.log"
    start_position => beginning
  }
}
output {
  elasticsearch { host => localhost }
}
```

Configtest says it's okay.

```
$ logstash --configtest -f logstash.conf                                                                                                             
Using milestone 2 input plugin 'file'. This plugin should be stable, but if you see strange behavior, please let us know! For more information on plugin milestones, see http://logstash.net/docs/1.4.2/plugin-milestones {:level=>:warn}
Configuration OK
```

But apparently it isn't.

```
$ logstash -f logstash.conf                                                                                                                          

Using milestone 2 input plugin 'file'. This plugin should be stable, but if you see strange behavior, please let us know! For more information on plugin milestones, see http://logstash.net/docs/1.4.2/plugin-milestones {:level=>:warn}
+---------------------------------------------------------+
| An unexpected error occurred. This is probably a bug.   |
| You can find help with this problem in a few places:    |
|                                                         |
| * chat: #logstash IRC channel on freenode irc.          |
|     IRC via the web: http://goo.gl/TI4Ro                |
| * email: logstash-users@googlegroups.com                |
| * bug system: https://logstash.jira.com/                |
|                                                         |
+---------------------------------------------------------+
The error reported is: 
  File paths must be absolute, relative path specified: ~/logs/*.log
```

I assume this is a bug?

**Comment by untergeek** [comment] 2015-01-23 19:51
`--configtest` validates the configuration file syntax, rather than test all of the plugins.  So, this is not a bug.  

Closing.

**Comment by jordansissel** [comment] 2015-01-28 01:58
Hmm, I think this is a missed expectation where Logstash's config parser happens in phases and the --configtest only validates the syntax, not the values. I'd be willing to consider this a bug given that I think most humans are disinterested in the phases of Logstash's config parser operation and are expecting --configtest to tell them "Is this config probably OK?"

I say probably, because there are things that could change external to the config (mostly network-oriented, like dns or connectivity).

**Comment by jordansissel** [comment] 2015-01-28 01:59
Maybe we should do two things:
* Try to figure out if we can solve config validation to validate the path stuff
* Improve the config test wording to say "Configuration seems OK" or something generally to indicate that it's not 100% guaranteed (again, given network problems that, even if tested, could change externally)

**Comment by chris-martin** [comment] 2015-01-28 02:10
"Configuration syntax OK" would be direct and honest output.

**Comment by jordansissel** [comment] 2015-01-28 02:17
I think folks may have different expectations of what "syntax" means, so I'm not sure about that wording.

**Comment by jordansissel** [comment] 2015-01-28 02:19
In truth, I think when folks use "config test" modes, I believe they are expecting that a successful passing of this config test should mean that actually running the program normally will be successful. In cases like this, where technically the syntax is correct, but the configuration is still not correct, we'll be misleading folks. I don't want to hide behind a curtain of pedantry saying the config _syntax_ is correct but that the program is still invalid, ya know?

**Comment by chris-martin** [comment] 2015-01-28 02:48
Yes, I opened the issue because I agree :)

If that is infeasible or cannot happen quickly, I do think changing the
message would be a helpful stopgap. I object to the vagueness of "seems OK"
because if you're going to change the copy, might as well try to change it
to something that more precisely indicates what the program does. But I'll
cease going on about the color of this particular bikeshed now.

**Comment by purbon** [comment] 2015-05-22 11:57
Related to https://github.com/elastic/logstash/issues/3199 https://github.com/elastic/logstash/issues/2074 https://github.com/elastic/logstash/issues/3199

**Comment by purbon** [comment] 2015-05-22 12:25
Nowadays the config test is nowaday only checking for syntax and not content of it. I'll #3301 in benefit of where we can discuss the right solution for this kind of error. I will add a comment there regarding this specific issue.

**Closed by purbon** 2015-05-22 12:25 UTC
Labels: discuss, enhancement, known issue
