### ISSUE TITLE
Update Kafka compatibility matrix

### ISSUE THREAD

**Issue by acchen97** [elastic/logstash#6489] opened 2017-01-05 19:00 UTC
The Kafka compatibility matrix seems out of date. Looking at the [master docs](https://www.elastic.co/guide/en/logstash/master/plugins-inputs-kafka.html), it appears we need to add 0.10.1 and 0.10.1.1 support, and the Kerberos SASL security feature support we introduced in 5.1.

It also appears that the [output matrix](https://www.elastic.co/guide/en/logstash/master/plugins-outputs-kafka.html) is more updated than the input matrix. Regardless, the matrices will diverge now since 0.10.1.1 support was introduced in different minor versions of the plugins.

Kafka input
- 0.10.1.1 support - v6.2.2
- Kerberos SASL - v6.1.0

Kafka output
- 0.10.1.1 support - v6.1.2
- Kerberos SASL - v6.1.0

@dedemorton can you help with updating this?

/cc @suyograo @talevy 

Reference: https://github.com/elastic/enhancements/issues/1712

**Comment by dedemorton** [comment] 2017-01-05 19:09
@acchen97 Yes I was planning to look at that today, in fact. Part of the problem is that the changes in the Ruby source haven't propagated to the published plugin docs. But it looks like other info is missing as well. We probably need to start with the Ruby source and make manual changes to the generated files for anything that's missing from the current version of the docs.

**Comment by acchen97** [comment] 2017-01-05 19:42
Thanks @dedemorton let me know where I can help.

**Comment by dedemorton** [comment] 2017-01-05 19:54
@acchen97 alvin @tal  Is it just me, or do the x’s in the kafka support matrix make it easier to maintain the matrix, but harder for users to understand? Here’s what we have in the Ruby source code right now in master: https://github.com/logstash-plugins/logstash-input-kafka/blob/master/lib/logstash/inputs/kafka.rb#L15. This is the matrix that will appear for the next Logstash release (that's when we update the published docs). 

I’m trying to update the matrix in both input and output plugins based on Alvin’s suggestions, but we are moving towards being increasingly less specific about versions. I think someone started using x's because the matrix was getting out of date too quickly.  So do I just need to add Kerberos SASL to the Securities Features column and call it a day, or is there more work to be done here?

**Comment by allenmchan** [comment] 2017-01-05 22:52
@acchen97 there is no 0.10.1.11 release. Do you mean 0.10.1.1?

The kafka team is working on better client support strategy (forward and backwards compatibility  able) and that should make this a lot easier to manage.
https://cwiki.apache.org/confluence/display/KAFKA/KIP-97%3A+Improved+Kafka+Client+RPC+Compatibility+Policy

**Comment by suyograo** [comment] 2017-01-05 23:57
> I’m trying to update the matrix in both input and output plugins based on Alvin’s suggestions, but we are moving towards being increasingly less specific about versions. I think someone started using x's because the matrix was getting out of date too quickly. So do I just need to add Kerberos SASL to the Securities Features column and call it a day, or is there more work to be done here?

@dedemorton you are right that x's doesn't read well. For example, Kerberos support was added in plugin version 5.1.0 and 6.1.0. Earlier versions don't have SASL support. I don't know how we can fit this additional info in the table. Any ideas?

**Comment by acchen97** [comment] 2017-01-06 01:12
@allenmchan you're right, thanks for the correction. The better client support should surely help with integration. :)

**Comment by dedemorton** [comment] 2017-01-06 22:44
Closed by  logstash-plugins/logstash-input-kafka#162 and  logstash-plugins/logstash-output-kafka#111

**Closed by dedemorton** 2017-01-06 22:44 UTC
Labels: docs
