### ISSUE TITLE
logstash  plugin load error : 'cabin/metrics', 'cabin/log/logger', 'logstash::codecs::multiline::Grok' error

### ISSUE THREAD

**Issue by LiYuzhuo2020** [elastic/logstash#15988] opened 2024-03-11 06:49 UTC

**Comment by andsel** [comment] 2024-03-12 09:37
Hi @LiYuzhuo2020 thanks for reporting this and getting in touch about it.
However to investigate the root cause, we need your help and more information.
Could you provide a portion of your logs around the error, in particular the full stacktrace of the error and the message, please 🙏 ?

**Comment by LiYuzhuo2020** [comment] 2024-03-12 15:45
yes sure,

![image](https://github.com/elastic/logstash/assets/53847606/a329b225-3f25-46f6-adfd-8df8fa5ae1c2)

I created 11 pipelines and each pipeline has its own .conf file included in pipelines.yml, previosuly I'm using logstash7.16.3 but later upgraded to logstash8.12.2 after adjustment of the .conf file of each pipeline it succeeded to start up and works fine but if I restart it for about 3 to 5 times might encountered plugin load error, one of plugin error shows above screenshot, each pipeline can has this plugin load error. After encountered that plugin error I can restart it without any changes it might turn to normal, this is quietly strange, there's no syntax error and all the required plugins installed properly. And if I changed back to 7.16.3 there never has such strange thing

**Comment by LiYuzhuo2020** [comment] 2024-03-12 15:53
and for the plugin load error 'logstash::codecs::multiline' GROK I think it's throwed here

logstash-codec-multiline:

def register
    ###  when require grok-pure it will failed to require it and throw error unable to configure plugin : "grok-pure/discovery"
    require "grok-pure" # rubygem 'jls-grok' 
    require 'logstash/patterns/core'

    # Detect if we are running from a jarfile, pick the right path.
    patterns_path = []
    patterns_path += [LogStash::Patterns::Core.path]

    @grok = Grok.new

    @patterns_dir = patterns_path.to_a + @patterns_dir
    @patterns_dir.each do |path|
      if ::File.directory?(path)
        path = ::File.join(path, "*")
      end

      Dir.glob(path).each do |file|
        @logger.debug("Grok loading patterns from file", :path => file)
        @grok.add_patterns_from_file(file)
      end
    end

**Comment by LiYuzhuo2020** [comment] 2024-03-13 02:18
tried, those errors still remains

such as

![image](https://github.com/elastic/logstash/assets/53847606/5779e7b6-866c-4097-987e-b6fa47ba4099)

**Comment by andsel** [comment] 2024-03-13 08:10
Hi @LiYuzhuo2020 thanks for confirming, maybe it's related to the fact that in JRuby patch doesn't change so much, maybe worthwhile to test also with a previous minor JRuby (`9.3.10.0`) which was shipped with Logstash `8.9.2`. 
However, I would like to be able to reproduce locally, could you share more on your environment, please?
- jvm.options
- pipelines definitions
- first line of logs when you start Logstash (around `Starting Logstash`), where Logstash prints, JVM version, OS, CPU arch, set of startup flags etc.

**Comment by LiYuzhuo2020** [comment] 2024-03-13 08:42
HI @andsel ， thanks for your investigation

1. we're using the default jvm options that logstash8.12.2 packed in the tar file
2. about the pipeline definitions the structure like this

pipeline.id
pipeline.workers 1 
pipeline.batch.size 1
pipeline.conf

3. shows below

![image](https://github.com/elastic/logstash/assets/53847606/e0acd81e-cf2a-4edd-b0f2-29eca498f778)

**Comment by LiYuzhuo2020** [comment] 2024-03-15 02:11
Hi @andsel , how's your progress, is this a bug or just need myself to adjust the configuration file?

**Comment by LiYuzhuo2020** [comment] 2024-03-16 13:32
sometimes even cannot find the 'add_patterns_from_file' method ...

**Comment by andsel** [comment] 2024-03-22 10:37
Hi @LiYuzhuo2020, no sorry no news, the information provided is not of much value. To try to understand what's happening the log (in textual form and not image) should be provided, and must cover from the start of Logstash till the reported error. Maybe better at debug level (start Logstash with `--debug`).

We have to figure out how to reproduce, so if you can isolate a minimal pipeline definition that manifest the problem with a certain probability would be great. Without that it's hard to share what's the problem.

**Comment by LiYuzhuo2020** [comment] 2024-03-22 15:13
I found this error log

illegal access of jruby

![image](https://github.com/elastic/logstash/assets/53847606/e34394f4-3854-4da0-83d2-3afc7700e152)

**Comment by LiYuzhuo2020** [comment] 2024-03-25 03:49
Hi @andsel thanks for your information, I followed your advice commented out other pipeline and investigate one by one finally found out the cause, it's due to one of my pipeline has timestamp convert error

**Comment by andsel** [comment] 2024-03-25 09:05
Great @LiYuzhuo2020 ! Once it's fixed for you, please 🙏  close the issue.

**Comment by LiYuzhuo2020** [comment] 2024-03-26 08:22
Hi @andsel , the issue looks like caused by the default geoIp database, I disabled it, it's much stable now.

but sometimes when start above 10 times there still has the probability occurring the 'string index out of range -1 ' without any plugin load error . I'm quiet confused about that why don't raise some more useful information when configure failed but raised the illegalStateException 囧

**Comment by LiYuzhuo2020** [comment] 2024-03-29 06:06
Hi @andsel , sorry still need your professional help, I degrade the version to 8.9.2 it never has the restart plugin load error but when the version back to 8.12.2 it will have the plugin load error after I restarted for about 10 + times .

**Closed** 2024-03-29 06:08 UTC
