### ISSUE TITLE
[regression] Conditionals spread across multiple lines now fail

### ISSUE THREAD

**Issue by lgoldstein** [elastic/logstash#3257] opened 2015-05-17 09:59 UTC
Version 1.4.2
```
:~/logstash-1.4.2/bin$ ./logstash -f ../../downloads/logstash-vmerlin.conf -t
Using milestone 1 filter plugin 'ruby'. This plugin should work, but would benefit from use by folks like you. Please let us know if you find bugs or have suggestions on how to improve this plugin.  For more information on plugin milestones, see http://logstash.net/docs/1.4.2/plugin-milestones {:level=>:warn}
Configuration OK
```
Version 1.5.0 - same computer, configuration file, Java, Ruby, everything - only different _logstash_ version
```
:~/logstash-1.5.0/bin$ ./logstash -f ../../downloads/logstash-vmerlin.conf -t
SyntaxError: (eval):1045: syntax error, unexpected kAND
          and ("syslog5424-timestamp" in [tags])
            ^
        eval at org/jruby/RubyKernel.java:1107
  initialize at /home/lgoldstein/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0-java/lib/logstash/pipeline.rb:30
     execute at /home/lgoldstein/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0-java/lib/logstash/agent.rb:109
         run at /home/lgoldstein/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0-java/lib/logstash/runner.rb:87
        call at org/jruby/RubyProc.java:271
         run at /home/lgoldstein/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0-java/lib/logstash/runner.rb:92
        call at org/jruby/RubyProc.java:271
  initialize at /home/lgoldstein/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/stud-0.0.19/lib/stud/task.rb:12
```

**Comment by purbon** [comment] 2015-05-17 10:01
@lgoldstein It would be very nice if you can share your configuration.

**Comment by lgoldstein** [comment] 2015-05-17 10:10
@purbon See https://gist.github.com/lgoldstein/898b1a92a9e435c29116

**Comment by purbon** [comment] 2015-05-17 10:16
thanks a lot @lgoldstein

**Comment by zhenghu** [comment] 2015-05-18 14:29
I meet the same issue for keyword `or` which works well in logstash-1.4.2

Here is the error : 
 ```
 (eval):22100: syntax error, unexpected kOR
        or ([type] == "logstash-indexer-input-atc")
 ```

Here is the config : 
 ```
     if     ([type] == "logstash-indexer-input-aqz")
        or ([type] == "logstash-indexer-input-atc")
        or ([type] == "logstash-indexer-input-lpc")
        or ([type] == "logstash-indexer-input-lpt")
        or ([type] == "logstash-indexer-input-lsp")
        or ([type] == "logstash-indexer-input-lvision")
        or ([type] == "logstash-indexer-input-ndr")
        or ([type] == "logstash-indexer-input-sik") {

        mutate {
            add_tag => [ "_grokparsefailure" ]
        }
    }
 ```

**Comment by Mogztter** [comment] 2015-05-19 08:01
Duplicate of #2850 ?

**Comment by purbon** [comment] 2015-05-19 08:02
Yes, I agree.

**Comment by jordansissel** [comment] 2015-05-19 19:18
Let's close this and move the discussion to this ticket: https://github.com/elastic/logstash/issues/2850

**Closed by jordansissel** 2015-05-19 19:18 UTC
Labels: bug, unconfirmed, v1.5.1
