### ISSUE TITLE
Cannot create pipeline {:reason> "Expected one of #, if, \"

### ISSUE THREAD

**Issue by Titusp12** [elastic/logstash#10713] opened 2019-04-23 21:09 UTC
input {
	file{ 
		path => "\c:\Users\joyde\Desktop\cars\autos.csv"
		start_position => "beginning"
		sincedb_path => "\dev\null"
	
}
}
filter {
	csv {
		separator => ","

		columns => [ "maker", "model", "mileage", "manufacture_year", "engine_displacement", "engine_power", "body_type", "color_slug", "stk_year", "transmission", "door_count", "seat_count", "fuel_type", "date_created", "date_last_seen", "price_eur" ]
	}
{

mutate {convert => ["mileage", "integer"] }
mutate {convert => ["price_eur", "float"] }
mutate {convert => ["engine_power", "integer"] }
mutate {convert => ["door_count", "integer"] }
mutate {convert => ["seat_count", "integer"] }

}

output {
	elasticsearch {
		hosts => "localhost:9200"
		index => "cars"
		document_type => "sold_cars"
	}
	stdout {}
}

**Comment by synapticiel** [comment] 2019-04-24 10:23
Need to close filter

input {
	file {
	path => "c:/Users/joyde/Desktop/cars/autos.csv"
	start_position => "beginning"
	sincedb_path => "/Users/joyde/Desktop/cars/sincedb_file.txt"

}
}

filter {
	csv {
	separator => ","
		columns => [ "maker", "model", "mileage", "manufacture_year", "engine_displacement", "engine_power", "body_type", "color_slug", "stk_year", "transmission", "door_count", "seat_count", "fuel_type", "date_created", "date_last_seen", "price_eur" ]
	}

mutate {convert => ["mileage", "integer"] }
mutate {convert => ["price_eur", "float"] }
mutate {convert => ["engine_power", "integer"] }
mutate {convert => ["door_count", "integer"] }
mutate {convert => ["seat_count", "integer"] }

}

output {
	elasticsearch {
	hosts => "localhost:9200"
	index => "cars"
	document_type => "sold_cars"
}
	stdout {}
}

**Comment by danhermann** [comment] 2019-04-24 14:55
Since this is a general usage question and not a reproducible bug report or a feature request, I am closing this issue.

>Please post all product and debugging questions on our forum.
>Your questions will reach our wider community members there, and if we confirm that there is a bug, then we can open a new issue here.
>
>-- Logstash Issue Template

Please open a thread on the [forum](https://discuss.elastic.co/c/logstash) if you need additional assistance although it looks as if @synapticiel's suggestion is correct.

**Closed by danhermann** 2019-04-24 14:55 UTC
