### ISSUE TITLE
IN condition not working with arrays containing URL or IP?

### ISSUE THREAD

**Issue by davidloubere** [elastic/logstash#1565] opened 2014-07-23 09:17 UTC
Running Logstash 1.4.1, the following conditions are not working:

    if [data][request][referer] in [ "http://example.com/route1", "http://example.com/route2" ] {
        # do stuff
    }

    if [data][request][client_ip] in [ "66.249.78.4", "66.249.78.60" ] {
        # do stuff
    }

Note that the fields shown in the left part of the above conditions are given as an example.

**Comment by jordansissel** [comment] 2015-01-23 23:36
@davidloubere can you show a sample event? This works for me:

```
% bin/logstash -e 'input { stdin { codec => json } } filter { if [data][request][referer] in [ "http://example.com/route1", "http://example.com/route2" ] { mutate { add_tag => "HURRAY" } } }'

--- Input:
{ "data": { "request": { "referer": "http://example.com/route1" } } }
--- Output:
{
  "data"       => {
    "request" => {
      "referer" => "http://example.com/route1"
    }
  },
  "@version"   => "1",
  "@timestamp" => "2015-01-23T23:35:50.715Z",
  "host"       => "Macintosh.lan",
  "tags"       => [
    [0] "HURRAY"
  ]
}
```

It adds the tag as configured.

**Comment by purbon** [comment] 2015-05-22 10:27
@davidloubere @jordansissel did the same test as jordan with logstash 1.5 

```
╭─purbon@purbon-elastic  ~/work/logstash  ‹master*› 
╰─$ bin/logstash -e 'input { stdin { codec => json } } filter { if [data][request][referer] in [ "http://example.com/route1", "http://example.com/route2" ] { mutate { add_tag => "HURRAY" } } }'
Logstash startup completed
{ "data": { "request": { "referer": "http://example.com/route1" } } }
{
          "data" => {
        "request" => {
            "referer" => "http://example.com/route1"
        }
    },
      "@version" => "1",
    "@timestamp" => "2015-05-22T10:25:18.670Z",
          "host" => "purbon-elastic.local",
          "tags" => [
        [0] "HURRAY"
    ]
}
```

everything works as expected. It would be very nice to have your input event, so we can reproduce it. Was the event json? text?

**Comment by jsvd** [comment] 2016-03-11 16:24
unknown if this was an actual issue, closing..

**Closed by jsvd** 2016-03-11 16:24 UTC
Labels: needs details

**Comment by ptc-mrucci** [comment] 2016-11-16 14:26
In case others fall into the same mistake, the `in` operator fails "by design" when the array contains a single element.
This is because the syntax is ambiguous and access to a field `[field_name]` is indistinguishable from an array with a single element `["array_value"]`.

This might or might not be obvious (it wasn't for me).
