### ISSUE TITLE
output.plugin.syslog, variable for target dont work

### ISSUE THREAD

**Issue by titusx-gmx-de** [elastic/logstash#9233] opened 2018-03-13 10:22 UTC
Please post all product and debugging questions on our [forum](https://discuss.elastic.co/c/logstash). Your questions will reach our wider community members there, and if we confirm that there is a bug, then we can open a new issue here.

Logstash Plugins are located in a different organization: https://github.com/logstash-plugins. For bugs on specific Logstash plugins, for example, if Redis Output has a defect, please open it in the respective Redis Output repository. 

For all general issues, please provide the following details for fast resolution:

- Version: 1:5.6.8-1

- Operating System: Ubuntu 16.04.4 LTS

- Config File (if you have sensitive info, please remove it):

```
input {
        udp {
                port => 514
                tags => ["input.syslog"]
        }
}
filter {
        if "input.syslog" in [tags] and [logsource] =~ /yoursystem/ {
                mutate {
                        add_tag => "output.syslog"
                        add_field => { "@output.syslog.to" => "192.168.11.222" }
                }
        }
}
output {
        if "output.syslog" in [tags] {
                syslog {
# reference dont work, no output, no error message:
#                      host => "%{@output.syslog.to}"
# address works:
                        host => "192.168.11.222"
                        port => "514"
                }
        }
}
```

- Sample Data:

- Steps to Reproduce:

**Comment by yaauie** [comment] 2018-03-19 19:23
It looks like this is a duplicate of a previously-reported issue on the syslog output plugin https://github.com/logstash-plugins/logstash-output-syslog/issues/44, which I recently converted to an enhancement request; hopefully the following provides context:

> This plugin works by opening a persistent connection and sending packets over that connection; it does not perform per-event string interpolation on the `host` field because doing so would require a new connection for each possible resulting value, which would in turn require overhead about managing and sharing those connections.
> 
> It would be entirely possible to implement this, and we would gladly work with community contributions to add this functionality.
> 
> I've opened an [enhancement issue](https://github.com/logstash-plugins/logstash-output-syslog/issues/47); please feel free to track it over there and/or help us implement :)
> -- [@yaauie on logstash-plugins/logstash-output-syslog/issues#44](https://github.com/logstash-plugins/logstash-output-syslog/issues/44#issuecomment-374336353)

**Closed** 2018-03-19 19:24 UTC

**Comment by Elctro** [comment] 2018-03-19 20:10
What a shame. This leaves us no option but to give up on logstash as this functionality is easier to implement from scratch rather than update it in logstash itself.
