### ISSUE TITLE
configureArtifactInfo gradle task needs build version to exist

### ISSUE THREAD

**Issue by jsvd** [elastic/logstash#13030] opened 2021-06-29 13:43 UTC
Gradle won't build when configured with a version that doesn't exist yet in the artifacts-api endpoint. For example, when building 8.0.0-alpha1-SNAPSHOT:

```
~/elastic/logstash master*
❯ VERSION_QUALIFIER=alpha1 ./gradlew configureArtifactInfo       
FAILURE: Build failed with an exception.

* Where:
Build file '/tmp/elastic/logstash/build.gradle' line: 172

* What went wrong:
A problem occurred evaluating root project 'logstash'.
> Could not create task ':copyEs'.
   > Could not create task ':downloadEs'.
      > Could not create task ':configureArtifactInfo'.
         > could not find the current artifact from the artifact-api https://artifacts-api.elastic.co/v1/versions for 8.0.0-alpha1
```

**Comment by andsel** [comment] 2021-07-01 10:36
The problem is that the task `configureArtifactInfo` retrieve the json content from `https://artifacts-api.elastic.co/v1/versions/8.0.0-alpha1-SNAPSHOT/builds` (which doesn't yet exist) but it retrieves it during Gradle task configuration phase, and this error break the configuration phase also if we asked to run a task which doesn't need the download of Elasticsearch, like for example a `clean`.
I think that moving all the configuration of these task in the `doLast {}` part of each task could fix the problem, because the `doLast` is processed only during the "execution" phase of Gradle and not during the "configuration"

**Comment by andsel** [comment] 2021-07-01 11:01
I've drafted the idea in #13042 but moving to execution phase we loose the input/output task definitions

**Closed** 2021-07-12 07:08 UTC
Labels: bug, build, status:needs-triage, v8.0.0
