### ISSUE TITLE
LS 2.4.0 beats SSL input: unsupported ciphersuite

### ISSUE THREAD

**Issue by buzzdeee** [elastic/logstash#6121] opened 2016-10-26 06:21 UTC
Hi,

I recently updated from LS 2.3.4 to 2.4.0 and found my beats plugin not working anymore.

My LS config for the input plugin looks like:

```
      beats {
        port => 12344
        ssl => true
        ssl_certificate => "/etc/logstash/logstash.crt"
        ssl_key => "/etc/logstash/logstash.key"
        ssl_certificate_authorities => [ "/etc/logstash/logstash-ca.crt" ]
        ssl_verify_mode => "force_peer"
        type => "logs"
      }
```

The private key is converted to pkcs8 format.

Filebeat 1.3.1 is installed, and my filebeat config looks like:

```
    filebeat:
      spool_size: 2048
      idle_timeout: 5s
      registry_file: ".filebeat"
      publish_async: false
      config_dir: "/etc/filebeat/conf.d"
    output:
      logstash:
        hosts:
        - logstash:12344
        index: logstash
        tls:
          certificate_authorities:
          - "/etc/filebeat/ca.pem"
          certificate: "/etc/filebeat/logstash.pem"
          certificate_key: "/filebeat/logstash.pem"
          min_version: '1.2'
```

LS itself starts up fine, but when the filebeat agent connects I get the following message in the LS logs:

`{:timestamp=>"2016-10-24T11:11:48.384000+0200", :message=>"Looks like you either have an invalid key or your private key was not in PKCS8 format.", :exception=>java.lang.IllegalArgumentException: Unsupported ciphersuite TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA38, :level=>:error}`

downgrading to LS 2.3.4 without any config change, filebeat has no problem to connect to LS and works as expected.

I'm on a recent OpenBSD amd64 6.0-snapshot, LS runs with Java jdk-1.8.0.72p1.
Wading through java docs, I found that the TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 cipher suite is only available with jdk-1.8.0, and only for TLS1.2, that's why I forced filebeat to use TLS1.2.

Reading up on: https://www.elastic.co/guide/en/beats/filebeat/current/configuration-output-tls.html
I even tried to force cipher_suite in filebeat tls config:

```
    tls:
      cipher_suites:
        - 'ECDHE-RSA-AES-128-GCM-SHA256'
```

Then LS still throws error about TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA38

One thing I wonder is about the ciphersuite name from the logs, TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA38
sholdn't it be TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 ???

Anything I'm doing wrong? cluebats welcome ;)

Cheers,
Sebastian

**Comment by ph** [comment] 2016-10-26 12:58
@buzzdeee The name might differ a bit between the golang and the java implementation I will need to verify/test that scenario. There is also option on the beats input to restrict the TLS version to accept.

**Comment by buzzdeee** [comment] 2016-10-26 13:33
@ph I have the following configured in filebeat.yml:

```
output:
  logstash:
    hosts:
    - logstash:12344
    index: logstash
    tls:
      cipher_suites:
      - 'ECDHE-RSA-AES-128-GCM-SHA256'
      certificate_authorities:
      - "/etc/logstash/ca.pem"
      certificate: "/etc/logstash/mynode.pem"
      certificate_key: "/etc/logstash/mynode.key"
      min_version: '1.2'
```
are you talking about the min_version option, or do you mean something else?
also, I defined the cipher_suites: array in filebeat as you see, but even with this completely different cipher suite, LS is whining about TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA38, instead of the 
one I configured.

**Comment by ph** [comment] 2016-10-26 13:41
> are you talking about the min_version option, or do you mean something else?

There is an option on the logstash beats input called `tls_min_version`

So you configure `ECDHE-RSA-AES-128-GCM-SHA256` in filebeat and beats input yield `TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA38` this is odd.

Can you start logstash in with `--log.level debug` and add the relevent details from the beats input. The input should be pretty verbose on a new connection about what cipher is enabled.

**Comment by ph** [comment] 2016-10-26 13:42
Just to be clear 2.3.4 -> 2.4.0 beats input is a complete rewrite from the ground up.

**Comment by ph** [comment] 2016-10-26 15:30
I have tested yet, but should it be `ECDHE-RSA-AES128-GCM-SHA256` instead of `ECDHE-RSA-AES-128-GCM-SHA256`  

I think the openssl naming doesn't have a `-` before the 128, but golang uses their own crypto implementation.

In the Netty code base when I search for ciphers I see only this difference.
https://github.com/netty/netty/blob/eb7f751ba519cbcab47d640cd18757f09d077b55/handler/src/test/java/io/netty/handler/ssl/CipherSuiteConverterTest.java#L47

**Comment by buzzdeee** [comment] 2016-10-26 17:34
I got the cipher suite names (cut 'n paste) for the cipher I configured from here:
https://www.elastic.co/guide/en/beats/filebeat/1.3/configuration-output-tls.html

anyways, will now check to get the debug log output from the beats input plugin.

**Comment by buzzdeee** [comment] 2016-10-26 18:54
Here we go, got the output from 
grep -i beats logstash.log

```
{:timestamp=>"2016-10-26T19:44:15.534000+0200", :message=>"Plugin not defined in namespace, checking for plugin file", :type=>"input", :name=>"beats", :path=>"logstash/inputs/beats", :level=>:debug, :file=>"logstash/plugin.rb", :line=>"86", :method=>"lookup"}
{:timestamp=>"2016-10-26T19:44:15.867000+0200", :message=>"config LogStash::Inputs::Beats/@port = 12344", :level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"154", :method=>"config_init"}
{:timestamp=>"2016-10-26T19:44:15.871000+0200", :message=>"config LogStash::Inputs::Beats/@ssl = true", :level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"154", :method=>"config_init"}
{:timestamp=>"2016-10-26T19:44:15.875000+0200", :message=>"config LogStash::Inputs::Beats/@ssl_certificate = \"/etc/logstash/logstash.crt\"", :level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"154", :method=>"config_init"}
{:timestamp=>"2016-10-26T19:44:15.879000+0200", :message=>"config LogStash::Inputs::Beats/@ssl_key = \"/etc/logstash/logstash.key\"", :level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"154", :method=>"config_init"}
{:timestamp=>"2016-10-26T19:44:15.883000+0200", :message=>"config LogStash::Inputs::Beats/@ssl_certificate_authorities = [\"/etc/logstash/logstash-ca.crt\"]", :level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"154", :method=>"config_init"}
{:timestamp=>"2016-10-26T19:44:15.888000+0200", :message=>"config LogStash::Inputs::Beats/@ssl_verify_mode = \"force_peer\"", :level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"154", :method=>"config_init"}
{:timestamp=>"2016-10-26T19:44:15.892000+0200", :message=>"config LogStash::Inputs::Beats/@type = \"logs\"", :level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"154", :method=>"config_init"}
{:timestamp=>"2016-10-26T19:44:15.897000+0200", :message=>"config LogStash::Inputs::Beats/@codec = <LogStash::Codecs::Plain charset=>\"UTF-8\">", :level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"154", :method=>"config_init"}
{:timestamp=>"2016-10-26T19:44:15.901000+0200", :message=>"config LogStash::Inputs::Beats/@add_field = {}", :level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"154", :method=>"config_init"}
{:timestamp=>"2016-10-26T19:44:15.905000+0200", :message=>"config LogStash::Inputs::Beats/@host = \"0.0.0.0\"", :level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"154", :method=>"config_init"}
{:timestamp=>"2016-10-26T19:44:15.909000+0200", :message=>"config LogStash::Inputs::Beats/@include_codec_tag = true", :level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"154", :method=>"config_init"}
{:timestamp=>"2016-10-26T19:44:15.914000+0200", :message=>"config LogStash::Inputs::Beats/@ssl_handshake_timeout = 10000", :level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"154", :method=>"config_init"}
{:timestamp=>"2016-10-26T19:44:15.918000+0200", :message=>"config LogStash::Inputs::Beats/@congestion_threshold = 5", :level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"154", :method=>"config_init"}
{:timestamp=>"2016-10-26T19:44:15.933000+0200", :message=>"config LogStash::Inputs::Beats/@target_field_for_codec = \"message\"", :level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"154", :method=>"config_init"}
{:timestamp=>"2016-10-26T19:44:15.937000+0200", :message=>"config LogStash::Inputs::Beats/@tls_min_version = 1", :level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"154", :method=>"config_init"}
{:timestamp=>"2016-10-26T19:44:15.984000+0200", :message=>"config LogStash::Inputs::Beats/@tls_max_version = 1.2", :level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"154", :method=>"config_init"}
{:timestamp=>"2016-10-26T19:44:15.997000+0200", :message=>"config LogStash::Inputs::Beats/@cipher_suites = [\"TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA38\", \"TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384\", \"TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256\", \"TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256\", \"TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384\", \"TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384\", \"TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256\"]", :level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"154", :method=>"config_init"}
{:timestamp=>"2016-10-26T19:44:16.008000+0200", :message=>"config LogStash::Inputs::Beats/@client_inactivity_timeout = 15", :level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"154", :method=>"config_init"}
{:timestamp=>"2016-10-26T19:44:28.078000+0200", :message=>"Beats inputs: Starting input listener", :address=>"0.0.0.0:12344", :level=>:info, :file=>"logstash/inputs/beats.rb", :line=>"153", :method=>"register"}
{:timestamp=>"2016-10-26T19:44:34.305000+0200", :message=>"Looks like you either have an invalid key or your private key was not in PKCS8 format.", :level=>:error, :file=>"logstash/inputs/beats/message_listener.rb", :line=>"57", :method=>"onChannelInitializeException"}
{:timestamp=>"2016-10-26T19:45:17.334000+0200", :message=>"Looks like you either have an invalid key or your private key was not in PKCS8 format.", :level=>:error, :file=>"logstash/inputs/beats/message_listener.rb", :line=>"57", :method=>"onChannelInitializeException"}
{:timestamp=>"2016-10-26T19:46:03.259000+0200", :message=>"Looks like you either have an invalid key or your private key was not in PKCS8 format.", :level=>:error, :file=>"logstash/inputs/beats/message_listener.rb", :line=>"57", :method=>"onChannelInitializeException"}
{:timestamp=>"2016-10-26T19:46:47.373000+0200", :message=>"Looks like you either have an invalid key or your private key was not in PKCS8 format.", :level=>:error, :file=>"logstash/inputs/beats/message_listener.rb", :line=>"57", :method=>"onChannelInitializeException"}
{:timestamp=>"2016-10-26T19:47:33.251000+0200", :message=>"Looks like you either have an invalid key or your private key was not in PKCS8 format.", :level=>:error, :file=>"logstash/inputs/beats/message_listener.rb", :line=>"57", :method=>"onChannelInitializeException"}
{:timestamp=>"2016-10-26T19:48:17.413000+0200", :message=>"Looks like you either have an invalid key or your private key was not in PKCS8 format.", :level=>:error, :file=>"logstash/inputs/beats/message_listener.rb", :line=>"57", :method=>"onChannelInitializeException"}
{:timestamp=>"2016-10-26T19:49:03.324000+0200", :message=>"Looks like you either have an invalid key or your private key was not in PKCS8 format.", :level=>:error, :file=>"logstash/inputs/beats/message_listener.rb", :line=>"57", :method=>"onChannelInitializeException"}
{:timestamp=>"2016-10-26T19:49:47.480000+0200", :message=>"Looks like you either have an invalid key or your private key was not in PKCS8 format.", :level=>:error, :file=>"logstash/inputs/beats/message_listener.rb", :line=>"57", :method=>"onChannelInitializeException"}
{:timestamp=>"2016-10-26T19:50:33.333000+0200", :message=>"Looks like you either have an invalid key or your private key was not in PKCS8 format.", :level=>:error, :file=>"logstash/inputs/beats/message_listener.rb", :line=>"57", :method=>"onChannelInitializeException"}
{:timestamp=>"2016-10-26T19:51:17.487000+0200", :message=>"Looks like you either have an invalid key or your private key was not in PKCS8 format.", :level=>:error, :file=>"logstash/inputs/beats/message_listener.rb", :line=>"57", :method=>"onChannelInitializeException"}
{:timestamp=>"2016-10-26T19:52:03.379000+0200", :message=>"Looks like you either have an invalid key or your private key was not in PKCS8 format.", :level=>:error, :file=>"logstash/inputs/beats/message_listener.rb", :line=>"57", :method=>"onChannelInitializeException"}
{:timestamp=>"2016-10-26T19:52:47.529000+0200", :message=>"Looks like you either have an invalid key or your private key was not in PKCS8 format.", :level=>:error, :file=>"logstash/inputs/beats/message_listener.rb", :line=>"57", :method=>"onChannelInitializeException"}
{:timestamp=>"2016-10-26T19:53:33.404000+0200", :message=>"Looks like you either have an invalid key or your private key was not in PKCS8 format.", :level=>:error, :file=>"logstash/inputs/beats/message_listener.rb", :line=>"57", :method=>"onChannelInitializeException"}
{:timestamp=>"2016-10-26T19:54:17.566000+0200", :message=>"Looks like you either have an invalid key or your private key was not in PKCS8 format.", :level=>:error, :file=>"logstash/inputs/beats/message_listener.rb", :line=>"57", :method=>"onChannelInitializeException"}
{:timestamp=>"2016-10-26T19:55:03.432000+0200", :message=>"Looks like you either have an invalid key or your private key was not in PKCS8 format.", :level=>:error, :file=>"logstash/inputs/beats/message_listener.rb", :line=>"57", :method=>"onChannelInitializeException"}
{:timestamp=>"2016-10-26T19:55:47.602000+0200", :message=>"Looks like you either have an invalid key or your private key was not in PKCS8 format.", :level=>:error, :file=>"logstash/inputs/beats/message_listener.rb", :line=>"57", :method=>"onChannelInitializeException"}
{:timestamp=>"2016-10-26T19:55:53.553000+0200", :message=>"Looks like you either have an invalid key or your private key was not in PKCS8 format.", :level=>:error, :file=>"logstash/inputs/beats/message_listener.rb", :line=>"57", :method=>"onChannelInitializeException"}
{:timestamp=>"2016-10-26T19:56:03.975000+0200", :message=>"stopping", :plugin=>"LogStash::Inputs::Beats", :level=>:debug, :file=>"logstash/inputs/base.rb", :line=>"81", :method=>"do_stop"}
{:timestamp=>"2016-10-26T19:56:03.998000+0200", :message=>"closing", :plugin=>"LogStash::Inputs::Beats", :level=>:debug, :file=>"logstash/plugin.rb", :line=>"37", :method=>"do_close"}

```
I got a bit curious now, since there seems to be a cipher_suites parameter for the beats plugin, so I tried to set that to:
Then I found this (no idea why I haven't seen that parameter before):
https://www.elastic.co/guide/en/logstash/2.4/plugins-inputs-beats.html#plugins-inputs-beats-cipher_suites

And there the odd cipher comes from.

```
  beats {
    port => 12344
    ssl => true
    ssl_certificate => "/etc/logstash/logstash.crt"
    ssl_key => "/etc/logstash/logstash.key"
    ssl_certificate_authorities => [ "/etc/logstash/logstash-ca.crt" ]
    ssl_verify_mode => "force_peer"
    cipher_suites => [ 'TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384', 'TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256', 'TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384', 'TLS_ECDHE_RSA_WITH_
AES_128_GCM_SHA256', 'TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256', 'TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384' ]
    type => "logs"
  }
```

with that I get now is:

```
{:timestamp=>"2016-10-26T20:36:08.608000+0200", :message=>"Looks like you either have an invalid key or your private key was not in PKCS8 format.", :exception=>java.lang.IllegalArgumentException: Cannot support TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 with currently installed providers, :level=>:error}
{:timestamp=>"2016-10-26T20:36:32.938000+0200", :message=>"Pipeline main started"}
{:timestamp=>"2016-10-26T20:36:34.222000+0200", :message=>"Looks like you either have an invalid key or your private key was not in PKCS8 format.", :exception=>java.lang.IllegalArgumentException: Cannot support TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 with currently installed providers, :level=>:error}
```

alright, so next try, in LS just changing cipher_suites to:

`cipher_suites => [ 'TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256' ]`

and in filebeat.yml:



```
   tls:
      cipher_suites:
      - 'ECDHE-ECDSA-AES-128-GCM-SHA256'
```

Then no error messages about the cipher suite anymore, but then still no luck to get them working, now in filebeat I only see:

Oct 26 20:52:48 galen /usr/local/bin/filebeat[49204]: transport.go:125: SSL client failed to connect with: EOF



That seems to be a workaround now for me, since

**Comment by ph** [comment] 2016-10-26 20:33
I can reproduce your scenario with openssl's s_client.

```
input {
    beats{
        ssl => true
        port => 5055
        ssl_certificate => "/Users/ph/es/certificates/certificate.crt"
        ssl_key => "/Users/ph/es/certificates/certificate.key"
        #cipher_suites => ["TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256"]
        tls_min_version => "1.2"
    }
}
```

```
openssl s_client -connect localhost:5055 -CAfile ~/es/certificates/certificate.crt -tls1_2 -cipher ECDHE-ECDSA-AES128-GCM-SHA256
```

Resulting with a `NO_SHARED_CIPHER` error when we run logstash debug mode.

The thing is this cipher is in listed in the default cipher list see https://github.com/logstash-plugins/logstash-input-beats/blob/master/src/main/java/org/logstash/netty/SslSimpleBuilder.java#L42

---
But lets say that we use another cipher in the standard default list `TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256` and use use *s_client*/tls1.2 with `ECDHE-RSA-AES128-GCM-SHA256`, this call will succeed and any other cipher will fail.

**Result**
```
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES128-GCM-SHA256
    Session-ID: FA1D558F25F5FF964A6EAA6742F3A247D66BCF3F67AFE653BBB7A951D9D8B847
    Session-ID-ctx:
    Master-Key: FEBD9BBDDBB3312562E37FE784A443CAA004FE45EE2177636CC9C573FE929FB76A3EE13C51CBEAD7EA3EB999308FE930
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1477512970
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
```


Concerning the default cipher list `TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA38` should be `TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384` we are missing a 4. I will make a PR for that.

So since the underlying library didn't catch the previous error, maybe the ciphers definition is problematic here. 

I will revise it and we really need an integration test for it.

**Comment by buzzdeee** [comment] 2016-10-26 21:48
\o/

you can reproduce it great, I don't feel alone anymore ;)

Even better, using the ciphers you proposed, filebeat indeed is able again to log to LS.
Now I have to tell my Puppet to reconfigure everything, and voila, back in business.
Then at least my home network has proper log collection again ;)

thanks a lot for help so far.

**Comment by ph** [comment] 2016-10-27 03:34
@buzzdeee Usually you shouldn't need to specify a list of ciphers to logstash we should just pickup the best we can in the context, minus the bug we had with name of the cipher.

The client and server is configured to take the higher protocol, TLS 1.2 in this case and the priority of the ciphers from the list, unless you really want to reject inferior protocol. I would just use the default.

**Comment by buzzdeee** [comment] 2016-10-27 06:07
yeah, that's what I was thinking as well how it's supposed to work, and with next release, I'll remove the hardcoded cipher suites again (hopefully ;)

**Comment by ph** [comment] 2016-10-31 13:53
I've pushed a PR there for review. https://github.com/logstash-plugins/logstash-input-beats/pull/156

**Comment by jordansissel** [comment] 2016-11-10 07:10
Want to close this and move to the beats input repo?

**Comment by ph** [comment] 2016-11-16 15:44
The PR was merged with the fix, closing this.

**Closed by ph** 2016-11-16 15:44 UTC
Labels: bug in plugin
