### ISSUE TITLE
[enhancement] Add cache configuration to logstash-filter-http

### ISSUE THREAD

**Issue by pdscopes** [elastic/logstash#10517] opened 2019-03-06 15:38 UTC
Logstash http filter should have an additional configuration option to cache the response from the remote RESTful API. This could be done in two ways: 
1.  Following the `Cache-Control`, `Pragma`, or `Expires` header returned.
2.  Allow the logstash configuration file to define the cache length.

This would be beneficial because it would:
1.  Increase the performance of the filter as it would not need to wait for the remote API to respond.
2.  Reduce the load on the remote API.

**Comment by yaauie** [comment] 2019-03-06 21:10
@pdscopes I agree, and we've already got an open issue to track the enhancement request.

I'm closing this issue as duplicate of https://github.com/logstash-plugins/logstash-filter-http/issues/10

**Closed by yaauie** 2019-03-06 21:10 UTC
