### ISSUE TITLE
Getting error while sending data from logstash to elasticsearch

### ISSUE THREAD

**Issue by betheman** [elastic/logstash#14489] opened 2022-09-03 14:09 UTC
I'm publishing logs from filebeat to redis and then from redis  logstash is reading data When i'm sending 500 loglines then it is working fine but when logline is around 1000 or more then it is giving below error.

MacBook Pro (16-inch, 2019)
Processor:2.3 GHz 8-Core Intel Core i9
Memory:16 GB 2667 MHz DDR4

Elasticsearch version:8.4.1
Logstash version:8.4.1
Filebeat version:8.4.1

logstash.conf:
input {
  redis {
    host => "localhost"
    key => "xyzlogs"
    data_type => "channel"
  }
}

 
filter {
  mutate {
        split => ["message", "|"]
        add_field => { "p1" => "%{[message][0]}" }
        add_field => { "p2" => "%{[message][1]}" }
        add_field => { "p3" => "%{[message][2]}" }
        add_field => { "p4" => "%{[message][3]}" }
        add_field => { "p4" => "%{[message][4]}" }
        add_field => { "p5" => "%{[message][5]}" }
        add_field => { "p6" => "%{[message][6]}" }
        add_field => { "p7" => "%{[message][7]}" }
        add_field => { "p8" => "%{[message][8]}" }
        add_field => { "p9" => "%{[message][9]}" }
        add_field => { "p10" => "%{[message][10]}" }
        add_field => { "p11" => "%{[message][11]}" }
        add_field => { "p12" => "%{[message][12]}" }
        add_field => { "p13" => "%{[message][13]}" }
        add_field => { "aggregation_key" => "%{[message][1]}|%{[message][2]}|%{[message][3]}|%{[message][11]}|%{[message][5]}|%{[message][7]}|%{[message][8]}|%{[message][9]}|%{[message][22]}|%{[message][21]}" }
  }
  mutate { 
        remove_field => ["message"] 
  } 
}
 
output {
   
  stdout {
    codec => rubydebug
  }
 
  # Sending properly parsed log events to elasticsearch
  elasticsearch {
    hosts => ["localhost:9200"]
    index => "cds%{+YYYYMMdd}"
    manage_template => true
    template => "path"
    template_name => "logs_template"
    template_overwrite => true
  }
}

Error Message:

[2022-09-03T19:27:06,412][ERROR][logstash.outputs.elasticsearch][main][da267a1aa24b8b3ff5fc2f0a709e84be0001a7f8c3579bb7abd649b3618a0b1c] Attempted to send a bulk request but there are no living connections in the pool (perhaps Elasticsearch is unreachable or down?) {:message=>"No Available connections", :exception=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::NoConnectionAvailableError, :will_retry_in_seconds=>2}
[2022-09-03T19:27:06,845][WARN ][logstash.outputs.elasticsearch][main] Restored connection to ES instance {:url=>"http://localhost:9200/"}
[2022-09-03T19:27:08,109][INFO ][logstash.outputs.elasticsearch][main][da267a1aa24b8b3ff5fc2f0a709e84be0001a7f8c3579bb7abd649b3618a0b1c] Failed to perform request {:message=>"Connection reset", :exception=>Manticore::SocketException, :cause=>java.net.SocketException: Connection reset}
[2022-09-03T19:27:08,109][WARN ][logstash.outputs.elasticsearch][main][da267a1aa24b8b3ff5fc2f0a709e84be0001a7f8c3579bb7abd649b3618a0b1c] Marking url as dead. Last error: [LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError] Elasticsearch Unreachable: [http://localhost:9200/_bulk][Manticore::SocketException] Connection reset {:url=>http://localhost:9200/, :error_message=>"Elasticsearch Unreachable: [http://localhost:9200/_bulk][Manticore::SocketException] Connection reset", :error_class=>"LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError"}
[2022-09-03T19:27:08,110][ERROR][logstash.outputs.elasticsearch][main][da267a1aa24b8b3ff5fc2f0a709e84be0001a7f8c3579bb7abd649b3618a0b1c] Attempted to send a bulk request but Elasticsearch appears to be unreachable or down {:message=>"Elasticsearch Unreachable: [http://localhost:9200/_bulk][Manticore::SocketException] Connection reset", :exception=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError, :will_retry_in_seconds=>4}
[2022-09-03T19:27:08,141][INFO ][logstash.outputs.elasticsearch][main][da267a1aa24b8b3ff5fc2f0a709e84be0001a7f8c3579bb7abd649b3618a0b1c] Failed to perform request {:message=>"Connection reset", :exception=>Manticore::SocketException, :cause=>java.net.SocketException: Connection reset}
[2022-09-03T19:27:08,142][WARN ][logstash.outputs.elasticsearch][main][da267a1aa24b8b3ff5fc2f0a709e84be0001a7f8c3579bb7abd649b3618a0b1c] Marking url as dead. Last error: [LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError] Elasticsearch Unreachable: [http://localhost:9200/_bulk][Manticore::SocketException] Connection reset {:url=>http://localhost:9200/, :error_message=>"Elasticsearch Unreachable: [http://localhost:9200/_bulk][Manticore::SocketException] Connection reset", :error_class=>"LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError"}
[2022-09-03T19:27:08,143][ERROR][logstash.outputs.elasticsearch][main][da267a1aa24b8b3ff5fc2f0a709e84be0001a7f8c3579bb7abd649b3618a0b1c] Attempted to send a bulk request but Elasticsearch appears to be unreachable or down {:message=>"Elasticsearch Unreachable: [http://localhost:9200/_bulk][Manticore::SocketException] Connection reset", :exception=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError, :will_retry_in_seconds=>4}
[2022-09-03T19:27:08,146][INFO ][logstash.outputs.elasticsearch][main][da267a1aa24b8b3ff5fc2f0a709e84be0001a7f8c3579bb7abd649b3618a0b1c] Failed to perform request {:message=>"Connection reset", :exception=>Manticore::SocketException, :cause=>java.net.SocketException: Connection reset}
[2022-09-03T19:27:08,147][WARN ][logstash.outputs.elasticsearch][main][da267a1aa24b8b3ff5fc2f0a709e84be0001a7f8c3579bb7abd649b3618a0b1c] Marking url as dead. Last error: [LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError] Elasticsearch Unreachable: [http://localhost:9200/_bulk][Manticore::SocketException] Connection reset {:url=>http://localhost:9200/, :error_message=>"Elasticsearch Unreachable: [http://localhost:9200/_bulk][Manticore::SocketException] Connection reset", :error_class=>"LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError"}
[2022-09-03T19:27:08,147][ERROR][logstash.outputs.elasticsearch][main][da267a1aa24b8b3ff5fc2f0a709e84be0001a7f8c3579bb7abd649b3618a0b1c] Attempted to send a bulk request but Elasticsearch appears to be unreachable or down {:message=>"Elasticsearch Unreachable: [http://localhost:9200/_bulk][Manticore::SocketException] Connection reset", :exception=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError, :will_retry_in_seconds=>4}
[2022-09-03T19:27:08,151][ERROR][logstash.outputs.elasticsearch][main][da267a1aa24b8b3ff5fc2f0a709e84be0001a7f8c3579bb7abd649b3618a0b1c] Attempted to send a bulk request but there are no living connections in the pool (perhaps Elasticsearch is unreachable or down?) {:message=>"No Available connections", :exception=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::NoConnectionAvailableError, :will_retry_in_seconds=>4}
[2022-09-03T19:27:08,240][INFO ][logstash.outputs.elasticsearch][main][da267a1aa24b8b3ff5fc2f0a709e84be0001a7f8c3579bb7abd649b3618a0b1c] Failed to perform request {:message=>"Connection reset", :exception=>Manticore::SocketException, :cause=>java.net.SocketException: Connection reset}
[2022-09-03T19:27:08,241][WARN ][logstash.outputs.elasticsearch][main][da267a1aa24b8b3ff5fc2f0a709e84be0001a7f8c3579bb7abd649b3618a0b1c] Marking url as dead. Last error: [LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError] Elasticsearch Unreachable: [http://localhost:9200/_bulk][Manticore::SocketException] Connection reset {:url=>http://localhost:9200/, :error_message=>"Elasticsearch Unreachable: [http://localhost:9200/_bulk][Manticore::SocketException] Connection reset", :error_class=>"LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError"}
[2022-09-03T19:27:08,241][ERROR][logstash.outputs.elasticsearch][main][da267a1aa24b8b3ff5fc2f0a709e84be0001a7f8c3579bb7abd649b3618a0b1c] Attempted to send a bulk request but Elasticsearch appears to be unreachable or down {:message=>"Elasticsearch Unreachable: [http://localhost:9200/_bulk][Manticore::SocketException] Connection reset", :exception=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError, :will_retry_in_seconds=>4}
[2022-09-03T19:27:08,324][INFO ][logstash.outputs.elasticsearch][main][da267a1aa24b8b3ff5fc2f0a709e84be0001a7f8c3579bb7abd649b3618a0b1c] Failed to perform request {:message=>"Connection reset", :exception=>Manticore::SocketException, :cause=>java.net.SocketException: Connection reset}
[2022-09-03T19:27:08,325][WARN ][logstash.outputs.elasticsearch][main][da267a1aa24b8b3ff5fc2f0a709e84be0001a7f8c3579bb7abd649b3618a0b1c] Marking url as dead. Last error: [LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError] Elasticsearch Unreachable: [http://localhost:9200/_bulk][Manticore::SocketException] Connection reset {:url=>http://localhost:9200/, :error_message=>"Elasticsearch Unreachable: [http://localhost:9200/_bulk][Manticore::SocketException] Connection reset", :error_class=>"LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError"}
[2022-09-03T19:27:08,325][ERROR][logstash.outputs.elasticsearch][main][da267a1aa24b8b3ff5fc2f0a709e84be0001a7f8c3579bb7abd649b3618a0b1c] Attempted to send a bulk request but Elasticsearch appears to be unreachable or down {:message=>"Elasticsearch Unreachable: [http://localhost:9200/_bulk][Manticore::SocketException] Connection reset", :exception=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError, :will_retry_in_seconds=>4}
[2022-09-03T19:27:08,404][INFO ][logstash.outputs.elasticsearch][main][da267a1aa24b8b3ff5fc2f0a709e84be0001a7f8c3579bb7abd649b3618a0b1c] Failed to perform request {:message=>"Connection reset", :exception=>Manticore::SocketException, :cause=>java.net.SocketException: Connection reset}
[2022-09-03T19:27:08,405][WARN ][logstash.outputs.elasticsearch][main][da267a1aa24b8b3ff5fc2f0a709e84be0001a7f8c3579bb7abd649b3618a0b1c] Marking url as dead. Last error: [LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError] Elasticsearch Unreachable: [http://localhost:9200/_bulk][Manticore::SocketException] Connection reset {:url=>http://localhost:9200/, :error_message=>"Elasticsearch Unreachable: [http://localhost:9200/_bulk][Manticore::SocketException] Connection reset", :error_class=>"LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError"}
[2022-09-03T19:27:08,405][ERROR][logstash.outputs.elasticsearch][main][da267a1aa24b8b3ff5fc2f0a709e84be0001a7f8c3579bb7abd649b3618a0b1c] Attempted to send a bulk request but Elasticsearch appears to be unreachable or down {:message=>"Elasticsearch Unreachable: [http://localhost:9200/_bulk][Manticore::SocketException] Connection reset", :exception=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError, :will_retry_in_seconds=>4}
[2022-09-03T19:27:08,406][INFO ][logstash.outputs.elasticsearch][main][da267a1aa24b8b3ff5fc2f0a709e84be0001a7f8c3579bb7abd649b3618a0b1c] Failed to perform request {:message=>"Connection reset", :exception=>Manticore::SocketException, :cause=>java.net.SocketException: Connection reset}
[2022-09-03T19:27:08,406][WARN ][logstash.outputs.elasticsearch][main][da267a1aa24b8b3ff5fc2f0a709e84be0001a7f8c3579bb7abd649b3618a0b1c] Marking url as dead. Last error: [LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError] Elasticsearch Unreachable: [http://localhost:9200/_bulk][Manticore::SocketException] Connection reset {:url=>http://localhost:9200/, :error_message=>"Elasticsearch Unreachable: [http://localhost:9200/_bulk][Manticore::SocketException] Connection reset", :error_class=>"LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError"}
[2022-09-03T19:27:08,407][ERROR][logstash.outputs.elasticsearch][main][da267a1aa24b8b3ff5fc2f0a709e84be0001a7f8c3579bb7abd649b3618a0b1c] Attempted to send a bulk request but Elasticsearch appears to be unreachable or down {:message=>"Elasticsearch Unreachable: [http://localhost:9200/_bulk][Manticore::SocketException] Connection reset", :exception=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError, :will_retry_in_seconds=>4}
[2022-09-03T19:27:08,416][ERROR][logstash.outputs.elasticsearch][main][da267a1aa24b8b3ff5fc2f0a709e84be0001a7f8c3579bb7abd649b3618a0b1c] Attempted to send a bulk request but there are no living connections in the pool (perhaps Elasticsearch is unreachable or down?) {:message=>"No Available connections", :exception=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::NoConnectionAvailableError, :will_retry_in_seconds=>4}
[2022-09-03T19:27:08,484][INFO ][logstash.outputs.elasticsearch][main][da267a1aa24b8b3ff5fc2f0a709e84be0001a7f8c3579bb7abd649b3618a0b1c] Failed to perform request {:message=>"Connection reset", :exception=>Manticore::SocketException, :cause=>java.net.SocketException: Connection reset}
[2022-09-03T19:27:08,485][WARN ][logstash.outputs.elasticsearch][main][da267a1aa24b8b3ff5fc2f0a709e84be0001a7f8c3579bb7abd649b3618a0b1c] Marking url as dead. Last error: [LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError] Elasticsearch Unreachable: [http://localhost:9200/_bulk][Manticore::SocketException] Connection reset {:url=>http://localhost:9200/, :error_message=>"Elasticsearch Unreachable: [http://localhost:9200/_bulk][Manticore::SocketException] Connection reset", :error_class=>"LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError"}
[2022-09-03T19:27:08,485][ERROR][logstash.outputs.elasticsearch][main][da267a1aa24b8b3ff5fc2f0a709e84be0001a7f8c3579bb7abd649b3618a0b1c] Attempted to send a bulk request but Elasticsearch appears to be unreachable or down {:message=>"Elasticsearch Unreachable: [http://localhost:9200/_bulk][Manticore::SocketException] Connection reset", :exception=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError, :will_retry_in_seconds=>4}
[2022-09-03T19:27:08,571][INFO ][logstash.outputs.elasticsearch][main][da267a1aa24b8b3ff5fc2f0a709e84be0001a7f8c3579bb7abd649b3618a0b1c] Failed to perform request {:message=>"Connection reset", :exception=>Manticore::SocketException, :cause=>java.net.SocketException: Connection reset}
[2022-09-03T19:27:08,571][WARN ][logstash.outputs.elasticsearch][main][da267a1aa24b8b3ff5fc2f0a709e84be0001a7f8c3579bb7abd649b3618a0b1c] Marking url as dead. Last error: [LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError] Elasticsearch Unreachable: [http://localhost:9200/_bulk][Manticore::SocketException] Connection reset {:url=>http://localhost:9200/, :error_message=>"Elasticsearch Unreachable: [http://localhost:9200/_bulk][Manticore::SocketException] Connection reset", :error_class=>"LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError"}

**Comment by yaauie** [comment] 2022-09-03 15:59
The GitHub issues are for confirmed issues with clear reproduction steps, not for general debugging. I'll close this issue and advise you to follow up in [the forums](https://discuss.elastic.co/c/elastic-stack/logstash/14).

But I'll also add some notes to help you get started:

Your logs indicate that Logstash's Elasticsearch Output plugin does not have any stable connections to Elasticsearch. At times it can it get a connection from the pool (because no connections have been successfully established since the last time it checked), and at other times it does establish a connection, but the connection is reset before the entire bulk request can be sent (which causes the dead connection and all other connections to be evicted from the pool). It is possible that a local Elasticsearch is under-provisioned and unable to keep up?

**Closed by yaauie** 2022-09-03 15:59 UTC
Labels: bug, status:needs-triage

**Comment by betheman** [comment] 2022-09-03 16:09
@yaauie 

Pls help in this i have tried different versions on my mac but getting same issue but same thing is working in linux machine.

**Comment by betheman** [comment] 2022-09-03 16:39
> The GitHub issues are for confirmed issues with clear reproduction steps, not for general debugging. I'll close this issue and advise you to follow up in [the forums](https://discuss.elastic.co/c/elastic-stack/logstash/14).
> 
> But I'll also add some notes to help you get started:
> 
> Your logs indicate that Logstash's Elasticsearch Output plugin does not have any stable connections to Elasticsearch. At times it can it get a connection from the pool (because no connections have been successfully established since the last time it checked), and at other times it does establish a connection, but the connection is reset before the entire bulk request can be sent (which causes the dead connection and all other connections to be evicted from the pool). It is possible that a local Elasticsearch is under-provisioned and unable to keep up?



> The GitHub issues are for confirmed issues with clear reproduction steps, not for general debugging. I'll close this issue and advise you to follow up in [the forums](https://discuss.elastic.co/c/elastic-stack/logstash/14).
> 
> But I'll also add some notes to help you get started:
> 
> Your logs indicate that Logstash's Elasticsearch Output plugin does not have any stable connections to Elasticsearch. At times it can it get a connection from the pool (because no connections have been successfully established since the last time it checked), and at other times it does establish a connection, but the connection is reset before the entire bulk request can be sent (which causes the dead connection and all other connections to be evicted from the pool). It is possible that a local Elasticsearch is under-provisioned and unable to keep up?

@yaauie

Pls help in this i have tried different versions on my mac but getting same issue but same thing is working in linux machine.

**Comment by yaauie** [comment] 2022-09-03 17:17
Again, the GitHub issue tracker is for reproducible issues with clear reproduction steps, and not for general debugging. I have directed you to our forums, and provided guidance.

Your Elasticsearch is hanging up on us (TCP connection reset), likely because it is not correctly tuned or is otherwise under-provisioned. From a Logstash perspective, there is not much that can be done. The output plugin appropriately handles getting hung up on by backing off and trying again. You will need to chase the upstream issue and figure out why elasticsearch is hanging up on us, and resolve that.
