### ISSUE TITLE
Exception in filterworker, probably urlencode plugin.

### ISSUE THREAD

**Issue by lephix** [elastic/logstash#3780] opened 2015-08-24 01:26 UTC
Version of Logstash is 1.5.3
Version of JDK is 1.8.0_45

Following is my configuration.

```
input {
    file {
        path => "/data/logs/nginx/access.log"
        start_position => "beginning"
    }
#    stdin{}
}
filter {
    grok {
        match => { "message" => "%{HOSTNAME:requestHost} - %{IPV4:requestIp} - %{NOTSPACE:requestRemoteUser} \[%{HTTPDATE:requestHttpDate}\] %{QS:requestUrl} %{NUMBER:requestHttpStatus:int} %{NUMBER:requestBodySentBytes:int} %{QS:requestHttpReferer} %{QS:requestHttpUserAgent} %{QS:requestHttpXForwaredFor} \"%{NUMBER:requestTime:float}\""}
    }
    date {
        match => ["requestHttpDate", "dd/MMM/yyyy:HH:mm:ss Z"]
    }
    kv {
        source => "requestUrl"
        field_split => "&? "
        trimkey => "_"
        trim => " "
    }
    mutate {
        convert => {
            "launch" => "integer"
            "screenDpi" => "float"
            "screenWidth" => "integer"
            "screenHeight" => "integer"
            "longitude" => "float"
            "latitude" => "float"
        }
    }
    urldecode {
        all_fields => true
    }
}
output {
    elasticsearch {
        protocol => "transport"
        cluster => "mc-es-ai"
        index => "logstash-busybox-%{+MM.dd}"
        host => ["10.162.65.105"]
    }
#    stdout {
#        codec => "json"
#    }
}
```

Following is the error message

```
{:timestamp=>"2015-08-24T07:09:51.349000+0800", :message=>"Exception in filterworker", "exception"=>#<RuntimeError: can't add a new key into hash during iteration>, "backtrace"=>["org/jruby/RubyHash.java:991:in `[]='", "/home/mucang/app/logstash-1.5.3/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.3-java/lib/logstash/util/accessors.rb:65:in `set'", "/home/mucang/app/logstash-1.5.3/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.3-java/lib/logstash/event.rb:146:in `[]='", "/home/mucang/app/logstash-1.5.3/vendor/bundle/jruby/1.9/gems/logstash-filter-urldecode-1.0.0/lib/logstash/filters/urldecode.rb:36:in `filter'", "org/jruby/RubyHash.java:1341:in `each'", "/home/mucang/app/logstash-1.5.3/vendor/bundle/jruby/1.9/gems/logstash-filter-urldecode-1.0.0/lib/logstash/filters/urldecode.rb:36:in `filter'", "/home/mucang/app/logstash-1.5.3/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.3-java/lib/logstash/filters/base.rb:163:in `multi_filter'", "org/jruby/RubyArray.java:1613:in `each'", "/home/mucang/app/logstash-1.5.3/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.3-java/lib/logstash/filters/base.rb:160:in `multi_filter'", "(eval):157:in `filter_func'", "/home/mucang/app/logstash-1.5.3/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.3-java/lib/logstash/pipeline.rb:219:in `filterworker'", "/home/mucang/app/logstash-1.5.3/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.3-java/lib/logstash/pipeline.rb:157:in `start_filters'"], :level=>:error}
```

Following is a example of our Nginx log. Some of the sensitive infos are replaced.

```
busybox.xxx.com - 39.71.227.1 - - [24/Aug/2015:09:00:12 +0800] "GET /api/xxx/xxx/list.htm?productId=1&protocol=2.2&_platform=android&_srv=t&_appName=xxx&_product=%E9%A9%BE%E8%80%83%E5%AE%9D%E5%85%B8&_vendor=xxx&_renyuan=xxx&_version=6.2.2&_system=KOT49H&_manufacturer=YuLong&_systemVersion=4.4.2&_device=Coolpad%208675-HD&_imei=xxx&_productCategory=xxx&_operator=M&_androidId=xxx&_mac=3c%3A91%3A57%3Aa2%3A9c%3Ab5&_appUser=xxx&_pkgName=com.xxx.xxx&_screenDpi=2.0&_screenWidth=720&_screenHeight=1280&_network=wifi&_launch=19&_webviewVersion=4.3&_firstTime=2015-06-11%2020%3A59%3A22&_userCity=123456&_p=5C46565957561C4550555C&_gpsType=baidu&_cityName=%E6%B5%8E%E5%8D%97%E5%B8%82&_cityCode=123456&_gpsCity=123456&_longitude=180.9733&_latitude=336.719&_ipCity=123456&_j=1.0&schoolName=%E6%B3%89%E6%97%BA%E9%A9%BE%E6%A0%A1&schoolCode=123456&sign=xxx HTTP/1.1" 200 3057 "-" "Mozilla/5.0 (Linux; Android 4.4.2; Coolpad 8675-HD Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/30.0.0.0 Mobile Safari/537.36" "-" "0.059"
```

**Comment by colinsurprenant** [comment] 2015-08-25 16:10
Thanks for the report @lephix. Can you actually reproduce the error with the sample log you copied? 

I ran the following and  did not reproduce the error:

`tmp/urldecode.conf`
```
input { stdin {codec => line {}}}

filter {
    grok {
        match => { "message" => "%{HOSTNAME:requestHost} - %{IPV4:requestIp} - %{NOTSPACE:requestRemoteUser} \[%{HTTPDATE:requestHttpDate}\] %{QS:requestUrl} %{NUMBER:requestHttpStatus:int} %{NUMBER:requestBodySentBytes:int} %{QS:requestHttpReferer} %{QS:requestHttpUserAgent} %{QS:requestHttpXForwaredFor} \"%{NUMBER:requestTime:float}\""}
    }
    date {
        match => ["requestHttpDate", "dd/MMM/yyyy:HH:mm:ss Z"]
    }
    kv {
        source => "requestUrl"
        field_split => "&? "
        trimkey => "_"
        trim => " "
    }
    mutate {
        convert => {
            "launch" => "integer"
            "screenDpi" => "float"
            "screenWidth" => "integer"
            "screenHeight" => "integer"
            "longitude" => "float"
            "latitude" => "float"
        }
    }
    urldecode {
        all_fields => true
    }
}

output { stdout {codec => rubydebug {}}}
```

`tmp/log.txt`
```
busybox.xxx.com - 39.71.227.1 - - [24/Aug/2015:09:00:12 +0800] "GET /api/xxx/xxx/list.htm?productId=1&protocol=2.2&_platform=android&_srv=t&_appName=xxx&_product=%E9%A9%BE%E8%80%83%E5%AE%9D%E5%85%B8&_vendor=xxx&_renyuan=xxx&_version=6.2.2&_system=KOT49H&_manufacturer=YuLong&_systemVersion=4.4.2&_device=Coolpad%208675-HD&_imei=xxx&_productCategory=xxx&_operator=M&_androidId=xxx&_mac=3c%3A91%3A57%3Aa2%3A9c%3Ab5&_appUser=xxx&_pkgName=com.xxx.xxx&_screenDpi=2.0&_screenWidth=720&_screenHeight=1280&_network=wifi&_launch=19&_webviewVersion=4.3&_firstTime=2015-06-11%2020%3A59%3A22&_userCity=123456&_p=5C46565957561C4550555C&_gpsType=baidu&_cityName=%E6%B5%8E%E5%8D%97%E5%B8%82&_cityCode=123456&_gpsCity=123456&_longitude=180.9733&_latitude=336.719&_ipCity=123456&_j=1.0&schoolName=%E6%B3%89%E6%97%BA%E9%A9%BE%E6%A0%A1&schoolCode=123456&sign=xxx HTTP/1.1" 200 3057 "-" "Mozilla/5.0 (Linux; Android 4.4.2; Coolpad 8675-HD Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/30.0.0.0 Mobile Safari/537.36" "-" "0.059"
```

```sh
$ cat tmp/log.txt | bin/logstash -f tmp/urldecode.conf
Logstash startup completed
{
                    "message" => "busybox.xxx.com - 39.71.227.1 - - [24/Aug/2015:09:00:12 +0800] \"GET /api/xxx/xxx/list.htm?productId=1&protocol=2.2&_platform=android&_srv=t&_appName=xxx&_product=驾考宝典&_vendor=xxx&_renyuan=xxx&_version=6.2.2&_system=KOT49H&_manufacturer=YuLong&_systemVersion=4.4.2&_device=Coolpad 8675-HD&_imei=xxx&_productCategory=xxx&_operator=M&_androidId=xxx&_mac=3c:91:57:a2:9c:b5&_appUser=xxx&_pkgName=com.xxx.xxx&_screenDpi=2.0&_screenWidth=720&_screenHeight=1280&_network=wifi&_launch=19&_webviewVersion=4.3&_firstTime=2015-06-11 20:59:22&_userCity=123456&_p=5C46565957561C4550555C&_gpsType=baidu&_cityName=济南市&_cityCode=123456&_gpsCity=123456&_longitude=180.9733&_latitude=336.719&_ipCity=123456&_j=1.0&schoolName=泉旺驾校&schoolCode=123456&sign=xxx HTTP/1.1\" 200 3057 \"-\" \"Mozilla/5.0 (Linux; Android 4.4.2; Coolpad 8675-HD Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/30.0.0.0 Mobile Safari/537.36\" \"-\" \"0.059\"",
                   "@version" => "1",
                 "@timestamp" => "2015-08-24T01:00:12.000Z",
                       "host" => "colin-mbp13r.local",
                "requestHost" => "busybox.xxx.com",
                  "requestIp" => "39.71.227.1",
          "requestRemoteUser" => "-",
            "requestHttpDate" => "24/Aug/2015:09:00:12 +0800",
                 "requestUrl" => "\"GET /api/xxx/xxx/list.htm?productId=1&protocol=2.2&_platform=android&_srv=t&_appName=xxx&_product=驾考宝典&_vendor=xxx&_renyuan=xxx&_version=6.2.2&_system=KOT49H&_manufacturer=YuLong&_systemVersion=4.4.2&_device=Coolpad 8675-HD&_imei=xxx&_productCategory=xxx&_operator=M&_androidId=xxx&_mac=3c:91:57:a2:9c:b5&_appUser=xxx&_pkgName=com.xxx.xxx&_screenDpi=2.0&_screenWidth=720&_screenHeight=1280&_network=wifi&_launch=19&_webviewVersion=4.3&_firstTime=2015-06-11 20:59:22&_userCity=123456&_p=5C46565957561C4550555C&_gpsType=baidu&_cityName=济南市&_cityCode=123456&_gpsCity=123456&_longitude=180.9733&_latitude=336.719&_ipCity=123456&_j=1.0&schoolName=泉旺驾校&schoolCode=123456&sign=xxx HTTP/1.1\"",
          "requestHttpStatus" => 200,
       "requestBodySentBytes" => 3057,
         "requestHttpReferer" => "\"-\"",
       "requestHttpUserAgent" => "\"Mozilla/5.0 (Linux; Android 4.4.2; Coolpad 8675-HD Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/30.0.0.0 Mobile Safari/537.36\"",
    "requestHttpXForwaredFor" => "\"-\"",
                "requestTime" => 0.059,
                  "productId" => "1",
                   "protocol" => "2.2",
                   "platform" => "android",
                        "srv" => "t",
                    "appName" => "xxx",
                    "product" => "驾考宝典",
                     "vendor" => "xxx",
                    "renyuan" => "xxx",
                    "version" => "6.2.2",
                     "system" => "KOT49H",
               "manufacturer" => "YuLong",
              "systemVersion" => "4.4.2",
                     "device" => "Coolpad 8675-HD",
                       "imei" => "xxx",
            "productCategory" => "xxx",
                   "operator" => "M",
                  "androidId" => "xxx",
                        "mac" => "3c:91:57:a2:9c:b5",
                    "appUser" => "xxx",
                    "pkgName" => "com.xxx.xxx",
                  "screenDpi" => 2.0,
                "screenWidth" => 720,
               "screenHeight" => 1280,
                    "network" => "wifi",
                     "launch" => 19,
             "webviewVersion" => "4.3",
                  "firstTime" => "2015-06-11 20:59:22",
                   "userCity" => "123456",
                          "p" => "5C46565957561C4550555C",
                    "gpsType" => "baidu",
                   "cityName" => "济南市",
                   "cityCode" => "123456",
                    "gpsCity" => "123456",
                  "longitude" => 180.9733,
                   "latitude" => 336.719,
                     "ipCity" => "123456",
                          "j" => "1.0",
                 "schoolName" => "泉旺驾校",
                 "schoolCode" => "123456",
                       "sign" => "xxx"
}
Logstash shutdown completed
```

**Comment by lephix** [comment] 2015-08-26 03:15
Yesterday, I encounter the problem again. Logstash has run about 1 day long before this error occurred.
Logstash get a error as same as I reported before.

    {:timestamp=>"2015-08-26T06:50:38.006000+0800", :message=>"Exception in filterworker", "exception"=>#<RuntimeError: can't add a new key into hash during iteration>, "backtrace"=>["org/jruby/RubyHash.java:991:in `[]='", "/home/mucang/app/logstash-current/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.4-java/lib/logstash/util/accessors.rb:119:in `find_or_create_target'", "org/jruby/RubyArray.java:1613:in `each'", "org/jruby/RubyEnumerable.java:866:in `inject'", "/home/mucang/app/logstash-current/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.4-java/lib/logstash/util/accessors.rb:119:in `find_or_create_target'", "/home/mucang/app/logstash-current/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.4-java/lib/logstash/util/accessors.rb:98:in `lookup_or_create'", "/home/mucang/app/logstash-current/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.4-java/lib/logstash/util/accessors.rb:63:in `set'", "/home/mucang/app/logstash-current/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.4-java/lib/logstash/event.rb:146:in `[]='", "/home/mucang/app/logstash-current/vendor/bundle/jruby/1.9/gems/logstash-filter-urldecode-1.0.0/lib/logstash/filters/urldecode.rb:36:in `filter'", "org/jruby/RubyHash.java:1341:in `each'", "/home/mucang/app/logstash-current/vendor/bundle/jruby/1.9/gems/logstash-filter-urldecode-1.0.0/lib/logstash/filters/urldecode.rb:36:in `filter'", "/home/mucang/app/logstash-current/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.4-java/lib/logstash/filters/base.rb:163:in `multi_filter'", "org/jruby/RubyArray.java:1613:in `each'", "/home/mucang/app/logstash-current/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.4-java/lib/logstash/filters/base.rb:160:in `multi_filter'", "(eval):157:in `filter_func'", "/home/mucang/app/logstash-current/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.4-java/lib/logstash/pipeline.rb:219:in `filterworker'", "/home/mucang/app/logstash-current/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.4-java/lib/logstash/pipeline.rb:157:in `start_filters'"], :level=>:error}

According to the timestamp, I think I found the log that broke the Logstash. I list 3 lines, the 2nd line is the target line. I cannot reproduce the error upper, but the logstash get stunned when processing 2nd line.

    busybox.kakamobi.com - 27.198.210.128 - - [26/Aug/2015:06:50:37 +0800] "GET /api/open/box/list.htm?productId=1&protocol=2.2&_platform=android&_srv=t&_appName=jiakaobaodian&_product=%E9%A9%BE%E8%80%83%E5%AE%9D%E5%85%B8&_vendor=xiaomi&_renyuan=YTX&_version=6.2.4&_system=KTU84P&_manufacturer=Xiaomi&_systemVersion=4.4.4&_device=MI%203&_imei=860311025744939&_productCategory=jiakaobaodian&_operator=C&_androidId=4ab6106a081d5ae3&_mac=f8%3Aa4%3A5f%3A70%3A96%3Ae6&_appUser=f1ca41f0c99d4e62bba7e9b8716ae02f&_pkgName=com.handsgo.jiakao.android&_screenDpi=3.0&_screenWidth=1080&_screenHeight=1920&_network=wifi&_launch=28&_webviewVersion=4.3&_firstTime=2015-08-03%2013%3A28%3A23&_userCity=370800&_p=464D55505D571A4055545E5E4751&_gpsType=baidu&_cityName=%E6%B5%8E%E5%AE%81%E5%B8%82&_cityCode=370800&_gpsCity=370800&_longitude=116.40658&_latitude=35.592415&_ipCity=370800&interface_version=2.0&bitauto_version=1.10&_j=1.0&schoolName=%E8%A5%BF%E5%9F%8E%E9%A9%BE%E6%A0%A1&schoolCode=370800129&sign=8c53465a633d5143c50472e0d0781baf HTTP/1.1" 200 2958 "-" "Mozilla/5.0 (Linux; Android 4.4.4; MI 3 Build/KTU84P) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/33.0.0.0 Mobile Safari/537.36" "-" "0.006"
    121.41.90.138 - 121.42.0.14 - - [26/Aug/2015:06:50:37 +0800] "GET /plus/search.php?keyword=as&typeArr[111%3D@%60%5C%27%60)+and+(SELECT+1+FROM+(select+count(*),concat(floor(rand(0)*2),(substring((select+CONCAT(0x7c,userid,0x7c,md5(233333))+from+%60%23@__admin%60+limit+0,1),1,62)))a+from+information_schema.tables+group+by+a)b)%23@%60%5C%27%60+]=a HTTP/1.1" 404 0 "http://121.41.90.138:80/cgi-bin/micromsg-bin/newgetdns" "Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1;Alibaba.Security.Heimdall.463295)" "-" "0.001"
    busybox.kakamobi.com - 222.74.228.13 - - [26/Aug/2015:06:50:37 +0800] "GET /api/open/box/list.htm?productId=1&protocol=2.2&_platform=android&_srv=t&_appName=jiakaobaodian&_product=%E9%A9%BE%E8%80%83%E5%AE%9D%E5%85%B8&_vendor=myapp&_renyuan=YTX&_version=6.2.4&_system=JZO54K&_manufacturer=samsung&_systemVersion=4.1.2&_device=SCH-N719&_imei=A0000044AB52E8&_productCategory=jiakaobaodian&_operator=T&_androidId=2c7c7b7cd8d997e3&_mac=34%3A23%3ABA%3A12%3A7A%3A03&_appUser=77ee783f8c4f4ea489309134e3a63a34&_pkgName=com.handsgo.jiakao.android&_screenDpi=2.0&_screenWidth=720&_screenHeight=1280&_network=g3&_launch=26&_webviewVersion=4.3&_firstTime=2015-07-28%2014%3A22%3A20&_userCity=150800&_p=5D4553515E571E445553585D455351&_gpsType=baidu&_cityName=%E5%B7%B4%E5%BD%A6%E6%B7%96%E5%B0%94%E5%B8%82&_cityCode=150800&_gpsCity=150800&_longitude=107.390154&_latitude=40.76958&_ipCity=321300&interface_version=2.0&bitauto_version=1.10&_j=1.0&schoolName=%E7%A7%91%E5%85%B4%E9%A9%BE%E6%A0%A1&schoolCode=150800023&sign=35bb7c50b8542b8004843f4fa1fc5b3d HTTP/1.1" 200 12492 "-" "Mozilla/5.0 (Linux; U; Android 4.1.2; zh-cn; SCH-N719 Build/JZO54K) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30" "10.11.227.108" "0.072"

**Comment by talevy** [comment] 2017-02-17 17:21
Closing this issue since it has been open for a long time and we haven't received the details to debug it further. Please reopen a new issue if you still run into issues

**Closed by talevy** 2017-02-17 17:21 UTC
Labels: needs details, unconfirmed
