### ISSUE TITLE
execution expired - MultiJson::ParseError

### ISSUE THREAD

**Issue by gowthamsadasivam** [elastic/logstash#4823] opened 2016-03-16 09:36 UTC
I'm trying to parse two **syslog files** (_/var/log/secure, /var/log/messages_) and three **hadoop log files** (_/var/log/hadoop-hdfs/\*.log, /var/log/hadoop-yarn/\*.log_). I'm getting the log files parsed as expected. But frequently I'm getting the following error message in the /var/log/logstash/logstash.log file. Not sure I'm missing any log entry/performance due to this issue.

> {:timestamp=>"2016-03-16T14:46:22.785000+0530", :message=>"execution expired", :class=>"MultiJson::ParseError", :backtrace=>["/opt/logstash/vendor/bundle/jruby/1.9/gems/jrjackson-0.3.8/lib/jrjackson/jrjackson.rb:87:in `is_time_string?'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/jrjackson-0.3.8/lib/jrjackson/jrjackson.rb:85:in `is_time_string?'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/jrjackson-0.3.8/lib/jrjackson/jrjackson.rb:34:in `load'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/multi_json-1.11.2/lib/multi_json/adapters/jr_jackson.rb:11:in `load'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/multi_json-1.11.2/lib/multi_json/adapter.rb:21:in `load'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/multi_json-1.11.2/lib/multi_json.rb:119:in `load'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.15/lib/elasticsearch/transport/transport/serializer/multi_json.rb:24:in `load'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.15/lib/elasticsearch/transport/transport/base.rb:259:in `perform_request'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.15/lib/elasticsearch/transport/transport/http/manticore.rb:54:in `perform_request'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.15/lib/elasticsearch/transport/transport/sniffer.rb:32:in `hosts'", "org/jruby/ext/timeout/Timeout.java:147:in `timeout'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.15/lib/elasticsearch/transport/transport/sniffer.rb:31:in `hosts'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.15/lib/elasticsearch/transport/transport/base.rb:76:in `reload_connections!'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.5.1-java/lib/logstash/outputs/elasticsearch/http_client.rb:72:in `sniff!'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.5.1-java/lib/logstash/outputs/elasticsearch/http_client.rb:60:in `start_sniffing!'", "org/jruby/ext/thread/Mutex.java:149:in `synchronize'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.5.1-java/lib/logstash/outputs/elasticsearch/http_client.rb:60:in `start_sniffing!'", "org/jruby/RubyKernel.java:1479:in `loop'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.5.1-java/lib/logstash/outputs/elasticsearch/http_client.rb:59:in `start_sniffing!'"], :level=>:error}

### **02-beats-input.conf**

> input {
  beats {
    port => 5044
    ssl => true
    ssl_certificate => "/etc/pki/tls/certs/logstash-forwarder.crt"
    ssl_key => "/etc/pki/tls/private/logstash-forwarder.key"
  }
}

### **10-syslog-filter.conf**

> filter {
  if [type] == "syslog" {
    grok {
      match => { "message" => "%{SYSLOGTIMESTAMP:log_timestamp} %{SYSLOGHOST:log_hostname} %{DATA:log_program}(?:\[%{POSINT:log_pid}\])?: %{GREEDYDATA:log_message}" }
      add_field => [ "received_at", "%{@timestamp}" ]
      add_field => [ "received_from", "%{host}" ]
      add_field => [ "log_type", "%{type}" ]
    }
    syslog_pri { }
    date {
      match => [ "log_timestamp", "MMM  d HH:mm:ss", "MMM dd HH:mm:ss" ]
    }
  }
}

### **11-hadooplog-filter.conf**

> filter {
  if [type] == "hadoop" {
    grok {
      match => { "message" => "%{TIMESTAMP_ISO8601:log_timestamp} %{WORD:log_severity} %{GREEDYDATA:log_message}" }
      add_field => [ "received_at", "%{@timestamp}" ]
      add_field => [ "received_from", "%{host}" ]
    }
  }
}

### **30-elasticsearch-output.conf**

> output {
  elasticsearch {
    hosts => ["localhost:9200"]
    sniffing => true
    manage_template => false
    index => "%{[@metadata][beat]}-%{+YYYY.MM.dd}"
    document_type => "%{[@metadata][type]}"
  }
}

Would like to know what was the issue that triggered the error in the **logstash.log** file.

**Comment by suyograo** [comment] 2016-03-17 00:37
What version of LS are you running?

**Comment by gowthamsadasivam** [comment] 2016-03-17 05:55
It's **logstash 2.2.2**

**Comment by gerane** [comment] 2016-03-29 12:21
I am seeing these same errors running the same LS version.

**Comment by andrewvc** [comment] 2016-03-29 14:30
Apologies guys, this will be fixed when this issue is closed. I've removed the use of the Threadsafe library (which is the source of this) in my refactors of the elasticsearch-ruby code. I'm hoping to get this out soon, it's my top priority. https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/377

**Comment by guyboertje** [comment] 2016-03-29 14:45
FYI the root cause is Ruby Timeout raising an exception (its normal behaviour), however this exception happens to be rescued during the multi-json parse of the sniffing response.
This indicates that the sniffing request/response from ES is taking far too long.
Normally, the JSON parsing of the response should occur much much earlier - so that some other rescue clause is active when the Timeout exception is actually raised.

**Comment by suyograo** [comment] 2016-06-30 00:36
Fixed in https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/390

**Closed by suyograo** 2016-06-30 00:36 UTC
Labels: needs details
