### ISSUE TITLE
Test failure: periodic flush count mismatch

### ISSUE THREAD

**Issue by jordansissel** [elastic/logstash#7060] opened 2017-05-09 23:55 UTC
https://logstash-ci.elastic.co/job/elastic+logstash+5.4+dockerubuntu-periodic/327/console

```
  1) LogStash::Pipeline Periodic Flush flushes the buffered contents of the filter
     Failure/Error: expect(event.get("message").count("\n")).to eq(99)
       
       expected: 99
            got: 98
       
```

**Comment by jsvd** [comment] 2017-05-16 10:07
closing as a duplicate of https://github.com/elastic/logstash/issues/7024

**Closed by jsvd** 2017-05-16 10:07 UTC
Labels: test failure
