### ISSUE TITLE
Cannot branch on existence of field

### ISSUE THREAD

**Issue by talevy** [elastic/logstash#3568] opened 2015-07-07 19:08 UTC
It is sometimes important to branch on whether an event contains a specific field.

example:
```
filter {
  if event.include?("[a]") {
    mutate {
      add_tag => ["_has_field_a"]
    }
  }
}
```

Currently, `if not [a] { }` matches when either the field `a` is `nil` or `a` is not found. It is not possible to distinguish between the two.

This issue raised itself when a user in Discuss[1] attempted to do so. no clean solution 
was found.

reference to existing (closed) jira issue: https://logstash.jira.com/browse/LOGSTASH-1422.

[1] https://discuss.elastic.co/t/check-existence-of-a-field-and-checking-null-value-in-field/24968.

**Comment by wiibaa** [comment] 2015-07-08 07:21
related: specific discussion on boolean field existence in #1867

**Comment by talevy** [comment] 2015-07-08 07:33
ah! @wiibaa thanks! this seems to be a duplicate then

**Comment by colinsurprenant** [comment] 2015-07-11 18:30
I like the idea of somehow exposing the event objects to conditionals `if event.include?("[a]")`

**Comment by jordansissel** [comment] 2015-07-11 19:49
Let's be careful about how we proceed with this scoping feature - specifically for future work. Given I hope to replace the logstash config syntax with an API (and probably JSON), we should be careful of explicitly choosing ruby (`event.include?("[a]")`) since the pipeline execution is trending towards Java.

**Comment by colinsurprenant** [comment] 2015-07-12 19:32
@jordansissel totally agree.

**Comment by jsvd** [comment] 2016-03-11 16:50
closing as a duplicate of https://github.com/elastic/logstash/issues/1867

**Closed by jsvd** 2016-03-11 16:50 UTC
Labels: enhancement
