### ISSUE TITLE
 Start time much longer for multiple pipelines

### ISSUE THREAD

**Issue by alah64** [elastic/logstash#12020] opened 2020-06-14 06:55 UTC
logstash loads pipeline configs in a single thread and if exists multiple pipelines , start time is boring.
this issue https://github.com/elastic/logstash/issues/11105 mentioned earlier and exists in 7.7.1 version too.

I have tested logstash versions 7.0.0 , 7.5.0 , 7.6.0 ,7.7.1 for two pipelines (helk and another) and these are the same.

![image](https://user-images.githubusercontent.com/41846701/84586194-a0ee7e80-ae2c-11ea-9565-d35e349d4e25.png)

**Comment by praseodym** [comment] 2020-06-14 16:06
Related to #12002?

**Comment by alah64** [comment] 2020-06-15 10:08
> 
> 
> Related to #12002?

yes, its related , i tested logstash 7.6.2 but regression exists (some differences exists in this version and monitoring record not exists until pipelines loaded completely): 
![image](https://user-images.githubusercontent.com/41846701/84645421-cc00cd00-af15-11ea-94b4-ec57d5d84dac.png)

**Comment by praseodym** [comment] 2020-06-16 14:09
Apparently #12002 was moved somewhere else: "This issue has been moved to a repository you don't have access to."

**Comment by kares** [comment] 2020-06-23 08:05
Hey Mark, yes but as you already noticed there's a new replacement issue at https://github.com/elastic/logstash/issues/12031 (with a potential PR at https://github.com/elastic/logstash/pull/12038).
I think we can close this as a duplicate of https://github.com/elastic/logstash/issues/12031

**Closed** 2022-01-19 06:39 UTC
