### ISSUE TITLE
Logstash 6.0 breaks ruby code if running more than 1 worker

### ISSUE THREAD

**Issue by vbohata** [elastic/logstash#8727] opened 2017-11-25 11:10 UTC
I upgraded Logstash to 6.0. After the upgrade a lot of ruby code stopped to work. Following code worked in Logstash 5, but in Logstash 6 it often causes these errors:
`Ruby exception occurred: org.jruby.RubyNil cannot be cast to org.jruby.RubyMatchData`
These error lines are repeated, no java stack trace is displayed.

```
 # fixes JSON before processing in LS and indexing in ES ...
  # lowercase json keys, replace invalid characters in json keys, in case of object value, add _o suffix to json keys
  ruby {
    code => '
      nlog_str_inarr = event.get("json_message").split("")
      nlog_str_outarr = []
      nlog_str_outarr_buff = []
      nlog_str_outarr_buffenabled = false
      nlog_key_prefixmatch = [ "", "", "" ]
      nlog_inside_key = false
      nlog_str_inarr.each { |c|
        if c !~ /^\s$/
          nlog_key_prefixmatch[0] = nlog_key_prefixmatch[1]
          nlog_key_prefixmatch[1] = nlog_key_prefixmatch[2]
          nlog_key_prefixmatch[2] = c
       end
        # detect key values
        if ! nlog_inside_key
          if nlog_key_prefixmatch[2] == "\"" && (nlog_key_prefixmatch[1] == "{" || nlog_key_prefixmatch[1] == "," || nlog_key_prefixmatch[1] == "")
            nlog_inside_key = true
          end
        else
          if nlog_key_prefixmatch[2] == "\"" && nlog_key_prefixmatch[1] != "\\"
            nlog_inside_key = false
            nlog_str_outarr_buffenabled = true
         else
            c.downcase!
            if c !~ /^[a-zA-Z0-9_-]$/
              c = "_"
            end
          end
        end
        if ! nlog_str_outarr_buffenabled
          nlog_str_outarr.push(c)
        else
          # buffering until reach the value, after that determine if the value is object and in this case add to the key "_o" suffix
          nlog_str_outarr_buff.push(c)
          if nlog_key_prefixmatch[1] == ":"
            if nlog_key_prefixmatch[2] == "{"
              nlog_str_outarr.push("_o")
            end
            nlog_str_outarr_buff.each { |bc|
              nlog_str_outarr.push(bc)
            }
            nlog_str_outarr_buff = []
            nlog_str_outarr_buffenabled = false
          end
        end
      }
      event.set("json_message_parsed", nlog_str_outarr.join())
    '
  }
```

- Version: 6.0.0
- Operating System: RHEL 7 running LS docker container built on CentOS 7

Once I set workers to 1 it work.

The issue is also discussed here: https://discuss.elastic.co/t/logstash-6-0-breaks-ruby-code-if-running-more-than-1-worker/109083

**Comment by vbohata** [comment] 2017-11-27 06:26
After the modification of ruby.rb as proposed in https://discuss.elastic.co/t/logstash-6-0-breaks-ruby-code-if-running-more-than-1-worker/109083/4 here is the full trace of the error:
`[2017-11-27T07:17:05,767][ERROR][logstash.filters.ruby    ] Ruby exception occurred {"exception"=>"org.jruby.RubyNil cannot be cast to org.jruby.RubyMatchData", "backtrace"=>["org.jruby.RubyString.regexSplit19(RubyString.java:3592)", "org.jruby.RubyString.splitCommon19(RubyString.java:3549)", "org.jruby.RubyString.split19(RubyString.java:3516)", "org.jruby.RubyString$INVOKER$i$split19.call(RubyString$INVOKER$i$split19.gen)", "org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:338)", "org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:163)", "org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:314)", "org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)", "org.jruby.ir.interpreter.Interpreter.INTERPRET_BLOCK(Interpreter.java:132)", "org.jruby.runtime.MixedModeIRBlockBody.commonYieldPath(MixedModeIRBlockBody.java:148)", "org.jruby.runtime.IRBlockBody.call(IRBlockBody.java:73)", "org.jruby.runtime.Block.call(Block.java:124)", "org.jruby.RubyProc.call(RubyProc.java:289)", "org.jruby.RubyProc.call19(RubyProc.java:273)", "org.jruby.RubyProc$INVOKER$i$0$0$call19.call(RubyProc$INVOKER$i$0$0$call19.gen)", "org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:204)", "org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:171)", "org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:177)", "org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:332)", "org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)", "org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:83)", "org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:179)", "org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:165)", "org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:348)", "org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:173)", "org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:177)", "opt.logstash.logstash_minus_core.lib.logstash.filters.base.invokeOther4:filter(/opt/logstash/logstash-core/lib/logstash/filters/base.rb:145)", "opt.logstash.logstash_minus_core.lib.logstash.filters.base.RUBY$method$do_filter$0(/opt/logstash/logstash-core/lib/logstash/filters/base.rb:145)", "org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:103)", "org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:163)", "org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:348)", "org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:173)", "org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:177)", "opt.logstash.logstash_minus_core.lib.logstash.filters.base.invokeOther4:do_filter(/opt/logstash/logstash-core/lib/logstash/filters/base.rb:164)", "opt.logstash.logstash_minus_core.lib.logstash.filters.base.RUBY$block$multi_filter$1(/opt/logstash/logstash-core/lib/logstash/filters/base.rb:164)", "org.jruby.runtime.CompiledIRBlockBody.yieldDirect(CompiledIRBlockBody.java:156)", "org.jruby.runtime.BlockBody.yield(BlockBody.java:114)", "org.jruby.runtime.Block.yield(Block.java:165)", "org.jruby.RubyArray.each(RubyArray.java:1734)", "org.jruby.RubyArray$INVOKER$i$0$0$each.call(RubyArray$INVOKER$i$0$0$each.gen)", "org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:139)", "org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:145)", "opt.logstash.logstash_minus_core.lib.logstash.filters.base.invokeOther7:each(/opt/logstash/logstash-core/lib/logstash/filters/base.rb:161)", "opt.logstash.logstash_minus_core.lib.logstash.filters.base.RUBY$method$multi_filter$0(/opt/logstash/logstash-core/lib/logstash/filters/base.rb:161)", "org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:103)", "org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:163)", "org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:200)", "org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:338)", "org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:163)", "opt.logstash.logstash_minus_core.lib.logstash.filter_delegator.invokeOther10:multi_filter(/opt/logstash/logstash-core/lib/logstash/filter_delegator.rb:48)", "opt.logstash.logstash_minus_core.lib.logstash.filter_delegator.RUBY$method$multi_filter$0(/opt/logstash/logstash-core/lib/logstash/filter_delegator.rb:48)", "org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:103)", "org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:163)", "org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:200)", "org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:338)", "org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:163)", "org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:314)", "org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)", "org.jruby.ir.interpreter.Interpreter.INTERPRET_BLOCK(Interpreter.java:132)", "org.jruby.runtime.MixedModeIRBlockBody.commonYieldPath(MixedModeIRBlockBody.java:148)", "org.jruby.runtime.IRBlockBody.doYield(IRBlockBody.java:186)", "org.jruby.runtime.BlockBody.yield(BlockBody.java:116)", "org.jruby.runtime.Block.yield(Block.java:165)", "org.jruby.RubyArray.each(RubyArray.java:1734)", "org.jruby.RubyArray$INVOKER$i$0$0$each.call(RubyArray$INVOKER$i$0$0$each.gen)", "org.jruby.internal.runtime.methods.JavaMethod$JavaMethodZeroBlock.call(JavaMethod.java:498)", "org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:77)", "org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:83)", "org.jruby.ir.instructions.CallBase.interpret(CallBase.java:428)", "org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:355)", "org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)", "org.jruby.ir.interpreter.Interpreter.INTERPRET_BLOCK(Interpreter.java:132)", "org.jruby.runtime.MixedModeIRBlockBody.commonYieldPath(MixedModeIRBlockBody.java:148)", "org.jruby.runtime.IRBlockBody.call(IRBlockBody.java:73)", "org.jruby.runtime.Block.call(Block.java:124)", "org.jruby.RubyProc.call(RubyProc.java:289)", "org.jruby.RubyProc.call19(RubyProc.java:273)", "org.jruby.RubyProc$INVOKER$i$0$0$call19.call(RubyProc$INVOKER$i$0$0$call19.gen)", "org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:204)", "org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:200)", "org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:161)", "org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:314)", "org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)", "org.jruby.ir.interpreter.Interpreter.INTERPRET_BLOCK(Interpreter.java:132)", "org.jruby.runtime.MixedModeIRBlockBody.commonYieldPath(MixedModeIRBlockBody.java:148)", "org.jruby.runtime.IRBlockBody.doYield(IRBlockBody.java:186)", "org.jruby.runtime.BlockBody.yield(BlockBody.java:116)", "org.jruby.runtime.Block.yield(Block.java:165)", "org.jruby.RubyArray.each(RubyArray.java:1734)", "org.jruby.RubyArray$INVOKER$i$0$0$each.call(RubyArray$INVOKER$i$0$0$each.gen)", "org.jruby.internal.runtime.methods.JavaMethod$JavaMethodZeroBlock.call(JavaMethod.java:498)", "org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:77)", "org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:83)", "org.jruby.ir.instructions.CallBase.interpret(CallBase.java:428)", "org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:355)", "org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)", "org.jruby.ir.interpreter.Interpreter.INTERPRET_BLOCK(Interpreter.java:132)", "org.jruby.runtime.MixedModeIRBlockBody.commonYieldPath(MixedModeIRBlockBody.java:148)", "org.jruby.runtime.IRBlockBody.call(IRBlockBody.java:73)", "org.jruby.runtime.Block.call(Block.java:124)", "org.jruby.RubyProc.call(RubyProc.java:289)", "org.jruby.RubyProc.call19(RubyProc.java:273)", "org.jruby.RubyProc$INVOKER$i$0$0$call19.call(RubyProc$INVOKER$i$0$0$call19.gen)", "org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:204)", "org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:200)", "org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:161)", "org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:314)", "org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)", "org.jruby.ir.interpreter.Interpreter.INTERPRET_BLOCK(Interpreter.java:132)", "org.jruby.runtime.MixedModeIRBlockBody.commonYieldPath(MixedModeIRBlockBody.java:148)", "org.jruby.runtime.IRBlockBody.call(IRBlockBody.java:73)", "org.jruby.runtime.Block.call(Block.java:124)", "org.jruby.RubyProc.call(RubyProc.java:289)", "org.jruby.internal.runtime.methods.ProcMethod.call(ProcMethod.java:63)", "org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:204)", "org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:200)", "org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:161)", "org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:314)", "org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)", "org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:83)", "org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:179)", "org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:165)", "org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:200)", "org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:161)", "org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:314)", "org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)", "org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:89)", "org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:214)", "org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:200)", "org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:208)", "org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:193)", "org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:323)", "org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)", "org.jruby.ir.interpreter.Interpreter.INTERPRET_BLOCK(Interpreter.java:132)", "org.jruby.runtime.MixedModeIRBlockBody.commonYieldPath(MixedModeIRBlockBody.java:148)", "org.jruby.runtime.IRBlockBody.call(IRBlockBody.java:73)", "org.jruby.runtime.Block.call(Block.java:124)", "org.jruby.RubyProc.call(RubyProc.java:289)", "org.jruby.RubyProc.call(RubyProc.java:246)", "org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:104)", "java.lang.Thread.run(Thread.java:748)"]}`

**Comment by guyboertje** [comment] 2017-11-27 10:17
So line 3592 `RubyMatchData match = useBackref ? (RubyMatchData)context.getBackRef() : (RubyMatchData)holder[0];` fails.
I tried to recreate and could not with:
```
input {
  generator {
    message => '{"fld_1": "a`b ", "fld_2": "-", "fld_3": 7}'
    count => 2
  }
}

filter {
  ruby {
    code => '
      nlog_str_inarr = event.get("message").split("")
      nlog_str_outarr = []
      nlog_str_outarr_buff = []
      nlog_str_outarr_buffenabled = false
      nlog_key_prefixmatch = [ "", "", "" ]
      nlog_inside_key = false
      nlog_str_inarr.each { |c|
        if c !~ /^\s$/
          nlog_key_prefixmatch[0] = nlog_key_prefixmatch[1]
          nlog_key_prefixmatch[1] = nlog_key_prefixmatch[2]
          nlog_key_prefixmatch[2] = c
       end
        # detect key values
        if ! nlog_inside_key
          if nlog_key_prefixmatch[2] == "\"" && (nlog_key_prefixmatch[1] == "{" || nlog_key_prefixmatch[1] == "," || nlog_key_prefixmatch[1] == "")
            nlog_inside_key = true
          end
        else
          if nlog_key_prefixmatch[2] == "\"" && nlog_key_prefixmatch[1] != "\\"
            nlog_inside_key = false
            nlog_str_outarr_buffenabled = true
         else
            c.downcase!
            if c !~ /^[a-zA-Z0-9_-]$/
              c = "_"
            end
          end
        end
        if ! nlog_str_outarr_buffenabled
          nlog_str_outarr.push(c)
        else
          # buffering until reach the value, after that determine if the value is object and in this case add to the key "_o" suffix
          nlog_str_outarr_buff.push(c)
          if nlog_key_prefixmatch[1] == ":"
            if nlog_key_prefixmatch[2] == "{"
              nlog_str_outarr.push("_o")
            end
            nlog_str_outarr_buff.each { |bc|
              nlog_str_outarr.push(bc)
            }
            nlog_str_outarr_buff = []
            nlog_str_outarr_buffenabled = false
          end
        end
      }
      event.set("json_message_parsed", nlog_str_outarr.join())
    '
  }
}

output {
  stdout { codec => rubydebug { metadata => true } }
}

```

**Comment by vbohata** [comment] 2017-11-27 13:20
So were you able to replicate the issue or do you need some anonymized sample data from me?

**Comment by original-brownbear** [comment] 2017-11-27 13:49
@guyboertje taking a look here, almost looks like a JRuby 9k bug?

**Comment by original-brownbear** [comment] 2017-11-27 13:59
this will take a while to reproduce in isolation, will try in vanilla JRuby but don't wanna block this issue if someone else wants to work on it or knows more about the ruby filter plugin

**Comment by original-brownbear** [comment] 2017-11-27 14:29
@guyboertje jup it's a JRuby bug as far as I can see:

```rb
str = '{"fld_1": "a`b ", "fld_2": "-", "fld_3": 7}'

running = true

splittt = lambda do |strr|
  begin
    res = strr.split("")
    res
  rescue => e
    puts("error")
    puts(e)
  end
end

one = Thread.new do
  puts "starting 1"
  while running do
    break if splittt.call(str).nil?
  end
end
two = Thread.new do
  puts "starting 2"
  while running do
    break if splittt.call(str).nil?
  end
end

while one.alive? && two.alive?
  sleep(1)
  puts "ping"
end
```

dies:

```sh
➜  logstash git:(repro-race-jruby-regex) ✗ ruby -Xcompile.invokedynamic=true -Xjit.threshold=0 regexrace.rb
starting 2starting 1

error
org.jruby.RubyNil cannot be cast to org.jruby.RubyMatchData
ping
```

It's ok to share a lambda across threads in (J)Ruby right?

**Comment by original-brownbear** [comment] 2017-11-27 14:33
@guyboertje sorry, that was stupid, answered my own question and validated that this is the issue:

```
➜  logstash git:(repro-race-jruby-regex) ✗ rvm use jruby-1.7.26
Using /Users/brownbear/.rvm/gems/jruby-1.7.26
➜  logstash git:(repro-race-jruby-regex) ✗ ruby -Xcompile.invokedynamic=true -Xjit.threshold=0 regexrace.rb
starting 1
starting 2
ping
ping            
```

<= Jruby `1.7.x` works fine => we broke this by upgrading to 9k.

**Comment by original-brownbear** [comment] 2017-11-27 14:37
link https://github.com/jruby/jruby/issues/4868

**Comment by guyboertje** [comment] 2017-11-27 15:36
@vbohata 

@original-brownbear confirmed this is a jruby bug and created an issue in JRuby.

I will test this with the new script path feature of logstash-filter-ruby v3.1.1

**Comment by guyboertje** [comment] 2017-11-27 15:49
@vbohata 

I can confirm that the bug does not occur when using the new script path feature in the latest ruby filter v 3.1.1

**Comment by guyboertje** [comment] 2017-11-27 15:54
Config
```ruby
input {
  generator {
    message => '{"fld_1": "a`b ", "fld_2": "-", "fld_3": 7}'
    count => 500
  }
}

filter {
  ruby {
    path => "/Users/guy/tmp/testing/scripts/multi-thread-split.rb"
  }
}

output {
  if "_rubyexception" in [tags] {
    stdout { codec => rubydebug { metadata => true } }
  }
}
```
multi-thread-split.rb
```ruby
# Disables mutex around the `filter` function
# Only use this if you know your code is threadsafe!
def concurrency
  :shared
end

def filter(event)
  nlog_str_inarr = event.get("message").split("")
  nlog_str_outarr = []
  nlog_str_outarr_buff = []
  nlog_str_outarr_buffenabled = false
  nlog_key_prefixmatch = [ "", "", "" ]
  nlog_inside_key = false
  nlog_str_inarr.each { |c|
    if c !~ /^\s$/
      nlog_key_prefixmatch[0] = nlog_key_prefixmatch[1]
      nlog_key_prefixmatch[1] = nlog_key_prefixmatch[2]
      nlog_key_prefixmatch[2] = c
   end
    # detect key values
    if ! nlog_inside_key
      if nlog_key_prefixmatch[2] == "\"" && (nlog_key_prefixmatch[1] == "{" || nlog_key_prefixmatch[1] == "," || nlog_key_prefixmatch[1] == "")
        nlog_inside_key = true
      end
    else
      if nlog_key_prefixmatch[2] == "\"" && nlog_key_prefixmatch[1] != "\\"
        nlog_inside_key = false
        nlog_str_outarr_buffenabled = true
     else
        c.downcase!
        if c !~ /^[a-zA-Z0-9_-]$/
          c = "_"
        end
      end
    end
    if ! nlog_str_outarr_buffenabled
      nlog_str_outarr.push(c)
    else
      # buffering until reach the value, after that determine if the value is object and in this case add to the key "_o" suffix
      nlog_str_outarr_buff.push(c)
      if nlog_key_prefixmatch[1] == ":"
        if nlog_key_prefixmatch[2] == "{"
          nlog_str_outarr.push("_o")
        end
        nlog_str_outarr_buff.each { |bc|
          nlog_str_outarr.push(bc)
        }
        nlog_str_outarr_buff = []
        nlog_str_outarr_buffenabled = false
      end
    end
  }
  event.set("json_message_parsed", nlog_str_outarr.join())

  [event]
end
```

See:
https://github.com/logstash-plugins/logstash-filter-ruby/blob/master/lib/logstash/filters/ruby.rb#L39
https://github.com/logstash-plugins/logstash-filter-ruby/blob/master/spec/fixtures/field_multiplier.rb

**Comment by andrewvc** [comment] 2017-11-27 17:13
Here's a link to the JRuby issue @original-brownbear made for reference: https://github.com/jruby/jruby/issues/4868

**Comment by vbohata** [comment] 2017-11-28 06:58
@guyboertje 
This will (if I understand it correctly) significantly slow down the whole pipeline as this will run one instance/method shared across multiple pipeline threads (using mutex).

Using the (old) code settings this should run non-blocking in each thread. It seems (https://github.com/jruby/jruby/issues/4868) lambda registration of the code at https://github.com/logstash-plugins/logstash-filter-ruby/blob/master/lib/logstash/filters/ruby.rb#L59 causes the race conditions in this issue.

**Comment by original-brownbear** [comment] 2017-11-28 10:10
Fixed in https://github.com/logstash-plugins/logstash-filter-ruby/pull/37, fixing the JRuby issue itself would be very complicated and appears to involve an issue of how Ruby lambdas work in general.

**Comment by original-brownbear** [comment] 2017-11-28 14:29
Version `3.1.2` of the Ruby filter was just published that and fixes this issue see https://rubygems.org/gems/logstash-filter-ruby/versions/3.1.2

**Closed by original-brownbear** 2017-11-28 14:29 UTC
Labels: bug, v6.0.0
