### ISSUE TITLE
A plugin had an unrecoverable error. Will restart this plugin

### ISSUE THREAD

**Issue by L1nja** [elastic/logstash#11532] opened 2020-01-23 11:10 UTC
Hello,

I am hoping someone could help me on an issue I am facing in our environment, which I have been trying to fault find for few days now without success. Below is the error I am getting on our logstash instance.

Jan 23 09:07:45 servername logstash: [2020-01-23T09:07:45,151][ERROR][logstash.pipeline] A plugin had an unrecoverable error. Will restart this plugin.
Jan 23 09:07:45 servername logstash: Pipeline_id:main
Jan 23 09:07:45 servername logstash: Plugin: <LogStash::Inputs::S3 access_key_id=>"************", add_field=>{"service"=>"cloudtrail"}, prefix=>"AWSLogs/************/CloudTrail/", secret_access_key=><password>, delete=>false, tags=>["platform", "cloudtrail", "aws", "property"], bucket=>"prqauditlogs", codec=><LogStash::Codecs::CloudTrail id=>"cloudtrail_************-****-****-****-************", enable_metric=>true, charset=>"UTF-8">, temporary_directory=>"/srv/log/cloudtrail/temp", interval=>300, id=>"************", region=>"eu-west-1", sincedb_path=>"/srv/log/sincedb/.*********", proxy_uri=>"http://xx.xx.xx.xx:3128", enable_metric=>true, role_session_name=>"logstash", watch_for_new_files=>true, include_object_properties=>false>
Jan 23 09:07:45 servername logstash: Error: Connection refused - Failed to open TCP connection to xx.xx.xx.xx:3128 (Connection refused - connect(2) for "xx.xx.xx.xx" port 3128)
Jan 23 09:14:32 servername logstash: Exception: Seahorse::Client::NetworkingError
Jan 23 09:14:32 servername logstash: Stack: org/jruby/ext/socket/RubyTCPSocket.java:135:in `initialize'
Jan 23 09:14:32 servername logstash: org/jruby/RubyIO.java:1155:in `open'
Jan 23 09:14:32 servername logstash: uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/net/http.rb:941:in `block in connect'
Jan 23 09:14:32 servername logstash: org/jruby/ext/timeout/Timeout.java:99:in `timeout'
Jan 23 09:14:32 servername logstash: uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/net/http.rb:939:in `connect'

I can telnet into the proxy server to which the logstash instance goes out. Also curl -v -k http://**.**.**.** 3128 connects okay. So thinking that network should not be a problem. Unless I missed something else?

Has anyone come across this issue before. Thanks in advance!

- Version: 6.8.4
- Operating System: centos7

**Comment by yaauie** [comment] 2020-01-23 22:11
Have you validated that the logstash host has a route to your proxy (e.g., ssh into your logstash host and issue your above curl command to validate the connection from there)? very often resolution problems like this occur because of firewall/routing rules between cloud-hosted infrastructure.

***

I am closing this issue, because we use the issue tracker here on Github for confirmed issues on Logstash core with clear reproduction steps, as noted in our issue template; I would encourage you to open a thread in the below-linked forums, where developers and community members work together to find solutions to problems:

:

> Please post all product and debugging questions on our [forum](https://discuss.elastic.co/c/logstash). Your questions will reach our wider community members there, and if we confirm that there is a bug, then we can open a new issue here.

Additionally, our issue template calls out that problems with specific plugins have their own issue trackers:

> Logstash Plugins are located in a different organization: https://github.com/logstash-plugins. For bugs on specific Logstash plugins, for example, if Redis Output has a defect, please open it in the respective Redis Output repository.

**Closed by yaauie** 2020-01-23 22:11 UTC
