### ISSUE TITLE
exception in running logstash

### ISSUE THREAD

**Issue by logstashbugreporter** [elastic/logstash#7377] opened 2017-06-08 00:31 UTC
hello, there, I got the following exception when running logstash: 

- Version: I download the current stable version logstash-5.4.1]
- Operating System: Redhat Enterprise R6.6(Santiago) 
- Config File (if you have sensitive info, please remove it):
input {
  beats {
    port => "5043"
  }
}

filter {
  mutate {
    rename => {
      "beat.hostname" => "beathost"
    }   
    remove_field => [ "@timestamp", "type", "@version", "tags", "beat" ]
  }
}

output {
  stdout { codec => rubydebug }
  kafka {
    topic_id => "graphlog"                                                                                                                                                     
  }

- Sample Data:
Before I added kafka output to the above config file, logstash ran file. 
After I added the kafka output to the logstash config file,  I still got output to stdout, but no output to kafka, and got the exception copied at the end. 
sample logstash output to stdout: 
{
       "host" => "yyu-XYZ",
     "source" => "/logs/myapp.out",
    "message" => "2017/06/06 18:29:20.974 WARN [ServiceMetricsEvent] [pool-6-thread-1] [cloud] [] Bababa"
}

- Steps to Reproduce:
I encountered this exception upon the first log event from filebeat:

Exception in thread "[main]>worker4" java.lang.ClassCastException: org.logstash.bivalues.StringBiValue cannot be cast to java.lang.String
	at org.logstash.Event.toString(Event.java:312)
	at org.logstash.ext.JrubyEventExtLibrary$RubyEvent.ruby_to_s(JrubyEventExtLibrary.java:209)
	at org.logstash.ext.JrubyEventExtLibrary$RubyEvent$INVOKER$i$0$0$ruby_to_s.call(JrubyEventExtLibrary$RubyEvent$INVOKER$i$0$0$ruby_to_s.gen)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:134)
	at org.jruby.ast.CallNoArgNode.interpret(CallNoArgNode.java:60)
	at org.jruby.ast.CallTwoArgNode.interpret(CallTwoArgNode.java:59)
	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
	at org.jruby.ast.IfNode.interpret(IfNode.java:118)
	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
	at org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:74)
	at org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:182)
	at org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.java:203)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:168)
	at org.jruby.ast.CallOneArgNode.interpret(CallOneArgNode.java:57)
	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
	at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
	at org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:74)
	at org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:182)
	at org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.java:203)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:168)
	at org.jruby.ast.FCallOneArgNode.interpret(FCallOneArgNode.java:36)
	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
	at org.jruby.evaluator.ASTInterpreter.INTERPRET_BLOCK(ASTInterpreter.java:112)
	at org.jruby.runtime.Interpreted19Block.evalBlockBody(Interpreted19Block.java:206)
	at org.jruby.runtime.Interpreted19Block.yield(Interpreted19Block.java:157)
	at org.jruby.runtime.Block.yield(Block.java:142)
	at org.jruby.RubyArray.eachCommon(RubyArray.java:1606)
	at org.jruby.RubyArray.each(RubyArray.java:1613)
	at org.jruby.RubyArray$INVOKER$i$0$0$each.call(RubyArray$INVOKER$i$0$0$each.gen)
	at org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:143)
	at org.jruby.runtime.callsite.CachingCallSite.callIter(CachingCallSite.java:154)
	at org.jruby.ast.CallNoArgBlockNode.interpret(CallNoArgBlockNode.java:64)
	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
	at org.jruby.ast.IfNode.interpret(IfNode.java:118)
	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
	at org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:74)
	at org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:182)
	at org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.java:203)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:168)
	at org.jruby.ast.CallOneArgNode.interpret(CallOneArgNode.java:57)
	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
	at org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:74)
	at org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:182)
	at org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.java:203)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:168)
	at org.jruby.ast.CallOneArgNode.interpret(CallOneArgNode.java:57)
	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
	at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
	at org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:74)
	at org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:182)
	at org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.java:203)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:168)
	at rubyjit.LogStash::Pipeline$$output_batch_75bfa3cb00ef46733d9a9d671234a933b6ebaa311118140819.block_3$RUBY$__file__(/home/yyu/tools/logstash-5.4.1/logstash-core/lib/logstash/pipeline.rb:407)
	at rubyjit$LogStash::Pipeline$$output_batch_75bfa3cb00ef46733d9a9d671234a933b6ebaa311118140819$block_3$RUBY$__file__.call(rubyjit$LogStash::Pipeline$$output_batch_75bfa3cb00ef46733d9a9d671234a933b6ebaa311118140819$block_3$RUBY$__file__)
	at org.jruby.runtime.CompiledBlock19.yield(CompiledBlock19.java:135)
	at org.jruby.runtime.Block.yield(Block.java:142)
	at org.jruby.RubyHash$13.visit(RubyHash.java:1355)
	at org.jruby.RubyHash.visitLimited(RubyHash.java:648)
	at org.jruby.RubyHash.visitAll(RubyHash.java:634)
	at org.jruby.RubyHash.iteratorVisitAll(RubyHash.java:1306)
	at org.jruby.RubyHash.each_pairCommon(RubyHash.java:1351)
	at org.jruby.RubyHash.each19(RubyHash.java:1342)
	at org.jruby.RubyHash$INVOKER$i$0$0$each19.call(RubyHash$INVOKER$i$0$0$each19.gen)
	at org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:143)
	at org.jruby.runtime.callsite.CachingCallSite.callIter(CachingCallSite.java:154)
	at rubyjit.LogStash::Pipeline$$output_batch_75bfa3cb00ef46733d9a9d671234a933b6ebaa311118140819.__file__(/home/yyu/tools/logstash-5.4.1/logstash-core/lib/logstash/pipeline.rb:406)
	at rubyjit.LogStash::Pipeline$$output_batch_75bfa3cb00ef46733d9a9d671234a933b6ebaa311118140819.__file__(/home/yyu/tools/logstash-5.4.1/logstash-core/lib/logstash/pipeline.rb)
	at org.jruby.internal.runtime.methods.JittedMethod.call(JittedMethod.java:181)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:168)
	at org.jruby.ast.FCallOneArgNode.interpret(FCallOneArgNode.java:36)
	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
	at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
	at org.jruby.ast.WhileNode.interpret(WhileNode.java:131)
	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
	at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
	at org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:74)
	at org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:225)
	at org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.java:219)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:202)
	at org.jruby.ast.FCallTwoArgNode.interpret(FCallTwoArgNode.java:38)
	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
	at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
	at org.jruby.evaluator.ASTInterpreter.INTERPRET_BLOCK(ASTInterpreter.java:112)
	at org.jruby.runtime.Interpreted19Block.evalBlockBody(Interpreted19Block.java:206)
	at org.jruby.runtime.Interpreted19Block.yield(Interpreted19Block.java:194)
	at org.jruby.runtime.Interpreted19Block.call(Interpreted19Block.java:125)
	at org.jruby.runtime.Block.call(Block.java:101)
	at org.jruby.RubyProc.call(RubyProc.java:300)
	at org.jruby.RubyProc.call(RubyProc.java:230)
	at org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:99)
	at java.lang.Thread.run(Thread.java:745)

**Comment by jsvd** [comment] 2017-06-09 15:19
this seems to be a duplicate of https://github.com/elastic/logstash/issues/6756

**Comment by logstashbugreporter** [comment] 2017-06-12 23:34
thanks for looking over this, I am wondering is there an ETA for fixing this bug?  thanks!

**Comment by colinsurprenant** [comment] 2017-06-16 15:48
In fact it is. We will followup in the original issue, thanks for your report @logstashbugreporter. The fix seems simple and hopefully should be possible to include for the next release.
Closing as duplicate.

**Closed by colinsurprenant** 2017-06-16 15:48 UTC
Labels: bug
