### ISSUE TITLE
logstash 6.0.0-alpha2 throws lir exception if two identical plugins are used in the inputs or outputs

### ISSUE THREAD

**Issue by jsvd** [elastic/logstash#7403] opened 2017-06-09 15:42 UTC
example:

```
/tmp/logstash-6.0.0-alpha2 % bin/logstash -e "input { generator { count => 1 } generator { count => 1 } }"
ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console.
Sending Logstash's logs to /tmp/logstash-6.0.0-alpha2/logs which is now configured via log4j2.properties
[2017-06-09T16:41:17,014][WARN ][logstash.config.source.multilocal] Ignoring the 'pipelines.yml' file because 'config.string' (-e) is being used.
[2017-06-09T16:41:17,078][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
[2017-06-09T16:41:17,251][ERROR][logstash.agent           ] Failed to execute action {:action=>LogStash::PipelineAction::Create/pipeline_id:main, :exception=>"Java::OrgLogstashConfigIr::InvalidIRException", :message=>"Some nodes on the graph are fully redundant!\n**GRAPH**\nVertices: 2 Edges: 0\n----------------------\n== Vertices Without Edges ==\nP[input-generator{\"count\"=>1}|[protocol]pipeline:2:9:```\ngenerator { count => 1 }\n```]\nP[input-generator{\"count\"=>1}|[protocol]pipeline:2:34:```\ngenerator { count => 1 }\n```]\n**GRAPH**|P[input-generator{\"count\"=>1}|[protocol]pipeline:2:9:```\ngenerator { count => 1 }\n```]===P[input-generator{\"count\"=>1}|[protocol]pipeline:2:34:```\ngenerator { count => 1 }\n```]"}
[2017-06-09T16:41:17,253][ERROR][logstash.agent           ] An exception happened when converging configuration {:exception=>LogStash::Error, :message=>"Don't know how to handle `Java::OrgLogstashConfigIr::InvalidIRException` for `LogStash::PipelineAction::Create/pipeline_id:main`", :backtrace=>["/tmp/logstash-6.0.0-alpha2/logstash-core/lib/logstash/converge_result.rb:27:in `create'", "/tmp/logstash-6.0.0-alpha2/logstash-core/lib/logstash/converge_result.rb:67:in `add'", "/tmp/logstash-6.0.0-alpha2/logstash-core/lib/logstash/agent.rb:351:in `converge_state'", "/tmp/logstash-6.0.0-alpha2/logstash-core/lib/logstash/agent.rb:139:in `with_pipelines'", "/tmp/logstash-6.0.0-alpha2/logstash-core/lib/logstash/agent.rb:337:in `converge_state'", "org/jruby/RubyArray.java:1613:in `each'", "/tmp/logstash-6.0.0-alpha2/logstash-core/lib/logstash/agent.rb:324:in `converge_state'", "/tmp/logstash-6.0.0-alpha2/logstash-core/lib/logstash/agent.rb:164:in `converge_state_and_update'", "/tmp/logstash-6.0.0-alpha2/logstash-core/lib/logstash/agent.rb:139:in `with_pipelines'", "/tmp/logstash-6.0.0-alpha2/logstash-core/lib/logstash/agent.rb:162:in `converge_state_and_update'", "/tmp/logstash-6.0.0-alpha2/logstash-core/lib/logstash/agent.rb:88:in `execute'", "/tmp/logstash-6.0.0-alpha2/logstash-core/lib/logstash/runner.rb:302:in `execute'", "org/jruby/RubyProc.java:281:in `call'", "/tmp/logstash-6.0.0-alpha2/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/task.rb:24:in `initialize'"]}

```

**Comment by original-brownbear** [comment] 2017-11-17 07:05
@andrewvc this one is kinda nasty I think :( Should I deal with it if you don't have any time?

**Comment by bmhughes** [comment] 2017-11-17 17:39
I've also ran into what I think is a similar version of this, if I use any duplicate if statements I get an error about duplicate IDs. I've got several of these in my filters looking at grokparsefailure to stop creating documents with rubbish in several fields, I've battled this for several days now with the v6 release and the only way I've managed to get logstash to start is to comment out the statements.

`[2017-11-17T11:38:32,706][ERROR][logstash.agent           ] Failed to execute action {:action=>LogStash::PipelineAction::Create/pipeline_id:main, :exception=>"Java::OrgLogstashConfigIr::InvalidIRException", :message=>"Config has duplicate Ids: \nID: 606e3c217cf1e68c891b1945bad63b0109be66fbc5043f563a38aa24819aa49e [if !(('_grokparsefailure'.include?event.getField('[tags]')))],[if !(('_grokparsefailure'.include?event.getField('[tags]')))],[if !(('_grokparsefailure'.include?event.getField('[tags]')))]", :backtrace=>["org.logstash.config.ir.graph.Graph.validate(org/logstash/config/ir/graph/Graph.java:292)", "org.logstash.config.ir.PipelineIR.<init>(org/logstash/config/ir/PipelineIR.java:52)", "java.lang.reflect.Constructor.newInstance(java/lang/reflect/Constructor.java:423)", "org.jruby.javasupport.JavaConstructor.newInstanceDirect(org/jruby/javasupport/JavaConstructor.java:246)", "org.jruby.RubyClass.newInstance(org/jruby/RubyClass.java:1022)", "org.jruby.RubyClass$INVOKER$i$newInstance.call(org/jruby/RubyClass$INVOKER$i$newInstance.gen)", "RUBY.compile_sources(/usr/share/logstash/logstash-core/lib/logstash/compiler.rb:30)", "RUBY.compile_lir(/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:107)", "RUBY.initialize(/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:49)", "RUBY.initialize(/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:215)", "org.jruby.RubyClass.newInstance(org/jruby/RubyClass.java:1022)", "org.jruby.RubyClass$INVOKER$i$newInstance.call(org/jruby/RubyClass$INVOKER$i$newInstance.gen)", "RUBY.execute(/usr/share/logstash/logstash-core/lib/logstash/pipeline_action/create.rb:35)", "RUBY.block in converge_state(/usr/share/logstash/logstash-core/lib/logstash/agent.rb:335)", "RUBY.with_pipelines(/usr/share/logstash/logstash-core/lib/logstash/agent.rb:141)", "RUBY.block in converge_state(/usr/share/logstash/logstash-core/lib/logstash/agent.rb:332)", "org.jruby.RubyArray.each(org/jruby/RubyArray.java:1734)", "org.jruby.RubyArray$INVOKER$i$0$0$each.call(org/jruby/RubyArray$INVOKER$i$0$0$each.gen)", "RUBY.converge_state(/usr/share/logstash/logstash-core/lib/logstash/agent.rb:319)", "RUBY.block in converge_state_and_update(/usr/share/logstash/logstash-core/lib/logstash/agent.rb:166)", "RUBY.with_pipelines(/usr/share/logstash/logstash-core/lib/logstash/agent.rb:141)", "RUBY.converge_state_and_update(/usr/share/logstash/logstash-core/lib/logstash/agent.rb:164)", "RUBY.block in execute(/usr/share/logstash/logstash-core/lib/logstash/agent.rb:105)", "org.jruby.RubyProc.call(org/jruby/RubyProc.java:289)", "org.jruby.RubyProc.call19(org/jruby/RubyProc.java:273)", "org.jruby.RubyProc$INVOKER$i$0$0$call19.call(org/jruby/RubyProc$INVOKER$i$0$0$call19.gen)", "RUBY.interval(/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/stud-0.0.23/lib/stud/interval.rb:18)", "RUBY.execute(/usr/share/logstash/logstash-core/lib/logstash/agent.rb:94)", "RUBY.block in execute(/usr/share/logstash/logstash-core/lib/logstash/runner.rb:362)", "org.jruby.RubyProc.call(org/jruby/RubyProc.java:289)", "org.jruby.RubyProc.call19(org/jruby/RubyProc.java:273)", "org.jruby.RubyProc$INVOKER$i$0$0$call19.call(org/jruby/RubyProc$INVOKER$i$0$0$call19.gen)", "RUBY.block in initialize(/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/stud-0.0.23/lib/stud/task.rb:24)", "org.jruby.RubyProc.call(org/jruby/RubyProc.java:289)", "org.jruby.RubyProc.call(org/jruby/RubyProc.java:246)", "java.lang.Thread.run(java/lang/Thread.java:748)"]}
[2017-11-17T11:38:32,709][ERROR][logstash.agent           ] An exception happened when converging configuration {:exception=>LogStash::Error, :message=>"Don't know how to handle `Java::OrgLogstashConfigIr::InvalidIRException` for `LogStash::PipelineAction::Create/pipeline_id:main`", :backtrace=>["/usr/share/logstash/logstash-core/lib/logstash/converge_result.rb:27:in `create'", "/usr/share/logstash/logstash-core/lib/logstash/converge_result.rb:67:in `add'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:347:in `block in converge_state'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:141:in `with_pipelines'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:332:in `block in converge_state'", "org/jruby/RubyArray.java:1734:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:319:in `converge_state'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:166:in `block in converge_state_and_update'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:141:in `with_pipelines'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:164:in `converge_state_and_update'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:105:in `block in execute'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/stud-0.0.23/lib/stud/interval.rb:18:in `interval'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:94:in `execute'", "/usr/share/logstash/logstash-core/lib/logstash/runner.rb:362:in `block in execute'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/stud-0.0.23/lib/stud/task.rb:24:in `block in initialize'"]}
`

**Comment by andrewvc** [comment] 2017-11-17 18:20
@bmhughes can you share your config? That would help us to debug it.

**Comment by bmhughes** [comment] 2017-11-18 14:01
Sure no problem I've attached it. I'm aware it's not the most tidy config in the world I currently working to sort it out but it did work fine with v5.

[conf.d.zip](https://github.com/elastic/logstash/files/1484628/conf.d.zip)

**Comment by original-brownbear** [comment] 2017-11-18 16:32
@andrewvc just an update here, the example @jsvd posted initially (and a few other with duplicate if statements I could not get to fail on `6.0.0` or `master`).
The config @bmhughes supplied fails for both `6.0.0` and `master` with the exact stack trace posted above => we clearly have a bug here.
I'll look into a fix here asap as discussed.

**Comment by original-brownbear** [comment] 2017-11-19 18:09
@andrewvc hah this took a while to find a minimal reproducer for :D because 
... this is failing randomly: if I just have the duplicate section twice in this test it happens rarely, if I let the `for` loop run `100` iterations it happens every time.

<img width="1560" alt="screen shot 2017-11-19 at 19 07 42" src="https://user-images.githubusercontent.com/6490959/32993772-fa74fa32-cd5c-11e7-8fc0-44f4d8bf8dcd.png">

Will track it down and fix later or tomorrow.

**Comment by original-brownbear** [comment] 2017-11-19 22:26
Adding a stable `hashCode` to `Vertex` and `Edge` (you can't use those as hash keys without forcing a stable `hashCode` on them since they have mutable fields) fixes the above example but not the client example.

i.e. 

```diff
 public abstract class Vertex implements SourceComponent, HashableWithSource {
+
+    private static final AtomicInteger SEQUENCE = new AtomicInteger();
+
+    private final int hashCode = SEQUENCE.incrementAndGet();
+
     private final SourceWithMetadata sourceWithMetadata;
     private Graph graph = this.getGraph();
     private volatile String contextualHashCache;
@@ -49,6 +55,15 @@ public abstract class Vertex implements SourceComponent, HashableWithSource {
         }
     }
 
+    @Override
+    public final int hashCode() {
+        return hashCode;
+    }
```

**Comment by andrewvc** [comment] 2017-11-22 11:08
@bmhughes would you mind if we used your attached config as a test case in our code? We'd need you to submit a PR and sign our CLA. If you cloud drop those files into `logstash-core/src/test/resources/org/logstash/config/ir/` that would be amazing and would help us move #7403 forward.

**Comment by bmhughes** [comment] 2017-11-22 14:45
Sure no problem, anything to help. 

I've created a PR #8711 and signed the CLA.

**Comment by original-brownbear** [comment] 2017-11-22 14:47
@bmhughes thanks! I'll look into that PR asap.

**Comment by original-brownbear** [comment] 2017-11-22 18:44
@andrewvc interesting ... with this merged, some other test related to this just randomly failed https://logstash-ci.elastic.co/job/elastic+logstash+6.x+multijob-unix-compatibility/os=oraclelinux/231/console ... back to it ...

**Comment by original-brownbear** [comment] 2017-11-22 18:48
completely deterministic failure here after 2 iterations (same hashes every time)

<img width="938" alt="screen shot 2017-11-22 at 19 47 37" src="https://user-images.githubusercontent.com/6490959/33144640-0687b98c-cfbe-11e7-8561-10d760340843.png">

**Comment by original-brownbear** [comment] 2017-11-22 18:56
no big alarm here, trivial fix incoming :)

**Comment by svnshikhil** [comment] 2017-11-23 13:24
solution-->

input {
  elasticsearch {
    hosts => ["XYZ:8000"] //ur host address
    index => "user_new_up"
  }
}

output {
  elasticsearch {
    hosts => ["localhost:9200"]
    index => "users"  
  }

  stdout {
    codec => "rubydebug"
  }
}

**Comment by original-brownbear** [comment] 2018-04-18 12:32
this was fixed by a series of PRs eventually and shouldn't happen anymore :)

**Closed by original-brownbear** 2018-04-18 12:32 UTC
Labels: bug, test failure

**Comment by cafuego** [comment] 2019-02-05 22:47
This just happened to me on 6.6.0 with a config that used a single `filter {}` statement containing two conditionals for two log format types that each had their own grok/date/mutate filters.

```
elk-logstash     | [2019-02-05T22:22:31,205][ERROR][logstash.agent           ] Failed to execute action {:action=>LogStash::PipelineAction::Create/pipeline_id:main, :exception=>"Java::OrgLogstashConfigIr::InvalidIRException", :message=>"Config has duplicate Ids: \nID: 88e3dd01579730050cc0d5319cf336e243da77ad5b91befa64cdb8f88f27aa1b [if (event.getField('[clientip]')!='-')],[if (event.getField('[clientip]')!='-')]", :backtrace=>["org.logstash.config.ir.graph.Graph.validate(org/logstash/config/ir/graph/Graph.java:292)", "org.logstash.config.ir.PipelineIR.<init>(org/logstash/config/ir/PipelineIR.java:52)", "java.lang.reflect.Constructor.newInstance(java/lang/reflect/Constructor.java:423)", "org.jruby.javasupport.JavaConstructor.newInstanceDirect(org/jruby/javasupport/JavaConstructor.java:246)", "org.jruby.RubyClass.newInstance(org/jruby/RubyClass.java:1022)", "org.jruby.RubyClass$INVOKER$i$newInstance.call(org/jruby/RubyClass$INVOKER$i$newInstance.gen)", "RUBY.compile_sources(/usr/share/logstash/logstash-core/lib/logstash/compiler.rb:30)", "RUBY.compile_lir(/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:107)", "RUBY.initialize(/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:49)", "RUBY.initialize(/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:215)", "org.jruby.RubyClass.newInstance(org/jruby/RubyClass.java:1022)", "org.jruby.RubyClass$INVOKER$i$newInstance.call(org/jruby/RubyClass$INVOKER$i$newInstance.gen)", "RUBY.execute(/usr/share/logstash/logstash-core/lib/logstash/pipeline_action/create.rb:35)", "RUBY.block in converge_state(/usr/share/logstash/logstash-core/lib/logstash/agent.rb:335)", "RUBY.with_pipelines(/usr/share/logstash/logstash-core/lib/logstash/agent.rb:141)", "RUBY.block in converge_state(/usr/share/logstash/logstash-core/lib/logstash/agent.rb:332)", "org.jruby.RubyArray.each(org/jruby/RubyArray.java:1734)", "org.jruby.RubyArray$INVOKER$i$0$0$each.call(org/jruby/RubyArray$INVOKER$i$0$0$each.gen)", "RUBY.converge_state(/usr/share/logstash/logstash-core/lib/logstash/agent.rb:319)", "RUBY.block in converge_state_and_update(/usr/share/logstash/logstash-core/lib/logstash/agent.rb:166)", "RUBY.with_pipelines(/usr/share/logstash/logstash-core/lib/logstash/agent.rb:141)", "RUBY.converge_state_and_update(/usr/share/logstash/logstash-core/lib/logstash/agent.rb:164)", "RUBY.execute(/usr/share/logstash/logstash-core/lib/logstash/agent.rb:90)", "RUBY.block in execute(/usr/share/logstash/logstash-core/lib/logstash/runner.rb:362)", "org.jruby.RubyProc.call(org/jruby/RubyProc.java:289)", "org.jruby.RubyProc.call19(org/jruby/RubyProc.java:273)", "org.jruby.RubyProc$INVOKER$i$0$0$call19.call(org/jruby/RubyProc$INVOKER$i$0$0$call19.gen)", "RUBY.block in initialize(/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/stud-0.0.23/lib/stud/task.rb:24)", "org.jruby.RubyProc.call(org/jruby/RubyProc.java:289)", "org.jruby.RubyProc.call(org/jruby/RubyProc.java:246)", "java.lang.Thread.run(java/lang/Thread.java:748)"]}
elk-logstash     | [2019-02-05T22:22:31,211][ERROR][logstash.agent           ] An exception happened when converging configuration {:exception=>LogStash::Error, :message=>"Don't know how to handle `Java::OrgLogstashConfigIr::InvalidIRException` for `LogStash::PipelineAction::Create/pipeline_id:main`", :backtrace=>["/usr/share/logstash/logstash-core/lib/logstash/converge_result.rb:27:in `create'", "/usr/share/logstash/logstash-core/lib/logstash/converge_result.rb:67:in `add'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:347:in `block in converge_state'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:141:in `with_pipelines'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:332:in `block in converge_state'", "org/jruby/RubyArray.java:1734:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:319:in `converge_state'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:166:in `block in converge_state_and_update'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:141:in `with_pipelines'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:164:in `converge_state_and_update'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:90:in `execute'", "/usr/share/logstash/logstash-core/lib/logstash/runner.rb:362:in `block in execute'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/stud-0.0.23/lib/stud/task.rb:24:in `block in initialize'"]}
```
