### ISSUE TITLE
Trying to delete log entery without index name

### ISSUE THREAD

**Issue by karasmeitar** [elastic/logstash#3506] opened 2015-06-26 21:32 UTC
Hi All,
I configured logstash to delete a log entry by using s3 input and elasticsearch output.
I didn't provide any index in the index attribute of the elasticsearch output part(because i don't know.).
I thought that logstash will search this document_id in all indexes but the document_id didn't deleted from the elasticsearch db and the delete file from the s3 bucket was removed.
What am i missing?

**Comment by untergeek** [comment] 2015-06-26 21:44
Deleting a document by _id in Elasticsearch requires 3 components, each necessary:
* Index name
* Type
* The document _id

If you are lacking one of those, you cannot delete by id.  Think of it like pinpointing a mailbox at an apartment building:  The zip code is the index name, the address is the type, and the mailbox number is the document _id.  In theory, there _could_ be two buildings in the same zip code with the same mailbox number but have different addresses.  Likewise you could have two identical addresses in two different zip codes, so there would be a collision there, too.  All 3 are necessary to delete by _id, or Elasticsearch will reject it.

Now, you can delete by query, where you look for that _id across multiple indices and hope there's only one (which is likely), but Logstash probably cannot do that in one step.  You'd need to search for the document in the elasticsearch input, and then you'd have the index, type and _id you could use.

**Comment by untergeek** [comment] 2015-06-26 21:46
Also, note, usage questions such as this should be at https://discuss.elastic.co/c/logstash

Closing as this is a usage issue, not a bug report.

**Closed by untergeek** 2015-06-26 21:46 UTC
