### ISSUE TITLE
Problem with sending logs to Elasticsearch when Java8 is used

### ISSUE THREAD

**Issue by prog8** [elastic/logstash#3638] opened 2015-07-22 08:04 UTC
This problem was mentioned here: https://discuss.elastic.co/t/1-5-0-elasticsearch-output-error/2105
and it appears when java 8 is used.

```
{:timestamp=>"2015-06-05T10:18:17.134000+0000", :message=>"Failed to flush outgoing items", :outgoing_count=>1, :exception=>#<NoMethodError: undefined methodmap' for "items":String>, :backtrace=>["/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-0.2.4-java/lib/logstash/outputs/elasticsearch/protocol.rb:93:innormalize_bulk_response'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-0.2.4-java/lib/logstash/outputs/elasticsearch/protocol.rb:108:inbulk'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-0.2.4-
```

**Comment by otisg** [comment] 2015-08-07 06:16
Ouch! @suyograo Do you know if the fix will be in 1.5.4?

**Comment by suyograo** [comment] 2015-08-07 07:13
@otisg yes, we'll get this in 1.5.4

**Comment by otisg** [comment] 2015-08-12 11:01
@suyograo @talevy Looks like 1.5.4 is out? https://github.com/elastic/logstash/blob/master/CHANGELOG.md - but I'm not sure if this made it in?

**Comment by purbon** [comment] 2015-08-12 11:03
@otisg 1.5.4 is not out, check https://www.elastic.co/downloads/logstash ... I guess the changes in the changelog somehow slip there accidentally.

**Comment by otisg** [comment] 2015-08-12 23:40
@purbon @suyograo Ouch, leak. Is there an ETA for 1.5.4?

**Comment by suyograo** [comment] 2015-08-13 06:25
@otisg actually @talevy was not able to reproduce this with java 8. 

Copying his reply from discuss here:
-------------------------------------------------

I am not seeing this behavior using Java 8.

can you try updating to the latest plugin version via

bin/plugin update logstash-output-elasticsearch
the @client client is the Elasticsearch Ruby Client, so I am not sure how 
the data type of the response has become a String.

**Comment by suyograo** [comment] 2015-08-13 06:26
@prog8 can you try updating your elasticsearch plugin as @talevy suggested? Also we need `java -version` information

**Comment by otisg** [comment] 2015-09-04 21:23
I've just witnessed a few more people who hit this bug.  They are using Logstash 1.5.4.  Here's the example config:

input {
  syslog { }
}

output {
  elasticsearch {
          host => "logsene-receiver.sematext.com"
          ssl => true
          port => 80
          index => "foo"
          protocol => http
          manage_template => false
 }
}

Updating the logstash-output-elasticsearch plugin ends up updating it to 2.0.0-beta2, which is probably not the right thing to do, but one of the people who hit this error did do that and it didn't help.

Any way I can provide more details, @talevy & @suyograo ?  Should we try --verbose and/or --debug to get more info?

**Comment by otisg** [comment] 2015-09-10 17:39
This can be closed.  Turns out Logstash was picky about Content-type response header.

**Comment by talevy** [comment] 2015-09-10 17:43
@otisg awesome, glad it got resolved!

**Closed by talevy** 2015-09-10 17:43 UTC
Labels: bug, needs details
