### ISSUE TITLE
logstash did not start on windows - JVM problem

### ISSUE THREAD

**Issue by nklt** [elastic/logstash#5996] opened 2016-10-04 20:46 UTC
Logstash 2.4.0 cannot start on Windows and throws a JVM exception.

C:\elastic\logstash-2.4.0>bin\logstash.bat -f c:\elastic\logstash-2.4.0\logstash.conf

The error message is  

```
JAVA_OPTS was set to [ -Xmx1g -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:+CMSParallelRemarkEnabled -XX:SurvivorRatio=8
 -XX:MaxTenuringThreshold=1 -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+HeapDumpOnOutO
fMemoryError -XX:HeapDumpPath="$LS_HOME/heapdump.hprof"]. Logstash will trust these options, and not set any defaults th
at it might usually set
Settings: Default pipeline workers: 1
←[31mPipeline aborted due to error {:exception=>"LogStash::ConfigurationError", :backtrace=>["C:/elastic/logstash-2.4.0/
vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/config/mixin.rb:88:in `config_init'", "org/jruby/Ruby
Hash.java:1342:in `each'", "C:/elastic/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash
/config/mixin.rb:72:in `config_init'", "C:/elastic/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/
lib/logstash/outputs/base.rb:79:in `initialize'", "C:/elastic/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/logstash-core-
2.4.0-java/lib/logstash/output_delegator.rb:74:in `register'", "C:/elastic/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/l
ogstash-core-2.4.0-java/lib/logstash/pipeline.rb:181:in `start_workers'", "org/jruby/RubyArray.java:1613:in `each'", "C:
/elastic/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/pipeline.rb:181:in `start_wor
kers'", "C:/elastic/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/pipeline.rb:136:in
 `run'", "C:/elastic/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/agent.rb:491:in `
start_pipeline'"], :level=>:error}←[0m
stopping pipeline {:id=>"main"}
The signal HUP is in use by the JVM and will not work correctly on this platform

```

The logstash configuration file is 

```
input {
  tcp {
    port => 5544
  }
}

output {
  elasticsearch {
    host => "localhost"
	protocol => "http"
  }
}
```

- Version: 2.4.0.
- Operating System: Windows Server 2012 R2 RTM
- Config File (if you have sensitive info, please remove it): pasted in message
- Sample Data: blank logstash server
- Steps to Reproduce:

**Comment by untergeek** [comment] 2016-10-05 13:03
The HUP message has nothing to do with Logstash's failure.  It is a benign message indicating that a HUP signal cannot be sent to the JVM (but this does not affect Logstash's functionality in any way).

In other words, if Logstash isn't starting, there's something else wrong.  In this case, the HUP error is not the one you should be looking at, but rather the `:exception=>"LogStash::ConfigurationError"`.  Logstash detected something it didn't like in your configuration.

Closing this as it is a duplicate of #5239

Please feel free to take your configuration question to our user forums at https://discuss.elastic.co/c/logstash

**Closed by untergeek** 2016-10-05 13:03 UTC

**Comment by untergeek** [comment] 2016-10-05 13:08
By the way, the problem is in the elasticsearch output block.  `host` needs to become `hosts`, and `protocol` is deprecated.  I'm not sure if you upgraded from an older version, or used an outdated configuration from a book or website.  The `protocol` flag has been deprecated since Logstash 2.0, and `host` was changed around the same time, if I recall correctly.

The current documentation can always be found online at https://www.elastic.co/guide/en/logstash/current/plugins-outputs-elasticsearch.html
