### ISSUE TITLE
Unable to find log4j2.properties on windows

### ISSUE THREAD

**Issue by trevorndodds** [elastic/logstash#6352] opened 2016-12-05 15:22 UTC
Windows, Logstash 5.0.2

When starting Logstash 5.0.1 and 5.0.2 logging no longer writes to to file. This was working on 5.0

    F:\ELK\logstash-5.0.2\bin>logstash -w4 -b2000 -f F:\ELK\logstash\configs\logstash-filebeat.conf --node.name logstash-filebeat -l F:\ELK\logstash\logs\logstash-filebeat
    Could not find log4j2 configuration at path /ELK/logstash-5.0.2/config/log4j2.properties. Using default config which logs to console

It seems to strip the full path to F:\ELK to /ELK

On 5.0

    Sending Logstash logs to F:\ELK\logstash\logs\logstash-filebeat which is now configured via log4j2.properties.

**Comment by julienadam** [comment] 2016-12-12 09:08
Can confirm this is still true for 5.1.1. Additionally, when that happens, the override switches --path.logs and --log.level are ignored and the output is sent to the console. Nothing is written to the log file specified in --path.logs or -l

> Could not find log4j2 configuration at path /logstash/logstash/config/log4j2.properties. Using default config which logs to console

**Comment by r3dlin3** [comment] 2016-12-21 23:35
As a workaround, the solution describes on [SO](http://stackoverflow.com/questions/40676294/logstash-cannot-find-log4j2-properties-file) do work.

**Comment by Mojster** [comment] 2017-03-01 09:44
Can confirm that this was not fixed with 5.2.2.
`Could not find log4j2 configuration at path /logstash/config/log4j2.properties.`
The right path should be:
`/config/log4j2.properties`

**Comment by trevorndodds** [comment] 2017-03-01 13:19
It's working for me but I have to specify --path.settings=

**Comment by Mojster** [comment] 2017-03-02 06:23
Thanks for the info.
I've fix mine with edit of _bin\setup.bat_.

Would be nice to see a permanent fix.

**Comment by xuanyuGIT** [comment] 2017-04-06 12:18
The problem is in the file `runner.rb` (`...\logstash-core\lib\logstash\runner.rb`), because Logstash uses `file://` prefix. Actually, it should use `file:///` prefix.

Changing the line `LogStash::Logging::Logger::initialize("file://" + log4j_config_location)` to `LogStash::Logging::Logger::initialize("file:///" + log4j_config_location)` will fix this problem.

It is the same for other cases which use a `file://` prefix. They should use `file:///`.

**Comment by suyograo** [comment] 2017-05-09 03:32
Fixed in 5.4.1 and 5.5

**Closed by suyograo** 2017-05-09 03:32 UTC
