### ISSUE TITLE
pipeline.batch settings ignored while persisted queue is enabled

### ISSUE THREAD

**Issue by shoggeh** [elastic/logstash#7243] opened 2017-05-28 23:52 UTC
- Version: 5.4.0
- Operating System: Linux
- Config File:

`/etc/logstash/logstash.yml`

```
  pipeline.batch.size: "4096"
  pipeline.batch.delay: "5000"
```

`/etc/logstash/conf.d/logstash.conf`
```
input { beats {} } 
output { elasticsearch { idle_flush_time => 5, flush_size => 4096 } }
```
- Sample Data:

I've been testing persisted queue and noticed very worrying thing: during normal operation elasticsearch {} output doesn't seem to accumulate output into batches at all. Settings like `idle_flush_time` / `flush_size` / `pipeline.batch.size / pipeline.batch.delay` have no real effect on actual batches size.

With beats {} input it's very visible that instead of sending accumulated batches, es output only sends as many events as provided by single beat input. It literally just dumps whatever it gets from inputs in real time.

- `queue.type: persisted` - separate bulk operations per beat input stream, being sent in real-time

```
POST /_bulk HTTP/1.1
{"index":{"_id":null,"_index":"test","_type":"log","_routing":null}}
{"offset":1,"input_type":"log","source":"/var/log/testA.log","program":"test","message":"test1",@timestamp":"2017-05-28T22:39:20.092Z","beat":{"name":"hostAAA"}}
{"index":{"_id":null,"_index":"test","_type":"log","_routing":null}}
{"offset":2,"input_type":"log","source":"/var/log/testA.log","program":"test","message":"test2",@timestamp":"2017-05-28T22:39:20.092Z","beat":{"name":"hostAAA"}}
```
```
POST /_bulk HTTP/1.1
{"index":{"_id":null,"_index":"test","_type":"log","_routing":null}}
{"offset":1,"input_type":"log","source":"/var/log/testB.log","program":"test","message":"test3",@timestamp":"2017-05-28T22:39:20.092Z","beat":{"name":"hostBBB"}}
```

- `queue.type: memory` - accumulated bulk operation up to `flush_size` / `idle_flush_time` / `pipeline.batch.size` / `pipeline.batch.delay` values

```
POST /_bulk HTTP/1.1
{"index":{"_id":null,"_index":"test","_type":"log","_routing":null}}
{"offset":1,"input_type":"log","source":"/var/log/testA.log","program":"test","message":"test1,"@timestamp":"2017-05-28T22:39:20.092Z","beat":{"name":"hostAAA"}}
{"index":{"_id":null,"_index":"test","_type":"log","_routing":null}}
{"offset":2,"input_type":"log","source":"/var/log/testA.log","program":"test","message":"test1,"@timestamp":"2017-05-28T22:39:20.092Z","beat":{"name":"hostAAA"}}
{"index":{"_id":null,"_index":"test","_type":"log","_routing":null}}
{"offset":1,"input_type":"log","source":"/var/log/testB.log","program":"test","message":"test1,"@timestamp":"2017-05-28T22:39:20.092Z","beat":{"name":"hostBBB"}}
```

As an end result this makes insane difference in number of bulk operations executed on ES side.
Observation is confirmed by ES stat from `_nodes/_local/stats` - `nodes.$node.indices.thread_pool.bulk.completed` can easily show two orders of magnitude difference with the same eps/volume being processed.

- Steps to Reproduce:
-- Run logstash with `queue.type: persisted` and `queue.type: memory`. 
-- Sniff events with `tcpdump -n -i lo dst port 9200 -s0 -A` or similar and compare results. 
-- Compare `indices.thread_pool.bulk.completed` stat provided by elasticsearch

As a side note: for whatever reason running `curl -XPUT 'localhost:9600/_node/logging?pretty' -H 'Content-Type: application/json' -d' { "logger.logstash.outputs.elasticsearch" : "TRACE" } '` to track events had no effect on my setup and nothing was logged. Is this expected? I had to use tcpdump instead.

**Comment by shoggeh** [comment] 2017-06-12 16:42
Just to give some numbers to it:

| queue.type | memory | persistent | 
| --- | --- | --- | 
| avg number of events imported per bulk operation | 400 | 4 |

**Comment by colinsurprenant** [comment] 2017-06-12 17:02
@shoggeh thanks for the report - this is strange and definitely requires investigation. I will try to reproduce and followup.

**Comment by skokhanovskiy** [comment] 2017-06-30 12:48
I have same issue too.
In my case, elasticsearch is behind nginx. This is access log when persisted queue is disabled (memory):
```
...
192.168.91.35 - - [30/Jun/2017:15:27:17 +0300] "POST /_bulk HTTP/1.1" 200 15351 "-" "Manticore 0.6.1" 1.640
192.168.91.35 - - [30/Jun/2017:15:27:46 +0300] "POST /_bulk HTTP/1.1" 200 15369 "-" "Manticore 0.6.1" 1.467
192.168.91.35 - - [30/Jun/2017:15:28:19 +0300] "POST /_bulk HTTP/1.1" 200 15382 "-" "Manticore 0.6.1" 3.624
192.168.91.35 - - [30/Jun/2017:15:28:51 +0300] "POST /_bulk HTTP/1.1" 200 15369 "-" "Manticore 0.6.1" 1.520
192.168.91.35 - - [30/Jun/2017:15:29:18 +0300] "POST /_bulk HTTP/1.1" 200 15435 "-" "Manticore 0.6.1" 1.398
192.168.91.35 - - [30/Jun/2017:15:29:50 +0300] "POST /_bulk HTTP/1.1" 200 15427 "-" "Manticore 0.6.1" 1.362
192.168.91.35 - - [30/Jun/2017:15:30:20 +0300] "POST /_bulk HTTP/1.1" 200 15376 "-" "Manticore 0.6.1" 1.598
...
```
This is when persisted queue is enabled:
```
...
192.168.91.35 - - [30/Jun/2017:15:22:57 +0300] "POST /_bulk HTTP/1.1" 200 154 "-" "Manticore 0.6.1" 0.002
192.168.91.35 - - [30/Jun/2017:15:22:57 +0300] "POST /_bulk HTTP/1.1" 200 153 "-" "Manticore 0.6.1" 0.001
192.168.91.35 - - [30/Jun/2017:15:22:57 +0300] "POST /_bulk HTTP/1.1" 200 155 "-" "Manticore 0.6.1" 0.002
192.168.91.35 - - [30/Jun/2017:15:22:57 +0300] "POST /_bulk HTTP/1.1" 200 157 "-" "Manticore 0.6.1" 0.002
192.168.91.35 - - [30/Jun/2017:15:22:57 +0300] "POST /_bulk HTTP/1.1" 200 157 "-" "Manticore 0.6.1" 0.002
... many many lines here ...
192.168.91.35 - - [30/Jun/2017:15:22:57 +0300] "POST /_bulk HTTP/1.1" 200 173 "-" "Manticore 0.6.1" 0.004
192.168.91.35 - - [30/Jun/2017:15:22:57 +0300] "POST /_bulk HTTP/1.1" 200 167 "-" "Manticore 0.6.1" 0.002
192.168.91.35 - - [30/Jun/2017:15:22:57 +0300] "POST /_bulk HTTP/1.1" 200 153 "-" "Manticore 0.6.1" 0.002
192.168.91.35 - - [30/Jun/2017:15:22:57 +0300] "POST /_bulk HTTP/1.1" 200 153 "-" "Manticore 0.6.1" 0.002
192.168.91.35 - - [30/Jun/2017:15:22:58 +0300] "POST /_bulk HTTP/1.1" 200 153 "-" "Manticore 0.6.1" 0.002
...
```
Pipeline configuration:
```
# cat /etc/logstash/logstash.yml | grep batch | grep -v ^#
pipeline.batch.size: 5000
pipeline.batch.delay: 5000
```
Logstash is used to collect the syslog by logstash-input-udp plugin and send parsed to elasticsearch cluster.

**Comment by shoggeh** [comment] 2017-06-30 15:06
Thanks @skokhanovskiy, that's exactly my observation too.

Additionally (as long as I understand meaning of values correctly in`_node/stats` correctly my logtsash instances are spending vast majority of time (**50%**) in elasticsearch output. This seems to be related to connection overhead caused by very small batches:

| queue.type | memory | persistent | 
| --- | --- | --- | 
| avg number of events imported per bulk operation | 400 | 4 |
| % of time spent in ES output | 7% | 50 % |

- `queue.type: persisted`
```
  "pipeline" : {
    "events" : {
      "duration_in_millis" : 4044541,
      "queue_push_duration_in_millis" : 285535
```
```
      "outputs" : [ {
        "events" : {
          "duration_in_millis" : 2054033,
        },
        "name" : "elasticsearch"
```

`2054033/4044541` = 50% of the time spent in ES output

- `queue.type: memory`

```
  "pipeline" : {
    "events" : {
      "duration_in_millis" : 2767433,
      "queue_push_duration_in_millis" : 12119
```
```
      "outputs" : [ {
        "events" : {
          "duration_in_millis" : 214446,
        },
        "name" : "elasticsearch"
```

`214446/2767433` = 7.7% of the time spent in ES output

Additionally Elasticsearch load seems to be slightly higher too when dealing with smaller batches.

**Comment by shoggeh** [comment] 2017-07-07 18:09
(Still actual in 5.5)

**Comment by berglh** [comment] 2017-07-13 23:24
This is pretty strange, I'm about to do some performance tuning on end of the logstash pipeline myself and noted the new batch behaviour of the [logstash-output-elasticsearch](https://www.elastic.co/guide/en/logstash/current/plugins-outputs-elasticsearch.html#_batch_sizes) plugin:

> This plugin attempts to send batches of events as a single request. However, if a request exceeds 20MB we will break it up until multiple batch requests. If a single document exceeds 20MB it will be sent as a single request.

Going back to version `logstash 5.0.2`, where this batch feature wasn't documented and I assume must be adhering to the flush size parameter, the `logstash-output-elasticsearch` plugin was version `logstash-output-elasticsearch (5.2.1)`. As of `logstash 5.1`, this feature was documented, perhaps you can try to downgrade the plugin to see if it adheres to the batch/flush event sizes - hopefully it's still compatible with `5.5`.

**Comment by shoggeh** [comment] 2017-07-17 17:01
@colinsurprenant sorry for being impatient, but is original issue considered a bug? I have to say I'm quite puzzled about it -- vast majority of ES guides say that event batching is a key factor to proper performance, but it seems this functionality is... non-functional with PQ enabled.

**Comment by colinsurprenant** [comment] 2017-11-09 19:17
Sorry for the delay here @shoggeh. Thanks @skokhanovskiy for confirming the behaviour. 
We will need to investigate to figure out why there is such a *bulking* difference at the ES output plugin when using in-memory queuing vs persisted queues.

**Comment by colinsurprenant** [comment] 2017-11-09 20:51
So, looking at this, the ES output plugin does not buffer anything internally anymore and only rely on the received batch size. Config options `flush_size` and `idle_flush_time` are deprecated and have no impact.

So the problem is about the size of each batch being built in LS prior to sending it to the worker.
- With persistent queues, the behaviour in a situation where output is **faster** than inputs, meaning the queue is always almost empty, the PQ will build a batch with whichever elements are in the queue at the moment the read operation is done. the timeout is only applied for when there's no element in the queue. In other words, the queue read operation is eagerly building a batch with the element that are in the queue at the moment of the read and will not try to *optimize* the batch size within the timeout period. 

- Looking at the recent changes in this area it *appears* (to be confirmed) that the behaviour we are seeing for the memory queueing is different: it will optimize the batch size within the timeout period.  Also, looking at the code it *seems* there is an interesting bug and it will actually always build a full batch regardless of the timeout. I will double check this but it has to do with [this code](https://github.com/elastic/logstash/blob/130fcf46a0514700254db69019e7294900db746c/logstash-core/src/main/java/org/logstash/common/LsQueueUtils.java#L82-L93) where eventually `queue.poll` will be passed a negative timeout value. Looking at the ArrayBlockingQueue implementation, it seems the negative timeout condition is only checked **after**  first looking if there are elements in the queue to return.

I will be working on double checking this and see if bugs need fixing and how we can make that behave better WRT the ES output bulking.

**Comment by colinsurprenant** [comment] 2017-11-10 00:43
Created #8632 to fix memory queue batch read timeout handling.
Created #8633 to discuss the batch creation semantics difference between Persistent Queue  and Memory Queue.

**Comment by colinsurprenant** [comment] 2017-12-05 19:09
This issue will be solved by #8702 which will be included in the upcoming 6.2 release.

**Comment by colinsurprenant** [comment] 2018-02-06 19:54
6.2 has just been released, would love to hear how this is working for you now @shoggeh @skokhanovskiy @berglh thanks!

**Comment by FranGM** [comment] 2018-02-06 21:44
Subbing in for @shoggeh here, we just completed the upgrade to 6.2 and overall things are looking a lot better!
`thread_pool.bulk.completed` is currently 1/5th of what it was pre-upgrade, and we're currently seeing a ~10% CPU usage decrease across our cluster. ES also seems happier, with a lot less times spent on merges.

**Comment by colinsurprenant** [comment] 2018-02-06 22:12
Thanks @FranGM for the update! This is awesome!

**Comment by colinsurprenant** [comment] 2018-02-08 21:34
I will go ahead and close this issue - but please go ahead and share your experience about this fix and let us know if it is working for you or not, I'll be monitoring.

**Closed by colinsurprenant** 2018-02-08 21:34 UTC
Labels: bug, persistent queues

**Comment by shoggeh** [comment] 2018-02-08 22:54
@colinsurprenant, @FranGM provided results from the same environment where the problem was originally spotted. All looks great, thanks!
