### ISSUE TITLE
Logstash crashes with ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by avinchakov** [elastic/logstash#8860] opened 2017-12-19 15:06 UTC
- **Version**: 6.1.0
- **Operating System**: Ubuntu 16.04.03 LTS 64GB RAM 24 CPU ELK-stack
- **Config File**:
logstash.yml
```
path.data: /var/lib/logstash
pipeline.workers: 24
pipeline.output.workers: 24
pipeline.batch.size: 1
pipeline.batch.delay: 5
path.config: /etc/logstash/conf.d
config.reload.automatic: false
queue.type: memory
path.logs: /var/log/logstash
```
jvm.options
```
-Xms6g
-Xmx6g
-XX:+UseParNewGC
-XX:+UseConcMarkSweepGC
-XX:CMSInitiatingOccupancyFraction=75
-XX:+UseCMSInitiatingOccupancyOnly
-XX:+DisableExplicitGC
-Djava.awt.headless=true
-Dfile.encoding=UTF-8
-XX:+HeapDumpOnOutOfMemoryError
```
- Sample Data: none
- Steps to Reproduce: upgrade from 5.6.2 to 6.1.0

Error log from syslog - https://pastebin.com/87wYHnLZ
Logstash log: - https://pastebin.com/Q8YQd7TV

**Comment by jsvd** [comment] 2017-12-19 15:13
duplicate of https://github.com/elastic/logstash/issues/8823
this will be fixed in 6.1.2

**Closed by jsvd** 2017-12-19 15:13 UTC
