### ISSUE TITLE
Exception in pipelineworker, the pipeline stopped processing new events, please check your filter configuration and restart Logstash

### ISSUE THREAD

**Issue by kaboalsoud** [elastic/logstash#10849] opened 2019-06-09 12:05 UTC
######################Error logs for  logstash======#############

[2019-06-09T14:22:58,810][ERROR][org.logstash.execution.WorkerLoop] Exception in pipelineworker, the pipeline stopped processing new events, please check your filter configuration and restart Logstash.
org.jruby.exceptions.SystemCallError: (SystemCallError) Unknown error (SystemCallError) - <STDOUT>
        at org.jruby.RubyIO.write(org/jruby/RubyIO.java:1472) ~[jruby-complete-9.2.7.0.jar:?]
        at org.jruby.RubyIO.write(org/jruby/RubyIO.java:1429) ~[jruby-complete-9.2.7.0.jar:?]
        at app.logstash_minus_7_dot_1_dot_1.vendor.bundle.jruby.$2_dot_5_dot_0.gems.logstash_minus_output_minus_stdout_minus_3_dot_1_dot_4.lib.logstash.outputs.stdout.multi_receive_encoded(/app/logstash-7.1.1/vendor/bundle/jruby/2.5.0/gems/logstash-output-stdout-3.1.4/lib/logstash/outputs/stdout.rb:43) ~[?:?]
        at org.jruby.RubyArray.each(org/jruby/RubyArray.java:1792) ~[jruby-complete-9.2.7.0.jar:?]
        at app.logstash_minus_7_dot_1_dot_1.vendor.bundle.jruby.$2_dot_5_dot_0.gems.logstash_minus_output_minus_stdout_minus_3_dot_1_dot_4.lib.logstash.outputs.stdout.multi_receive_encoded(/app/logstash-7.1.1/vendor/bundle/jruby/2.5.0/gems/logstash-output-stdout-3.1.4/lib/logstash/outputs/stdout.rb:42) ~[?:?]
        at app.logstash_minus_7_dot_1_dot_1.logstash_minus_core.lib.logstash.outputs.base.multi_receive(/app/logstash-7.1.1/logstash-core/lib/logstash/outputs/base.rb:87) ~[?:?]
        at org.logstash.config.ir.compiler.OutputStrategyExt$AbstractOutputStrategyExt.multi_receive(org/logstash/config/ir/compiler/OutputStrategyExt.java:118) ~[logstash-core.jar:?]
        at org.logstash.config.ir.compiler.AbstractOutputDelegatorExt.multi_receive(org/logstash/config/ir/compiler/AbstractOutputDelegatorExt.java:101) ~[logstash-core.jar:?]
        at app.logstash_minus_7_dot_1_dot_1.logstash_minus_core.lib.logstash.java_pipeline.start_workers(/app/logstash-7.1.1/logstash-core/lib/logstash/java_pipeline.rb:235) ~[?:?]

#############################################################

- Version: logstash-7.1.1
 java :openjdk version "1.8.0_212"
- Operating System: Rhel 7.6
- Config File (if you have sensitive info, please remove it):
input {
    beats {
       "
         add_field => { "pipeline_receiver" => "beats-receiver-5044"}
        port => "5044"
    }
}

filter {
  grok {
         match => { "message" => "%{TIMESTAMP_ISO8601:timestamp} %{LOGLEVEL:loglevel} +\[%{DATA:logger}\] %{GREEDYDATA:msgdetail}" }
         add_field => [ "received_at", "%{@timestamp}" ]
         add_field => [ "received_from", "%{host}" ]
   }
}

output {

  stdout {
    codec => rubydebug
  }

  if [type] == "Jboss_log"
 {
  elasticsearch {
    hosts => ["10.21.130.22:9200"]
    sniffing => true
    manage_template => false
    index => "jboss-%{+YYYY.MM.dd}"

  }
}
else
  {
elasticsearch {
    hosts => ["10.21.130.22:9200"]
    sniffing => true
    manage_template => false
    index => "%{[@metadata][beat]}-%{[@metadata][version]}-%{+YYYY.MM.dd}"

}
}
#################################

- Sample Data:
jboss server logs 
16:18:02,516 INFO  [org.jboss.as] (MSC service thread 1-7) JBAS015899: JBoss EAP 6.4.0.GA (AS 7.5.0.Final-redhat-21) starting
16:18:02,526 DEBUG [org.jboss.as.config] (MSC service thread 1-7) Configured system properties:
        [Standalone] =
        awt.toolkit = sun.awt.X11.XToolkit
        com.stc.mylink.environment = preprod
        file.encoding = UTF-8
        file.encoding.pkg = sun.io
        file.separator = /
        https.cipherSuites = TLS_RSA_WITH_AES_256_CBC_SHA,TLS_RSA_WITH_AES_128_CBC_SHA,SSL_RSA_WITH_3DES_EDE_CBC_SHA
        https.protocols = TLSv1.2
        java.awt.graphicsenv = sun.awt.X11GraphicsEnvironment
        java.awt.headless = true
        java.awt.printerjob = sun.print.PSPrinterJob
        java.class.path = /app/liferay_home_new/jboss-eap-6.4/jboss-modules.jar
        java.class.version = 52.0
        java.endorsed.dirs = /app/java/jdk1.8.0_181/jre/lib/endorsed
        java.ext.dirs = /app/java/jdk1.8.0_181/jre/lib/ext:/usr/java/packages/lib/ext
        java.home = /app/java/jdk1.8.0_181/jre

- Steps to Reproduce:

**Comment by yaauie** [comment] 2019-06-12 19:44
Since this is a general usage question and not a reproducible bug report or a feature request, I am closing this issue.

> Please post all product and debugging questions on our [forum](https://discuss.elastic.co/c/logstash).
> Your questions will reach our wider community members there, and if we confirm that there is a bug, then we can open a new issue here.
> 
> -- [Logstash Issue Template](https://raw.githubusercontent.com/elastic/logstash/master/.github/ISSUE_TEMPLATE.md)

Hopefully the following will help you get on track, but if you need more, please open a thread on the [forum](https://discuss.elastic.co/c/logstash).

***

When the Stdout Output plugin sent `IO#write` to `$stdout`, a `SystemCallError` was raised, indicating that your operating system refused to perform the write (perhaps because the underlying io channel was already closed).

My best guess is that you are starting Logstash up without an open channel to stdout (the `java.awt.headless = true` is fishy). I've opened up an issue on the plugin to help us have a more informative error: https://github.com/logstash-plugins/logstash-output-stdout/issues/16

**Closed by yaauie** 2019-06-12 19:44 UTC
