### ISSUE TITLE
How to update logstash 8.9.1 to 8.12.02

### ISSUE THREAD

**Issue by Micheal-Madhan** [elastic/logstash#16018] opened 2024-03-21 12:40 UTC
"Hi, this is Michael Mathan S. I'm trying to upgrade Logstash from version 8.9.1 to 8.12.2, but I'm encountering several errors. Could you please advise me on how to fix the following errors?

**Error 1:**
[2024-03-20T11:56:35,871][ERROR][logstash.outputs.elasticsearch][main] Failed to install template: Got response code '400' contacting Elasticsearch at URL 'http://localhost:9200/_index_template/lims'. The error message indicates: 'x_content_parse_exception', with the reason being '[1:44] [index_template] unknown field [settings]'.

**Error 2:**
[2024-03-21T15:10:04,942][ERROR][logstash.javapipeline][main] Pipeline error: NoMethodError: undefined method `serverless?' for #<LogStash::Outputs::ElasticSearch::HttpClient::Pool:0x2373b975>.

Attached are my logstash.config and LIMSIndices.json files for your reference.

**[logstash.config contents]**

    # Sample Logstash configuration for creating a simple
    # Beats -> Logstash -> Elasticsearch pipeline.
    
    input {
      beats {
        client_inactivity_timeout => 600
        port => 5044
      }
    }
    
    filter{
        mutate{
            replace => [ "message", "%{message}" ]
            gsub => [ 'message','\n','']
        }
    
        if [message] =~ /^{.*}$/{
            json { source => message }
        }
    }
    
    output {
     if [fields][log_type] == "Order" {
          elasticsearch {
            hosts => ["http://localhost:9200/"]
            index => "lims-%{[fields][log_type]}-%{+yyyy-MM}"
            template_overwrite => "true"
            template_name => "lims"
            manage_template => true
            template => "../Logstash/LimsIndexTemplate/LIMSIndices.json"
            user => ["LimsKLESuperUser"]
            password => "${ES_PWD}"
          }
      }
      else{
          elasticsearch {
            hosts => ["http://localhost:9200/"]
            index => "lims-%{[fields][log_type]}-%{+yyyy}"
            template_overwrite => "true"
            template_name => "lims"
            manage_template => true
            template => "../Logstash/LimsIndexTemplate/LIMSIndices.json"
            user => ["LimsKLESuperUser"]
            password => "${ES_PWD}"
          }
         }
    }

**[LIMSIndices.json contents]**

    {
      "index_patterns" : "lims-*",
      "version" : 60001,
      "settings" : {
        "index.refresh_interval" : "5s",
        "index.mapping.total_fields.limit": 3000,
        "number_of_shards": 1,
        "number_of_replicas" : 0
      },
      "mappings" : {
        "dynamic_templates" : [ {
          "message_field" : {
            "path_match" : "message",
            "match_mapping_type" : "string",
            "mapping" : {
              "type" : "text",
              "norms" : false
            }
          }
        }, {
          "string_fields" : {
            "match" : "*",
            "match_mapping_type" : "string",
            "mapping" : {
              "type" : "text", "norms" : false,
              "fields" : {
                "keyword" : { "type": "keyword", "ignore_above": 256 }
              }
            }
          }
        } ],
        "properties" : {
          "@timestamp": { "type": "date"},
          "@version": { "type": "keyword"},
          "geoip"  : {
            "dynamic": true,
            "properties" : {
              "ip": { "type": "ip" },
              "location" : { "type" : "geo_point" },
              "latitude" : { "type" : "half_float" },
              "longitude" : { "type" : "half_float" }
            }
          }
        }
      }
    }

Could you please review these and provide guidance? Thanks!"

**Comment by kaisecheng** [comment] 2024-03-21 12:48
@Micheal-Madhan could you provide the full error log?

**Comment by Micheal-Madhan** [comment] 2024-03-21 12:56
@kaisecheng  Here's the full error log:

```
[2024-03-21T18:19:20,639][ERROR][logstash.javapipeline    ][main] Pipeline error {:pipeline_id=>"main", :exception=>#<NoMethodError: undefined method `serverless?' for #<LogStash::Outputs::ElasticSearch::HttpClient::Pool:0x540140e1>>, :backtrace=>["C:/LIMSAudit/Logstash/vendor/bundle/jruby/3.1.0/gems/logstash-output-elasticsearch-11.22.2-java/lib/logstash/outputs/elasticsearch/license_checker.rb:14:in `appropriate_license?'", "C:/LIMSAudit/Logstash/vendor/bundle/jruby/3.1.0/gems/logstash-output-elasticsearch-11.22.2-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:262:in `block in healthcheck!'", "org/jruby/ext/thread/Mutex.java:171:in `synchronize'", "C:/LIMSAudit/Logstash/vendor/bundle/jruby/3.1.0/gems/logstash-output-elasticsearch-11.22.2-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:258:in `block in healthcheck!'", "org/jruby/RubyHash.java:1601:in `each'", "C:/LIMSAudit/Logstash/vendor/bundle/jruby/3.1.0/gems/logstash-output-elasticsearch-11.22.2-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:238:in `healthcheck!'", "C:/LIMSAudit/Logstash/vendor/bundle/jruby/3.1.0/gems/logstash-output-elasticsearch-11.22.2-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:376:in `update_urls'", "C:/LIMSAudit/Logstash/vendor/bundle/jruby/3.1.0/gems/logstash-output-elasticsearch-11.22.2-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:87:in `update_initial_urls'", "C:/LIMSAudit/Logstash/vendor/bundle/jruby/3.1.0/gems/logstash-output-elasticsearch-11.22.2-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:81:in `start'", "C:/LIMSAudit/Logstash/vendor/bundle/jruby/3.1.0/gems/logstash-output-elasticsearch-11.22.2-java/lib/logstash/outputs/elasticsearch/http_client.rb:369:in `build_pool'", "C:/LIMSAudit/Logstash/vendor/bundle/jruby/3.1.0/gems/logstash-output-elasticsearch-11.22.2-java/lib/logstash/outputs/elasticsearch/http_client.rb:63:in `initialize'", "org/jruby/RubyClass.java:904:in `new'", "C:/LIMSAudit/Logstash/vendor/bundle/jruby/3.1.0/gems/logstash-output-elasticsearch-11.22.2-java/lib/logstash/outputs/elasticsearch/http_client_builder.rb:106:in `create_http_client'", "C:/LIMSAudit/Logstash/vendor/bundle/jruby/3.1.0/gems/logstash-output-elasticsearch-11.22.2-java/lib/logstash-output-elasticsearch-11.22.2-java/lib/logstash/outputs/elasticsearch/http_client_builder.rb:102:in `build'", "C:/LIMSAudit/Logstash/vendor/bundle/jruby/3.1.0/gems/logstash-output-elasticsearch-11.22.2-java/lib/logstash/plugin_mixins/elasticsearch/common.rb:42:in `build_client'", "C:/LIMSAudit/Logstash/vendor/bundle/jruby/3.1.0/gems/logstash-output-elasticsearch-11.22.2-java/lib/logstash/outputs/elasticsearch.rb:300:in `register'", "org/logstash/config/ir/compiler/AbstractOutputDelegatorExt.java:69:in `register'", "C:/LIMSAudit/Logstash/logstash-core/lib/logstash/java_pipeline.rb:237:in `block in register_plugins'", "org/jruby/RubyArray.java:1989:in `each'", "C:/LIMSAudit/Logstash/logstash-core/lib/logstash/java_pipeline.rb:236:in `register_plugins'", "C:/LIMSAudit/Logstash/logstash-core/lib/logstash/java_pipeline.rb:610:in `maybe_setup_out_plugins'", "C:/LIMSAudit/Logstash/logstash-core/lib/logstash/java_pipeline.rb:249:in `start_workers'", "C:/LIMSAudit/Logstash/logstash-core/lib/logstash/java_pipeline.rb:194:in `run'", "C:/LIMSAudit/Logstash/logstash-core/lib/logstash/java_pipeline.rb:146:in `block in start'"], "pipeline.sources"=>["C:/LIMSAudit/logstash/logstash.conf"], :thread=>"#<Thread:0x67c68514 C:/LIMSAudit/Logstash/logstash-core/lib/logstash/java_pipeline.rb:134 run>"}
[2024-03-21T18:19:20,735][INFO ][logstash.javapipeline    ][main] Pipeline terminated {"pipeline.id"=>"main"}
[2024-03-21T18:19:20,749][ERROR][logstash.agent           ] Failed to execute action {:id=>:main, :action_type=>LogStash::ConvergeResult::FailedAction, :message=>"Could not execute action: PipelineAction::Create<main>, action_result: false", :backtrace=>nil}
[2024-03-21T18:19:20,772][INFO ][logstash.runner          ] Logstash shut down.
[2024-03-21T18:19:20,785][FATAL][org.logstash.Logstash    ] Logstash stopped processing because of an error: (SystemExit) exit
org.jruby.exceptions.SystemExit: (SystemExit) exit
	at org.jruby.RubyKernel.exit(org/jruby/RubyKernel.java:808) ~[jruby.jar:?]
	at org.jruby.RubyKernel.exit(org/jruby/RubyKernel.java:767) ~[jruby.jar:?]
	at C_3a_.LIMSAudit.Logstash.lib.bootstrap.environment.<main>(C:\LIMSAudit\Logstash\lib\bootstrap\environment.rb:90) ~[?:?]
```

Let me know if you need further assistance!

**Comment by kaisecheng** [comment] 2024-03-21 13:11
@Micheal-Madhan sorry I didn't make it clear. Can you provide the log from logstash start to end?
It is weird to see undefined method \`serverless?'. The correct method name should be `serverless?`, not sure how it ends up with a prefix \` in the log. 

Without the whole piece of log, I guess you are connecting to Elasitcsearch version 8. The index template has changed the format. [Here](https://github.com/logstash-plugins/logstash-output-elasticsearch/tree/main/lib/logstash/outputs/elasticsearch/templates/ecs-disabled) is a sample template for different versions. For [v8](https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/main/lib/logstash/outputs/elasticsearch/templates/ecs-disabled/elasticsearch-8x.json#L4-L5), the `settings` field is wrapped in `mappings`. Elasticsearch docs has an [example](https://www.elastic.co/guide/en/elasticsearch/reference/current/index-templates.html#create-index-templates)

**Comment by Micheal-Madhan** [comment] 2024-03-21 13:44
[logstash-plain.log](https://github.com/elastic/logstash/files/14696034/logstash-plain.log)

**Comment by kaisecheng** [comment] 2024-03-21 14:39
Thanks for the log. Confirmed that the template error is due to incompatible format as I mentioned in the last comment.

For the undefined method, I am wondering if something goes wrong in the upgrade, so the file is incomplete. Can you diff your file `C:/LIMSAudit/Logstash/vendor/bundle/jruby/3.1.0/gems/logstash-output-elasticsearch-11.22.2-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb` against [source code in Github](https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/v11.22.2/lib/logstash/outputs/elasticsearch/http_client/pool.rb). It should has [serverless?](https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/v11.22.2/lib/logstash/outputs/elasticsearch/http_client/pool.rb#L505C9-L507) defined

**Comment by Micheal-Madhan** [comment] 2024-03-22 04:22
@kaisecheng Thank you for the quick response and assistance. It's working now, thanks for your help!

**Comment by babudurairaji** [comment] 2024-03-22 07:49
Hi @kaisecheng ,

I appreciate your help in resolving this issue quickly. it saved our time.

**Comment by kaisecheng** [comment] 2024-03-22 10:13
It is a problem in the user's environment, hence closes it.

**Closed by kaisecheng** 2024-03-22 10:13 UTC
Labels: invalid

**Comment by babudurairaji** [comment] 2024-05-08 14:07
Hi Kaisecheng,

Could you clarify the following items for me? Could you please help me with this? 

- We have been using Elasticsearch (ES), Filebeat, Logstash, and Kibana for backup and restore purposes.
- All components will run exclusively on-premises. Since our client environment restricts the use of cloud services, everything must run on-premises.
- The Elasticsearch (ES) setup is in non-cluster mode, storing data on a single Windows server.
- The data is expected to grow from 1 GB to more than 1 TB. How should disk storage on a single server be managed to accommodate this growth?
- What is the best approach to implement data storage transitioning from hot to frozen mode? The frozen data storage might be on another Windows server. How can hot and frozen data storage be effectively implemented in an on-premises environment?
- How can data be retrieved from the frozen data storage in case it is not available in the hot storage?
- Can searchable snapshots be implemented without Kibana?



We are seeking technical expert advice to implement the ELK stack in our environment. Could you please help me with this.

Regards,
Babu
