### ISSUE TITLE
logstash.sysv: restart and autorun configtest is error when condition of JMX enabled.

### ISSUE THREAD

**Issue by nxhack** [elastic/logstash#4666] opened 2016-02-10 05:50 UTC
Ubuntu 12.04.5 LTS
logstash                                   1:2.2.0-1
openjdk-7-jre                              7u95-2.6.4-0ubuntu0.12.04.1

https://github.com/elastic/logstash/blob/master/pkg/logstash.sysv#L180

````
# /etc/init.d/logstash restart
Configuration error. Not restarting. Re-run with configtest parameter for details
# /etc/init.d/logstash configtest
Error: Exception thrown by the agent : java.rmi.server.ExportException: Port already in use: 5401; nested exception is: 
	java.net.BindException: Address already in use
```
I am using port 5401 JMX in my settings.
/etc/default/logstash
```
LS_JAVA_OPTS="-Djava.net.preferIPv4Stack=true \
-Dcom.sun.management.jmxremote \
-Dcom.sun.management.jmxremote.port=5401 \
```

**Comment by ppf2** [comment] 2016-02-24 21:13
+1 and reproducible using LS 2.2.2 with the simplest configuration.  Once JMX is added to LS_JAVA_OPTS, it will not restart properly.  See video repro [here](https://drive.google.com/a/elastic.co/file/d/0B1rxJ0dAZbQvMjBLZE1nd1dNQTQ/view?usp=sharing).

**Comment by ppf2** [comment] 2016-02-24 21:25
Duplicate of https://github.com/elastic/logstash/issues/4319.

**Closed by ppf2** 2016-02-24 21:25 UTC
Labels: bug
