### ISSUE TITLE
syslog msgs for stacktracelines are loosing info about program

### ISSUE THREAD

**Issue by ghost** [elastic/logstash#3783] opened 2015-08-24 14:30 UTC
last week i upgrade logstash on our loghost from 1.4.2 to 1.5.4 and we are now seeing #011<something> files on our loghost. The something is the 1st word from the msg. 

It looks like the problem is with the stacktraceexception lines where the 'program' field isn't added. and instead it uses the 1st word from the msg. Weird thing is that 1.4.2 doesn't have a problem with it.
Is there something changed in 1.5 that can cause this? and how to circumvent this??

no other software then logstash on the loghost was updated.

{"message":"<171>Aug 24 15:54:00 ad005 #011java.lang.RuntimeException:  There was an error in ProcessTask","@version":"1","@timestamp":"2015-08-24T13:54:00.091Z","host":"111.11.11.5"}
{"message":"<171>Aug 24 15:54:00 ad005 #011at:  eu.comparegroup.services.stats.tasks.ProcessTask.run(ProcessTask.java:74)","@version":"1","@timestamp":"2015-08-24T13:54:00.092Z","host":"111.11.11.5"}
{"message":"<171>Aug 24 15:54:00 ad005 #011at:  java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)","@version":"1","@timestamp":"2015-08-24T13:54:00.094Z","host":"111.11.11.5"}
{"

**Comment by suyograo** [comment] 2015-08-26 02:55
@kveerman I don't understand the question. Can you provide a sample log line and your config? Are you trying to parse multilines?

**Comment by kveerman** [comment] 2015-08-26 07:59
the stacktraces are from our java applications

and they end up like these on the filesystem. The #011 isn't a big issue, thats just syslog encode special chars 
Aug 23 04:04 #011at.log-20150823.bz2
Aug 23 04:04 #011Caused.log-20150823.bz2
Aug 23 04:04 #011eu.comparegroup.services.volatileproducts.exception.RepositoryException.log-20150823.bz2
Aug 23 04:04 #011java.lang.IllegalArgumentException.log-20150823.bz2
Aug 23 04:04 #011java.lang.RuntimeException.log-20150823.bz2
Aug 23 04:04 #011java.sql.SQLException.log-20150823.bz2
Aug 23 04:04 #011org.elasticsearch.transport.ReceiveTimeoutTransportException.log-20150823.bz2
Aug 23 04:04 #011org.hibernate.exception.GenericJDBCException.log-20150823.bz2
Aug 23 04:04 #011org.quartz.SchedulerException.log-20150823.bz2

logstash conf

input {
  syslog {
    type => syslog
    port => 5142
  }

}
filter {
  if [type] == 'syslog'{
    syslog_pri{}
    mutate {
      split => ["logsource", "."]
      add_field => { "short_host" => "%{logsource[0]}"}
      ## WARNING ### Do NOT, repeat NOT remove the enter in below gsub replacement. that is THE way to add a newline.
      gsub => [ "message","#012","
"]
    }
  }
}

output {
  if [type] == 'syslog' and [facility_label] == 'local4' {
    file {
      path => "/export/logs/%{short_host}/services/%{+YYYY-MM-dd}/%{program}.access.log"
      message_format => "%{message}"
      flush_interval => "0"
    }
  }
  if [type] == 'syslog' and [facility_label] == 'local5' {
    file {
      path => "/export/logs/%{short_host}/services/%{+YYYY-MM-dd}/%{program}.log"
      message_format => "%{message}"
      flush_interval => "0"
    }
  }
 
  #stdout { codec => rubydebug }
}

**Comment by kveerman** [comment] 2015-08-26 08:05
so to see what the problem is i changed the conf to a simple tcp input, no filter and a fileoutput. which is when i noticed that the stacktrace lines are individual lines without a program identifier.

**Comment by talevy** [comment] 2017-02-17 17:21
Closing this issue since it has been open for a long time and we haven't received the details to debug it further. Please reopen a new issue if you still run into issues

**Closed by talevy** 2017-02-17 17:21 UTC
Labels: needs details
