### ISSUE TITLE
feature/metrics is not working with latest commits

### ISSUE THREAD

**Issue by suyograo** [elastic/logstash#4679] opened 2016-02-12 07:38 UTC
```
suyog@machine:~/ws/elastic/logstash (feature/metrics)$ bin/logstash -e 'input { stdin {} } output { stdout {} }'
Settings: Default pipeline workers: 8
Logstash startup completed
{:debug=>nil, :http_host=>nil, :http_port=>nil}
No application configured, nothing to run {:level=>:error}
```

Environment:
```
suyog@machine:~/ws/elastic/logstash (feature/metrics)$ ruby -v
jruby 1.7.19 (1.9.3p551) 2015-01-29 20786bd on Java HotSpot(TM) 64-Bit Server VM 1.8.0_65-b17 +jit [darwin-x86_64]
suyog@machine:~/ws/elastic/logstash (feature/metrics)$ java -version
java version "1.8.0_65"
Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.65-b01, mixed mode)
```

Cleaned up `build/ vendor/ .bundle` and tried again. Same result

With `--debug`

```
Settings: Default pipeline workers: 8
Starting pipeline {:id=>"main", :pipeline_workers=>8, :batch_size=>125, :batch_delay=>5, :max_inflight=>1000, :level=>:info, :file=>"logstash/pipeline.rb", :line=>"222", :method=>"start_workers"}
Pipeline started {:level=>:info, :file=>"logstash/pipeline.rb", :line=>"170", :method=>"run"}
Logstash startup completed
{:debug=>true, :http_host=>nil, :http_port=>nil}
=== puma start: 2016-02-11 23:38:06 -0800 === {:level=>:debug, :file=>"logstash/webserver.rb", :line=>"47", :method=>"log"}
Puma starting in single mode... {:level=>:debug, :file=>"logstash/webserver.rb", :line=>"47", :method=>"log"}
* Version 2.16.0 (jruby 1.9.3), codename: Midwinter Nights Trance {:level=>:debug, :file=>"logstash/webserver.rb", :line=>"47", :method=>"log"}
* Min threads: 0, max threads: 16 {:level=>:debug, :file=>"logstash/webserver.rb", :line=>"47", :method=>"log"}
* Environment: development {:level=>:debug, :file=>"logstash/webserver.rb", :line=>"47", :method=>"log"}
No application configured, nothing to run {:level=>:error, :file=>"logstash/webserver.rb", :line=>"51", :method=>"error"}
```

**Comment by purbon** [comment] 2016-02-12 09:08
investigating....

**Comment by purbon** [comment] 2016-02-12 09:29
Did a test again and for now, not able to reproduce ... the only reason I could think puma might be giving this error message:

`No application configured, nothing to run {:level=>:error, :file=>"logstash/webserver.rb", :line=>"51", :method=>"error"}`

is when the `logstash/webserver.rb`,  line 23 in the cli options is not able to find the _init.ru_ file. This test has been made with the dev env, will also test now with the packaged artifacts (.tar.gz).

here is my env:

```
skywalker% java -version
java version "1.8.0_40-ea"
Java(TM) SE Runtime Environment (build 1.8.0_40-ea-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.40-b18, mixed mode)
skywalker% ruby --version
jruby 1.7.20 (1.9.3p551) 2015-05-04 3086e6a on Java HotSpot(TM) 64-Bit Server VM 1.8.0_40-ea-b15 +jit [darwin-x86_64]
```

**Comment by jsvd** [comment] 2016-02-12 10:54
worked well for me, couldn't reproduce it

**Comment by ph** [comment] 2016-02-12 13:54
Oh my! Never see that one before.

**Comment by purbon** [comment] 2016-02-12 13:55
@ph please test, not @guy, @jsvd or me has been able to reproduce. might be some strange thing into @suyograo env, who knows :-/

**Comment by ph** [comment] 2016-02-12 14:08
I tested it with a fresh checkout.
```
~/e/logstash git:feature/metrics ❯❯❯ java -version                        ⏎ ✱ ◼
java version "1.8.0_20"
Java(TM) SE Runtime Environment (build 1.8.0_20-b26)
Java HotSpot(TM) 64-Bit Server VM (build 25.20-b23, mixed mode)
```

```
{:debug=>nil, :http_host=>nil, :http_port=>nil}
No application configured, nothing to run {:level=>:error}
```

This is weird, :http_host and :http_port nil? How can that be possible the settings are coming from the runner?

**Comment by ph** [comment] 2016-02-12 14:10
I though we have removed the debugging `puts`  in the webserver?

@suyograo what is the sha1 of your branch?

```
git log -1 --format="%H"
```

**Comment by purbon** [comment] 2016-02-12 14:13
@ph removed, https://github.com/elastic/logstash/commit/fa51c506c41ace97a3a23ed24feeb36bde29fd4b

**Comment by suyograo** [comment] 2016-02-12 15:36
Here is my lock file https://gist.github.com/suyograo/dd38576b7ca8a6d34bf5

**Comment by suyograo** [comment] 2016-02-12 15:37
@ph 48e37470c58233f1a08baf50774c2afd086cee85

**Comment by ph** [comment] 2016-02-12 15:55
`init.ru` is not included in the gem

because of this line https://github.com/elastic/logstash/blob/master/logstash-core/logstash-core.gemspec#L14

**Comment by ph** [comment] 2016-02-12 15:55
imho We can use .rb instead of .ru, I mean its actually a ruby file.

**Comment by purbon** [comment] 2016-02-12 15:56
@ph not sure I like to change the naming, but this will fix it out of the box, without much changes... :-P

**Comment by purbon** [comment] 2016-02-12 15:56
and end of the day, rack does not care about naming.

**Comment by purbon** [comment] 2016-02-12 16:23
As discovered by hard, it should be endup in `.ru`, otherwise rack and sinatra are not happy each other. Will open an issue to investigate improved orgs for the app in next iteration.

**Comment by ph** [comment] 2016-02-12 18:10
Fixed in the metrics branch

**Closed by ph** 2016-02-12 18:10 UTC
Labels: blocker, bug, metrics
