### ISSUE TITLE
List of broken plugins for 2.0

### ISSUE THREAD

**Issue by ph** [elastic/logstash#4010] opened 2015-10-09 18:39 UTC
I ran into a few issue for my last mass publish done on October 8
This is the list of the plugins that were not correctly published.

plugin | why it didn't work?
------------ | -------------
logstash-filter-aggregate | dont have the permission to publish?
logstash-filter-alter | test green now -> http://build-eu-00.elastic.co/view/LS%20Plugins/view/LS%20FIlters/job/logstash-plugin-filter-alter-unit/
logstash-filter-environment | https://github.com/logstash-plugins/logstash-filter-environment/pull/6
logstash-filter-metrics | https://github.com/logstash-plugins/logstash-filter-metrics/issues/21 and  https://github.com/logstash-plugins/logstash-filter-metrics/issues/19
logstash-filter-yaml | EMPTY REPO
logstash-input-dynamodb | EMPTY REPO
logstash-input-heroku  | https://github.com/logstash-plugins/logstash-input-heroku/issues/8
logstash-input-perfmon | EMPTY REPO
logstash-output-logentries | EMPTY REPO?
logstash-output-neo4j | Can't run the test https://github.com/logstash-plugins/logstash-output-neo4j/issues/3
logstash-output-newrelic | EMPTY REPO!
logstash-input-rackspace | https://github.com/logstash-plugins/logstash-input-rackspace/issues/2
logstash-output-slack | https://github.com/logstash-plugins/logstash-output-rackspace/issues/3
logstash-output-solr_http  | republish worked ? Guess a rubygems hiccups?

**Comment by purbon** [comment] 2015-10-12 11:58
@ph 

* empty repos have nothing we could do much about, probably just skip them until they have all the content necessary.
* about logstash-filter-aggregate, I think is as easy as talking to @fbaligand about adding the elastic with rights to publish the plugin.

**Comment by fbaligand** [comment] 2015-10-12 12:35
@ph @purbon 
When you say "dont have the permission to publish?", you speak about publishing to rubygems.org ?

**Comment by purbon** [comment] 2015-10-12 12:39
@fbaligand yes, we do mass publishing from time to time, some of them to fix common documentation issues. In the case of your plugin, it's lock to your user, as it always been released by you. Lets discuss about it offline if you want.

**Comment by fbaligand** [comment] 2015-10-12 13:05
@ph @purbon 
OK, the elastic mail is dev_ops@elastic.co, right ?
I will add it tonight as owner of the rubygems project.

**Comment by purbon** [comment] 2015-10-12 14:42
I check jenkins and found this plugins being this days broken:

Inputs 

* http://build-eu-00.elastic.co/view/LS%20Plugins/view/LS%20Inputs/job/logstash-plugin-input-unix-unit/
* http://build-eu-00.elastic.co/view/LS%20Plugins/view/LS%20Inputs/job/logstash-plugin-input-snmptrap-unit/

Filters

* http://build-eu-00.elastic.co/view/LS%20Plugins/view/LS%20FIlters/job/logstash-plugin-filter-environment-unit/ (fix when https://github.com/logstash-plugins/logstash-filter-environment/pull/6 is merged)

Outputs

* http://build-eu-00.elastic.co/view/LS%20Plugins/view/LS%20Outputs/job/logstash-plugin-output-statsd-unit/
* http://build-eu-00.elastic.co/view/LS%20Plugins/view/LS%20Outputs/job/logstash-plugin-output-gelf-unit/ (looks like an specific JDK8 issue)

plugins listed but without a comment is because the issue looks more like a test implementation issue because of doing test with multiple JDK in jenkins, if there is a probably cause of the issue is noted together with the link. All others are green or like rackspace pending to be added in jenkins.

**Comment by fbaligand** [comment] 2015-10-12 20:23
Hi,

I just have added elastic to logstash-filter-aggregate owners !

Tell me if it fixes logstash build ;)

Fabien

2015-10-12 16:42 GMT+02:00 Pere Urbón <notifications@github.com>:

**Closed** 2016-01-14 00:40 UTC
Labels: bug, shutdown semantics
