### ISSUE TITLE
Accessing Metrics Endpoint during Startup Returns HTTP Status 500

### ISSUE THREAD

**Issue by lbesuchet** [elastic/logstash#12919] opened 2021-05-21 06:57 UTC
same as issue #8004, happening again since v12.0

**Comment by multani** [comment] 2021-06-03 08:04
We are seeing an issue similar with Logstash 7.12.1, running from within Docker.

This is the output (a bit redacted) from when this starts. After a while, something gets unstuck and the calls are passing again:

```
{
  "level": "INFO",
  "logEvent": {
    "message": "Log4j configuration path used is: /local/etc/logstash/log4j2.properties"
  },
  "loggerName": "logstash.runner",
  "thread": "main",
  "timeMillis": 1622706057360
}
{
  "level": "INFO",
  "logEvent": {
    "jruby.version": "jruby 9.2.13.0 (2.5.7) 2020-08-03 9a89c94bcc OpenJDK 64-Bit Server VM 11.0.10+9 on 11.0.10+9 +indy +jit [linux-x86_64]",
    "logstash.version": "7.12.1",
    "message": "Starting Logstash"
  },
  "loggerName": "logstash.runner",
  "thread": "main",
  "timeMillis": 1622706057413
}
{
  "level": "WARN",
  "logEvent": {
    "message": "Ignoring the 'pipelines.yml' file because modules or command line options are specified"
  },
  "loggerName": "logstash.config.source.multilocal",
  "thread": "LogStash::Runner",
  "timeMillis": 1622706057814
}
{
  "level": "INFO",
  "logEvent": {
    "message": "Successfully started Logstash API endpoint",
    "port": 9600
  },
  "loggerName": "logstash.agent",
  "thread": "Api Webserver",
  "timeMillis": 1622706058649
}
{
  "level": "ERROR",
  "logEvent": {
    "backtrace": [
      "/usr/share/logstash/logstash-core/lib/logstash/instrument/metric_store.rb:241:in `block in get_recursively'",
      "org/jruby/RubyArray.java:1809:in `each'",
      "/usr/share/logstash/logstash-core/lib/logstash/instrument/metric_store.rb:240:in `get_recursively'",
      "/usr/share/logstash/logstash-core/lib/logstash/instrument/metric_store.rb:251:in `block in get_recursively'",
      "org/jruby/RubyArray.java:1809:in `each'",
      "/usr/share/logstash/logstash-core/lib/logstash/instrument/metric_store.rb:240:in `get_recursively'",
      "/usr/share/logstash/logstash-core/lib/logstash/instrument/metric_store.rb:111:in `block in get'",
      "org/jruby/ext/thread/Mutex.java:164:in `synchronize'",
      "/usr/share/logstash/logstash-core/lib/logstash/instrument/metric_store.rb:110:in `get'",
      "/usr/share/logstash/logstash-core/lib/logstash/instrument/metric_store.rb:124:in `get_shallow'",
      "/usr/share/logstash/logstash-core/lib/logstash/instrument/metric_store.rb:173:in `block in extract_metrics'",
      "org/jruby/RubyArray.java:1809:in `each'",
      "org/jruby/RubyEnumerable.java:1126:in `inject'",
      "/usr/share/logstash/logstash-core/lib/logstash/instrument/metric_store.rb:149:in `extract_metrics'",
      "/usr/share/logstash/logstash-core/lib/logstash/api/service.rb:45:in `extract_metrics'",
      "/usr/share/logstash/logstash-core/lib/logstash/api/commands/base.rb:37:in `extract_metrics'",
      "/usr/share/logstash/logstash-core/lib/logstash/api/commands/stats.rb:73:in `events'",
      "/usr/share/logstash/logstash-core/lib/logstash/api/modules/node_stats.rb:57:in `events_payload'",
      "/usr/share/logstash/logstash-core/lib/logstash/api/modules/node_stats.rb:37:in `block in GET /?:filter?'",
      "org/jruby/RubyMethod.java:115:in `call'",
      "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1675:in `block in compile!'",
      "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1013:in `block in route!'",
      "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1032:in `route_eval'",
      "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1013:in `block in route!'",
      "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1061:in `block in process_route'",
      "org/jruby/RubyKernel.java:1189:in `catch'",
      "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1059:in `process_route'",
      "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1011:in `block in route!'",
      "org/jruby/RubyArray.java:1809:in `each'",
      "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1008:in `route!'",
      "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1129:in `block in dispatch!'",
      "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `block in invoke'",
      "org/jruby/RubyKernel.java:1189:in `catch'",
      "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `invoke'",
      "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1124:in `dispatch!'",
      "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:939:in `block in call!'",
      "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `block in invoke'",
      "org/jruby/RubyKernel.java:1189:in `catch'",
      "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `invoke'",
      "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:939:in `call!'",
      "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:929:in `call'",
      "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/rack-protection-2.1.0/lib/rack/protection/xss_header.rb:18:in `call'",
      "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/rack-protection-2.1.0/lib/rack/protection/path_traversal.rb:16:in `call'",
      "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/rack-protection-2.1.0/lib/rack/protection/json_csrf.rb:26:in `call'",
      "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/rack-protection-2.1.0/lib/rack/protection/base.rb:50:in `call'",
      "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/rack-protection-2.1.0/lib/rack/protection/base.rb:50:in `call'",
      "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/rack-protection-2.1.0/lib/rack/protection/frame_options.rb:31:in `call'",
      "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/rack-2.2.3/lib/rack/null_logger.rb:11:in `call'",
      "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'",
      "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:216:in `call'",
      "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1991:in `call'",
      "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/rack-2.2.3/lib/rack/urlmap.rb:74:in `block in call'",
      "org/jruby/RubyArray.java:1809:in `each'",
      "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/rack-2.2.3/lib/rack/urlmap.rb:58:in `call'",
      "/usr/share/logstash/logstash-core/lib/logstash/api/rack_app.rb:74:in `call'",
      "/usr/share/logstash/logstash-core/lib/logstash/api/rack_app.rb:48:in `call'",
      "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/rack-2.2.3/lib/rack/builder.rb:244:in `call'",
      "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/puma-4.3.7-java/lib/puma/server.rb:713:in `handle_request'",
      "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/puma-4.3.7-java/lib/puma/server.rb:472:in `process_client'",
      "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/puma-4.3.7-java/lib/puma/server.rb:328:in `block in run'",
      "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/puma-4.3.7-java/lib/puma/thread_pool.rb:134:in `block in spawn_thread'"
    ],
    "class": "LogStash::Instrument::MetricStore::MetricNotFound",
    "error": "Unexpected Internal Error",
    "http_accept": null,
    "http_version": "HTTP/1.1",
    "message": "For path: events. Map keys: [:reloads]",
    "path_info": "/_node/stats",
    "query_string": "",
    "request_method": "GET",
    "status": 500
  },
  "loggerName": "logstash.agent",
  "thread": "Ruby-0-Thread-8@puma threadpool 001: :1",
  "timeMillis": 1622706059918
}
{
  "level": "ERROR",
  "logEvent": {
    "http_accept": null,
    "http_version": "HTTP/1.1",
    "message": "API HTTP Request",
    "path_info": "/_node/stats",
    "query_string": "",
    "request_method": "GET",
    "status": 500
  },
  "loggerName": "logstash.agent",
  "thread": "Ruby-0-Thread-8@puma threadpool 001: :1",
  "timeMillis": 1622706059993
}
{
  "level": "INFO",
  "logEvent": {
    "message": "Reflections took 56 ms to scan 1 urls, producing 23 keys and 47 values "
  },
  "loggerName": "org.reflections.Reflections",
  "thread": "Converge PipelineAction::Create<main>",
  "timeMillis": 1622706062864
}
{
  "level": "ERROR",
  "logEvent": {
    "backtrace": [
      "/usr/share/logstash/logstash-core/lib/logstash/instrument/metric_store.rb:241:in `block in get_recursively'",
      "org/jruby/RubyArray.java:1809:in `each'",
      "/usr/share/logstash/logstash-core/lib/logstash/instrument/metric_store.rb:240:in `get_recursively'",
      "/usr/share/logstash/logstash-core/lib/logstash/instrument/metric_store.rb:251:in `block in get_recursively'",
      "org/jruby/RubyArray.java:1809:in `each'",
      "/usr/share/logstash/logstash-core/lib/logstash/instrument/metric_store.rb:240:in `get_recursively'",
      "/usr/share/logstash/logstash-core/lib/logstash/instrument/metric_store.rb:111:in `block in get'",
      "org/jruby/ext/thread/Mutex.java:164:in `synchronize'",
      "/usr/share/logstash/logstash-core/lib/logstash/instrument/metric_store.rb:110:in `get'",
      "/usr/share/logstash/logstash-core/lib/logstash/instrument/metric_store.rb:124:in `get_shallow'",
      "/usr/share/logstash/logstash-core/lib/logstash/instrument/metric_store.rb:173:in `block in extract_metrics'",
      "org/jruby/RubyArray.java:1809:in `each'",
      "org/jruby/RubyEnumerable.java:1126:in `inject'",
      "/usr/share/logstash/logstash-core/lib/logstash/instrument/metric_store.rb:149:in `extract_metrics'",
      "/usr/share/logstash/logstash-core/lib/logstash/api/service.rb:45:in `extract_metrics'",
      "/usr/share/logstash/logstash-core/lib/logstash/api/commands/base.rb:37:in `extract_metrics'",
      "/usr/share/logstash/logstash-core/lib/logstash/api/commands/stats.rb:73:in `events'",
      "/usr/share/logstash/logstash-core/lib/logstash/api/modules/node_stats.rb:57:in `events_payload'",
      "/usr/share/logstash/logstash-core/lib/logstash/api/modules/node_stats.rb:37:in `block in NodeStats'",
      "org/jruby/RubyMethod.java:115:in `call'",
      "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1675:in `block in compile!'",
      "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1013:in `block in route!'",
      "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1032:in `route_eval'",
      "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1013:in `block in route!'",
      "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1061:in `block in process_route'",
      "org/jruby/RubyKernel.java:1189:in `catch'",
      "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1059:in `process_route'",
      "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1011:in `block in route!'",
      "org/jruby/RubyArray.java:1809:in `each'",
      "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1008:in `route!'",
      "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1129:in `block in dispatch!'",
      "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `block in invoke'",
      "org/jruby/RubyKernel.java:1189:in `catch'",
      "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `invoke'",
      "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1124:in `dispatch!'",
      "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:939:in `block in call!'",
      "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `block in invoke'",
      "org/jruby/RubyKernel.java:1189:in `catch'",
      "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `invoke'",
      "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:939:in `call!'",
      "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:929:in `call'",
      "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/rack-protection-2.1.0/lib/rack/protection/xss_header.rb:18:in `call'",
      "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/rack-protection-2.1.0/lib/rack/protection/path_traversal.rb:16:in `call'",
      "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/rack-protection-2.1.0/lib/rack/protection/json_csrf.rb:26:in `call'",
      "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/rack-protection-2.1.0/lib/rack/protection/base.rb:50:in `call'",
      "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/rack-protection-2.1.0/lib/rack/protection/base.rb:50:in `call'",
      "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/rack-protection-2.1.0/lib/rack/protection/frame_options.rb:31:in `call'",
      "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/rack-2.2.3/lib/rack/null_logger.rb:11:in `call'",
      "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'",
      "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:216:in `call'",
      "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1991:in `call'",
      "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/rack-2.2.3/lib/rack/urlmap.rb:74:in `block in call'",
      "org/jruby/RubyArray.java:1809:in `each'",
      "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/rack-2.2.3/lib/rack/urlmap.rb:58:in `call'",
      "/usr/share/logstash/logstash-core/lib/logstash/api/rack_app.rb:74:in `call'",
      "/usr/share/logstash/logstash-core/lib/logstash/api/rack_app.rb:48:in `call'",
      "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/rack-2.2.3/lib/rack/builder.rb:244:in `call'",
      "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/puma-4.3.7-java/lib/puma/server.rb:713:in `handle_request'",
      "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/puma-4.3.7-java/lib/puma/server.rb:472:in `process_client'",
      "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/puma-4.3.7-java/lib/puma/server.rb:328:in `block in run'",
      "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/puma-4.3.7-java/lib/puma/thread_pool.rb:134:in `block in spawn_thread'"
    ],
    "class": "LogStash::Instrument::MetricStore::MetricNotFound",
    "error": "Unexpected Internal Error",
    "http_accept": null,
    "http_version": "HTTP/1.1",
    "message": "For path: events. Map keys: [:reloads, :pipelines]",
    "path_info": "/_node/stats",
    "query_string": "",
    "request_method": "GET",
    "status": 500
  },
  "loggerName": "logstash.agent",
  "thread": "Ruby-0-Thread-8@puma threadpool 001: :1",
  "timeMillis": 1622706069923
}
{
  "level": "ERROR",
  "logEvent": {
    "http_accept": null,
    "http_version": "HTTP/1.1",
    "message": "API HTTP Request",
    "path_info": "/_node/stats",
    "query_string": "",
    "request_method": "GET",
    "status": 500
  },
  "loggerName": "logstash.agent",
  "thread": "Ruby-0-Thread-8@puma threadpool 001: :1",
  "timeMillis": 1622706069927
}

[... about 10 more errors, same as above]

{
  "level": "INFO",
  "logEvent": {
    "changes": {
      "added": [
        {
          "metaClass": {
            "metaClass": {
              "metaClass": {
                "changes": "{:removed=>[], :added=>[https://es-url-redacted.es.amazonaws.com:443/]}"
              }
            }
          }
        }
      ]
    },
    "message": "Elasticsearch pool URLs updated"
  },
  "loggerName": "logstash.outputs.amazonelasticsearch",
  "thread": "[main]-pipeline-manager",
  "timeMillis": 1622706187921
}
{
  "level": "INFO",
  "logEvent": {
    "healthcheck_url": {
      "metaClass": {
        "metaClass": {
          "metaClass": {
            "healthcheck_url": "https://es-url-redacted.es.amazonaws.com:443/",
            "path": "/"
          }
        }
      }
    },
    "message": "Running health check to see if an Elasticsearch connection is working"
  },
  "loggerName": "logstash.outputs.amazonelasticsearch",
  "thread": "[main]-pipeline-manager",
  "timeMillis": 1622706188085
}
{
  "level": "WARN",
  "logEvent": {
    "message": "Restored connection to ES instance",
    "url": "https://es-url-redacted.es.amazonaws.com:443/"
  },
  "loggerName": "logstash.outputs.amazonelasticsearch",
  "thread": "[main]-pipeline-manager",
  "timeMillis": 1622706188794
}
{
  "level": "INFO",
  "logEvent": {
    "es_version": 7,
    "message": "ES Output version determined"
  },
  "loggerName": "logstash.outputs.amazonelasticsearch",
  "thread": "[main]-pipeline-manager",
  "timeMillis": 1622706188843
}
{
  "level": "WARN",
  "logEvent": {
    "es_version": 7,
    "message": "Detected a 6.x and above cluster: the `type` event field won't be used to determine the document _type"
  },
  "loggerName": "logstash.outputs.amazonelasticsearch",
  "thread": "[main]-pipeline-manager",
  "timeMillis": 1622706188848
}
{
  "level": "INFO",
  "logEvent": {
    "class": "LogStash::Outputs::AmazonElasticSearch",
    "hosts": [
      "//es-url-redacted.es.amazonaws.com"
    ],
    "message": "New Elasticsearch output"
  },
  "loggerName": "logstash.outputs.amazonelasticsearch",
  "thread": "[main]-pipeline-manager",
  "timeMillis": 1622706188863
}
{
  "level": "INFO",
  "logEvent": {
    "message": "Using mapping template from",
    "path": "/local/etc/logstash/templates/logstash.json"
  },
  "loggerName": "logstash.outputs.amazonelasticsearch",
  "thread": "Ruby-0-Thread-14: :1",
  "timeMillis": 1622706188886
}
{
  "level": "INFO",
  "logEvent": {
    "manage_template": {
      "index_patterns": [
        "logstash-*"
      ],
      "mappings": {
        "dynamic_templates": [
          {
            "message_field": {
              "mapping": {
                "norms": false,
                "type": "text"
              },
              "match_mapping_type": "string",
              "path_match": "message"
            }
          },
          {
            "string_fields": {
              "mapping": {
                "fields": {
                  "keyword": {
                    "ignore_above": 256,
                    "type": "keyword"
                  }
                },
                "norms": false,
                "type": "text"
              },
              "match": "*",
              "match_mapping_type": "string"
            }
          }
        ],
        "properties": {
          "@timestamp": {
            "type": "date"
          },
          "@version": {
            "type": "keyword"
          },
          "duration": {
            "type": "long"
          },
          "geoip": {
            "dynamic": true,
            "properties": {
              "ip": {
                "type": "ip"
              },
              "latitude": {
                "type": "half_float"
              },
              "location": {
                "type": "geo_point"
              },
              "longitude": {
                "type": "half_float"
              }
            }
          }
        }
      },
      "settings": {
        "index.refresh_interval": "5s",
        "number_of_shards": 5
      },
      "version": 60001
    },
    "message": "Attempting to install template"
  },
  "loggerName": "logstash.outputs.amazonelasticsearch",
  "thread": "Ruby-0-Thread-14: :1",
  "timeMillis": 1622706188964
}
{
  "level": "INFO",
  "logEvent": {
    "message": "Installing amazon_es template to /_template/logstash"
  },
  "loggerName": "logstash.outputs.amazonelasticsearch",
  "thread": "Ruby-0-Thread-14: :1",
  "timeMillis": 1622706189070
}
{
  "level": "INFO",
  "logEvent": {
    "message": "Starting pipeline",
    "pipeline.batch.delay": 50,
    "pipeline.batch.size": 125,
    "pipeline.max_inflight": 2000,
    "pipeline.sources": [
      "/local/etc/logstash/conf.d/000-inputs.conf",
      "/local/etc/logstash/conf.d/020-filters.conf",
      "/local/etc/logstash/conf.d/1000-output-elasticsearch.conf",
      "/local/etc/logstash/conf.d/dead-letter.conf"
    ],
    "pipeline.workers": 16,
    "pipeline_id": "main",
    "thread": "#<Thread:0x31c695fb run>"
  },
  "loggerName": "logstash.javapipeline",
  "thread": "[main]-pipeline-manager",
  "timeMillis": 1622706189891
}
{
  "level": "INFO",
  "logEvent": {
    "message": "Pipeline Java execution initialization time",
    "seconds": 8.43
  },
  "loggerName": "logstash.javapipeline",
  "thread": "[main]-pipeline-manager",
  "timeMillis": 1622706198319
}
```

Attached is the plugins list.
[plugins.txt](https://github.com/elastic/logstash/files/6589973/plugins.txt)

**Comment by BBQigniter** [comment] 2021-07-22 06:09
strangely we see this error too only on one out of two test-logstash servers (centos 7, logstash installed via rpm) - version 7.13.4

**Comment by MakoWish** [comment] 2021-09-22 20:18
We are seeing this on Logstash 7.14.2.

**Comment by AlphaRaven** [comment] 2022-03-01 13:08
Upgraded just now and still seeing this issue on 7.17.1. So I guess my post #13313 is duplicate of this.

**Comment by andsel** [comment] 2022-03-24 10:32
The fix #13424 landed on versions `7.17.2` and `8.1.0` please could you retry with one of those, and report here?

**Comment by AhmadManzoor** [comment] 2022-04-01 12:44
still available in version 8.1

````{"status":500,"request_method":"GET","path_info":"/_node/stats/jvm","query_string":"","http_version":"HTTP/1.1","http_accept":"*/*","error":"Unexpected Internal Error","class":"LogStash::Instrument::MetricStore::MetricNotFound","message":"For path: events. Map keys: [:reloads]","backtrace":["/usr/share/logstash/logstash-core/lib/logstash/instrument/metric_store.rb:241:in `block in get_recursively'","org/jruby/RubyArray.java:1821:in `each'","/usr/share/logstash/logstash-core/lib/logstash/instrument/metric_store.rb:240:in `get_recursively'","/usr/share/logstash/logstash-core/lib/logstash/instrument/metric_store.rb:251:in `block in get_recursively'","org/jruby/RubyArray.java:1821:in `each'","/usr/share/logstash/logstash-core/lib/logstash/instrument/metric_store.rb:240:in `get_recursively'","/usr/share/logstash/logstash-core/lib/logstash/instrument/metric_store.rb:111:in `block in get'","org/jruby/ext/thread/Mutex.java:164:in `synchronize'","/usr/share/logstash/logstash-core/lib/logstash/instrument/metric_store.rb:110:in `get'","/usr/share/logstash/logstash-core/lib/logstash/instrument/metric_store.rb:124:in `get_shallow'","/usr/share/logstash/logstash-core/lib/logstash/instrument/metric_store.rb:173:in `block in extract_metrics'","org/jruby/RubyArray.java:1821:in `each'","org/jruby/RubyEnumerable.java:1126:in `inject'","/usr/share/logstash/logstash-core/lib/logstash/instrument/metric_store.rb:149:in `extract_metrics'","/usr/share/logstash/logstash-core/lib/logstash/api/service.rb:45:in `extract_metrics'","/usr/share/logstash/logstash-core/lib/logstash/api/commands/base.rb:37:in `extract_metrics'","/usr/share/logstash/logstash-core/lib/logstash/api/commands/stats.rb:73:in `events'","/usr/share/logstash/logstash-core/lib/logstash/api/modules/node_stats.rb:61:in `events_payload'","/usr/share/logstash/logstash-core/lib/logstash/api/modules/node_stats.rb:37:in `block in NodeStats'","org/jruby/RubyMethod.java:115:in `call'","/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1675:in `block in compile!'","/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1013:in `block in route!'","/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1032:in `route_eval'","/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1013:in `block in route!'","/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1061:in `block in process_route'","org/jruby/RubyKernel.java:1189:in `catch'","/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1059:in `process_route'","/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1011:in `block in route!'","org/jruby/RubyArray.java:1821:in `each'","/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1008:in `route!'","/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1129:in `block in dispatch!'","/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `block in invoke'","org/jruby/RubyKernel.java:1189:in `catch'","/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `invoke'","/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1124:in `dispatch!'","/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:939:in `block in call!'","/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `block in invoke'","org/jruby/RubyKernel.java:1189:in `catch'","/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `invoke'","/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:939:in `call!'","/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:929:in `call'","/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/rack-protection-2.1.0/lib/rack/protection/xss_header.rb:18:in `call'","/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/rack-protection-2.1.0/lib/rack/protection/path_traversal.rb:16:in `call'","/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/rack-protection-2.1.0/lib/rack/protection/json_csrf.rb:26:in `call'","/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/rack-protection-2.1.0/lib/rack/protection/base.rb:50:in `call'","/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/rack-protection-2.1.0/lib/rack/protection/base.rb:50:in `call'","/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/rack-protection-2.1.0/lib/rack/protection/frame_options.rb:31:in `call'","/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/rack-2.2.3/lib/rack/null_logger.rb:11:in `call'","/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'","/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:216:in `call'","/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1991:in `call'","/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/rack-2.2.3/lib/rack/urlmap.rb:74:in `block in call'","org/jruby/RubyArray.java:1821:in `each'","/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/rack-2.2.3/lib/rack/urlmap.rb:58:in `call'","/usr/share/logstash/logstash-core/lib/logstash/api/rack_app.rb:74:in `call'","/usr/share/logstash/logstash-core/lib/logstash/api/rack_app.rb:48:in `call'","/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/rack-2.2.3/lib/rack/builder.rb:244:in `call'","/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/puma-5.6.1-java/lib/puma/request.rb:77:in `block in handle_request'","/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/puma-5.6.1-java/lib/puma/thread_pool.rb:340:in `with_force_shutdown'","/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/puma-5.6.1-java/lib/puma/request.rb:76:in `handle_request'","/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/puma-5.6.1-java/lib/puma/server.rb:441:in `process_client'","/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/puma-5.6.1-java/lib/puma/thread_pool.rb:147:in `block in spawn_thread'"]}````

**Comment by MakoWish** [comment] 2022-04-01 15:24
Can confirm the error still exists on 8.1.2 as well.

**Comment by yaauie** [comment] 2022-04-01 16:15
It looks like my backport to 8.1 (https://github.com/elastic/logstash/pull/13844) missed the release train, which is totally my fault. The relevant bits are in place on the 8.2 branch and will be resolved in 8.2.0 😞

**Comment by andsel** [comment] 2022-04-04 07:23
I can confirm `8.2` branch doesn't present the problem so `8.2.0` fix it.

**Closed by andsel** 2022-04-04 07:23 UTC
Labels: bug

**Comment by AhmadManzoor** [comment] 2022-04-08 21:42
@andsel I am using logstash version 8.1 downloaded from here https://www.elastic.co/downloads/logstash. ca you please tell me what is the changelog I can update on my package. I tried to clone the repo and checkout to version 8.2 but I can't run it there due to java issues. 
```
ogstash/logstash-core/lib/jars: No such file or directory
ls: cannot access *.jar: No such file or directory
Using system java: /usr/bin/java
Error: Could not find or load main class org.logstash.launchers.JvmOptionsParser
Caused by: java.lang.ClassNotFoundException: org.logstash.launchers.JvmOptionsParser

```

**Comment by andsel** [comment] 2022-04-11 09:10
@AhmadManzoor which commit did you use?

I build locally from branch `8.2` commit a323af499262a09032289c92a8e6c41352bfca6b and not able to reproduce.

To build locally I checkout to branch `8.2` and built with:
```
./gradlew clean installDefaultGems
bin/logstash
```

with the curl 
```
curl http://localhost:9600/_node/stats
```
I got a 200 HTTP code with valid JSON response.

How can I reproduce your test?
