### ISSUE TITLE
Logstash HPA - During scaling in of logstash pods creates orphan pvc

### ISSUE THREAD

**Issue by carijit24** [elastic/logstash#12966] opened 2021-06-07 12:36 UTC
### **Describe the feature:**

**Problem Statement**
In our ecosystem we ship application logs from microservices hosts using Filebeat to logstash where persistent queues are enabled. Filebeat supports structured (e.g. JSON) and unstructured (e.g. log lines) log shipment. Logstash uses azure log analytics plugin to push the logs to azure.

We use HPA alongwith logstash statefulset in order to scale out OR scale in based on the defined matrices. The issue we're facing  when logstash scale out lets say from 2 pods to 5 pods, the associated pvc gets created due to dynamic provisioning used in logstash statefulset by **volumeClaimTemplates** and it becomes

```
Logstash POD                                   Associated PVC
logstash-0                                     data-logstash-0
logstash-1                                     data-logstash-1
logstash-2                                     data-logstash-2
logstash-3                                     data-logstash-3
logstash-4                                     data-logstash-4
```

It is working fine during scaling out of pods.

but problem occurred when HPA scale in the logstash pods from 5 to 2 then it becomes

```
Logstash POD                                   Associated PVC
logstash-0                                     data-logstash-0
logstash-1                                     data-logstash-1
                                               data-logstash-2
                                               data-logstash-3
                                               data-logstash-4
```

Now data-logstash-2, data-logstash-3 and data-logstash-4 becomes orphan PVC and it holds the logs to be processsed and none of the pod attached to it. These data associated with orphan PVC gets processed when next time scale out happens in logstash. This causes old logs coming up in Azure log analytics intermittently which makes life difficult for us.

**Probable Solution**

Something specific in logstash container to do graceful shutdown during scale down. When logstash pod receives termination signal during scale down, it should complete the task (should process the logs reside in the associated PVC with the pod ~~and deletes the PVC when it process the logs~~) before getting terminated. In that way we can void orphan PVC (holding the data to be processed) during scale in.

### **Describe a specific use case for the feature:**

Same as mentioned in the problem statement above

**Comment by ryan-dyer-sp** [comment] 2021-06-08 19:50
How is logstash supposed to delete a PVC?  

This sounds like a misconfiguration issue.  Why are you declaring a PVC if its not persistent?  Why not just use a memory backed emptydir volume?

**Comment by carijit24** [comment] 2021-06-09 10:33
Hey @ryan-dyer-sp thanks for pointing the glitch in the description. I've updated the description. As part of the solution what I'm looking for is logstash pods should finish up processing the data reside in associated pvc before getting terminated during scale down. 
It will help us to resolve the existing problem we have the older logs coming up in between due to orphan pvc holding the data to be processed when the next time scale up happens

**Comment by ryan-dyer-sp** [comment] 2021-06-09 12:34
I can understand your frustration, but this isnt something that elastic is likely to do.  This would be a fundamental change in their shutdown behavior.  Currently logstash attempts to safely finish any in flight events and then shutdown leaving anything in the persistent queue to be handled later.  What you're seeing is the expected behavior of how logstash works.  

We have the same fundamental pipeline as you (app logs > ES) with HPA.  However, we don't use logstash persistent queues.  We use a kafka cluster to act as the persistent queue.  So filebeat > kafka > logstash > ES.  Then you can scale logstash in/out all day long and it just picks up reading from the topic/queue when it comes back online.  You can even have all your logstash go offline for hours or days without worrying about filebeat backing up and running out of its persistent storage.

**Comment by andsel** [comment] 2021-06-09 15:32
Hi @carijit24 
listening to PODs I think you have a Kubernetes environment, and actually Logstash doesn't support Kubernetes. However speaking of Logstash process shutdown some help could be provided. When you have a persistent queue (aka PQ) and you want Logstash to process all the data in the PQ before shutdown is completed you can enable the configuration option [`queue.drain`](https://www.elastic.co/guide/en/logstash/current/persistent-queues.html#configuring-persistent-queues) in the `config/logstash.yml`. This option force Logstash process to consume completely the PQ before exiting.

**Comment by carijit24** [comment] 2021-06-09 16:18
Hi @andsel we're already using `queue.drain: true` but that doesn't solve this issue looks like. when HPA scale down happens, looks like the container runs inside the kubernetes POD gets terminated before processing the data resided in associated `persistent volume claim AKA pvc` which logstash persistent queue stores in `pvc`.

**Comment by andsel** [comment] 2021-06-10 06:40
@cargious can share some Logstash logs when the process is asked to shutdown? Which version of Logstash are you using?

**Comment by carijit24** [comment] 2021-06-10 09:07
Hi @andsel we're using logstash `appVersion: 7.1.1` at the moment. I will get the logs from our environment shortly

**Comment by andsel** [comment] 2021-06-10 09:20
`7.1.1` is pretty old and Logstash since that has improved a lot the pipeline management and the shutdown sequence, check https://www.elastic.co/guide/en/logstash/current/logstash-7-11-0.html. So I think that version is simply too old

**Comment by carijit24** [comment] 2021-06-10 13:25
@andsel what would be the latest stable version of logstash if I plan to upgrade our logstash version ? will the version `7.13.0` be good - https://www.elastic.co/guide/en/logstash/current/logstash-7-13-0.html ? Its better to upgrade to the latest version and then see if it solves the purpose.

I have one more query - does logstash support Amazon SQS as persistent queue. we're planning to move out of logstash persistent queues which internally use aws EFS and introduce a message broker instead.

**Comment by andsel** [comment] 2021-06-10 13:29
> what would be the latest stable version of logstash?

The latest, actually is `7.13.1`

>  does logstash support Amazon SQS as persistent queue?

you can pull data out of SQS  with logstash-input-sqs, but's not the same thing as a local persistent queue

**Comment by carijit24** [comment] 2021-06-17 15:47
@andsel I have tried upgrading our logstash to latest `7.13.2` but when the `pods`are coming up it is not able to recognize `azure log analytics` output plugin. something like this - `Couldn't find any output plugin named 'azure_loganalytics'`

the full stack race is as follows - 
```
Failed to execute action {:action=>LogStash::PipelineAction::Create/pipeline_id:main1, :exception=>"Java::JavaLang::IllegalStateException", :message=>"Unable to configure plugins: (PluginLoadingError) Couldn't find any output plugin named 'azure_loganalytics'. Are you sure this is correct? Trying to load the azure_loganalytics output plugin resulted in this error: Unable to load the requested plugin named azure_loganalytics of type output. The plugin is not installed.", :backtrace=>["org.logstash.config.ir.CompiledPipeline.<init>(CompiledPipeline.java:119)", "org.logstash.execution.JavaBasePipelineExt.initialize(JavaBasePipelineExt.java:86)", "org.logstash.execution.JavaBasePipelineExt$INVOKER$i$1$0$initialize.call(JavaBasePipelineExt$INVOKER$i$1$0$initialize.gen)", "org.jruby.internal.runtime.methods.JavaMethod$JavaMethodN.call(JavaMethod.java:837)", "org.jruby.ir.runtime.IRRuntimeHelpers.instanceSuper(IRRuntimeHelpers.java:1169)", "org.jruby.ir.instructions.InstanceSuperInstr.interpret(InstanceSuperInstr.java:84)", "org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:361)", "org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:72)", "org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:86)", "org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:73)", "org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:84)", "org.jruby.RubyClass.newInstance(RubyClass.java:939)", "org.jruby.RubyClass$INVOKER$i$newInstance.call(RubyClass$INVOKER$i$newInstance.gen)", "org.jruby.ir.targets.InvokeSite.invoke(InvokeSite.java:207)", "usr.share.logstash.logstash_minus_core.lib.logstash.pipeline_action.create.RUBY$method$execute$0(/usr/share/logstash/logstash-core/lib/logstash/pipeline_action/create.rb:52)", "usr.share.logstash.logstash_minus_core.lib.logstash.pipeline_action.create.RUBY$method$execute$0$__VARARGS__(/usr/share/logstash/logstash-core/lib/logstash/pipeline_action/create.rb)", "org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:80)", "org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:70)", "org.jruby.ir.targets.InvokeSite.invoke(InvokeSite.java:207)", "usr.share.logstash.logstash_minus_core.lib.logstash.agent.RUBY$block$converge_state$2(/usr/share/logstash/logstash-core/lib/logstash/agent.rb:389)", "org.jruby.runtime.CompiledIRBlockBody.callDirect(CompiledIRBlockBody.java:138)", "org.jruby.runtime.IRBlockBody.call(IRBlockBody.java:58)", "org.jruby.runtime.IRBlockBody.call(IRBlockBody.java:52)", "org.jruby.runtime.Block.call(Block.java:139)", "org.jruby.RubyProc.call(RubyProc.java:318)", "org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:105)", "java.base/java.lang.Thread.run(Thread.java:829)"]}
[2021-06-17T15:15:14,537][ERROR][logstash.agent ] Failed to execute action {:action=>LogStash::PipelineAction::Create/pipeline_id:main1, :exception=>"Java::JavaLang::IllegalStateException", :message=>"Unable to configure plugins: (PluginLoadingError) Couldn't find any output plugin named 'azure_loganalytics'. Are you sure this is correct? Trying to load the azure_loganalytics output plugin resulted in this error: Unable to load the requested plugin named azure_loganalytics of type output. The plugin is not installed.", :backtrace=>["org.logstash.config.ir.CompiledPipeline.<init>(CompiledPipeline.java:119)", "org.logstash.execution.JavaBasePipelineExt.initialize(JavaBasePipelineExt.java:86)", "org.logstash.execution.JavaBasePipelineExt$INVOKER$i$1$0$initialize.call(JavaBasePipelineExt$INVOKER$i$1$0$initialize.gen)", "org.jruby.internal.runtime.methods.JavaMethod$JavaMethodN.call(JavaMethod.java:837)", "org.jruby.ir.runtime.IRRuntimeHelpers.instanceSuper(IRRuntimeHelpers.java:1169)", "org.jruby.ir.instructions.InstanceSuperInstr.interpret(InstanceSuperInstr.java:84)", "org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:361)", "org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:72)", "org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:86)", "org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:73)", "org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:84)", "org.jruby.RubyClass.newInstance(RubyClass.java:939)", "org.jruby.RubyClass$INVOKER$i$newInstance.call(RubyClass$INVOKER$i$newInstance.gen)", "org.jruby.ir.targets.InvokeSite.invoke(InvokeSite.java:207)", "usr.share.logstash.logstash_minus_core.lib.logstash.pipeline_action.create.RUBY$method$execute$0(/usr/share/logstash/logstash-core/lib/logstash/pipeline_action/create.rb:52)", "usr.share.logstash.logstash_minus_core.lib.logstash.pipeline_action.create.RUBY$method$execute$0$__VARARGS__(/usr/share/logstash/logstash-core/lib/logstash/pipeline_action/create.rb)", "org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:80)", "org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:70)", "org.jruby.ir.targets.InvokeSite.invoke(InvokeSite.java:207)", "usr.share.logstash.logstash_minus_core.lib.logstash.agent.RUBY$block$converge_state$2(/usr/share/logstash/logstash-core/lib/logstash/agent.rb:389)", "org.jruby.runtime.CompiledIRBlockBody.callDirect(CompiledIRBlockBody.java:138)", "org.jruby.runtime.IRBlockBody.call(IRBlockBody.java:58)", "org.jruby.runtime.IRBlockBody.call(IRBlockBody.java:52)", "org.jruby.runtime.Block.call(Block.java:139)", "org.jruby.RubyProc.call(RubyProc.java:318)", "org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:105)", "java.base/java.lang.Thread.run(Thread.java:829)"]}
```

It looks like there is no azure log analytics plugin available for logstash output
https://www.elastic.co/guide/en/logstash/7.13/output-plugins.html
Also it looks like it gets discontinued from `7.8` version onwards - https://www.elastic.co/guide/en/logstash/current/azure-module.html

is it so? please can you confirm?
That means we will not be able to upgrade to latest logstash if we want to stick to azure log analytics

**Comment by andsel** [comment] 2021-06-18 07:50
Hi @carijit24 

> It looks like there is no azure log analytics plugin available for logstash output

yes the error is due to the fact that `logstash-output-azure_analytics` is not installed. That plugin is not an official plugin released with Logstash, nor in version `7.1.1` (https://github.com/elastic/logstash/blob/v7.1.1/Gemfile.jruby-2.5.lock.release).
However you can install it in Logstash with `bin/logstash-plugin install logstash-output-azure_analytics.
Mind that is maintained here https://github.com/yokawasa/logstash-output-azure_loganalytics.

> Also it looks like it gets discontinued from 7.8 version onwards - https://www.elastic.co/guide/en/logstash/current/azure-module.html

Yes that's discontinued, but the job of that module was to bring data in from Azure Event Hub and have some dashboards on Kibana, it didn't push data output to Azure, so it's not comparable with `logstash-output-azure_analytics`.

So as recap, you can use `logstash-output-azure_analytics` in Logstash `7.13.0` you only have to install it.

**Comment by carijit24** [comment] 2021-06-23 16:20
Hi @andsel  
    I have upgraded the logstash version to latest `7.13.2` and in process of testing. Its very hard to replicate the scenario. However I have enabled logstash and logstash output azureloganalytics plugin to `TRACE` to check when the logstash pod is getting scaled down how the logs look like.
As we have `queue.drain` to `true`, I've noticed that when logstash pod received `SIGTERM` signal its actually doing a graceful shutdown as it looks like 
it first stopped receiving input logs from `filebeat` 
then it processes the messages in persistent queues through multi pipelines
at last it stopped the queues and pipelines and it completely shutdown.

I've attached the log here just to get my understanding verified with you.
[logstash_sigterm.log](https://github.com/elastic/logstash/files/6703453/logstash_sigterm.log)

**Comment by andsel** [comment] 2021-06-24 12:14
It seems a clean shutdown, so to me seems fixed and without any problem

**Comment by andsel** [comment] 2021-07-06 12:47
Hi @carijit24 do you consider this issue as resolved or Logstash is still experiencing problems?

**Comment by carijit24** [comment] 2021-07-21 09:44
@andsel we have monitored the latest logstash changes in our test environments and no complaints. we recently roll out the latest version to our production. so far so good. We can close this ticket I guess. Thanks a lot for your suggestion.

**Comment by andsel** [comment] 2021-07-21 10:39
That's great @carijit24 !

**Closed by andsel** 2021-07-21 10:39 UTC
Labels: docker, docs, enhancement, persistent queues, status:needs-info

**Comment by qxmips** [comment] 2022-12-08 11:36
> @andsel what would be the latest stable version of logstash if I plan to upgrade our logstash version ? will the version `7.13.0` be good - https://www.elastic.co/guide/en/logstash/current/logstash-7-13-0.html ? Its better to upgrade to the latest version and then see if it solves the purpose.
> 
> I have one more query - does logstash support Amazon SQS as persistent queue. we're planning to move out of logstash persistent queues which internally use aws EFS and introduce a message broker instead.

Hi @carijit24 , just saw your message regarding persistent queues vs SQS,  did you have any performance issue when stored the queues on EFS storage? does it work better with a broker instead of the persistent queues  in your case?
