### ISSUE TITLE
[WARN ][logstash.inputs.udp ] UDP listener died {:exception=>#<IOError: closed stream>

### ISSUE THREAD

**Issue by ismFerDev** [elastic/logstash#7554] opened 2017-06-28 12:38 UTC
- Version: 5 
- Operating System: Amazon Linux

Hi team,

I'm having this error:
```
Jun 28 12:17:51 ip-192-168-174-194.eu-west-1.compute.internal docker-compose[2040]: devops-common-logstash_1  | 12:17:51.181 [[main]<udp] WARN  logstash.inputs.udp - UDP listener died {:exception=>#<IOError: closed stream>, :backtrace=>["org/jruby/RubyIO.java:3705:in `select'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-udp-3.1.0/lib/logstash/inputs/udp.rb:93:in `udp_listener'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-udp-3.1.0/lib/logstash/inputs/udp.rb:56:in `run'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:443:in `inputworker'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:436:in `start_input'"]}
Jun 28 12:17:56 ip-192-168-174-194.eu-west-1.compute.internal docker-compose[2040]: devops-common-logstash_1  | 12:17:56.075 [Ruby-0-Thread-1448: /usr/share/logstash/logstash-core/lib/logstash/shutdown_watcher.rb:31] WARN  logstash.shutdownwatcher - {"inflight_count"=>443, "stalling_thread_info"=>{"other"=>[{"thread_id"=>35, "name"=>"[main]<beats", "current_call"=>"[...]/vendor/bundle/jruby/1.9/gems/logstash-input-beats-3.1.18-java/lib/logstash/inputs/beats.rb:206:in `run'"}, {"thread_id"=>36, "name"=>"[main]<tcp", "current_call"=>"[...]/vendor/bundle/jruby/1.9/gems/logstash-input-tcp-4.1.0/lib/logstash/inputs/tcp.rb:122:in `accept'"}], ["LogStash::Filters::Metrics", {"meter"=>"event", "add_tag"=>"metric", "id"=>"1743b6c1b8df363109da9024a4cfa13de134e571-23"}]=>[{"thread_id"=>28, "name"=>"[main]>worker0", "current_call"=>"[...]/vendor/bundle/jruby/1.9/gems/jls-grok-0.11.4/lib/grok-pure.rb:182:in `match'"}, {"thread_id"=>30, "name"=>"[main]>worker2", "current_call"=>"[...]/logstash-core/lib/logstash/instrument/metric_store.rb:55:in `put_if_absent'"}], ["LogStash::Filters::UserAgent", {"target"=>"useragent", "source"=>"agent", "add_field"=>{"[useragent][raw]"=>"%{agent}"}, "remove_field"=>["agent"], "id"=>"1743b6c1b8df363109da9024a4cfa13de134e571-15"}]=>[{"thread_id"=>29, "name"=>"[main]>worker1", "current_call"=>"[...]/vendor/bundle/jruby/1.9/gems/logstash-filter-grok-3.4.1/lib/logstash/filters/grok.rb:345:in `each'"}, {"thread_id"=>31, "name"=>"[main]>worker3", "current_call"=>"[...]/vendor/bundle/jruby/1.9/gems/logstash-filter-date-3.1.5/lib/logstash/filters/date.rb:176:in `initialize'"}]}}
```
I can't reproduce it.

**Comment by ismFerDev** [comment] 2017-06-28 13:13
mu conf file:
```
/opt/logstash# cat /etc/logstash/conf.d/*
input {
  udp {
    port => 5001
    type => "udp"
  }
}input {
  tcp {
    port => 5002
    codec => "json_lines"
    type => "journald"
  }
}input {
  beats {
    port => 5001
  }
}input {
  tcp {
    port => 5004
    type => "tcp"
    codec => json_lines
  }
}filter {
if [type] != "tcp" {
  if [input_type] == "stdin" {
    json{
      source => "message"
      target => "message_json"
    }
    mutate {
      replace => { "message" => "%{[message_json][MESSAGE]}" }
      add_field => {
        "systemd_service" => "%{[message_json][_SYSTEMD_UNIT]}"
        "[beat][name]" => "%{[message_json][_SYSTEMD_UNIT]}"
        "hostname" => "%{[message_json][_HOSTNAME]}"
        "__REALTIME_TIMESTAMP" => "%{[message_json][__REALTIME_TIMESTAMP]}"
        "_CMDLINE" => "%{[message_json][_CMDLINE]}"
        "_MACHINE_ID" => "%{[message_json][_MACHINE_ID]}"
        "priority_code" => "%{[message_json][PRIORITY]}"
      }
      remove_field => [ "message_json", "timestamp" ]
      rename => [ "MESSAGE", "message" ]
      rename => [ "_SYSTEMD_UNIT", "systemd_service" ]
      rename => [ "_HOSTNAME", "hostname" ]
      gsub => [ "__REALTIME_TIMESTAMP", ".{3}$", "" ]
      gsub => [ "[beat][name]", ".service", "" ]
    }
    grok {
      match => { "message" => '(?i)%{COMBINEDAPACHELOG} %{NUMBER} %{QS} %{QS}' }
      add_tag => [ "access_log" ]
      tag_on_failure => [ ]
    }

    if "access_log" in [tags] {
      mutate {
        replace => { "source" => "/var/log/%{[beat][name]}/access.log" }
        remove_field => [ "clientip", "ident", "auth", "verb", "request", "httpversion", "rawrequest", "response", "bytes", "elapsedTime", "referrer", "agent" ]
      }
    } else {
      mutate {
        replace => { "source" => "/var/log/%{[beat][name]}/app.log" }
      }
    }
  }
}
}filter {
  if [type] == "tcp" {
    if [re_matching_event_type] == "aggregate_int" {
      grok {
        match => { "message" => "%{DATA:re_matching_entity}--%{DATA:re_matching_action} %{NUMBER:re_matching_count}"}
      }
      mutate {
        convert => {"re_matching.count" => "integer"}
      }
    }
  }
}filter {
    if [source] =~ "access.log"{
        grok {
          match => { "message" => '(?i)%{COMBINEDAPACHELOG} %{NUMBER:elapsedTime} %{QS:zipkinParentId} %{QS:zipkinTraceId}' }
          # For backwards compatibility with old Kibana dashboards
          add_field => {
            "http_verb" => "%{verb}"
            "http_request" => "%{request}"
            "http_version" => "%{httpversion}"
            "http_status_code" => "%{response}"
            "referer" => "%{referrer}"
            "response_bytes" => "%{bytes}"
            "timeTaken" => "%{elapsedTime}"
          }
        }

        mutate {
          convert => { "elapsedTime" => "integer" }
          convert => { "timeTaken" => "integer" }
          convert => { "bytes" => "integer" }
          convert => { "response_bytes" => "integer" }
          add_tag => [ "access_log" ]
        }

        geoip {
            source => "clientip"
        }

        useragent {
            target => "useragent"
            source => "agent"
            add_field => { "[useragent][raw]" => "%{agent}" }
            remove_field => [ "agent" ]
        }

        date {
            match => [ "timestamp" , "dd/MMM/yyyy:HH:mm:ss Z" ]
            remove_field => ["timestamp"]
        }
    }
}filter {
    if [source] =~ "app.log"{
        grok {
            match => { "message" => "%{TIMESTAMP_ISO8601:date} %{LOGLEVEL:priority} %{NUMBER:pid} \[%{DATA:thread}\] %{DATA:logger} : (%{GREEDYDATA:message}\s+\{%{DATA:context}\}|%{GREEDYDATA:message})\s+\{%{DATA:mdc}\}\s*(%{GREEDYDATA:stacktrace})?" }
            overwrite => [ "message" ]
        }

        if [stacktrace] {
            ruby {
                code => "
                     event.set('stacktrace', event.get('stacktrace').gsub(92.chr + 'n', 10.chr))
                "
            }
        }

        mutate {
            add_tag => [ "app_log" ]
            gsub => [ "context", '(?<!")\s*:\s*(?<!")', "." ]
            gsub => [ "context", '(?<!")\s*"\s*(?<!")', " " ]
            #gsub => [ "context", '"(:\s?)"', '"‡"' ]
        }

        kv {
            recursive => true
            value_split => ":"
            field_split => ","
            source => "context"
            target => "context"
            trim_key => "\"\ \(\)"
        }

        kv {
            field_split => ", "
            source => "mdc"
            target => "mdc"
        }

        date {
          match => ["date", "ISO8601"]
          remove_field => ["date"]
        }
    }
}
# This will emit metrics of the messages received
# https://www.elastic.co/guide/en/logstash/current/plugins-filters-metrics.html
filter {
    metrics {
      meter => "event"
      add_tag => "metric"
    }
}
output {
  if "metric" not in [tags] {
    amazon_es {
      hosts => “HOST"
      port => 80
      protocol => http
      region => "eu-west-1"
      template_name => "filebeat"
      template => "/etc/logstash/template.json"
      template_overwrite => true
      flush_size => 10000
      idle_flush_time => 10
      max_retries => 5
    }
  }
}
output {
  if [source] =~ "access.log"{
    statsd {
      host => "statsd"
      port => "8125"
      sender => "%{[beat][name]}"
      increment => "status.%{response}"
    }
  }
}
output {
  if "metric" in [tags] {
    statsd {
      host => "statsd"
      port => "8125"
      namespace => "i-0330b50ef287ebfad--logstash"
      set => {
        rate_1m => "%{[event][rate_1m]}"
        rate_5m => "%{[event][rate_5m]}"
        rate_15m => "%{[event][rate_15m]}"
        count => "%{[event][count]}"
      }
    }
  }
}
```

**Comment by micoq** [comment] 2017-06-29 17:27
Hello,

It could be a file descriptor exhaustion caused by too many TCP clients on ports 5002 and 5004. I had the same problem  (#7401). The UDP input can die because it can consume some file descriptors for the underlying `epoll()` call and reach the limit (it's not related to the number of UDP clients).

However, the TCP input will crash more often in this situation (each TCP client consumes a descriptor). Did you sometimes have a message like this ?
`[ERROR][logstash.inputs.tcp      ] An error occurred. Closing connection {:client=>"10.0.0.1:50748", :exception=>#<IOError: Too many open files>...`

Anyways, you can try to increase the file descriptor limits for the user who runs Logstash to be able to handle all your TCP clients: 4 files descriptors per TCP client and 1 file descriptor per beats client.

**Comment by ismFerDev** [comment] 2017-06-29 20:30
Hi @micoq ,
first, thanks for your advice.
I think too that problem were related to fd and limits but:
1) 
```
ip-192-168-174-194 10031 # ps -ef|grep -i logstas
root      9991  9975  0 07:43 ?        00:00:00 /sbin/tini -- /docker-entrypoint.sh logstash -f /etc/logstash/conf.d -w 4 --http.host 0.0.0.0 --debug 4
root     10031  9991 98 07:43 ?        12:17:18 /docker-java-home/jre/bin/java -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+DisableExplicitGC -Djava.awt.headless=true -Dfile.encoding=UTF-8 -XX:+HeapDumpOnOutOfMemoryError -Xmx1g -Xms256m -Xss2048k -Djffi.boot.library.path=/usr/share/logstash/vendor/jruby/lib/jni -Xbootclasspath/a:/usr/share/logstash/vendor/jruby/lib/jruby.jar -classpath : -Djruby.home=/usr/share/logstash/vendor/jruby -Djruby.lib=/usr/share/logstash/vendor/jruby/lib -Djruby.script=jruby -Djruby.shell=/bin/sh org.jruby.Main /usr/share/logstash/lib/bootstrap/environment.rb logstash/runner.rb -f /etc/logstash/conf.d -w 4 --http.host 0.0.0.0 --debug 4
```
2)
```
ip-192-168-174-194 10031 # cd /proc/10031/
ip-192-168-174-194 10031 # cat limits
...
Max open files            1048576              1048576              files
...
```
3)
```
ip-192-168-174-194 tmp # lsof| grep 10031|wc -l
21773
```
4) I haven't got limit per user.
```
ip-192-168-174-194 limits.d # whoami
root
ip-192-168-174-194 limits.d # ulimit
unlimited
```
I see that open file number is growing, on the other hand I can't find `Too many open files` on trace.

I'm going to monitoring fd.

**Comment by micoq** [comment] 2017-06-29 22:31
You can also checks the system-wide limit:
`cat /proc/sys/fs/file-max`

I didn't know if it's relevant for this problem but you can check the thread number used by Logstash: each TCP connection creates a thread and `IO.Select()` can create a thread too (however the error message doesn't match).

enother limiting factor could be the maximum thread number: Each TCP connection creates a thread and IO.Select()

**Comment by jsvd** [comment] 2017-08-04 15:22
closing as duplicated of https://github.com/logstash-plugins/logstash-input-udp/issues/29

**Closed by jsvd** 2017-08-04 15:22 UTC
