### ISSUE TITLE
[test failure: master, 6.x] NoMethodError: undefined method `[]=' for #<LogStash::OutputDelegator:0x14e3006f>

### ISSUE THREAD

**Issue by colinsurprenant** [elastic/logstash#8025] opened 2017-08-18 15:47 UTC
Showed up once in master build https://logstash-ci.elastic.co/job/elastic+logstash+master+dockerubuntu-periodic/3122/consoleFull

```
Failures:

  1) LogStash::Api::Modules::Plugins should return a 404 to unknown request
     Failure/Error: output_events_map = Hash.new { |h, k| h[k] = [] }

     NoMethodError:
       undefined method `[]=' for #<LogStash::OutputDelegator:0x14e3006f>
     Shared Example Group: "not found" called from ./logstash-core/spec/logstash/api/modules/node_plugins_spec.rb:9
     # ./logstash-core/lib/logstash/pipeline.rb:522:in `block in output_batch'
     # ./logstash-core/lib/logstash/pipeline.rb:529:in `block in output_batch'
     # ./logstash-core/lib/logstash/util/wrapped_acked_queue.rb:297:in `block in each'
     # ./logstash-core/lib/logstash/util/wrapped_acked_queue.rb:296:in `each'
     # ./logstash-core/lib/logstash/pipeline.rb:523:in `output_batch'
     # ./logstash-core/lib/logstash/pipeline.rb:481:in `worker_loop'
     # ./logstash-core/lib/logstash/pipeline.rb:437:in `block in start_workers'

Finished in 8.2 seconds (files took 19.72 seconds to load)
13 examples, 1 failure

Failed examples:

rspec ./logstash-core/spec/logstash/api/modules/node_plugins_spec.rb:7 # LogStash::Api::Modules::Plugins should return a 404 to unknown request

Randomized with seed 35047
```

**Comment by colinsurprenant** [comment] 2017-08-18 20:36
again in https://logstash-ci.elastic.co/job/elastic+logstash+6.x+multijob-unix-compatibility/os=debian/42/console

**Comment by original-brownbear** [comment] 2017-09-03 06:33
This is a duplicate of https://github.com/elastic/logstash/issues/8030 (it's a Jruby9k JIT issue).
This may be fixed by a new JRuby tomorrow (that's why I heard at least, it's fixed with JRuby `master`).

**Closed by original-brownbear** 2017-09-03 06:33 UTC
Labels: test failure
