### ISSUE TITLE
bin/plugin install local-thing.gem still tries to reach rubygems.org

### ISSUE THREAD

**Issue by jordansissel** [elastic/logstash#3571] opened 2015-07-07 22:40 UTC
Reported on discuss.elastic.co: https://discuss.elastic.co/t/shield-w-logstash-offline-install/25072/2

I think this is because bin/plugin updates the Gemfile and then runs the equivalent of `bundle install` which will ask rubygems.org for a manifest of current gems while it tries to apply the Gemfile.

**Comment by Sunte16** [comment] 2015-07-20 11:03
Does already a solution exist for that issue? I am facing exactly the same problem...

**Comment by jonlieb** [comment] 2015-07-23 19:30
I have the same problem. I am using logstash-1.5.0. will 1.5.1 fix it? is there a fix in work? what is the ETA?

**Comment by jordansissel** [comment] 2015-07-24 05:22
The following PRs are working towards fixing offline and private-gem-repository solutions:
* https://github.com/elastic/logstash/pull/3583
* https://github.com/elastic/logstash/pull/3404

If you are affected by this problem, your help with testing and validating of these patches is much appreciated. :)

**Comment by darkdefender27** [comment] 2015-10-09 10:37
I know this is a pretty old discussion thread. But, I am curious to know whether the issue is resolved or not. Because I am also facing the exact issue as the people above. PS. I am sitting behind a company proxy. Any help is much appreciated. Thanks!

**Comment by purbon** [comment] 2015-10-09 10:54
@darkdefender27 as noted by @jordansissel, this is solved in #3583, however this PR is taking a while to get merged in, as soon as ready it will get merged and delivered. I apologies for the inconveniences in the meanwhile, although you're more than welcome, actually very appreciate it, so jump in and test if #3583 actually fix your issue.

@darkdefender27 re:proxy not sure it's your issue. The problem nowadays is that only ```https://rubygems.org``` is being requested, skipping any other source setup, for commands in ```bin/plugin```. The right behaviour is to use the Gemfile defined sources.

**Comment by wiibaa** [comment] 2016-05-25 20:58
@purbon now the PR is mergerd, is this issue solved ?

**Comment by ph** [comment] 2017-01-03 15:42
Reaching rubygems when installing a .gem is currently an **expected** behavior, when you install a .gem it may requires  additional dependencies or updates and theses will be done when you install it. A *.gem* bit itself doesn't have any concept of the outside world.

What you actually need here is to install the `.gem` in an online environment and do `prepare-offline-pack` which will come in 5.2 https://github.com/elastic/logstash/pull/6404

The previous command will create what we could call a uber gem containing all the dependencies.

**Closed** 2017-01-03 15:42 UTC
Labels: bug, bundler, plugin manager
