### ISSUE TITLE
bin/logstash -version tries to parse a config

### ISSUE THREAD

**Issue by ph** [elastic/logstash#5017] opened 2016-04-05 13:18 UTC
I don' think this is expected when you run `bin/logstash -version` it tries to load a configuration file and fails. I believe it should return `missing parameters` or `invalid command`
```
~/e/s/logstash-5.0.0-alpha1.snapshot2 ❯❯❯ bin/logstash -version
fetched an invalid config {:config=>"rsioninput { stdin { type => stdin } }output { stdout { codec => rubydebug } }", :reason=>"Expected one of #, input, filter, output at line 1, column 1 (byte 1) after ", :level=>:error}
starting agent {:level=>:info}
~/e/s/logstash-5.0.0-alpha1.snapshot2

```

**Comment by jsvd** [comment] 2016-04-05 14:12
closing as a duplicate of https://github.com/elastic/logstash/issues/4861

**Closed by jsvd** 2016-04-05 14:12 UTC
Labels: bug, known issue, v5.0.0-alpha2
