### ISSUE TITLE
Apply fix for cgroups when used in docker containers

### ISSUE THREAD

**Issue by tylersmalley** [elastic/logstash#6797] opened 2017-03-03 01:23 UTC
A fix was made in [Elasticsearch](https://github.com/elastic/elasticsearch/pull/22757) and [elasticsearch-docker](https://github.com/elastic/elasticsearch-docker/pull/25) to workaround a mounting issue within cgroups. Logstash should account for this as well.

**Comment by tylersmalley** [comment] 2017-03-03 01:24
cc: @bohyun-e

**Comment by bohyun-e** [comment] 2017-03-03 01:43
@suyograo @ph could you guys look into this? Thanks.

**Comment by ph** [comment] 2017-03-03 05:38
Thanks @bohyun-e 

We have two solutions to implement the same workaround:

1. Either we add a new options to our *logstash.yml* file `cgroups.hierarchy.override` ?
2. Or we go with the java property option in the *jvm.options* file.

I am inclined to go to 1 route simply because we don't really use java properties.

**Comment by bohyun-e** [comment] 2017-03-03 06:39
cc: @jasontedor since he's worked on the ES side of things.

**Comment by tylersmalley** [comment] 2017-03-04 02:43
@ph, that's also the route were going to take in Kibana.

**Comment by jasontedor** [comment] 2017-03-04 02:54
@tylersmalley @ph I recommend making two properties (instead of one as was done in Elasticsearch) and naming them something like `cgroup.cpu.path.override` and `cgroup.cpuacct.path.override`. I intend to deprecate `cgroups.hierarchy.override` in Elasticsearch and replace them with something like the above. Also, as we've done in Elasticsearch, I would make it clear that this a hack around an upstream problem and will eventually be removed.

**Comment by ph** [comment] 2017-03-15 00:33
I've sync with @jasontedor and will use the following scheme:

```
cpu.cgroup.path.override
cpuacct.cgroup.path.override
```

**Comment by luismanuel001** [comment] 2017-08-08 15:43
any workaround for this error?

**Comment by jayunit100** [comment] 2017-08-10 14:29
were seeing this to, any update ?

**Comment by shaunr88** [comment] 2018-02-28 16:56
Was this work ever completed?

**Comment by antalm** [comment] 2018-03-01 13:02
I'd like to run logstash in a container, but I don't want to mount /sys/fs/cgroup from the host. Is it possible to do so in recent version of logstash?

**Comment by jarpy** [comment] 2018-08-28 03:55
We're getting a lot of reports in elastic/logstash-docker#89 that I _think_ would be resolved by this feature.

**Comment by guyboertje** [comment] 2018-09-13 13:52
So to sum up: this is a hack to provide substitute paths segments to build a successful full path to the needed paths but we don't know what the underlying problem is.

**Comment by jasontedor** [comment] 2018-09-15 03:44
So we understand the problem quite well. The problem is that inside a container, when you read `/proc/self/cgroup` we get paths to the cgroups that are not the actual paths:

```
23:38:21 1d [jason@totoro:~] $ sudo docker exec -it 0d6ee7a927d8 /bin/bash
[root@0d6ee7a927d8 elasticsearch]# ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
elastic+     1 93.7  2.0 6285520 1338696 ?     Ssl  03:38   0:25 /opt/jdk-10.0.2/bin/java -Xms1g -Xmx1g -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+AlwaysPreTouch -Xss1m -Djav
root       198  0.7  0.0  11832  2996 pts/0    Ss   03:38   0:00 /bin/bash
root       213  0.0  0.0  51720  3468 pts/0    R+   03:38   0:00 ps aux
[root@0d6ee7a927d8 elasticsearch]# cat /proc/1/cgroup 
11:cpuset:/docker/0d6ee7a927d8cbb7334971e1917a97d6e174702f6b16102e056397d53d4159ba
10:perf_event:/docker/0d6ee7a927d8cbb7334971e1917a97d6e174702f6b16102e056397d53d4159ba
9:hugetlb:/docker/0d6ee7a927d8cbb7334971e1917a97d6e174702f6b16102e056397d53d4159ba
8:devices:/docker/0d6ee7a927d8cbb7334971e1917a97d6e174702f6b16102e056397d53d4159ba
7:blkio:/docker/0d6ee7a927d8cbb7334971e1917a97d6e174702f6b16102e056397d53d4159ba
6:net_cls,net_prio:/docker/0d6ee7a927d8cbb7334971e1917a97d6e174702f6b16102e056397d53d4159ba
5:memory:/docker/0d6ee7a927d8cbb7334971e1917a97d6e174702f6b16102e056397d53d4159ba
4:cpu,cpuacct:/docker/0d6ee7a927d8cbb7334971e1917a97d6e174702f6b16102e056397d53d4159ba
3:pids:/docker/0d6ee7a927d8cbb7334971e1917a97d6e174702f6b16102e056397d53d4159ba
2:freezer:/docker/0d6ee7a927d8cbb7334971e1917a97d6e174702f6b16102e056397d53d4159ba
1:name=systemd:/docker/0d6ee7a927d8cbb7334971e1917a97d6e174702f6b16102e056397d53d4159ba
0::/system.slice/docker.service
```

However, these are not right, *within* the container, it's a lie, a terrible lie. Instead, we *have* to look at `/sys/fs/cgroup/`.

See elastic/elasticsearch-docker#25 for more background, especially the comment in the commit that explains the situation.

**Comment by jasontedor** [comment] 2018-09-15 03:46
This is Docker problem, by the way (actually it's at an even lower level). There are upstream issues for it, linked previously, but it's been awhile so I am doubting they will ever do anything about it.

**Closed** 2018-09-22 11:13 UTC
Labels: monitoring
