### ISSUE TITLE
Gradle/Java Unit Tests Have no Log4J Configuration

### ISSUE THREAD

**Issue by original-brownbear** [elastic/logstash#7242] opened 2017-05-28 22:41 UTC
When I run standard gradle tests via `./gradlew test` I see a bunch of this:

```sh
org.logstash.ackedqueue.HeadPageTest > newHeadPage STANDARD_ERROR
    ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console.

org.logstash.DLQEntryTest > testSerDe STANDARD_ERROR
    SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
    SLF4J: Defaulting to no-operation (NOP) logger implementation
    SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

Logging for tests should be correctly configured by putting a `log4j*.properties` file in the test resources so that we can get proper stacktraces from failures and remove the annoying warning.

**Comment by jakelandis** [comment] 2017-07-06 18:18
There are actually issues here:


1) 
```
org.logstash.ackedqueue.HeadPageTest > newHeadPage STANDARD_ERROR
    ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console.
```
^^ This is caused by the lack of the log4j2.properties on the classpath. This is resolved via https://github.com/elastic/logstash/issues/7526 by adding a default log4j2.properties on the main classpath (not test) to configure the default context and get rid of the annoying warning on startup. The default configuration will get updated very early in the startup lifecycle.


2)
```
org.logstash.DLQEntryTest > testSerDe STANDARD_ERROR
    SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
    SLF4J: Defaulting to no-operation (NOP) logger implementation
    SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```
^^ This is caused by the lack of an SLF4J to log4j2-impl binding on the classpath. Many (most ?), Java 3rd party libraries log via the SLF4J API, so we need to provide an implementation bridge. I will create PR for this. 

_Of side note, 3rd parties may also use JUL (Java Util Logging) or JCL (Jakarta Commons Logging), in which case we could use libraries provided by SLF4J to re-map those API's to the SLF4J API, which would in turn get implemented by Log4J2, but that has the potential to cause performance issues, and no one is asking for it, and those libraries (JUL/JCL) are not heavily used anymore... so I don't plan to add those wrappers._

**Closed** 2017-07-06 23:42 UTC
Labels: adoptme, low hanging fruit, tests-infra, v5.6.0, v6.0.0
