### ISSUE TITLE
logstash kv plugin issue

### ISSUE THREAD

**Issue by liguoli0216** [elastic/logstash#7006] opened 2017-05-02 07:47 UTC
logstash: 5.2
        kv {
            field_split => "&"
        }
i use the kv plugin format my log, when the log like： **&dname=[=]]=[[=]** , i got error and thread crash：

Exception in thread "[main]>worker0" java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(ArrayList.java:418)
	at java.util.ArrayList.remove(ArrayList.java:495)
	at org.logstash.FieldReference.parse(FieldReference.java:37)
	at org.logstash.PathCache.cache(PathCache.java:37)
	at org.logstash.PathCache.isTimestamp(PathCache.java:30)
	at org.logstash.ext.JrubyEventExtLibrary$RubyEvent.ruby_set_field(JrubyEventExtLibrary.java:122)
	at org.logstash.ext.JrubyEventExtLibrary$RubyEvent$INVOKER$i$2$0$ruby_set_field.call(JrubyEventExtLibrary$RubyEvent$INVOKER$i$2$0$ruby_set_field.gen)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:202)
	at rubyjit.LogStash::Filters::KV$$filter_77eb82846fd5a9ee64951db60649781fb6c097bc1028566121.block_1$RUBY$__file__(/usr/share/logstash/vendor/bundle/jruby/1.9/gems/l
ogstash-filter-kv-3.1.1/lib/logstash/filters/kv.rb:287)
	at rubyjit$LogStash::Filters::KV$$filter_77eb82846fd5a9ee64951db60649781fb6c097bc1028566121$block_1$RUBY$__file__.call(rubyjit$LogStash::Filters::KV$$filter_77eb828
46fd5a9ee64951db60649781fb6c097bc1028566121$block_1$RUBY$__file__)
	at org.jruby.runtime.CompiledBlock19.yield(CompiledBlock19.java:135)
	at org.jruby.runtime.Block.yield(Block.java:142)
	at org.jruby.RubyHash$13.visit(RubyHash.java:1355)
	at org.jruby.RubyHash.visitLimited(RubyHash.java:648)
	at org.jruby.RubyHash.visitAll(RubyHash.java:634)
	at org.jruby.RubyHash.iteratorVisitAll(RubyHash.java:1306)
	at org.jruby.RubyHash.each_pairCommon(RubyHash.java:1351)
	at org.jruby.RubyHash.each19(RubyHash.java:1342)
	at org.jruby.RubyHash$INVOKER$i$0$0$each19.call(RubyHash$INVOKER$i$0$0$each19.gen)
	at org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:143)
	at org.jruby.runtime.callsite.CachingCallSite.callIter(CachingCallSite.java:154)
	at rubyjit.LogStash::Filters::KV$$filter_77eb82846fd5a9ee64951db60649781fb6c097bc1028566121.__file__(/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-filte
r-kv-3.1.1/lib/logstash/filters/kv.rb:287)
	at rubyjit.LogStash::Filters::KV$$filter_77eb82846fd5a9ee64951db60649781fb6c097bc1028566121.__file__(/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-filte
r-kv-3.1.1/lib/logstash/filters/kv.rb)
	at org.jruby.internal.runtime.methods.JittedMethod.call(JittedMethod.java:201)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:336)
	at org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:179)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:183)
	at rubyjit.LogStash::Filters::Base$$do_filter_8e8403dcfdf01a35ffca12ed35ec4e79455489071028566121.__file__(/usr/share/logstash/logstash-core/lib/logstash/filters/bas
e.rb:145)
	at rubyjit.LogStash::Filters::Base$$do_filter_8e8403dcfdf01a35ffca12ed35ec4e79455489071028566121.__file__(/usr/share/logstash/logstash-core/lib/logstash/filters/bas
e.rb)
	at org.jruby.internal.runtime.methods.JittedMethod.call(JittedMethod.java:201)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:336)
	at org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:179)
	at org.jruby.runtime.callsite.CachingCallSite.callIter(CachingCallSite.java:188)
	at rubyjit.LogStash::Filters::Base$$multi_filter_6c0dea8219a042f89f5a5b41e60697f8088a7c451028566121.block_0$RUBY$__file__(/usr/share/logstash/logstash-core/lib/logs
tash/filters/base.rb:164)
	at rubyjit$LogStash::Filters::Base$$multi_filter_6c0dea8219a042f89f5a5b41e60697f8088a7c451028566121$block_0$RUBY$__file__.call(rubyjit$LogStash::Filters::Base$$mult
i_filter_6c0dea8219a042f89f5a5b41e60697f8088a7c451028566121$block_0$RUBY$__file__)
	at org.jruby.runtime.CompiledBlock19.yield(CompiledBlock19.java:135)
	at org.jruby.runtime.Block.yield(Block.java:142)
	at org.jruby.RubyArray.eachCommon(RubyArray.java:1606)
	at org.jruby.RubyArray.each(RubyArray.java:1613)
	at org.jruby.RubyArray$INVOKER$i$0$0$each.call(RubyArray$INVOKER$i$0$0$each.gen)
	at org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:143)
	at org.jruby.runtime.callsite.CachingCallSite.callIter(CachingCallSite.java:154)
	at rubyjit.LogStash::Filters::Base$$multi_filter_6c0dea8219a042f89f5a5b41e60697f8088a7c451028566121.__file__(/usr/share/logstash/logstash-core/lib/logstash/filters/
base.rb:161)
	at rubyjit.LogStash::Filters::Base$$multi_filter_6c0dea8219a042f89f5a5b41e60697f8088a7c451028566121.__file__(/usr/share/logstash/logstash-core/lib/logstash/filters/
base.rb)
	at org.jruby.internal.runtime.methods.JittedMethod.call(JittedMethod.java:181)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:326)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:170)
	at rubyjit.LogStash::FilterDelegator$$multi_filter_87d312cb29252318f5ba9dfc74f2695ff3ca582a1028566121.__file__(/usr/share/logstash/logstash-core/lib/logstash/filter
_delegator.rb:41)
	at rubyjit.LogStash::FilterDelegator$$multi_filter_87d312cb29252318f5ba9dfc74f2695ff3ca582a1028566121.__file__(/usr/share/logstash/logstash-core/lib/logstash/filter
_delegator.rb)
	at org.jruby.internal.runtime.methods.JittedMethod.call(JittedMethod.java:181)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:168)
	at org.jruby.ast.CallOneArgNode.interpret(CallOneArgNode.java:57)
	at org.jruby.ast.DAsgnNode.interpret(DAsgnNode.java:110)
	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
	at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
	at org.jruby.evaluator.ASTInterpreter.INTERPRET_BLOCK(ASTInterpreter.java:112)
	at org.jruby.runtime.Interpreted19Block.evalBlockBody(Interpreted19Block.java:206)
	at org.jruby.runtime.Interpreted19Block.yield(Interpreted19Block.java:194)
	at org.jruby.runtime.Interpreted19Block.call(Interpreted19Block.java:125)
	at org.jruby.runtime.Block.call(Block.java:101)
	at org.jruby.RubyProc.call(RubyProc.java:300)
	at org.jruby.internal.runtime.methods.ProcMethod.call(ProcMethod.java:64)
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:210)
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:206)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:168)
	at rubyjit.LogStash::Pipeline$$filter_batch_8b39fcf0c88910d9d1334cd3b953ec2ed19c83e91028566121.block_0$RUBY$__file__(/usr/share/logstash/logstash-core/lib/logstash/
pipeline.rb:378)
	at rubyjit$LogStash::Pipeline$$filter_batch_8b39fcf0c88910d9d1334cd3b953ec2ed19c83e91028566121$block_0$RUBY$__file__.call(rubyjit$LogStash::Pipeline$$filter_batch_8
b39fcf0c88910d9d1334cd3b953ec2ed19c83e91028566121$block_0$RUBY$__file__)
	at org.jruby.runtime.CompiledBlock19.yield(CompiledBlock19.java:159)
	at org.jruby.runtime.CompiledBlock19.call(CompiledBlock19.java:87)
	at org.jruby.runtime.Block.call(Block.java:101)
	at org.jruby.RubyProc.call(RubyProc.java:300)
	at org.jruby.RubyProc.call19(RubyProc.java:281)
	at org.jruby.RubyProc$INVOKER$i$0$0$call19.call(RubyProc$INVOKER$i$0$0$call19.gen)
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:210)
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:206)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:168)
	at rubyjit.LogStash::Util::WrappedSynchronousQueue::ReadBatch$$each_eec1abd315644e9e3d7962c32b7a93c73eaf0a4a1028566121.block_0$RUBY$__file__(/usr/share/logstash/log
stash-core/lib/logstash/util/wrapped_synchronous_queue.rb:201)
	at rubyjit$LogStash::Util::WrappedSynchronousQueue::ReadBatch$$each_eec1abd315644e9e3d7962c32b7a93c73eaf0a4a1028566121$block_0$RUBY$__file__.call(rubyjit$LogStash::
Util::WrappedSynchronousQueue::ReadBatch$$each_eec1abd315644e9e3d7962c32b7a93c73eaf0a4a1028566121$block_0$RUBY$__file__)
	at org.jruby.runtime.CompiledBlock19.yield(CompiledBlock19.java:135)
	at org.jruby.runtime.Block.yield(Block.java:142)
	at org.jruby.RubyHash$13.visit(RubyHash.java:1355)
	at org.jruby.RubyHash.visitLimited(RubyHash.java:648)
	at org.jruby.RubyHash.visitAll(RubyHash.java:634)
	at org.jruby.RubyHash.iteratorVisitAll(RubyHash.java:1306)
	at org.jruby.RubyHash.each_pairCommon(RubyHash.java:1351)
	at org.jruby.RubyHash.each19(RubyHash.java:1342)
	at org.jruby.RubyHash$INVOKER$i$0$0$each19.call(RubyHash$INVOKER$i$0$0$each19.gen)
	at org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:143)
	at org.jruby.runtime.callsite.CachingCallSite.callIter(CachingCallSite.java:154)
	at rubyjit.LogStash::Util::WrappedSynchronousQueue::ReadBatch$$each_eec1abd315644e9e3d7962c32b7a93c73eaf0a4a1028566121.__file__(/usr/share/logstash/logstash-core/li
b/logstash/util/wrapped_synchronous_queue.rb:200)
	at rubyjit.LogStash::Util::WrappedSynchronousQueue::ReadBatch$$each_eec1abd315644e9e3d7962c32b7a93c73eaf0a4a1028566121.__file__(/usr/share/logstash/logstash-core/li
b/logstash/util/wrapped_synchronous_queue.rb)
	at org.jruby.internal.runtime.methods.JittedMethod.call(JittedMethod.java:161)
	at org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:143)
	at org.jruby.runtime.callsite.CachingCallSite.callIter(CachingCallSite.java:154)
	at rubyjit.LogStash::Pipeline$$filter_batch_8b39fcf0c88910d9d1334cd3b953ec2ed19c83e91028566121.chained_0_rescue_1$RUBY$SYNTHETIC__file__(/usr/share/logstash/logstas
h-core/lib/logstash/pipeline.rb:377)
	at rubyjit.LogStash::Pipeline$$filter_batch_8b39fcf0c88910d9d1334cd3b953ec2ed19c83e91028566121.__file__(/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb)
	at rubyjit.LogStash::Pipeline$$filter_batch_8b39fcf0c88910d9d1334cd3b953ec2ed19c83e91028566121.__file__(/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb)
	at org.jruby.internal.runtime.methods.JittedMethod.call(JittedMethod.java:181)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:326)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:170)
	at org.jruby.ast.FCallOneArgNode.interpret(FCallOneArgNode.java:36)
	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
	at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
	at org.jruby.ast.WhileNode.interpret(WhileNode.java:131)
	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
	at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
	at org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:74)
	at org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:225)
	at org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.java:219)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:346)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:204)
	at org.jruby.ast.FCallTwoArgNode.interpret(FCallTwoArgNode.java:38)
	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
	at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
	at org.jruby.evaluator.ASTInterpreter.INTERPRET_BLOCK(ASTInterpreter.java:112)
	at org.jruby.runtime.Interpreted19Block.evalBlockBody(Interpreted19Block.java:206)
	at org.jruby.runtime.Interpreted19Block.yield(Interpreted19Block.java:194)
	at org.jruby.runtime.Interpreted19Block.call(Interpreted19Block.java:125)
	at org.jruby.runtime.Block.call(Block.java:101)
	at org.jruby.RubyProc.call(RubyProc.java:300)
	at org.jruby.RubyProc.call(RubyProc.java:230)
	at org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:99)
	at java.lang.Thread.run(Thread.java:745)

**Comment by yidingalan** [comment] 2017-05-24 15:41
Got the same error. Hope someone can clarify on this 

kv filter: 
```
  kv { 
    trim_key => "<>\[\],`\."
    remove_field => ["\\%{some_field}", "{%{some_field}"]
    include_brackets => false
  }
```

**Comment by jsvd** [comment] 2017-05-26 16:11
closing as a duplicate of https://github.com/logstash-plugins/logstash-filter-kv/issues/48

**Closed by jsvd** 2017-05-26 16:11 UTC
