### ISSUE TITLE
why does logstash-5.1.1 json filter have a slower performance than logstash-2.3.1

### ISSUE THREAD

**Issue by rivencxl** [elastic/logstash#6425] opened 2016-12-16 07:47 UTC
I'm preparing to upgrade my logstash to 5.1.1, and I'm just surprised that logstash-5.1.1 performed a slower result than logstash-2.3.1!

- Operating System: CentOS Linux release 7.0.1406
- Config File :
`input {
  generator {
    count => 10000000
    message => '[2016-03-28 07:23:33.348] [WARN] [nioEventLoopGroup-3-23] [com.vip.mobile.probe.handler.ProbeV1Handler] >>> [Illegal request -  miss parameter] json={"a":{"c":"cc","d":"dd"},"b":"bbb"} msg=Miss required parameter "mid" in request'
    add_field => ['jsonMsg','{"a":{"c":"cc","d":"dd"},"b":"bbb"}']
 }
}

filter {
        if [jsonMsg] {
           json {
             source => "jsonMsg"
             target => "json"
           }
           mutate {
             remove_field => "jsonMsg"
           }
        }
}
output {
   null {}
}`
- Steps to Reproduce:
 `time logstash-5.1.1/bin/logstash -f test.conf -w 1`
 `time logstash-2.3.1/bin/logstash -f test.conf -w 1`

**Comment by jordansissel** [comment] 2016-12-19 21:29
I get basically the same speed. I tested Logstash 2.3.1, 2.4.1, 5.1.1. All of them hover around 29,100 eps with your config (slightly modified to use stdout instead of null so I can measure throughput).

```input {
  generator {
    count => 10000000
      message => '[2016-03-28 07:23:33.348] [WARN] [nioEventLoopGroup-3-23] [com.vip.mobile.probe.handler.ProbeV1Handler] >>> [Illegal request - miss parameter] json={"a":{"c":"cc","d":"dd"},"b":"bbb"} msg=Miss required parameter "mid" in request'
      add_field => ['jsonMsg','{"a":{"c":"cc","d":"dd"},"b":"bbb"}']
  }
}

filter {
  if [jsonMsg] {
    json {
      source => "jsonMsg"
        target => "json"
    }
    mutate {
      remove_field => "jsonMsg"
    }
  }
}
output {
  stdout { codec => dots } 
}
```

I can't reproduce this. Can you show your numbers?

**Comment by rivencxl** [comment] 2016-12-21 07:47
`[guest@p-centos ~]$ time logstash-5.1.1/bin/logstash -f logstash_conf/test.conf -w 1
Sending Logstash's logs to /home/guest/logstash-5.1.1/logs which is now configured via log4j2.properties
[2016-12-21T15:20:39,355][INFO ][logstash.pipeline        ] Starting pipeline {"id"=>"main", "pipeline.workers"=>1, "pipeline.batch.size"=>125, "pipeline.batch.delay"=>5, "pipeline.max_inflight"=>125}
[2016-12-21T15:20:39,364][INFO ][logstash.pipeline        ] Pipeline main started
[2016-12-21T15:20:39,432][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
[2016-12-21T15:28:49,526][WARN ][logstash.agent           ] stopping pipeline {:id=>"main"}

real	8m16.494s
user	9m21.818s
sys	0m11.586s
[guest@p-centos ~]$ time logstash-2.3.1/bin/logstash -f logstash_conf/test.conf -w 1
Settings: User set pipeline workers: 1, Default pipeline workers: 4
Pipeline main started
Pipeline main has been shutdown
stopping pipeline {:id=>"main"}

real	4m53.476s
user	5m51.198s
sys	0m11.867s`

`[guest@p-centos ~]$ cat logstash_conf/test.conf
input {
  generator {
    count => 10000000
    message => '[2016-03-28 07:23:33.348] [WARN] [nioEventLoopGroup-3-23] [com.vip.mobile.probe.handler.ProbeV1Handler] >>> [Illegal request -  miss parameter] json={"a":{"c":"cc","d":"dd"},"b":"bbb"} msg=Miss required parameter "mid" in request'
    add_field => ['jsonMsg','{"a":{"c":"cc","d":"dd"},"b":"bbb"}']
 }
}

filter {

        if [jsonMsg] {
           json {
             source => "jsonMsg"
             target => "json"
           }
           mutate {
             remove_field => "jsonMsg"
           }
        }
}
output {
   null {}
#   stdout { codec => dots }
}`

**Comment by untergeek** [comment] 2017-01-06 20:37
@rivencxl why don't you try the same method as @jordansissel with the dots codec on stdout?

Also, it appears you're using a VM (I'm guessing from `guest@p-centos`).  Is that the case?  If so, one of the issues with slow startups (especially in VMs) is a lack of entropy.  See #6117 

Otherwise, this is probably a duplicate of #5507 

Closing in favor of one of those tickets.

**Closed by untergeek** 2017-01-06 20:37 UTC
Labels: needs details, unconfirmed
