### ISSUE TITLE
Logstash keeps respawning on Ubuntu 12.04 LTS

### ISSUE THREAD

**Issue by Thinkscape** [elastic/logstash#2676] opened 2015-02-24 17:48 UTC
### Steps
1. Install logstash on Ubuntu 12.04 LTS from debian packages.
2. Start the service.
3. Make sure it is running (i.e. `ps` or `/etc/init.d/logstash status`)
4. Attempt to stop the service with `/etc/init.d/logstash stop`
5. (optionally) attempt to kill it with `killall java` or similar.

### Expected:
The service stops.

### Actual:
It seems that init keeps respawning the service, as it would when it had died for unknown reason. However, /etc/init.d/logstash does indeed kill the process and removes the pid file.

There seems to be some conflict between init respawning and the init scripts for logstash.

`````bash
# service logstash stop
logstash stop/waiting

# ps -Af | grep logstash
logstash   303     1 60 17:33 ?        00:00:25 /usr/bin/java -Djava.io.tmpdir=/var/lib/logstash -Xmx500m -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -Djava.awt.headless=true -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -jar /opt/logstash/vendor/jar/jruby-complete-1.7.11.jar -I/opt/logstash/lib /opt/logstash/lib/logstash/runner.rb agent -f /etc/logstash/conf.d -l /var/log/logstash/logstash.log
logstash  1184     1 88 17:34 ?        00:00:09 /usr/bin/java -Djava.io.tmpdir=/var/lib/logstash -Xmx500m -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -Djava.awt.headless=true -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -jar /opt/logstash/vendor/jar/jruby-complete-1.7.11.jar -I/opt/logstash/lib /opt/logstash/lib/logstash/runner.rb web -l /var/log/logstash/logstash.log
````

````bash
# tail /var/log/syslog -n 2
Feb 24 17:44:35 precise64 kernel: [  661.344984] init: logstash-web main process (1936) terminated with status 1
Feb 24 17:44:35 precise64 kernel: [  661.345013] init: logstash-web main process ended, respawning
`````

**Comment by markwalkom** [comment] 2015-02-25 10:06
It's a different service, it's `logstash-web`, issue a stop on that and you should find things clear up.

**Comment by ph** [comment] 2015-02-25 14:54
Similar to the other issue that you have opened? https://github.com/elasticsearch/logstash/issues/2678
This look related again to `logstash-web`, we have removed this service in 1.5, I'll close this ticket.

If its the `logstash agent` that is failing this could be another bug feel free to open a new ticket.

**Comment by Thinkscape** [comment] 2015-02-25 15:05
This is about agent ... not `-web`.

**Comment by ph** [comment] 2015-02-25 15:11
Ok, I'll try your steps to reproduce it. From the syslog I thought it was `-web`.

**Comment by Thinkscape** [comment] 2015-02-25 15:12
I've pasted wrong lines. It's the same story in syslog for agent which gets respawned after killing.

**Comment by jbq** [comment] 2015-05-15 09:43
Same happened to me, logstash should ship with an empty Upstart config file `/etc/init/logstash.conf` to prevent respawn and to make `service status` reliable

**Comment by Tosta-Mixta** [comment] 2015-09-22 08:41
Same issue for me on Ubuntu 14.04.3 for logstash and logstash-web. 

Repo used : 
deb http://packages.elasticsearch.org/logstash/1.5/debian stable main

--
```bash
# ps -Af | grep logstash
logstash   307  1.2 11.4 3116012 461524 ?      SNsl 09:42   0:45 /usr/bin/java -Djava.io.tmpdir=/var/lib/logstash -Djava.io.tmpdir=/var/lib/logstash -Xmx500m -Xss2048k -Djffi.boot.library.path=/opt/logstash/vendor/jruby/lib/jni -Djava.io.tmpdir=/var/lib/logstash -Djava.io.tmpdir=/var/lib/logstash -Xbootclasspath/a:/opt/logstash/vendor/jruby/lib/jruby.jar -classpath : -Djruby.home=/opt/logstash/vendor/jruby -Djruby.lib=/opt/logstash/vendor/jruby/lib -Djruby.script=jruby -Djruby.shell=/bin/sh org.jruby.Main --1.9 /opt/logstash/lib/bootstrap/environment.rb logstash/runner.rb agent -f /etc/logstash/conf.d -l /var/log/logstash/logstash.log
logstash 16076  188  5.3 2743424 216124 ?      SNsl 10:41   0:13 /usr/bin/java -Djava.io.tmpdir=/var/lib/logstash -Djava.io.tmpdir=/var/lib/logstash -Xmx500m -Xss2048k -Djffi.boot.library.path=/opt/logstash/vendor/jruby/lib/jni -Djava.io.tmpdir=/var/lib/logstash -Djava.io.tmpdir=/var/lib/logstash -Xbootclasspath/a:/opt/logstash/vendor/jruby/lib/jruby.jar -classpath : -Djruby.home=/opt/logstash/vendor/jruby -Djruby.lib=/opt/logstash/vendor/jruby/lib -Djruby.script=jruby -Djruby.shell=/bin/sh org.jruby.Main --1.9 /opt/logstash/lib/bootstrap/environment.rb logstash/runner.rb web -l /var/log/logstash/logstash.log
```

**Comment by markwalkom** [comment] 2015-09-22 08:55
Generally this happens if there is a problem and LS cannot cleanly start, upstart will just try to start a new process continuously.

Check `/var/log/upstart` and you should find something.

**Comment by untergeek** [comment] 2016-03-11 18:00
Logstash web no longer exists in recent versions.  This issue should no longer exist.

Closing.

**Closed by untergeek** 2016-03-11 18:00 UTC

**Comment by networknerd** [comment] 2017-12-07 08:46
The issue might be appearing because in later versions of logstash , logstash is managed via initctl but not via service. The initialization script of logstash must be present at /etc/init/logstash.conf.
If you want to stop logstash , you need to type sudo initctl stop logstash . By doing this , it wont respawn.
