### ISSUE TITLE
logstash init script configtest (and restart) broken for configfile

### ISSUE THREAD

**Issue by stdweird** [elastic/logstash#4470] opened 2016-01-13 09:43 UTC
logstash supports a file for `-f` option, but setting `LS_CONF_DIR` to a file is not support in the init script

this is the problematic code
```bash
configtest() {
  # Check if a config file exists                                                                                                                     
  if [ ! "$(ls -A ${LS_CONF_DIR}/* 2> /dev/null)" ]; then
    log_failure_msg "There aren't any configuration files in ${LS_CONF_DIR}"
    exit 1
  fi
```

* should test for is a file file or presence of files
* `log_failure_msg` does not exist on EL6

impact: configtest is broken, but also `restart`, meaning that upgrading to 2.1.1 results in old verison still runnning

**Comment by purbon** [comment] 2016-03-11 17:12
Hi @stdweird 
  thanks a lot for your feedback, I tried to reproduce in a local vagrant machine and got no positive results on it, what I basically did is

* Install LS 2.1
* Add a config
* update
* restart LS

and everything worked as expected.

in regards of LS_CONF_DIR, for LS when working as a service is intended to actually get its files through  a config dir by design, you simply can drop there your files. 

Can you elaborate more on how log_failure_msg is missing in EL6? I understand it should also be missing from centos 6, isn't?

closing this for now as is really old and did not got more feedback, we can always reopen if more information pop up.

**Closed by purbon** 2016-03-11 17:12 UTC
Labels: bug, needs details, packaging

**Comment by stdweird** [comment] 2016-03-11 17:57
@purbon i can't reopen the issue, but logstatsh allows to pass a file via the `-f` option, and thuse we use the `LS_CONF_DIR` variable (i.e. `LS_CONF_DIR=/path/to/file.conf`). in that case, this fails hard

where is log_failure_msg supposed to come from? is it a function or a script?
