### ISSUE TITLE
Leap year bug?

### ISSUE THREAD

**Issue by johnr-spindance** [elastic/logstash#4929] opened 2016-03-30 15:10 UTC
I found this in our logstash log the other day when looking for a different issue.

I'm sure its not a huge issue since logs were still collected that day but I thought I'd bring it up:

```
{:timestamp=>"2016-02-29T06:46:02.600000+0000", :message=>"Failed parsing date from field", :field=>"timestamp", :value=>"Feb 29 06:46:02", :exception=>org.joda.time.IllegalFieldValueException: Cannot parse "Feb 29 06:46:02": Value 29 for dayOfMonth must be in the range [1,28], :level=>:warn}
```

**Comment by wiibaa** [comment] 2016-03-30 18:40
Hello , I cannot reproduce this with recent version of filter-date plugin, can you please give some more information:
- logstash version
- plugin version from `bin/plugin list --verbose | grep filter-date`

Thanks

**Comment by johnr-spindance** [comment] 2016-03-30 18:44
Sure:

```
$ /opt/logstash/agent/bin/logstash --version
logstash 2.1.0
```

Plugins:
```
$ /opt/logstash/agent/bin/plugin list --verbose | grep filter-date
logstash-filter-date (2.0.2)
```

**Comment by wiibaa** [comment] 2016-03-30 19:54
This version of the plugin was strongly depending on the logstash start date, it seems your instance is running since last year, do you not have the problem that all these events without a year in timestamp have a @timestamp with 2015 instead of 2016 ??

Also upgrading to a more recent version of the plugin would fix the issue

**Comment by johnr-spindance** [comment] 2016-03-30 20:12
Ok, I didn't catch that at first. If the log that was generated is missing the year field, thats something that the app thats logging is missing (ie. not logstash's fault).

**Comment by wiibaa** [comment] 2016-03-31 04:26
Indeed, if you are in a position to change the time format in your application logging that's the better option. However when it is not an option(syslog RFC...), logstash tries to fix this, you can check https://github.com/logstash-plugins/logstash-filter-date/pull/4 for the current logic applied and related bugs that should be similar to your issue. Also there is still an open point for tracking enhancement to this logic in https://github.com/logstash-plugins/logstash-filter-date/issues/51.

If you have enough information about your report, can you please close this issue.
By the way when an issue is plugin-specific, can you please open it directly against the plugin repository next time. Thx

**Comment by suyograo** [comment] 2016-04-15 22:10
Closing. Please reopen in logstash-plugins/logstash-filter-date if still an issue

**Closed by suyograo** 2016-04-15 22:10 UTC
