### ISSUE TITLE
Logstash doesn't handle arrays passed in via environment variables

### ISSUE THREAD

**Issue by nick-george** [elastic/logstash#6665] opened 2017-02-08 11:20 UTC
I can't pass in arrays to Logstash via environment variables. Ideally any support would also support empty arrays. It would also be nice if we could pass in any logstash (Ruby?) type (boolean, array, hash, number, string). Please see this thread for further context: https://discuss.elastic.co/t/ls-environment-variable-handling-doesnt-appear-to-behave-as-documented/73828

- Version: 5.1.2
- Operating System: Oracle Linux (Redhat) 7
- Config File (if you have sensitive info, please remove it):
- Sample Data:
- Steps to Reproduce: (see below)

```
sudo -u logstash LS_ARRAY="['1','2']" /usr/share/logstash/bin/logstash -e \
'input{stdin{}} filter{mutate{add_field=>{my_array=>"${LS_ARRAY}"}}} output{stdout{codec=> rubydebug}}' \
--path.settings /etc/logstash

Sending Logstash's logs to /var/log/logstash which is now configured via log4j2.properties
The stdin plugin is now waiting for input:
BLAH
{
    "@timestamp" => 2017-02-08T11:07:44.778Z,
      "@version" => "1",
          "host" => "countersight-prod.countersight.co",
       "message" => "BLAH",
      "my_array" => "['1','2']"
}

```

**Comment by untergeek** [comment] 2017-02-08 14:21
I understand the desire for this, but it's non-trivial to fix.  Environment variables are strings.  Bash and the like are typeless, so there's no quick or easy way for Logstash to know what the "content" of a shell/environment variable is, that it should be typed, since they are simply read in as strings.

**Comment by nick-george** [comment] 2017-02-08 15:56
Hi untergeek. From comments made by the author of the environment variable functionality (in the linked discuss.elastic.co thread), Fabien seems to think that implementing a fix for arrays would not be all that difficult. 

Or, as an alternative approach:
 
What if the _content_ of the bash variable is placed in the config file verbatim? I'll try and illustrate this with an example: 

In Bash: 
`LS_MY_ARRAY='["1","2","3","4","5"]'`

Some example (hypothetical) logstash config: 
```
filter{
  mutate{
    add_field=>{ 
      my_array=>${LS_ARRAY} <- Note the lack of quotes around the variable reference
    } 
  }
}
``` 

And the resulting config after variable substitution: 
```
filter{
  mutate{
    add_field=>{ 
      my_array=>["1","2","3","4","5"]
    } 
  }
}
```
It shouldn't matter type bash thinks the variable is; what does matter is how logstash interprets it. Part of the problem with the existing environment variable functionality is that any references have to be wrapped in quotes (I don't know why this is the case).

**Comment by untergeek** [comment] 2017-02-08 16:18
@nick-george 

> what does matter is how logstash interprets it. Part of the problem with the existing environment variable functionality is that any references have to be wrapped in quotes (I don't know why this is the case).

That's exactly the issue here.  Variable interpolation between Ruby and shell/ENV _requires_ that the environment variable name be a string (encapsulated in quotes), otherwise we could accidentally stomp on a Ruby variable, or worse, accidentally declare something out of scope which would cause the entire process to crash.  We've looked at this before and there have been no easy answers because we are obliged to protect the code from injection attacks and error causing conditions.

**Comment by nick-george** [comment] 2017-02-08 16:45
Damn.. OK, understood. I'm not sure what Fabien has in mind for a fix. I had assumed that the environment variable interpolation somehow worked more like the C pre-processor or m4.

**Comment by fbaligand** [comment] 2017-02-15 19:07
@untergeek @nick-george 
Yes, I have plan to make it work with arrays. It's pretty easy to do after a look at code.
That said, the only question is to agree with Logstash team for the syntax/behavior.

Up to me, two options in the environment variable injection mechanism :
- In any string at any level , I can detect the syntax `"[value1,value2]"` and convert it to an array of 2 strings
- If specifically the target config is an array, I can detect the syntax `"value1,value2"` and convert it to an array of 2 strings

@jordansissel what do you think about ?

**Comment by nick-george** [comment] 2017-02-21 19:39
Hi Fabien,

It looks like your first option would be easier to detect an empty array with. 

Cheers,
Nick

**Comment by jordansissel** [comment] 2017-02-21 22:02
My preference is for your second suggestion `value1,value2,...` given I have seen this more than the other `[...]` syntax in command line tools.

Additionally, for our configuration types, all of them have validation and parsing functions so we can have the list syntax `value1,value2,...` only be treated as a list for list-like settings.

**Comment by jordansissel** [comment] 2017-02-21 22:05
The proposed syntax:

```
my_array=>${LS_ARRAY} 
```

will require grammar changes in Logstash, and I typically resist grammar changes because they are hard for us to get right. However, I am open to this proposal.

**Comment by fbaligand** [comment] 2017-02-22 09:37
@jordansissel 
- Like you, I think second suggestion is more standard
- I think that Logstash grammar change is both dangerous and complex
- When I said "It's pretty easy to do", I think to just update the current env var injection mechanism so that it converts the value to an array when it's relevant.
- So, in my mind, I think `my_array=> "${LS_ARRAY}" ` will be replaced by `my_array=> ["value1", "value2"]`
- It would be coherent with number value replacement where `port => "${TCP_PORT}"` is replaced by `port => 12345`
- To do that :
  - I update [replace_env_placeholders method](https://github.com/elastic/logstash/blob/master/logstash-core/lib/logstash/config/mixin.rb#L163) behavior
  - I check if config type is an array (using `:validate` info), and if value starts with `${` and ends with `}`
  - If so, I convert the result value to an array using `String.split`
  - Special case : if result value is an empty string, I convert it to an empty array

What do you think about ?

**Comment by jordansissel** [comment] 2017-02-22 16:00
I would prefer not to have quoted strings behave in the way you describe.

**Comment by fbaligand** [comment] 2017-02-22 21:42
OK.
In that case, I don't know how to implement it.

**Comment by jordansissel** [comment] 2017-02-23 22:49
Indeed! I am in favor of the idea (environment variables as values in the
config), and I am confident we can find some way to implement it, even if
it means adding to the grammar :)

**Comment by fbaligand** [comment] 2017-02-25 19:02
OK.
In that case, good luck :)

**Comment by mavlyutov** [comment] 2017-07-18 11:00
hi!
any news on that?

**Comment by jordansissel** [comment] 2017-08-21 20:23
Duplicate of https://github.com/elastic/logstash/issues/6366. Let's bring future discussions there.

**Closed by jordansissel** 2017-08-21 20:23 UTC
