### ISSUE TITLE
Got error with elasticsearch output plugin logstash-1.5.0-1

### ISSUE THREAD

**Issue by jindov** [elastic/logstash#3272] opened 2015-05-19 08:25 UTC
This is my output.conf:

output {

```
statsd {
    host => "192.168.1.100"
    namespace => "log_services"
    increment => "%{logsource}.outputmsgpersec"
}

if [services] == "service1" {
    elasticsearch {
            cluster => "test"
            index => "service1-%{+YYYY.MM.dd}"
            host => "10.0.0.10"
            protocol => "http"
            template_name => "service1"
    }
    statsd {
            host => "192.168.1.100"
            namespace => "byte_counting"
            count => [ "body_bytes_sent", "%{body_bytes_sent}" ]
    }
```

   }

   if [services] == "service2" {
        elasticsearch {
                cluster => "test"
                index => "service2-%{+YYYY.MM.dd}"
                host => "10.0.0.10"
                protocol => "http"
                template_name => "service2"
        }
   }

   elasticsearch {
        cluster => "test"
        host => "10.0.0.10"
        protocol => "http"
   }
}

and this is error when running this config:

{:timestamp=>"2015-05-19T15:48:35.380000+0700", :message=>"retrying failed action with response code: 429", :level=>:warn}
{:timestamp=>"2015-05-19T15:48:46.379000+0700", :message=>"Got error to send bulk of actions to elasticsearch server at 118.69.73.194 : Read timed out", :level=>:error}
{:timestamp=>"2015-05-19T15:48:46.382000+0700", :message=>"Failed to flush outgoing items", :outgoing_count=>12, :exception=>#<Manticore::Timeout: Read timed out>, :backtrace=>["/opt/logstash/vendor/bundle/jruby/1.9/gems/manticore-0.4.1-java/lib/manticore/response.rb:35:in `initialize'", "org/jruby/RubyProc.java:271:in`call'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/manticore-0.4.1-java/lib/manticore/response.rb:61:in `call'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/manticore-0.4.1-java/lib/manticore/response.rb:225:in`call_once'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/manticore-0.4.1-java/lib/manticore/response.rb:128:in `code'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.7/lib/elasticsearch/transport/transport/http/manticore.rb:50:in`perform_request'", "org/jruby/RubyProc.java:271:in `call'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.7/lib/elasticsearch/transport/transport/base.rb:187:in`perform_request'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.7/lib/elasticsearch/transport/transport/http/manticore.rb:33:in `perform_request'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.7/lib/elasticsearch/transport/client.rb:115:in`perform_request'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-api-1.0.7/lib/elasticsearch/api/actions/bulk.rb:80:in `bulk'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-0.2.4-java/lib/logstash/outputs/elasticsearch/protocol.rb:100:in`bulk'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-0.2.4-java/lib/logstash/outputs/elasticsearch.rb:437:in `submit'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-0.2.4-java/lib/logstash/outputs/elasticsearch.rb:462:in`flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.19/lib/stud/buffer.rb:219:in `buffer_flush'", "org/jruby/RubyHash.java:1341:in`each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.19/lib/stud/buffer.rb:216:in `buffer_flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.19/lib/stud/buffer.rb:193:in`buffer_flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.19/lib/stud/buffer.rb:112:in `buffer_initialize'", "org/jruby/RubyKernel.java:1507:in`loop'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.19/lib/stud/buffer.rb:110:in `buffer_initialize'"], :level=>:warn}

**Comment by suyograo** [comment] 2015-05-26 16:09
@jindov is your ES cluster overloaded? How big is it and how many events are you sending to it? This usually happens when ES is busy and rejects indexing requests from LS.

**Comment by jindov** [comment] 2015-05-28 08:21
I used statsd to count how many mes/s, it's about 11k/s, my server is alway reach high loadavg: 20-30. Is that an error. How can I tuning my logstash agent?JAVA HEAP SIZE for every agent is 1500m

**Comment by german23** [comment] 2015-06-01 07:19
I also got a similar problem after upgrading to LS 1.5.0-1, the error message in the logstash log looks a bit different though:


{:timestamp=>"2015-05-30T10:21:18.656000+0200", :message=>"Got error to send bulk of actions to elasticsearch server at ES-Clusterip : Read timed out", :level=>:error}
{:timestamp=>"2015-05-30T10:21:18.656000+0200", :message=>"Failed to flush outgoing items", :outgoing_count=>7500, :exception=>#<Manticore::Timeout: Read timed out>, :backtrace=>["/opt/logstash/vendor/bundle/jruby/1.9/gems/manticore-0.4.1-java/lib/manticore/response.rb:35:in `initialize'", "org/jruby/RubyProc.java:271:in `call'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/manticore-0.4.1-java/lib/manticore/response.rb:61:in `call'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/manticore-0.4.1-java/lib/manticore/response.rb:225:in `call_once'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/manticore-0.4.1-java/lib/manticore/response.rb:128:in `code'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.7/lib/elasticsearch/transport/transport/http/manticore.rb:50:in `perform_request'", "org/jruby/RubyProc.java:271:in `call'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.7/lib/elasticsearch/transport/transport/base.rb:187:in `perform_request'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.7/lib/elasticsearch/transport/transport/http/manticore.rb:33:in `perform_request'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.7/lib/elasticsearch/transport/client.rb:115:in `perform_request'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-api-1.0.7/lib/elasticsearch/api/actions/bulk.rb:80:in `bulk'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-0.2.4-java/lib/logstash/outputs/elasticsearch/protocol.rb:100:in `bulk'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-0.2.4-java/lib/logstash/outputs/elasticsearch.rb:437:in `submit'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-0.2.4-java/lib/logstash/outputs/elasticsearch.rb:436:in `submit'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-0.2.4-java/lib/logstash/outputs/elasticsearch.rb:462:in `flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-0.2.4-java/lib/logstash/outputs/elasticsearch.rb:460:in `flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.19/lib/stud/buffer.rb:219:in `buffer_flush'", "org/jruby/RubyHash.java:1341:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.19/lib/stud/buffer.rb:216:in `buffer_flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.19/lib/stud/buffer.rb:193:in `buffer_flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.19/lib/stud/buffer.rb:159:in `buffer_receive'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-0.2.4-java/lib/logstash/outputs/elasticsearch.rb:426:in `receive'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0-java/lib/logstash/outputs/base.rb:88:in `handle'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0-java/lib/logstash/outputs/base.rb:79:in `worker_setup'"], :level=>:warn}


At the same time this message occurs at the ES-Server:

[2015-05-30 10:11:50,066][DEBUG][http.netty               ] [SSD] Caught exception while handling client http traffic, closing connection [id: 0x78d8bb21, /LS-ServerIP:38378 :> /ES-ClusterIP:9200]
java.nio.channels.ClosedChannelException
        at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.cleanUpWriteBuffer(AbstractNioWorker.java:433)
        at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.writeFromUserCode(AbstractNioWorker.java:128)
        at org.elasticsearch.common.netty.channel.socket.nio.NioServerSocketPipelineSink.handleAcceptedSocket(NioServerSocketPipelineSink.java:99)
        at org.elasticsearch.common.netty.channel.socket.nio.NioServerSocketPipelineSink.eventSunk(NioServerSocketPipelineSink.java:36)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendDownstream(DefaultChannelPipeline.java:779)
        at org.elasticsearch.common.netty.channel.Channels.write(Channels.java:725)
        at org.elasticsearch.common.netty.handler.codec.oneone.OneToOneEncoder.doEncode(OneToOneEncoder.java:71)
        at org.elasticsearch.common.netty.handler.codec.oneone.OneToOneEncoder.handleDownstream(OneToOneEncoder.java:59)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:591)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendDownstream(DefaultChannelPipeline.java:784)
        at org.elasticsearch.http.netty.pipelining.HttpPipeliningHandler.handleDownstream(HttpPipeliningHandler.java:87)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:591)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:582)
        at org.elasticsearch.http.netty.NettyHttpChannel.sendResponse(NettyHttpChannel.java:199)
        at org.elasticsearch.rest.action.support.RestResponseListener.processResponse(RestResponseListener.java:43)
        at org.elasticsearch.rest.action.support.RestActionListener.onResponse(RestActionListener.java:49)
        at org.elasticsearch.action.bulk.TransportBulkAction$2.finishHim(TransportBulkAction.java:360)
        at org.elasticsearch.action.bulk.TransportBulkAction$2.onResponse(TransportBulkAction.java:330)
        at org.elasticsearch.action.bulk.TransportBulkAction$2.onResponse(TransportBulkAction.java:323)
        at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction.performReplicas(TransportShardReplicationOperationAction.java:601)
        at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction.performOnPrimary(TransportShardReplicationOperationAction.java:516)
        at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction$1.run(TransportShardReplicationOperationAction.java:422)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)


I can confirm that at the time this error occurs, the ES-Cluster wasn´t overloaded, nether the BULK queue run full.

I downgraded to 1.4.2 to make the ELK-Stack up and runnig again but can upgrade any time if you need additional information (Note: I didnt post my LS-Config here because it´s quite big - there is nothing special in it, execpt some groks,dates and mutate commands)

Cheers

**Comment by jsvd** [comment] 2015-06-01 08:59
@german23 the logstash-output-elasticsearch plugin has been updated to 0.2.7 so if you can please try 1.5.0 again, but before update the plugin with:

`bin/plugin update logstash-output-elasticsearch`

**Comment by german23** [comment] 2015-06-02 09:39
@jvsd i upgraded again and updated the es-output plugin.

It works fine at the moment, but i am not sure if the problem is solved until it runs in production mode for a few days.

Im gonna keep you informed if the problems appear again

**Comment by german23** [comment] 2015-06-15 05:31
Hi again,

i have tested logstash 1.5.0 with the updated es-output plugin for about 2 weeks and no problems occured during this time(also the performance was great compared to 1.4 ).

The issue can be closed

**Comment by suyograo** [comment] 2015-06-15 06:03
@german23 thanks. Any numbers on performance compared to 1.4?

**Comment by german23** [comment] 2015-06-16 05:31
Looked at the average CPU load over 2 weeks, its 15% lower than with 1.5.
While parsing mostly Windows Eventlogs with json input and mostly grok/mutate filters, the maximum throughput we expected increased from 6000 events/s to 10000 events/s.

**Comment by suyograo** [comment] 2017-02-17 17:42
Closing this issue since it has been open for a long time and we haven't received the details to debug it further. Please reopen a new issue if you still run into issues

**Closed by suyograo** 2017-02-17 17:42 UTC
Labels: question
