### ISSUE TITLE
Non deterministic test for JVMMemoryCommand

### ISSUE THREAD

**Issue by ph** [elastic/logstash#5165] opened 2016-04-21 18:24 UTC
```
    #schema
      return hot threads information
      return heap information
      return non heap information (FAILED - 1)

Failures:

  1) JVM stats LogStash::Api::JvmMemoryCommand#schema return non heap information
     Failure/Error: do_request { subject.run }
     NoMethodError:
       undefined method `[]' for nil:NilClass
     # ./logstash-core/lib/logstash/api/lib/app/commands/stats/memory_command.rb:9:in `run'
     # ./logstash-core/spec/api/lib/commands/jvm_spec.rb:28:in `report'
     # ./logstash-core/spec/api/spec_helper.rb:90:in `do_request'
     # ./logstash-core/spec/api/lib/commands/jvm_spec.rb:28:in `report'
     # ./logstash-core/spec/api/lib/commands/jvm_spec.rb:40:in `(root)'
     # ./vendor/bundle/jruby/1.9/gems/rspec-wait-0.0.8/lib/rspec/wait.rb:46:in `(root)'
     # ./rakelib/test.rake:47:in `(root)'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.1.2/lib/rake/task.rb:248:in `execute'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.1.2/lib/rake/task.rb:243:in `execute'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.1.2/lib/rake/task.rb:187:in `invoke_with_call_chain'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.1.2/lib/rake/task.rb:180:in `invoke_with_call_chain'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.1.2/lib/rake/task.rb:173:in `invoke'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.1.2/lib/rake/application.rb:150:in `invoke_task'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.1.2/lib/rake/application.rb:106:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.1.2/lib/rake/application.rb:106:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.1.2/lib/rake/application.rb:115:in `run_with_threads'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.1.2/lib/rake/application.rb:100:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.1.2/lib/rake/application.rb:78:in `run'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.1.2/lib/rake/application.rb:176:in `standard_exception_handling'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.1.2/lib/rake/application.rb:75:in `run'

Finished in 9.63 seconds (files took 3.4 seconds to load)
141 examples, 1 failure

Failed examples:

rspec ./logstash-core/spec/api/lib/commands/jvm_spec.rb:39 # JVM stats LogStash::Api::JvmMemoryCommand#schema return non heap information

Randomized with seed 32646
```

**Comment by ph** [comment] 2016-04-21 18:24
in ~100 runs, first time I got this one.

**Comment by purbon** [comment] 2016-04-30 12:20
closing this as duplicate of #5161, source of the error is the same.

**Closed by purbon** 2016-04-30 12:20 UTC
Labels: tests
