### ISSUE TITLE
Performance regression in basic json handling

### ISSUE THREAD

**Issue by purbon** [elastic/logstash#3589] opened 2015-07-10 09:35 UTC
From the performance regression test introduced thanks to https://github.com/elastic/logstash-performance-testing I noticed that the general performance of JSON handling is slowing down, the most critical one seems to be for the ```json_lines``` codec, where 1.4.2 is actually a lot faster than recent versions.

![screen shot 2015-07-10 at 11 33 20](https://cloud.githubusercontent.com/assets/68540/8616018/27801902-26f8-11e5-98ab-89aaf775c57c.png)
![screen shot 2015-07-10 at 11 34 00](https://cloud.githubusercontent.com/assets/68540/8616017/277cf600-26f8-11e5-8e87-b101e2752951.png)

details about the legends can be seen in the screenshots. Feel free to ping me for more details if necessary.

**Comment by colinsurprenant** [comment] 2015-07-10 18:41
So I understand, what happen on 2015-07-06 for the hike in performance? we changed hardware? obviously only the relative numbers across versions are interesting but just so I know...

**Comment by colinsurprenant** [comment] 2015-07-10 21:42
A few observations. I ran a few *manual* benchmarks to validate this. 

1-  Note that the output of the `pv` command reads like this:
```
duration [last second TPS] [average TPS] 
```
so the meaningful number to read is the average TPS.

2- using `filter{clone{}}` in the config is essentially a filter pass-thru, where the filter function is called but no computation is actually done (clone has nothing to clone and just outputs the original event).

3- I tested 2 versions for each branch: the original and untouched and a "stripped" Event class where I modified the `.to_json` method to return a hardcoded "{}" string to bypass json serialization, I removed the Timestamp initialization and I removed the metadata handling. Obviously the stripped version will be faster.
 
#### master
```sh
yes 'test 01' |  bin/logstash -e 'input{stdin{}} filter{clone{}} output{stdout{codec => json_lines}}' | pv -Wlart > /dev/null
01:00 [35.1k/s] [34.4k/s]
```

#### master + stripped event
```sh
yes 'test 01' |  bin/logstash -e 'input{stdin{}} filter{clone{}} output{stdout{codec => json_lines}}' | pv -Wlart > /dev/null
01:00 [ 104k/s] [ 105k/s]
```

#### 1.4.2
```sh
yes 'test 01' | bin/logstash -e 'input{stdin{}} filter{clone{}} output{stdout{codec => json_lines}}' | pv -Wlart > /dev/null
01:01 [51.4k/s] [51.6k/s]
```

#### 1.4.2 + stripped event
```sh
yes 'test 01' | bin/logstash -e 'input{stdin{}} filter{clone{}} output{stdout{codec => json_lines}}' | pv -Wlart > /dev/null
01:02 [ 138k/s] [ 135k/s]
```

---

branch | no change | stripped | % increase
---|---|---|---
master | 34.4k/s | 105k/s | 205%
1.4.2 | 51.6k/s | 135k/s | 162%
% increase | 50% | 29% |

Unless I am misreading this, it tells me is that json serialization is **not** the main cause for the performance regression in this simple scenario. I ran a few quick profiling sessions and *I think* it is related to the new filter & output functions compilation, and it was performing better in 1.4.2 because it was actually buggy and not correctly handing conditionals etc. (I am not saying we should not try to see if we can further optimize)

We also have to keep in mind that this config scenario, especially the stripped version, essentially test a do-nothing pipeline so what we see here is the base pipeline latency but as soon as we add any kind of  non pass-thru filters or outputs, conditionals, the base latency will become somewhat irrelevant and master actually performs better.

**Comment by purbon** [comment] 2015-07-13 08:48
@colinsurprenant the spike you see is a hardware change, yes. since then it has been running in the same machine.

**Comment by purbon** [comment] 2015-07-13 08:58
@colinsurprenant I apologies if the question sounds stupid, if like this please feel free to educate me.  Let me know if makes sense, i understand you say this 30% slow down is because of the very same pipeline, right? might be we should do a bit of work to understand if we can speed this up a bit, isn't? I found kinda interesting the bare pipeline is nowadays 30% slower.

**Comment by colinsurprenant** [comment] 2015-07-13 12:37
@purbon not sure I understand your question. In my last comment above I said:

> and I think it is related to the new filter & output functions compilation, and it was performing better in 1.4.2 because it was actually buggy and not correctly handing conditionals etc.»

In other words, I think it is slower because it has to do more to actually perform conditionals correctly. 
I also said:

> (I am not saying we should not try to see if we can further optimize)

In other words, sure, we should probably analyse this to make sure we understand the cause
BUT I also said:

> this config scenario [...]  what we see here is the base pipeline latency but as soon as we add any kind of non pass-thru filters or outputs, conditionals, the base latency will become somewhat irrelevant and master actually performs better.

In other words, I think this is probably a red herring and this particular performance regression is not very relevant to the overall performance when run with a *real* config.

These are more-or-less unsubstantiated educated guesses. I might be wrong and more work would be necessary to confirm for sure but I am not too-too worried since all other performance benchmarks with non-trivial configs indicates a good margin of improvement for 1.5.x.

**Comment by purbon** [comment] 2015-07-13 12:41
Ok, thanks for clarifying your point.

**Comment by colinsurprenant** [comment] 2015-07-13 20:38
I think I finally got to the bottom of this. Two modifications are affecting base performance:
- the addition of the check in the stdin input for the `!event.include?("host")` in https://github.com/logstash-plugins/logstash-input-stdin/blob/master/lib/logstash/inputs/stdin.rb#L34 
- the decorate refactor using the Decorator class in https://github.com/elastic/logstash/blob/master/lib/logstash/inputs/base.rb#L113-L114

more benchmarks:

- reverting these changes in master and removing the filter:

#### master + stripped event + reverted changes + no filter
```sh
yes 'test 01' |  bin/logstash -e 'input{stdin{}}  output{stdout{codec => json_lines}}' | pv -Wlart > /dev/null
01:01 [ 212k/s] [ 190k/s]
```

#### 1.4.2 + stripped event + no filter
```sh
yes 'test 01' | bin/logstash -e 'input{stdin{}}  output{stdout{codec => json_lines}}' | pv -Wlart > /dev/null
01:02 [ 184k/s] [ 175k/s]
```

- adding back the filter:

#### master + stripped event + reverted changes
```sh
yes 'test 01' |  bin/logstash -e 'input{stdin{}} filter{clone{}} output{stdout{codec => json_lines}}' | pv -Wlart > /dev/null
01:02 [ 130k/s] [ 137k/s]
```

#### 1.4.2 + stripped event
```sh
yes 'test 01' | bin/logstash -e 'input{stdin{}} filter{clone{}} output{stdout{codec => json_lines}}' | pv -Wlart > /dev/null
01:02 [ 138k/s] [ 133k/s]
```

We see that these 2 changes are affecting the *very bare* pipeline without filters throughput for this config. We also see that adding back filters reduces the differences caused by these 2 changes and master is just slightly faster.

**Comment by colinsurprenant** [comment] 2015-07-13 20:44
Let's add back json serializing.

#### master + stripped event(with json) + reverted changes
```sh
yes 'test 01' |  bin/logstash -e 'input{stdin{}} filter{clone{}} output{stdout{codec => json_lines}}' | pv -Wlart > /dev/null
01:02 [38.6k/s] [35.5k/s]
```

#### 1.4.2 + stripped event(with json)
```sh
yes 'test 01' | bin/logstash -e 'input{stdin{}} filter{clone{}} output{stdout{codec => json_lines}}' | pv -Wlart > /dev/null
01:00 [46.7k/s] [48.6k/s]
```

This last bench shows that 1- json serialization is the most costly operation and 2- json serialization performance has regressed from 1.4.2. This test deals with very small documents and I remember that the JrJackson refactor initial tests did show interesting improvements particularly with larger documents. 

Now **the interesting bench**, when using back the most recent stdin input and the base input with new Decorator class and with proper json serialization:

#### master + stripped event(with json)
```sh
yes 'test 01' |  bin/logstash -e 'input{stdin{}} filter{clone{}} output{stdout{codec => json_lines}}' | pv -Wlart > /dev/null
01:01 [42.4k/s] [36.5k/s]
```

#### 1.4.2 + stripped event(with json)
```sh
es 'test 01' | bin/logstash -e 'input{stdin{}} filter{clone{}} output{stdout{codec => json_lines}}' | pv -Wlart > /dev/null
01:01 [49.8k/s] [47.6k/s]
```

We see that these 2 "reverted changes" become irrelevant related to the cost of performing json serialization. 

## Conclusion

After these tests I am more confident in saying that: 

1- in these tests the main processing cost is the json serialization and there is in fact a performance regression in 1.5.x from 1.4.2 serializing small documents.

2- the 2 other performance regressions identified above (stdin input host check and the base input Decorator class) become irrelevant in the context of other **more costly** processing like json serialization.

**Comment by guyboertje** [comment] 2015-07-21 14:02
I did similar tests.

In `vendor/bundle/jruby/1.9/gems/` I deleted the jrjackson-0.2.9 folder and symlinked it to my local jrjackson folder

I then modified json.rb like so
```ruby
def jruby_dump(o)
  # test for enumerable here to work around an omission in JrJackson::Json.dump to
  # also look for Java::JavaUtil::ArrayList, see TODO submit issue
  
  if JrJackson::BuildInfo.version == '0.3.0'
    JrJackson::Base.generate(o)
  else
    o.is_a?(Enumerable) ? JrJackson::Raw.generate(o) : JrJackson::Json.dump(o)
  end

  # '{"message"=>"test 01", "@version"=>"1", "@timestamp"=>"'.concat(Time.now.to_s).concat('", "host"=>"Elastics-MBP"}')

rescue => e
  raise LogStash::Json::GeneratorError.new(e.message)
end
```
This allowed me to checkout master or the new 9000 branch on my JrJackson repo.

JrJackson -> master
```sh
guy at Elastics-MBP in ~/elastic/logstash on master*
$ yes 'test 01' |  bin/logstash -e 'input{stdin{}} filter{clone{}} output{stdout{codec => json_lines}}' | pv -Wlart > /dev/null
01:00 [53.8k/s] [53.3k/s]
```

JrJackson -> 9000
```sh
guy at Elastics-MBP in ~/elastic/logstash on master*
$ yes 'test 01' |  bin/logstash -e 'input{stdin{}} filter{clone{}} output{stdout{codec => json_lines}}' | pv -Wlart > /dev/null
01:00 [60.8k/s] [63.6k/s]
```

JrJackson -> null (comment code and uncomment canned string return value)
```sh
guy at Elastics-MBP in ~/elastic/logstash on master*
$ yes 'test 01' |  bin/logstash -e 'input{stdin{}} filter{clone{}} output{stdout{codec => json_lines}}' | pv -Wlart > /dev/null
01:00 [ 124k/s] [ 123k/s]
```

Conclusion:
-  Timings on my MBP are not comparable to @colinsurprenant machine.
-  The new JrJackson code should provide a significant improvement
-  Normally JSON parsers have to deal with extremely varying object contents but given that we are working with a small subset of Event contents, I wonder whether some form of canned string with interpolation can be leveraged, i.e. like ERB templates.

**Comment by guyboertje** [comment] 2015-07-22 00:57
After some more experimentation:

- String interpolation on the Ruby side is fastest, perhaps because the JRuby code for this is optimised.
- String construction on the Java side is a bit slower, I'm guessing the overhead lies in the conversion of a Java string into a RubyString (ByteList and UTF8 encoding).
- The new JrJackson generate code is pretty close to optimal in terms of JSON string generation.
- We need a faster way of building RubyStrings from Java.

**Comment by guyboertje** [comment] 2015-10-02 11:12
See #3702

**Comment by colinsurprenant** [comment] 2016-01-13 21:36
we can now close this issue, we are way beyond the 1.5 codebase for serialization and such, this is pretty much irrelevant now.

**Closed by colinsurprenant** 2016-01-13 21:36 UTC
Labels: bug, performance-regression
