### ISSUE TITLE
Logstash problem: message=>"Failed to flush outgoing items",<Errno::EBADF: Bad file descriptor - Bad file descriptor>

### ISSUE THREAD

**Issue by nadalie** [elastic/logstash#2241] opened 2014-12-15 11:25 UTC
Since a couple of months ago, I'm experiencing problem with logstash, in the logs I have several error like the following: 

```
{:timestamp=>"2014-12-15T10:30:25.482000-0700", :message=>"Failed to flush outgoing items", :outgoing_count=>252, :exception=>#<Errno::EBADF: Bad file descriptor - Bad file descriptor>, :backtrace=>["org/jruby/RubyIO.java:2097:in `close'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/ftw-0.0.39/lib/ftw/connection.rb:173:in `connect'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/ftw-0.0.39/lib/ftw/connection.rb:168:in `connect'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/ftw-0.0.39/lib/ftw/connection.rb:156:in `connect'", "org/jruby/RubyArray.java:1613:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/ftw-0.0.39/lib/ftw/connection.rb:139:in `connect'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/ftw-0.0.39/lib/ftw/agent.rb:406:in `connect'", "org/jruby/RubyProc.java:271:in `call'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/ftw-0.0.39/lib/ftw/pool.rb:48:in `fetch'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/ftw-0.0.39/lib/ftw/agent.rb:403:in `connect'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/ftw-0.0.39/lib/ftw/agent.rb:319:in `execute'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/ftw-0.0.39/lib/ftw/agent.rb:217:in `post!'", "/opt/logstash/lib/logstash/outputs/elasticsearch/protocol.rb:106:in `bulk_ftw'", "/opt/logstash/lib/logstash/outputs/elasticsearch/protocol.rb:80:in `bulk'", "/opt/logstash/lib/logstash/outputs/elasticsearch.rb:315:in `flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.17/lib/stud/buffer.rb:219:in `buffer_flush'", "org/jruby/RubyHash.java:1339:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.17/lib/stud/buffer.rb:216:in `buffer_flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.17/lib/stud/buffer.rb:193:in `buffer_flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.17/lib/stud/buffer.rb:112:in `buffer_initialize'", "org/jruby/RubyKernel.java:1521:in `loop'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.17/lib/stud/buffer.rb:110:in `buffer_initialize'"], :level=>:warn}
```

I have ElasticSearch 1.1.1 and Logstash 1.4.2, and the configuration for logstash is like this:

```
input {
    udp {
        type => "udp"
        port => 30000
    }
}

filter {
   if [type] == "udp" {
      mutate {
        rename => ["@host", "host"]
      }
      dns {
         reverse => ["host"]
         action => "replace"
      }
      grok {
          patterns_dir => "/etc/logstash/patterns"
          match => ["message", "%{OLD_MESSAGE}",
                    "message", "%{NEW_MESSAGE}"
                   ]
      }
   }
}

output {
    elasticsearch {
        protocol => "http"
        cluster => "logstash"
        host => "127.0.0.1"
        index => "logstash-syslog-%{+YYYY.MM.dd}"
    }

}
```

What is wrong? Is there any bug in Logstash? Should I upgrade it?

Thanks in advance/

**Comment by nadalie** [comment] 2015-01-06 16:01
Sorry for not answering before, I was out for holidays.
The maximun number of file descriptors is set to 64k:
I have already set to the maximum (to 64k):

      "process" : {
        "refresh_interval" : 1000,
        "id" : 862,
        "max_file_descriptors" : 65535,
        "mlockall" : false
      }
And for the logstash process is set to maximum 10000 open files in /etc/security/limits.conf.
Even though, I'm not logging so many data so this limit should not be reached, the maximum is 15.000 messages in a day, so even the connection needs time to close it, it shouldn't be a problem.

I'm running on Linux and I'm thinking that maybe this is happening because running out of RAM memory. My server has only 3gigas of RAM but only 256 megas assigned to ES, my ES configuration is 5 shards and creating a index per day and keeping just the latest 30 indexes.
Could it be this?

**Comment by vasekch** [comment] 2015-01-07 12:03
I had issue with very same symptoms. I'm running the same versions of LS and ES as described, I have it in containers with lot of resources.

My issue was that output -> elasticsearch -> host was set to just hostname "es1" and my search domain in resolv.conf was in wrong order, so I got public IP, where is forbidden to access elasticsearch port 9200. I provided FQDN (or just IP) and everything started to work.

@nadalie this is not obviously your case, but I suggest to doublecheck that your ES is accessible from where logstash is running and there is no obstruction on the port. Something like ```telnet 127.0.0.1 9200```

**Comment by nadalie** [comment] 2015-01-07 14:01
@vasekch I'm running both in the same machine so I'm able to connect to the ES port is accesible from logstash, thanks!

**Comment by msheiny** [comment] 2015-02-11 14:50
I just came across this issue and similar to what @vasekch mentioned, it turned out to be networking stack related to ES. I am also running a non-data ES node on the same logstash box - turns out an iptables change I made forgot to allow an exception for localhost traffic. I was able to do a curl against the localhost ES server before I put in the iptables fix which initially threw me off.

**Comment by nadalie** [comment] 2015-02-13 15:18
What do you mean that is a networking stack problem? I didn't change anything from iptables(in fact, I allow connections from 9200 "-A INPUT -m state --state NEW -m tcp -p tcp --dport 9200 -j ACCEPT
" ). I cannot understand that without changing anything in the configuration and so on, I suddenly experiencing problems.

**Comment by vasekch** [comment] 2015-02-13 15:45
@nadalie: in my case I had error message every time, if I'm getting you correctly you only have this message in logs time to time.
If you have firewall on and can not turn it off to test it, I would suggest to review your DoS preventing rules (req/s etc), maybe they come to play when you don't expect it.
And yes, it's most probably network stack problem AFAIK.

**Comment by untergeek** [comment] 2015-02-13 16:09
I can confirm that the `Errno::EBADF: Bad file descriptor` message _can_ occur when a remote port is inaccessible or disconnects in-flight.

**Comment by evgygor** [comment] 2015-03-25 14:39
Same exception as in issue #2896 but in output ti influxdb

**Comment by fizerkhan** [comment] 2015-05-03 17:59
+1

**Comment by nadalie** [comment] 2015-05-04 08:50
I still have the problem, but I don't see it's a problem of the remote ports is not available. It just happen after couple of months running without problems, and there is not a network disconnection. I don't have firewall.

**Comment by albarki** [comment] 2015-05-11 19:20
i have the same error, i have two instance of logstash one used as indexer and read from redis server and other is shipper and forward to redis
the logstash indexer which reads from the redis always has this error in the logs after some time

**Comment by sdembra** [comment] 2015-07-06 10:58
I had same message in the logs. It was due to too many CLOSE_WAIT connections on logstash port.
On cleanup of these connections, the error was gone. 

Hope this helps someone.

**Comment by albarki** [comment] 2015-08-07 13:44
my issue is resolved by making a cron job to restart the logstash instance that reads from redis-server each 6 hours and it works now perfectly

**Comment by projx** [comment] 2015-10-30 21:05
Thank you!

I had the same issue with Logstash 2.0 Final on Ubuntu, turned out to be caused by the local firewall (UFW), calling "ufw disable" appears to have fixed this.

**Comment by sammcj** [comment] 2016-01-06 20:51
We have this problem whenever the upstream elasticsearch or load balancer for the logstash output is temporarily unavailable, from that point on logstash fails to process any logs and they go to abyss until the process is restarted.

**Comment by jordansissel** [comment] 2016-01-06 22:30
What version of logstash and what version of the logstash-output-elasticsearch plugin?

**Comment by arivazhagan-jeganathan** [comment] 2016-03-07 11:24
@sdembra  How are you managing clean up of connections in CLOSE_WAIT? Please shed some light. I am on the same issue.

**Comment by sdembra** [comment] 2016-03-10 04:37
I just restart logstash process when there are too many CLOSE_WAIT
connections.

One more reason behind getting too many CLOSE_WAIT connections can be
elasticsearch
going out of memory.

In that case, you will have to increase memory for ES.

Another thing you can do, if you are using a multi node ES cluster, is to
set
appropriate parameters in elasticsearch.yml file:


*discovery.zen.minimum_master_nodes: (number of master-eligible nodes / 2)
+ 1*
*discovery.zen.ping.timeout: 30s.*

*Default ping timeout is 3s.*

Hope this helps.

**Comment by arivazhagan-jeganathan** [comment] 2016-03-10 04:45
@sdembra  Thank you for the info. We made some configuration changes in logstash output configuration for elasticsearch and it works good.
We added flush_size of 500 and idle_flush_time of 5 seconds. Earlier connections went to CLOSE_WAIT without these configuration. Now its fine.

**Comment by untergeek** [comment] 2016-03-11 16:44
So this isn't a bug _per se,_ but perhaps we could catch this exception and return a more descriptive error message in the log.  This may be beneficially informational in cases where Logstash is at the mercy of the remote service.

Added the "logging improvements" label.

**Comment by sbarvick** [comment] 2016-11-17 21:33
I found that this issue was the same as [https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/127] resolved by proper output configuration described in [https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/127#issuecomment-261374678]

**Comment by nealshan2** [comment] 2016-11-29 07:51
I ask our admin to restart the server and issue was solved. 
ES was started and logstash was started, while send bulk request, ES was killed by some reason, maybe OOM(out of memory).

**Comment by untergeek** [comment] 2017-01-06 20:07
Since this is primarily an issue in the Elasticsearch output plugin, this is being migrated to https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/542

**Closed by untergeek** 2017-01-06 20:07 UTC
Labels: logging improvements, needs details
