### ISSUE TITLE
Non gracefull way of handling closed indices

### ISSUE THREAD

**Issue by plarivee** [elastic/logstash#2922] opened 2015-03-30 18:03 UTC
I had my indexers jam because of closed indices and logstash trying to insert stuff into them.
```
{:timestamp=>"2015-03-29T06:25:03.855000-0400", :message=>"Failed to flush outgoing items", :outgoing_count=>1, :exception=>org.elasticsearch.indices.IndexMissingException: [logstash-staging-2014.03.27] missing, :backtrace=>["org.elasticsearch.cluster.routing.operation.plain.PlainOperationRouting.indexRoutingTable(org/elasticsearch/cluster/routing/operation/plain/PlainOperationRouting.java:244)", "org.elasticsearch.cluster.routing.operation.plain.PlainOperationRouting.shards(org/elasticsearch/cluster/routing/operation/plain/PlainOperationRouting.java:258)", "org.elasticsearch.cluster.routing.operation.plain.PlainOperationRouting.shards(org/elasticsearch/cluster/routing/operation/plain/PlainOperationRouting.java:254)", "org.elasticsearch.cluster.routing.operation.plain.PlainOperationRouting.indexShards(org/elasticsearch/cluster/routing/operation/plain/PlainOperationRouting.java:70)", "org.elasticsearch.action.bulk.TransportBulkAction.executeBulk(org/elasticsearch/action/bulk/TransportBulkAction.java:238)", "org.elasticsearch.action.bulk.TransportBulkAction.doExecute(org/elasticsearch/action/bulk/TransportBulkAction.java:149)", "org.elasticsearch.action.bulk.TransportBulkAction.doExecute(org/elasticsearch/action/bulk/TransportBulkAction.java:65)", "org.elasticsearch.action.support.TransportAction.execute(org/elasticsearch/action/support/TransportAction.java:63)", "org.elasticsearch.client.node.NodeClient.execute(org/elasticsearch/client/node/NodeClient.java:92)", "org.elasticsearch.client.support.AbstractClient.bulk(org/elasticsearch/client/support/AbstractClient.java:147)", "org.elasticsearch.action.bulk.BulkRequestBuilder.doExecute(org/elasticsearch/action/bulk/BulkRequestBuilder.java:165)", "org.elasticsearch.action.ActionRequestBuilder.execute(org/elasticsearch/action/ActionRequestBuilder.java:85)", "org.elasticsearch.action.ActionRequestBuilder.execute(org/elasticsearch/action/ActionRequestBuilder.java:59)", "java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:606)", "LogStash::Outputs::Elasticsearch::Protocols::NodeClient.bulk(/opt/logstash/lib/logstash/outputs/elasticsearch/protocol.rb:207)", "LogStash::Outputs::Elasticsearch::Protocols::NodeClient.bulk(/opt/logstash/lib/logstash/outputs/elasticsearch/protocol.rb:207)", "LogStash::Outputs::ElasticSearch.flush(/opt/logstash/lib/logstash/outputs/elasticsearch.rb:315)", "LogStash::Outputs::ElasticSearch.flush(/opt/logstash/lib/logstash/outputs/elasticsearch.rb:315)", "Stud::Buffer.buffer_flush(/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.17/lib/stud/buffer.rb:219)", "Stud::Buffer.buffer_flush(/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.17/lib/stud/buffer.rb:219)", "org.jruby.RubyHash.each(org/jruby/RubyHash.java:1339)", "Stud::Buffer.buffer_flush(/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.17/lib/stud/buffer.rb:216)", "Stud::Buffer.buffer_flush(/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.17/lib/stud/buffer.rb:216)", "Stud::Buffer.buffer_flush(/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.17/lib/stud/buffer.rb:193)", "Stud::Buffer.buffer_flush(/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.17/lib/stud/buffer.rb:193)", "Stud::Buffer.buffer_receive(/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.17/lib/stud/buffer.rb:159)", "Stud::Buffer.buffer_receive(/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.17/lib/stud/buffer.rb:159)", "LogStash::Outputs::ElasticSearch.receive(/opt/logstash/lib/logstash/outputs/elasticsearch.rb:311)", "LogStash::Outputs::ElasticSearch.receive(/opt/logstash/lib/logstash/outputs/elasticsearch.rb:311)", "LogStash::Outputs::Base.handle(/opt/logstash/lib/logstash/outputs/base.rb:86)", "LogStash::Outputs::Base.handle(/opt/logstash/lib/logstash/outputs/base.rb:86)", "RUBY.initialize((eval):645)", "org.jruby.RubyProc.call(org/jruby/RubyProc.java:271)", "LogStash::Pipeline.output(/opt/logstash/lib/logstash/pipeline.rb:266)", "LogStash::Pipeline.output(/opt/logstash/lib/logstash/pipeline.rb:266)", "RUBY.outputworker(/opt/logstash/lib/logstash/pipeline.rb:225)", "RUBY.start_outputs(/opt/logstash/lib/logstash/pipeline.rb:152)", "java.lang.Thread.run(java/lang/Thread.java:744)"], :level=>:warn}
```

that caused that no logs was going to ES during that time. There should be a way to either remove those logs or send them to a file or anything that could work.

**Comment by untergeek** [comment] 2015-03-30 18:28
Thanks for contributing!  We are aware of this, and a way around is in the future.  

This ticket is effectively a duplicate of #2607 

Closing in favor of that one.

**Closed by untergeek** 2015-03-30 18:28 UTC
Labels: enhancement, feature, resiliency
