### ISSUE TITLE
Hot Threads failure in Travis CI

### ISSUE THREAD

**Issue by andrewvc** [elastic/logstash#5135] opened 2016-04-18 20:20 UTC
Using our new [Travis CI branch](https://github.com/elastic/logstash/pull/4608) we sometimes get [this odd failure](https://travis-ci.org/elastic/logstash/builds/124009233).

This seems like an intermittently failing test we'll have to look into.

@purbon do you understand what's going on here?

**Comment by purbon** [comment] 2016-04-19 14:44
This is odd, never saw something like this, I will investigate and report
here. thanks for the reporting and sorry for the inconveniences.

- purbon

**Comment by purbon** [comment] 2016-04-30 12:26
related to #5161

not closing this as the error is different as the ones received in related issues, here the errors description is:

```
.....................................................................F
Failures:
  1) JVM stats LogStash::Api::HotThreadsCommand#schema return hot threads information
     Failure/Error: Unable to find matching line from backtrace
     Java::JavaLang::IllegalArgumentException:
       Comparison method violates its general contract!
     # java.util.TimSort.mergeLo(TimSort.java:773)
     # java.util.TimSort.mergeAt(TimSort.java:510)
     # java.util.TimSort.mergeCollapse(TimSort.java:437)
     # java.util.TimSort.sort(TimSort.java:241)
     # java.util.Arrays.sort(Arrays.java:1512)
     # java.util.ArrayList.sort(ArrayList.java:1454)
     # java.util.Collections.sort(Collections.java:175)
     # com.purbon.jrmonitor.monitors.HotThreadsMonitor.sort(HotThreadsMonitor.java:158)
     # com.purbon.jrmonitor.monitors.HotThreadsMonitor.detect(HotThreadsMonitor.java:154)
     # com.purbon.jrmonitor.reports.RubyThreadsReport.generate(RubyThreadsReport.java:41)
     # com.purbon.jrmonitor.reports.RubyThreadsReport$INVOKER$s$generate.call(RubyThreadsReport$INVOKER$s$generate.gen)
```

however source of issue might be related.

**Comment by suyograo** [comment] 2016-05-16 22:40
Caused by #5161

**Closed by suyograo** 2016-05-16 22:40 UTC
Labels: bug, tests
