### ISSUE TITLE
Java execution conditionals doesn't find @metadata

### ISSUE THREAD

**Issue by simmel** [elastic/logstash#9296] opened 2018-03-28 10:12 UTC
- Version: 6.x branch commit b952767de42f6cdaa5740b344c18b8eba1b54c1a
- Operating System: OS X and Debian stretch
- Config File (if you have sensitive info, please remove it):
```
input {
  stdin {
  }
}

filter {
  metrics {
    meter => "[@metadata][events]"
      flush_interval => 60
      add_tag => ["graph"]
  }

  if [@metadata][events][count] {
    mutate {
      add_field => {
        "logsource" => "this should only happen when [@metadata][events][count] exists"
      }
    }
  }
}

output {
  stdout {
    codec => rubydebug {
      metadata => true
    }
  }
}
```
- Sample Data: anything will do
- Steps to Reproduce:
With Ruby exec everything works as expected
With Java Exec the field `logsource` gets added even though `[@metadata][events][count]` doesn't exist. Something with conditionals and `@metadata` is broken with Java Exec.

Paging @original-brownbear = )

**Comment by original-brownbear** [comment] 2018-03-28 10:24
@simmel thanks :) taking a look

**Comment by original-brownbear** [comment] 2018-03-28 10:33
jup reproduced :) => fixing

**Comment by original-brownbear** [comment] 2018-03-28 10:37
@andrewvc seems this one is a problem with the `PipelineIR`, this is the `Graph` that hits the compiler here:

```
**GRAPH**
Vertices: 6 Edges: 6
----------------------P[input-stdin{}|[str]pipeline:2:3:```
stdin {
  }
```] -> __QUEUE__
__QUEUE__ -> P[filter-metrics{"meter"=>"[@metadata][events]", "flush_interval"=>60, "add_tag"=>["graph"]}|[str]pipeline:7:3:```
metrics {
    meter => "[@metadata][events]"
      flush_interval => 60
      add_tag => ["graph"]
  }
```]
P[filter-metrics{"meter"=>"[@metadata][events]", "flush_interval"=>60, "add_tag"=>["graph"]}|[str]pipeline:7:3:```
metrics {
    meter => "[@metadata][events]"
      flush_interval => 60
      add_tag => ["graph"]
  }
```] -> [if (event.get('[@metadata]'))]
[if (event.get('[@metadata]'))] -|true|-> P[filter-mutate{"add_field"=>{"logsource"=>"this should only happen when [@metadata][events][count] exists"}}|[str]pipeline:14:5:```
mutate {
      add_field => {
        "logsource" => "this should only happen when [@metadata][events][count] exists"
      }
    }
```]
[if (event.get('[@metadata]'))] -|false|-> P[output-stdout{"codec"=>#<Java::OrgLogstashConfigIrImperative::PluginStatement:0x21e84c9d>}|[str]pipeline:23:3:```
stdout {
    codec => rubydebug {
      metadata => true
    }
  }
```]
P[filter-mutate{"add_field"=>{"logsource"=>"this should only happen when [@metadata][events][count] exists"}}|[str]pipeline:14:5:```
mutate {
      add_field => {
        "logsource" => "this should only happen when [@metadata][events][count] exists"
      }
    }
```] -> P[output-stdout{"codec"=>#<Java::OrgLogstashConfigIrImperative::PluginStatement:0x21e84c9d>}|[str]pipeline:23:3:```
stdout {
    codec => rubydebug {
      metadata => true
    }
  }
```]
**GRAPH**
```

should be easy to track down :)

**Comment by original-brownbear** [comment] 2018-03-28 10:41
urgh the problem is on the Ruby (Treetop) side :)

<img width="1494" alt="screen shot 2018-03-28 at 12 41 08" src="https://user-images.githubusercontent.com/6490959/38024452-56544f96-3285-11e8-98cd-6259b4b305de.png">

**Comment by original-brownbear** [comment] 2018-03-28 12:06
fixed in `master` and `6.x` via https://github.com/elastic/logstash/pull/9297 :)

**Closed by original-brownbear** 2018-03-28 12:06 UTC
Labels: bug

**Comment by simmel** [comment] 2018-03-28 14:44
👌 Relates to #9226
