### ISSUE TITLE
Need help in writing grok pattern for network log.

### ISSUE THREAD

**Issue by chandanchilakamudi** [elastic/logstash#10479] opened 2019-02-20 09:38 UTC
Hi

I am new to logstash 
I want to send log data in to elasticsearch to visualize the data through kibana.

please find the below sample log data.
02/08/2019 19:55:05 Reply from IP: bytes=32 time=677ms TTL=111
02/08/2019 19:55:06 Request timed out.
02/08/2019 19:55:26 Reply from IP: Destination host unreachable.

Please help me how to write 3 grok filter pattern to send data in to elastic search using logstash.

**Comment by yaauie** [comment] 2019-02-20 22:47
Since this is a general usage question and not a reproducible bug report or a feature request, I am closing this issue.

> Please post all product and debugging questions on our [forum](https://discuss.elastic.co/c/logstash).
> Your questions will reach our wider community members there, and if we confirm that there is a bug, then we can open a new issue here.
> 
> -- [Logstash Issue Template](https://raw.githubusercontent.com/elastic/logstash/master/.github/ISSUE_TEMPLATE.md)

Please open a thread on the [forum](https://discuss.elastic.co/c/logstash). When you do, be specific about what information you're looking to extract from each type of message.

**Closed by yaauie** 2019-02-20 22:47 UTC
