### ISSUE TITLE
JRuby fails to load on armv7l

### ISSUE THREAD

**Issue by Trevor159** [elastic/logstash#10888] opened 2019-06-24 23:09 UTC
- Version: 7.1.1
- Operating System: Linux odroidxu4 4.14.111-odroidxu4 #2 SMP PREEMPT Wed May 8 17:30:01 CEST 2019 armv7l armv7l armv7l GNU/Linux

ERROR: `Jun 24 23:04:13 odroid logstash[30841]: [2019-06-24T23:04:13,339][ERROR][org.logstash.Logstash    ] java.lang.IllegalStateException: Logstash stopped processing because of an error: (LoadError) load error: ffi/ffi -- java.lang.NullPointerException: null`

Very similar/maybe the same but on a different env as #10755 

I worked with some JRuby folks, aka @Headius , debugging and standalone JRuby was running fine on the device. This leads him to believe "it is likely some odd packaging or configuration issue with their embedded JRuby"

**Comment by headius** [comment] 2019-06-25 18:01
JRuby folks standing by to assist here. As @Trevor159 explained, we did not have any issues getting a plain JRuby 9.2.7.0 distribution to start up and use FFI, so it seems something else is amiss when JRuby is packaged in Logstash.

I may have access to an armv7l device for investigation, if necessary.

**Comment by ryanbreed-tp** [comment] 2019-06-28 20:23
came here to +1 on this as well, I can use the vendored jruby ffi/ffi just fine when requring/invoking from vendor/jruby/bin/{jruby,jirb}, but launching from ./bin/logstash always results in NPE originating somewhere near ffi/ffi. 

openjdk (8|11) armv7l linux+logstash 7.2 + logstash-core/lib/jars/jruby-complete-9.2.7.0 jar 

previously, I was able to work around this by opening the jruby-complete .jar,  forcibly copying `lib/ruby/stdlib/ffi/platform/arm-linux/types.conf` to `lib/ruby/stdlib/ffi/platform/arm-linux/platform.conf`, and then re-jarring. doing the same from  `vendor/jruby/lib/ruby/stdlib/ffi/platform/arm-linux/` doesn't work.

**Comment by boddyw** [comment] 2019-07-24 01:59
came here to +1 on this as well, I also come the same problem on arm8+openjdk8+logstash6.8.1.

**Comment by boddyw** [comment] 2019-08-22 06:00
i hava solved this on arm8+openjdk8+logstash6.8.1.
by copying the 
jruby-complete-9.2.7.0.jar\META-INF\jruby.home\lib\ruby\stdlib\ffi\platform\aarch64-linux
types.conf file to platform.conf.

u can use 'uname -a ' to find where is the types.conf   folder u need to  replace. 
such as:
```shell
# uname -a
aarch64 aarch64 aarch64 GNU/Linux
```
then u get aarch64-linux but  not arm-linux.

**Comment by headius** [comment] 2019-08-22 07:44
Can you open a JRuby issue about this? It sounds like a fairly easy patch.

**Comment by goferito** [comment] 2019-11-16 22:44
I've just fixed the issue with this script:
https://gist.github.com/alexalouit/a857a6de10dfdaf7485f7c0cccadb98c

I have now logstash 7.3.2 in a Raspberry Pi 4 with Buster :tada:

**Comment by jloehel** [comment] 2020-07-02 21:16
> Can you open a JRuby issue about this? It sounds like a fairly easy patch.

@headius What is the current status? Can you please link the JRuby issue. I have the same issue on a Rock64 with aarch64.

**Comment by robbavey** [comment] 2020-07-02 21:26
@loehel The Logstash team is currently working on aarch64 support in a future release. 

There is a meta issue [here](https://github.com/elastic/logstash/issues/11767), which you can follow our progress on. Any help testing would be gratefully received.

**Comment by jloehel** [comment] 2020-07-02 21:29
> @loehel The Logstash team is currently working on aarch64 support in a future release.
> 
> There is a meta issue [here](https://github.com/elastic/logstash/issues/11767), which you can follow our progress on. Any help testing would be gratefully received.

Thanks for your quick reply. Please let me know if I can help. :-) Great work guys.

**Comment by headius** [comment] 2020-07-08 19:34
@jloehel Recent JRuby releases should work fine on AArch64. The trickier bit here is that some deployments (like LogStash, I believe) use the all-in-one "jruby-complete.jar" which must be able to unpack some native libraries when it runs. On some systems that process fails (due to filesystem permissions or security restrictions, for example) so some of our functionality is reduced.

Given that you're trying to run LogStash I would recommend continuing to work through this issue tracker, and if at some point it's more clear that it's a JRuby issue we'll be standing by to help.

**Comment by jloehel** [comment] 2020-07-09 03:01
> @jloehel Recent JRuby releases should work fine on AArch64. The trickier bit here is that some deployments (like LogStash, I believe) use the all-in-one "jruby-complete.jar" which must be able to unpack some native libraries when it runs. On some systems that process fails (due to filesystem permissions or security restrictions, for example) so some of our functionality is reduced.
> 
> Given that you're trying to run LogStash I would recommend continuing to work through this issue tracker, and if at some point it's more clear that it's a JRuby issue we'll be standing by to help.

Thanks for your reply headius. I am using now this ansible tasks: https://gist.github.com/jloehel/c9c7fac7a1e9e6bd732268e1f1bea9b7 It works fine for me.

But it would be nice to get rid of this workaround. :-)

**Comment by robbavey** [comment] 2020-09-01 13:21
I believe this should be working now, with the `7.9.0` release of Logstash.

This appeared to have been caused by jruby/jruby#6219, where during ffi loading platform configuration files, an unhandled NPE would be thrown, rather than the handled file NotFound when attempting to load platform.conf, resulting in the error shown here.

This was fixed by this [commit](https://github.com/headius/jruby/commit/9575276a04a4f5ec6418989403bcfdbb47284cdd), included in the version of jruby shipped with logstash `7.9.0`.

Please let us know if this fixes your problem

**Comment by roaksoax** [comment] 2022-10-31 20:29
Gonna close this issue as we believe it is now fixed. Please re-open if you believe this is still exists in the latest version of LS.

**Closed by roaksoax** 2022-10-31 20:29 UTC
