### ISSUE TITLE
Slow even when running version

### ISSUE THREAD

**Issue by smithamax** [elastic/logstash#1511] opened 2014-07-08 08:14 UTC
I'm running logstash on my mac, and on a linux box. It takes ages to start up on both.

even when running a simple `logstash version` it takes more than 10 seconds.

on os x
```
$ time logstash version
logstash 1.4.1

real  0m13.211s
user 0m15.355s
sys   0m0.724s
```

on linux
```
$ time /opt/logstash/bin/logstash version
logstash 1.4.2-modified

real  0m36.963s
user 0m34.432s
sys   0m1.997s
```

Does anyone have any insight into why this takes so long and if there is a solution?

**Comment by untergeek** [comment] 2015-01-23 18:19
Closing.  Feel free to re-open, if desired.

**Comment by timmolter** [comment] 2015-02-05 16:23
I'd like to report this issue too:

    $ time /opt/logstash/bin/logstash version
    logstash 1.4.2-modified

    real	1m31.590s
    user	1m47.771s
    sys	0m4.444s

Running any thing takes over a minute to start. How can I debug the problem? Are there some flags I can set to ignore anything? What's the reason for the slow startup?

**Comment by untergeek** [comment] 2015-02-05 16:28
```
$ time bin/logstash --version
logstash 2.0.0.dev

real	0m4.149s
user	0m10.876s
sys	0m0.494s
```

This is beyond strange.  What hardware are you running on?

**Comment by timmolter** [comment] 2015-02-05 16:36
I have a Linux Box running 32-bit Lubuntu 12.04 with a quad core Intel Atom, 4GB RAM. The thing is that I run other Java apps on it, and they start up instantly. Any tips to find the bottleneck?

**Comment by untergeek** [comment] 2015-02-05 16:39
How much RAM is free?  Logstash is pretty hungry.  It will want 500M for the heap, minimum.  It could be that you're hitting swap, which would definitely explain the slow-down.

Which Java are you using?

Also, and Atom processor, 4 cores notwithstanding, is not a high-powered CPU.

**Comment by timmolter** [comment] 2015-02-05 16:43
344 MB free. That's probably the issue. I'm using Java 8, the latest from Oracle. 

Is Logstash claiming 500MB at startup even if it's not needed? For just `logstash --version` for example. That seems unecessary. Where are the JVM memory flags set?

**Comment by untergeek** [comment] 2015-02-05 16:46
```
$ cat bin/logstash
#!/bin/sh
# Run logstash from source
#
# This is most useful when done from a git checkout.
#
# Usage:
#     bin/logstash <command> [arguments]
#
# See 'bin/logstash help' for a list of commands.
#
# Defaults you can override with environment variables
LS_HEAP_SIZE="${LS_HEAP_SIZE:=500m}"
```

You can simply set `LS_HEAP_SIZE` as an env variable before launching.

The problem is that if you're using Logstash with the Elasticsearch output, if you use the node protocol, Logstash wants that heap to spawn an Elasticsearch client.  To save memory you should go with `protocol => "http"`.

It should use less memory on a 32bit JVM, but for me on 64bit, Logstash won't even start with less than 320M, just fyi.

**Comment by untergeek** [comment] 2015-02-05 16:48
if you only need a log shipper, you might consider logstash-forwarder, beaver (python-based), nxlog, or something similar.  Logstash is heavy because it includes all of the functionality, whether you need it or not (at least in 1.4.x that's true.  1.5 will allow you to install only what plugins you need).

**Comment by untergeek** [comment] 2015-02-05 16:51
That 320M figure was a full configuration, not just trying to spit out `--version` information, btw.

**Comment by timmolter** [comment] 2015-02-06 09:00
Sorry to criticize without a solution, but it seems like there is a fundamental design flaw if running `logstash --version` takes over a minute. I would expect for it to take less than a second. I ran it again with 800MB of free mem with the same results. Perhaps not everything should be "loaded" in logstash if it's not needed.

I'll take a look at logstash-forwarder. Thanks for taking time to help!

**Comment by electrical** [comment] 2015-02-06 09:51
@timmolter I think the main issue is that we don't just start up java, we start up Jruby as well, load all the gem's and jars that are included in jruby and then load up any gems that we need extra.
That causes the main slow down in 1.4
In 1.5 we've improved that and also upgraded Jruby it self which has some improvements.

**Comment by moander** [comment] 2015-10-29 13:17
startup is still ridiculously slow on v2.0.0-rc1.

```
root@instance-1:~# time /opt/logstash/bin/logstash --version
logstash 2.0.0-rc1

real	0m13.221s
user	0m10.868s
sys	0m0.276s
```

Oracle JDK
```
root@instance-1:~# java -version
java version "1.8.0_66"
Java(TM) SE Runtime Environment (build 1.8.0_66-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.66-b17, mixed mode)
```

**Comment by jraby** [comment] 2015-11-16 23:38
Same here on a m4.large instance on ec2 (2 cores, 8GB of ram)

```
$ time /opt/logstash/bin/logstash --version
logstash 2.0.0

real    0m18.887s
user    0m21.561s
sys     0m0.468s
```

**Comment by jsvd** [comment] 2016-06-16 11:52
fast -V/--version has been merged. should ship with 5.0 and 2.4

**Comment by purbon** [comment] 2016-06-16 11:58
I wonder if they are still having slowness not just with version, can you
share more details?

/purbon

**Comment by suyograo** [comment] 2016-06-25 00:50
Fixed in 5490

**Closed by suyograo** 2016-06-25 00:50 UTC
Labels: enhancement, v5.0.0-alpha4

**Comment by edgar-humberto** [comment] 2016-10-28 18:40
Running `logstash --help` on 5.0.0 took over a minute

**Comment by hatdropper1977** [comment] 2016-10-31 18:30
I followed the recommendation to change /dev/random to /dev/urandom as written [here](https://github.com/elastic/logstash/issues/5491).  Running --help went from 26 minutes to 11 seconds.

**Comment by IDUnderCover** [comment] 2016-11-01 05:24
@hatdropper1977 Thanks, it works for me.
