### ISSUE TITLE
Trouble aborting pipeline using ctrl-c

### ISSUE THREAD

**Issue by tbragin** [elastic/logstash#7913] opened 2017-08-04 18:39 UTC
version: 6.0.0-beta1 BC7

pipeline:
```
input {
  generator {
    count => 0
    message => "test message"
  }
}

filter {
  sleep {
    time => "1"
    every => 1
  }
}

output {
  stdout { codec => dots }
  elasticsearch {
    hosts => ["http://localhost:9200"]
    user => "elastic"
    password => "elastic"
  }
}
```

had to submit ctrl-c many dozen times, in the meanwhile events kept coming and occasionally similar messages appeared
`[2017-08-04T11:19:54,882][WARN ][logstash.shutdownwatcher ] {"inflight_count"=>250, "stalling_thread_info"=>{["LogStash::Filters::Sleep", {"time"=>"1", "every"=>1, "id"=>"15ad4fc181ff6a55b7e6c89c55c67d102ddcb1f9-2"}]=>[{"thread_id"=>36, "name"=>"[main]>worker1", "current_call"=>"[...]/vendor/bundle/jruby/2.3.0/gems/logstash-filter-sleep-3.0.4/lib/logstash/filters/sleep.rb:105:in `sleep’“}, {“thread_id”=>38, “name”=>“[main]>worker3”, “current_call”=>“[...]/vendor/bundle/jruby/2.3.0/gems/logstash-filter-sleep-3.0.4/lib/logstash/filters/sleep.rb:105:in `sleep'"}]}}`

**Comment by andrewvc** [comment] 2017-08-04 19:55
@tbragin this is because of the use of the sleep filter. Logstash operates in batches, the default batch size is 125. Logstash also does not want to stop if there are in-flight events, instead waiting for any inflight batches to finish processing first.

In this case, Logstash will wait at least 125 seconds to stop due to that sleep filter. This is what you want in production, but not when testing with the sleep filter.

You can avoid this situation by overriding the batch size with the `-b` option. For example: `bin/logstash -b 1 -e 'input { generator {} } filter { sleep { time => 1 } } output { stdout {} }'`

I'm going to close this since this is expected behavior.

**Closed by andrewvc** 2017-08-04 19:55 UTC
Labels: bug

**Comment by tbragin** [comment] 2017-08-04 20:27
Thanks @andrewvc !

**Comment by jsvd** [comment] 2017-08-04 23:56
The problem seems to be that both [`shutdown_pipelines`](https://github.com/elastic/logstash/blob/master/logstash-core/lib/logstash/agent.rb#L439-L448) and [`force_shutdown_pipelines!`](https://github.com/elastic/logstash/blob/master/logstash-core/lib/logstash/agent.rb#L430-L437) use the [`with_pipelines`](https://github.com/elastic/logstash/blob/master/logstash-core/lib/logstash/agent.rb#L138-L145) iterator that is gated by a mutex.

After the first ctrl+c, `shutdown_pipelines` begins the effort to gracefully empty the pipeline events (which can take a long time if there's a sleep filter), acquiring the lock. With the second ctrl+c, `force_shutdown_pipelines!`  is called and through `with_pipelines` it tries to acquire the `@pipelines_lock`, but is never able to get it, so force shutdown never happens.

A pr has been created to fix this: https://github.com/elastic/logstash/pull/7918

**Comment by jsvd** [comment] 2017-08-09 08:33
Just to be clear: Logstash should terminate immediately on the second SIGINT (ctrl+c), and that wasn't happening in the 6.x line due to a locking issue.
The PR #7918 forces logstash to call `exit(1)` in these situations, fixing the issue.
