### ISSUE TITLE
Logstash 5.0.0-beta1 - No stdout errors for invalid config

### ISSUE THREAD

**Issue by ceeeekay** [elastic/logstash#5974] opened 2016-09-27 22:17 UTC
- Version: 5.0.0-beta1
- Operating System: Ubuntu 14.04.5
- Steps to Reproduce:

Start logstash in the foreground with an invalid config, e.g.,
```
input {
  stdin {}
}
output{
  stdout {
    workers => 2
  }
}
```
Logstash silently exits, however it does log to /var/log/logstash/logstash-plain.log

{edited by @jordansissel}
Previously, it would print errors to stdout if the config contained errors.

**Comment by jordansissel** [comment] 2016-09-28 01:30
@ceeeekay how did you install Logstash?

**Comment by ceeeekay** [comment] 2016-09-28 01:33
@jordansissel .deb package, previously rm'ed /etc/logstash and /usr/share/logstash - so as close to a clean install as I could get.

**Comment by ceeeekay** [comment] 2016-09-28 01:36
As an update to my original config, *some* errors log to stdout/stderr - e.g., if logstash.yml uses the older path.log instead of path.logs, there's a startup error printed.  This behaviour alone (some types of errors being printed, some not) is extremely confusing, to me at lest :)

**Comment by jordansissel** [comment] 2016-09-28 01:37
The .deb package ships with a default log configuration that doesn't have a console output. This change was done in https://github.com/elastic/logstash/pull/5903 for https://github.com/elastic/logstash/issues/5894. 

The idea was that for production packages (rpm/deb) that are run via sysv init, upstart, or systemd, writing to both a logfile and console will cause double data logged to disk because most of these systems will capture stdout and write it to a file.

The .tar.gz release of Logstash 5.0.0-beta1 should log to console by default, though.

**Comment by jordansissel** [comment] 2016-09-28 01:38
For clarity, the intent is that when run from a service manager Logstash should not write to stdout ("console" in log4j parlance).

Workaround: use this log4j2 config: https://github.com/elastic/logstash/blob/5.0/config/log4j2.properties

**Comment by ceeeekay** [comment] 2016-09-28 01:40
@jordansissel - makes sense. Can you comment on the mix of errors/no errors I'm seeing though?

Thanks for the config.

**Comment by jordansissel** [comment] 2016-09-28 01:43
@ceeeekay it's a bug that we output to stdout in this case you mention. I can reproduce it:

```
% bin/logstash -e 'foo'
INFO: Logstash has a new settings file which defines start up time settings. This file is typically located in $LS_HOME/config or /etc/logstash. If you installed Logstash through a package and are starting it manually please specify the location to this settings file by passing in "--path.settings=/path/.." in the command line options
ERROR: Failed to load settings file from "path.settings". Aborting... path.setting=/home/jls/build/logstash-5.0.0-beta1/config, exception=ArgumentError, message=>Setting "path.log" hasn't been registered
```

We should log this with log4j2 instead of writing directly to stderr.

**Comment by jordansissel** [comment] 2016-09-28 01:48
I filed #5975 to get move this error message to logging instead of direct stderr writes.

**Comment by ceeeekay** [comment] 2016-09-28 01:55
Awesome - thanks.

**Comment by talevy** [comment] 2016-10-12 16:20
#5999 seems to have fixed this. closing

**Closed by talevy** 2016-10-12 16:20 UTC
Labels: bug, Pioneer Program, v5.0.0, v5.0.0-beta1
