### ISSUE TITLE
Logstash terminates with status 0 if a plugin fails

### ISSUE THREAD

**Issue by Xylakant** [elastic/logstash#4420] opened 2016-01-05 18:01 UTC
### Description:
If a plugin fails with an unrecoverable error, the logstash process terminates with a status code of 0.

### Expected:
It should terminate with a non-zero status code indicating an error.

### Affected version:
1.5.6 (2.x not tested)

### Reproduction:
This input config reproduces the issue by triggering an error in the file plugin:
````
input {
  file {
    path => "/var/log/messages"
    sincedb_path => "/tmp/foo/bar"
  }
}
output {}
````

A logstash process started in the foreground will log an unrecoverable error in the file plugin and at some point terminate with status code 0.

**Comment by jordansissel** [comment] 2016-01-06 21:13
I tested on 2.1.1 and this doesn't fail for me.

```
% bin/logstash -e 'input {
  file {
    path => "/var/log/messages"
    sincedb_path => "/tmp/foo/bar"
  }
}
output {}'
Settings: Default filter workers: 1
Logstash startup completed
```

No error.

If I change `path` to be a file that exists (/var/log/messages doesn't exist on my system), I get this:

```
% bin/logstash -e 'input {
  file {
    path => "/tmp/a"
    sincedb_path => "/tmp/foo/bar"
  }
}
output {}'
Settings: Default filter workers: 1
Logstash startup completed
A plugin had an unrecoverable error. Will restart this plugin.
  Plugin: <LogStash::Inputs::File path=>["/tmp/a"], sincedb_path=>"/tmp/foo/bar", codec=><LogStash::Codecs::Plain charset=>"UTF-8">, stat_interval=>1, discover_interval=>15, sincedb_write_interval=>15, start_position=>"end", delimiter=>"\n">
  Error: No such file or directory - /tmp/foo/bar.194884.11628.343063 {:level=>:error}
```

This is a non-fatal error for Logstash and causes the file input to be restarted.

I can't reproduce the problem you describe (exiting with status 0). Can you test this on 2.x?

**Comment by Xylakant** [comment] 2016-01-07 09:13
seems that 2.1 does not terminate in this case. I actually prefer the 1.x behavior since it's much easier to detect that a process went away with an error than detecting errors in log messages, but I can see the reasons not to. Maybe terminating after a certain number of errors would be an option, but that's not what this topic is about.

**Comment by suyograo** [comment] 2016-01-11 20:16
Closing this since this is not an issue on 2.1

**Closed by suyograo** 2016-01-11 20:16 UTC
