### ISSUE TITLE
Error messages when no permission to read config file

### ISSUE THREAD

**Issue by micheloosterhof** [elastic/logstash#2571] opened 2015-02-10 20:10 UTC
I accidently made made config files not readable by the 'logstash' user account. This resulted in the following error messages:

{:timestamp=>"2015-02-10T20:07:58.723000+0000", :message=>"Error: Expected one of #, input, filter, output at line 1, column 1 (byte 1) after ", :file=>"logstash/agent.rb", :line=>"140"}
{:timestamp=>"2015-02-10T20:07:58.744000+0000", :message=>"You may be interested in the '--configtest' flag which you can\nuse to validate logstash's configuration before you choose\nto rest
art a running system.", :file=>"logstash/agent.rb", :line=>"142"}

I suggest that the system gives a more descriptive error than the current one.

**Comment by jordansissel** [comment] 2015-02-10 20:10
Neat. That certainly is a terrible error message.

**Comment by magnusbaeck** [comment] 2015-08-20 18:47
As far as I can tell this is already fixed at the current master head (commit beae32b) so we should be able to close the issue.

    $ touch test.conf
    $ chmod 0 test.conf
    $ bin/logstash -f test.conf
    The error reported is:
      Permission denied - /home/magnus/src/logstash/logstash/test.conf
    $ mkdir test
    $ mv test.conf test
    $ bin/logstash -f test/
    The error reported is:
      Permission denied - /home/magnus/src/logstash/logstash/test/test.conf

**Comment by PhilippSpo** [comment] 2015-10-14 09:07
I get the same error:
```
{:timestamp=>"2015-10-14T10:47:20.110000+0200", :message=>"Error: Expected one of #, input, filter, output at line 23, column 1 (byte 287) after "}
{:timestamp=>"2015-10-14T10:47:20.117000+0200", :message=>"You may be interested in the '--configtest' flag which you can\nuse to validate logstash's configuration before you choose\nto restart a running system."}
```
This is how my logstash.conf looks like:
```
input {
  file {
    type => "json"
    path => ["/etc/logstash/conf.d/metaDataFields.log"]
    codec => "json"
  }
}
filter {
  json {
    source => "message"
  }
}
output {
  stdout {
    codec => rubydebug
  }
  elasticsearch {
    protocol => "http"
    index => "myindex"
  }
}
```
I am using the most recent version of logstash.
This error only occurs if I start logstash as a service. When I test my config it tells me the the config is OK:
```sh
$ ./bin/logstash --config /etc/logstash/conf.d/logstash.conf --configtest
```
Also this works fine:
```sh
$ ./bin/logstash --config /etc/logstash/conf.d/logstash.conf
[2015-10-14 10:54:49.656]  WARN -- Concurrent: [DEPRECATED] Java 7 is deprecated, please use Java 8.
Java 7 support is only best effort, it may not work. It will be removed in next release (1.0).
Logstash startup completed
```
Both files (logstash.conf and metaDataFields.log have full permissions for root)

**Comment by alfredocambera** [comment] 2016-01-12 20:21
The error occurs when the configuration file doesn't have the appropiate strcuture. Here is how I reproduced the bug:

  root@vagrant-ubuntu-trusty:/etc/logstash/conf.d# /opt/logstash/bin/logstash --version
  logstash 2.1.1
  root@vagrant-ubuntu-trusty:/etc/logstash/conf.d# java -version
  java version "1.8.0_66"
  Java(TM) SE Runtime Environment (build 1.8.0_66-b17)
  Java HotSpot(TM) 64-Bit Server VM (build 25.66-b17, mixed mode)
  root@vagrant-ubuntu-trusty:/etc/logstash/conf.d# ls -al
  total 8
  drwxrwxr-x 2 root root 4096 ene 12 20:07 .
  drwxrwxr-x 4 root root 4096 ene 12 16:20 ..
  root@vagrant-ubuntu-trusty:/etc/logstash/conf.d# touch test.conf
  root@vagrant-ubuntu-trusty:/etc/logstash/conf.d# ls -al
  total 8
  drwxrwxr-x 2 root root 4096 ene 12 20:07 .
  drwxrwxr-x 4 root root 4096 ene 12 16:20 ..
  -rw-r--r-- 1 root root    0 ene 12 20:07 test.conf
  root@vagrant-ubuntu-trusty:/etc/logstash/conf.d# /opt/logstash/bin/logstash -f *.conf --configtest                                                                                           
  Error: Expected one of #, input, filter, output at line 2, column 1 (byte 2) after 
  root@vagrant-ubuntu-trusty:/etc/logstash/conf.d# vi test.conf  # created a 'bad' conf file
  root@vagrant-ubuntu-trusty:/etc/logstash/conf.d# cat test.conf 
  {
  }
  root@vagrant-ubuntu-trusty:/etc/logstash/conf.d# /opt/logstash/bin/logstash -f *.conf --configtest                                                                                           
  Error: Expected one of #, input, filter, output at line 1, column 1 (byte 1) after 
  root@vagrant-ubuntu-trusty:/etc/logstash/conf.d# vi test.conf 
  root@vagrant-ubuntu-trusty:/etc/logstash/conf.d# cat test.conf 
  input {
    stdin {
    }
  }
  
  output {
    stdout {
    }
  }
  root@vagrant-ubuntu-trusty:/etc/logstash/conf.d# /opt/logstash/bin/logstash -f *.conf --configtest                                                                                           
  Configuration OK

I agree with @jordansissel  and @micheloosterhof. An improved error message is required.

Hope it helps to improve the application, specially for novice user who are very prone to make syntax errors on the configuration file.

Alfredo

**Comment by jsvd** [comment] 2016-03-11 17:50
From what I understand the initial issue is fixed: provide a sane error message if access to the config file is denied.

With a broken configuration: ` { } ` I think the error message: `Error: Expected one of #, input, filter, output at line 1, column 1 (byte 1) after` is not great but actually hints at what the problem is: the file must start with input,filter or output.

Please open another issue for user facing syntax error messages

**Closed by jsvd** 2016-03-11 17:50 UTC
Labels: enhancement
