### ISSUE TITLE
Logstash jvm node stats api double what should be

### ISSUE THREAD

**Issue by Exocomp** [elastic/logstash#7381] opened 2017-06-08 10:24 UTC
There is some more info into on the discuss forum:
https://discuss.elastic.co/t/logstash-jvm-stats-api-heap-used-percent/88407

I'm using version 5.3.1, basically the node stats API is returning values that are double what it should be:

nodeStats API => "http://127.0.0.1:9600/_node/stats/jvm"

I have configuration with 1 GB of heap.

heap_max_in_bytes => 2.113 GB
heap_used_in_bytes => 1.01 GB

Using VisualVM I can see the heap size and used bytes are half these values.  Please review other fields in this API to determine if the issue affects them as well.

Thanks,
E

**Comment by jordansissel** [comment] 2017-06-08 23:20
@ph I thought we fixed this?

**Comment by jordansissel** [comment] 2017-06-08 23:23
Duplicate of https://github.com/elastic/logstash/issues/6608. Fixed by https://github.com/elastic/logstash/pull/6827.

The fix is available in Logstash 5.4.0 and beyond.

**Closed by jordansissel** 2017-06-08 23:23 UTC
