### ISSUE TITLE
Logstash error while installing codec - logstash-codec-nmap

### ISSUE THREAD

**Issue by xsallowed** [elastic/logstash#6351] opened 2016-12-05 13:51 UTC
ERROR: Installation Aborted, message: Bundler could not find compatible versions for gem "logstash-core-plugin-api":
  In snapshot (Gemfile.lock):
    logstash-core-plugin-api (= 2.1.16)

**Comment by andrewvc** [comment] 2016-12-05 17:45
Hmmm, this plugin needs to be updated to LS 5.x

**Comment by jsvd** [comment] 2017-01-06 17:49
this is a duplicate of https://github.com/logstash-plugins/logstash-codec-nmap/issues/9

**Closed by jsvd** 2017-01-06 17:49 UTC
