### ISSUE TITLE
IPV6 - csv: is not an IP string literal

### ISSUE THREAD

**Issue by joschi99** [elastic/logstash#9267] opened 2018-03-21 09:23 UTC
- Version: 6.2.2
- Operating System: CentOS 6.9

we are sending Exchange 2016 Transport Logs using Filebeat 6.2.2 to logstash. The logfile has a CSV strcuture, so we are parsing the file using the csv filter:
```
    csv {
      columns => [ "date-time", "client-ip", "client-hostname", "server-ip", "server-hostname", "source-context", "connector-id", "source", "event-id", "internal-message-id", "message-id", "network-message-id", "recipient-address", "recipient-status", "total-bytes", "recipient-count", "related-recipient-address", "reference", "message-subject", "sender-address", "return-path", "message-info", "directionality", "tenant-id", "original-client-ip", "original-server-ip", "custom-data", "transport-traffic-type", "log-id", "schema-version" ]
      separator => ","
    }
```
We have some IP-address in this records and we defined on the template this attributes as IP. Everything is working fine, but we are not able to handle IPV6 addresses. This is the error that we got:
```
[2018-03-21T10:11:40,730][WARN ][logstash.outputs.elasticsearch] Could not index event to Elasticsearch. {:status=>400, :action=>["index", {:_id=>nil, :_index=>"exchange-2018.03.20", :_type=>"doc", :_routing=>nil}, #<LogStash::Event:0x212aea0>], :response=>{"index"=>{"_index"=>"exchange-2018.03.20", "_type"=>"doc", "_id"=>"8IDUR2IBwebE7nJFBgz5", "status"=>400, "error"=>{"type"=>"mapper_parsing_exception", "reason"=>"failed to parse [original-server-ip]", "caused_by"=>{"type"=>"illegal_argument_exception", "reason"=>"'fe80::1862:1326:5e45:357d%6' is not an IP string literal."}}}}}
```

**Comment by andrewvc** [comment] 2018-03-26 16:51
It seems like this is not a bug report but user error, due to that, we are closing it. We ask that users with questions about the use of Logstash ask those questions on our forum: https://discuss.elastic.co/c/logstash 

The issues section of this repo is for bug reports only, and this is not a bug, but a configuration error.

**Closed by andrewvc** 2018-03-26 16:51 UTC

**Comment by yaauie** [comment] 2018-03-26 16:52
(hint: the `%6` at the end of the IP is not a valid part of an IPv6 literal, so Elasticsearch is correct in rejecting the message)
