### ISSUE TITLE
[6.2.2] - Syslog parsing is getting error when PQ enabled

### ISSUE THREAD

**Issue by joschi99** [elastic/logstash#9247] opened 2018-03-16 08:45 UTC
- Version: 6.2.2
- Operating System: CentoOS 6.9
- Configuration files (logstash.yml, input configuration):
[logstash-config.zip](https://github.com/elastic/logstash/files/1818480/logstash-config.zip)

If we activate PQ on logstash (see logstash.yml), the syslog parses is getting error:
`[2018-03-16T09:39:01,959][WARN ][logstash.outputs.elasticsearch] Could not index event to Elasticsearch. {:status=>400, :action=>["index", {:_id=>nil, :_index=>"rsyslog-2018.03.16", :_type=>"doc", :_routing=>nil}, #<LogStash::Event:0x4518880b>], :response=>{"index"=>{"_index"=>"rsyslog-2018.03.16", "_type"=>"doc", "_id"=>"BKf2LWIBZGIPMDA4WGo9", "status"=>400, "error"=>{"type"=>"mapper_parsing_exception", "reason"=>"failed to parse [pid]", "caused_by"=>{"type"=>"number_format_exception", "reason"=>"For input string: \"<78>M\""}}}}}
`
If we use queue.type: memory the syslog messages are parsed without problems. Someone knows what is wrong in this configuration?

Regards,
Jochen

**Comment by andrewvc** [comment] 2018-03-19 20:22
@original-brownbear do you have an idea here? This looks like an encoding serialization/deserialization issue.

**Comment by original-brownbear** [comment] 2018-03-19 21:27
@andrewvc looks like another manifestation of #9167 maybe. Will have to try and reproduce to be sure, but it's obviously a serialization issue :(

**Comment by andrewvc** [comment] 2018-03-19 23:08
If it is a dupe, feel free to close and continue in #9167

**Comment by original-brownbear** [comment] 2018-03-22 15:50
@joschi99 is this failing for every event?

Also, would it be possible for you to provide me with an event that serializes incorrectly with PQ enabled by just running it through:

```sh
output {
  stdout { codec => rubydebug }
}
```
It would be extremely helpful to have that for PQ enabled and disabled. That should allow me to track this down easily.

Thanks

**Comment by joschi99** [comment] 2018-03-23 11:01
hi @original-brownbear,

you will find both samples attached this post:
[syslog-queuetype-memory.txt](https://github.com/elastic/logstash/files/1841239/syslog-queuetype-memory.txt)
[syslog-queuetype-persisted.txt](https://github.com/elastic/logstash/files/1841240/syslog-queuetype-persisted.txt)

Regards,
Jochen

**Comment by original-brownbear** [comment] 2018-03-23 11:37
@joschi99 thanks! 

Unfortunately, the outputs look exactly the same to me. Are all of these messages failing to map in ES? Or put differently, can you not even get a single message through to ES when PQ is active?

**Comment by joschi99** [comment] 2018-03-23 16:40
hi @original-brownbear 

quit strange. I tried with different syslog messages. I got everytime the same error. Only a few messages will be send to Elastic, but this messages seem's corrupted. One of the syslog messages send to elastic are restarting rsyslogd, but the message is not correct:
![image](https://user-images.githubusercontent.com/6400595/37841958-384877ce-2ec1-11e8-87b0-56183d6c5abf.png)

The same message without PQ:
![image](https://user-images.githubusercontent.com/6400595/37841969-3e8d981c-2ec1-11e8-92d2-aa61140bed41.png)

**Comment by original-brownbear** [comment] 2018-03-23 17:15
@joschi99 thanks that's really helpful. I'll try and reproduce this :)

**Comment by original-brownbear** [comment] 2018-03-26 17:03
In all likelihood this is caused by #9167, waiting for a fix to that here

**Comment by original-brownbear** [comment] 2018-04-02 12:44
Fixed in https://github.com/elastic/logstash/pull/9308

**Closed by original-brownbear** 2018-04-02 12:44 UTC
Labels: P2, bug

**Comment by gmoskovicz** [comment] 2018-04-18 14:46
Also back-ported in https://github.com/elastic/logstash/pull/9318 to `6.2.4`
