### ISSUE TITLE
Logstash 1.5.0: Updating plugin claims no plugin updated, even though it was

### ISSUE THREAD

**Issue by jib** [elastic/logstash#3254] opened 2015-05-15 18:41 UTC
See here:

```
user@host:/opt/logstash$ apt-cache policy logstash
logstash:
  Installed: (none)
  Candidate: 1:1.5.0-1
  Version table:
     1:1.5.0-1 0
        500 http://apt.krxd.net/foss/ trusty/development amd64 Packages
     1.5.0.rc4-1 0
        500 http://apt.krxd.net/foss/ trusty/development amd64 Packages
        100 /var/lib/dpkg/status
     1.4.2-1-2c0f5a1 0
        500 http://apt.krxd.net/foss/ trusty/development amd64 Packages
user@host:/opt/logstash$ sudo apt-get install logstash
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  logstash
0 upgraded, 1 newly installed, 0 to remove and 10 not upgraded.
Need to get 87.8 MB of archives.
After this operation, 133 MB of additional disk space will be used.
Get:1 http://apt.krxd.net/foss/ trusty/development logstash all 1:1.5.0-1 [87.8 MB]
Fetched 87.8 MB in 1s (50.1 MB/s)
Selecting previously unselected package logstash.
(Reading database ... 74626 files and directories currently installed.)
Preparing to unpack .../logstash_1%3a1.5.0-1_all.deb ...
Unpacking logstash (1:1.5.0-1) ...
Processing triggers for ureadahead (0.100.0-16) ...
Setting up logstash (1:1.5.0-1) ...
user@host:/opt/logstash$ sudo -u logstash bin/plugin list --verbose | grep kafka
logstash-input-kafka (0.1.14)
logstash-output-kafka (0.1.11)
user@host:/opt/logstash$ sudo -u logstash bin/plugin update logstash-input-kafka
Updating logstash-input-kafka
No plugin updated
user@host:/opt/logstash$ sudo -u logstash bin/plugin list --verbose | grep kafka
logstash-input-kafka (0.1.15)
logstash-output-kafka (0.1.11)
```

Checking on disk, the plugin has indeed been updated.

**Comment by purbon** [comment] 2015-06-02 13:42
I run a test with the current 1.5 branch, also with the kafka input plugin and I got this output:

```
╭─purbon@purbon-elastic  ~/work/logstash  ‹0850fc0› 
╰─$ bin/plugin list kafka
logstash-input-kafka
logstash-output-kafka
╭─purbon@purbon-elastic  ~/work/logstash  ‹0850fc0› 
╰─$ bin/plugin list --verbose kafka
logstash-input-kafka (0.1.14)
logstash-output-kafka (0.1.11)
╭─purbon@purbon-elastic  ~/work/logstash  ‹0850fc0› 
╰─$ bin/plugin update logstash-input-kafka
Updating logstash-input-kafka
Updated logstash-input-kafka 0.1.14 to 0.1.15
``` 

the code to show this message looks to be there since the addition of the update command [1]. I will now test with the generated package if I can reproduce this behaviour. In the meanwhile, @jib can you provide more details of your platform? jvm version? operating system ? package version ? etc..

Thanks a lot,


[1] https://github.com/elastic/logstash/blob/48bcc5b74df2fd05b42af01f9255f938c3da0ce4/lib/pluginmanager/update.rb#L77

**Comment by purbon** [comment] 2015-06-02 14:30
@jib I tested with ubuntu trusty 64 bits using the last deb package and saw the Updated message.

```
vagrant@vagrant-ubuntu-trusty-64:~$ sudo /opt/logstash/bin/plugin update logstash-input-kafka
bash: warning: setlocale: LC_ALL: cannot change locale (de_DE.UTF-8)
Updating logstash-input-kafka
Updated logstash-input-kafka 0.1.14 to 0.1.15
vagrant@vagrant-ubuntu-trusty-64:~$ 
```

can you provide more details of your infra? so we try to narrow down the reproduce of your issue.

**Comment by jib** [comment] 2015-06-04 19:41
@purbon Confirmed that I also no longer see this message. Tested by installing another plugin:

```
logstash@host:/opt/logstash$ bin/plugin install logstash-output-syslog
Validating logstash-output-syslog
Installing logstash-output-syslog
Installation successful
logstash@host:/opt/logstash$ dpkg -l|grep logstash
ii  logstash    1:1.5.0-1  all  An extensible logging pipeline
logstash@host:/opt/logstash$ uname -a
Linux host 3.13.0-52-generic #85-Ubuntu SMP Wed Apr 29 16:44:17 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by suyograo** [comment] 2015-06-08 16:06
@jib @purbon thanks for looking into this. Will close this -- let us know if it appears again.

**Closed by suyograo** 2015-06-08 16:06 UTC
Labels: bug, needs details, v1.5.1
