### ISSUE TITLE
Grok failure (beta2)

### ISSUE THREAD

**Issue by splitice** [elastic/logstash#4055] opened 2015-10-18 08:45 UTC
I did an upgrade of one node in our logstash cluster which was running beta1 to beta2 today. A very large issue could be immediately seen, all the matched fields appear to not be extracted correctly.

Here is a screenshot from kibana.

![19_41_08 1](https://cloud.githubusercontent.com/assets/468579/10563295/808e9f7e-75d0-11e5-8c41-c952603ac20d.png)

The only fields that work are those explicitly typed with the grok syntax ```{PATTERN:name:type}```. It would appear the start of the log message is being used, these log messages parsed start with ```[number] ....```.

This pattern and configuration worked fine with beta1.

This may be grok or core related so I am opening the bug here until cause identified. There doesnt seem to be any relevant commits in the plugin that I can see.

**Comment by purbon** [comment] 2015-10-19 05:27
@splitice Thanks a lot for your report! I' wondering if you can share your config/patterns with us? I would really love to reproduce, and for sure fix! :+1: 

Looking forward to it,

**Comment by splitice** [comment] 2015-10-19 05:32
I can try and build a self contained configuration for it, not sure you want the monstrosity we run.

From what I have observed and from reading through some other likely related issues it appears to be pretty common (i.e observed with the syslog pattern)

**Comment by purbon** [comment] 2015-10-19 05:36
@splitice Thanks man, will also do some debugging, looking forward to hunt the issue and fix it.

**Comment by splitice** [comment] 2015-10-19 05:56
I have confirmed that the issue exhibits the same behaviour as #4048. The field corruption (start of line used) is not seen in rubydebug, only the elasticsearch output.

I will take a look at some other output options and see which have issues next.

Input:
```
{"facility"=>"auth","message":"Failed password for testuser from 1.1.1.1 port 22"}
```

Config:
```
input {
stdin {
codec=> json
}
}

filter {
if [facility] == "auth" {
                grok {
                        match => [
                                "message", "Failed password for (invalid user |)%{USERNAME:username} from %{IP:src_ip} port %{BASE10NUM:port}"
                        ]
                        remove_field => ["message","severity"]
                        add_tag => ["ssh_failure"]
                }
}
}

output {
#stdout { codec => rubydebug }
elasticsearch { }
}
```

ELS:
```
{
  "took" : 10,
  "timed_out" : false,
  "_shards" : {
    "total" : 7,
    "successful" : 7,
    "failed" : 0
  },
  "hits" : {
    "total" : 1,
    "max_score" : 1.0,
    "hits" : [ {
      "_index" : "test",
      "_type" : "logs",
      "_id" : "AVB-qIL8wx2h9Ji6o0ga",
      "_score" : 1.0,
      "_source":{"facility":"auth","@version":"1","@timestamp":"2015-10-19T05:53:03.408Z","host":"logstash-1.internal.x4b.org","username":"Failed p","src_ip":"Failed ","port":"Fa","tags":["ssh_failure"]}
    } ]
  }
}
```

Rubydebug:
```
{
      "facility" => "auth",
      "@version" => "1",
    "@timestamp" => "2015-10-19T05:48:02.862Z",
          "host" => "logstash-1.internal.x4b.org",
      "username" => "testuser",
        "src_ip" => "1.1.1.1",
          "port" => "22",
          "tags" => [
        [0] "ssh_failure"
    ]
}
```

**Comment by splitice** [comment] 2015-10-19 06:00
Confirmed the same behaviour with file output logging:

Config:
```
input {
stdin {
codec=> json
}
}

filter {
if [facility] == "auth" {
                grok {
                        match => [
                                "message", "Failed password for (invalid user |)%{USERNAME:username} from %{IP:src_ip} port %{BASE10NUM:port}"
                        ]
                        remove_field => ["message","severity"]
                        add_tag => ["ssh_failure"]
                }
}
}

output {
file { path => "/var/log/logstash/test.log" }
}
``

```
{"facility":"auth","@version":"1","@timestamp":"2015-10-19T05:58:52.563Z","host":"logstash-1.internal.x4b.org","username":"Failed p","src_ip":"Failed ","port":"Fa","tags":["ssh_failure"]}
```

Hopefully this helps.

**Comment by splitice** [comment] 2015-10-19 06:11
Issue can be seen with ```stdout { codec => json }``` so its codec related?

**Comment by purbon** [comment] 2015-10-19 07:10
Thanks a lot Mathew, this is very helpful.

/purbon

**Comment by purbon** [comment] 2015-10-19 09:21
I confirm this issue and all the findings by @splitice (good work man)

If you run:

```
input {
  generator {
    lines => [ "purbon 192.168.1.1" ]
    count => 1
  }
}

filter {
  grok {
    match => [
      "message", "%{USERNAME:username} %{IP:src_ip}"
      ]
  }
}

output {
  stdout { codec => json  }
``` 

you will get

```
{"message":"purbon 192.168.1.1","@version":"1","@timestamp":"2015-10-19T09:19:10.499Z","host":"skywalker","sequence":0,"username":"purbon","src_ip":"purbon 192."}
```

that is wrong, but if you change the config to use:

```
input {
  generator {
    lines => [ "purbon 192.168.1.1" ]
    count => 1
  }
}

filter {
  grok {
    match => [
      "message", "%{USERNAME:username} %{IP:src_ip}"
      ]
  }
}

output {
  stdout { codec => rubydebug  }
}
```

you actually get

```
{
       "message" => "purbon 192.168.1.1",
      "@version" => "1",
    "@timestamp" => "2015-10-19T09:18:48.003Z",
          "host" => "skywalker",
      "sequence" => 0,
      "username" => "purbon",
        "src_ip" => "192.168.1.1"
}
```

that is correct. If I would have to look for a suspect, the json codec, or also JrJackson new version, would be my first candidates as well. /cc  @guyboertje

**Comment by guyboertje** [comment] 2015-10-19 09:39
However, this test does not fail:
```ruby

  describe "when event created via JSON parser" do
    config <<-CONFIG
      filter {grok {match => ["message", "Failed password for (invalid user |)%{USERNAME:username} from %{IP:src_ip} port %{BASE10NUM:port}"] remove_field => ["message","severity"] add_tag => ["ssh_failure"]}}
    CONFIG

    sample('{"facility":"auth","message":"Failed password for testuser from 1.1.1.1 port 22"}') do
      insist { subject["username"] } == "testuser"
      insist { subject["port"] } == "22"
      insist { subject["src_ip"] } == "1.1.1.1"
      insist { subject.to_json } =~ %r|{"@version":"1","@timestamp":"20\d\d-\d\d-\d\dT\d\d:\d\d:\d\d\.\d\d\dZ","username":"testuser","src_ip":"1.1.1.1","port":"22","tags":\["ssh_failure"\]}|
    end
  end
```

**Comment by purbon** [comment] 2015-10-19 09:40
@guyboertje not sure why, but if you test the end user experience (as I shared in my previous comment), the logic is broken. So I would say the test is also broken, or incomplete.

**Comment by guyboertje** [comment] 2015-10-19 09:41
I have tested the full pipeline on the command line.  Confirm that issue exists.

**Comment by purbon** [comment] 2015-10-19 09:52
I rolled back JrJackson, in the current master by using ```0.2.9``` and cleaning out lines introduced in ```json.rb``` lines 38 and 50. Then executed:

```
input {
  generator {
    lines => [ "purbon 192.168.1.1" ]
    count => 1
  }
}

filter {
  grok {
    match => [
      "message", "%{USERNAME:username} %{IP:src_ip}"
      ]
  }
}

output {
  stdout { codec => json  }
}
```

and got a good output,

```
{"message":"purbon 192.168.1.1","@version":"1","@timestamp":"2015-10-19T09:49:36.321Z","host":"skywalker","sequence":0,"username":"purbon","src_ip":"192.168.1.1"}
```

so, at less, I would say this looks like some jrjackson update issue, or closely related.

**Comment by ei-grad** [comment] 2015-10-19 10:01
Same issue with
```
    grok {
      match => { "message" => "%{COMBINEDAPACHELOG}" }
    }
```

Example record:
```
79.174.53.77 - - [19/Oct/2015:08:47:22 +0300] "GET /api/v2/catalogs?token=HY9HV5eOc5HNZDBDaHb2TuJnKk2GUBY1&mode=fetch,expanded&ids=4050 HTTP/1.1" 200 9960 "-" "Edadeal/151005.1905 CFNetwork/758.0.2 Darwin/15.0.0"
```

**Comment by guyboertje** [comment] 2015-10-19 11:42
Update: The grok filter is storing references to regex MatchData in the Event. e.g. `event[k] = m[2]`.  JRuby reports these as Strings. While serializing, JrJackson tries to grab the bytes from this object and get given the wrong ones.  Thanks to @jsvd for narrowing this down.

**Comment by guyboertje** [comment] 2015-10-19 13:44
This is a JrJackson bug.  it is fixed in v 0.3.6 which is in rubygems now.

**Comment by guyboertje** [comment] 2015-10-19 13:56
@splitice @ei-grad if you do `bin/bundle update jrjackson`, does it work?

**Comment by purbon** [comment] 2015-10-19 13:58
@guyboertje this will only work if they are using a clone if the git repo, otherwise if they use a package they will not find ```bin/bundle```, see https://github.com/elastic/logstash/blob/master/rakelib/artifacts.rake#L28

**Comment by suyograo** [comment] 2015-10-19 21:59
@splitice many thanks for trying out beta2 and opening this issue <3 

beta3 has been release with this fix. Can you please try? https://www.elastic.co/blog/logstash-2-0-0-beta3-released

**Closed** 2015-10-19 21:59 UTC
Labels: blocker, bug

**Comment by splitice** [comment] 2015-10-20 01:55
Confirmed fix works on the configuration posted.
