### ISSUE TITLE
One bad output plug-in can prevent output from another plug-in

### ISSUE THREAD

**Issue by pfuntner** [elastic/logstash#7046] opened 2017-05-08 13:59 UTC
I have application using logstash to send logs to destinations via output plug-ins.  If I have one plug-in mis-configured (wrong hostname, Elasticsearch not started at destination, etc.), logstash doesn't seem to send output to the other plug-in that's still properly configured.

- Logstash  version: 5.4.0
- OS: Ubuntu 16.04.1 LTS
- Configuration:
 ```
==> logstash_input.conf <==
input {
  tcp {
    port => 3000
    type => "syslog_logs"
  }

  file {
    path => ["/logs/**/*-json.log"]
    exclude => ["*.json", "*.conf"]
    type => "json_logs"
    codec => json
  }
}

filter {

  if [type] == "syslog_logs"
  {
          grok {
            match => {
              message => [
                "<%{NONNEGINT:syslog_priority}>%{NONNEGINT:syslog_version} +(?:%{TIMESTAMP_ISO8601:syslog_timestamp}|-) +(?:%{HOSTNAME:syslog_host}|-) +(-|%{SYSLOG5424PRINTASCII:syslog_app}) +(-|%{SYSLOG5424PRINTASCII:syslog_process}) +(-|%{SYSLOG5424PRINTASCII:syslog_messageid}) +%{GREEDYDATA:syslog_message}"
              ]
            }
          }
          grok {
            match => {
              syslog_message  => [
                ...
                ...
                "%{GREEDYDATA:foo_message}"
              ]
            }
          }
  }
  else if [type] == "json_logs"
  {

    grok {
      match => {
        "log"  => [
                ...
                "%{TIMESTAMP_ISO8601:supervisor_time} %{LOGLEVEL:supervisor_log_level} %{GREEDYDATA:supervisor_message}",
                ...
                "%{GREEDYDATA:bar_message}"
         ]
      }
    }

    if [bar_message] =~ /^\{\s*\"/
    {
      json {
        source => "bar_message"
      }
    }

    mutate {
      rename => { "[attrs][container_name]" => "container_name" }
    }
    mutate {
      rename => { "[attrs][DATA_CENTER]" => "data_center" }
    }
    mutate {
      rename => { "[attrs][NETWORKID]" => "network_id" }
    }
    mutate {
      rename => { "[attrs][LOCALMSPID]" => "peer_org" }
    }
  }

  if ("" in [foo_message]) {
    throttle {
      before_count => -1
      after_count => 100
      period => 1800
      max_age => 3600
      key => "%{data_center}%{network_id}%{container_name}%{foo_message}"
      add_tag => "throttled"
    }
  }
  else if ("" in [bar_message]) {
    throttle {
      before_count => -1
      after_count => 100
      period => 1800
      max_age => 3600
      key => "%{data_center}%{network_id}%{container_name}%{bar_message}"
      add_tag => "throttled"
    }
  }
  if "throttled" in [tags] {
    drop { }
  }
}

==> logstash_es.conf <==
output {
  elasticsearch {
    hosts => ["pfuntner1"]
    codec => "json"
  }
}

==> logstash_es2.conf <==
output {
  elasticsearch {
    hosts => ["pfuntner-dev"]
    codec => "json"
  }
}
 ```
- Sample data: I don't think it's relevant - I think it can be anything
- Steps to reproduce:
 1. Start Elasticsearch and Kibana on two destination systems _(two Elasticsearch's, two Kibana's)_
 2. Start logstash
 3. Start the application using logstash
 4. Verify that output is being received at both Kibanas
 5. Stop the application and logstash
 6. Stop Elasticsearch and Kibana at only one of the destination systems
 7. Start logstash
 8. Start the application using logstash

 At this point, I expected the Kibana that's still running to receive log output.  I don't except one output plug-in that can't work to affect the operation of another output plug-in that will work.

When I originally saw this I was:
 - Trying to use a lumberjack output plug-in along with an elastic search output plug-in but if there was a problem with either, I wouldn't get logs at the other destination either.  I wanted to see if I could do it without the lumberjack output plug-in.
 - Using logstash 5.1.1.  I used 5.4.0 instead and saw the same behavior

**Comment by pfuntner** [comment] 2017-05-08 18:08
Log with two good destinations:

```
{"level":"WARN","loggerName":"logstash.outputs.elasticsearch","timeMillis":1494266218695,"thread":"[main]-pipeline-manager","logEvent":{"message":"Restored connection to ES instance","url":{"metaClass":{"metaClass":{"metaClass":{"url":"http://pfuntner1:9200/"}}}}}}
{"level":"WARN","loggerName":"logstash.outputs.elasticsearch","timeMillis":1494266219605,"thread":"[main]-pipeline-manager","logEvent":{"message":"Restored connection to ES instance","url":{"metaClass":{"metaClass":{"metaClass":{"url":"http://pfuntner-dev:9200/"}}}}}}
```

Log with one good destination:

```
{"level":"WARN","loggerName":"logstash.outputs.elasticsearch","timeMillis":1494266675212,"thread":"[main]-pipeline-manager","logEvent":{"message":"Restored connection to ES instance","url":{"metaClass":{"metaClass":{"metaClass":{"url":"http://pfuntner1:9200/"}}}}}}
{"level":"WARN","loggerName":"logstash.outputs.elasticsearch","timeMillis":1494266675546,"thread":"[main]-pipeline-manager","logEvent":{"message":"Attempted to resurrect connection to dead ES instance, but got an error.","url":{"metaClass":{"metaClass":{"metaClass":{"url":"http://pfuntner-dev:9200/","error_type":{"metaClass":{"metaClass":{"error_type":"LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError","error":"Elasticsearch Unreachable: [http://pfuntner-dev:9200/][Manticore::SocketException] Connection refused (Connection refused)"}}}}}}}}}
{"level":"WARN","loggerName":"logstash.outputs.elasticsearch","timeMillis":1494266675551,"thread":"[main]-pipeline-manager","logEvent":{"message":"Marking url as dead. Last error: [LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError] Elasticsearch Unreachable: [http://pfuntner-dev:9200/][Manticore::SocketException] Connection refused (Connection refused)","url":{"metaClass":{"metaClass":{"metaClass":{"url":"http://pfuntner-dev:9200/","error_message":"Elasticsearch Unreachable: [http://pfuntner-dev:9200/][Manticore::SocketException] Connection refused (Connection refused)","error_class":"LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError"}}}}}}
{"level":"ERROR","loggerName":"logstash.outputs.elasticsearch","timeMillis":1494266675552,"thread":"[main]-pipeline-manager","logEvent":{"message":"Failed to install template.","message":"Elasticsearch Unreachable: [http://pfuntner-dev:9200/][Manticore::SocketException] Connection refused (Connection refused)","class":"LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError","backtrace":["/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-6.3.0-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:287:in `perform_request_to_url'","/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-6.3.0-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:273:in `perform_request'","/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-6.3.0-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:363:in `with_connection'","/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-6.3.0-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:272:in `perform_request'","/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-6.3.0-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:280:in `get'","/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-6.3.0-java/lib/logstash/outputs/elasticsearch/http_client.rb:83:in `get_version'","/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-6.3.0-java/lib/logstash/outputs/elasticsearch/template_manager.rb:16:in `get_es_version'","/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-6.3.0-java/lib/logstash/outputs/elasticsearch/template_manager.rb:20:in `get_es_major_version'","/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-6.3.0-java/lib/logstash/outputs/elasticsearch/template_manager.rb:7:in `install_template'","/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-6.3.0-java/lib/logstash/outputs/elasticsearch/common.rb:54:in `install_template'","/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-6.3.0-java/lib/logstash/outputs/elasticsearch/common.rb:21:in `register'","/usr/share/logstash/logstash-core/lib/logstash/output_delegator_strategies/shared.rb:9:in `register'","/usr/share/logstash/logstash-core/lib/logstash/output_delegator.rb:41:in `register'","/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:268:in `register_plugin'","/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:279:in `register_plugins'","org/jruby/RubyArray.java:1613:in `each'","/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:279:in `register_plugins'","/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:288:in `start_workers'","/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:214:in `run'","/usr/share/logstash/logstash-core/lib/logstash/agent.rb:398:in `start_pipeline'"]}}
{"level":"WARN","loggerName":"logstash.outputs.elasticsearch","timeMillis":1494266680554,"thread":"Ruby-0-Thread-16: /usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-6.3.0-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:234","logEvent":{"message":"Attempted to resurrect connection to dead ES instance, but got an error.","url":{"metaClass":{"metaClass":{"metaClass":{"url":"http://pfuntner-dev:9200/","error_type":{"metaClass":{"metaClass":{"error_type":"LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError","error":"Elasticsearch Unreachable: [http://pfuntner-dev:9200/][Manticore::SocketException] Connection refused (Connection refused)"}}}}}}}}}
{"level":"WARN","loggerName":"logstash.outputs.elasticsearch","timeMillis":1494266680833,"thread":"[main]>worker2","logEvent":{"message":"UNEXPECTED POOL ERROR","e":{"metaClass":{"metaClass":{"metaClass":{"e":"No Available connections"}}}}}}
{"level":"ERROR","loggerName":"logstash.outputs.elasticsearch","timeMillis":1494266680841,"thread":"[main]>worker2","logEvent":{"message":"Attempted to send a bulk request to elasticsearch, but no there are no living connections in the connection pool. Perhaps Elasticsearch is unreachable or down?","error_message":"No Available connections","class":"LogStash::Outputs::ElasticSearch::HttpClient::Pool::NoConnectionAvailableError","will_retry_in_seconds":2}}
{"level":"WARN","loggerName":"logstash.outputs.elasticsearch","timeMillis":1494266681831,"thread":"[main]>worker3","logEvent":{"message":"UNEXPECTED POOL ERROR","e":{"metaClass":{"metaClass":{"metaClass":{"e":"No Available connections"}}}}}}
{"level":"ERROR","loggerName":"logstash.outputs.elasticsearch","timeMillis":1494266681832,"thread":"[main]>worker3","logEvent":{"message":"Attempted to send a bulk request to elasticsearch, but no there are no living connections in the connection pool. Perhaps Elasticsearch is unreachable or down?","error_message":"No Available connections","class":"LogStash::Outputs::ElasticSearch::HttpClient::Pool::NoConnectionAvailableError","will_retry_in_seconds":2}}
{"level":"WARN","loggerName":"logstash.outputs.elasticsearch","timeMillis":1494266682844,"thread":"[main]>worker2","logEvent":{"message":"UNEXPECTED POOL ERROR","e":{"metaClass":{"metaClass":{"metaClass":{"e":"No Available connections"}}}}}}
{"level":"ERROR","loggerName":"logstash.outputs.elasticsearch","timeMillis":1494266682845,"thread":"[main]>worker2","logEvent":{"message":"Attempted to send a bulk request to elasticsearch, but no there are no living connections in the connection pool. Perhaps Elasticsearch is unreachable or down?","error_message":"No Available connections","class":"LogStash::Outputs::ElasticSearch::HttpClient::Pool::NoConnectionAvailableError","will_retry_in_seconds":4}}
{"level":"WARN","loggerName":"logstash.outputs.elasticsearch","timeMillis":1494266682867,"thread":"[main]>worker1","logEvent":{"message":"UNEXPECTED POOL ERROR","e":{"metaClass":{"metaClass":{"metaClass":{"e":"No Available connections"}}}}}}
{"level":"ERROR","loggerName":"logstash.outputs.elasticsearch","timeMillis":1494266682868,"thread":"[main]>worker1","logEvent":{"message":"Attempted to send a bulk request to elasticsearch, but no there are no living connections in the connection pool. Perhaps Elasticsearch is unreachable or down?","error_message":"No Available connections","class":"LogStash::Outputs::ElasticSearch::HttpClient::Pool::NoConnectionAvailableError","will_retry_in_seconds":2}}
.
.
.
```

**Comment by jsvd** [comment] 2017-05-26 15:51
@pfuntner this is, for the time being and for some time in the future, the behaviour by design and can't be configured. The idea is that all destinations should have a similar view of events being processed by logstash, and if one stops then all data flow should stop.

It's possible in the future we'll be able to tune this behaviour when we have a graph based execution of the pipeline, but I'm going to close this issue as no action will be taken.

**Closed by jsvd** 2017-05-26 15:51 UTC
