### ISSUE TITLE
Logstash plugin install fails behind proxy (5.2.1)

### ISSUE THREAD

**Issue by heikkis** [elastic/logstash#6788] opened 2017-03-02 13:09 UTC
Using Docker image sebp/elk:521.

Version is 5.2.1.

## Without proxy need
When running command without proxy-need it works fine:
```
FROM sebp/elk:521

WORKDIR ${LOGSTASH_HOME}
RUN gosu logstash bin/logstash-plugin install logstash-filter-de_dot
```

Installation works:
```
 ---> Running in 51ac83106922
Validating logstash-filter-de_dot
Installing logstash-filter-de_dot
Installation successful
```

## Behind proxy

Dockerfile:
```
FROM sebp/elk:521

WORKDIR ${LOGSTASH_HOME}
ENV HTTP_PROXY=127.0.0.1:3128
ENV HTTPS_PROXY=127.0.0.1:3128
ENV http_proxy=127.0.0.1:3128
ENV https_proxy=127.0.0.1:3128
RUN gosu logstash bin/logstash-plugin install logstash-filter-de_dot
```

Output is:
```
Step 7 : RUN gosu logstash bin/logstash-plugin install logstash-filter-de_dot
 ---> Running in 675fcdee65fb
Validating logstash-filter-de_dot
Installing logstash-filter-de_dot

Exception: java.lang.ThreadDeath thrown from the UncaughtExceptionHandler in thread "Thread-3"
Error Bundler::InstallError, retrying 1/10
An error occurred while installing logstash-core-event-java (5.2.1), and Bundler cannot continue.
Make sure that `gem install logstash-core-event-java -v '5.2.1'` succeeds before bundling.
WARNING: SSLSocket#session= is not supported
```

**Comment by ph** [comment] 2017-03-03 01:11
I will close this issue, since it is a duplicate of https://github.com/elastic/logstash/issues/6619
I will also take a look

**Closed by ph** 2017-03-03 01:11 UTC
