### ISSUE TITLE
Unable to install Plugin that uses Java Library

### ISSUE THREAD

**Issue by driverpt** [elastic/logstash#5072] opened 2016-04-08 15:31 UTC
Hello,

In Logstash 2.3.1 we're trying to install a Plugin based in a Java Library and we're having problems installing it into a standalone instance.

> luis.duarte@ip-10-10-11-121:/var/lib/logstash$ sudo -u logstash $LS_HOME/bin/logstash-plugin install --no-verify ~/logstash-filter-<filter_name>-0.0.2-java.gem
> Installing logstash-filter-<filter_name>
> Error Bundler::InstallError, retrying 1/10
> An error occurred while installing logstash-filter-<filter_name> (0.0.2), and Bundler cannot continue.
> Make sure that `gem install logstash-filter-<filter_name> -v '0.0.2'` succeeds before bundling.
> ^C
> 
> luis.duarte@ip-10-10-11-121:/var/lib/logstash$ sudo -u logstash $LS_HOME/vendor/jruby/bin/jruby -S gem install ~/logstash-filter-<filter_name>-0.0.2-java.gem
>   jar dependencies for logstash-filter-<filter_name>-0.0.2-java.gemspec . . .
> [ERROR] [ERROR] Some problems were encountered while processing the POMs:
> [FATAL] Non-parseable POM /opt/logstash/<hidden-project>/vendor/jruby/lib/ruby/shared/jars/gemspec_pom.rb: only whitespace content allowed before start tag and not # (position: START_DOCUMENT seen #... @1:1)  @ line 1, column 1
>  @
> [ERROR] The build could not read 1 project -> [Help 1]
> [ERROR]
> [ERROR]   The project  (/opt/logstash/<hidden-project>/vendor/jruby/lib/ruby/shared/jars/gemspec_pom.rb) has 1 error
> [ERROR]     Non-parseable POM /opt/logstash/<hidden-project>/vendor/jruby/lib/ruby/shared/jars/gemspec_pom.rb: only whitespace content allowed before start tag and not # (position: START_DOCUMENT seen #... @1:1)  @ line 1, column 1 -> [Help 2]
> [ERROR]
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR]
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
> [ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/ModelParseException
> ERROR:  While executing gem ... (Errno::ENOENT)
>     No such file or directory - /opt/logstash/<hidden-project>/vendor/jruby/lib/ruby/gems/shared/gems/logstash-filter-<filter_name>-0.0.2-java/deps.lst
>

**Comment by driverpt** [comment] 2016-04-08 15:43
From what i'm observing, if i'm installing a .gem file, it means it's already packaged, and it doesn't make any sense to go look for the jars in the Maven Central, if they are already there.

**Comment by jsvd** [comment] 2016-04-08 16:23
I'll try to replicate with a plugin that uses jar-dependencies. We know this parseable pom was fixed in some scenarios, apparently something else is still broken.

+1 on the offline notion, and that's what should happen. currently bin/logstash-plugin pack creates a pack of installed plugins that allows you to do offline installation, even for plugins like logstash-output-elasticsearch and logstash-input-kafka, which use jar-dependencies.

**Comment by driverpt** [comment] 2016-04-08 16:48
@jsvd The `bin/logstash-plugin install --local` should assume that the .gem is prepackaged with everything and install it bypassing all the gem building/fetching.
From what i'm analysing i believe that this has something to do with the jar-dependencies gem, because i'm doing a `sudo -u logstash $LS_HOME/vendor/jruby/bin/jruby -S gem install --force --local logstash-filter-<hidden_name>-<version>-java.gem` and it's executing the 'jar-dependencies' maven build.

**Comment by jsvd** [comment] 2016-04-08 16:55
in the custom plugin gemspec do you have jar-dependencies as a runtime or development dependency? it seems to make a difference in the build/installation process https://github.com/mkristian/jar-dependencies#vendoring-your-jars-before-packing-the-jar

**Comment by driverpt** [comment] 2016-04-08 16:58
Here's the Gemspec. It's obfuscated for privacy issues

`
Gem::Specification.new do |s|
  s.name          = 'logstash-filter-<hidden>'
  s.version       = '0.0.2'
  s.licenses      = ['Proprietary']
  s.summary       = "<hidden>"
  s.description   = "<hidden>"
  s.authors       = ["<hidden>"]
  s.email         = "<hidden>"
  s.homepage      = "<hidden>"
  s.require_paths = ["lib"]
  s.platform      = "java"

  # Files
  s.files = Dir['lib/**/*','spec/**/*','vendor/**/*','*.gemspec','*.md','CONTRIBUTORS','Gemfile','LICENSE','NOTICE.TXT']

  # Tests
  s.test_files = s.files.grep(%r{^(test|spec|features)/})

  # Special flag to let us know this is actually a logstash plugin
  s.metadata = { "logstash_plugin" => "true", "logstash_group" => "filter" }

  # Gem dependencies
  s.add_runtime_dependency "logstash-core", ">= 2.3.0", "< 3.0.0"
  s.add_development_dependency 'logstash-devutils', "~> 0.0"

  # Jar dependencies
  s.requirements << "jar '<groupId>:<artifactId>', '0.0.2'"
  s.add_runtime_dependency "jar-dependencies"
end
`

**Comment by jsvd** [comment] 2016-04-08 16:59
can you try:

```
IMPORTANT: make sure that jar-dependencies is only a development dependency of your gem. if it is a runtime dependency the require_jars file will be overwritten during installation.
```

**Comment by driverpt** [comment] 2016-04-08 17:13
@jsvd It worked.

**Comment by mattgruter** [comment] 2016-04-18 11:24
Thanks for the tip @jsvd 
Should the documentation be updated as it is stating to use `s.add_runtime_dependency 'jar-dependencies'` instead of `s.add_development_dependency 'jar-dependencies'`?
https://www.elastic.co/guide/en/logstash/current/_how_to_write_a_logstash_filter_plugin.html#_jar_dependencies_3

**Comment by jsvd** [comment] 2016-04-20 16:27
@mattgruter you mean the opposite, right? i.e. update `s.add_development_dependency 'jar-dependencies'` in the docs

**Comment by jsvd** [comment] 2016-04-21 08:19
this issue was solved, tracking the documentation change in https://github.com/elastic/logstash/issues/5154

**Closed by jsvd** 2016-04-21 08:19 UTC
Labels: bug, needs details, unconfirmed

**Comment by fatemabw** [comment] 2017-09-07 16:35
I am having the exact same issue. And still didn't get it to work, getting on my nerves now.
Some details, I recently upgraded my ELK tsack and all are on the latest and greatest version: 5.5.2
We run a reverse proxy, hence not all sites are accessible to the elk box, and hence whatever are the required files I have already downloaded and pasted to the box offline.

I need the translate plugin in my logstash, hence being a very naive user of Logstash, I though the following command should work, but unfortunately it doesn't:

# sudo -u logstash JARS_DEBUG=true JARS_VERBOSE=true DEBUG=1 /usr/share/logstash/bin/logstash-plugin install /etc/logstash/local-plugins/logstash-filter-translate-3.0.3.gem

<snippet>

Validating /etc/logstash/local-plugins/logstash-filter-translate-3.0.3.gem
Installing logstash-filter-translate
Resolving dependencies..........
...
...
Using polyglot 0.3.5
0:  polyglot (0.3.5) from /usr/share/logstash/vendor/bundle/jruby/1.9/specifications/polyglot-0.3.5.gemspec
Using treetop 1.4.15
0:  treetop (1.4.15) from /usr/share/logstash/vendor/bundle/jruby/1.9/specifications/treetop-1.4.15.gemspec
  jar dependencies for logstash-core-5.5.2-java.gemspec . . .
mvn dependency:copy-dependencies dependency:list -X -e -Dverbose=true -Dmaven.repo.local=/opt/logstash/.m2/repository -f /usr/share/logstash/vendor/bundle/jruby/1.9/gems/jar-dependencies-0.3.11/lib/jars/gemspec_pom.rb -Djars.0=org.apache.logging.log4j:log4j-api:jar:2.6.2 -Djars.1=org.apache.logging.log4j:log4j-core:jar:2.6.2 -Djars.2=com.fasterxml.jackson.core:jackson-core:jar:2.7.4 -Djars.3=com.fasterxml.jackson.core:jackson-databind:jar:2.7.4 -Djars.4=com.fasterxml.jackson.module:jackson-module-afterburner:jar:2.7.4 -Djars.5=com.fasterxml.jackson.dataformat:jackson-dataformat-cbor:jar:2.7.4 -Djars.specfile=/usr/share/logstash/logstash-core/logstash-core.gemspec -DoutputAbsoluteArtifactFilename=true -DincludeTypes=jar -DoutputScope=true -DuseRepositoryLayout=true -DoutputDirectory=/opt/logstash/.m2/repository -DoutputFile=/usr/share/logstash/logstash-core/deps.lst
mvn dependency:copy-dependencies dependency:list -X -e -Dverbose=true -Dmaven.repo.local=/opt/logstash/.m2/repository -f /usr/share/logstash/vendor/bundle/jruby/1.9/gems/jar-dependencies-0.3.11/lib/jars/gemspec_pom.rb -Djars.0=org.apache.logging.log4j:log4j-api:jar:2.6.2 -Djars.1=org.apache.logging.log4j:log4j-core:jar:2.6.2 -Djars.2=com.fasterxml.jackson.core:jackson-core:jar:2.7.4 -Djars.3=com.fasterxml.jackson.core:jackson-databind:jar:2.7.4 -Djars.4=com.fasterxml.jackson.module:jackson-module-afterburner:jar:2.7.4 -Djars.5=com.fasterxml.jackson.dataformat:jackson-dataformat-cbor:jar:2.7.4 -Djars.specfile=/usr/share/logstash/logstash-core/logstash-core.gemspec -DoutputAbsoluteArtifactFilename=true -DincludeTypes=jar -DoutputScope=true -DuseRepositoryLayout=true -DoutputDirectory=/opt/logstash/.m2/repository -DoutputFile=/usr/share/logstash/logstash-core/deps.lst
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T11:41:47-05:00)
Maven home: /usr/share/logstash/vendor/bundle/jruby/1.9/gems/ruby-maven-libs-3.3.9/maven-home
Java version: 1.8.0_141, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.141-1.b16.el7_3.x86_64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.10.0-514.26.2.el7.x86_64", arch: "amd64", family: "unix"
[DEBUG] Reading global settings from /usr/share/logstash/vendor/bundle/jruby/1.9/gems/ruby-maven-libs-3.3.9/maven-home/conf/settings.xml
[DEBUG] Reading user settings from /opt/logstash/.m2/settings.xml
[DEBUG] Using manager EnhancedLocalRepositoryManager with priority 10.0 for /opt/logstash/.m2/repository
[DEBUG] Using transporter WagonTransporter with priority -1.0 for https://repo.maven.apache.org/maven2
[DEBUG] Using connector BasicRepositoryConnector with priority 0.0 for https://repo.maven.apache.org/maven2
Downloading: https://repo.maven.apache.org/maven2/org/torquebox/mojo/mavengem/0.2.1/mavengem-0.2.1.pom
[DEBUG] Writing tracking file /opt/logstash/.m2/repository/org/torquebox/mojo/mavengem/0.2.1/mavengem-0.2.1.pom.lastUpdated
[WARNING] Failed to read extensions descriptor /usr/share/logstash/logstash-core/.mvn/extensions.xml: Plugin org.torquebox.mojo:mavengem-wagon:0.2.1 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.torquebox.mojo:mavengem-wagon:jar:0.2.1
[DEBUG] Created new class realm maven.api
[DEBUG] Importing foreign packages into class realm maven.api
[DEBUG]   Imported: javax.enterprise.inject.* < plexus.core
[DEBUG]   Imported: javax.enterprise.util.* < plexus.core
[DEBUG]   Imported: javax.inject.* < plexus.core
[DEBUG]   Imported: org.apache.maven.* < plexus.core
[DEBUG]   Imported: org.apache.maven.artifact < plexus.core
[DEBUG]   Imported: org.apache.maven.classrealm < plexus.core
[DEBUG]   Imported: org.apache.maven.cli < plexus.core
[DEBUG]   Imported: org.apache.maven.configuration < plexus.core
[DEBUG]   Imported: org.apache.maven.exception < plexus.core
[DEBUG]   Imported: org.apache.maven.execution < plexus.core
[DEBUG]   Imported: org.apache.maven.execution.scope < plexus.core
[DEBUG]   Imported: org.apache.maven.lifecycle < plexus.core
[DEBUG]   Imported: org.apache.maven.model < plexus.core
[DEBUG]   Imported: org.apache.maven.monitor < plexus.core
[DEBUG]   Imported: org.apache.maven.plugin < plexus.core
[DEBUG]   Imported: org.apache.maven.profiles < plexus.core
[DEBUG]   Imported: org.apache.maven.project < plexus.core
[DEBUG]   Imported: org.apache.maven.reporting < plexus.core
[DEBUG]   Imported: org.apache.maven.repository < plexus.core
[DEBUG]   Imported: org.apache.maven.rtinfo < plexus.core
[DEBUG]   Imported: org.apache.maven.settings < plexus.core
[DEBUG]   Imported: org.apache.maven.toolchain < plexus.core
[DEBUG]   Imported: org.apache.maven.usability < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.* < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.authentication < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.authorization < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.events < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.observers < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.proxy < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.repository < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.resource < plexus.core
[DEBUG]   Imported: org.codehaus.classworlds < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.* < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.classworlds < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.component < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.configuration < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.container < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.context < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.lifecycle < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.logging < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.personality < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.util.xml.Xpp3Dom < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.util.xml.pull.XmlPullParser < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.util.xml.pull.XmlPullParserException < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.util.xml.pull.XmlSerializer < plexus.core
[DEBUG]   Imported: org.eclipse.aether.* < plexus.core
[DEBUG]   Imported: org.eclipse.aether.artifact < plexus.core
[DEBUG]   Imported: org.eclipse.aether.collection < plexus.core
[DEBUG]   Imported: org.eclipse.aether.deployment < plexus.core
[DEBUG]   Imported: org.eclipse.aether.graph < plexus.core
[DEBUG]   Imported: org.eclipse.aether.impl < plexus.core
[DEBUG]   Imported: org.eclipse.aether.installation < plexus.core
[DEBUG]   Imported: org.eclipse.aether.internal.impl < plexus.core
[DEBUG]   Imported: org.eclipse.aether.metadata < plexus.core
[DEBUG]   Imported: org.eclipse.aether.repository < plexus.core
[DEBUG]   Imported: org.eclipse.aether.resolution < plexus.core
[DEBUG]   Imported: org.eclipse.aether.spi < plexus.core
[DEBUG]   Imported: org.eclipse.aether.transfer < plexus.core
[DEBUG]   Imported: org.eclipse.aether.version < plexus.core
[DEBUG]   Imported: org.slf4j.* < plexus.core
[DEBUG]   Imported: org.slf4j.helpers.* < plexus.core
[DEBUG]   Imported: org.slf4j.spi.* < plexus.core
[DEBUG] Populating class realm maven.api
[INFO] Error stacktraces are turned on.
[DEBUG] Reading global settings from /usr/share/logstash/vendor/bundle/jruby/1.9/gems/ruby-maven-libs-3.3.9/maven-home/conf/settings.xml
[DEBUG] Reading user settings from /opt/logstash/.m2/settings.xml
[DEBUG] Reading global toolchains from /usr/share/logstash/vendor/bundle/jruby/1.9/gems/ruby-maven-libs-3.3.9/maven-home/conf/toolchains.xml
[DEBUG] Reading user toolchains from /opt/logstash/.m2/toolchains.xml
[DEBUG] Using local repository at /opt/logstash/.m2/repository
[DEBUG] Using manager EnhancedLocalRepositoryManager with priority 10.0 for /opt/logstash/.m2/repository
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-parseable POM /usr/share/logstash/vendor/bundle/jruby/1.9/gems/jar-dependencies-0.3.11/lib/jars/gemspec_pom.rb: only whitespace content allowed before start tag and not e (position: START_DOCUMENT seen e... @1:1)  @ line 1, column 1
 @
[ERROR] The build could not read 1 project -> [Help 1]
org.apache.maven.project.ProjectBuildingException: Some problems were encountered while processing the POMs:
[FATAL] Non-parseable POM /usr/share/logstash/vendor/bundle/jruby/1.9/gems/jar-dependencies-0.3.11/lib/jars/gemspec_pom.rb: only whitespace content allowed before start tag and not e (position: START_DOCUMENT seen e... @1:1)  @ line 1, column 1

        at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:422)
        at org.apache.maven.graph.DefaultGraphBuilder.collectProjects(DefaultGraphBuilder.java:419)
        at org.apache.maven.graph.DefaultGraphBuilder.getProjectsForMavenReactor(DefaultGraphBuilder.java:410)
        at org.apache.maven.graph.DefaultGraphBuilder.build(DefaultGraphBuilder.java:83)
        at org.apache.maven.DefaultMaven.buildGraph(DefaultMaven.java:491)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:219)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[ERROR]
[ERROR]   The project  (/usr/share/logstash/vendor/bundle/jruby/1.9/gems/jar-dependencies-0.3.11/lib/jars/gemspec_pom.rb) has 1 error
[ERROR]     Non-parseable POM /usr/share/logstash/vendor/bundle/jruby/1.9/gems/jar-dependencies-0.3.11/lib/jars/gemspec_pom.rb: only whitespace content allowed before start tag and not e (position: START_DOCUMENT seen e... @1:1)  @ line 1, column 1 -> [Help 2]
org.apache.maven.model.io.ModelParseException: only whitespace content allowed before start tag and not e (position: START_DOCUMENT seen e... @1:1)
        at org.apache.maven.model.io.DefaultModelReader.read(DefaultModelReader.java:122)
        at org.apache.maven.model.io.DefaultModelReader.read(DefaultModelReader.java:86)
        at org.apache.maven.model.building.DefaultModelProcessor.read(DefaultModelProcessor.java:81)
        at org.apache.maven.model.building.DefaultModelBuilder.readModel(DefaultModelBuilder.java:533)
        at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:273)
        at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:469)
        at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:438)
        at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:401)
        at org.apache.maven.graph.DefaultGraphBuilder.collectProjects(DefaultGraphBuilder.java:419)
        at org.apache.maven.graph.DefaultGraphBuilder.getProjectsForMavenReactor(DefaultGraphBuilder.java:410)
        at org.apache.maven.graph.DefaultGraphBuilder.build(DefaultGraphBuilder.java:83)
        at org.apache.maven.DefaultMaven.buildGraph(DefaultMaven.java:491)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:219)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.codehaus.plexus.util.xml.pull.XmlPullParserException: only whitespace content allowed before start tag and not e (position: START_DOCUMENT seen e... @1:1)
        at org.codehaus.plexus.util.xml.pull.MXParser.parseProlog(MXParser.java:1557)
        at org.codehaus.plexus.util.xml.pull.MXParser.nextImpl(MXParser.java:1436)
        at org.codehaus.plexus.util.xml.pull.MXParser.next(MXParser.java:1131)
        at org.apache.maven.model.io.xpp3.MavenXpp3ReaderEx.read(MavenXpp3ReaderEx.java:4392)
        at org.apache.maven.model.io.xpp3.MavenXpp3ReaderEx.read(MavenXpp3ReaderEx.java:598)
        at org.apache.maven.model.io.DefaultModelReader.read(DefaultModelReader.java:113)
        ... 25 more
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/ModelParseException

Errno::ENOENT: No such file or directory - /usr/share/logstash/logstash-core/deps.lst
org/jruby/RubyIO.java:3804:in `read'
org/jruby/RubyIO.java:3987:in `read'
/usr/share/logstash/vendor/bundle/jruby/1.9/gems/jar-dependencies-0.3.11/lib/jars/installer.rb:73:in `load_from_maven'
/usr/share/logstash/vendor/bundle/jruby/1.9/gems/jar-dependencies-0.3.11/lib/jars/installer.rb:239:in `install_dependencies'
/usr/share/logstash/vendor/bundle/jruby/1.9/gems/jar-dependencies-0.3.11/lib/jars/installer.rb:226:in `do_install'
/usr/share/logstash/vendor/bundle/jruby/1.9/gems/jar-dependencies-0.3.11/lib/jars/installer.rb:172:in `vendor_jars'
/usr/share/logstash/vendor/jruby/lib/ruby/shared/jars/post_install_hook.rb:28:in `(root)'
org/jruby/RubyProc.java:281:in `call'
/usr/share/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/source/path.rb:215:in `run_hooks'
org/jruby/RubyArray.java:1613:in `each'
/usr/share/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/source/path.rb:214:in `run_hooks'
/usr/share/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/source/path.rb:195:in `generate_bin'
org/jruby/RubyDir.java:341:in `chdir'
/usr/share/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/shared_helpers.rb:53:in `chdir'
/usr/share/logstash/vendor/jruby/lib/ruby/1.9/monitor.rb:211:in `mon_synchronize'
/usr/share/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/shared_helpers.rb:52:in `chdir'
/usr/share/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/source/path.rb:189:in `generate_bin'
/usr/share/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/source/path.rb:73:in `install'
/usr/share/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/installer.rb:107:in `install_gem_from_spec'
/usr/share/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/installer.rb:269:in `install_sequentially'
org/jruby/RubyArray.java:1613:in `each'
/usr/share/logstash/vendor/jruby/lib/ruby/1.9/forwardable.rb:201:in `each'
/usr/share/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/installer.rb:268:in `install_sequentially'
/usr/share/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/installer.rb:90:in `run'
/usr/share/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/installer.rb:18:in `install'
/usr/share/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/cli/install.rb:80:in `run'
/usr/share/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/cli.rb:155:in `install'
/usr/share/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/share/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/usr/share/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/usr/share/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/usr/share/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/cli.rb:10:in `start'
/usr/share/logstash/lib/bootstrap/bundler.rb:168:in `execute_bundler'
/usr/share/logstash/lib/bootstrap/bundler.rb:129:in `invoke!'
/usr/share/logstash/lib/pluginmanager/install.rb:142:in `install_gems_list!'
/usr/share/logstash/lib/pluginmanager/install.rb:61:in `execute'
/usr/share/logstash/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
/usr/share/logstash/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/subcommand/execution.rb:11:in `execute'
/usr/share/logstash/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
/usr/share/logstash/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'
/usr/share/logstash/lib/pluginmanager/main.rb:48:in `(root)'
Bundler::InstallError: An error occurred while installing logstash-core (5.5.2), and Bundler cannot continue.
Make sure that `gem install logstash-core -v '5.5.2'` succeeds before bundling.
  install_gem_from_spec at /usr/share/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/installer.rb:145
   install_sequentially at /usr/share/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/installer.rb:269
                   each at org/jruby/RubyArray.java:1613
                   each at /usr/share/logstash/vendor/jruby/lib/ruby/1.9/forwardable.rb:201
   install_sequentially at /usr/share/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/installer.rb:268
                    run at /usr/share/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/installer.rb:90
                install at /usr/share/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/installer.rb:18
                    run at /usr/share/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/cli/install.rb:80
                install at /usr/share/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/cli.rb:155
                    run at /usr/share/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/vendor/thor/lib/thor/command.rb:27
         invoke_command at /usr/share/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/vendor/thor/lib/thor/invocation.rb:126
               dispatch at /usr/share/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/vendor/thor/lib/thor.rb:359
                  start at /usr/share/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/vendor/thor/lib/thor/base.rb:440
                  start at /usr/share/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/cli.rb:10
        execute_bundler at /usr/share/logstash/lib/bootstrap/bundler.rb:168
                invoke! at /usr/share/logstash/lib/bootstrap/bundler.rb:129
     install_gems_list! at /usr/share/logstash/lib/pluginmanager/install.rb:142
                execute at /usr/share/logstash/lib/pluginmanager/install.rb:61
                    run at /usr/share/logstash/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:67
                execute at /usr/share/logstash/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/subcommand/execution.rb:11
                    run at /usr/share/logstash/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:67
                    run at /usr/share/logstash/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:132
                 (root) at /usr/share/logstash/lib/pluginmanager/main.rb:48


Any help would be appreciated, as I have lost all hope now.

Thanks.
