### ISSUE TITLE
Daemon crashes

### ISSUE THREAD

**Issue by markri** [elastic/logstash#6060] opened 2016-10-14 21:05 UTC
Stack (fresh install):
- CentOS 7
- Logstash 2.4.0
- Filebeat 1.3.1
- Elasticsearch 2.4.1

A really simple config (no other configs)

`input {
  beats {
    port => 5044
  }
}
output {
  elasticsearch { hosts => ["127.0.0.1:9200"] }
}`

Problem:
When I start logstash as a daemon it crashes after ~15 seconds. But executing logstash on command line doesn't crash at all.

Output:

Start logstash service and check if its started

`[root@server logstash]# systemctl start logstash`
`[root@server logstash]# ps afx | grep logst`
`30004 pts/0    S+     0:00  |                       \_ grep --color=auto logst`
`29919 pts/0    SNl    0:14 /bin/java -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -Djava.awt.headless=true -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+HeapDumpOnOutOfMemoryError -Djava.io.tmpdir=/var/lib/logstash -Xmx1g -Xss2048k -Djffi.boot.library.path=/opt/logstash/vendor/jruby/lib/jni -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -Djava.awt.headless=true -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+HeapDumpOnOutOfMemoryError -Djava.io.tmpdir=/var/lib/logstash -XX:HeapDumpPath=/opt/logstash/heapdump.hprof -Xbootclasspath/a:/opt/logstash/vendor/jruby/lib/jruby.jar -classpath : -Djruby.home=/opt/logstash/vendor/jruby -Djruby.lib=/opt/logstash/vendor/jruby/lib -Djruby.script=jruby -Djruby.shell=/bin/sh org.jruby.Main --1.9 /opt/logstash/lib/bootstrap/environment.rb logstash/runner.rb agent -f /etc/logstash/conf.d -l /var/log/logstash/logstash.log`

After 15 seconds it's not in the process list anymore
`[root@server logstash]# ps afx | grep logst`
`30007 pts/0    S+     0:00  |                       \_ grep --color=auto logst`

Executing same command from process list will keep running

`[root@server logstash]# /bin/java -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -Djava.awt.headless=true -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+HeapDumpOnOutOfMemoryError -Djava.io.tmpdir=/var/lib/logstash -Xmx1g -Xss2048k -Djffi.boot.library.path=/opt/logstash/vendor/jruby/lib/jni -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -Djava.awt.headless=true -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+HeapDumpOnOutOfMemoryError -Djava.io.tmpdir=/var/lib/logstash -XX:HeapDumpPath=/opt/logstash/heapdump.hprof -Xbootclasspath/a:/opt/logstash/vendor/jruby/lib/jruby.jar -classpath : -Djruby.home=/opt/logstash/vendor/jruby -Djruby.lib=/opt/logstash/vendor/jruby/lib -Djruby.script=jruby -Djruby.shell=/bin/sh org.jruby.Main --1.9 /opt/logstash/lib/bootstrap/environment.rb logstash/runner.rb agent -f /etc/logstash/conf.d -l /var/log/logstash/logstash.log`
`Sending logstash logs to /var/log/logstash/logstash.log.`
`Settings: Default pipeline workers: 1`
`log4j:WARN No appenders could be found for logger` `(io.netty.util.internal.logging.InternalLoggerFactory).`
`log4j:WARN Please initialize the log4j system properly.`
`log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.`
`Pipeline main started`

no logs in /var/log/logstash :-(

Any advice?

**Comment by suyograo** [comment] 2016-10-14 21:29
@markri when you start LS manually (not as a daemon) where is the config file? Note that when LS starts as a service, it will read all the files in /etc/conf.d/logstash. Make sure there is no bad files in there.

**Comment by markri** [comment] 2016-10-14 21:36
I used the same cmd line read from processlist, (which includes -f /etc/logstash/conf.d)

Just to be sure:
[root@server ~]# service logstash configtest
Configuration OK

Which is the same as
[root@server logstash]# bin/logstash -f /etc/logstash/conf.d --configtest
Configuration OK

So it must be something between running manually and being run as a daemon, because that's the only difference I can spot

**Comment by jordansissel** [comment] 2016-11-10 07:34
The logs will hopefully have the answer here. 

Does /var/log/logstash/logstash.log have anything meaningful?

What about the systemd journal?

**Comment by markri** [comment] 2016-11-10 21:15
Unfortunately nothing

[root@server logstash]# journalctl -u logstash.service
-- Logs begin at Sun 2016-10-16 10:37:00 CEST, end at Thu 2016-11-10 22:07:09 CET. --
Nov 10 22:07:09 37-97-136-10.colo.transip.net systemd[1]: Started LSB: Starts Logstash as a daemon..
[root@37-97-136-10 logstash]#

and no log file touched in /var/log/logstash

**Comment by guyboertje** [comment] 2017-05-15 08:13
Can't reproduce, closing.

**Closed by guyboertje** 2017-05-15 08:13 UTC
Labels: needs details, v2.4.0
