### ISSUE TITLE
Filters mix event fields

### ISSUE THREAD

**Issue by bobrik** [elastic/logstash#2825] opened 2015-03-16 12:51 UTC
My config:

```
input {
    file {
        path => "/something/log/*.log"
        codec => multiline {
            pattern => "^(web|docker)"
            negate => true
            what => previous
        }
    }
}

filter {
    grok {
        match => {
            "path" => "/something/log/%{WORD:log}.log"
        }
        remove_field => ["path"]
    }

    grok {
        match => {
            "message" => "(?m)^%{WORD:hostname}\s+r%{INT:revision} (?<time>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2},\d{3}) +%{NUMBER:elapsed} (?<mode>(WEB|API|CLI|TST|UNK))(?<level>(DEBUG|INFO|WARN|ERROR|FATAL))\s+\[(?<extra>[^\]]+)\] %{GREEDYDATA:text}"
        }
        remove_field => ["message", "host"]
    }

    mutate {
        rename => {
            "text" => "message"
            "hostname" => "host"
        }
    }

    date {
        match => [
            "time",
            "YYYY-MM-dd HH:mm:ss,SSS"
        ]
        timezone => "Europe/Moscow"
        remove_field => ["time"]
    }

    kv {
        source => "extra"
        target => "kv"
        value_split => ":"
        remove_field => ["extra"]
    }
}

output {
    elasticsearch {
        protocol => "http"
        host => ["some-host"]
        template => "elasticsearch-template.json"
        template_overwrite => true
    }
}
```

Event happens in `CronManager` log:

```
$ fgrep 'used too much memory: 55050240' -r log/ | fgrep 70019
log/CronManager.log:web13  r20150316011 2015-03-16 15:43:14,652 +013.416 CLIWARN  [pid:70019] <redacted>: Cron <redacted> used too much memory: 55050240
```

But in elasticsearch totally different log shows up:

![image](https://cloud.githubusercontent.com/assets/89186/6666306/1a256b36-cbf4-11e4-8b2d-a9d7ab243859.png)

I'm running logstash 1.5.0.rc2.

**Comment by wiibaa** [comment] 2015-03-16 16:59
Sadly multiline codec and file input are not working well together
Root cause is here https://github.com/logstash-plugins/logstash-input-file/issues/10

**Comment by jordansissel** [comment] 2015-03-16 17:25
Let's track discussion on one ticket. I'll close this one in favor of https://github.com/logstash-plugins/logstash-input-file/issues/10

**Closed** 2015-03-16 17:49 UTC
