### ISSUE TITLE
Can't Reload Service

### ISSUE THREAD

**Issue by gauchoux** [elastic/logstash#10448] opened 2019-02-14 13:13 UTC
Hi,

I'm using Logstash 6.4 on a Linux server.
Before 6.4 I had the 2.x version and whenever I changed a config I would use the command "sudo service logstash reload" but it doesn't seem to work (exist?) anymore.
Here is the output I get when I try the command with 6.4:
![image](https://user-images.githubusercontent.com/23196279/52788760-370c6c00-3062-11e9-8038-139b43e9ec12.png)

I tried with systemctl too, but i get the same message:
![image](https://user-images.githubusercontent.com/23196279/52788796-54413a80-3062-11e9-81a8-036a675ae5c9.png)

Output of "systemctl status logstash.service":
![image](https://user-images.githubusercontent.com/23196279/52788929-be59df80-3062-11e9-9a79-b495965036d2.png)

I know I could use auto reload but it doesn't seem to work properly for me and I prefer the service reload method.
Can anyone help me out ?
Thanks

**Comment by gauchoux** [comment] 2019-02-19 10:10
Up.
Anyone has the same problem or a solution ?

**Comment by yaauie** [comment] 2019-02-19 17:48
> Up.
> Anyone has the same problem or a solution ?

This is not a forum for general usage questions, and bumping your own issues will not accelerate responses.

***

Since this is a general usage question and not a reproducible bug report or a clear feature request, I am closing this issue.

> Please post all product and debugging questions on our [forum](https://discuss.elastic.co/c/logstash).
> Your questions will reach our wider community members there, and if we confirm that there is a bug, then we can open a new issue here.
> 
> -- [Logstash Issue Template](https://raw.githubusercontent.com/elastic/logstash/master/.github/ISSUE_TEMPLATE.md)

Hopefully the following will help you get on track, but if you need more, please open a thread on the [forum](https://discuss.elastic.co/c/logstash).

***

The systemd job for Logstash does not have a `reload` command, which is why your attempt to invoke it fails.

The systemd job for Logstash is built using a library called [pleaserun](https://github.com/jordansissel/pleaserun), which abstracts away the implementation details of a variety of service runners, and pleaserun itself does not currently have a `reload` command, so support would need to be added there in order for Logstash jobs to get the command.

It looks like there was some work to add such in https://github.com/jordansissel/pleaserun/issues/58, but that work appears to have stalled out.

**Closed by yaauie** 2019-02-19 17:48 UTC
