### ISSUE TITLE
Extract all version info into one single file

### ISSUE THREAD

**Issue by suyograo** [elastic/logstash#5414] opened 2016-06-01 08:38 UTC
Today there are several places to update versions for different gems. We should extract all of them out and move them to a separate file under `pkg/version.yml`

The structure of version.yml can be:

```
logstash-core: 5.0.0-alpha3
# random comment here
logstash-core-plugin-api: 2.1.6
logstash-core-event-java: 5.0.0-alpha3
# any other dependency here:
```

Once this is done, its easy to set version by the unified build script.

**Comment by jsvd** [comment] 2016-06-01 13:02
my first approach was to make all version constants to pull from the YAML file.
The problem is that our gems, when packaged, won't contain the yaml file unless we replicate it to all core gems.
The alternative is having indeed a yaml file that is used as SSOT, but then a rake task is used to propagate changes in the YAML to the gemspecs.
Thoughts?

**Comment by suyograo** [comment] 2016-06-01 13:04
> The alternative is having indeed a yaml file that is used as SSOT, but then a rake task is used to propagate changes in the YAML to the gemspecs. 

Works. As long as there is just one place as source to truth

**Comment by suyograo** [comment] 2016-06-01 13:12
> but then a rake task is used to propagate changes in the YAML to the gemspecs.

This task should be called only by `rake set-version` though, right?

Is this the workflow you're thinking:

* `rake version:set --version 5.0.0-alpha4` will set this version in `pkg/version.yml` and then call another internal rake task to propagate this to all the Gems?
* `rake version:get` outputs the current version.
* `rake artifact:tar` will build a snapshot artifact from the current sha and version: 5.0.0-alpha4-snapshot.
* `rake artifact:tar --release` will build a release artifact from the current sha and version: 5.0.0-alpha4.

**Comment by jsvd** [comment] 2016-06-01 13:24
I'm thinking of:

* `rake version:sync`: check if it's necessary to propagate the changes and does it if so. This can be called at the start of ANY rake task automatically, like we do now for vendoring jruby.
* `rake version:set[5.0.0-alpha4]` which changes the yaml file and then calls `rake version:sync`
* `rake version:show` that prints the version of the logstash package
   - `rake version:show[all|logstash|logstash-core|logstash-core-event|..]` show version of subcomponent or all of them
* `rake artifact:tar` create a snapshot artifact from current sha with CURRENT.VERSION-snapshot and writes to a file latest.build `commit_sha1:file_sha1`
* `rake artifact:tar[release]` or `RELEASE=1 rake artifact:tar` reads latest.build, checks if latest commit sha is `commit_sha1` and if there's a local artifact `file_sha1`. If so, copies file with new name and finishes, otherwise builds from scratch. we can have a --force or FORCE=1 flag to force the creation of the build.

**Comment by suyograo** [comment] 2016-06-01 14:15
@jsvd +1, the flow makes sense, except for one thing:

> and writes to a file latest.build

I don't think we need sha for the first iteration. IMO, this complicates things, maybe just pick the current sha and build release for now?

Also +1 on `rake artifact:tar[release]` instead of `RELEASE=1 rake artifact:tar`

**Comment by jsvd** [comment] 2016-06-01 14:19
using environment variables is useful for stuff like RELEASE=1 rake artifact:tar artifact:deb artifact:zip

As for the latest.build, the idea is to avoid doing a full build with a --release. in most cases we should already have a snapshot build from the sha1. it's just a matter of renaming

**Comment by suyograo** [comment] 2016-06-01 14:24
The problem with env variable `RELEASE=1` is when some one sets it (previous run, or whatever) and forgets about it. We may be doing irreversible stuff for release, so I would be concerned about an environment variable.. WDYT?

**Comment by jsvd** [comment] 2016-06-01 14:25
well if a script is doing:
```
export RELEASE=1
rake artifact:tar
```
it's a very very bad sign..correct approach should be `RELEASE=1 rake artifact:tar`

anyway, I'm ok with not implementing the env var for now

**Comment by suyograo** [comment] 2016-06-01 14:31
whats the rake way of passing in flags?

**Comment by jsvd** [comment] 2016-06-01 14:36
`rake task[flag1, flag2]` is the rake way

**Comment by jsvd** [comment] 2016-06-03 13:43
one concern with `rake version:set[5.0.0-alpha4]` is that we can expect that all logstash components (global package, core, event, event-java) will be in sync, but logstash-core-plugin-api has different versioning that will only be bumped during release builds, not snapshots.

So are we OK that `rake version:` tasks (set, show, sync) don't manage logstash-core-plugin-api?

**Comment by jsvd** [comment] 2016-06-03 13:52
current example of rake version:sync / rake version:show (this is still WIP):

```
% rake version:show
logstash: 5.0.0.dev
logstash-core: 5.0.0.dev
logstash-core-event: 5.0.0.dev
logstash-core-event-java: 5.0.0.dev
% vim versions.yml # edit and bump versions
% cat versions.yml
logstash: 5.0.1
logstash-core: 5.0.1
logstash-core-event: 5.0.1
logstash-core-event-java: 5.0.1
% rake version:sync
Updating "logstash" from "5.0.0.dev" to "5.0.1"
Updating "logstash-core" from "5.0.0.dev" to "5.0.1"
Updating "logstash-core-event" from "5.0.0.dev" to "5.0.1"
Updating "logstash-core-event-java" from "5.0.0.dev" to "5.0.1"
% rake version:show
logstash: 5.0.1
logstash-core: 5.0.1
logstash-core-event: 5.0.1
logstash-core-event-java: 5.0.1
% git diff logstash-*
diff --git a/logstash-core-event-java/lib/logstash-core-event-java/version.rb b/logstash-core-event-java/lib/logstash-core-event-java/version.rb
index cfc6a16..2dce911 100644
--- a/logstash-core-event-java/lib/logstash-core-event-java/version.rb
+++ b/logstash-core-event-java/lib/logstash-core-event-java/version.rb
@@ -5,4 +5,4 @@
 # Note to authors: this should not include dashes because 'gem' barfs if
 # you include a dash in the version string.
 
-LOGSTASH_CORE_EVENT_JAVA_VERSION = "5.0.0.dev"
+LOGSTASH_CORE_EVENT_JAVA_VERSION = "5.0.1"
diff --git a/logstash-core-event/lib/logstash-core-event/version.rb b/logstash-core-event/lib/logstash-core-event/version.rb
index e1e0774..2b412a3 100644
--- a/logstash-core-event/lib/logstash-core-event/version.rb
+++ b/logstash-core-event/lib/logstash-core-event/version.rb
@@ -5,4 +5,4 @@
 # Note to authors: this should not include dashes because 'gem' barfs if
 # you include a dash in the version string.
 
-LOGSTASH_CORE_EVENT_VERSION = "5.0.0.dev"
+LOGSTASH_CORE_EVENT_VERSION = "5.0.1"
diff --git a/logstash-core-plugin-api/lib/logstash-core-plugin-api/version.rb b/logstash-core-plugin-api/lib/logstash-core-plugin-api/version.rb
index ced5939..a0587fa 100644
--- a/logstash-core-plugin-api/lib/logstash-core-plugin-api/version.rb
+++ b/logstash-core-plugin-api/lib/logstash-core-plugin-api/version.rb
@@ -1,2 +1,2 @@
 # encoding: utf-8
-LOGSTASH_CORE_PLUGIN_API = "2.0.0"
+LOGSTASH_CORE_PLUGIN_API = "2.0.1"
diff --git a/logstash-core/lib/logstash-core/version.rb b/logstash-core/lib/logstash-core/version.rb
index 737441c..4bb97a3 100644
--- a/logstash-core/lib/logstash-core/version.rb
+++ b/logstash-core/lib/logstash-core/version.rb
@@ -5,4 +5,4 @@
 # Note to authors: this should not include dashes because 'gem' barfs if
 # you include a dash in the version string.
 
-LOGSTASH_CORE_VERSION = "5.0.0.dev"
+LOGSTASH_CORE_VERSION = "5.0.1"
diff --git a/logstash-core/lib/logstash/version.rb b/logstash-core/lib/logstash/version.rb
index 676dde5..35735b0 100644
--- a/logstash-core/lib/logstash/version.rb
+++ b/logstash-core/lib/logstash/version.rb
@@ -11,4 +11,4 @@
 #       eventually this file should be in the root logstash lib fir and dependencies in logstash-core should be
 #       fixed.
 
-LOGSTASH_VERSION = "5.0.0.dev"
+LOGSTASH_VERSION = "5.0.1"
```

**Comment by suyograo** [comment] 2016-06-03 14:01
Yeah we should be ok with https://github.com/elastic/logstash/issues/5414#issuecomment-223582141

The plugin-api is only expected to be published after promoting a release candidate to a release, so it can be bumped up and published after that. Can we add `rake version:set logstash-core-plugin-api 2.12.0`.

Also `version:sync` should be careful to update _all_ version references in gemspecs. For example, another caveat is pre-releases. `5.0.0-alpha1` will become `5.0.0.alpha1` in gemspecs

**Comment by jsvd** [comment] 2016-06-21 14:31
this has been implemented by https://github.com/elastic/logstash/issues/5460

**Closed by jsvd** 2016-06-21 14:31 UTC
Labels: enhancement, packaging, unified release
