### ISSUE TITLE
Getting high cpu when we use multiline plugin with logstash input journald plugins in logstash.........

### ISSUE THREAD

**Issue by jain108shubhamtbt** [elastic/logstash#9975] opened 2018-09-11 10:13 UTC
Getting logstash logs : 

[2018-09-11T12:26:04,265][INFO ][logstash.filters.multiline] Grok loading patterns from file {:path=>"/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-patterns-core-4.0.2/patterns/mongodb"}
[2018-09-11T12:26:04,266][INFO ][logstash.filters.multiline] Grok loading patterns from file {:path=>"/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-patterns-core-4.0.2/patterns/nagios"}
[2018-09-11T12:26:04,267][INFO ][logstash.filters.multiline] Grok loading patterns from file {:path=>"/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-patterns-core-4.0.2/patterns/linux-syslog"}
[2018-09-11T12:26:04,267][INFO ][logstash.filters.multiline] Grok loading patterns from file {:path=>"/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-patterns-core-4.0.2/patterns/bro"}
[2018-09-11T12:26:04,267][INFO ][logstash.filters.multiline] Grok loading patterns from file {:path=>"/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-patterns-core-4.0.2/patterns/grok-patterns"}
[2018-09-11T12:26:04,268][INFO ][logstash.filters.multiline] Grok loading patterns from file {:path=>"/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-patterns-core-4.0.2/patterns/java"}
[2018-09-11T12:26:04,269][INFO ][logstash.filters.multiline] Grok loading patterns from file {:path=>"/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-patterns-core-4.0.2/patterns/aws"}
[2018-09-11T12:26:04,270][INFO ][logstash.filters.multiline] Grok loading patterns from file {:path=>"/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-patterns-core-4.0.2/patterns/redis"}
[2018-09-11T12:26:04,270][INFO ][logstash.filters.multiline] Grok loading patterns from file {:path=>"/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-patterns-core-4.0.2/patterns/postgresql"}
[2018-09-11T12:26:04,270][INFO ][logstash.filters.multiline] Grok loading patterns from file {:path=>"/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-patterns-core-4.0.2/patterns/bacula"}
[2018-09-11T12:26:04,271][INFO ][logstash.filters.multiline] Grok loading patterns from file {:path=>"/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-patterns-core-4.0.2/patterns/junos"}
[2018-09-11T12:26:04,271][INFO ][logstash.filters.multiline] Grok loading patterns from file {:path=>"/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-patterns-core-4.0.2/patterns/firewalls"}
[2018-09-11T12:26:04,272][INFO ][logstash.filters.multiline] Grok loading patterns from file {:path=>"/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-patterns-core-4.0.2/patterns/mcollective"}

**Comment by jain108shubhamtbt** [comment] 2018-09-11 10:14
Please help me .

**Comment by yaauie** [comment] 2018-09-14 18:46
I am closing this issue because it is a debugging question and not a bug or feature request.

> Please post all product and debugging questions on our [forum](https://discuss.elastic.co/c/logstash). Your questions will reach our wider community members there, and if we confirm that there is a bug, then we can open a new issue here.
> -- [ISSUE_TEMPLATE](https://github.com/elastic/logstash/blob/master/.github/ISSUE_TEMPLATE.md)

***

Additionally, the log messages you posted indicate that a Grok Filter is taking ~7ms to load pattern definitions from about a dozen definition files, which does not indicate the "high cpu" being reported.

When you do post in the forums, please include relevant pipeline configuration, sample input, version data, etc., so that the people who see your post can have an idea of where to start.

**Closed by yaauie** 2018-09-14 18:46 UTC
