### ISSUE TITLE
logstash-plugin update behaves oddly

### ISSUE THREAD

**Issue by Paladin** [elastic/logstash#5580] opened 2016-07-01 15:08 UTC
- Version: logstash 2.3.3 (elasticsearch 2.3.3 as well)
- Operating System: Centos7

Went on an updating spree for all the plugins I'm using (BTW, it might be nice to implement "gem outdated" in this context) and I ran into this:

    $> bin/logstash-plugin update logstash-output-elasticsearch
    
    You are updating logstash-output-elasticsearch to a new version 4.1.1, which may not be compatible with 2.7.0. are you sure you want to proceed (Y/N)?
    Y
    Updating logstash-output-elasticsearch
    Updated logstash-output-elasticsearch 2.7.0 to 2.7.1

After this experience, tried two other approaches in an attempt to workaround it:
uninstall/install the plugin (ended up with 2.7.1 again)
ran the update a second time (on 2.7.1), it repeated the are you sure question (2.7.1 instead of 2.7.0 in the text above) then finished with "No plugin updated."

if you're only going to update to 2.7.1, logstash, why ask me if I'm sure I want to update to 4.1.1?
How does one update to 4.1.1?
If I'm not supposed to, why offer it as an option?

**Comment by jordansissel** [comment] 2016-07-08 16:19
Agreed this is weird behavior

**Comment by AGirin** [comment] 2016-08-04 18:23
Same hereL
https://github.com/elastic/logstash/issues/5727

**Comment by suyograo** [comment] 2016-08-04 18:29
We are working on removing this warning.

**Comment by tomerilp** [comment] 2016-08-11 14:11
Did you manage to update the throttle plugin?
I am facing the same issue

**Comment by jsvd** [comment] 2016-09-02 14:04
closing this in favor of https://github.com/elastic/logstash/issues/5858, since the original warning message is gone and the problem is now that logstash 2.4 should allow updating plugins across major versions as long as the logstash-core-plugin-api constraint is respected.

**Closed by jsvd** 2016-09-02 14:04 UTC
Labels: plugin manager
