### ISSUE TITLE
Error output while executing rspec for logstash event - Tests don't fail

### ISSUE THREAD

**Issue by breml** [elastic/logstash#4762] opened 2016-03-04 17:39 UTC
While debugging https://github.com/elastic/logstash/pull/4425#issuecomment-192006325 I found an other issue in current master (https://github.com/elastic/logstash/tree/00947a57de3f306250b8db1852303349d9109441) while executing the rspec tests for logstash event. The problem shows up only sporadically, for example with seed 3320, 16506 and 42821.

```
$ bin/rspec --seed 3320 logstash-core-event/spec/logstash/event_spec.rb
Using Accessor#strict_set for specs
Run options: exclude {:redis=>true, :socket=>true, :performance=>true, :couchdb=>true, :elasticsearch=>true, :elasticsearch_secure=>true, :export_cypher=>true, :integration=>true, :windows=>true}
..........Error parsing @timestamp string value=foo
Unrecognized @timestamp value type=class java.lang.Long
....................................................................................................................................................

Finished in 1.71 seconds (files took 1.81 seconds to load)
158 examples, 0 failures

Randomized with seed 3320
```

This seems to be a problem in the ordering of the rspec tests or inproper setup/tear down of tests.

@purbon and @suyograo FYI: is not related to https://github.com/elastic/logstash/issues/4370

**Comment by jordansissel** [comment] 2016-03-04 19:49
Is this a problem? i don't necessarily expect test output to be silent.

**Comment by breml** [comment] 2016-03-04 22:17
@jordansissel you are right, output is not necessarily a problem, but for me it is at least confusing if I get an output saying `Error parsing @timestamp string value=foo` and `Unrecognized @timestamp value type=class java.lang.Long`. It distracts me from the impact of my actual work/changes if helping to improve logstash.
Additionally these outputs are only printed sporadically and this confuses me even more.

**Comment by purbon** [comment] 2016-03-07 09:21
I agree with @breml, this is not necessary a problem, but is an smell, especially if the output starts with `Error` or `Unrecognized`, we should verify if this is an actually error or not. 

On the other side, I prefere test not to output anything to stdout, they make debugging strange. this related with our plugins test that also output stuff, that should be for sure ironed out.

**Comment by purbon** [comment] 2016-03-07 09:40
After checking source code, https://github.com/elastic/logstash/blob/master/logstash-core-event-java/src/main/java/com/logstash/Event.java#L248-L276 this looks to me like only a sign not too verbose logger usage inside test :+1:, definetly something to clean up, but for now I think is more of a kind of a low hanging fruit, what do you think? @breml open for improvements here for sure, PR very welcome :+1:

**Comment by breml** [comment] 2016-03-08 12:54
@purbon I will not touch the java code, since I am not familiar with it.

I ask my self, what is the value in logging thous two cases (else and catch) if it always falls back to `return Timestamp.now();`.

**Comment by jakelandis** [comment] 2017-06-09 15:36
I appears that some refactoring since the time of this issue has removed the extra output from the rspec.   Can not reproduce, closing. 

```
 bin/rspec --seed 3320 logstash-core/spec/logstash/event_spec.rb
--- jar coordinate com.fasterxml.jackson.core:jackson-databind already loaded with version 2.7.4 - omit version 2.7.3
--- jar coordinate com.fasterxml.jackson.core:jackson-annotations already loaded with version 2.7.0 - omit version 2.7.3
--- jar coordinate com.fasterxml.jackson.module:jackson-module-afterburner already loaded with version 2.7.4 - omit version 2.7.3
--- jar coordinate com.fasterxml.jackson.core:jackson-core already loaded with version 2.7.4 - omit version 2.7.3
ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console.
Sending Logstash's logs to  which is now configured via log4j2.properties
Run options: exclude {:redis=>true, :socket=>true, :performance=>true, :couchdb=>true, :elasticsearch=>true, :elasticsearch_secure=>true, :export_cypher=>true, :integration=>true, :windows=>true}
.....................................

Finished in 0.376 seconds (files took 11.99 seconds to load)
37 examples, 0 failures

Randomized with seed 3320
```

**Closed by jakelandis** 2017-06-09 15:36 UTC
Labels: adoptme, low hanging fruit, tests-infra
