### ISSUE TITLE
Logstash new type of error, encountered it for the first time, need help ASAP.

### ISSUE THREAD

**Issue by tushar1402** [elastic/logstash#12021] opened 2020-06-14 20:07 UTC
- Version: 7.1.1
- Operating System: Windows 10
- Config File (if you have sensitive info, please remove it):
- Sample Data:
- Steps to Reproduce:

Hi I am facing a new kind of error when I try to run my logstash. This error is coming from the beginning and I am not able to find any solution on the open domain. Can the logstash community help me out to solve this error? 
Following is the error:
**Error: Could not find or load main class Stack\logstash-7.7.1\logstash-7.7.1\logstash-core\lib\jars\animal-sniffer-annotations-1.14.jar;C:\ELK**

Thanks in advance.

**Comment by yaauie** [comment] 2020-06-15 14:45
Typically we attempt to do debugging-style discussions in [the forum](https://discuss.elastic.co/c/elastic-stack/logstash/14), and reserve the Issues section on Github for known issues with clear reproduction steps:

> Please post all product and debugging questions on our [forum](https://discuss.elastic.co/c/logstash). Your questions will reach our wider community members there, and if we confirm that there is a bug, then we can open a new issue here.
>
> -- [.github/ISSUE_TEMPLATE.md](https://github.com/elastic/logstash/blob/master/.github/ISSUE_TEMPLATE.md)

I'm closing this issue, but hope the following helps -- please open a topic in the forums if you need further assistance.

The `.zip` distribution available via elastic.co contains a `bin/logstash.bat` that is intended to be the primary path to execution on Windows, but if you are downloading the source directly from Github you will need to _build_ the project yourself before it can be used. Please keep in mind that the source of the `master` branch is _forward-facing_, containing speculative work and breaking changes, and is not considered to be stable.

**Closed by yaauie** 2020-06-15 14:45 UTC
