### ISSUE TITLE
Configtest doesn't detect problem with configuration

### ISSUE THREAD

**Issue by marek-obuchowicz** [elastic/logstash#5342] opened 2016-05-21 13:45 UTC
logstash-2.3.2 shows OK when running configtests, but fails to start:

```
./logstash agent -t -f /etc/logstash-indexer/conf.d
Configuration OK
```

```
./logstash agent -f /etc/logstash-indexer/conf.d
Settings: Default pipeline workers: 8
Unknown setting 'protocol' for elasticsearch {:level=>:error}
Pipeline aborted due to error {:exception=>#<LogStash::ConfigurationError: Something is wrong with your configuration.>
```

Output config is:

```
    elasticsearch {
      hosts => ["mgm-elk-00:9200", "mgm-elk-01:9200"]
      protocol => "http"
      flush_size => 1500
      idle_flush_time => 5
      index => "logstash-%{environment}-lumberjack-%{+YYYY.MM.dd}"
      document_type => "logs"
    }
```

**Comment by jsvd** [comment] 2016-05-27 14:08
Seems to be a change in the OutputDelegator that delays the creation of output plugins, but I need to investigate further.
Interestingly, it no longer happens in 5.x

```
/tmp/logstash-5.0.0-alpha2 % bin/logstash -e "output { stdout { meh => hey } }" -t
Unknown setting 'meh' for stdout {:level=>:error}
The given configuration is invalid. Reason: Something is wrong with your configuration. {:level=>:fatal}
1 /tmp/logstash-2.3.2 % bin/logstash -e "output { stdout { meh => hey } }" -t
Configuration OK
```

**Comment by jsvd** [comment] 2016-05-27 14:30
test that reproduces the issue:

```diff
diff --git a/logstash-core/spec/logstash/pipeline_spec.rb b/logstash-core/spec/logstash/pipeline_spec.rb
index 33110e5..dc3a6de 100644
--- a/logstash-core/spec/logstash/pipeline_spec.rb
+++ b/logstash-core/spec/logstash/pipeline_spec.rb
@@ -92,6 +92,34 @@ describe LogStash::Pipeline do
   let(:safe_thread_count)       { 1 }
   let(:override_thread_count)   { 42 }
 
+  describe "#initialize" do
+    before(:each) do
+      allow(LogStash::Plugin).to receive(:lookup).with("input", "dummyinput").and_return(DummyInput)
+      allow(LogStash::Plugin).to receive(:lookup).with("codec", "plain").and_return(DummyCodec)
+      allow(LogStash::Plugin).to receive(:lookup).with("output", "dummyoutput").and_return(DummyOutput)
+      allow(LogStash::Plugin).to receive(:lookup).with("filter", "dummyfilter").and_return(DummyFilter)
+    end
+
+    context "with incorrect input plugin options" do
+      let(:config_string) { "input { dummyinput { fakeflag => yep } }" }
+      it "should raise exception" do
+        expect { described_class.new(config_string) }.to raise_error
+      end
+    end
+    context "with incorrect filter plugin options" do
+      let(:config_string) { "filter { dummyfilter { fakeflag => yep } }" }
+      it "should raise exception" do
+        expect { described_class.new(config_string) }.to raise_error
+      end
+    end
+    context "with incorrect output plugin options" do
+      let(:config_string) { "input { dummyinput {} } output { dummyoutput { fakeflag => yep } }" }
+      it "should raise exception" do
+        expect { described_class.new(config_string) }.to raise_error
+      end
+    end
+  end
+
   describe "defaulting the pipeline workers based on thread safety" do
     before(:each) do
       allow(LogStash::Plugin).to receive(:lookup).with("input", "dummyinput").and_return(DummyInput)
```

fails on 2.x:

```
logstash (git)-[2.x] % bin/rspec ./logstash-core/spec/logstash/pipeline_spec.rb:95
Using Accessor#strict_set for specs
Run options:
  include {:locations=>{"./logstash-core/spec/logstash/pipeline_spec.rb"=>[95]}}
  exclude {:redis=>true, :socket=>true, :performance=>true, :couchdb=>true, :elasticsearch=>true, :elasticsearch_secure=>true, :export_cypher=>true, :integration=>true, :windows=>true}
..F

Failures:

  1) LogStash::Pipeline#initialize with incorrect output plugin options should raise exception
     Failure/Error: expect { described_class.new(config_string) }.to raise_error
       expected Exception but nothing was raised
     # ./logstash-core/spec/logstash/pipeline_spec.rb:118:in `(root)'
     # ./vendor/bundle/jruby/1.9/gems/rspec-wait-0.0.8/lib/rspec/wait.rb:46:in `(root)'
     # ./lib/bootstrap/rspec.rb:12:in `(root)'

Finished in 0.08 seconds (files took 0.817 seconds to load)
3 examples, 1 failure

Failed examples:

rspec ./logstash-core/spec/logstash/pipeline_spec.rb:117 # LogStash::Pipeline#initialize with incorrect output plugin options should raise exception

Randomized with seed 15956
```

**Comment by jsvd** [comment] 2017-11-06 11:09
This is fixed in 5.x as noted above, closing.

**Closed by jsvd** 2017-11-06 11:09 UTC
Labels: bug
