### ISSUE TITLE
 Error: org.postgresql.Driver not loaded. Are you sure you've included the correct jdbc driver in :jdbc_driver_library?

### ISSUE THREAD

**Issue by mahsare** [elastic/logstash#10873] opened 2019-06-19 13:08 UTC
I have a postgres database and just want to ingest it to elasticsearch using logstash. I've just followed the official documetation on https://www.elastic.co/blog/logstash-jdbc-input-plugin and until now I have the following configuration file for logstash:

# file: simple-out.conf
input {
    jdbc {
        # Postgres jdbc connection string to our database, mydb
        jdbc_connection_string => "jdbc:postgresql://localhost:5432/mydb"
        # The user we wish to execute our statement as
        jdbc_driver_library => "/home//user/logstash-7.1.1/lib/postgresql-9.4-1204.jdbc42.jar"
        jdbc_user => "postgres"
        # The path to our downloaded jdbc driver
        # The name of the driver class for Postgresql
        jdbc_driver_class => "org.postgresql.Driver"
        # our query
        statement => "SELECT * from contacts"
    }
}
output {
    stdout { codec => json_lines }
}
~  

but after running the command : bin/logstash -f simple-out.conf on the linux terminal, I've got the following error:
**r: failed to coerce jdk.internal.loader.ClassLoaders$AppClassLoader to java.net.URLClassLoader>}**
and 
**Error: org.postgresql.Driver not loaded. Are you sure you've included the correct jdbc driver in :jdbc_driver_library?
  Exception: LogStash::ConfigurationError**
I've tried different jdbc postgres driver, but the error still remains,
How can i fix the error?

- Version: logstash 7.1.1, java 11
- Operating System:ubuntu 18.04

**Comment by guyboertje** [comment] 2019-06-19 15:03
This is a known issue and we are working on a fix

See [this issue](https://github.com/logstash-plugins/logstash-input-jdbc/issues/331#issuecomment-496899391)

Duplicate of #10753 

Closing

**Closed by guyboertje** 2019-06-19 15:03 UTC
