### ISSUE TITLE
S3 Output: duplicate files

### ISSUE THREAD

**Issue by clebio** [elastic/logstash#4389] opened 2015-12-22 17:26 UTC
# Background

I'm attempting to have **filebeat send logs from several servers to a single Logstash instance, and then write those logs to S3**. I have several beat listeners on different ports open on the Logstash server, but even when only one filebeat service has connected to the logstash server, I get multiple copies of the log file written to separate paths in S3.

I have a single Logstash server and a cluster of 3 servers for Kafka.

I'm using Ansible for provisioning and adhoc commands, hence the presence of the commands below. But beside running the same diagnostic commands on multiple servers, Ansible is not germane to this issue, in my opinion.

# Overview

My Logstash configs for the various beats listeners:
```bash
$ ansible -i ~/dev/ec2.py $AUTH tag*logstash -m shell -a 'cat /etc/logstash/conf.d/*'
172.19.1.44 | success | rc=0 >>
# kafka.conf
input {
  beats {
    port => 5047
    type => "kafka"
  }
}
output {
  s3 {
    bucket => "app-logs/kafka"
    tags => "kafka"
    time_file => 1
    temporary_directory => "/mnt/logstash/kafka"
  }

# storm.conf
input {
  beats {
    port => 5045
    type => "storm"
  }
}
output {
  s3 {
    bucket => "app-logs/storm"
    tags => "storm"
    time_file => 1
    temporary_directory => "/mnt/logstash/storm"
  }

# zookeeper.conf
}
input {
  beats {
    port => 5046
    type => "zookeeper"
  }
}
output {
  s3 {
    bucket => "app-logs/zookeeper"
    tags => "zookeeper"
    time_file => 1
    temporary_directory => "/mnt/logstash/zookeeper"
  }
}
```

I verify that *only the Kafka beat* is connected (port 5047):
```bash
$ ansible -i ~/dev/ec2.py $AUTH tag*logstash -m shell -a 'netstat -nap | grep :504' -b
172.19.1.44 | success | rc=0 >>
tcp6       0      0 :::5046                 :::*                    LISTEN      30863/java
tcp6       0      0 :::5047                 :::*                    LISTEN      30863/java
tcp6       0      0 :::5044                 :::*                    LISTEN      30863/java
tcp6       0      0 :::5045                 :::*                    LISTEN      30863/java
tcp6       0     12 172.19.1.44:5047        172.19.2.180:55469      ESTABLISHED 30863/java
```

# Main issue
## Expected outcome

I'd expect to find files from the Kafka filebeat in the `s3://app-logs/kafka/` path, and no other files on S3 at this point.

## Actual outcome
On S3, I have several copies of the Kafka log, each written to sub-paths that match the four different listeners. While the file sizes are slightly different, I've copied these from S3 to my machine and verified that they're all Kafka logs. I *suspect* that the files are getting written to the different S3 paths at _slightly_ different times, hence the _slightly_ different file sizes.

```bash
$ aws s3 ls --recursive s3://app-logs
2015-12-22 08:47:39    3172593 kafka/ls.s3.ip-172-19-1-44.2015-12-22T14.46.tag_kafka.part0.txt
2015-12-22 08:47:39    3217387 storm/ls.s3.ip-172-19-1-44.2015-12-22T14.46.tag_storm.part0.txt
2015-12-22 08:47:39    3231906 zookeeper/ls.s3.ip-172-19-1-44.2015-12-22T14.46.tag_zookeeper.part0.txt
```

**Comment by clebio** [comment] 2015-12-22 17:28
Sorry, should have mentioned, I'm using `filebeat_1.0.1_amd64.deb` and `logstash_2.1.1-1_all.deb`, both from `https://download.elastic.co/logstash`.

**Comment by suyograo** [comment] 2015-12-23 02:53
@clebio thanks for the detailed report. We'll take a look soon

**Comment by clebio** [comment] 2015-12-29 17:08
Hi again. I'm trying to debug a bit further.

## Manual log messaging into filebeat

on a throw-away server with Filebeat listening:
```bash
# /etc/filebeat/filebeat.yml
filebeat:
  shipper:
      tags: ["testing", ]

  prospectors:
    -
      paths:
        - "/var/log/testing/*.log"
output:
  logstash:
    enabled: true
    max_retries: -1

    hosts:
    - "172.19.1.44:5044"
```

    $ echo "<<`date`>> ping" >> /var/log/testing/app.log

On the same, original logstash server, with all other filebeat producers turned off:
```bash
# find /mnt/logstash/ -cmin 1 -type f
/mnt/logstash/kafka/ls.s3.ip-172-19-1-44.2015-12-29T16.17.part1.txt
/mnt/logstash/default/ls.s3.ip-172-19-1-44.2015-12-29T16.18.part3.txt
/mnt/logstash/zookeeper/ls.s3.ip-172-19-1-44.2015-12-29T16.18.part6.txt
/mnt/logstash/storm/ls.s3.ip-172-19-1-44.2015-12-29T16.17.part1.txt

# find /mnt/logstash/ -cmin 1 -type f -exec cat {} \;
2015-12-29T16:18:54.439Z ip-172-19-2-188 <<Tue Dec 29 16:18:46 UTC 2015>> ping
2015-12-29T16:18:54.439Z ip-172-19-2-188 <<Tue Dec 29 16:18:46 UTC 2015>> ping
2015-12-29T16:18:54.439Z ip-172-19-2-188 <<Tue Dec 29 16:18:46 UTC 2015>> ping
2015-12-29T16:18:54.439Z ip-172-19-2-188 <<Tue Dec 29 16:18:46 UTC 2015>> ping

# netstat -nap | grep ':504'
tcp        1      0 172.19.1.44:41838       172.19.1.44:5044        CLOSE_WAIT  25403/filebeat
tcp6       0      0 :::5046                 :::*                    LISTEN      25769/java
tcp6       0      0 :::5047                 :::*                    LISTEN      25769/java
tcp6       0      0 :::5044                 :::*                    LISTEN      25769/java
tcp6       0      0 :::5045                 :::*                    LISTEN      25769/java
tcp6       0      0 172.19.1.44:5044        172.19.2.188:39012      ESTABLISHED 25769/java
```

## Filebeat input with non-S3 output

Changed the output plugin from S3 to (local) file.
```bash
# grep 'output' -A 4 /etc/logstash/conf.d/*
/etc/logstash/conf.d/kafka.conf:output {
/etc/logstash/conf.d/kafka.conf-  file {
/etc/logstash/conf.d/kafka.conf-    path => "/tmp/logstash/kafka"
/etc/logstash/conf.d/kafka.conf-  }
/etc/logstash/conf.d/kafka.conf-}
--
/etc/logstash/conf.d/default-default.conf:output {
/etc/logstash/conf.d/default-default.conf-  file {
/etc/logstash/conf.d/default-default.conf-    path => "/tmp/logstash/default"
/etc/logstash/conf.d/default-default.conf-  }
/etc/logstash/conf.d/default-default.conf-}
--
/etc/logstash/conf.d/storm.conf:output {
/etc/logstash/conf.d/storm.conf-  file {
/etc/logstash/conf.d/storm.conf-    path => "/tmp/logstash/storm"
/etc/logstash/conf.d/storm.conf-  }
/etc/logstash/conf.d/storm.conf-}
--
/etc/logstash/conf.d/zookeeper.conf:output {
/etc/logstash/conf.d/zookeeper.conf-  file {
/etc/logstash/conf.d/zookeeper.conf-    path => "/tmp/logstash/zookeeper"
/etc/logstash/conf.d/zookeeper.conf-  }
/etc/logstash/conf.d/zookeeper.conf-}
```

One open connection, for “default”:
```bash
u# netstat -nap | grep ':504'
tcp        1      0 172.19.1.44:41885       172.19.1.44:5044        CLOSE_WAIT  29568/filebeat
tcp6       0      0 :::5046                 :::*                    LISTEN      29750/java
tcp6       0      0 :::5047                 :::*                    LISTEN      29750/java
tcp6       0      0 :::5044                 :::*                    LISTEN      29750/java
tcp6       0      0 :::5045                 :::*                    LISTEN      29750/java
tcp6       0      0 172.19.1.44:5044        172.19.2.188:39013      ESTABLISHED 29750/java
```
    $ echo "<<`date`>> ping" >> /var/log/testing/app.log

Same log message in each output file:
```bash
# for FILE in $(ls /tmp/logstash/*); do echo -n "$FILE: " && cat $FILE; done
/tmp/logstash/kafka: {"message":"<<Tue Dec 29 17:05:17 UTC 2015>> ping","@version":"1","@timestamp":"2015-12-29T17:05:17.981Z","beat":{"hostname":"ip-172-19-2-188","name":"ip-172-19-2-188"},"count":1,"fields":null,"input_type":"log","offset":29299,"source":"/var/log/testing/app.log","type":"log","host":"ip-172-19-2-188","messages":"<<Tue Dec 29 17:05:17 UTC 2015>> ping","tags":["_grokparsefailure"]}
/tmp/logstash/default: {"message":"<<Tue Dec 29 17:05:17 UTC 2015>> ping","@version":"1","@timestamp":"2015-12-29T17:05:17.981Z","beat":{"hostname":"ip-172-19-2-188","name":"ip-172-19-2-188"},"count":1,"fields":null,"input_type":"log","offset":29299,"source":"/var/log/testing/app.log","type":"log","host":"ip-172-19-2-188","messages":"<<Tue Dec 29 17:05:17 UTC 2015>> ping","tags":["_grokparsefailure"]}
/tmp/logstash/storm: {"message":"<<Tue Dec 29 17:05:17 UTC 2015>> ping","@version":"1","@timestamp":"2015-12-29T17:05:17.981Z","beat":{"hostname":"ip-172-19-2-188","name":"ip-172-19-2-188"},"count":1,"fields":null,"input_type":"log","offset":29299,"source":"/var/log/testing/app.log","type":"log","host":"ip-172-19-2-188","messages":"<<Tue Dec 29 17:05:17 UTC 2015>> ping","tags":["_grokparsefailure"]}
/tmp/logstash/zookeeper: {"message":"<<Tue Dec 29 17:05:17 UTC 2015>> ping","@version":"1","@timestamp":"2015-12-29T17:05:17.981Z","beat":{"hostname":"ip-172-19-2-188","name":"ip-172-19-2-188"},"count":1,"fields":null,"input_type":"log","offset":29299,"source":"/var/log/testing/app.log","type":"log","host":"ip-172-19-2-188","messages":"<<Tue Dec 29 17:05:17 UTC 2015>> ping","tags":["_grokparsefailure"]}
```

# Conclusion

The duplication does not seem to be related to S3, but rather earlier in the pipeline, when Logstash is writing to local temp files. The filebeat input plugin *appears* well-behaved, in that the correct ports are listened for, and only one connection is established per upstream filebeat producer. (incidentally, OSX's Notes wants to autocorrect "filebeat" to "filbert".)

Anyway, hopefully that helps isolate the issue. I'm grateful for any feedback on what might be happening internally to Logstash.

**Comment by clebio** [comment] 2016-01-08 14:24
Hello again. Can I get some guidance on this? I'm willing to try other configurations or debug further, but not sure how to proceed right now.

**Comment by ph** [comment] 2016-03-11 17:58
Okay this is not actually a problem with logstash, this is how it is designed. Let me give you a bit of background with how it work.

Logstash actually compile all your configuration files it will merge all the inputs, filters and outputs configuration. (from all your files into **one**)

Taking this configuration:

```
input {
 file { path => "/tmp/hello.log" }
 type => "normal"
}
output {
 file { path => "helloA.log"}
}
output {
 file { path => "helloB.log"}
}
output {
 file { path => "helloC.log"}
}
```

This will become this for logstash after the compiler of the configuration file.

```
input {
 file { path => "/tmp/hello.log" }
 type => "normal"
}
output {
 file { path => "helloA.log"}
 file { path => "helloB.log"}
 file { path => "helloC.log"}
}
```

So all elements read from the `hello.log` will be written to `helloA.log` `helloB.log`, `helloC.log`.
To control where the events should go you need to use conditionals and data from your events to tell logstash where to send them. See this docs https://www.elastic.co/guide/en/logstash/current/event-dependent-configuration.html

I will be closing this issue, since this is not a bug but a configuration issue.

**Closed by ph** 2016-03-11 17:58 UTC
Labels: bug, unconfirmed
