### ISSUE TITLE
Issues with different version name schemas between rubygems and maven.

### ISSUE THREAD

**Issue by purbon** [elastic/logstash#2937] opened 2015-04-02 08:12 UTC
Moved from the logstash-input-log4j repo to here as is where it belongs:

--
I got on step further, having a successfull bundle install by using specific logstash-core gem version in the gemspec 
````
s.add_runtime_dependency "logstash-core", '1.5.0.rc2'
````
I strongly suspect that ruby-maven is having a hard time because logstash-core gem versioning does not follow [maven convention for qualifier](http://docs.oracle.com/middleware/1212/core/MAVEN/maven_version.htm#MAVEN401)
So for him, none of the [available version in rubygem ](https://rubygems.org/gems/logstash-core) are following the rule [1.4.0,2.0.0), thus failing

This should be fixed with 1.5.0 release hopefully or if you do an rc3, please try naming it with a **dash** 1.5.0-rc3 as 
  > All versions with a qualifier are older than the same version without a qualifier (release version).
---

Thanks @wiibaa for bringing this.

More details in the old issue (https://github.com/logstash-plugins/logstash-input-log4j/issues/5).

It relates to https://github.com/elastic/logstash/pull/2932

**Comment by ph** [comment] 2015-04-06 04:11
Make sense!

**Comment by colinsurprenant** [comment] 2015-04-07 11:39
I don't understand the relation with a gemspec `.add_runtime_dependency` on a gem and ruby-maven, what am I missing?

I think the problem is simply that that using a dependency like
```ruby
s.add_runtime_dependency "logstash-core", '>= 1.4.0', '< 2.0.0'
```
will just try to fetch the latest **released** gem that match this version constrain but `1.5.0.rc2` is a **pre-released** version. Just like when using Rubygems you have to use  `gem install --pre ...` to force installing a pre-released version.

**Comment by wiibaa** [comment] 2015-04-07 11:55
@colinsurprenant the root issue I strongly suspect 
> If you do not follow Maven versioning standards in your project versioning scheme, then for version comparison, **Maven interprets the entire version as a simple string.**

this would explain why the version range check  in ruby-maven to lookup the logstash-core gem is failing.

Side discussion about pre-release, maven is doing it its own way and enforcing the use of **SNAPSHOT** as a special qualifier for prerelease see [7.2 The SNAPSHOT Qualifier](http://docs.oracle.com/middleware/1212/core/MAVEN/maven_version.htm#MAVEN402)
Otherwise you are free to set the last part of the version as you like i.e Spring or Hibernate does as following 
http://mvnrepository.com/artifact/org.springframework/spring-core/4.1.6.RELEASE
http://mvnrepository.com/artifact/org.hibernate/hibernate-core/4.3.8.Final

and the version ordering is managed in the repository metadata like
https://repo1.maven.org/maven2/org/hibernate/hibernate-core/maven-metadata.xml

**Comment by colinsurprenant** [comment] 2015-04-07 13:02
@wiibaa but where/when is maven involved in resolving a gem dependency?

**Comment by wiibaa** [comment] 2015-04-07 13:08
@colinsurprenant seems to be the presence of a direct jar dependency in the gemspec (like log4j) that is triggering it , but I'm far from understanding the dark magic of jar-dependencies and ruby-maven together

**Comment by colinsurprenant** [comment] 2015-04-07 13:28
well AFAIK maven will only be involved for jar dependencies, not gems.  as I said, since the default behaviour for Rubygems is to **not** install pre-released gems unless you add the `--pre` options, (a pre released gem is a gem with a version that has a trailing .something_alphanumeric, like .beta or .rc3) I really think this is the actual problem when resolving the gemspec dependencies.

**Comment by colinsurprenant** [comment] 2015-04-07 15:24
after reviewing this with @pere and @ph we figured the problem is in fact caused by ruby-maven but for the reason I described for pre-released gems. when jars are specified in the dependencies, all dependencies resolution will go through the ruby-maven rubygems proxy and this is where this problem occurs. 

we agreed to get rid of install-time jar fetching and just embed the jar in the gem to get rid of all the jar dependencies/maven issues and added complexity.

**Comment by purbon** [comment] 2015-04-07 15:30
As @colinsurprenant said, we aim to change the way jar dependencies are going to be fetch to have them embedded somehow, this is going to let us get rid of the workflow that was causing that.

 To track the progress of this task I'm opening another issue that help on this.

**Comment by colinsurprenant** [comment] 2015-04-07 16:16
also relates to #2376

**Comment by suyograo** [comment] 2015-04-14 01:25
No longer an issue with https://github.com/elastic/logstash/issues/2954. We will stick to semver for LS releases, Gems will be packaged with jars at creation time

**Closed** 2015-04-14 01:26 UTC
Labels: bug
