### ISSUE TITLE
Logstash Forwarder can not connect when running logstash under ibm java 7

### ISSUE THREAD

**Issue by jamido** [elastic/logstash#1561] opened 2014-07-22 11:44 UTC
Installed Logstash 1.4.2 on SLES11SP2 and IBM-Java 7 and Logstash-forwarder. Logstash forwader can not connect to logstash. 
Logstash-forwarder throws this exceptoion: server selected unsupported protocol version 300
Downgraded Java to 1.6 everything works fine.

java -v 
java version "1.7.0"
Java(TM) SE Runtime Environment (build pxa6470sr7-20140410_01(SR7))
IBM J9 VM (build 2.6, JRE 1.7.0 Linux amd64-64 Compressed References 20140409_195732 (JIT enabled, AOT enabled)
J9VM - R26_Java726_SR7_20140409_1418_B195732
JIT  - r11.b06_20140409_61252
GC   - R26_Java726_SR7_20140409_1418_B195732_CMPRSS
J9CL - 20140409_195732)
JCL - 20140409_01 based on Oracle 7u55-b13

openssl s_client java 1.6 working fine:
New, TLSv1/SSLv3, Cipher is EDH-RSA-DES-CBC3-SHA
Server public key is 2048 bit
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
SSL-Session:
    Protocol  : TLSv1
    Cipher    : EDH-RSA-DES-CBC3-SHA
    Session-ID: 53CE4D8BFB8F9779A6EDC6ADBABA509AEE87F278B93CB0F0E3C40C6ECA8796F8
    Session-ID-ctx:
    Master-Key: 89758FC630BDE376FFB7B930A17B40AD7BD3882C8628FEB3A8A19C1439E50B1BCA67CC394A48B923EBD598AA691C9F08
    Key-Arg   : None
    Start Time: 1406029195
    Timeout   : 300 (sec)
    Verify return code: 18 (self signed certificate)

openssl s_client java 1.7 NOT working:

New, TLSv1/SSLv3, Cipher is EDH-RSA-DES-CBC3-SHA
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
SSL-Session:
    Protocol  : SSLv3
    Cipher    : EDH-RSA-DES-CBC3-SHA
    Session-ID: 53CE4E4A8BF4196A7517971CBA92E059631A0E56878C9BCE6ED271CA2CFE220D
    Session-ID-ctx:
    Master-Key: 794C6A9F35D1D669647B4385F094E643537B3BC10BF489FF9B96F544FE23D5CE231596FEF4F323A530D639F581BF8684
    Key-Arg   : None
    Start Time: 1406029387
    Timeout   : 300 (sec)
    Verify return code: 18 (self signed certificate)

**Comment by jordansissel** [comment] 2015-01-23 23:32
IBM Java 7 is not really supported right now. (We do not test on it)

Still, I tried to download the IBM JRE 7  for Linux, but it required some kind of login. I can't reproduce this without the software.

**Comment by jordansissel** [comment] 2015-01-23 23:33
Judging by the error (` Logstash-forwarder throws this exceptoion: server selected unsupported protocol version 300) it appears that the server is forcing SSLv3 on IBM Java 7, and I don't know why.

**Comment by purbon** [comment] 2015-05-22 10:14
@jamido do you have more information on this issue?  is this still relevant for 1.5 and new release of logstash-forwarder? 

as @jordansissel said we're not testing with Suse and IBM JRE7, so is hard for us to reproduce this error. It would be very nice of you if you can provide us more details.

**Comment by suyograo** [comment] 2016-03-11 16:17
Not testing with IBM Java 7 now. Closing

**Closed by suyograo** 2016-03-11 16:17 UTC
Labels: bug, needs details, unconfirmed
