### ISSUE TITLE
Kafka integration test can fail during setup

### ISSUE THREAD

**Issue by andrewvc** [elastic/logstash#7178] opened 2017-05-22 13:48 UTC
Form https://travis-ci.org/elastic/logstash/jobs/234760314

```
  1) Test Kafka Input can ingest 37 apache log lines from Kafka broker
     Failure/Error: @fixture = Fixture.new(__FILE__)
     
     Docker::Error::UnexpectedResponseError:
     # /home/travis/.rvm/gems/jruby-1.7.25/gems/docker-api-1.33.4/lib/docker/util.rb:200:in `extract_id'
     # /home/travis/.rvm/gems/jruby-1.7.25/gems/docker-api-1.33.4/lib/docker/image.rb:265:in `build_from_tar'
     # /home/travis/.rvm/gems/jruby-1.7.25/gems/docker-api-1.33.4/lib/docker/image.rb:278:in `build_from_dir'
     # ./services/kafka_service.rb:10:in `setup'
     # ./framework/fixture.rb:73:in `setup_services'
     # ./framework/fixture.rb:72:in `setup_services'
     # ./framework/fixture.rb:29:in `initialize'
     # ./specs/kafka_input_spec.rb:12:in `(root)'
```

**Comment by jsvd** [comment] 2017-05-22 13:51
this seems to be a dup of an issue that got a PR and was closed, I added a comment there: https://github.com/elastic/logstash/issues/7160#issuecomment-303061906

**Comment by andrewvc** [comment] 2017-05-22 13:55
@jsvd would you like to use this as the new issue or close / reopen #7160 ?

**Comment by jsvd** [comment] 2017-05-22 13:56
I'll let @original-brownbear decide if this is similar (then close) or a different thing (then keep open).

**Comment by andrewvc** [comment] 2017-05-22 14:39
I believe https://github.com/elastic/logstash/pull/7179 will be a good fix for this, waiting for those tests to pass ATM

**Comment by jsvd** [comment] 2017-05-29 10:16
I got this again in https://travis-ci.org/elastic/logstash/jobs/237106207#L1837

**Comment by original-brownbear** [comment] 2017-05-29 10:26
@jsvd wasn't there some SSL bug in Jruby ? :D The error so looks like some SSL lib issue (admittedly could be a bunch of other things too), I've never seen this one with MRI Ruby ...

**Comment by original-brownbear** [comment] 2017-05-29 10:28
nevermind ... Travis shouldn't be running an encrypted Docker socket ...

**Comment by colinsurprenant** [comment] 2017-05-29 13:49
removing elasticsearch-bot @andrewvc can you please reassign?

**Comment by jsvd** [comment] 2017-05-30 09:31
a few more instances of this:
https://travis-ci.org/elastic/logstash/jobs/237429275#L2256
https://travis-ci.org/elastic/logstash/jobs/237429282#L2217
https://travis-ci.org/elastic/logstash/jobs/237429280#L2192

**Comment by original-brownbear** [comment] 2017-05-30 09:32
@jsvd @andrewvc this is getting kind of painful I guess ... unless someone else has the time should I take a look here tonight?

**Comment by jsvd** [comment] 2017-05-30 09:38
I can take a stab at it thought I've been avoiding to since my docker knowledge is slim. anyway it can definitely wait until you're back home.

**Comment by original-brownbear** [comment] 2017-05-30 09:51
We can try a hack like https://github.com/elastic/logstash/pull/7264, let's see if we can make Travis run from a more recent Docker version. I can't reproduce this issue at all locally, but there are a number of bugs in that Docker version that may cause this ... maybe we get a freebie :P

**Comment by original-brownbear** [comment] 2017-05-30 10:45
@andrewvc @jsvd haver a look at #7264 ;)

**Comment by original-brownbear** [comment] 2017-05-30 14:38
fixed via #7264

**Comment by original-brownbear** [comment] 2017-06-03 03:27
happens still, see https://travis-ci.org/elastic/logstash/jobs/238786856#L1900 (his the version upgrade in it)

**Comment by original-brownbear** [comment] 2017-06-07 04:42
another case https://travis-ci.org/elastic/logstash/jobs/240206997#L1831

**Comment by original-brownbear** [comment] 2017-06-07 04:44
link https://github.com/swipely/docker-api/issues/455 -> https://github.com/moby/moby/issues/15759

**Comment by original-brownbear** [comment] 2017-06-07 07:05
Fixed at last by #7178 :)

**Comment by original-brownbear** [comment] 2017-07-04 09:25
not fixed https://travis-ci.org/elastic/logstash/jobs/249902174#L2087

**Comment by original-brownbear** [comment] 2017-07-06 12:45
closing for now, seems the retry fixed it (at least at the moment the issue is not visible)

**Comment by original-brownbear** [comment] 2017-07-11 15:21
@jsvd this happened again despite the retry https://travis-ci.org/elastic/logstash/jobs/252417390#L2003 :(

**Comment by original-brownbear** [comment] 2017-07-13 10:38
another case: https://travis-ci.org/elastic/logstash/jobs/253140457#L2797

This time both tests fail, not just one of them.

**Comment by original-brownbear** [comment] 2017-09-13 17:35
we dropped Docker so this is finally not an issue anymore :)

**Closed by original-brownbear** 2017-09-13 17:35 UTC
Labels: test failure
