### ISSUE TITLE
[test failure: master] Test Logstash Slowlog should write logs to a new dir

### ISSUE THREAD

**Issue by colinsurprenant** [elastic/logstash#8073] opened 2017-08-25 14:48 UTC
Integration test non-related failure.

https://travis-ci.org/elastic/logstash/jobs/268160331

```
Failures:
  1) Test Logstash Slowlog should write logs to a new dir
     Failure/Error: expect(IO.read(slowlog_file).split("\n").size).to eq(2)
     
       expected: 2
            got: 1
     
       (compared using ==)
     # ./specs/slowlog_spec.rb:44:in `block in (root)'
     # /home/travis/.rvm/gems/jruby-9.1.10.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block in (root)'
Finished in 25 minutes 26 seconds (files took 9.44 seconds to load)
32 examples, 1 failure
Failed examples:
rspec ./specs/slowlog_spec.rb:33 # Test Logstash Slowlog should write logs to a new dir
Randomized with seed 29073
```

**Comment by colinsurprenant** [comment] 2017-08-25 14:50
also reported in https://travis-ci.org/elastic/logstash/jobs/266095127 per #8033

**Comment by original-brownbear** [comment] 2017-09-19 17:23
@jakelandis FYI (since I know you're working on the tests), this one is a reproducible error for me locally too and not a result of a lack of processing power.
It also shows up as `3` counted instead of the expected `2` for me locally.

**Comment by original-brownbear** [comment] 2017-09-19 17:42
I think it's this https://github.com/logstash-plugins/logstash-filter-sleep/issues/7 ??

**Comment by jakelandis** [comment] 2017-09-19 19:54
@colinsurprenant / @original-brownbear 

I (accidentally) logged a duplicate over at https://github.com/elastic/logstash/issues/8322 and submitted a PR https://github.com/elastic/logstash/issues/8322 to fix it. 

The test itself is just trying to assert that it actually writes to the file, the actual count is a bit incidental.  I _think_ too little CPU and the you can get '1' instead of '2' and too much (if there is such a thing) can result in counts higher then '2'.  I trying >= 2 to see if that can stabilize it...if not we will have to do >= 0 or do a fuzzy match. 

Closing this in-favor of https://github.com/elastic/logstash/issues/8322

**Closed** 2017-09-19 19:55 UTC
Labels: test failure

**Comment by original-brownbear** [comment] 2017-09-19 21:38
@jakelandis 

>  I think too little CPU and the you can get '1' instead of '2' and

nah, I can reproduce `1` instead of `2` on a really powerful box reliably. If I run with `-w 1` it stops failing, it's the linked concurrency issue for in all likelihood (you can't overcount from doing `i++` in parallel, only undercount).
I'm also pretty sure this overcounting comes from concurrency problems, because the if you are on `i == 2` (i.e. waiting) and do `i++` there's a good shot that you'll miss the increment in another thread with reads and writes not being ordered and when you do, you'll get an additional wait.

The fact that `-w 1` fixes this makes me really confident it's just https://github.com/logstash-plugins/logstash-filter-sleep/issues/7 tbh :)
