### ISSUE TITLE
Logstash 6.4.1 & 6.5.0 High CPU usage

### ISSUE THREAD

**Issue by YanekR** [elastic/logstash#10196] opened 2018-12-04 14:18 UTC
Hi All,

We were using the Elastic Stack since 5.4.0 installed on our cluster:

Cluster details:
64GB of RAM
8 cores of E5-2680 v4 @ 2.40GHz
Dedicated storage for elasticsearch data dir: 1.2TB mounted 

- 10 elasticsearch nodes
- 4 logstash nodes
- 2 kibana nodes

Since 5.4.0 we were upgrading the cluster to versions:
 - 5.4.0 -> 5.6.0;
 - 5.6.0 -> 6.0.1;
 - 6.0.1 -> 6.2.4;
 - 6.2.4 -> 6.3.0;
 - 6.3.0 -> 6.4.1;
 - 6.4.1 -> 6.5.0

We use logstash as a Kafka consumer that writes directly to Elasticsearch.

After 6.3.0 -> 6.4.1 upgrade I have notice high CPU usage change on logstash nodes comparing to version 6.3.0. In consequence Logstash stopped consume logs from Kafka and start producing huge ingestion lag.

Below you will find my ElasticStack upgrade steps with comments:

At first 6.3.0 --> 6.4.1 (whole stack)
Then from 6.4.1 --> 6.4.2 (only Logstash)
then from 6.4.1 --> 6.5.0 (whole stack)

![upgrade to 6 4 1](https://user-images.githubusercontent.com/10604141/49444486-9bdc5800-f7cf-11e8-98fc-4e21ee274a25.png)

Then decided to move to version 6.4.2 all goes back to normal (still higher comparing to 6.3.0 but in tolerance).

<img width="1853" alt="upgrade to 6 4 2" src="https://user-images.githubusercontent.com/10604141/49444867-b400a700-f7d0-11e8-9d7a-ce90b0449365.png">

After couple of hours 6.4.2 start to behave like, so as a next step was to upgrade to 6.5.0, a whole stack. Upgrade gave same results as the upgrade to 6.4.1 

<img width="1853" alt="upgrade to 6 5 0" src="https://user-images.githubusercontent.com/10604141/49445085-4e60ea80-f7d1-11e8-997d-f3db92fa92c6.png">

<img width="1918" alt="htop" src="https://user-images.githubusercontent.com/10604141/49445519-5d946800-f7d2-11e8-8808-8ddf21b7a7b1.png">

What could be possible reason for high CPU usage? Is it any missing config setup or is it a bug? I could not find an error logs or warn logs which could point to the problem. When I downgrade those nodes to previous version 6.3.0, all go back to normal.

For comparison please see below CPU usage on node that runs 6.3.0 version which was running parallely on 3rd and 4th node with exactly same setups. 

<img width="1843" alt="logstash 6 3 0 to 6 5 0" src="https://user-images.githubusercontent.com/10604141/49445231-bfa09d80-f7d1-11e8-8184-e4676104e9c5.png">

## Details

- Version: 6.5.0 
- Operating System: Linux 3.10.0-693.2.2.el7.x86_64 
- $free -h

total        used        free      shared  buff/cache   available
Mem:            31G        1.9G         18G        1.6G         10G         27G
Swap:          2.0G          0B        2.0G

## logstash.yml:

    path.data: path_to_data
    path.config: path_to_conf
    config.reload.interval: 3s
    path.logs: path_to_logs

#### Xmx represents the maximum size of total heap space

-Xms4g
-Xmx4g

#### GC configuration
-XX:+UseParNewGC
-XX:+UseConcMarkSweepGC
-XX:CMSInitiatingOccupancyFraction=75
-XX:+UseCMSInitiatingOccupancyOnly

#### disable calls to System#gc
-XX:+DisableExplicitGC

#### set the I/O temp directory
-Djava.io.tmpdir=path_to_tmp_dir

#### set to headless, just in case
-Djava.awt.headless=true

#### ensure UTF-8 encoding by default (e.g. filenames)

-Dfile.encoding=UTF-8

#### heap dumps are created in the working directory of the JVM
-XX:+HeapDumpOnOutOfMemoryError

#### ensure the directory exists
-Xloggc:path_to_gc_logs

#### 100-beats.conf

input {
  beats {
    port => 5044
  }
}

#### 103-kafka.conf

input {
  kafka {
    id => "kafka"
    client_id => "kafka.host"
    bootstrap_servers => "bootstrap.server"
    decorate_events => true
    codec => "json"
    topics_pattern => "topic_pattern"
  }
  kafka {
    id => "kafka_uat"
    client_id => "kafka.host"
    bootstrap_servers => "bootstrap.server"
    decorate_events => true
    codec => "json"
    topics_pattern => "topic_pattern"
  }
}

#### 300-output.conf

output {
    if [@metadata][kafka][topic] {
        elasticsearch {
           hosts => [ "elk_hosts" ]
             user => abc
             password => xyz
             index => "index_pattern"
        }
    } else {
        elasticsearch {
           hosts => [ "elk_hosts" ]
             user => abc
             password => xyz
             index => "lndex_pattern_for_leftovers"
        }
    }
}

**Comment by danhermann** [comment] 2018-12-05 16:16
@YanekR, thank you for your detailed bug report. Would it be possible to retrieve the hot threads in Logstash 6.4.1 or 6.5.0 while it is exhibiting high CPU usage? You can do that via the Hot Threads API:

`curl -XGET 'logstashhost:9600/_node/hot_threads?threads=20&pretty'`

replacing `logstashhost` with the name of your Logstash host.

**Comment by YanekR** [comment] 2018-12-07 11:10
@danhermann  Thank you for your reply. 

Please find attached hot_thread_dumps for each node (6.3.0 & 6.5.0)

 ### Hot threads dump for each node:
[hot_threads_dumps.zip](https://github.com/elastic/logstash/files/2656946/hot_threads_dumps.zip)

### Visual comparison

<img width="1726" alt="nodes_comparsion" src="https://user-images.githubusercontent.com/10604141/49644541-059b7280-fa19-11e8-920a-c8390057075c.png">

**Comment by danhermann** [comment] 2018-12-07 11:34
@YanekR, the high CPU usage on both your 6.5.0 nodes is due to regexp processing, likely in the grok filter. Are you using the grok filter anywhere in your configuration?

**Comment by YanekR** [comment] 2018-12-07 16:09
@dan

**Comment by YanekR** [comment] 2018-12-07 19:08
@danhermann that's correct. We are using some grok & one KV filters. Was there any significant change between versions 6.3.0 and later ones that cause this change in CPU usage? For both versions we use same pipeline with same grok & KV filters. For 6.3.0 all works fine, but for 6.4.1, 6.4.2 & 6.5.0 causes high CPU usage?

Thanks,
Jan

**Comment by danhermann** [comment] 2018-12-10 14:02
@YanekR, there have been a number of recent changes to the KV filter. I'd suggest ensuring that you are on version 4.2.1 of the KV filter. If so, we probably need to take a closer look at the KV filter as a possible cause of the performance regressions you're seeing.

**Comment by praseodym** [comment] 2018-12-10 17:59
Enabling the Logstash slow log could be better way to find the culprit filter.

**Comment by YanekR** [comment] 2018-12-10 20:08
@danhermann yes, we use version 4.2.1 of the KV filter which comes together with Logstash 6.5.0.
I forgot to add that the other anomaly of this is that Logstash stops completely consume & emit events (event received/emitted rate is 0 events/sec).  

I will switch off a filter with KV and will monitor if that is a reason of my problem. 

Also, following @praseodym advice I will turn on slow logs for Logstash. Will come soon with results.

**Comment by yaauie** [comment] 2018-12-10 21:04
@YanekR there was significant reworking of the KV filter earlier this year; I had thought that we had worked our way through the performance regressions by the 4.2.1 release of the plugin, but if you're experiencing them then clearly we haven't.

It is possible that your inputs are pathological against the regular expression(s) generated by the KV filter; they could cause the regex engine to churn exponentially relative to the input's length, which could cause your logstash pipeline to stall.

It would help if we knew exactly how your KV filter is configured, as well as exactly what input it is stalling on. Any information you're willing/able to provide would help in chasing it down or finding a work-around. If you'd like to share this information privately, feel free to either:
 - encrypt with my public key from https://keybase.io/yaauie and share the cyphertext along with your public key here; OR
 - e-mail them to me at github-drop+logstash10196@yaauie.com and mention here that you have done so.

**Comment by YanekR** [comment] 2018-12-17 14:56
@danhermann @yaauie, 

I had turned off KV filter from my pipeline (replace it with dissect filter). It seems that KV was a cause of my issues. 

I prepare some examples of logs which were parsed by KV. IMHO they were not pathological against the regular expression(s).

KV was configured in a simplest way: just  kv{} - without any additional exclusions or inclusions, neither transformations. 

Please find how logstash looks after this change:

#### node 1 - logstash 6.5.0
<img width="1736" alt="node_1_logstash_6 5 0" src="https://user-images.githubusercontent.com/10604141/50088336-04c9c400-0203-11e9-97fa-1173f64a876a.png">

#### node 2 - logstash 6.5.0
<img width="1740" alt="node_2_logstash_6 5 0" src="https://user-images.githubusercontent.com/10604141/50088371-20cd6580-0203-11e9-94b2-f6e053e85e8e.png">

#### node 3 - logstash 6.3.0
<img width="1742" alt="node_3_logstash_6 3 0" src="https://user-images.githubusercontent.com/10604141/50088390-304cae80-0203-11e9-8e94-2f66b823cde0.png">

#### node 4 - logstash 6.3.0
<img width="1742" alt="node_4_logstash_6 3 0" src="https://user-images.githubusercontent.com/10604141/50088401-3e9aca80-0203-11e9-9014-47b16b894246.png">

### nodes comparison
<img width="1683" alt="screenshot 2018-12-17 at 13 54 57" src="https://user-images.githubusercontent.com/10604141/50088611-c54fa780-0203-11e9-87fa-78ef9b86fb88.png">

Thanks,
Jan

**Comment by thebitllc** [comment] 2018-12-31 22:37
I have a similar issue with 6.4.2, we went from 5.6.x to 6.4.2 and logstashes are dying. Just now all 6 logstashes died with symptoms:

100% cpu usage, 0 events ingested/emitted.

We have some kv filters, but I can't disable them. I'll enable the slowlog, because nothing useful in the logs.

**Comment by thebitllc** [comment] 2019-01-01 03:51
During the restart of the "stuck" logstash, it spitted out the following exceptions. KV filter seems to be issue.

[2018-12-31T17:12:30,503][WARN ][org.logstash.execution.ShutdownWatcherExt] {"inflight_count"=>0, "stalling_threads_info"=>{"other"=>[{"thread_id"=>75, "name"=>"[xxx]<kafka", "current_call"=>"[...]/vendor/bundle/jruby/2.3.0/gems/logstash-input-kafka-8.1.1/lib/logstash/inputs/kafka.rb:226:in `join'"}, {"thread_id"=>76, "name"=>"[xxx]<kafka", "current_call"=>"[...]/vendor/bundle/jruby/2.3.0/gems/logstash-input-kafka-8.1.1/lib/logstash/inputs/kafka.rb:226:in `join'"}, {"thread_id"=>77, "name"=>"[xxx]<kafka", "current_call"=>"[...]/vendor/bundle/jruby/2.3.0/gems/logstash-input-kafka-8.1.1/lib/logstash/inputs/kafka.rb:226:in `join'"}, {"thread_id"=>78, "name"=>"[xxx]<kafka", "current_call"=>"[...]/vendor/bundle/jruby/2.3.0/gems/logstash-input-kafka-8.1.1/lib/logstash/inputs/kafka.rb:226:in `join'"}], ["LogStash::Filters::KV", {"transform_key"=>"lowercase", "field_split"=>"&?", "source"=>"[TempUrl][Hash]", "id"=>"01f64e0df74b3f4adfe2cc85a95c9e004c45148713bfd095a758560326d1fd9f", "value_split"=>"=", "include_keys"=>[], "target"=>"[Service][Route]"}]=>[{"thread_id"=>71, "name"=>nil, "current_call"=>"[...]/vendor/bundle/jruby/2.3.0/gems/logstash-filter-kv-4.2.1/lib/logstash/filters/kv.rb:498:in `scan'"}], ["LogStash::Filters::KV", {"transform_key"=>"lowercase", "field_split"=>"&?", "source"=>"[TempUrl][QueryString]", "id"=>"4f041758bc86e29a52d848942ad97ddfae6abeee9d0d793cc9466cb9e86e3050", "value_split"=>"=", "include_keys"=>[}]=>[{"thread_id"=>72, "name"=>nil, "current_call"=>"[...]/vendor/bundle/jruby/2.3.0/gems/logstash-filter-kv-4.2.1/lib/logstash/filters/kv.rb:498:in `scan'"}, {"thread_id"=>73, "name"=>nil, "current_call"=>"[...]/vendor/bundle/jruby/2.3.0/gems/logstash-filter-kv-4.2.1/lib/logstash/filters/kv.rb:498:in `scan'"}, {"thread_id"=>74, "name"=>nil, "current_call"=>"[...]/vendor/bundle/jruby/2.3.0/gems/logstash-filter-kv-4.2.1/lib/logstash/filters/kv.rb:498:in `scan'"}]}}

**Comment by thebitllc** [comment] 2019-01-01 22:19
That's the usual symtomps of a "stuck" logstash

![image](https://user-images.githubusercontent.com/4561976/50576875-608e7280-0de9-11e9-9c29-e56aea2f5ebd.png)

**Comment by gulycka** [comment] 2019-01-10 16:11
Hi guys,

I just come across the similar issue, probably also with KV filter. Log rate is constant for longer time, but CPU utilization rises dramatically (from 10% to 40%) without any obvious reason.

See the graph from monitoring below.

![2019-01-10 17_02_26-temp buffer - onenote](https://user-images.githubusercontent.com/3018848/50980866-fa48d480-14f9-11e9-8b27-79c218325444.png)

I also run on logstash version 6.4.2.

When I tried to restart logstash service I got following message with KV filter stuck on operation:
`[2019-01-10T16:49:21,234][WARN ][org.logstash.execution.ShutdownWatcherExt] {"inflight_count"=>0, "stalling_threads_info"=>{["LogStash::Filters::KV", {"value_split_pattern"=>"=", "field_split_pattern"=>",", "transform_key"=>"lowercase", "exclude_keys"=>["type", "host", "path", "srv-ip", "srv-name", "@timestamp", "syslog_timestamp", "rest", "message"], "trim_value"=>"\\\"", "allow_duplicate_values"=>"false", "source"=>"rest", "id"=>"e494f3d80a7ee6df1f4cc31a66f6031be55b7dab58eea4a2bdfbdd30442ffcb0", "whitespace"=>"strict"}]=>[{"thread_id"=>87, "name"=>nil, "current_call"=>"[...]/vendor/bundle/jruby/2.3.0/gems/logstash-filter-kv-4.2.1/lib/logstash/filters/kv.rb:498:in `scan'"}, {"thread_id"=>89, "name"=>nil, "current_call"=>"[...]/vendor/bundle/jruby/2.3.0/gems/logstash-filter-kv-4.2.1/lib/logstash/filters/kv.rb:498:in `scan'"}, {"thread_id"=>91, "name"=>nil, "current_call"=>"[...]/vendor/bundle/jruby/2.3.0/gems/logstash-filter-kv-4.2.1/lib/logstash/filters/kv.rb:498:in `scan'"}, {"thread_id"=>92, "name"=>nil, "current_call"=>"[...]/vendor/bundle/jruby/2.3.0/gems/logstash-filter-kv-4.2.1/lib/logstash/filters/kv.rb:498:in `scan'"}, {"thread_id"=>93, "name"=>nil, "current_call"=>"[...]/vendor/bundle/jruby/2.3.0/gems/logstash-filter-kv-4.2.1/lib/logstash/filters/kv.rb:498:in `scan'"}, {"thread_id"=>94, "name"=>nil, "current_call"=>"[...]/vendor/bundle/jruby/2.3.0/gems/logstash-filter-kv-4.2.1/lib/logstash/filters/kv.rb:498:in `scan'"}, {"thread_id"=>97, "name"=>nil, "current_call"=>"[...]/vendor/bundle/jruby/2.3.0/gems/logstash-filter-kv-4.2.1/lib/logstash/filters/kv.rb:498:in `scan'"}, {"thread_id"=>108, "name"=>nil, "current_call"=>"[...]/vendor/bundle/jruby/2.3.0/gems/logstash-filter-kv-4.2.1/lib/logstash/filters/kv.rb:498:in `scan'"}]}}`

After restart the utilization was 5% again for some short time, then it started to raise to 17% and above.

@thebitllc - I will be glad if you can let us know if the upgrade to 6.5.x helped to resolve the issue.

Regards.

**Comment by guyboertje** [comment] 2019-01-10 18:01
@thebitllc @gulycka 

I recently was troubleshooting a stalled/slow shutdown where various worker threads were in the KV filter scan method.

We saw that the input was Kafka having 6 consumer threads and a fetch size of 500 documents but the number of workers was 4 and a batch size of 125. At shutdown, a flag is set on the input(s), when the input loop (usually a separate thread) gets a chance to test the flag, if set will exit the loop. In this case the 6 consumers had fetched 500 documents for a total of 3000 events, however the workers could only process 4 X 125 events per loop. This meant that the workers would need to do 6 loops of filter and output execution before the input(s) could check the flag to actually stop - LS did eventually stop in this case.

None of the above explains the increased CPU load though.

To some degree, the worker and the input threads spend some time parked on a wait condition, either the input thread is waiting to hand some events to a worker thread or a filter is waiting for a response or an output is waiting for a response. While parked they consume no CPU.

Now, Logstash has a few filters that use regular expressions internally. [Regex engines are susceptible to getting stuck](https://www.owasp.org/index.php/Regular_expression_Denial_of_Service_-_ReDoS) as a function of the defined pattern and the data being fed into the engine. However, different data might not get stuck as such, but more like take many more cycles to complete.
A sudden increase in the CPU load could mean that some worker threads are stuck but the general events per second rate is more determined by external factors than worker filter processing speed.

If workers are indeed stuck in KV scan then they will never "exit" and remain being reported by the shutdown reporter. I feel it is hard to "fix" the KV filter for these cases because we can't recreate them easily, i.e. don't know what patterns + data combined lead to this.

**Comment by gulycka** [comment] 2019-01-11 08:57
Hi @guyboertje,

thank you for quite detailed explanation of the possible issue.
The thing with the stopping of logstash server and unprocessed amount of logs makes sense, but to be sure if the problem is related to KV filter I leave the whole parsing configuration untouched except the KV part. I commented out the KV filter and restart the service. Still there is lots of processing by grok filters, but no KV filter afterwards. KV filter was used on just a part of logs, I would say on maximum 10% of recieved logs, not more. Below you can see the CPU Utilization graph for last 24 hours. As you can see without KV filter there were no high long term peaks of CPU Utilization. So I think that the problem is really processing in KV filter.

I will be glad if @thebitllc can share with us his tests of newer version (6.5.x) of ELK cluster, if the issue persists or if it is fixed.

![2019-01-11 09_53_25-monitoring - elkprod01 - logstash - ba-esparser03](https://user-images.githubusercontent.com/3018848/51023374-0cbd1f80-1587-11e9-9dda-5c5bcfcf096a.png)

Thanks.

**Comment by praseodym** [comment] 2019-01-11 15:36
> Now, Logstash has a few filters that use regular expressions internally. [Regex engines are susceptible to getting stuck](https://www.owasp.org/index.php/Regular_expression_Denial_of_Service_-_ReDoS) as a function of the defined pattern and the data being fed into the engine. However, different data might not get stuck as such, but more like take many more cycles to complete.

The [grok filter has a timeout setting](https://www.elastic.co/guide/en/logstash/current/plugins-filters-grok.html#plugins-filters-grok-timeout_millis) to prevent a situation like this. Maybe it would be worthwhile to add this feature to the KV filter as well? That would also make problematic patterns and data easier to detect.

**Comment by keneo** [comment] 2019-02-20 15:09
I have the same issue with kv filter. Is there any alternative for kv?

**Comment by keneo** [comment] 2019-02-20 20:13
I spent 3h on this and found the problem trigger: \x22

Workaround that worked for me: 

`mutate { gsub => [ "the_field_i_run_kv_on", "\\x22", '"' ] }`

**Comment by jrask** [comment] 2019-03-13 14:58
We also have problems with pipeline stalling due to kv plugin during shutdown with 6.6.1.
Reverted to 6.3.0 verified that the problem was not there in that version.

**Comment by colinsurprenant** [comment] 2019-03-14 14:06
Here's the versions map for LS vs KV:

LS versions | KV version
--- | ---
6.3.0 | 4.1.1
6.3.1 - 6.3.2 | 4.1.2
6.4.0 | 4.2.0
6.4.1 - 6.6.2 | 4.2.1

Going through the comment, the common cause for the performance drop seems to point to the upgrade of KV to version **4.2.1**. There is no report of usage LS 6.4.0 so we don't know if the actual performance drop started in KV 4.2.0 or 4.2.1 but it seems that KV 4.1.1 and 4.1.2 are fine in that respect. 

- If using LS 6.4.0 and up a short-term workaround would be to downgrade KV to 4.1.2 and see if this help. 
- We will need sample data and KV configs to help with the diagnostic of the performance regression, please reach out to @yaauie or myself to share this with us if possible. A very simple config (stdin + kv filter + stdout) and a single log line that can be sent repeatedly to logstash stdin where we can witness the performance regression would be ideal.

**Comment by thebitllc** [comment] 2019-03-21 19:58
I had a ticket opened with Elastic and they suggested to use the following options:

						include_brackets => false
						whitespace => strict

These options improved our performance.

**Comment by ldrolez** [comment] 2019-04-05 12:33
I also tried many logstash versions up to 6.7.1 and had to downgrade to 6.3.2. 
Since I had problems with the KV unterminated quotes bug with the same versions, I wondered if the high CPU problem was not linked to the fix of that bug

**Comment by colinsurprenant** [comment] 2019-05-06 21:06
bump, any followup for this?

**Comment by cdenneen** [comment] 2019-06-25 23:23
Using 6.8.0 with kv filter 4.3.0 still same issue

**Comment by colinsurprenant** [comment] 2019-07-05 15:00
@cdenneen could you provide more information to help troubleshoot? Like the kv filter filter version that was last working correctly for you, your kv filter config, some sample data so we can try to reproduce locally...

Also, did you try downgrading the kv filter to the latest version that was behaving correctly for you before?

**Comment by danielyahn** [comment] 2019-08-05 16:49
@colinsurprenant is there an open issue on the [logstash-plugins/logstash-filter-kv](https://github.com/logstash-plugins/logstash-filter-kv)? Do you know if this issue is fixed with later version such as 4.4.0 (logstash 7.3)?

**Comment by colinsurprenant** [comment] 2019-08-06 19:22
@danielyahn there were a number of issues fixed in the kv filter, some performance regressions and other about the timeout enforcer which did not work correctly (which could result in runaway regex taking 100% CPU for an arbitrary long time). You can take a look at the changelog and/or try it to see if it works for you. If if does not I suggest you open a new issue with more information about your specific problem.

**Comment by colinsurprenant** [comment] 2019-08-06 19:31
As noted above, [it was discovered that the kv filter timeout enforcer did not work](https://github.com/elastic/logstash/pull/10978), that linked PR also contains a workaround. Also lots of improvements were made to the kv filter since that issue was opened. 

I will go ahead and close this issue. If you feel like you still have performance problem I suggest you open a new issue with as much details as possible to help diagnose the nature of the performance problem.

**Closed by colinsurprenant** 2019-08-06 19:31 UTC
