### ISSUE TITLE
package build is broken due to Bad file descriptor errors while installing gems

### ISSUE THREAD

**Issue by purbon** [elastic/logstash#3171] opened 2015-05-05 15:58 UTC
To run ``artifact:deb```, ``artifact::rpm``` or the all plugins test where a mass installation of plugins is being done make the process to break with errors like:

```
[artifact:install-logstash-core] using logstash-core from Rubygems
[artifact:deb] building deb package
Installing fpm >= 0 because the build process needs it.
[bootstrap] Fetching and installing gem: fpm (>= 0)

rake aborted!
Errno::EBADF: Bad file descriptor - Bad file descriptor (https://api.rubygems.org/quick/Marshal.4.8/fpm-0.1.0.gemspec.rz)
org/jruby/RubyArray.java:2468:in `select'
org/jruby/RubyArray.java:1613:in `each'
/Users/purbon/work/logstash/rakelib/gems.rake:39:in `(root)'
org/jruby/RubyProc.java:271:in `call'
org/jruby/RubyArray.java:1613:in `each'
/Users/purbon/work/logstash/rakelib/gems.rake:16:in `(root)'
org/jruby/RubyProc.java:271:in `call'
org/jruby/RubyArray.java:1613:in `each'
/Users/purbon/work/logstash/rakelib/dependency.rake:20:in `(root)'
org/jruby/RubyProc.java:271:in `call'
org/jruby/RubyArray.java:1613:in `each'
```
(from the ```artifact:deb``` build)

this is afecting:

* all the package build except zip and tar
*  the all plugins test.

**Comment by ph** [comment] 2015-05-05 17:46
I also got this issue when trying to generate the local package.


```
[bootstrap] Fetching and installing gem: fpm (>= 0)
rake aborted!
Could not find 'backports' (>= 2.6.2) among 30 total gem(s)
Checked in 'GEM_PATH=/Users/ph/es/logstash/vendor/bundle/jruby/1.9', execute `gem env` for more information
org/jruby/RubyArray.java:1613:in `each'
/Users/ph/es/logstash/rakelib/artifacts.rake:125:in `package'
/Users/ph/es/logstash/rakelib/artifacts.rake:246:in `(root)'

**Comment by colinsurprenant** [comment] 2015-05-05 17:48
also reproduced in 1.5 branch doing

    rake artifact:deb

**Comment by purbon** [comment] 2015-05-05 17:51
@ph @colinsurprenant got the strange feeling this is a regression workarounded by the old default files :+1:

**Comment by purbon** [comment] 2015-05-05 17:52
actually doing

```rake artifact:prepare && rake dependency:fpm``` works

**Comment by ph** [comment] 2015-05-05 18:05
My previous comments was on master on 1.5 I get file descriptor error:

```
[artifact:install-logstash-core] using logstash-core from Rubygems
[artifact:deb] building deb package
Installing fpm >= 0 because the build process needs it.
[bootstrap] Fetching and installing gem: fpm (>= 0)
rake aborted!
Errno::EBADF: Bad file descriptor - Bad file descriptor (https://api.rubygems.org/quick/Marshal.4.8/fpm-0.1.0.gemspec.rz)
org/jruby/RubyArray.java:2468:in `select'
org/jruby/RubyArray.java:1613:in `each'

**Comment by colinsurprenant** [comment] 2015-05-05 18:26
@pere no related to the old `.defaults`, it doe snot exist anymore.

It has to do with the fact that the `fpm` gem is "forced installed" outside bundler.

I was able to solve by moving the `fpm` and `stud` gem into the `Gemfile` and also adding a missing `require "logstash/version"` at the top of `artifacts.rake`.

**Comment by purbon** [comment] 2015-05-05 18:27
ok, was just a hunch :-) good you solve it ... are you making a PR to make this fix ?

**Comment by colinsurprenant** [comment] 2015-05-05 18:34
well, I don't like to have them globally installed and live in the package... it's just a good indication of tha nature pf the problem.

per @ph suggestion, trying to just pre-install them at the bootstrap instead... stay tuned ;)

**Comment by ph** [comment] 2015-05-05 18:34
@colinsurprenant I am not sure I like that, FPM will bring a lot of dependencies in the `.lock`. Maybe we could do the installation with minitar. (bootstrap)

**Comment by purbon** [comment] 2015-05-05 18:36
We can install them just for the build of the package in a kinda gemset?
makes sense?

- purbon

On Tue, May 5, 2015 at 8:34 PM, Pier-Hugues Pellerin <
notifications@github.com> wrote:

> @colinsurprenant <https://github.com/colinsurprenant> I am not sure I
> like that, FPM will bring a lot of dependencies in the .lock. Maybe we
> could do the installation with minitar. (bootstrap)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elastic/logstash/issues/3171#issuecomment-99172280>.
>



-- 
Pere Urbon-Bayes
Software Engineer
https://www.elastic.co
https://twitter.com/purbon

**Comment by colinsurprenant** [comment] 2015-05-05 18:36
@ph ^^ +1 see previous comments :P

**Comment by ph** [comment] 2015-05-05 18:38
@purbon group could work http://bundler.io/v1.3/groups.html probably cleaner +1.
We can create a "build" group and use bundler to install them.

**Comment by purbon** [comment] 2015-05-05 18:40
+1

On Tue, May 5, 2015 at 8:39 PM, Pier-Hugues Pellerin <
notifications@github.com> wrote:

> @purbon <https://github.com/purbon> group could work
> http://bundler.io/v1.3/groups.html probably cleaner +1.
> We can create a "build" group and use bundler to install them.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elastic/logstash/issues/3171#issuecomment-99174389>.
>



-- 
Pere Urbon-Bayes
Software Engineer
https://www.elastic.co
https://twitter.com/purbon

**Comment by ph** [comment] 2015-05-05 18:42
Only minitar(for getting and uncompressing jruby) and bundler need be installed first.

**Comment by colinsurprenant** [comment] 2015-05-05 19:56
proposed fix in #3172

**Comment by purbon** [comment] 2015-05-05 20:34
Hi,
  can you update this fix to also include the all pluguins test? same
problem happen there.

/purbon

On Tuesday, May 5, 2015, Colin Surprenant <notifications@github.com> wrote:

> proposed fix in #3172 <https://github.com/elastic/logstash/pull/3172>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elastic/logstash/issues/3171#issuecomment-99202845>.
>


-- 
Pere Urbon-Bayes
Software Engineer
https://www.elastic.co
https://twitter.com/purbon

**Comment by purbon** [comment] 2015-05-05 20:38
The fix look reasonable to me.

/purbon

On Tuesday, May 5, 2015, Pere Urbon-Bayes <pere.urbon@elastic.co> wrote:

> Hi,
>   can you update this fix to also include the all pluguins test? same
> problem happen there.
>
> /purbon
>
> On Tuesday, May 5, 2015, Colin Surprenant <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> proposed fix in #3172 <https://github.com/elastic/logstash/pull/3172>
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/elastic/logstash/issues/3171#issuecomment-99202845>.
>>
>
>
> --
> Pere Urbon-Bayes
> Software Engineer
> https://www.elastic.co
> https://twitter.com/purbon
>
>

-- 
Pere Urbon-Bayes
Software Engineer
https://www.elastic.co
https://twitter.com/purbon

**Comment by colinsurprenant** [comment] 2015-05-05 20:44
@purbon what do you mean by «also include the all pluguins test» ?

**Comment by purbon** [comment] 2015-05-05 20:49
all pluguins test dependencies, the one eased to access github is in the
same situation as fpm for the artifacts.

/purbon

pd: check jenkins build if you want more details

On Tuesday, May 5, 2015, Colin Surprenant <notifications@github.com> wrote:

> @purbon <https://github.com/purbon> what do you mean by «also include the
> all pluguins test» ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elastic/logstash/issues/3171#issuecomment-99215277>.
>


-- 
Pere Urbon-Bayes
Software Engineer
https://www.elastic.co
https://twitter.com/purbon

**Comment by colinsurprenant** [comment] 2015-05-05 21:42
@purbon I'm sorry, I don't understand what you mean, what should be included where?

**Comment by colinsurprenant** [comment] 2015-05-05 21:46
Just tried the `rake test:install-all` and it's failing on the octokit gem, so I assume that's what you meant @pere. fixing now. same idea, I will put it in the `:development` group. because its not really to build package but run tests for all plugins. trying that now.

**Comment by colinsurprenant** [comment] 2015-05-05 22:42
ok, `rake:install-all` and `rake test:plugins` all working now with #3172

**Comment by colinsurprenant** [comment] 2015-05-06 02:27
please jenkins, test this.

**Comment by colinsurprenant** [comment] 2015-05-06 02:54
need more reviews on #3172 @pere @jsvd @ph

**Comment by purbon** [comment] 2015-05-06 07:01
reviewing #3172

**Closed** 2015-05-06 12:28 UTC
Labels: 1.5.0-rc4, blocker, bug, bundler
