### ISSUE TITLE
Odd grok behaviour

### ISSUE THREAD

**Issue by jmcta** [elastic/logstash#5501] opened 2016-06-15 03:10 UTC
Following examples online, I've setup a filter to process syslog messages for filters running later:

```
filter {
  if [type] == "syslog" {
    grok {
      match => { "message" => "<%{POSINT:syslog_pri}>%{SYSLOGTIMESTAMP:syslog_timestamp} %{SYSLOGHOST:syslog_hostname} %{DATA:syslog_program}(?:\[%{POSINT:syslog_pid}\])?: %{GREEDYDATA:syslog_message}" }
      add_field => [ "received_at", "%{@timestamp}" ]
      add_field => [ "received_from", "%{@source_host}" ]
      tag_on_failure => [ "syslog_fail" ]
      add_tag => [ "unmatched" ]
    }

    syslog_pri {
    }

    date {
      match => [ "syslog_timestamp", "MMM  d HH:mm:ss", "MMM dd HH:mm:ss" ]
    }
  }
}
```

The issue being, neither "syslog_fail" or "unmatched" are added to the tags section.  I know the if statement is passing as syslog_pri adds the four syslog_\* fields.  However no matter what I do, the grok doesn't seem to be running.  It doesn't succeed, it doesn't fail, it just does nothing.  I can change the pattern to be just:

`"%{GREEDYDATA:syslog_message}"`

which should match everything, but it still doesn't add either the pass or fail tag.

Example of a parsed line:

```
{
  "_index": "logstash-2016.06.15",
  "_type": "syslog",
  "_id": "AVVSBKqK1Yb3EXZgRNWP",
  "_score": null,
  "_source": {
    "@timestamp": "2016-06-15T03:04:44.792Z",
    "syslog_severity_code": 5,
    "port": 43842,
    "syslog_facility": "user-level",
    "@version": "1",
    "host": "10.1.1.99",
    "syslog_facility_code": 1,
    "message": "<190>Jun 14 21:04:44 firewall dhcpd: DHCPREQUEST for 10.1.1.155 from c8:d5:fe:e5:56:0d (C8D5FEE5560D) via eth0",
    "type": "syslog",
    "syslog_severity": "notice",
    "tags": [
      "dhclient_fail"
    ]
  },
  "fields": {
    "@timestamp": [
      1465959884792
    ]
  },
  "sort": [
    1465959884792
  ]
}
```

the dhclient_fail tag is due to a filter later in time that fails without the appropriate syslog_\* fields.

Logstash version 5.0.0alpha3

I know I'm missing something, I just can't put my finger on it.

**Comment by JamesMcTavish** [comment] 2016-06-15 15:30
I can fix the issue, but I'm not sure why.  If I have two filter files:

conf.d/200-filter-syslog.conf
```
filter {
  if [type] == "syslog" {
    grok {
      match => { "message" => "<%{POSINT:syslog_pri}>%{SYSLOGTIMESTAMP:syslog_timestamp} %{SYSLOGHOST:syslog_hostname} %{DATA:syslog_program}(?:\[%{POSINT:syslog_pid}\])?:? %{GREEDYDATA:syslog_message}" }
      add_field => [ "received_at", "%{@timestamp}" ]
      add_field => [ "received_from", "%{@source_host}" ]
      add_tag => [ "unmatched" ]
      tag_on_failure => [ "syslog_fail" ]
    }

    syslog_pri {
    }

    date {
      match => [ "syslog_timestamp", "MMM  d HH:mm:ss", "MMM dd HH:mm:ss" ]
    }
  }
}
```
conf.d/201-filter-pam.conf
```
filter {
  if [type] == "syslog" {

    grok {
      match => { "syslog_message" => "pam_unix\(%{WORD:pam_program}:%{WORD:pam_stage}\): %{GREEDYDATA:pam_message}" }
      add_tag => [ "pam" ]
      tag_on_failure => [ "pam_fail" ]
    }
  }
}
```
It appears to ignore the execution of the grok within the 200 file.  No tag on failure, no add_tag on success.  Combining them into one file with one filter, it starts working:

```
filter {
  if [type] == "syslog" {
    grok {
      match => { "message" => "<%{POSINT:syslog_pri}>%{SYSLOGTIMESTAMP:syslog_timestamp} %{SYSLOGHOST:syslog_hostname} %{DATA:syslog_program}(?:\[%{POSINT:syslog_pid}\])?:? %{GREEDYDATA:syslog_message}" }
      add_field => [ "received_at", "%{@timestamp}" ]
      add_field => [ "received_from", "%{@source_host}" ]
      add_tag => [ "unmatched" ]
      tag_on_failure => [ "syslog_fail" ]
    }

    syslog_pri {
    }

    date {
      match => [ "syslog_timestamp", "MMM  d HH:mm:ss", "MMM dd HH:mm:ss" ]
    }
  }
  if [type] == "syslog" {

    grok {
      match => { "syslog_message" => "pam_unix\(%{WORD:pam_program}:%{WORD:pam_stage}\): %{GREEDYDATA:pam_message}" }
      add_tag => [ "pam" ]
      tag_on_failure => [ "pam_fail" ]
    }
  }
}
```
Shouldn't i be able to separate the configuration out into multiple filter {} blocks?

**Comment by jordansissel** [comment] 2016-06-15 16:35
I haven't tried to reproduce, but my guess for testing this would be to have two `filter { ... }` blocks in a single file and see if it ignores the first one.

**Comment by JamesMcTavish** [comment] 2016-06-15 17:56
I can confirm, that if I cat the first two files together and remove the two, it behaves the same way.

**Comment by jordansissel** [comment] 2016-06-15 22:15
Ok cool! This bug is probably somewhere in the config compiler.

**Comment by Gabry993** [comment] 2016-07-14 06:47
I have a similar issue when trying to keep filters separated in many conf file. I found this workaround, maybe it could help to understand how to fix this bug:
in the first filter file I open the filter section 
`filter {`
and I close it only in the last filter file
`}`
I don't like this solution, but it's the only way I found to keep conf files separated without any odd grok behaviours.

**Comment by magnusbaeck** [comment] 2016-07-29 19:06
I was hit by this too (Logstash 2.3.4), but only when starting Logstash with `-f file1 -f file2`. If I use a single `-f` option that points to a directory with file1 and file2 it works fine.

```
$ cat syslog.example 
Oct  6 20:55:29 localhost lovebeat[31993]: Beat from logging.hallonet.syslog (prev 3 ms ago)
$ ls conf 
syslog.conf  test.conf
$ cat conf/syslog.conf 
filter {
  grok {
    match => [
      "message", "%{SYSLOGBASE2} %{GREEDYDATA:message}",
      "message", "(?:%{SYSLOGTIMESTAMP:timestamp}|(?<timestamp>%{SYSLOGTIMESTAMP} 20[12][0-9])) *(?:%{SYSLOGFACILITY} )?(?:%{SYSLOGHOST:logsource} )?%{SYSLOGPROG}: %{GREEDYDATA:message}"
    ]
    overwrite => ["message"]
  }
}
$ cat conf/test.conf 
filter {
  mutate {
    add_field => { "foo" => "bar" }
  }
}
```

This works as expected:

```
$ /opt/logstash/bin/logstash -e 'output { stdout { codec => rubydebug } } input { stdin { } }' -f conf/ < syslog.example 
Settings: Default pipeline workers: 8
Pipeline main started
{
       "message" => "Beat from logging.hallonet.syslog (prev 3 ms ago)",
      "@version" => "1",
    "@timestamp" => "2016-07-29T18:50:03.272Z",
          "host" => "bertie",
     "timestamp" => "Oct  6 20:55:29",
     "logsource" => "localhost",
       "program" => "lovebeat",
           "pid" => "31993",
           "foo" => "bar"
}
Pipeline main has been shutdown
stopping pipeline {:id=>"main"}
```

This doesn't (note absence of `foo` field):

```
$ /opt/logstash/bin/logstash -e 'output { stdout { codec => rubydebug } } input { stdin { } }' -f conf/syslog.conf conf/test.conf < syslog.example 
Settings: Default pipeline workers: 8
Pipeline main started
{
       "message" => "Beat from logging.hallonet.syslog (prev 3 ms ago)",
      "@version" => "1",
    "@timestamp" => "2016-07-29T18:56:13.616Z",
          "host" => "bertie",
     "timestamp" => "Oct  6 20:55:29",
     "logsource" => "localhost",
       "program" => "lovebeat",
           "pid" => "31993"
}
Pipeline main has been shutdown
stopping pipeline {:id=>"main"}
```

It seems like the second file is ignored, because reversing the order of the files in the command reverses which filter is applied:

```
$ /opt/logstash/bin/logstash -e 'output { stdout { codec => rubydebug } } input { stdin { } }' -f conf/test.conf conf/syslog.conf < syslog.example
Settings: Default pipeline workers: 8
Pipeline main started
{
       "message" => "Oct  6 20:55:29 localhost lovebeat[31993]: Beat from logging.hallonet.syslog (prev 3 ms ago)",
      "@version" => "1",
    "@timestamp" => "2016-07-29T18:56:44.558Z",
          "host" => "bertie",
           "foo" => "bar"
}
Pipeline main has been shutdown
stopping pipeline {:id=>"main"}
```

Except it's not quite that simple! If I rename the files back to their original names,

```
mv conf/test.conf conf/60-hostnames-filter.conf.j2               
mv conf/syslog.conf conf/50-syslog-filter.conf.j2                 
```

I get the reverse result, i.e. the first file is ignored:

```
$ /opt/logstash/bin/logstash -e 'output { stdout { codec => rubydebug } } input { stdin { } }' -f conf/50-syslog-filter.conf.j2 -f conf/60-hostnames-filter.conf.j2 < syslog.example
Settings: Default pipeline workers: 8
Pipeline main started
{
       "message" => "Oct  6 20:55:29 localhost lovebeat[31993]: Beat from logging.hallonet.syslog (prev 3 ms ago)",
      "@version" => "1",
    "@timestamp" => "2016-07-29T19:02:43.655Z",
          "host" => "bertie",
           "foo" => "bar"
}
Pipeline main has been shutdown
stopping pipeline {:id=>"main"}
```

**Comment by magnusbaeck** [comment] 2016-07-29 19:15
Reading the code and documentation, there's nothing that indicates that using multiple `-f` options is actually supported. In that case my comment above can be ignored.

**Comment by kares** [comment] 2021-02-04 10:02
closing as defunct by now

**Closed by kares** 2021-02-04 10:02 UTC
Labels: bug
