### ISSUE TITLE
Regression of the running time of rspec for logstash-1.5.0

### ISSUE THREAD

**Issue by zhenghu** [elastic/logstash#3285] opened 2015-05-20 09:49 UTC
I running my logstash unit test with rspec.
But  with logstash-1.5.0, the test running time is 5x longger than logstash-1.4.2.

I run the test with the following commands : 
`bin/plugin install --development`
`bin/rspec test.rb`

Is there some plugin should be installed for improve the performance of rspec of 1.5.0 ?

**Comment by untergeek** [comment] 2015-05-20 12:55
One simple explanation that comes immediately to mind is that we added many, many more tests since 1.4.2.  You may simply be running into tests which take longer, which were not there in 1.4.2.

**Comment by ph** [comment] 2015-05-20 12:56
@untergeek he is targeting one file and not the whole suite, not quite sure what would make it a lot slower.

**Comment by untergeek** [comment] 2015-05-20 13:03
(facepalm)... I need to read more closely after I first wake up :smile:

**Comment by ph** [comment] 2015-05-20 13:10
@zhenghu Not sure what could make the test run slow, are you running them on windows?

There is workaround, you can try to use Drip see https://github.com/elastic/logstash/blob/master/README.md#drip-launcher

**Comment by zhenghu** [comment] 2015-05-20 13:14
@ph In fact, I run the test on both windows and linux. In linux it worse 10x slower. 

Thanks for your suggestion, I will try this plugin.

But I think this regression should be better to figure out.

**Comment by ph** [comment] 2015-05-20 13:14
@zhenghu agree about the regression!

**Comment by colinsurprenant** [comment] 2015-05-21 15:29
@zhenghu but are you including the time of installing the development dependencies 
```sh
bin/plugin install --development
```
in your test time measurement?

**Comment by zhenghu** [comment] 2015-05-22 07:25
@colinsurprenant No I am not including the installing time.
Here are two screenshot of the test report. The time is the pure test time. 

report-1.4.2
![report_1 4 2](https://cloud.githubusercontent.com/assets/3342705/7765934/1e662916-0064-11e5-836c-0aa49b4896df.png)

report-1.5.0
![report_1 5 0](https://cloud.githubusercontent.com/assets/3342705/7765935/1e672046-0064-11e5-9902-c30948b03901.png)

**Comment by colinsurprenant** [comment] 2015-05-22 14:39
@zhenghu ok. it's very hard to diagnose without having access to the actual code. 

Would you be willing to try and create a minimal example which recreates this behaviour and share that with us? Or, if you can share your spec & code we could look at it?

**Comment by zhenghu** [comment] 2015-05-22 16:08
@colinsurprenant 
I put the conf and test ruby file in my google drive.

Here is the shareLink : https://drive.google.com/folderview?id=0B2lbKsz3TibJfmVudmFwM3N4M0l1cXlJdjl2Ry15Qko2UThkVV9MdGlDVHVMV2lGZmJJTkE&usp=sharing

Hoping this help.

**Comment by mrdavidlaing** [comment] 2015-08-01 06:48
:+1: for this - I've noticed a similar slowdown in my logstash rspec tests

**Comment by talevy** [comment] 2017-02-17 17:22
Closing this issue since it has been open for a long time and we haven't received the details to debug it further. Please reopen a new issue if you still run into issues

**Closed by talevy** 2017-02-17 17:22 UTC
Labels: needs details, performance regression, tests-infra, unconfirmed
