### ISSUE TITLE
Pipeline stops processing events because of exception in filterworker "#<NoMethodError: undefined method `>' for nil:NilClass>"

### ISSUE THREAD

**Issue by robinsmidsrod** [elastic/logstash#1637] opened 2014-08-15 08:04 UTC
I'm getting this error in the logstash error log, and when it happens the pipeline stops processing events. The inputs are still able to receive events, but no events get through to the output stage.

```
{:timestamp=>"2014-08-14T08:09:19.415000+0000", :message=>"Exception in filterworker", "exception"=>#<NoMethodError: undefined method `>' for nil:NilClass>, "backtrace"=>["(eval):920:in `initialize'", "org/jruby/RubyProc.java:271:in `call'", "/opt/logstash/lib/logstash/pipeline.rb:262:in `filter'", "/opt/logstash/lib/logstash/pipeline.rb:203:in `filterworker'", "/opt/logstash/lib/logstash/pipeline.rb:143:in `start_filters'"], :level=>:error}
```

The error happens infrequently (about every other day or so), so I'm unsure what exactly is causing it.

I'm using the website DEB of logstash 1.4.2 on Ubuntu 14.04.

```
# java -version
java version "1.7.0_55"
OpenJDK Runtime Environment (IcedTea 2.4.7) (7u55-2.4.7-1ubuntu1)
OpenJDK 64-Bit Server VM (build 24.51-b03, mixed mode)
```

What other information do you need to debug this further?

**Comment by tmortensen** [comment] 2015-01-30 16:22
I ran into the same issue,  I am glad to report the workaround solved my issue. 
My filter sample is pretty short,  It for sure is a result of testing an empty field. 

http://pastebin.com/xy4r41rQ

**Comment by chenryn** [comment] 2015-03-06 03:54
I got similar exceptions when I wrote some codes in filters/ruby. I know I should use conditions before my `evnet['fieldname'].split()` operation, but, only 0.01% lines don't have such fieldname exists, why we must jadge this every line?

I image whether logstash can has a mechanism to restart the died filterworker to force the number of filterworkers equal `-w` setting.

**Comment by derjohn** [comment] 2015-05-19 12:24
Workaround?
  
ruby {
    # because if [somevar] doesnt work in all cases
    code => "if not defined? event['somevar']; event['somevar'] = 'dummyvalue' end"
  }

**Comment by hmorgado** [comment] 2015-08-07 14:06
Same thing happened to me and a simple verification if the field is not null solved the problem.
```
if [responsetime] {
        ruby {
	    code => "event['responsetime'] = event['responsetime'] / 1000"
        }
}
```

**Comment by suyograo** [comment] 2016-01-28 20:56
We'll reopen this if it happens in 2.x

**Comment by sprysprocket** [comment] 2016-02-18 21:40
This just happened to me in 2.2.1. The case is nearly identical to the original timestamp comparison case that kicked off this issue.

My configuration is pretty beefy, and would take a while to boil down. That said, I was able to reproduce easily by just adding the following to any ol' filter:

```
filter {
  if [bogusfield] < 100 {
    drop {}
  }
}
```

...which kills the logstash process. The logstash.err log shows the following:

```
NoMethodError: undefined method `<' for nil:NilClass
  cond_func_613 at (eval):11739
           each at org/jruby/RubyArray.java:1613
  cond_func_613 at (eval):11737
    filter_func at (eval):2024
   filter_batch at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.2.1-java/lib/logstash/pipeline.rb:256
           each at org/jruby/RubyArray.java:1613
         inject at org/jruby/RubyEnumerable.java:852
   filter_batch at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.2.1-java/lib/logstash/pipeline.rb:254
    worker_loop at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.2.1-java/lib/logstash/pipeline.rb:212
  start_workers at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.2.1-java/lib/logstash/pipeline.rb:190
```

Adding the null check eliminates the problem, but it does seem less than ideal that the entire process exits, rather than registering the error, and moving along.

**Comment by FlorianLiers** [comment] 2016-06-15 10:57
Happened to me as well in version 2.3.0. That's very anoying and reduces the stability of the whole solution significantly. @suyograo: Can you please re-open this issue?

**Comment by ebuildy** [comment] 2016-06-16 10:29
You should add an option on LogStash in order to catch filter exceptions, since these exceptions are based on input data that user cannot predict. (I am running the same very important issue with useragent filter, if useragent value is not a string, filter throws an exception then LogStash itself stops).

**Comment by andrewvc** [comment] 2016-06-16 12:22
I'm reopening this issue since its still a problem in 2.x / 5.0, and yes, is serious and preventable.

**Comment by andrewvc** [comment] 2016-06-16 12:26
My $0.02

1. We should catch filter exceptions and log them rather than crashing
2. The UX around these things is tricky. I think the most sensible thing is to convert `[foo] > 0` to `[foo] and [foo] > 0`.

**Comment by ikoniaris** [comment] 2016-06-17 00:43
Yup, adding a check for the actual field in your condition before the comparison should work as @andrewvc said above.

**Comment by kares** [comment] 2021-11-10 05:38
closing this old timer

**Closed by kares** 2021-11-10 05:38 UTC
Labels: bug, v5.5.0
