### ISSUE TITLE
logstash-web init scripts still packaged in logstash 2.0

### ISSUE THREAD

**Issue by igalic** [elastic/logstash#4352] opened 2015-12-15 08:19 UTC
```
igalic@log01 ~ % dpkg -l  logstash
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                 Version              Description
+++-====================-====================-========================================================
ii  logstash             1:2.0.0-1            An extensible logging pipeline
igalic@log01 ~ % dpkg -S /etc/init/logstash-web.conf
logstash: /etc/init/logstash-web.conf
igalic@log01 ~ % dpkg -L logstash | grep logstash-web
/etc/init/logstash-web.conf
/etc/default/logstash-web
/etc/init.d/logstash-web
igalic@log01 ~ %
```

**Comment by jordansissel** [comment] 2015-12-16 01:26
Good catch. <3

**Comment by jordansissel** [comment] 2016-01-06 20:32
I can't reproduce this:

```
% ar p logstash_2.0.0-1_all.deb data.tar.gz | tar -zt | grep etc/init.d
./etc/init.d/
./etc/init.d/logstash
```

I suspect your logstash-web file is left-over from a prior logstash version that shipped it - and that file was likely marked as a config file, so it persisted across package removal or upgrades. You may have to use dpkg/apt-get's purge feature to purge this file.

I can at least confirm that the 2.0.0 deb package does _not_ contain logstash-web.

**Comment by suyograo** [comment] 2016-01-06 20:33
Thanks @jordansissel 

@igalic can you try from a fresh install. If you can reproduce, I'll reopen this issue

**Closed by suyograo** 2016-01-06 20:33 UTC
Labels: bug, packaging, v2.2.0
