### ISSUE TITLE
Temporary JRuby files in /tmp are not cleaned up in SuSE

### ISSUE THREAD

**Issue by danhermann** [elastic/logstash#11051] opened 2019-08-14 15:12 UTC
**Logstash version:** 7.x

**Server OS version:** SuSE Enterprise Linux 12 SP4

**Describe the bug:** User reported that the temporary files are not being automatically cleaned up, as expected, and the temporary directory (`/tmp`) is being filled up with directories of format `jruby-<pid>/<name>.jar`.
Tested with 7.1.1 and 7.3.0.

**Steps to reproduce:**
1. install logstash as rpm
2. start configure some pipeline configuration
3. See temporary files accumulate in the tmp directory
I didn't have any debug configuration and pipeline configuration just was an stdout output and a generator input and some simple filter configuration

**Expected behavior:**
Temporary files are supposed to be deleted after report is completed.

**Comment by AndrewMcQuerry** [comment] 2020-07-08 18:00
We're seeing this on 6.8.1 and 6.8.3 as well, tar install.  It would seem that some of the jruby-<pid> directories are successfully having their contents emptied (yet the directory still exists), while others still contain various .jar's totalling 7.2Mb per directory in our case.

**Comment by AndrewMcQuerry** [comment] 2020-07-08 18:07
The commit above only addresses if the PID of logstash is 1.
Is there a plan for addressing logstash instances that run in linux with variable PIDs?

jruby-37317
jruby-37707
jruby-4149966
jruby-4150483
jruby-4160723
jruby-457642

In addition, we currently run multiple logstash instance (separate JVM's) on the same Linux Server.   Having an "rm -rf /tmp/jruby-*" would most likely remove jruby directories for logstash instances that are still running.  Is this directory required to be present during an entire run of logstash? or is it OK for it to be removed even for a JVM/PID that is still running?

**Comment by rwaweber** [comment] 2021-01-26 04:24
Another pair of related symptoms:

When using the kafka output plugin(could be reproducible with the input plugin, haven't tested) with snappy compression, it seems to be dropping a snappy shared library file in `/tmp` after every restart.

Also seems to be creating a `/tmp/logstash$bignum/org/logstash/generated/CompiledDataset/` directory with a bunch(19) of files that are all names `CompiledDataSet[0-19].java`, though I feel like that likely has something to do with the config file compiler internals.

**Comment by brunobastosg** [comment] 2021-05-21 13:39
I have the same problem. Logstash 7.x running on CentOS 7.

**Comment by dimovnike** [comment] 2021-09-01 12:05
The problem is present in the docker image also:

image: docker.elastic.co/logstash/logstash:6.8.0
13G     /var/lib/docker/overlay2/803c0ddecf3965b250534970a05075e70b2af52c71eaa15576cef60cac22e8ec/diff/tmp/jruby-1

is there any workaround for this?

**Comment by jasonneurohr** [comment] 2021-09-20 06:30
We are experiencing this behaviour on Logstash 7.13.2 (RPM install) on RHEL 7.8 which is filling up our VM disks.

Can we get it resolved or confirm we can periodically clear the files without impacting data going through logstash?

**Comment by vishnupriya9017** [comment] 2021-12-08 11:14
I'm using Logstash 7.12.X deployed in SuSE. I could see the same issue the jruby temp folder growing with the restarts of the service it is above 1 GB. Any leads how to resolve this?

**Comment by maltewhiite** [comment] 2021-12-29 09:46
I am seeing this on logstash 7.16.2 using [Puppet](https://forge.puppet.com/modules/elastic/logstash). Running CentOS

**Comment by maltewhiite** [comment] 2022-01-14 11:54
This is ridiculous. Keeps filling up all our Logstash servers and killing them. 

![image](https://user-images.githubusercontent.com/90693329/149511497-528714ed-7226-473c-a0a4-401a3bd38c3a.png)

**Comment by Mauro-Rizzi** [comment] 2022-01-14 20:35
Since I first commented on this on August I learned a few things:

1- This seems to only happen when you run more than one logstash instance at a time (from different installations on the same machine)
2 - You can delete the files freely as long as they are not locked (and consequently in active use)
3 - Because of the above what I did was to edit the bat (Yes, because of company policy I have to use windows) file and make it run a powershell that deletes these files recursevily (while being unable to delete the ones currently being used by a process). Since I run this second logstash instance every 5 minutes this means I don't get any leftover files clogging the system. If you're running into a similar problem you could just cron this cleanup to run every 5 or 10 minutes and generally have no issue. This is just a workaround.
4 - I really feel it's outrageous this hasn't been given much priority.

**Comment by rwaweber** [comment] 2022-01-21 14:59
Since elastic has largely ignored this problem for a few years now, you may want to give [vector](https://vector.dev) a shot.

We've moved a large number of our pipelines over and seen a substantial performance increase and resource utilization drop since.

While what I'm proposing is certainly not a solution for this problem, it's been a thousand cuts of problems like this with logstash over the years that eventually caused my team to give up on it and move to something else.

**Comment by dantamsdb** [comment] 2022-08-15 15:16
> 1- This seems to only happen when you run more than one logstash instance at a time (from different installations on the same machine) 

We are seeing this happen on a server where only a single instance of Logstash is running. 

It seems that every time we restart Logstash, a new jruby directory is created.

**Comment by kaisecheng** [comment] 2022-08-26 15:11
This might relate to a  jruby [issue](https://github.com/jruby/jruby/issues/3352). Sending SIGKILL to logstash in ubuntu results in unclean /tmp/jruby-$PID/. A graceful shutdown does clean the folder. 

"rm -rf /tmp/jruby-*" is not ideal as other jruby processes may use the resources.

logstash-core can write the pid to `path.data` and clean up /tmp/jruby at startup

**Comment by kaisecheng** [comment] 2022-08-27 14:59
The issue happens in the latest v7.17.6 and has gone in v8.1.0 after the [pr](https://github.com/elastic/logstash/pull/13159) of dropping redundant jruby-complete.jar

**Comment by kaisecheng** [comment] 2022-09-05 15:52
The issue is fixed since v8.1.0, hence close the issue.

**Closed by kaisecheng** 2022-09-05 15:52 UTC
Labels: bug

**Comment by claudia-a-tavares-alb** [comment] 2024-06-27 09:17
These Issue was resolved in some 7.17.X version?
