### ISSUE TITLE
How Dissect filter handle with new line

### ISSUE THREAD

**Issue by MoonChaserChen** [elastic/logstash#10467] opened 2019-02-19 03:33 UTC
**I have a message like:**
_com.fifedu.kyxlPay.service.impl.PurchaseOrderServiceImpl
2019-02-16 20:19:33 ERROR [http-bio-6040-exec-6][](PurchaseOrderServiceImpl.java:58) ===== Current course has been paid. userId: cd719dbed1564f15abc242e6c85d882a, courseId: 4569c8ad6e714cbb8f48265f6ebae6d7_
**And i want to extract this message to:**
{
           "msg" => "===== Current course has been paid. userId: 6c2ae253479144c8a36959434cdc91c2, courseId: e19f436ffe2349f1869c620d099dac28",
         "level" => "ERROR",
        "thread" => "http-bio-6040-exec-9",
       "message" => "com.fifedu.kyxlPay.service.impl.PurchaseOrderServiceImpl\n2019-02-16 18:41:24 ERROR [http-bio-6040-exec-9][](PurchaseOrderServiceImpl.java:58) ===== Current course has been paid. userId: 6c2ae253479144c8a36959434cdc91c2, courseId: e19f436ffe2349f1869c620d099dac28",
         "where" => "PurchaseOrderServiceImpl.java:58",
         "class" => "com.fifedu.kyxlPay.service.impl.PurchaseOrderServiceImpl",
            "ts" => "2019-02-16 18:41:24"
}
**And this is part of my bad code which can't get the right result:**
```
filter {
    dissect {
        mapping => {
            "message" => '"%{class}"
"%{details}"'
            "details" => "%{ts} %{+ts} %{level} [%{thread}][](%{where}) %{msg}"
        }
    }
}
```
**Instead i get the result like:**
{
       "details" => "com.fifedu.kyxlPay.service.impl.PurchaseOrderServiceImpl\n2019-02-16 20:19:26 ERROR [http-bio-6040-exec-3][](PurchaseOrderServiceImpl.java:58) ===== Current course has been paid. userId: cd719dbed1564f15abc242e6c85d882a, courseId: 4569c8ad6e714cbb8f48265f6ebae6d7",
       "message" => "com.fifedu.kyxlPay.service.impl.PurchaseOrderServiceImpl\n2019-02-16 20:19:26 ERROR [http-bio-6040-exec-3][](PurchaseOrderServiceImpl.java:58) ===== Current course has been paid. userId: cd719dbed1564f15abc242e6c85d882a, courseId: 4569c8ad6e714cbb8f48265f6ebae6d7",
         "class" => "",
}

**Logstash Version is 5.6.3**

**Comment by yaauie** [comment] 2019-02-19 17:22
Since this is a general usage question, and not a reproducible bug report or feature request, I'm closing this issue. We ask that general usage questions be handled within our forums, which have a wider audience and faster response times.

> Please post all product and debugging questions on our [forum](https://discuss.elastic.co/c/logstash).
> Your questions will reach our wider community members there, and if we confirm that there is a bug, then we can open a new issue here.
> 
> -- [Logstash Issue Template](https://raw.githubusercontent.com/elastic/logstash/master/.github/ISSUE_TEMPLATE.md)

Hopefully the following will also help you get on track:

***

Assuming you have an appropriate multiline configuration and that the events are not being split up before hitting your filter, then it is possible to use a literal newline in your dissect filter; the dissect filter also cannot have extra quotes around the values you are attempting to capture.

The following works for me, to extract everything up until your log message (which likely contains a variable number of spaces and is a bit tricky).

~~~
filter {
    dissect {
        mapping => {
            "message" => '%{class}
%{ts} %{+ts} %{level} [%{thread}] ===== %{details}'
        }
    }
}
~~~

If you have further questions, please follow up by creating an issue in the [forum](https://discuss.elastic.co/c/logstash).

**Closed by yaauie** 2019-02-19 17:22 UTC
