### ISSUE TITLE
random failure in rake test:core

### ISSUE THREAD

**Issue by colinsurprenant** [elastic/logstash#5157] opened 2016-04-21 16:49 UTC
I just go this random failure in `rake test:core`. something to investigate? @ph @purbon 

```
Failures:

  1) LogStash::Agent metrics after config reloading resets the metric collector
     Failure/Error: expect(snapshot.metric_store.get_with_path("/stats/events")[:stats][:events][:in].value).to eq(new_config_generator_counter)
     LogStash::Instrument::MetricStore::MetricNotFound:
       For path: stats
     # ./logstash-core/lib/logstash/instrument/metric_store.rb:136:in `get_recursively'
     # ./logstash-core/lib/logstash/instrument/metric_store.rb:135:in `get_recursively'
     # ./logstash-core/lib/logstash/instrument/metric_store.rb:92:in `get'
     # ./logstash-core/lib/logstash/instrument/metric_store.rb:80:in `get_with_path'
     # ./logstash-core/spec/logstash/agent_spec.rb:374:in `(root)'
     # ./vendor/bundle/jruby/1.9/gems/rspec-wait-0.0.8/lib/rspec/wait.rb:46:in `(root)'
     # ./rakelib/test.rake:42:in `(root)'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.1.2/lib/rake/task.rb:248:in `execute'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.1.2/lib/rake/task.rb:243:in `execute'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.1.2/lib/rake/task.rb:187:in `invoke_with_call_chain'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.1.2/lib/rake/task.rb:180:in `invoke_with_call_chain'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.1.2/lib/rake/task.rb:173:in `invoke'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.1.2/lib/rake/application.rb:150:in `invoke_task'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.1.2/lib/rake/application.rb:106:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.1.2/lib/rake/application.rb:106:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.1.2/lib/rake/application.rb:115:in `run_with_threads'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.1.2/lib/rake/application.rb:100:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.1.2/lib/rake/application.rb:78:in `run'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.1.2/lib/rake/application.rb:176:in `standard_exception_handling'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.1.2/lib/rake/application.rb:75:in `run'

Finished in 38.62 seconds (files took 3.51 seconds to load)
926 examples, 1 failure

Failed examples:

rspec ./logstash-core/spec/logstash/agent_spec.rb:359 # LogStash::Agent metrics after config reloading resets the metric collector

Randomized with seed 48319
```

**Comment by ph** [comment] 2016-04-21 16:50
duplicate of https://github.com/elastic/logstash/issues/5152

**Closed by ph** 2016-04-21 16:50 UTC

**Comment by colinsurprenant** [comment] 2016-04-21 16:55
are you sure? it does not "look" like the same error & backtrace? but I'll leave that to you to judge!

**Comment by ph** [comment] 2016-04-21 16:57
The messge is a bit different, but its the same problem.
