### ISSUE TITLE
http input doesn't handle Content-Type with charset

### ISSUE THREAD

**Issue by martintrojer** [elastic/logstash#9231] opened 2018-03-12 15:08 UTC
- Version: 6.2.2
- Operating System: All
- Config File (if you have sensitive info, please remove it):
`input { http { port=>5045 }}`
- Sample Data:
1. `curl -XPOST http://localhost:5045 -H "Content-Type: application/json; charset=utf-8" -d '{"@metadata": {"beat": "foo"}}'`
vs
2. `curl -XPOST http://localhost:5045 -H "Content-Type: application/json" -d '{"@metadata": {"beat": "foo"}}'`
- Steps to Reproduce:
Curl example 1 above doesnt get parsed as JSON correctly while example 2 does. Logstash should handle both cases.

**Comment by jsvd** [comment] 2018-03-12 15:50
@martintrojer thank you for the report, but I'm closing as duplicate of https://github.com/logstash-plugins/logstash-input-http/issues/35

**Closed by jsvd** 2018-03-12 15:50 UTC
