### ISSUE TITLE
Deadlock in Logstash 1.5 with filter flusher

### ISSUE THREAD

**Issue by driskell** [elastic/logstash#3361] opened 2015-06-02 09:43 UTC
Hello,

I've noticed on one my multiline worker nodes I'm getting very frequent deadlocks in the "|worker" thread and "pipeline" thread. Other nodes are perfectly fine, so seems one of those annoying race conditions with very specific triggers. Also nodes without multiline filter, and therefore with `-w 8` for multiple workers, are fine too.

Investigating the Java stack trace (https://gist.github.com/driskell/2173a91ac3de78e035e9) and trying to locate the equivalent ruby code, it looks like there is a possibility of a race condition in regards to the filter flusher, if there's only one worker. Probably would never happen in MRI Ruby because of green threads. But JRuby native threads I think it could.

If the following happens between the filterworker `pop`ing off a Flush event and processing it in the mutex...
1. A new event is pushed onto the queue to fill it
2. The flush interval triggers and blocks trying to add a flush event to the queue
... then the filter worker will block trying to obtain the lock. However, the lock is held waiting for the queue to free up, which will never happen because the worker reading from the queue is blocked.
**Deadlock**

If I find time I'll try a PR. I think the solution is to push only a single flush event to the queue? And not push another until that one is processed. So just needs a flag inside the Mutex, say, `@filter_flush_pending` - that way if the circumstances above occur, number 2 wouldn't block as it wouldn't try to add another flush event.

**Comment by ph** [comment] 2015-06-02 13:23
@driskell Thanks we changed a bit that part and that could explain the newer issues, @colinsurprenant can you look at this please?

**Comment by driskell** [comment] 2015-06-02 13:37
So far my patch is working - the one I've committed above is slightly tweaked from what I'm testing but only on syntax level to make it cleaner so could be a good baseline. I'll apply it directly shortly and see how it runs next couple days (it's been hanging nearly every day since upgraded but not had time to look until now.)

I can raise as PR earlier if you wish.

**Comment by ph** [comment] 2015-06-02 13:40
@driskell I would still raise a PR if you can, other people using the multiline filter are reporting similar issues. With your report we will be able to reproduce it.

**Comment by driskell** [comment] 2015-06-02 21:35
@ph it's worth noting this is not related directly to multiline filter. It's purely related to single threaded worker setups, which includes all users of multiline filter but also includes others.

**Comment by driskell** [comment] 2015-06-02 21:37
@ph The root cause is in Logstash pipeline code it seems

**Comment by ph** [comment] 2015-06-03 14:08
@jsvd and I were able to reproduce it, we are discussing the need to actually do a synchronize on that part of the code.

**Comment by driskell** [comment] 2015-06-03 14:22
Ah. I guess inside the filter worker it doesn't need it at all.
It only needs it to synchronise the flusher thread kill so it doesn't kill it while it's pushing onto the queue, potentially corrupting the queue.

**Comment by jsvd** [comment] 2015-06-04 09:18
@driskell I think we could just keep the mutex for the [filterworker flush handling](https://github.com/elastic/logstash/blob/master/lib/logstash/pipeline.rb#L223) and the [kill call](https://github.com/elastic/logstash/blob/master/lib/logstash/pipeline.rb#L118). the flusher_thread is just pushing the flush event to the queue, at most it will block on a full queue (which is ok).

**Comment by driskell** [comment] 2015-06-04 10:10
But the flusher thread could get killed in the middle of a push. There's no guarantee this would not corrupt the queue from what I can see.

The filter worker is fine as it does not touch anything the other two areas do. The only other flush is after filter workers finish (and they are waited for before calling it)

**Comment by jsvd** [comment] 2015-06-04 10:19
humm not sure how the queue could get corrupted, the single op the thread does, SizedQueue#push, is essentially a [@mutex.synchronize wrapped in a Thread.handle_interrupt](http://ruby-doc.org/stdlib-2.0.0/libdoc/thread/rdoc/Queue.html#method-i-push) block.

anyway I think removing the whole flusher_lock mutex should not be a problem, thoughts?

**Comment by driskell** [comment] 2015-06-04 10:32
MRI is thread handle interrupt but in JRuby it is a Java class and AFAICT it doesn't do any interrupt handling.

**Comment by ph** [comment] 2015-06-04 15:21
@jsvd @driskell I think we can remove the the lock on filterworker flush, this will revert back the behavior of 1.4.2.

But, we also need to change some of the filters to make sure they are thread safe and protect the `filter` and the `flush` method, I suggest to create another issue to add a thin layer on top of the plugins that will add automatically add this check when the plugin implement a flush method.

A quick find show the plugins that implements flush.
```
logstash-filter-collate/lib/logstash/filters/collate.rb:101:  def flush(options = {})
logstash-filter-collate/lib/logstash/filters/collate.rb:114:  end # def flush
logstash-filter-elapsed/lib/logstash/filters/elapsed.rb:174:  def flush(options = {})
logstash-filter-metaevent/lib/logstash/filters/metaevent.rb:34:  def flush
logstash-filter-metrics/lib/logstash/filters/metrics.rb:176:  def flush(options = {})
logstash-filter-multiline/lib/logstash/filters/multiline.rb:186:  def flush(options = {})
```

**Comment by colinsurprenant** [comment] 2015-06-04 15:26
Thanks guys for looking into this. I will followup with the background info on why I added this in the first place. As you guys figured out, there is indeed clearly a deadlock situation. Here are my thoughts:
- we should and will refactor this, @ph & @jsvd has good ideas plus the new shutdown logic we are looking into in #3210 but this will be for a future 1.6/2.0 release.
- in the short-short term, I think that just removing the `@flusher_lock.synchronize` on https://github.com/elastic/logstash/blob/master/lib/logstash/pipeline.rb#L223 should solve this. This mutex lock is in fact useless since the `LogStash::FlushEvent` signal passing already provides the sequencing of the calling of the filter and flush method in the plugins to avoid concurrently call both from different threads. The `@flusher_lock.synchronize`  on https://github.com/elastic/logstash/blob/master/lib/logstash/pipeline.rb#L118 is actually just there to avoid sending a `Thread.kill` in the middle of the push operation which could cause corruption. 

Note that with the previous short-term fix, a shutdown sequence could still hang if the output queue stays full. Since we already send a `Thread.kill` to stop the filters "without protection" then maybe having this protection for the flusher during the shutdown is superfluous since this problem currently exists anyway with the filters. Maybe we should just keep the current potential "problem" as-is in 1.5 and  just remove the `@flusher_lock.synchronize` everywhere and instead aim for the "real" fix in 1.6? This would "fix" the runtime deadlock and the shutdown deadlock, at the cost of loosing some data in the shutdown when output is stuck, which has already been the case in 1.5 and earlier versions. 

Thoughts?

**Comment by ph** [comment] 2015-06-04 15:27
thanks for @colinsurprenant and @jsvd comments, there is not need to change any plugins.

**Comment by colinsurprenant** [comment] 2015-06-04 15:28
@ph we do not need to change the filter plugins even if we remove the `@flusher_lock.synchronize` everywhere since the `flush` and `filter` methods are never called concurrently, its either one or the other, always from the filter worker.

**Comment by colinsurprenant** [comment] 2015-06-04 15:29
@ph we have concurrency issues in our comments :P

**Comment by ph** [comment] 2015-06-04 15:30
@colinsurprenant Until we have the persistent queue in place losing in transit events if the output are block is something we can't cleanly deal.

**Comment by colinsurprenant** [comment] 2015-06-04 15:34
@ph well there could be alternatives but would require adding timeouts to the blocking queues and log dropped events in the shutdown (they would sitll be "lost" but at least logged so you could retrieve them if you really wanted to), but this is not really in the scope of this issue and I agree with you that the better solution is to use persistence in this case.

**Comment by ph** [comment] 2015-06-04 15:35
@colinsurprenant Yes,I agree to remove the lock also in the Tick and the shutdown sequence at the cost of losing some events. 

+ 1 for timeouts.

**Comment by jsvd** [comment] 2015-06-04 15:38
+1 on all of the above
always happy to remove a mutex :+1:

**Comment by colinsurprenant** [comment] 2015-06-04 17:42
@driskell what do you think about this strategy + would you mind trying #3378 ?

**Comment by driskell** [comment] 2015-06-04 18:07
Looks good I'll give it a try over the weekend.

I can see JRuby by design won't corrupt a queue. The kill works by sending 'mail' according to wiki and getting checked by a thread poll call (which happens every few statements and around sleeps and io calls I think). So probably all good apart from the original shutdown problem you noted.

**Comment by ph** [comment] 2015-06-08 15:14
fixed in https://github.com/elastic/logstash/issues/3361

**Closed by ph** 2015-06-08 15:14 UTC
Labels: blocker, bug, v1.5.1

**Comment by slava-vishnyakov** [comment] 2015-06-11 11:34
@ph Thank you for the fix! Works as expected!

**Comment by dirtdiver512** [comment] 2015-06-11 17:14
All,  Not sure i am having a related issue but the LS is hanging.  it works for sometimes a few minutes to a few hours then just hangs.  I try and stop the service and it will not stop so I have to kill it, then restart it.  nothing in the logs.  I replaced the file here:

https://raw.githubusercontent.com/driskell/logstash/fe1cb7c91f13fda1661b9471dbcc4bd390b4d487/lib/logstash/pipeline.rb

**Comment by colinsurprenant** [comment] 2018-11-19 17:38
@yinrong thanks for your feedback - please note that this is a very old issue related to a very old and now unsupported logstash version and a lot of improvements has been made since then. 

If you have a problematic use-case please do not hesitate to share the specific details with us, the more information and reproduction details you provide, the easier for us it will be to troubleshoot and hopefully fix a problem.
Thank you.
