### ISSUE TITLE
support installing local plugins .gem files

### ISSUE THREAD

**Issue by jordansissel** [elastic/logstash#2779] opened 2015-03-05 21:06 UTC
Info: https://gist.github.com/tebriel/f58980f662ca17dc2ded

This gemfile worked in 1.5.0 beta1, but not 1.5.0 rc1

**Comment by tebriel** [comment] 2015-03-05 21:07
Thank you!

**Comment by ph** [comment] 2015-03-09 19:47
@tebriel I assume you are currently developing this plugin.

`bin/plugin install my-plugin.gem` is currently broken.
If you want to test an unpublished gem inside a logstash installation you can do the following.

Edit the logstash `Gemfile`, add a line similar to this one `gem 'my-plugin', :path => '~/src/my-plugin'` and run `bin/plugin install --verify` this will make the plugin in development available inside the logstash installation.

**Comment by tebriel** [comment] 2015-03-10 03:53
Okay thanks, I'll do that.

**Comment by colinsurprenant** [comment] 2015-03-10 15:56
Yes, thanks for the report, we will be providing support for this in 1.5, this feature has been a collateral damage of the recent refactor of the plugin architecture :P

**Comment by robmckeown** [comment] 2015-03-10 19:26
Getting similar 
[rmckeown@oc3122150850 logstash-1.5.0.rc2]$  bin/plugin install --verify /home/rmckeown/dev/lsPlugins/logstash-output-scacsv/logstash-output-scacsv-0.2.1.gem 
Validating /home/rmckeown/dev/lsPlugins/logstash-output-scacsv/logstash-output-scacsv-0.2.1.gem
Error reading plugin file /home/rmckeown/dev/lsPlugins/logstash-output-scacsv/logstash-output-scacsv-0.2.1.gem, caused by NameError

**Comment by tebriel** [comment] 2015-03-10 19:28
Yeah same problem as mine. Installing from gem via plugin command is broke currently.

Sent from my iPhone

On Mar 10, 2015, at 12:27 PM, Rob Mckeown <notifications@github.com<mailto:notifications@github.com>> wrote:


Getting similar
[rmckeown@oc3122150850 logstash-1.5.0.rc2]$ bin/plugin install --verify /home/rmckeown/dev/lsPlugins/logstash-output-scacsv/logstash-output-scacsv-0.2.1.gem
Validating /home/rmckeown/dev/lsPlugins/logstash-output-scacsv/logstash-output-scacsv-0.2.1.gem
Error reading plugin file /home/rmckeown/dev/lsPlugins/logstash-output-scacsv/logstash-output-scacsv-0.2.1.gem, caused by NameError

**Comment by robmckeown** [comment] 2015-03-10 19:37
@tebriel - did you try this 'Edit the logstash Gemfile, add a line similar to this one gem 'my-plugin', :path => '~/src/my-plugin' and run bin/plugin install --verify this will make the plugin in development available inside the logstash installation' and did it resolve the issue for you ?

**Comment by tebriel** [comment] 2015-03-10 19:41
I have not, I'm at Elastic{ON} right now and probably shouldn't be mucking around on the box that handles all our logstash data. Will have to wait until Thursday or Friday to try.

**Comment by tebriel** [comment] 2015-03-10 19:51
```
cmoultrie@Sauron ~/G/logstash-1.5.0.rc2> bin/plugin install --verify
No plugin specified
```

**Comment by DanielRedOak** [comment] 2015-03-10 21:27
I am trying similar but I am trying to update an existing plugin, namely logstash-input-s3.  I tried adding the gem 'logstash-input-s3', :path => bit but it seems to keep grabbing the provided one.

**Comment by tebriel** [comment] 2015-03-10 21:31
Have you tried uninstalling and then going from scratch? Given that the .gem install process is broken, maybe the upgrade is too if going by .gem

**Comment by DanielRedOak** [comment] 2015-03-10 21:32
Yep, removed and verified it was gone.  Remove all references in Gemfile Gemfile.defaults and Gemfile.jruby1-.9.lock

**Comment by tebriel** [comment] 2015-03-10 21:38
crappy idea, but rename the plugin locally and rebuild it so that it can't fetch out the new name? Otherwise I'm out of suggestions and someone from the Logstash team will have to pipe in.

**Comment by ph** [comment] 2015-03-10 21:59
@tebriel @DanielRedOak The `:path` option should be a directory and not an actual `plugin.gem`.

@DanielRedOak did you look at the `vendor/bundle/jruby/1.9/gems/` if the s3 plugins was still there?

**Comment by DanielRedOak** [comment] 2015-03-10 22:01
@ph yep, had :path as the path to the dir and verified that the gem was not installed :/

**Comment by ph** [comment] 2015-03-10 22:09
@DanielRedOak Are you doing the `bin/plugin install` inside the master branch or with the tar.gz release? I have an issue on my side where the plugin isn't uninstalled.

**Comment by DanielRedOak** [comment] 2015-03-10 22:09
tar.gz of rc2

**Comment by ph** [comment] 2015-03-10 22:10
Yeah, same issue here! we are getting somewhere :)

**Comment by tebriel** [comment] 2015-03-10 22:22
@ph I'm now just thrashing around. Can you spot anything else wrong?

```
cmoultrie@Sauron ~/G/logstash-1.5.0.rc2> ls -l ~/Downloads/
-rw-r--r--@ 1 cmoultrie  staff        9216 Feb 10 16:14 logstash-filter-geohashcid-0.1.0.gem
-rw-r--r--@ 1 cmoultrie  staff        9728 Feb 10 16:15 logstash-filter-identify-0.1.0.gem
-rw-r--r--@ 1 cmoultrie  staff        9728 Feb 10 16:15 logstash-filter-multirequest-0.1.0.gem
```

```
gem 'logstash-filter-geohashcid', :path => '~/Downloads/'
gem 'logstash-filter-identify', :path => '~/Downloads/'
gem 'logstash-filter-multirequest', :path => '~/Downloads/'
```

```
cmoultrie@Sauron ~/G/logstash-1.5.0.rc2> bin/plugin install --verify logstash-filter-geohashcid
Validating logstash-filter-geohashcid
Plugin logstash-filter-geohashcid does not exist
Installation aborted
```

**Comment by ph** [comment] 2015-03-10 22:22
@tebriel are you still at the conference?

**Comment by tebriel** [comment] 2015-03-10 22:23
@ph yes, about 10ft away from the Genius Bar.

**Comment by ph** [comment] 2015-03-10 22:24
i am at the genius bar ! right side

**Comment by ph** [comment] 2015-03-10 22:33
the right command is `bin/plugin install --no-verify` to skip the verification process, just edited the previous comment. Still investigating your issue @DanielRedOak

**Comment by DanielRedOak** [comment] 2015-03-11 17:12
Here is the issue: https://github.com/elastic/logstash/blob/master/lib/logstash/pluginmanager/install.rb#L73

This writes back to the gemfile the plugin name and version and doesn't keep any other options.  Then things continue on with the now plain 'gem "logstash-input-s3"'

**Comment by colinsurprenant** [comment] 2015-03-11 18:18
@DanielRedOak what I understand is that you are trying to update input-s3 with local version that you modified/patched?

if this is the case, try this: first uninstall your input s3: `bin/plugin uninstall logstash-input-s3` then edit your `Gemfile` and add `gem "logstash-input-s3", :path => "/path/to/your/gem/dev/dir"` and do a `bin/plugin install --no-verify`. 

Let me know if that works. Yes, the options are dropped at the code you pointed at, I'll review this.

@ph let's pair today on this at the genius bar?

**Comment by DanielRedOak** [comment] 2015-03-11 18:22
Commenting out that line in code and running the install with --no-verify is how I got things working. Without commenting out that line it just re-installed from rubygems.org since the Gemfile was modified before bundler ran

**Comment by colinsurprenant** [comment] 2015-03-11 21:26
@DanielRedOak after editing your `Gemfile` and adding `:path` did you do?
```sh
bin/plugin install --no-verify
```
or
```sh
bin/plugin install --no-verify logstash-input-s3
```
I think you might be doing the latter  in which case I can see how the path would be removed, but if you only do the former: `bin/plugin install --no-verify` without specifying the actual plugin, it should work.

The idea is that a bare `bin/plugin install --no-verify` will process your current `Gemfile` so it will pickup any edits you made to it.

**Comment by DanielRedOak** [comment] 2015-03-11 21:36
I was doing bin/plugin install --no-verify logstash-input-s3 so that could very well be it

**Comment by colinsurprenant** [comment] 2015-03-11 22:06
yeah, then it would definitely get rid of the options as you noted. I think it is more a proper documentation issue - and I'm really open to suggestions here... my idea is that when doing `bin/plugin install --no-verify logstash-input-s3` it should always go and try to remote install the plugin. It you know what you are doing and edit you `Gemfile` then `bin/plugin install --no-verify` is all you need to process that `Gemfile`. 

In "normal" usage scenarios the `Gemfile` is never hand edited so that should never be an issue. For developers, you can end up editing the `Gemfile` if you want to point a plugin to a local dev directory using `:path` just like you are doing in which case I am wondering what should be expected if doing `bin/plugin install --no-verify logstash-input-s3`... thoughts?

Maybe it's just the `--no-verify` options that is confusing? 

Maybe we should provide just another command altogether like `bin/bundle` to process the local `Gemfile` so that using `bin/plugin install` is always for remote installation (or for a local `.gem` file when fixed).

**Comment by DanielRedOak** [comment] 2015-03-12 16:55
Yea I was confused.  Maybe throwing in an option that forces use of the local gemfile or atleast pretends to?  bin/plugin install --no-verify --from-gemfile  I just had assumed you always needed to specify the plugin to install.  

Either that or just make it known that bin/plugin install --no-verify will just use the Gemfile

In any case, when the option to install like bin/plugin install some.gem works again it might all be moot

**Comment by colinsurprenant** [comment] 2015-03-13 03:18
Well, from a development perspective, using `:path` is much more practical: you don't have to build the gem every time you want to test it, you just call `bin/plugin install --no-verify` once and every time you run the plugin, it is directly from the development directory. 

So, granted it is confusing as it is.

The more I think about it I think we should just expose the Bundler `bundle` command for developers with either `bin/bundle ...` or  `bin/plugin bundle ...`. This way to process the local `Gemfile` you could do `bin/bundle` or `bin/bundle install` but you could also use all the options of the original bundle command.

**Comment by nathanlburns** [comment] 2015-03-18 00:15
Any update on this issue? How can I install a plugin from a gem file? The workaround pasted above does not work for me. I have a new output plugin that is not public. Only source is gem file. Gem file worked in beta1, but not rc2. 

I have added the gem to the Logstash gem file and specified path pointing to the directory containing the gem. The error I get is 'Plugin not found, aborting'.

**Comment by nathanlburns** [comment] 2015-03-18 00:41
Quick update, I can install from local path if it's extracted gem, not the compiled one.  

When is a fix expected for gem file based install? This is blocking me from being able to test at scale.

**Comment by tebriel** [comment] 2015-03-18 03:24
Currently you have to install from the source directory, not the gem file. You cannot install from a gem file in RC1.

Sent from my iPhone

On Mar 17, 2015, at 8:41 PM, Nathan Burns <notifications@github.com<mailto:notifications@github.com>> wrote:


Quick update, I can install from local path if it's extracted gem, not the compiled one.

When is a fix expected for gem file based install? This is blocking me from being able to test at scale.

**Comment by nathanlburns** [comment] 2015-03-18 16:43
Is there any estimate as to when this will once again be supported?

**Comment by suyograo** [comment] 2015-03-18 21:30
@nathanlburns we are looking at proposing a workaround for this in the 1.5.0 GA timeframe.

**Comment by javifr** [comment] 2015-04-08 11:11
Hi everybody,

I'm facing a quite strange situation.

I'm working on two new logstash plugins for Dropbox, based on the s3 logstash plugins:
- [Input](https://github.com/javifr/logstash-plugin-input-dropbox)
- [Output](https://github.com/javifr/logstash-plugin-output-dropbox)

Both plugins are working fine when installed **on my laptop-machine with Logstash.1.5.0.rc2**.
I've been able yo **add them to the logstash Gemfile**, and running a ```bin/plugin install --no-verify``` worked like a charm.

But I have a Digital Ocean instance running ELK ( I followed [this](https://www.digitalocean.com/community/tutorials/how-to-install-elasticsearch-logstash-and-kibana-4-on-ubuntu-14-04) tutorial ), and only the instalation of my logstash-output-dropbox is working. When I'm running ```bin/plugin install --no-verify``` with my **logstash-input-dropbox** I'm constantly getting this error:

````
root@elk-loyalguru:/opt/logstash# bin/plugin install --no-verify
Installing...
Error Bundler::GemspecError, retrying 1/10
Error Bundler::GemspecError, retrying 2/10
Error Bundler::GemspecError, retrying 3/10
Error Bundler::GemspecError, retrying 4/10
Error Bundler::GemspecError, retrying 5/10
Error Bundler::GemspecError, retrying 6/10
Error Bundler::GemspecError, retrying 7/10
Error Bundler::GemspecError, retrying 8/10
Error Bundler::GemspecError, retrying 9/10
Error Bundler::GemspecError, retrying 10/10
Too many retries, aborting, caused by Bundler::GemspecError
Installation aborted
```

Is really strange because on my local machine is perfectly working.

This is the Gemfile of the plugin that is not being installed:
https://github.com/javifr/logstash-plugin-input-dropbox/blob/master/logstash-input-dropbox.gemspec

I'm quite desperate...

Thans in advance to everybody.

**Comment by ph** [comment] 2015-04-08 13:54
First, cool plugins :)

Could you gist the content of your gemfile?

**Comment by javifr** [comment] 2015-04-08 14:02
Thanks ;)

There it goes the Gemfile of the logstash in my machine in digital ocean:

```bash
# This is a Logstash generated Gemfile.
# If you modify this file manually all comments and formatting will be lost.

source "https://rubygems.org"
gemspec :name => "logstash-core"
gem "logstash-input-dropbox", :path => "/opt/logstash-input-dropbox"
gem "logstash-output-dropbox", :path => "/opt/logstash-output-dropbox"
gem "logstash-output-zeromq"
gem "logstash-codec-collectd"
gem "logstash-output-xmpp"
gem "logstash-codec-dots"
gem "logstash-codec-edn"
gem "logstash-codec-edn_lines"
gem "logstash-codec-fluent"
gem "logstash-codec-es_bulk"
gem "logstash-codec-graphite"
gem "logstash-codec-json"
gem "logstash-codec-json_lines"
gem "logstash-codec-line"
gem "logstash-codec-msgpack"
gem "logstash-codec-multiline"
gem "logstash-codec-netflow"
gem "logstash-codec-oldlogstashjson"
gem "logstash-codec-plain"
gem "logstash-codec-rubydebug"
gem "logstash-filter-anonymize"
...
```

As i said before, if I remove the logstash-input-dropbox but I keep the logstash-output-dropbox, the installation proceeds fine. But the logstash-input-dropbox is giving me the problem.

**Comment by ph** [comment] 2015-04-08 14:05
Could you try this command and give us the output?

`DEBUG=1 bin/plugin install --no-verify`

**Comment by javifr** [comment] 2015-04-08 14:17
THANK YOU @ph !!!    :)

The problem is that the author meta has an accent ( Javi Fern**á**ndez ) that is being interpreted as an error, for some reason my local machine was ok with that, but my machine at Digital Ocean was not.

Here the output:
```
root@elk-loyalguru:/opt/logstash# DEBUG=1 bin/plugin install --no-verify
Installing...
Error Bundler::GemspecError, retrying 1/10
There was a SyntaxError while loading logstash-input-dropbox.gemspec:
/opt/logstash-input-dropbox/logstash-input-dropbox.gemspec:8: invalid multibyte char (US-ASCII)
Error Bundler::GemspecError, retrying 2/10
There was a SyntaxError while loading logstash-input-dropbox.gemspec:
/opt/logstash-input-dropbox/logstash-input-dropbox.gemspec:8: invalid multibyte char (US-ASCII)
Error Bundler::GemspecError, retrying 3/10
```

Once corrected, BOOM! it works:

```
root@elk-loyalguru:/opt# logstash/bin/plugin install --no-verify
Installing...
Installation successful
```

It has been really helpfull to know how the DEBUG mode works, do you think that this could be added to the documentation, the manual of the command and so on?

Thanks again!

**Comment by ph** [comment] 2015-04-08 14:19
I would guess your local setup is correctly setup for utf-8, maybe there is something different on your digitalocean box? locales maybe?

Concerning the DEBUG=1, We should definitively add it! Maybe we could add a --debug flag to the command? What do you think?

**Comment by javifr** [comment] 2015-04-08 14:40
I'm quite a beginner in terms of sys-adminstration, so I don't even know how to start looking for the locales... by the moment if changed the author from Fernández to Fernandez :)

And a --debug flag sounds NICE.
In fact, before posting my first issue here I tried things like ```--verbose``` and ```-d```. 

So :+1:  to a ```--debug```flag!

**Comment by javifr** [comment] 2015-04-08 14:54
(a bit out of this issue )

@ph where I could go for general questions related to logstash plugin creation?

For example now I'm facing a problem in which my plugin once installed, and logstash service started, it's stops with this error on ```/var/log/logstash/logstash.err```:

```
INFO: [logstash-elk-loyalguru-1442407170-18354] started
NotImplementedError: fstat unimplemented unsupported or native support failed to load
                size at org/jruby/RubyFile.java:1108
  rotate_events_log? at /opt/logstash-output-dropbox/lib/logstash/outputs/dropbox.rb:234
        handle_event at /opt/logstash-output-dropbox/lib/logstash/outputs/dropbox.rb:274
            register at /opt/logstash-output-dropbox/lib/logstash/outputs/dropbox.rb:161
                call at org/jruby/RubyProc.java:271
              encode at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-line-0.1.5/lib/logstash/codecs/line.rb:53
             receive at /opt/logstash-output-dropbox/lib/logstash/outputs/dropbox.rb:222
              handle at /opt/logstash/lib/logstash/outputs/base.rb:88
          initialize at (eval):231
                call at org/jruby/RubyProc.java:271
              output at /opt/logstash/lib/logstash/pipeline.rb:279
        outputworker at /opt/logstash/lib/logstash/pipeline.rb:235
       start_outputs at /opt/logstash/lib/logstash/pipeline.rb:163
```

**Comment by ph** [comment] 2015-04-08 14:55
You are at the right place but open a new issue with it

**Comment by ph** [comment] 2015-04-09 13:53
fixed in https://github.com/elastic/logstash/pull/2946

**Closed by ph** 2015-04-09 13:53 UTC
Labels: blocker, bundler
