### ISSUE TITLE
Make logstash to return an array when the same grok pattern matches multiple times

### ISSUE THREAD

**Issue by ArthurSens** [elastic/logstash#8898] opened 2017-12-29 10:48 UTC
Hello,

I've been looking for this in the [Logstash User Guide](https://www.elastic.co/guide/en/logstash/current/index.html) for a really long time and wasn't able to find anything that could help.
I've also opened a [thread at the discuss forum](https://discuss.elastic.co/t/help-needed-same-grok-pattern-multiple-matches/113318/2) recently and I haven't got any answer, so I'm just assuming it's not possible yet.

I will explain the idea with my problem as an example:

I'm having a difficult time to classify some JBOSS logs when it sends me java exceptions.

Here is a message example:
```
Throwable while attempting to get a new connection: null
org.jboss.resource.JBossResourceException: Could not create connection; - nested throwable: (com.microsoft.sqlserver.jdbc.SQLServerException: Cannot open database "database" requested by the login. The login failed.
```

Here is the filter I'm using:
```
filter {
  grok {
    match => { "message" => "\.(?<java_exception>([A-z]|[0-9])*Exception):(.|\r|\n)*" }
  }
}
```

What I get in return:
```
{
  "java_exception": "JBossResourceException"
}
```
But as you can see `SQLServerException` also is a valid match to this same grok pattern
I would like to get this as my filter result:

```
{
  "java_exception": ["JBossResourceException", "SQLServerException"]
}
```

**Comment by jsvd** [comment] 2017-12-29 11:13
closing as duplicate of https://github.com/logstash-plugins/logstash-filter-grok/issues/27
currently there is no way to do this. https://github.com/logstash-plugins/logstash-filter-grok/issues/35 contains the skeleton of a proposal

**Closed by jsvd** 2017-12-29 11:13 UTC

**Comment by micobarac** [comment] 2020-10-02 14:30
Why are the issues on this very same matter getting closed and nothing had been done to support this for years?
