### ISSUE TITLE
[7.6.0] Logstash no longer accepts completely commented pipeline conf files

### ISSUE THREAD

**Issue by xander33** [elastic/logstash#11598] opened 2020-02-12 18:47 UTC
There appears to be a breaking change from 7.5.2 => 7.6.0 in the way pipelines are read. Logstash appears to no longer accept a file that is completely commented out. Ex:

1-input.conf:
```
input {
  tcp {
    port => 1234
    codec => json
  }
}
```
2-filter.conf:
```
#filter {
#  ruby {
#    code => 'event.set( "test", "test_value" )'
#  }
#}
```
3-output.conf:
```
output {
  stdout { }
}
```
This will fail with this message:
```
[2020-02-12T18:26:58,059][ERROR][logstash.agent           ] Failed to execute action {:action=>LogStash::PipelineAction::Create/pipeline_id:main, :exception=>"LogStash::ConfigurationError", :message=>"Expected one of [ \\t\\r\\n], \"#\", \"input\", \"filter\", \"output\" at line 6, column 1 (byte 78) after #filter {\n#  ruby {\n#    code => 'event.set( \"test\", \"test_value\" )'\n#  }\n#}\n", :backtrace=>["/usr/share/logstash/logstash-core/lib/logstash/compiler.rb:47:in `compile_imperative'", "/usr/share/logstash/logstash-core/lib/logstash/compiler.rb:55:in `compile_graph'", "/usr/share/logstash/logstash-core/lib/logstash/compiler.rb:17:in `block in compile_sources'", "org/jruby/RubyArray.java:2580:in `map'", "/usr/share/logstash/logstash-core/lib/logstash/compiler.rb:14:in `compile_sources'", "org/logstash/execution/AbstractPipelineExt.java:161:in `initialize'", "org/logstash/execution/JavaBasePipelineExt.java:47:in `initialize'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:27:in `initialize'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline_action/create.rb:36:in `execute'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:326:in `block in converge_state'"]}
```
Editing the comments in 2-filter.conf to just enable an empty `filter { }` block will start successfully:
```
filter {
#  ruby {
#    code => 'event.set( "test", "test_value" )'
#  }
}
```
This was not the behavior in 7.5.2. A file could be completely commented out.

**Comment by faulkga** [comment] 2020-02-14 19:12
Any chance 2-filter.conf didn't have a newline as the last line of the file?

I suspect the issue is less that the entire file is commented out, and more that Logstash now seems to merge the files in such a way that if the last line of an intermediary .conf file begins with a hash mark instead of a newline that results in the first line of the next merged segment to be commented out, similar to if you cat the files together on the command line.

I encountered a similar issue with multiple configuration files. Logstash 7.6.0 wouldn't start without shutting down when trying to merge the .conf files until I either removed last line comments or added a new line after the comment. 

It seems this may be Logstash enforcing newlines as the last line in .conf files.

I suspect this would also fix your issue:
`#filter {
#  ruby {
#    code => 'event.set( "test", "test_value" )'
#  }
#}

`

**Comment by xander33** [comment] 2020-02-17 16:46
@faulkga Thanks for your response and good thought. But, yes the files definitely end with new line characters. I didn't have a blank line at the end of each, but even after adding some logstash still fails with the same message:
```
cat -A conf/*.conf
$
input {$
  tcp {$
    port => 1234$
    codec => json$
  }$
}$
$
$
#filter {$
#  ruby {$
#    code => 'event.set( "test", "test_value" )'$
#  }$
#}$
$
$
output {$
  stdout { }$
}$
$
```
When testing, I'd often comment out a whole filter block with sed. Not a big deal I guess, just don't have blank files in your pipeline.

**Comment by andsel** [comment] 2020-02-18 11:27
In version 7.6 and above we changed the way the sources composes the pipelines text (PR #11456). We switched from something "cat all files into a string" to "use each source segment with metadata", this opened Logstash to expose the source reference of each plugin into the monitoring HTTP API. I suspect that this change kicks in with that behaveiour.

**Comment by jsvd** [comment] 2020-02-20 11:30
with the change in 11456 we have exposed the fact that we expect a config file to have at least one pipeline section.

In fact, this is not necessary at all, we should be able to pass in a config file without sections and it would behave like an empty "filter {}" configuration:

```
> pp grammar.parse("filter {}").compile
{:input=>#<Java::OrgLogstashConfigIrImperative::NoopStatement:0x8c2bb88>,
 :filter=>#<Java::OrgLogstashConfigIrImperative::NoopStatement:0x683ba3c1>,
 :output=>#<Java::OrgLogstashConfigIrImperative::NoopStatement:0x79242162>}
```

So there's no reason to produce the same with empty strings or only comments.

we can slightly tweak the [config rule](https://github.com/elastic/logstash/blob/master/logstash-core/lib/logstash/compiler/lscl/lscl_grammar.treetop#L5-L7) to accept zero or more plugins, and alternatively just `_`, something like 

```diff
   rule config
-    _ plugin_section _ (_ plugin_section)* _ <LogStash::Compiler::LSCL::AST::Config>
+   (_ plugin_section)* _ <LogStash::Compiler::LSCL::AST::Config>
   end
```

This would allow us to delete the empty file reject clause, as those would still compile:

```
irb(main):005:0> grammar.parse("").compile
=> {:input=>#<Java::OrgLogstashConfigIrImperative::NoopStatement:0x5875480e>, :filter=>#<Java::OrgLogstashConfigIrImperative::NoopStatement:0x38b88037>, :output=>#<Java::OrgLogstashConfigIrImperative::NoopStatement:0x606b9417>}
irb(main):006:0> grammar.parse("# hey\n").compile
=> {:input=>#<Java::OrgLogstashConfigIrImperative::NoopStatement:0x6fc9f8bc>, :filter=>#<Java::OrgLogstashConfigIrImperative::NoopStatement:0x35d57a47>, :output=>#<Java::OrgLogstashConfigIrImperative::NoopStatement:0x319b7537>}
```

**Closed** 2020-02-27 09:43 UTC
