### ISSUE TITLE
How to send a reload signal to LS on windows?

### ISSUE THREAD

**Issue by githubmui** [elastic/logstash#5230] opened 2016-05-02 08:04 UTC
Hi,
I don't know how to send a SIGHUP to LS 2.3.1 on Windows 7. I need this signal mechanism, because the polling of the reload detect engine (every 5s) needs to much CPU power on windows (up to 5%).

Maybe it's possible to use the JRUBY filter plugin  to trigger the reload directly from JRuby code? 
Do you have a clue, if this is possible?
- Version: LS 2.3.1
- Operating System: Windows 7

Cheers.

**Comment by acchen97** [comment] 2016-05-13 18:02
@githubmui if the default reload poll is too frequent, did you try changing the reload interval with the `--reload-interval <seconds>` option?

https://www.elastic.co/guide/en/logstash/current/reloading-config.html

**Comment by zhammer** [comment] 2020-01-17 17:10
@githubmui from looking at the source it seems like there's not windows config reload signal
    # no point in enabling config reloading before the agent starts
    # also windows doesn't have SIGHUP. we can skip it
    sighup_id = LogStash::Environment.windows? ? nil : trap_sighup()

**Comment by andsel** [comment] 2020-01-20 14:11
This issue relates to very old Logstash version, and no interaction by the opener for long time. I close it, in any case if the problem is still persists in newer version of Logstash don't hesitate to open a new one.

**Closed by andsel** 2020-01-20 14:11 UTC
Labels: enhancement, windows

**Comment by zhammer** [comment] 2020-01-20 16:19
@andsel i agree it’s fair to close given time but the code snippet i posted is current and (as far as i can tell) shows there’s no config reload signal on windows. if intention is to leave it that way for now i’d be happy to update https://www.elastic.co/guide/en/logstash/current/reloading-config.html to say “config reloading is only supported on linux”
