### ISSUE TITLE
Pipeline has stopped when facing bad json

### ISSUE THREAD

**Issue by btungut** [elastic/logstash#8885] opened 2017-12-26 07:51 UTC
Hi,

We're using logstash 6.1 with kafka input and elasticsearch output. Our inputs (from kafka) are json serialized objects and all of them serialized from same object.

This serialized object I've mention above, contains one string field with name **Entity**. It contains json serialized object and there can be many types. 

We're getting from kafka and indexing to Elasticsearch 1,000,0000 messages per day. All of messages indexing successfully except one!

When a key-value pair field has string empty key, like that;
`\"SpecialFilters\":{\"\":[\"?\"],\"1057\":[\"33377\"]}`

Logstash worker process is failing with this log;
`[2017-12-21T20:44:24,101][ERROR][logstash.pipeline        ] worker, the pipeline stopped processing new events, please check your filter configuration and restart Logstash. {:pipeline_id=>"indexer", "exception"=>"-1", "backtrace"=>["java.util.ArrayList.elementData(ArrayList.java:422)", "java.util.ArrayList.remove(ArrayList.java:499)", "org.logstash.FieldReference.parse(FieldReference.java:159)", "org.logstash.FieldReference.parseToCache(FieldReference.java:146)", "org.logstash.FieldReference.from(FieldReference.java:78)", "org.logstash.ConvertedMap.convertKey(ConvertedMap.java:101)", "org.logstash.ConvertedMap.access$000(ConvertedMap.java:23)", "org.logstash.ConvertedMap$1.visit(ConvertedMap.java:34)", "org.logstash.ConvertedMap$1.visit(ConvertedMap.java:28)", "org.jruby.RubyHash.visitLimited(RubyHash.java:662)", "org.jruby.RubyHash.visitAll(RubyHash.java:647)", "org.logstash.ConvertedMap.newFromRubyHash(ConvertedMap.java:68)", "org.logstash.ConvertedMap.newFromRubyHash(ConvertedMap.java:63)", "org.logstash.Valuefier.lambda$initConverters$11(Valuefier.java:142)", "org.logstash.Valuefier.convert(Valuefier.java:73)", "org.logstash.ConvertedMap$1.visit(ConvertedMap.java:34)", "org.logstash.ConvertedMap$1.visit(ConvertedMap.java:28)", "org.jruby.RubyHash.visitLimited(RubyHash.java:662)", "org.jruby.RubyHash.visitAll(RubyHash.java:647)", "org.logstash.ConvertedMap.newFromRubyHash(ConvertedMap.java:68)", "org.logstash.ConvertedMap.newFromRubyHash(ConvertedMap.java:63)", "org.logstash.Valuefier.lambda$initConverters$11(Valuefier.java:142)", "org.logstash.Valuefier.convert(Valuefier.java:73)", "org.logstash.ConvertedMap$1.visit(ConvertedMap.java:34)", "org.logstash.ConvertedMap$1.visit(ConvertedMap.java:28)", "org.jruby.RubyHash.visitLimited(RubyHash.java:662)", "org.jruby.RubyHash.visitAll(RubyHash.java:647)", "org.logstash.ConvertedMap.newFromRubyHash(ConvertedMap.java:68)", "org.logstash.ConvertedMap.newFromRubyHash(ConvertedMap.java:63)", "org.logstash.Valuefier.lambda$initConverters$11(Valuefier.java:142)", "org.logstash.Valuefier.convert(Valuefier.java:73)", "org.logstash.ext.JrubyEventExtLibrary$RubyEvent.ruby_set_field(JrubyEventExtLibrary.java:95)", "usr.share.logstash.vendor.bundle.jruby.$2_dot_3_dot_0.gems.logstash_minus_filter_minus_json_minus_3_dot_0_dot_5.lib.logstash.filters.json.RUBY$method$filter$0(/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-filter-json-3.0.5/lib/logstash/filters/json.rb:86)", "usr.share.logstash.logstash_minus_core.lib.logstash.filters.base.RUBY$method$do_filter$0(/usr/share/logstash/logstash-core/lib/logstash/filters/base.rb:145)", "usr.share.logstash.logstash_minus_core.lib.logstash.filters.base.RUBY$block$multi_filter$1(/usr/share/logstash/logstash-core/lib/logstash/filters/base.rb:164)", "org.jruby.runtime.CompiledIRBlockBody.yieldDirect(CompiledIRBlockBody.java:156)", "org.jruby.runtime.BlockBody.yield(BlockBody.java:114)", "org.jruby.runtime.Block.yield(Block.java:165)", "org.jruby.RubyArray.each(RubyArray.java:1734)", "usr.share.logstash.logstash_minus_core.lib.logstash.filters.base.RUBY$method$multi_filter$0(/usr/share/logstash/logstash-core/lib/logstash/filters/base.rb:161)", "usr.share.logstash.logstash_minus_core.lib.logstash.filter_delegator.RUBY$method$multi_filter$0(/usr/share/logstash/logstash-core/lib/logstash/filter_delegator.rb:48)", "org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:103)", "org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:163)", "org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:200)", "org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:161)", "org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:314)", "org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)", "org.jruby.ir.interpreter.Interpreter.INTERPRET_BLOCK(Interpreter.java:132)", "org.jruby.runtime.MixedModeIRBlockBody.commonYieldPath(MixedModeIRBlockBody.java:148)", "org.jruby.runtime.IRBlockBody.doYield(IRBlockBody.java:186)", "org.jruby.runtime.BlockBody.yield(BlockBody.java:116)", "org.jruby.runtime.Block.yield(Block.java:165)", "org.jruby.RubyArray.each(RubyArray.java:1734)", "org.jruby.RubyArray$INVOKER$i$0$0$each.call(RubyArray$INVOKER$i$0$0$each.gen)", "org.jruby.internal.runtime.methods.JavaMethod$JavaMethodZeroBlock.call(JavaMethod.java:498)", "org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:77)", "org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:83)", "org.jruby.ir.instructions.CallBase.interpret(CallBase.java:428)", "org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:355)", "org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)", "org.jruby.ir.interpreter.Interpreter.INTERPRET_BLOCK(Interpreter.java:132)", "org.jruby.runtime.MixedModeIRBlockBody.commonYieldPath(MixedModeIRBlockBody.java:148)", "org.jruby.runtime.IRBlockBody.call(IRBlockBody.java:73)", "org.jruby.runtime.Block.call(Block.java:124)", "org.jruby.RubyProc.call(RubyProc.java:289)", "org.jruby.RubyProc.call19(RubyProc.java:273)", "org.jruby.RubyProc$INVOKER$i$0$0$call19.call(RubyProc$INVOKER$i$0$0$call19.gen)", "org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:204)", "org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:200)", "org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:161)", "org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:314)", "org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)", "org.jruby.ir.interpreter.Interpreter.INTERPRET_BLOCK(Interpreter.java:132)", "org.jruby.runtime.MixedModeIRBlockBody.commonYieldPath(MixedModeIRBlockBody.java:148)", "org.jruby.runtime.IRBlockBody.doYield(IRBlockBody.java:186)", "org.jruby.runtime.BlockBody.yield(BlockBody.java:116)", "org.jruby.runtime.Block.yield(Block.java:165)", "org.jruby.RubyArray.each(RubyArray.java:1734)", "org.jruby.RubyArray$INVOKER$i$0$0$each.call(RubyArray$INVOKER$i$0$0$each.gen)", "org.jruby.internal.runtime.methods.JavaMethod$JavaMethodZeroBlock.call(JavaMethod.java:498)", "org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:77)", "org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:83)", "org.jruby.ir.instructions.CallBase.interpret(CallBase.java:428)", "org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:355)", "org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)", "org.jruby.ir.interpreter.Interpreter.INTERPRET_BLOCK(Interpreter.java:132)", "org.jruby.runtime.MixedModeIRBlockBody.commonYieldPath(MixedModeIRBlockBody.java:148)", "org.jruby.runtime.IRBlockBody.call(IRBlockBody.java:73)", "org.jruby.runtime.Block.call(Block.java:124)", "org.jruby.RubyProc.call(RubyProc.java:289)", "org.jruby.RubyProc.call19(RubyProc.java:273)", "org.jruby.RubyProc$INVOKER$i$0$0$call19.call(RubyProc$INVOKER$i$0$0$call19.gen)", "org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:204)", "org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:200)", "org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:161)", "org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:314)", "org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)", "org.jruby.ir.interpreter.Interpreter.INTERPRET_BLOCK(Interpreter.java:132)", "org.jruby.runtime.MixedModeIRBlockBody.commonYieldPath(MixedModeIRBlockBody.java:148)", "org.jruby.runtime.IRBlockBody.call(IRBlockBody.java:73)", "org.jruby.runtime.Block.call(Block.java:124)", "org.jruby.RubyProc.call(RubyProc.java:289)", "org.jruby.internal.runtime.methods.ProcMethod.call(ProcMethod.java:63)", "org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:204)", "org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:200)", "usr.share.logstash.logstash_minus_core.lib.logstash.pipeline.RUBY$method$filter_batch$0(/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:455)", "org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:103)", "org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:163)", "org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:200)", "org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:161)", "org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:314)", "org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)", "org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:89)", "org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:214)", "org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:200)", "org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:208)", "org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:358)", "org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:195)", "org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:323)", "org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)", "org.jruby.ir.interpreter.Interpreter.INTERPRET_BLOCK(Interpreter.java:132)", "org.jruby.runtime.MixedModeIRBlockBody.commonYieldPath(MixedModeIRBlockBody.java:148)", "org.jruby.runtime.IRBlockBody.call(IRBlockBody.java:73)", "org.jruby.runtime.Block.call(Block.java:124)", "org.jruby.RubyProc.call(RubyProc.java:289)", "org.jruby.RubyProc.call(RubyProc.java:246)", "org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:104)", "java.lang.Thread.run(Thread.java:748)"], :thread=>"#<Thread:0x3cf0bfcf@/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:245 sleep>"}`

Our pipeline config;
filter {

    #BEGIN - This pipeline's messages is json serialized objects, deserialize that.
	json {
		source => "message"
		target => "object"
		tag_on_failure => [ "_jsonparsefailure_message_to_object" ]
	}
  
  ...SOME OTHER...
	
	#BEGIN - Parse Entity if exist and contains json char
	if [object][ExtraData][Entity] {
        mutate {
            rename  => { "[object][ExtraData][Entity]" => "[object][ExtraData][RawEntity]" }
        }
        
        if "{" in [object][ExtraData][RawEntity] and [object][ExtraData][RawEntity] != "" and [object][ExtraData][RawEntity] != "null" {
            json {
                source => "[object][ExtraData][RawEntity]"
                target => "[object][ExtraData][Entity]"
				skip_on_invalid_json => true
                tag_on_failure => [ "_jsonparsefailure_entity" ]
                remove_field => [ "[object][ExtraData][RawEntity]" ]
            }
        }
    }
	#END

}

**Comment by btungut** [comment] 2017-12-26 07:58
Same at https://github.com/elastic/logstash/issues/8882

**Comment by jordansissel** [comment] 2017-12-28 05:38
Duplicate of https://github.com/elastic/logstash/issues/8823

Fixed in https://github.com/elastic/logstash/pull/8824; first release with fix is Logstash 6.1.1

**Comment by btungut** [comment] 2017-12-28 07:28
@jordansissel we're already using 6.1.1 but still facing this problem.

**Comment by jordansissel** [comment] 2017-12-28 07:57
I have misread this issue, and I don't think this issue was addressed. The issue I linked (#8824) sounded related, but I don't know if it is. I commented on https://github.com/elastic/logstash/issues/8823 as a followup.

**Comment by TimothyZhang** [comment] 2018-01-22 02:29
+1. the same error.

**Comment by TimothyZhang** [comment] 2018-01-22 02:57
Is there a quick workaround for this issue before it been fixed? It's really critical because logstash totally not working.

**Comment by jsvd** [comment] 2018-01-22 11:39
@TimothyZhang this is fixed in 6.1.2

**Closed** 2018-01-22 11:42 UTC
