### ISSUE TITLE
Pipeline shutdown can be blocked by stdin input

### ISSUE THREAD

**Issue by jordansissel** [elastic/logstash#1769] opened 2014-09-23 15:54 UTC
For whatever reason, I can't figure out how to close stdin in JRuby and interrupt any currently-blocked reads on stdin.

This confuses users and is generally annoying.

The symptom is that ^C should terminate logstash cleanly, but stdin never really stops so the pipeline stays up until you close stdin as a user (via ^D)

(related: #1767)

**Comment by seanfahey** [comment] 2015-03-10 22:41
Is it possible to have the Getting Started documentation updated, until the issue is fixed? http://logstash.net/docs/1.4.2/tutorials/getting-started-with-logstash in the "Logstash in two commands" section.

**Comment by josegonzalez** [comment] 2015-03-11 14:34
Note: I'm unable to get it to close, even with CTRL+D. I have to manually kill the agent using `kill -term` or `kill -9`. I'm running under the openjre in case that helps.

**Comment by colinsurprenant** [comment] 2015-04-01 21:49
@josegonzalez for the shutdown + redis issue see #2871

**Comment by colinsurprenant** [comment] 2015-05-13 16:41
just a quick update to say I found a way to extract an `InterruptibleChannel` from `System.in` - I'll be making a test integration in the stdin input plugin which should allow a simple ^C to correctly shutdown logstash when using stdin input. 

I looks like this solution only works on Java 8 though.

**Comment by jordansissel** [comment] 2015-05-13 16:47
@colinsurprenant I'm OK with this - Java 7 is EOL anyway, so I think it's reasonable to expect that Java 8 should become more common very soon.

**Comment by jordansissel** [comment] 2015-05-13 16:47
<3 you so much for finding this solution

**Comment by josegonzalez** [comment] 2015-05-14 15:54
Yay java 8!

**Comment by colinsurprenant** [comment] 2015-05-15 23:29
landed the [jruby-stdin-channel](https://github.com/colinsurprenant/jruby-stdin-channel) gem for it. just need to insert that into the stdin input and see how that behave :P

**Comment by colinsurprenant** [comment] 2015-05-17 00:29
inserted in the stdin input in logstash-plugins/logstash-input-stdin#3

**Comment by jsvd** [comment] 2016-03-11 16:35
please follow this in https://github.com/logstash-plugins/logstash-input-stdin/pull/3

**Closed by jsvd** 2016-03-11 16:35 UTC
Labels: enhancement, v5.0.0
