### ISSUE TITLE
Investigate lingering docker containers in integration tests

### ISSUE THREAD

**Issue by robbavey** [elastic/logstash#8676] opened 2017-11-15 01:45 UTC
Recent test failures that were occurring due to out of memory issues on the build boxes, appear to be down to lingering docker containers (https://github.com/elastic/infra/issues/3109), possibly after test failures.

**Comment by original-brownbear** [comment] 2017-11-15 09:23
@robbavey hmm it doesn't look like we're actually leaving any containers around, both of our `docker run` invocations (unit- and integration-tests) use the `--rm` flag.

Maybe the issue is further of the stack in terms of how Jenkins is configured (I'm thinking about what happens when a build is killed because of another push to a PR while one is running already for example)?

**Comment by elasticdog** [comment] 2017-11-15 15:16
Yes, I believe that scenario, or a manual build abort, or simply an unexpected failure in the middle of a run would all leave lingering containers. Most of the build scripts in our other projects [explicitly trap all exit signals](https://github.com/elastic/beats/blob/408af589f814ef378d6aa469660ebc813026cf24/dev-tools/jenkins_ci.sh#L19-L30) and attempt to cleanup things in those cases. Since Jenkins isn't managing anything beyond which build script is called, it has no knowledge of what to do and relies on the script itself keeping the environment clean.

**Comment by original-brownbear** [comment] 2018-01-16 16:37
I think I fixed this in #8953 , closing here we can reopen if this remains a problem.

**Closed by original-brownbear** 2018-01-16 16:37 UTC
Labels: test failure, tests-infra
