### ISSUE TITLE
Logstash Ignores Stanzas with One-item Arrays

### ISSUE THREAD

**Issue by RyanFrantz** [elastic/logstash#2737] opened 2015-03-02 21:49 UTC
When updating my Logstash config, I tried specifying a one-item array when checking the event type:

    if [type] in ["nginx_access_log"] {

Unfortunately, while I saw events in Elasticsearch (my current target), they didn't include the parsed fields I expected. It wasn't until I update the statement to be an equality match that Logstash started parsing the events:

    if [type] == "nginx_access_log" {

We're running Logstash 1.4.1.

**Comment by jordansissel** [comment] 2015-03-02 21:51
I think we fixed this for 1.5. The problem was something around `["nginx_access_log"]` being considered as a field reference and not a one-item array.

**Comment by wiibaa** [comment] 2015-03-10 09:24
Reproduced with 1.5.0RC2, PR #1361 and linked issues are still open,

**Comment by jordansissel** [comment] 2016-03-09 00:38
There are other issues reporting this as well. I'm not sure we've fixed it.

A possible workaround is to make your array have a bogus 2nd item in it:

```
if [type] in ["nginx", "WHOA SOMETHING I WILL NEVER SEE"] {
  ...
}
```

**Comment by jsvd** [comment] 2016-03-11 16:47
@jordansissel this is a dup of https://github.com/elastic/logstash/issues/1850, from what I see. closing this

**Closed by jsvd** 2016-03-11 16:47 UTC
