### ISSUE TITLE
if Conditional around input filter doesn’t appear to be working

### ISSUE THREAD

**Issue by sjivan** [elastic/logstash#6263] opened 2016-11-16 10:26 UTC
I'm trying to setup conditional file input sources based on an environment variable and it was reading the file even when the condition was false.

To simplify the test I setup

    input {
         if 1 == 2 {
                file {
                      path => ...
                }
         }
    }

Logstash picks up the file source despite the false condition. 

Using LS 5.0

See https://discuss.elastic.co/t/if-conditional-around-input-filter-doesnt-appear-to-be-working/66166

**Comment by jsvd** [comment] 2016-11-16 10:40
this is a known issue, conditionals shouldn't even be supported in the input section, since the only use case would be using environment variable interpolation, which I believe we also don't support in the inputs.

closing as duplicate of https://github.com/elastic/logstash/issues/6080

**Closed by jsvd** 2016-11-16 10:40 UTC
