### ISSUE TITLE
NullPointerException in EventCondition$Compiler.compare

### ISSUE THREAD

**Issue by gquintana** [elastic/logstash#10706] opened 2019-04-23 10:25 UTC
This issue is very similar to #9843 except it's not on equality but on comparison.

I suspect that under some unexpected circumstances, at https://github.com/elastic/logstash/blob/master/logstash-core/src/main/java/org/logstash/config/ir/compiler/EventCondition.java#L415 ,  `left` may be null.

```
[2019-04-15T15:33:03,818][ERROR][org.logstash.execution.WorkerLoop] Exception in pipelineworker, the pipeline stopped processing new events, please check your filter configuration and restart Logstash.
java.lang.NullPointerException: null
	at org.logstash.config.ir.compiler.EventCondition$Compiler$UnexpectedTypeException.<init>(EventCondition.java:616) ~[logstash-core.jar:?]
	at org.logstash.config.ir.compiler.EventCondition$Compiler.compare(EventCondition.java:418) ~[logstash-core.jar:?]
	at org.logstash.config.ir.compiler.EventCondition$Compiler.lambda$compareFieldToConstant$11(EventCondition.java:409) ~[logstash-core.jar:?]
	at org.logstash.config.ir.compiler.Utils.filterEvents(Utils.java:25) ~[logstash-core.jar:?]
	at org.logstash.generated.CompiledDataset3.compute(Unknown Source) ~[?:?]
	at org.logstash.generated.CompiledDataset4.compute(Unknown Source) ~[?:?]
	at org.logstash.generated.CompiledDataset458.compute(Unknown Source) ~[?:?]
	at org.logstash.generated.CompiledDataset459.compute(Unknown Source) ~[?:?]
	at org.logstash.generated.CompiledDataset460.compute(Unknown Source) ~[?:?]
	at org.logstash.generated.CompiledDataset461.compute(Unknown Source) ~[?:?]
	at org.logstash.generated.CompiledDataset462.compute(Unknown Source) ~[?:?]
	at org.logstash.generated.CompiledDataset463.compute(Unknown Source) ~[?:?]
	at org.logstash.generated.CompiledDataset464.compute(Unknown Source) ~[?:?]
	at org.logstash.generated.CompiledDataset465.compute(Unknown Source) ~[?:?]
	at org.logstash.config.ir.compiler.DatasetCompiler$Complement.compute(DatasetCompiler.java:379) ~[logstash-core.jar:?]
	at org.logstash.generated.CompiledDataset21.compute(Unknown Source) ~[?:?]
	at org.logstash.generated.CompiledDataset466.compute(Unknown Source) ~[?:?]
	at org.logstash.generated.CompiledDataset467.compute(Unknown Source) ~[?:?]
	at org.logstash.generated.CompiledDataset470.compute(Unknown Source) ~[?:?]
	at org.logstash.generated.CompiledDataset471.compute(Unknown Source) ~[?:?]
	at org.logstash.generated.CompiledDataset472.compute(Unknown Source) ~[?:?]
	at org.logstash.generated.CompiledDataset473.compute(Unknown Source) ~[?:?]
	at org.logstash.generated.CompiledDataset474.compute(Unknown Source) ~[?:?]
	at org.logstash.generated.CompiledDataset475.compute(Unknown Source) ~[?:?]
	at org.logstash.generated.CompiledDataset476.compute(Unknown Source) ~[?:?]
	at org.logstash.generated.CompiledDataset477.compute(Unknown Source) ~[?:?]
	at org.logstash.generated.CompiledDataset478.compute(Unknown Source) ~[?:?]
	at org.logstash.generated.CompiledDataset481.compute(Unknown Source) ~[?:?]
	at org.logstash.generated.CompiledDataset482.compute(Unknown Source) ~[?:?]
	at org.logstash.generated.CompiledDataset485.compute(Unknown Source) ~[?:?]
	at org.logstash.execution.WorkerLoop.run(WorkerLoop.java:64) [logstash-core.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_202]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_202]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_202]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_202]
	at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(JavaMethod.java:438) [jruby-complete-9.1.13.0.jar:?]
	at org.jruby.javasupport.JavaMethod.invokeDirect(JavaMethod.java:302) [jruby-complete-9.1.13.0.jar:?]
	at org.jruby.java.invokers.InstanceMethodInvoker.call(InstanceMethodInvoker.java:36) [jruby-complete-9.1.13.0.jar:?]
	at appli.projects.sup.supervision.logstash.logstash_minus_6_dot_6_dot_1.logstash_minus_core.lib.logstash.java_pipeline.RUBY$block$start_workers$2(/appli/projects/sup/supervision/logstash/logstash-6.6.1/logstash-core/lib/logstash/java_pipeline.rb:238) [jruby-complete-9.1.13.0.jar:?]
	at org.jruby.runtime.CompiledIRBlockBody.callDirect(CompiledIRBlockBody.java:145) [jruby-complete-9.1.13.0.jar:?]
	at org.jruby.runtime.IRBlockBody.call(IRBlockBody.java:71) [jruby-complete-9.1.13.0.jar:?]
	at org.jruby.runtime.Block.call(Block.java:124) [jruby-complete-9.1.13.0.jar:?]
	at org.jruby.RubyProc.call(RubyProc.java:289) [jruby-complete-9.1.13.0.jar:?]
	at org.jruby.RubyProc.call(RubyProc.java:246) [jruby-complete-9.1.13.0.jar:?]
	at org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:104) [jruby-complete-9.1.13.0.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
```

- Version: 6.6.1
- Operating System: RHEL7
- Config File (if you have sensitive info, please remove it): it may be related to this filter, when `errornumber` is null or undefined
```
      if [errornumber] < 0 {
        mutate {
          add_field => {
            "level" => "error"
          }
        }
      }
```
- Steps to Reproduce: Not able to reproduce it yet

**Comment by danhermann** [comment] 2019-04-25 14:49
@gquintana, thanks for reporting this and identifying the root cause. This same thing occurs in the Ruby execution engine and per https://github.com/elastic/logstash/issues/5547, we would like to add a flag that would allow users to suppress the error and log a warning, but we have not yet implemented that.

**Comment by gquintana** [comment] 2019-05-09 13:31
The PR #10712 shows how to reproduce the problem.

Detail of the problem

1. A filter with `if [foo] > 12`
2. Send an event where [foo] is null or undefined
3. The `EventCondition.compare` method tries to throw an `UnexpectedTypeException`
4. The `UnexpectedTypeException` raises a NullPointerException
5. The NullPointerException kills the worker thread and the whole pipeline.

Workaround: *Always* test nullity before comparison, replace all `if [foo] > 12` by `if [foo] and [foo] > 12`

The problem seems related to using the Java execution engine (default in LS 6.7+).

**Comment by jsvd** [comment] 2019-06-19 21:10
As @danhermann mentioned this has always been an issue, even with the ruby execution:

```
/tmp/logstash-6.6.0 % bin/logstash -e "filter { if [fee] > 0 { } }"
Sending Logstash logs to /tmp/logstash-6.6.0/logs which is now configured via log4j2.properties
[2019-06-19T21:43:41,800][WARN ][logstash.config.source.multilocal] Ignoring the 'pipelines.yml' file because modules or command line options are specified
[2019-06-19T21:43:41,822][INFO ][logstash.runner          ] Starting Logstash {"logstash.version"=>"6.6.0"}
[2019-06-19T21:43:48,658][INFO ][logstash.pipeline        ] Starting pipeline {:pipeline_id=>"main", "pipeline.workers"=>8, "pipeline.batch.size"=>125, "pipeline.batch.delay"=>50}
[2019-06-19T21:43:48,771][INFO ][logstash.pipeline        ] Pipeline started successfully {:pipeline_id=>"main", :thread=>"#<Thread:0x3dbf5201 run>"}
The stdin plugin is now waiting for input:
[2019-06-19T21:43:48,808][INFO ][logstash.agent           ] Pipelines running {:count=>1, :running_pipelines=>[:main], :non_running_pipelines=>[]}
[2019-06-19T21:43:49,049][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
hello
[2019-06-19T21:43:50,901][ERROR][logstash.pipeline        ] Exception in pipelineworker, the pipeline stopped processing new events, please check your filter configuration and restart Logstash. {:pipeline_id=>"main", "exception"=>"undefined method `>' for nil:NilClass", "backtrace"=>["(eval):35:in `block in initialize'", "org/jruby/RubyArray.java:1734:in `each'", "(eval):33:in `block in initialize'", "(eval):20:in `block in filter_func'", "/tmp/logstash-6.6.0/logstash-core/lib/logstash/pipeline.rb:341:in `filter_batch'", "/tmp/logstash-6.6.0/logstash-core/lib/logstash/pipeline.rb:320:in `worker_loop'", "/tmp/logstash-6.6.0/logstash-core/lib/logstash/pipeline.rb:287:in `block in start_workers'"], :thread=>"#<Thread:0x3dbf5201 sleep>"}
[2019-06-19T21:43:50,973][FATAL][logstash.runner          ] An unexpected error occurred! {:error=>#<NoMethodError: undefined method `>' for nil:NilClass>, :backtrace=>["(eval):35:in `block in initialize'", "org/jruby/RubyArray.java:1734:in `each'", "(eval):33:in `block in initialize'", "(eval):20:in `block in filter_func'", "/tmp/logstash-6.6.0/logstash-core/lib/logstash/pipeline.rb:341:in `filter_batch'", "/tmp/logstash-6.6.0/logstash-core/lib/logstash/pipeline.rb:320:in `worker_loop'", "/tmp/logstash-6.6.0/logstash-core/lib/logstash/pipeline.rb:287:in `block in start_workers'"]}
[2019-06-19T21:43:51,018][ERROR][org.logstash.Logstash    ] java.lang.IllegalStateException: Logstash stopped processing because of an error: (SystemExit) exit
/tmp/logstash-6.6.0 %
```

In a situation like this we can't evaluate the conditional to neither true nor false. We could log and drop the event but it's not currently possible to distinguish between a rare "poison message" and a change in the data source that would cause all data to be discarded and logged to disk.

One thing we could do is tag these events with a `_error` tag and find a way to skip the whole conditional block. This way these failed events could still be salvaged by a conditional like `output { if "_error" in [tags] { file { path => /tmp/errors.log } }` - unless the broken conditional happens in the output section..

At the end of the day the best solution will be to write these events to the DLQ if it's enabled. We're working on improving the user experience with the DLQ so we rely more on it for situations like this.

**Comment by colinsurprenant** [comment] 2020-05-22 14:52
Closing and rebooting this issue in #11917

**Closed by colinsurprenant** 2020-05-22 14:52 UTC
