### ISSUE TITLE
Proposal: Weekly "tree-age" party

### ISSUE THREAD

**Issue by jordansissel** [elastic/logstash#2357] opened 2015-01-14 22:15 UTC
Ahem.. a "tree-age" (pronounced "triage", hehe)

We've been discussing internally among Logstashers at Elasticsearch various ways to improve our transparency and involvement with the community. One topic that came up strongly was to do a public triage-and-fix session, possibly weekly, which would involve the community directly with us (elasticsearch logstash folks) to help move logstash forward and discuss improvements, bugs, etc.

@tbragin, @robynbergeron, myself, and @suyog were present in the internal discussion. 
Summarizing this discussion, a rough sketch of this proposal follows:

---

Once weekly, hold a public event on #logstash IRC channel where we discuss bugs, solicit feedback, , review patches, etc. The goal is to allow a predictable time and space for discussing things.

The result of each triage session will be summarized and emailed to the logstash-users@ mailing list.

---

Some implementation concerns:
* We'll want to be aware of timezone availability and probably will shift the meeting time around to allow different folks to participate.
* In preparation, we'll internally prepare some kind of agenda for issues and PRs that need further study or review.
* Rough idea is to spend 1-2 hours each week doing this specific triage event.

**Comment by jordansissel** [comment] 2015-01-14 22:17
<3 to @untergeek for the "tree-age" punniness.

**Comment by untergeek** [comment] 2015-01-14 22:19
I **love** this idea!  Where do I sign up?

**Comment by kurtado** [comment] 2015-01-14 22:35
![triaging](https://cloud.githubusercontent.com/assets/1161427/5749109/81e31572-9bfa-11e4-94b3-8c9657c62edd.jpg)

**Comment by robynbergeron** [comment] 2015-01-14 22:51
@untergeek I don't know if we'd need a place to sign up; I think it could just be something where, if you can, you show up :)

Alternately - perhaps there could be a way to post an agenda as an issue, and people could say whether or not they're coming. (This seems like a not-fabulous idea to me, but throwing it out there anyway! The plus side of this is that people who are unable to attend might be able to at least comment on the agenda or etc. if they need to.)

**Comment by robynbergeron** [comment] 2015-01-14 22:58
For the record, I also <3 this idea. :) I think one thing to think about (and @jordansissel & @suyograo,  correct me if I'm off track here) - is that at least initially we may want to focus on one area per meeting. But over time - especially as some "back-log" (heh heh) gets better - I think it's definitely something that could have a regular, consistent agenda with time to address all the areas Jordan mentioned above. 

Does the bot in the #logstash channel have the meetbot plugin? It's a great way to record all the details and also capture the high-level topics, decisions made, etc. from IRC into something organized and readable, and is also saved as a webpage.

**Comment by ph** [comment] 2015-01-14 23:05
Awesome! count me in!

**Comment by jordansissel** [comment] 2015-01-14 23:36
![81e31572-9bfa-11e4-94b3-8c9657c62edd](https://cloud.githubusercontent.com/assets/131818/5749979/261973ae-9c03-11e4-9359-c6fa16952de1.jpg)

**Comment by tbragin** [comment] 2015-01-15 00:42
While we're going through a large backlog (like now), I like the idea of picking an area for each triage session (e.g. a specific plugin or category of concerns where a lot of requests / issues need attention). I think it will allow us to focus our efforts, but will also result in measurable improvement in areas where most pain is felt. 

Also, part of the plan we discussed is to triage not only in Github, but also in the deprecated, but searcheable [public JIRA](https://logstash.jira.com/browse/LOGSTASH-2287?jql=project%20%3D%20LOGSTASH%20AND%20status%20in%20(Open%2C%20%22In%20Progress%22%2C%20Reopened%2C%20New%2C%20Confirmed%2C%20%22Need%20Information%22%2C%20Answered)) and start closing those issues or moving them over, if they are still valid. I had a couple of users ask me about public JIRA, since they found useful content there via Googling, without realizing that it's no longer maintained :(

I'd love to hear thoughts on what topics / areas might benefit from triage most immediately.

**Comment by purbon** [comment] 2015-01-16 15:46
love the idea, count me in!

**Comment by colinsurprenant** [comment] 2015-01-21 19:54
Yes!! +1

**Comment by jsvd** [comment] 2015-01-23 11:36
A tree-age test run will happen in a couple of hours (14:00 CEST) in the #logstash freenode channel. I'll go through some very old issues and we'll decide a course of action for each.

**Comment by suyograo** [comment] 2015-01-24 00:09
Tree-age update at the end of 23 Jan 2015: 

Today's theme was to start with the oldest open issues and pull requests. Most of the core developers were hanging out in the #logstash IRC channel too

Results from today:
1. We closed 54 issues and updated/triaged about 55 issues. See [list](https://github.com/elasticsearch/logstash/issues?q=is%3Aissue+sort%3Aupdated-desc+updated%3A%3E2015-01-23+is%3Aopen) of issues
2. Closed/migrated [24 pull requests](https://github.com/elasticsearch/logstash/pulls?q=sort%3Aupdated-desc+updated%3A%3E2015-01-23+is%3Apr+is%3Aclosed) 


![screen shot 2015-01-23 at 16 05 15](https://cloud.githubusercontent.com/assets/1595958/5884989/ffc39ba8-a319-11e4-83a2-e9bcb1484309.png)

Until next week!

**Comment by purbon** [comment] 2015-01-26 09:01
This is very nice, we should iterating this! I really enjoyed the experience!!

**Comment by suyograo** [comment] 2015-02-07 01:15
this week's theme were triaging issues from the old Logstash [JIRA](logstash.jira.com) system. 

At close today, we've resolved 157 issues in JIRA, migrated 30 issues to plugins repo and 10 issues to Logstash core

**Comment by suyograo** [comment] 2015-08-07 22:13
Closing this, we'll open new themes for fix-it-friday

**Closed by suyograo** 2015-08-07 22:13 UTC
