### ISSUE TITLE
Logstash 2.3 failed if run with auto-reload option

### ISSUE THREAD

**Issue by qk4l** [elastic/logstash#4969] opened 2016-04-01 10:04 UTC
Hello,

My Logstash instances fall down if they was run with `-r` or `auto-reload` option.

```
NoMethodError: undefined method `multi_filter' for nil:NilClass
  cond_func_533 at (eval):10162
           each at org/jruby/RubyArray.java:1613
  cond_func_533 at (eval):10159
    filter_func at (eval):1646
   filter_batch at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.0-java/lib/logstash/pipeline.rb:271
           each at org/jruby/RubyArray.java:1613
         inject at org/jruby/RubyEnumerable.java:852
   filter_batch at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.0-java/lib/logstash/pipeline.rb:269
    worker_loop at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.0-java/lib/logstash/pipeline.rb:227
  start_workers at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.0-java/lib/logstash/pipeline.rb:205
```
Here is my shrinked config:
```
/etc/logstash/conf.d# ls -1
001-input.conf
011-apache.conf
100-output.conf
# cat ./*
 
input {
  beats {
    port => 5003
    tags => beats
    ssl => true
    ssl_certificate => '/etc/certs/example.com/example.cer'
    ssl_key => '/etc/certs/example.com/example.key'
  }
}

filter {
  if [type] == "apache" {
    grok {
      match => { "message" => "%{COMMONAPACHELOG} %{NUMBER:response_time}" }
      break_on_match  => true
      match => { "message" => "%{COMMONAPACHELOG}" }
    }
  }
}
output {
    elasticsearch {
        hosts => ['localhost:9201', 'example2.com:9201']
        document_type => "%{[@metadata][type]}"
        index => "logstash-%{[@metadata][beat]}-%{+YYYY.MM.dd}"
    }
}
```

**Comment by jsvd** [comment] 2016-04-01 10:20
thanks for reporting, but I'm going to close as a duplicate of https://github.com/elastic/logstash/issues/4968, please track the issue there

**Closed by jsvd** 2016-04-01 10:20 UTC
