### ISSUE TITLE
Pass --log "FILE" make logstash quit without notice.

### ISSUE THREAD

**Issue by purbon** [elastic/logstash#4615] opened 2016-02-02 15:22 UTC
If running logstash in master with,

* ```./bin/logstash -f ../dummy.conf --log foo.bar --debug ``` 

or

* ```./bin/logstash -f ../dummy-metrics.conf --log foo.bar ``

it created the file ```foo.bar```, but logstash quits without any notice.

config is easy as:

```
input {
  generator {
    count => 0
  }
}

output {
  stdout { codec => rubydebug }
}
```

this means no logs could be generated for debug.

**Comment by ph** [comment] 2016-02-02 15:26
it work in 2.2.0 tar.gz release.

~/logstash-2.2.0 ❯❯❯ cat foo.bar
{:timestamp=>"2016-02-02T10:25:48.550000-0500", :message=>"Error: No config files found: /Users/ph/test.conf\nCan you make sure this path is a logstash config file?"}
{:timestamp=>"2016-02-02T10:25:48.565000-0500", :message=>"You may be interested in the '--configtest' flag which you can\nuse to validate logstash's configuration before you choose\nto restart a running system."}

**Comment by ph** [comment] 2016-02-02 15:27
work in 2.1.1 confirmed by @jsvd

**Comment by purbon** [comment] 2016-02-02 15:27
@colinsurprenant any idea why this might happen?

**Comment by jsvd** [comment] 2016-02-02 16:00
this is due to cabin still being stuck on 0.7.0, and should be 0.8.x, after bumping in gemfile we get:

```
% ./bin/logstash -f config --log ./log --debug
Sending logstash logs to ./log.
Error: No config files found: /private/tmp/logstash/config
Can you make sure this path is a logstash config file? {:level=>:fatal, :file=>"logstash/runner.rb", :line=>"162", :method=>"execute"}
usage:
  bin/logstash -f CONFIG_FILE [-t] [--quiet|verbose|debug] [-w COUNT] [-l LOG]
  bin/logstash -e CONFIG_STR [-t] [--quiet|verbose|debug] [-w COUNT] [-l LOG]
  bin/logstash -i SHELL [--quiet|verbose|debug]
  bin/logstash -V [--verbose|debug]
  bin/logstash --help
```

**Comment by colinsurprenant** [comment] 2016-02-02 16:51
:thumbsup:

**Comment by jsvd** [comment] 2016-02-02 17:26
fixed in https://github.com/elastic/logstash/pull/4616

**Closed by jsvd** 2016-02-02 17:26 UTC
Labels: bug, v2.3.0
