### ISSUE TITLE
Restarting beat, breaks logstash

### ISSUE THREAD

**Issue by PersonaN0nGrata** [elastic/logstash#11709] opened 2020-03-20 16:16 UTC
- Version: 7.96.1
- Operating System: UBUNTU 18.04
- Config File (if you have sensitive info, please remove it):
![image](https://user-images.githubusercontent.com/54578187/77183195-3dbfab00-6ace-11ea-9fd5-2dff98a6f034.png)

- Sample Data:
![image](https://user-images.githubusercontent.com/54578187/77183239-562fc580-6ace-11ea-842d-97a6db0a04eb.png)

- Steps to Reproduce: I have the ELK stack running on 1 device, with no data coming through to kibana. when i restart winlogbeat, on another device, it breaks logstash, which never recovers.
It worked last friday, and then it broke over the weekend.

Doesnt look like its really listening on the correct port on ipv4?
![image](https://user-images.githubusercontent.com/54578187/77316589-fb82ad80-6d09-11ea-8eb2-34ed3aee027a.png)

Says it connects to Elasticsearch though
![image](https://user-images.githubusercontent.com/54578187/77316638-135a3180-6d0a-11ea-99f5-05d490874964.png)

But i am unable to see data on kibana

**Comment by praseodym** [comment] 2020-03-27 11:26
This is a duplicate of https://github.com/logstash-plugins/logstash-input-beats/issues/348

**Closed** 2021-12-30 07:59 UTC
