### ISSUE TITLE
logstash with ES cluster error

### ISSUE THREAD

**Issue by liyin37** [elastic/logstash#13142] opened 2021-08-17 14:37 UTC
logstash version:  docker.elastic.co/logstash/logstash:7.13.2
elasticsearch version: 6.8.13  build images from https://github.com/jigante/dockerfiles/tree/main/elasticsearch-alpine/6.8，I use the none oss VERSION

when I run  the logstash with the logstash.yml:
```
input {
    redis {
      host => "${REDIS_HOST:redis}"
          port => "${REDIS_PORT:6379}"
          password => "${REDIS_PASSWORD:xxxxxxx}"
      db => "${REDIS_DB:2}"
      key => "geo-server-log"
      data_type => "list"
          type => "geo-server-log"
    }
    
    redis {
      host => "${REDIS_HOST:redis}"
          port => "${REDIS_PORT:6379}"
          password => "${REDIS_PASSWORD:xxxxxxx}"
      db => "${REDIS_DB:2}"
      key => "arcgis-system-log"
      data_type => "list"
          type => "arcgis-system-log"
    }
    
    redis {
        host => "${REDIS_HOST:redis}"
            port => "${REDIS_PORT:6379}"
            password => "${REDIS_PASSWORD:xxxxxxx}"
        db => "${REDIS_DB:2}"
        key => "geoscene-system-log"
        data_type => "list"
            type => "geoscene-system-log"
    }

    redis {
      host => "${REDIS_HOST:redis}"
          port => "${REDIS_PORT:6379}"
          password => "${REDIS_PASSWORD:xxxxxxx}"
      db => "${REDIS_DB:2}"
      key => "geoscene-server-log"
      data_type => "list"
          type => "geoscene-server-log"
    }
}

filter {
    if[type] == "geo-server-log"{
            mutate {
                  split => ["message"," - "]
            }
            
            if [message][0]{
                  mutate {
                          add_field => {
                                  "splitMessage" => "%{[message][0]}"
                          }
                  }
            }
            
            if [message][1]{
                  mutate {
                          add_field => {
                                  "content" => "%{[message][1]}"
                          }
                  }
            }  

            grok {
                  match => { "splitMessage" => "%{TIMESTAMP_ISO8601:logTime} %{LOGLEVEL:level} %{NOTSPACE:source}"}
            }
            
            #正则切出来的数据为字符串，要转化为日期型，不然ES范围查询有问题
            date {
                  match => ["logTime", "ISO8601"]
                  target => "logTime"
            }
            
            mutate {
                  remove_field => ["splitMessage"]
            } 
    }
    
    if[type] == "arcgis-system-log"{
          xml{
                  remove_namespaces=>"true"
          source => "message"
          target =>"doc"
                  xpath => [
                          "/Msg/@time","logTime_temp",
                          "/Msg/text()","content_temp",
                          "/Msg/@type","level_temp"
                  ]
          }
    
          mutate {
                  add_field => {"source" => "arcgis-system-log"}
          } 

    
        if([logTime_temp][0]){
              date{
                      match => ["[logTime_temp][0]", "ISO8601"]
                      target => "logTime"
              }
              mutate {
                      #add_field => {"logTime" => "%{[logTime_temp][0]}"}
                      remove_field => ["logTime_temp"]
              }

        }
        
        if([content_temp][0]){
              mutate {
                      add_field => {"content" => "%{[content_temp][0]}"}
                      remove_field => ["content_temp"]
              }
        }
        
        if([level_temp][0]){
              mutate {
                      add_field => {"level" => "%{[level_temp][0]}"}
                      remove_field => ["level_temp"]
              }
        }
        
        if([source_temp][0]){
              mutate {
                      add_field => {"source" => "%{[source_temp][0]}"}
                      remove_field => ["source_temp"]
              }
        }
    }
    
    if[type] == "arcgis-server-log"{
          xml{
                  remove_namespaces=>"true"
          source => "message"
          target =>"doc"
                  xpath => [
                          "/Msg/@time","logTime_temp",
                          "/Msg/text()","content_temp",
                          "/Msg/@type","level_temp",
                          "/Msg/@target","source_temp"
                  ]
          }

        
        if([logTime_temp][0]){
              date{
                      match => ["[logTime_temp][0]", "ISO8601"]
                      target => "logTime"
              }
              mutate {
                      #add_field => {"logTime" => "%{[logTime_temp][0]}"}
                      remove_field => ["logTime_temp"]
              }

        }
        
        if([content_temp][0]){
              mutate {
                      add_field => {"content" => "%{[content_temp][0]}"}
                      remove_field => ["content_temp"]
              }
        }
        
        if([level_temp][0]){
              mutate {
                      add_field => {"level" => "%{[level_temp][0]}"}
                      remove_field => ["level_temp"]
              }
        }
        
        if([source_temp][0]){
              mutate {
                      add_field => {"source" => "%{[source_temp][0]}"}
                      remove_field => ["source_temp"]
              }
        }
    }

    if[type] == "geoscene-server-log"{
      grok {
        match =>{"message" => "(?%{YEAR}-%{MONTHNUM}-%{MONTHDAY}[T ]%{HOUR}:?%{MINUTE}(?::?%{SECOND}))(?\.\d{6}) %{HOSTNAME:host} %{LOGLEVEL:level} %{IPORHOST:clientip} <*%{WORD:user}>* (?(%{WORD}|\?)) %{URIPATHPARAM:requestUrl} (?([A-Za-z]([A-Za-z0-9+\-./]+)+|\?)) %{JAVACLASS:class} %{WORD:method} %{NUMBER:responseCode} %{NUMBER:responseTime} %{GREEDYDATA:responseBody}"}     
       }
      
      date{
           match => ["logTime", "ISO8601"]
           target => "logTime"
      }

      mutate {
          add_field => {"content" => "%{message}"}
      }
      
    }

    if[type] == "geoscene-system-log"{
      grok {
          match => {"message" => "%{TIMESTAMP_ISO8601:logTime} \[%{WORD:main}\] \[%{JAVACLASS:class}\] %{LOGLEVEL:level} %{GREEDYDATA:responseBody}"}
      }
      date{
           match => ["logTime", "ISO8601"]
           target => "logTime"
      }

      mutate {
          add_field => {"content" => "%{message}"}
      }
    }
    
    mutate {
          add_field => {"saveTime" => "%{@timestamp}"}
          add_field => {"hostName" => "%{[host][name]}"}
          add_field => {"catalog" => "%{[type]}"}
    } 
    
}
output {
  elasticsearch {
    hosts => '${ES_HOSTS:elasticsearch:9200}'
    manage_template => false
    index => "gistack_server_log"
        document_type => "gistack_server_log"
  }
}
```
the  redis and the elasticsearch are all running ,ES is cluster mode, but logstash run error.
![image](https://user-images.githubusercontent.com/42507175/129746117-0903b741-43d0-4030-9724-4227561b4748.png)

**Comment by kares** [comment] 2021-08-23 10:59
as the error mentions one of your grok definitions seems to be lacking a closing parenthesis:
this is not a confirmed bug and should not be tagged as so, please use the [forums](https://discuss.elastic.co/) for questions like these.

**Closed by kares** 2021-08-23 10:59 UTC
Labels: bug, status:needs-triage
