### ISSUE TITLE
http-poller plugin add_field doesn't work

### ISSUE THREAD

**Issue by Domi756** [elastic/logstash#6773] opened 2017-03-01 09:17 UTC
When using 'add_field' in the http_poller input plugin of a Logstash configuration, the field is lost when the plugin returns an error on the test URL.

See example input block below.  The Links LINK_1 and LINK_3 for example may return a success (http 200) and the added field 'environment' will be part of the resulting document.
But in a case were LINK_2_DOWN and LINK_3_UNREACHABLE return an error response (http <> 200) then the added field 'environment' is NOT part of the result document.

- Version: 2.4.x, 5.x
- Operating System: Linux
- Config File: (input block of the Logstash configuration file)
input {
        # ITT Polling.
        http_poller {
                urls => {
                        LINK_1  => "http://xxx-it.html"
                        LINK_2_DOWN => "http://xxx-down.html"
                }
                request_timeout => 10
                interval => 300
                codec => plain
                metadata_target => "http_poller_metadata"
                add_field => { "environment" => "I" }
        }
        # UAT Polling.
        http_poller {
                urls => {
                        LINK_3  => "http://xxx-uat.html"
                        LINK_4_UNREACHABLE => "http://xxx-unreachable.html"
                }
                request_timeout => 10
                interval => 300
                codec => plain
                metadata_target => "http_poller_metadata"
                add_field => { "environment" => "A" }
        }
}

**Comment by dekimsey** [comment] 2017-04-12 18:46
We also use `add_field` to include contextual information about the test (stack, environment, application instance, etc). We need the values to show up on error documents as they are used when writing indexes and search queries.

**Comment by jsvd** [comment] 2017-08-04 15:46
closing as duplicate of https://github.com/logstash-plugins/logstash-input-http_poller/issues/77

**Closed by jsvd** 2017-08-04 15:46 UTC
