### ISSUE TITLE
PQ data page with corrupt event length

### ISSUE THREAD

**Issue by danhermann** [elastic/logstash#10184] opened 2018-11-29 20:25 UTC
A user on LS 6.4.2 reports the following error when running `pqrepair`:

    bin/pqrepair /Users/jared/Downloads/queue/main
    Exception in thread "main" java.lang.IllegalArgumentException
      at sun.nio.ch.FileChannelImpl.position(FileChannelImpl.java:278)
      at org.logstash.ackedqueue.PqRepair.recreateCheckpoint(PqRepair.java:139)
      at org.logstash.ackedqueue.PqRepair.fixMissingCheckpoints(PqRepair.java:105)
      at org.logstash.ackedqueue.PqRepair.repair(PqRepair.java:67)
      at org.logstash.ackedqueue.PqRepair.main(PqRepair.java:36)

Upon inspection of the PQ data pages, it appears that there's some kind of corruption for the encoding of event lengths in one of the page files. None of the events appear to be longer than a couple Kb, but the length of one event is encoded as hex `FF FF FF FF` which is deserialized as a negative signed integer resulting in the exception above. This could be the result of a bug in the original persistence of the PQ data.

Edit: The user is running CentOS 7.5 with PQ data on an XFS filesystem.

**Comment by kaisecheng** [comment] 2022-02-08 16:31
Given that we cannot reproduce this issue with the recent Logstasth version, believe it is not an issue anymore, so close it.
If anyone encounters the same behavior, we can reopen.

**Closed by kaisecheng** 2022-02-08 16:31 UTC
Labels: bug, persistent queues, int-shortlist
